ElementsProject/lightning

test/test_onion.py
trivial patch to not repeat sha calculations
=> test_onion.py: drop repeated sha calculation

daemon/invoice.c, daemon/test/test.sh
=> jsonrpc: Fixed `listinvoice` returning broken JSON

bitcoin/script.c, daemon/commit_tx.c, daemon/cryptopkt.c, daemon/db.c, daemon/dns.c, daemon/feechange.c, daemon/invoice.c, daemon/jsonrpc.c, daemon/lightning-cli.c, daemon/log.c, daemon/log.h, daemon/packets.c, daemon/packets.h, daemon/pay.c, daemon/peer.c, daemon/routing.c, daemon/routing.h, daemon/sphinx.c, daemon/timeout.c, state.c, test/test_protocol.c, test/test_state_coverage.c, utils.h
The final result of some (fairly hacky) tests for leaks.  Many of these were once-off, but several were per peer or per json connection.
=> Leak fixes

daemon/feechange.c, daemon/peer.c, daemon/routing.c, daemon/sphinx.c
(Thanks to Jon Griffiths for reporting these!)
=> Pvs studio: various fixes found by running trial version

daemon/peer.c
This is based on the test-speedup branch; only the last two changes are actually for #29
=> Closing unacked htlcs race 29

daemon/chaintopology.c, daemon/jsonrpc.c, daemon/jsonrpc.h, daemon/lightningd.c, daemon/lightningd.h, daemon/peer.c, daemon/peer.h, daemon/test/Makefile, daemon/test/test.sh
Turns out we need some debug infrastructure to test this, and that actually found a bug with restarting.
=> Re-enable anchor timeout

.travis.yml, daemon/test/test-routing
Added simple travis-ci configuration that will build and test branches and pull requests.
Travis CI will probably blacklist us, due to the `bitcoind` dependency, but I had the ban lifted after talking to their support and explaining what we do, I can coordinate with them to do the same here :-)
=> Adding Travis-CI configuration

Makefile, daemon/json.c
But "make check" still fails a-la #94
=> Fix #91 32 bit build

daemon/peer.c
=> json_connect: don't try to double-fail if amount insufficient.

daemon/irc_announce.c
This is a temporary fix until we finish #88.
=> irc: Switched to LFNet.org IRC server

tests/test_lightningd.py, tests/utils.py
In particular, my bitcoind is in /usr/local/bin
=> pytest: don't assume paths of valgrind and bitcoind.

Makefile, ccan/ccan/intmap/LICENSE, ccan/ccan/intmap/_info, ccan/ccan/intmap/intmap.c, ccan/ccan/intmap/intmap.h, ccan/ccan/intmap/test/run-order-smallsize.c, ccan/ccan/intmap/test/run-order.c, ccan/ccan/intmap/test/run-signed-int.c, ccan/ccan/intmap/test/run.c
Opening a separate pull request ahead of the gossip PR in order not to pollute the code review with an already code-reviewed module.
The `update-ccan` target didn't work for me so I added the required module manually.
=> ccan: Added ccan/intmap

tools/generate-wire.py
The wiregen tool was a bit hard to maintain since it was printing all
over the place, mixing template and processing logic. This commit
tears the two apart, externalizes everything that is not a single code
line, and repackages it into templates. Specifically functions are now
their own template and header/implementation files are a template.
Furthermore this simplifies some of the boilerplate of mapping types
to sizes and back again, by extracting them into dicts.
All changes have been verified to produce identical results on the
current wire definitions, except a bit of whitespace changes.
=> gen-wire: Cleanup of the wire generator tool

INSTALL.md
Trivial patch to the INSTALL readme file.
Signed-off-by: Marco Amadori <marco.amadori@gmail.com>
=> INSTALL.md: Add 'install' to apt command examples.

daemon/test/scripts/vars.sh, lightningd/channel/channel.c, lightningd/channel_config.c, lightningd/channel_config.h, lightningd/gossip/gossip.c, lightningd/hsm/hsm.c, lightningd/lightningd.c, lightningd/opening/opening.c, lightningd/opening/opening_wire.csv, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/subd.c, lightningd/subd.h, lightningd/test/Makefile, wire/fromwire.c, wire/wire.h
Various fixes when we switch valgrind on in children.
=> Valgrind subdaemons

tests/utils.py
Running long integration tests could result in `bitcoind` dropping the
connection inbetween calls, and since python-bitcoinlib does not
reconnect and/or retry, all subsequent tests would fail as well. This
patch switches to throwaway connections, each serving just one
request. It's easier than to reach into the bitcoinlib to reconnect
and reauth, but comes with some overhead, but I think it's acceptable
for the few bitcoin calls we actually perform.
=> pytest: Simple wrapper around BitcoinProxy to avoid timeouts

lightningd/peer_control.c, tests/test_lightningd.py, wire/wire_io.c
Stuff I found while working on reconnect... please apply!
=> Misc fixes

INSTALL.md, README.md
Like many I don't read any documentation besides the readme in the
repo, so I thought I could just pull some simple getting started info
into the readme to make it easy for people to get started :-)
=> doc: Updating README

lightningd/channel/channel.c, lightningd/channel/channel_wire.csv, lightningd/daemon_conn.c, lightningd/gossip/gossip.c, lightningd/gossip/gossip_wire.csv, lightningd/gossip_control.c, lightningd/hsm_control.c, lightningd/hsm_control.h, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/new_connection.c, lightningd/opening/opening.c, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/peer_htlcs.c, lightningd/peer_state.h, lightningd/status.c, lightningd/subd.c, lightningd/subd.h, tests/test_lightningd.py, tools/generate-wire.py, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c, wire/wire_sync.c, wire/wire_sync.h
Including a significant refactor which makes things generally simpler.
=> Shutdown support.

lightningd/channel/channel.c, lightningd/channel/channel_wire.csv, lightningd/crypto_sync.c, lightningd/crypto_sync.h, lightningd/cryptomsg.c, lightningd/opening/opening.c, lightningd/opening/opening_wire.csv, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/peer_failed.c, lightningd/peer_htlcs.c, lightningd/test/run-cryptomsg.c, wire/gen_peer_wire_csv, wire/peer_wire.c, wire/peer_wire.h, wire/test/run-peer-wire.c
Now fully meets latest spec, including open flags and funding_locked retransmissions.
=> More cleanups and closing updates

lightningd/sphinx.c, lightningd/sphinx.h
=> sphinx: fix payload amount encoding

lightningd/closing/closing.c, lightningd/closing/closing_wire.csv, lightningd/peer_control.c, lightningd/peer_control.h
This simplifies significantly, as we don't need to remember what we offered.
=> closing: update to match proposal to restart negotiation on reconnect.

lightningd/gossip/gossip.c, tests/test_lightningd.py
There was a race condition that would cause an assertion to segfault if a call to release_peer was interleaved with a fail_peer. The release_peer was making the peer non-local, which was then causing the assertion in fail_peer to fail. Now we just have 3 cases: not found, local, and non-local. The same is now true for the release following a disconnect which was not propagated up to `masterd`.
=>  gossip: Fix a race condition between release_peer and fail_peer

.gitignore, lightningd/lightningd.h, lightningd/options.c, tests/utils.py
=> Cleanup: remove unused IRC flag.

channeld/channel.c, lightningd/peer_control.c
The logic of dispatching the announcement_signatures message was
distributed over several places and daemons. This aims to simplify it
by moving it all into `channeld`, making peer_control only report
announcement depth to `channeld`, which then takes care of the
rest. We also do not reuse the funding_locked tx watcher since it is
easier to just fire off a new watcher with the specific purpose of
waiting for the announcement_depth.
This was causing some flaky tests in the integration testing with eclair.
=> gossip: Simplify announce_signature exchange

channeld/channel.c, lightningd/peer_control.c, wallet/walletrpc.c
Addresses #207 by adding a method to retrieve available funds from the
wallet.
Closes: #207
=> jsonrpc: Add listfunds RPC command

openingd/opening.c
"zero" means all channels, which works, but is overkill.
Fixes: #262
=> openingd: set channel_id on failure messages.

lightningd/chaintopology.c, lightningd/log.c, lightningd/log.h, lightningd/new_connection.c, lightningd/peer_control.c, tests/test_lightningd.py, wallet/wallet.c, wallet/wallet.h
Some logging enhancements along the way...
=> Fix wallet change

lightningd/peer_control.c, tests/test_lightningd.py
This is an alternative solution for #275. I think it is simpler since we are not manipulating the generated messages outside of the appropriate function calls, and don't do hotfixing in place. The downside is of course that it serializes twice instead of an in-place patch.
I ran this with and without the second commit for 25 times, the bug manifested itself once every 4 runs on average without the fix, and did not present itself with it.
=> Fix the node_announcement signature

Makefile, channeld/Makefile, channeld/channel.c, common/Makefile, common/io_debug.c, common/io_debug.h, common/status.c, common/test/test_sphinx.c, common/utils.c, common/utils.h, gossipd/Makefile, gossipd/gossip.c, hsmd/Makefile, hsmd/hsm.c, lightningd/Makefile, lightningd/lightningd.c, lightningd/log.c, lightningd/test/run-find_my_path.c
Didn't find any issues, but worth doing.  At least for dev builds.
=> Extra debugging tests

tools/generate-wire.py
Generalize generate-wire.py python3 path
=> tools/generate-wire.py: generalize python3 path

common/close_tx.c
=> close_tx: make version 1, not version 2.

common/wire_error.c, common/wire_error.h, gossipd/gossip.c, lightningd/subd.h
Christian's feedback of the gossipd/subd rework.
=> Subd rework fallout

channeld/channel.c, channeld/channel_wire.csv, gossipd/routing.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, hsmd/Makefile, hsmd/hsm.c, hsmd/hsm_wire.csv, lightningd/gossip_control.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/test/run-find_my_path.c, tests/test_lightningd.py, tests/utils.py, wallet/db.c, wallet/wallet.c, wallet/wallet_tests.c, wire/fromwire.c
Various simple patches on which the others are based...
=> Misc cleanups

lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/options.h, lightningd/peer_control.c, lightningd/test/run-find_my_path.c, tests/utils.py
These are clearly important!  Just the last patch, the rest is simply #316
=> Color and alias

gossipd/gossip.c
=> gossipd: receive global/local features the right way around

gossipd/gossip.c
954a3990fa0399522eb75de7adc58a40de6ebdd8 had two errors:
1) We created the handoff message *before* we sent the final packet, meaning
that the cryptostate was out-of-sync.
2) We called io_wait() on the output side of a duplex connection: it has
to be io_wait_out().
This time, stress testing for 2 hours revealed no more problems.
=> gossipd: really fix peer handoff.

lightningd/peer_control.c, tests/test_lightningd.py
Travis has been hitting the payment problem intermittantly, can't reproduce here.
Also, reproduced a race which meant lightningd didn't see the "permfail".  Fixed.
=> Test fixes / debugging

tools/generate-wire.py
If a structure foo has a optional fields opt1 and opt2, this creates
towire_foo, towire_foo_opt1 and towire_foo_opt2 (since opt2 implies opt1),
similarly for fromwire_*.
This requires the callers to be updated to call the correct routines (eg.
try fromwire_foo_opt2, then fromwire_foo_opt1, then finally fromwire_foo),
but this is a minimal change to the generation code.
=> Optional field support.

lightningd/peer_control.c
=> jsonrpc: Only print netaddr in getpeers when we know it

channeld/channel.c
We were sending the announcement_signatures as soon as we locally
locked and got the announcement_depth, this doesn't make the channel
usable any sooner and forces the other side to stash the
signature. This defers the announcement_signature until the channel
really is usable.
This is done by adding an additional check for the remote locked
message and adding a trigger on remote lock.
For more about the rationale behind this see cdecker/lightning-integration#8
Fixes #353
=> channel: Defer sending the announcement_signature until both lock

Makefile, tools/generate-wire.py, wire/gen_peer_wire_csv
We don't implement the option, but we update the CSV and generate-wire.py to handle it.
=> option-data-loss-protect: fix generate-wire.py and update.

lightningd/peer_control.c
=> closingd: start with proper maximum fee, not our guesstimate.

onchaind/onchain.c
There were two bugs here.  First, grind_feerate() needs to check the
actual range of feerates, not the same rate over and over!  Secondly,
we need to grind the feerate for the HTLC-success tx, too.
These were masked by the fact that our tests always use the same feerate!
"Untested code is buggy code"
=> onchaind: fix feerate determination.

lightningd/invoice.c, lightningd/invoice.h, tests/test_lightningd.py, wallet/db.c, wallet/wallet.c
OK, so wallet backwards compat might be overkill, but it's fun...
=> Implement invoice expiry

.travis.yml, channeld/channel.c, channeld/full_channel.c, common/close_tx.c, lightningd/peer_htlcs.c
More output from real-live testing against lnd.
=> Fix no wait for revoke and ack on reestablish

lightningd/peer_control.c, tests/test_lightningd.py
Our config -> their CSV delay, their config -> our CSV delay.
Fixes: #395
=> onchaind: fix reversed CSV delays.

lightningd/options.c
Fix for https://github.com/ElementsProject/lightning/issues/381
=> Load defaults for purpose of help.

README.md, closingd/Makefile, contrib/pylightning/lightning/lightning.py, devtools/bolt11-cli.c, onchaind/Makefile, openingd/Makefile, tools/generate-wire.py, tools/mockup.sh
=> Remove trailing whitespace

channeld/channel.c, channeld/test/run-full_channel.c, lightningd/peer_control.c, lightningd/test/run-commit_tx.c
=> Remove redundant code

common/withdraw_tx.c, common/withdraw_tx.h, hsmd/hsm.c, hsmd/hsm_client_wire_csv, tests/test_lightningd.py, wallet/walletrpc.c
Fixes: https://github.com/ElementsProject/lightning/issues/410
=> Support P2SH

tests/test_lightningd.py, wallet/walletrpc.c
Fixes: #428 
Dependent on #422
=> Support BECH32 for withdrawal from wallet

hsmd/hsm.c, tests/test_lightningd.py, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c
Includes fixing some nasty withdrawl signing bugs...
=> Withdraw all

bitcoin/script.c, bitcoin/script.h, common/withdraw_tx.c, lightningd/build_utxos.c, lightningd/build_utxos.h, lightningd/peer_control.c, tests/test_lightningd.py, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c
It'd be nice to check that the txs actually met >= feerate we specified, too...
=> Funding fee calc

common/sphinx.c, doc/lightning-cli.1, doc/lightning-cli.1.txt, tools/generate-wire.py
Fix typos (repeated words, "a" vs. "an")
=> Fix typos (repeated words, "a" vs. "an")

contrib/pylightning/lightning/lightning.py, tools/generate-wire.py
Python fixes:
* Fix access to undefined variable.
* Remove unused imports.
=> Python fixes: Fix access to undefined variable. Remove unused imports.

lightningd/options.c, lightningd/test/run-commit_tx.c
=> Remove duplicate includes

tests/test_lightningd.py
Remove trailing semicolons in Python code.
=> Remove trailing semicolons in Python code

common/wireaddr.c
=> Remove redundant assignments

lightningd/peer_control.c
Pass bool `true` instead of `"true"` to `json_add_bool(..., bool value)`.
=> Pass bool true instead of "true" to json_add_bool(..., bool value)

lightningd/peer_control.c, lightningd/peer_htlcs.c, onchaind/onchain.c, tests/test_lightningd.py, wallet/db.c, wallet/db.h, wallet/test/run-db.c, wallet/test/run-wallet.c, wallet/wallet.c
While I was on the way to implementing watching restoration, I came across these...
=> Various fixes

gossipd/gossip.c
Let me know if I'm missing something but this looks wrong :-) 
Ping @cdecker :-)
=> Remove redundant call to get_connection_by_scid(...)

doc/lightning-waitanyinvoice.7, doc/lightning-waitanyinvoice.7.txt, lightningd/invoice.c, lightningd/invoice.h, tests/test_lightningd.py, wallet/wallet.c, wallet/wallet.h
Dependent on #445 
This is idea of @rustyrussell, to use pay_index in waitanyinvoice.
=> Change interface of waitanyinvoice to use pay_index instead of label

tests/test_lightningd.py
=> Fix typo: "disonnect"

README.md
To save others the pain that I went through :[
=> readme: note about walletbroadcast

Makefile, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, tools/rel.sh
Fixes: https://github.com/ElementsProject/lightning/issues/383
=> Implement "install" and "uninstall" targets for Makefile.

channeld/channel.c, lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/gossip_control.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, tests/test_lightningd.py, wire/fromwire.c, wire/towire.c
Some minor cleanups from the FIXME audit.
=> FIXME sweep

channeld/channel.c, common/json.c, gossipd/gossip.c, gossipd/gossip_wire.csv, gossipd/routing.c, gossipd/routing.h, lightningd/bitcoind.c, lightningd/bitcoind.h, lightningd/gossip_control.c, tests/test_lightningd.py
With some drive-by fixes along the way...
=> Short channel id check

lightningd/invoice.c, lightningd/invoice.h, wallet/wallet.c
Just clarify about why there are two loops in `resolve_invoice`.
=> invoice: Clarify comments about the two loops in resolve_invoice.

doc/lightning-invoice.7, doc/lightning-invoice.7.txt, lightningd/invoice.c, lightningd/invoice.h, lightningd/pay.c, lightningd/peer_htlcs.c, tests/test_lightningd.py, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
=> Implement invoices without an amount (i.e. any-amount invoice)

gossipd/routing.c
This is causing some serious problems with the CI. We defer the `channel_update`s while we are checking the `short_channel_id` against the outpoint in the blockchain. However we have 2 updates for every single channel that need to be deferred. Especially when the outpoint check takes a while (e.g., `valgrind`) it can happen that the single deferral slot is clobbered with both updates, and so we drop the earlier update on the floor.
This PR creates two slots, one for each direction, so we still get at least one good update for either direction, and at least a log entry should we still clobber.
=> gossip: Do not clobber updates attached to a channel announcement

README.md
=> README: Update to latest behavior: we no longer need addfunds command.

common/Makefile, common/features.c, common/features.h, gossipd/Makefile, gossipd/routing.c, gossipd/test/Makefile, lightningd/Makefile, lightningd/gossip_control.c, lightningd/peer_control.c, lightningd/peer_control.h
=> gossipd: check features

README.md, contrib/pylightning/lightning/lightning.py, doc/Makefile, doc/lightning-decodepay.7, doc/lightning-decodepay.7.txt, doc/lightning-delinvoice.7, doc/lightning-delinvoice.7.txt, doc/lightning-getroute.7, doc/lightning-getroute.7.txt, doc/lightning-invoice.7, doc/lightning-invoice.7.txt, doc/lightning-listinvoice.7, doc/lightning-listinvoice.7.txt, doc/lightning-listpayments.7.txt, doc/lightning-pay.7, doc/lightning-pay.7.txt, doc/lightning-waitanyinvoice.7, doc/lightning-waitanyinvoice.7.txt, doc/lightning-waitinvoice.7, doc/lightning-waitinvoice.7.txt, lightningd/invoice.c, lightningd/invoice.h, lightningd/pay.c, lightningd/peer_htlcs.c, tests/benchmark.py, tests/test_lightningd.py, wallet/db.c, wallet/wallet.c, wallet/wallet.h
I wanted to add the msatoshi_received field mentioned in #570 but I ended up doing some cleanups, fixing some docs, writing some man pages... help!
=> JSON invoice cleanups

channeld/channel.c
@jb55 does this indeed fix #592 ?
Thanks!
=> channeld: handle ping instead of crashing when expecting reestablish.

lightningd/peer_control.c, lightningd/peer_control.h, openingd/opening.c, tests/test_lightningd.py, wire/peer_wire.h
=> jsonrpc: Return an error if funding amount is too large

doc/INSTALL.md
=> INSTALL.md: Add `automake` as dependency.

channeld/channel.c, lightningd/bitcoind.c, lightningd/htlc_end.c, lightningd/htlc_end.h, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/pay.c, lightningd/peer_htlcs.c, lightningd/peer_htlcs.h, tests/test_lightningd.py, tests/utils.py, wallet/db.c, wallet/db.h, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
This fixes the issue raised by #588 which is in fact much deeper.  I found an unrelated bitcoind issue during testing, too.
=> Payment persistence

doc/INSTALL.md
Make seems to require python as well as python3.
=> Python is a needed dependency here

lightningd/invoice.c, tests/test_lightningd.py, wallet/db.c, wallet/invoices.c, wallet/wallet.h
=> invoices: Add `paid_timestamp` field.

tests/test_lightningd.py
This was flaky because we didn't wait for the fee update to complete
and were using the old, way too small, fees, which upset bitcoind.
Fixes #669
=> pytest: Fix test_fee_limits

contrib/lightning-cli.bash-completion
this commit adds a file that can be sourced to bash to allow the completion when the tab is pressed in the command line.
=> adding the bash completition script for the client

README.md
See https://github.com/ElementsProject/lightning/commit/5698a133c2b5d38ea287f4604cf089b9a53ac1eb and https://github.com/ElementsProject/lightning/commit/7fdb30cbda9a3e748d1fcca0b89fe8bc3e71d8e9
=> Update CLI commands in README

lightningd/peer_control.c
=> listpeers: print channel configs

channeld/channel.c
=> channeld: don't spam with all our attempts to commit.

README.md, gossipd/gossip.c, lightningd/jsonrpc.c, tests/utils.py
My weekly cleanup backlog:
- Specify that pruned nodes are not fully supported just yet
- Remove binding error from `gossipd`
- Remove jcon connection closed error reporting
- Remove annoying trace from `gossipd`
Fixes 788
Fixes 778
=> Miscellaneous cleanups

bitcoin/chainparams.c, lightningd/options.c
Add "litecoin-testnet" chainparam with litecoin testnet genesis blockhash, port and options.
=> Add litecoin testnet support

lightningd/options.c
There is an interaction between `--ipaddr` and `--port`, namely that the
default port is used when parsing `--ipaddr` if `--port` comes after the
`--ipaddr`, and `--port` is used if it comes before it. Adding a port to
`--ipaddr` still trumps everything else, but this way we correctly set
port in the address.
Fixes #760 
Reported-by: Wladimir J. van der Laan @laanwj
=> opts: Declare --port to be an early arg

common/version.h, lightningd/lightningd.c, lightningd/options.c, lightningd/peer_control.c, tests/test_lightningd.py, tests/utils.py
Make log output texts friendlier to new users.
=> Onboarding: Make log output texts friendlier to new users

lightningd/peer_control.c
Fixes: #818
Make it more detailed and step-by-step to ensure we are computing it correctly.
=> peer_control: Correct roundoff of remote-side msatoshi.

channeld/full_channel.h, common/bolt11.h, common/daemon_conn.c, common/dev_disconnect.c, common/wire_error.h, external/libwally-core/src/secp256k1/src/group.h, external/libwally-core/src/secp256k1/src/group_impl.h, lightningd/chaintopology.c, wallet/wallet.h
Someone has a sticky F key :-)
=> Spelling corrections

README.md
Recently explained on Discord and it helped me alot. Could be useful to add this to the README.md. Did some small adjustments. Credits: Spencer Truman
Closed the previous pull request because of an mistake with my fork. 
https://github.com/ElementsProject/lightning/pull/799
=> Different states explained

lightningd/chaintopology.h, lightningd/options.c, tests/test_lightningd.py
* update references to sat/kb to sat/kw
* remove stray semicolons in python tests
=> Fix references to sat/kb feerates

lightningd/bitcoind.c, lightningd/bitcoind.h, lightningd/options.c
Might help alleviate some of the issues of having to run a full-node
on the same machine as `lightningd`.
=> cli: Add rpcuser, rpcpassword and rpcconnect to bitcoind

contrib/pylightning/README.md, contrib/pylightning/lightning/lightning.py, contrib/pylightning/setup.py, tests/test_lightningd.py
This PR add all the current lightningd available RPC commands to the LightningRpc object.
Also increase package minor version.
=> Update pylightning with current lightningd RPC commands

channeld/Makefile, channeld/channel.c, closingd/Makefile, closingd/closing.c, common/Makefile, common/read_peer_msg.c, common/read_peer_msg.h, openingd/Makefile, openingd/opening.c
This is my attempt to make a common helper; it's not perfect, but it *is* a code reduction.
=> Read peer msg common

gossipd/routing.c
We use this technique for the other tags, so use it here too.
This was drawn to my attention when I made more than 10 channels in a
block, and the string changed length:
Valgrind error file: valgrind-errors.31415
==31415== Conditional jump or move depends on uninitialised value(s)
==31415==    at 0x4C35E20: bcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31415==    by 0x11A624: queue_broadcast (broadcast.c:40)
==31415==    by 0x118D93: handle_pending_cannouncement (routing.c:704)
==31415==    by 0x1109E3: handle_txout_reply (gossip.c:1796)
==31415==    by 0x111177: recv_req (gossip.c:1955)
==31415==    by 0x136723: next_plan (io.c:59)
==31415==    by 0x137220: do_plan (io.c:387)
==31415==    by 0x13725E: io_ready (io.c:397)
==31415==    by 0x138B97: io_loop (poll.c:305) …
=> routing: use marshalled short_channel_id, not string as tag for channel_announce

tests/test_lightningd.py, tests/utils.py
These changes fix a couple of issues / inconveniences I encountered when trying to run the test suite on my system. Feel free to merge, cherry-pick, ignore, or suggest improvements.
=> A couple of changes to make the test suite more robust

bitcoin/tx.c
If no witnesses are present on any inputs, then extended serialisation should not be used.
Signed-off-by: Jon Griffiths <jon_p_griffiths@yahoo.com>
=> push_tx: Don't create BIP 144 invalid transactions

common/configdir.c
short oneliner as rustyrussel suggested
=> allow --rpc-file option to change default value

README.md, lightningd/options.c
* add docs about configuration file
* update max-locktime-blocks description to be accurate (I think... let me know if this is not correct)
Fixes: https://github.com/ElementsProject/lightning/issues/382
=> Configuration File Documentation

bitcoin/tx.c, bitcoin/tx.h, lightningd/peer_control.c, onchaind/onchain.c
Reported-by: Jon Griffiths @jgriffiths 
Then fixed-by: @jgriffiths
=> Fix weight calculation, rename cost->weight.

channeld/channel.c
=> channel: Plug minor leaks.

bitcoin/tx.c
When a serialized length refers to an array of structures, the trivial
DOS prevention can be out by a factor of sizeof(serialized struct). Use
the size of the serialized structure as a multiplier to prevent this.
Transaction inputs are the motivating example, where the check is out by
a factor of ~40.
=> pull_length: Take structure size into account when checking max

gossipd/gossip.c, gossipd/gossip_wire.csv, gossipd/routing.c, gossipd/routing.h, lightningd/gossip_control.c, lightningd/pay.c
=> Recover from unparseable routing failure

lightningd/peer_control.c
`activate_peer` does little more than wiring up some txwatches and
asking `gossipd` to reconnect to the peer. If the peer manages to
reconnect before we activate then we would crash.
This just changes the `assert` causing the crash into a conditional
whether we need to reconnect or not.
Fixes #713
=> master: Don't crash if peer reconnects before we activate it

bitcoin/script.c, channeld/channel_wire.csv, common/htlc_state.h, doc/lightning-pay.7, doc/lightning-pay.7.txt, doc/lightning-sendpay.7, doc/lightning-sendpay.7.txt, lightningd/netaddress.c, lightningd/peer_control.c, onchaind/onchain.c, onchaind/onchain_wire.csv, onchaind/onchain_wire.h, test/test_protocol.c, test/test_state_coverage.c, tests/test_lightningd.py, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
=> Fix a-vs-an typos

lightningd/jsonrpc_errors.h, wallet/wallet.h
Fix two recently introduced typos.
=> Fix two recently introduced typos

common/json.c, common/json.h, doc/lightning-pay.7, doc/lightning-pay.7.txt, lightningd/pay.c
=> Add fee limit to `pay` command

wallet/walletrpc.c
Just some drive-by cleanups that didn't fit anywhere else :wink:
=> Weekly cleanups

wallet/walletrpc.c
This caused a bit of confusion for our testers, when funding a channel
the funds are no longer available and listed in `lisfunds`, causing
them to believe funds to have disappeared. This PR adds funds that are
allocated to channels in the `listfunds` output, together with some
info about the channel, to make sure this doesn't happen again.
=> JSON-RPC: Add funds in channels to `listfunds`

lightningd/gossip_control.c
Just some minor things that were suggested during review.
=> gossip: Fix up some comments on PR #955

doc/lightning-cli.1, doc/lightning-cli.1.txt, doc/lightning-pay.7, doc/lightning-pay.7.txt
=> doc: Mention keyword arguments, update pay to mention use of null.

lightningd/jsonrpc.c
=> JSON-RPC: Fix unquoted error string when parser fails

.travis.yml
The `!` outside of parentheses was being cut by travis.
=> travis: Correctly process $SOURCE_CHECK_ONLY.

contrib/pylightning/lightning/lightning.py, tests/test_lightningd.py
I'd like to get #884 merged, however I can't amend the PR without @gdassori allowing us to push to his branch, so I took the liberty of cherry-picking his branch and fixing it up to address the feedback given in the original PR.
Ping @gdassori 
Closes #884
=> pylightning: Implement dict based API client (update from #884)

contrib/pylightning/lightning/lightning.py
Trivial changes to make the code pythonic
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
=> pylightning: make flake8 happy

Makefile, ccan/README, ccan/ccan/daemonize/LICENSE, ccan/ccan/daemonize/_info, ccan/ccan/daemonize/daemonize.c, ccan/ccan/daemonize/daemonize.h, ccan/ccan/daemonize/test/run.c, ccan/ccan/tal/path/path.c, ccan/ccan/tal/path/path.h, lightningd/chaintopology.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c
This is what  @gabridome wants I think...
=> Implement daemon mode

lightningd/jsonrpc.c, lightningd/jsonrpc.h, tests/test_lightningd.py
Closes: #1007 
(On top of #994)
=> JSON nonblocking

common/bolt11.c
The bolt11 specification requires that the version number of the Fallback on-chain address be 5 bits wide instead of 8 bits.
To test this I:
1. modified my local repo to accept a p2pkh fallback address at the end of the "invoice" command.
2. create an invoice
3. use "decodepay" on the bolt11 string
Before this change, decodepay would fail because it doesn't read the right version number of the address.
If there is another way to test the encoding of the fallback address, please do let me know :-).
If we want to add fallback address to the list of args accepted by the "invoice" command, I could help with that too.
=> lightningd: encode fallback address in 5 bits

lightningd/peer_control.c, tests/test_lightningd.py
=> peer_control: Support xxx@yyy:zzz form for connecting.

wallet/wallet.c
Check return value of `sqlite3_step(stmt)`.
=> Check return value of sqlite3_step(stmt)

lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c
=> Add option to specify pid file

lightningd/subd.c
We need to do a more complex dance if stdin was important.
Fixes: #1016
=> subd: handle stdin being closed (eg. --daemon).

gossipd/routing.c, lightningd/bitcoind.c, lightningd/chaintopology.c, lightningd/dev_ping.c, lightningd/gossip_control.c, lightningd/jsonrpc.c, lightningd/pay.c, lightningd/payalgo.c
Remove redundant casts to same type.
=> Remove redundant casts to same type

lightningd/dev_ping.c, tests/test_lightningd.py
It's a dev command, but still.
Fixes: #985
=> dev_ping: don't crash with silly values.

channeld/channel.c, closingd/closing.c, gossipd/routing.c, hsmd/hsm.c, lightningd/chaintopology.c, lightningd/channel.c, lightningd/channel.h, lightningd/htlc_end.c, lightningd/log.c, lightningd/log.h, lightningd/onchain_control.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, lightningd/watch.c, lightningd/watch.h, onchaind/onchain.c, test/test_protocol.c, wallet/test/run-db.c, wallet/test/run-wallet.c, wallet/wallet.c
Remove unused function arguments.
=> Remove unused function arguments

tests/benchmark.py, tests/test_lightningd.py, tests/utils.py, tools/generate-wire.py
Make Python code conform to the Python PEP 8 style guide.
=> Make Python code conform to the Python PEP 8 style guide

gossipd/gossip.c, lightningd/lightningd.h, lightningd/options.c
=> Add --no-listen option to disable listening for incoming connections

wallet/walletrpc.c
=> wallet: Fix an off by one error in dev-listaddrs

Makefile, tests/benchmark.py, tests/test_lightningd.py, tests/utils.py
Add `make check-python` (`flake8` check).
=> Add "make check-python" (flake8 check)

lightningd/lightningd.c, lightningd/test/run-find_my_path.c, wallet/db.c, wallet/db.h, wallet/test/run-wallet.c
=> lightningd: close and reopen db across fork for daemonize

external/Makefile
=> Only make clean external submodules if Makefile present

gossipd/gossip.c, gossipd/handshake.c, gossipd/routing.c, gossipd/routing.h
This is preamble work to the lifetime rework: mainly stuff I saw as I was going along.  The final one is an actual bugfix though.  Getting these out the way makes the next PR simpler.
Thanks!
=> Minor gossip cleanups

lightningd/payalgo.c
Fixes: #1136 
@hkjn , please see this!
=> payalgo: Throttle pay command if failure is due to blockheight disagreement

cli/lightning-cli.c, tests/test_lightningd.py
The display format is now:
<pre>
command1
description1
command2
description2
.
.
.
</pre>
=> Improved display of lightning-cli help for humans

contrib/Dockerfile.builder.fedora
The Fedora distro version of Dockerfile.builder
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
=> contrib: Add Dockerfile.builder.fedora

lightningd/bitcoind.c
Improve onboarding experience by handling common failure scenarios for new users more gracefully.
Improve usability in these scenarios:
* `bitcoin-cli` not available in `PATH` and/or `bitcoind` not installed
* `bitcoin-cli` available in `PATH` but `bitcoind` is not running
Before this commit (scenario: `bitcoin-cli` not available in PATH and/or `bitcoind` not installed):
```
$ lightningd/lightningd
bitcoin-cli exec failed: No such file or directory
Aborted (core dumped)
```
After this commit (scenario: `bitcoin-cli` not available in PATH and/or `bitcoind` not installed):
```
$ lightningd/lightningd
bitcoin-cli not found. Is bitcoin-cli (part of Bitcoin Core) available in your PATH?
Make sure you have bitcoind running and that bitcoin-cli is able to connect to bitcoind.
You can verify that …
```
=> Improve onboarding experience by handling common failure scenarios for new users more gracefully

common/test/run-sphinx.c, devtools/Makefile, devtools/onion.c
It also gave me the opportunity to retest the test vectors in the spec, and against the `lnd` tool.
Fixes #503
=> Fix the onion tool

lightningd/gossip_control.c
that permits to list one single node or channel.
=> help: listnodes and listchannels,have optional arg

bitcoin/shadouble.c, channeld/channel.c, common/read_peer_msg.c, common/status.c, common/type_to_string.h, gossipd/gossip.c, gossipd/routing.c, gossipd/routing.h, gossipd/test/run-bench-find_route.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, wire/peer_wire.c, wire/peer_wire.h
I've been working on trying to test the gossip enhancements proposed, and it requires some more infrastructure around features and gossip messages.
In particular, we'll be relaying more messages for gossipd, so that needs to be enhanced: we've currently been ignoring errors when we should have been closing connections according to the spec.
=> Gossip enhance prework

doc/Makefile, doc/lightning-autocleaninvoice.7.txt, doc/lightning-delexpiredinvoice.7, doc/lightning-delexpiredinvoice.7.txt, doc/lightning-delinvoice.7, doc/lightning-delinvoice.7.txt, lightningd/invoice.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/test/run-find_my_path.c, tests/test_lightningd.py, wallet/invoices.c, wallet/invoices.h, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
Fixes: #711 
Not quite merge-ready yet --- want to add tests, please wait...
=> invoices: Add delexpiredinvoice command.

doc/INSTALL.md
build: update INSTALL.md to include Fedora #1028 
doc: Add TOC to INSTALL.md 
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
=> Documentation

doc/INSTALL.md
Also, technically, the name of the current version of the OS is macOS, so I
updated it.
=> Added link to macOS in install index.

lightningd/peer_control.c, lightningd/peer_htlcs.c, wallet/db.c, wallet/wallet.c, wallet/wallet.h
=> wallet: Track some channel usage statistics.

common/subdaemon.c, lightningd/log.c
Use correct type field for signed integers in format strings.
=> Use correct type field for signed integers in format strings

bitcoin/base58.c, bitcoin/base58.h, bitcoin/locktime.c, bitcoin/locktime.h, bitcoin/script.c, bitcoin/script.h, bitcoin/signature.c, bitcoin/signature.h, cli/lightning-cli.c, common/bolt11.c, common/bolt11.h, common/json.c, common/json.h, lightningd/opt_time.c, lightningd/opt_time.h, wallet/wallet.c, wallet/wallet.h, wire/peer_wire.c, wire/peer_wire.h
Remove unused functions not covered by tests.
**Note to reviewers:** I'm sure we want to keep a subset of these around for consistency (preferably with the addition of one test per unused function). Let me know which we want to keep and I'll revert the removal of these.
=> Remove unused functions not covered by tests

onchaind/onchain.c
=> onchain: print exactly what we were doing if we fail in grind_feerate.

channeld/channeld_htlc.h, common/htlc.h, common/json_escaped.c, common/json_escaped.h, lightningd/channel.h
Remove unused functions not covered by tests (round 2).
**Note to reviewers:** It could be the case that we want to keep a subset of these around for consistency (preferably with the addition of one test per unused function). Let me know which we want to keep and I'll revert the removal of these.
=> Remove unused functions not covered by unit tests

doc/lightning-invoice.7, doc/lightning-invoice.7.txt, lightningd/invoice.c, tests/test_lightningd.py
=> invoice: allow numeric labels again.

tests/test_lightningd.py
Just two things I noticed while doing other stuff. One should get us slightly more robust results when testing  and the other was failing my CI builds.
=> Drive-by fixes

lightningd/channel.c, lightningd/channel.h, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, wallet/db.c, wallet/wallet.c
So we know how much counterparty could theoretically steal from us
(msatoshi_to_us - msatoshi_to_us_min) and how much we could
theoretically steal from counterparty (msatoshi_to_us_max -
msatoshi_to_us).
For more piloting goodness.
=> wallet: Add msatoshi_to_us_min and msatoshi_to_us_max statistics for channels

tests/test_lightningd.py, tests/utils.py
This allows us to have some default options that can then be overridden easily
on a per-test basis. Ran into this while writing a test that was trying to set
`--locktime-blocks`, but was overridden by the defaults due to CLI precedence.
=> pytest: Use a dict to pass options to lightningd

lightningd/chaintopology.c, wallet/wallet.c
There are two very hard problems in software engineering:
1. Off-by-one errors
In this case we were rolling back further than needed and we were starting the
catchup one block further than expected.
=> topology: Two off-by-one error when catching up with the blockchain

lightningd/closing_control.c
=> closing_control: Fix loop limit in better_closing_fee.

gossipd/Makefile, gossipd/gossip.c, gossipd/gossip_store.c, gossipd/gossip_store.csv, gossipd/gossip_store.h, gossipd/gossip_wire.csv, gossipd/routing.c, gossipd/routing.h, gossipd/test/run-bench-find_route.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, lightningd/gossip_control.c
Technically this "fixes" #1341 but we still need the root cause.
=> gossipd: improve diag for the weird announce duplicate, make store more robust

tests/test_lightningd.py, wallet/walletrpc.c
Fixes: #1400 
Eventually. For now we have a failing test confirming the bug report.
=> Fix listfunds output address

Makefile, channeld/channel.c, channeld/channel_wire.csv, closingd/closing.c, closingd/closing_wire.csv, gossipd/gossip.c, gossipd/gossip_wire.csv, lightningd/channel.c, lightningd/channel_control.c, lightningd/channel_control.h, lightningd/closing_control.c, lightningd/closing_control.h, lightningd/gossip_control.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/opening_control.c, lightningd/opening_control.h, lightningd/peer_control.c, lightningd/peer_control.h, tests/test_lightningd.py, tests/utils.py, wallet/test/run-wallet.c
This contains some of the simpler fixes which crept into the ongoing permconnect (#1322) which is taking far too long.  Let's make sure these pass CI and get reviewed, while I work on that one.
=> Misc test fixes

contrib/pylightning/lightning/lightning.py, doc/lightning-invoice.7, doc/lightning-invoice.7.txt, lightningd/invoice.c, tests/test_lightningd.py
=> invoice: Support providing preimage when making invoice.

common/Makefile, common/bech32_util.c, common/bech32_util.h, common/bolt11.c, common/test/run-bolt11.c, common/wireaddr.c, common/wireaddr.h, devtools/Makefile, gossipd/Makefile, gossipd/gossip.c, lightningd/Makefile
=> Use the DNS Seed to locate nodes that we can't find otherwise

lightningd/invoice.c, tests/test_lightningd.py, wallet/invoices.c, wallet/invoices.h, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
=> invoice: Check duplicate preimage when explicitly sprcified.

doc/lightning-close.7, doc/lightning-close.7.txt, lightningd/json.c, lightningd/json.h, lightningd/peer_control.c, tests/test_lightningd.py, wallet/test/run-wallet.c
=> Use channel id for `close` parameter

Makefile, cli/lightning-cli.c, common/configdir.c, hsmd/hsm.c, hsmd/hsm_client_wire_csv, lightningd/hsm_control.c, lightningd/hsm_control.h, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/options.h, lightningd/test/run-find_my_path.c, tests/test_lightningd.py, tests/utils.py
These are mainly pulled from #1413 which we might not be doing, plus one which @practicalswift might want to review (the last one).
=> More cleanups

README.md, contrib/Dockerfile.builder.fedora, doc/INSTALL.md
Fixes #1451 
Reported-by: Perlover <@Perlover>
=> doc: Remove libsodium-dev dependency, it's in-tree

contrib/Dockerfile.builder, contrib/Dockerfile.builder.i386
These were spamming the logs and making the log view almost unusable.
Forgot I had this laying around, and it got dropped in the latest push to the docker hub, I'll regenerate them once this is merged in.
=> travis: Fix the locale in the builder images

channeld/channel.c
Our closingd doesn't handle it:
lightningd(2968): 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 chan #1:
Peer permanent failure in CLOSINGD_SIGEXCHANGE: lightning_closingd: sent ERROR Expected closing_signed:
0103ff54517293892ec3f214f2343c54cbfbf24aa6ffb8d5585d3bc1b543eae0a272000067000001000146390e0c043c777226927eacd2186a03f064e4bdc30f891cb6e4990af49967d34b338755e99d728987e3d49227815e17f3ab40092434a59e33548e870071176d26d19a4e4d8f7715c13ac2d6bf3238608a1ccf9afd91f774d84d170d9edddebf7460c54d49bd6cd81410bc3eeeba2b7278b1b5f7e748d77d793f31086847d582
=> channeld: don't send ANNOUNCEMENT_SIGNATURES if we've send shutdown.

channeld/channel.c, gossipd/broadcast.c, gossipd/broadcast.h, gossipd/gossip.c, gossipd/gossip_wire.csv, gossipd/routing.c, gossipd/routing.h, gossipd/test/run-bench-find_route.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, lightningd/gossip_control.c, lightningd/gossip_msg.c, lightningd/gossip_msg.h, tests/utils.py
... and a tweak I've had sitting around for ages which helps speed my debug cycles :)
=> Unannounced channel fix

common/wireaddr.c, common/wireaddr.h, gossipd/gossip.c, gossipd/tor.c, gossipd/tor.h, lightningd/connect_control.c, lightningd/json.c, lightningd/options.c, wallet/wallet.c
How's this @Saibato ?  Works for me; basically after all the cleanups the actual patch to implement it is pretty short.
=> Tor/socks cleanups and hostname support.

doc/TOR.md
Signed-off-by: Saibato <saibato.naga@protonmail.com>
=> reflect latest option changes in master to TOR.md

gossipd/broadcast.c, gossipd/broadcast.h, gossipd/gossip.c, gossipd/gossip_store.c, gossipd/gossip_store.h, gossipd/routing.c, gossipd/test/run-bench-find_route.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c
Compacts the `gossip_store` if we have more than 100 messages and 10% stale.
=> Implement gossip_store compactions

configure
=> configure: Check for version of pytest

Makefile, doc/release-notes/release-0.6.md
Written by Christian Decker wth feedback from Shannon Appelcline.
Special thanks to Fabrice Drouin of ACINQ fame for choosing the release
name!
=> Release notes for 0.6 "I Accidentally The Smart Contract"

bitcoin/Makefile, bitcoin/feerate.h, lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/peer_control.c, onchaind/onchain.c, onchaind/onchain_types.h, onchaind/test/run-grind_feerate.c, tests/test_lightningd.py, tests/utils.py, wallet/test/run-wallet.c
Now fixed to work with 0.16.1 and master as well.   Obviously the first change is needed before release, but I'd like the rest too, so we don't get weird test breakage when 0.16.2 is released.
=> tests: fix to work with bitcoind master branch.

Makefile
Places everything under opt/clightning, as per LSB.
=> Makefile: add bin-tarball rule to produce clightning-<version>-<distro>.tar.xz

Makefile
Just a small fix to make it work again.
=> ncc: we need to set variables like CC in a different way.

contrib/Dockerfile.builder, contrib/Dockerfile.builder.i386
Remove duplicate line in docker file:
```
libsqlite3-dev \
libgmp-dev \
libsqlite3-dev \
```
=> remove duplicate line

Makefile, ccan/README, ccan/ccan/timer/_info, ccan/ccan/timer/timer.c, ccan/ccan/utf8/LICENSE, ccan/ccan/utf8/_info, ccan/ccan/utf8/test/run-decode.c, ccan/ccan/utf8/test/run-encode-decode.c, ccan/ccan/utf8/test/run-encode.c, ccan/ccan/utf8/utf8.c, ccan/ccan/utf8/utf8.h, common/Makefile, common/decode_short_channel_ids.c, common/decode_short_channel_ids.h, devtools/Makefile, devtools/decodemsg.c, devtools/print_wire.c, devtools/print_wire.h, gossipd/Makefile, gossipd/gossip.c, tools/generate-wire.py
In particular, we need further decoding of some fields: alias, addresses and encoded_short_ids.
=> Improve the output of decodemsg.

doc/lightningd-config.5, doc/lightningd-config.5.txt, gossipd/gossip.c, lightningd/options.c, tests/test_gossip.py, tests/utils.py
Plus a drive-by --bind-addr fix.
=> Disallow multiple addresses of same type

cli/lightning-cli.c
It may not immediately obvious that this is available
=> cli: add manpage hint at the end of human help output

lightningd/chaintopology.c
Implements an EWMA for the fee estimation. Achieves 90% influence of the newer
fee after 5 minutes, and adjusts to the polling rate that is configured.
I'm not completely set on the parameters yet, the 5 minutes comes from 1/2 block
interval, and it has one downside, namely that we'll be adjusting the fees forever
(actually until we drop below the single-satoshi precision). We could change the
parameters, and implement a more coarse-grained cut-off point.
Let the :bike: :house: begin :-)
Fixes #750
Fixes #1622
Closes #1637
Partially solves #1529
=> bitcoind: Smooth fee changes over a number of estimates

wallet/wallet.c
There is evidence that this message can be confusing[1].
Suggest a way to resolve the error in the message.
[1] https://www.reddit.com/r/Bitcoin/comments/7ybcq9/programming_how_can_i_resolve_the_below_error/
=> wallet: fix up semi-cryptic wallet error message

channeld/channel.c, closingd/closing.c, common/read_peer_msg.c, common/read_peer_msg.h, gossipd/gossip.c, gossipd/gossip_wire.csv, gossipd/routing.c, gossipd/routing.h, lightningd/gossip_msg.c, lightningd/gossip_msg.h, lightningd/peer_control.c, openingd/opening.c, tests/test_lightningd.py
I had these lying around; I'm cleaning up my branches so I figured it was time to push them.
=> listpeers enhancements and suppress duplicates

contrib/pylightning/lightning/lightning.py
All getroute parameter could be used from python.
=> pylightning: add missing arguments to getroute

lightningd/params.c, lightningd/params.h, lightningd/test/run-params.c
We want this feature before #1682. Nicely implemented by @rustyrussell.
=> Param with defaults

doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c
#1526 Custom path for config file
=>  add --conf parameter

lightningd/Makefile, lightningd/param.c, lightningd/param.h, lightningd/test/run-param.c
=> param: renamed files

tests/test_lightningd.py
I saw an error in test_gossip_weirdalias in Travis, where listnodes(nodeid)
returned *BOTH* nodes; it happened to fail because [0] was the wrong one, but
it would have passed if the order had been different.
This helper asserts that we really do only have one element, and should
catch such bugs faster.
=> pytest: only_one() helper to catch if RPC returns more elements than expected

.gitignore
run-param and run-derive_basepoints
=> Added recently created unit tests to .gitignore

lightningd/peer_control.c
=> lightningd: fix crash on listpeers.

devtools/Makefile
=> fix: make devtools-clean

Makefile
The man5 section wasn't being added in the Makefile.
=> Add lightningd-config(5) to install

lightningd/chaintopology.c
Fixes problem of unrealistic feerate smoothing at startup when a call to `get_feerate` happened before any _actual_ feerate poll.
Fixes most of #1698
Uses variable `topo->startup` because it seemed available
Will test on my `mainnet` node when it is finished syncing.
=> at startup initialize smoothed feerate to polled feerate

lightningd/watch.c
did not find anything in the coding style which would require the use of goto therefor I thought it can be exchanged with a `do {...} while()` statement
=> exchanged code containing goto with a do while loop

doc/HACKING.md, tests/requirements.txt
Looks like this was out of date
=> doc: update python test requirements in HACKING

common/json.c, common/json.h, lightningd/jsonrpc.c, lightningd/param.c, lightningd/pay.c
Added `json_tok_sha256` and converted `json_tok_tok` over in a few places.
=> Added json_tok_sha256

wallet/db.c
Return `true` or `false` from `sqlite3_bind_*` based on result from SQLite instead of always returning `true`.
=> Return true or false from sqlite3_bind_* based on result from SQLite instead of always returning true

channeld/commit_tx.c, gossipd/gossip.c
=> Remove dead stores

common/test/run-sphinx.c
Don't advertise features we don't have in `run-sphinx`.
=> Don't advertise features we don't have in run-sphinx

lightningd/options.c
This gives the network options a chance to load from arguments before usage
exits, so that the proper defaults are shown.
This didn't work before:
lightningd --mainnet --help
It showed testnet defaults, now it shows mainnet defaults.
Fixes #1554
=> lightningd: show selected network defaults in usage

closingd/closing.c, gossipd/gossip.c
Remove unused function parameters.
=> Remove unused function parameters

common/wireaddr.c
Make sure we're not using uninitialized values.
=> Make sure we're not using uninitialized values

contrib/Dockerfile.builder.fedora
=> contrib: Dockerfile.builder.fedora bump fedora release

CHANGELOG.md, gossipd/routing.c, lightningd/gossip_msg.c, tests/test_lightningd.py
A funny thing happened on the way to fixing other random stuff...
(Untested code is buggy code!!)
=> Address fixes

lightningd/opening_control.c, openingd/opening.c, openingd/opening_wire.csv, tests/test_lightningd.py, tests/utils.py
Gálli Zoltán (@gallizoltan) sent an email bug report following up on his Medium post (https://medium.com/coinmonks/how-to-spend-all-funds-from-a-lightning-channel-44eded09a6dc).
Thanks!
=> Fix channel reserve enforcement

CHANGELOG.md, channeld/Makefile, channeld/channel.c, common/crypto_sync.c, common/crypto_sync.h, connectd/connect.c, contrib/pylightning/lightning/lightning.py, lightningd/Makefile, lightningd/channel.c, lightningd/channel.h, lightningd/channel_control.c, lightningd/channel_control.h, lightningd/connect_control.c, lightningd/peer_htlcs.c, lightningd/ping.c, tests/test_gossip.py, tests/test_misc.py, wallet/test/run-wallet.c
A collection of random network things to make us faster and more reliable, basically.  And the compulsory random code driveby cleanup :)
It's on top of #1799 
Fixes #1487
=> Networking enhancements.

connectd/connect.c, tests/test_connection.py
=> Fix connect crash

Dockerfile
* Update public signing key location
For more information check: 
https://github.com/sgerrand/alpine-pkg-glibc/blob/master/README.md#please-note
=> fix: issue:1848 - Docker Image is not building:

gossipd/gossip.c
Lightning charge tests stopped working without a timeout, being unable
to find a route.  The 15 second delay doesn't matter in real life, but
in these scenarios it does.  This fixes it by making sure the channel
is usable immediately.
=> gossipd: don't delay the very first channel_update.

contrib/short_channel_id-to-txid.sh
I use this to look up on smartbit.com.au to see if a channel is spent, for example.
=> contrib/short_channel_id-to-txid.sh: simple mapping util.

lightningd/bitcoind.c, tests/test_connection.py, tests/test_misc.py, tests/utils.py
These are the test infrastructure patches from #1846.
Please apply, even if the bitcoin-cli stuff gets rewritten later.
=> Pytest tweaks

channeld/channel.c, channeld/channel_wire.csv, lightningd/peer_htlcs.c, tests/test_connection.py
Travis found this for #1846 but that's just because we send feerate adjustments more.
=> Reconnect after feerate bad sig fix

CHANGELOG.md, contrib/pylightning/lightning/lightning.py, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/channel_control.c, lightningd/closing_control.c, lightningd/opening_control.c, lightningd/options.c, lightningd/peer_control.c, lightningd/peer_control.h, tests/test_closing.py, tests/test_connection.py, tests/test_misc.py, tests/utils.py
This is the final (and less critical) part of the original mega-feerate PR #1846 
It was entitled i-dream-of-feerate after I woke up thinking about feerates and how we should be handling it.  I had no idea how much work there was to do on this neglected corner of the code until the bug report which triggered #1836 ...
=> Feerate enhancements: cleanups, `feerate` command and wider min-max tolerances.

CHANGELOG.md, Makefile
Reordered CHANGELOG.md, and added names and credits for all versions.
=> v0.6.1-rc1

doc/lightning-listinvoices.7, doc/lightning-listinvoices.7.txt
=> changed formatting for better readability on github

lightningd/gossip_control.c
Fix-up peerid name references in all JSON rpc.
=> Fixup reference to peer-id in JSON rpc

gossipd/gossip_wire.csv, gossipd/gossipd.c, lightningd/Makefile, lightningd/gossip_control.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/ping.c, lightningd/ping.h
We would never complete further ping commands if we had < responses
than pings.  Oops.
Fixes: #1928
=> ping: complete JSON RPC ping commands even if one ping gets no response.

connectd/tor_autoservice.c
Fixes #1939
Signed-off-by: Saibato <Saibato.naga@pm.me>
=> set the tor autoservice port also in struct wireaddr

devtools/.gitignore, devtools/Makefile, devtools/decodemsg.c, devtools/gossipwith.c, gossipd/gossip_store.c, gossipd/gossip_store.h, gossipd/routing.c, gossipd/routing.h, tests/test_gossip.py, wallet/wallet.c
Dragging in `gossipfrom` (now `gossipwith`) is a hack, but it's hard to test this without writing significant new infrastructure...
=> Don't accept announcements for recently-closed channels.

CHANGELOG.md, channeld/channeld.c, channeld/full_channel.c, common/bolt11.c, common/decode_short_channel_ids.c, common/memleak.c, common/msg_queue.c, common/utils.h, connectd/connectd.c, gossipd/gossipd.c, gossipd/routing.c, lightningd/bitcoind.c, lightningd/chaintopology.c, lightningd/channel_control.c, lightningd/invoice.c, lightningd/lightningd.c, lightningd/options.c, lightningd/param.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, onchaind/onchaind.c, tests/test_invoices.py, tests/utils.py, tools/check-bolt.c, wallet/db.c, wallet/test/run-wallet.c, wallet/txfilter.c, wallet/wallet.c
For routeboost testing (#1982), I wanted these, but they're really unrelated.
A "misc crap" PR like this is terrible practice, but separating them also leads to rebase hell...
=> Misc updates

CHANGELOG.md, gossipd/gossipd.c
Things one notices while perusing the code...
=> Gossip query fixes

tests/test_misc.py
Seems we simply were too quick to check for effects.
=> pytest: Stabilize test_feerates

CHANGELOG.md, common/features.h, gossipd/gossip_wire.csv, gossipd/gossipd.c, gossipd/routing.c, gossipd/routing.h, lightningd/gossip_msg.c, lightningd/gossip_msg.h, lightningd/options.c
More reading, more fixing...
We really should test the `riskfactor` parameter, but at least this is better than "1"!
=> OMG even more gossip fixes

cli/lightning-cli.c, lightningd/jsonrpc.c
* Fallback to help rpc when manpage is not found
* Simplify json help response
Fixes #1882
=> cli: help improvements

tests/requirements.txt
It looks like this is a new dependency.
Sort the list while we're at it.
=> python: add cheroot to requirements.txt

lightningd/peer_htlcs.c
This is the source of failure in the test_restart_many_payments stress
test: we don't commit the outgoing HTLC immediately, instead waiting for
gossip to tell us the peer for the outgoing channel, then waiting for
that channeld to tell is it's committed.  The result was incoming HTLCs
with no outgoing.
I initially pushed the HTLCs through that same path, but of course
(since peers are not connected yet!) the only result was that we failed
these HTLCs immediately.  So I chose the far simpler course of just
failing them directly.
To reproduce this, I had to increase the test_restart_many_payments
num to 10, and run it with nice -20 taskset -c 0.
=> lightningd: fail HTLCs which are in-transit as we shut down.

CHANGELOG.md
We all need to add this to our mental checklist of PR review I think...
=> Missing changelog entries

Makefile, ccan/README, ccan/ccan/crypto/shachain/tools/Makefile, ccan/ccan/crypto/shachain/tools/shachain48.c, ccan/ccan/htable/_info, ccan/ccan/htable/htable.c, ccan/ccan/htable/htable.h, ccan/ccan/io/io.c, ccan/ccan/io/io.h, ccan/ccan/io/test/run-45-eof.c, ccan/ccan/membuf/LICENSE, ccan/ccan/membuf/_info, ccan/ccan/membuf/membuf.c, ccan/ccan/membuf/membuf.h, ccan/ccan/membuf/test/run.c, ccan/ccan/rbuf/_info, ccan/ccan/rbuf/rbuf.c, ccan/ccan/rbuf/rbuf.h, ccan/ccan/rbuf/test/run-all.c, ccan/ccan/rbuf/test/run-open.c, ccan/ccan/rbuf/test/run-partial-read.c, ccan/ccan/rbuf/test/run-term-eof.c, ccan/ccan/rbuf/test/run.c, ccan/ccan/structeq/structeq.h, ccan/ccan/structeq/test/compile_fail-unexpected-negative-padding.c, ccan/ccan/structeq/test/run-with-unknown-padding.c, connectd/connectd.c, connectd/tor_autoservice.c, tests/test_connection.py
We tend to randomly get "Cryptographic handshake: Operation now in progress." when weuse the wrong key.
=> Better handshake fail msg

lightningd/peer_control.c, tests/test_pay.py
Just my weekly cleanups :wink:
=> Minor cleanups

contrib/pylightning/lightning/lightning.py, doc/lightning-sendpay.7, doc/lightning-sendpay.7.txt
pylightning and the documentation are both out-of-step.
Thanks to @darosior for the report (via PR #2046)
=> Fix sendpay usage

CHANGELOG.md
Actual tag needs to be made after this is merged/rebased.
=> CHANGELOG: tag 0.6.2-rc1.

.travis.yml, Makefile, tests/test_closing.py, tests/test_connection.py, tests/test_gossip.py, tests/test_misc.py, tests/test_pay.py, tests/utils.py
This is what happens when I upgrade my OS...
=> Random updates

channeld/channeld.c, common/daemon.c, common/daemon_conn.c, common/daemon_conn.h, common/msg_queue.c, common/msg_queue.h, connectd/connectd.c, gossipd/gossipd.c, hsmd/hsmd.c, lightningd/subd.c, lightningd/subd.h
This is more tal-idiomatic IMHO.  Though it means an extra allocation at startup time, I think it adds clarity.
=> make daemon_conn and msg_queue tal objects

contrib/pylightning/lightning/lightning.py, lightningd/payalgo.c
Just a tiny rephrasing :wink: 
Fixes #2078
=> docs: Mention that msatoshi on pay is not optional, but ignored

CHANGELOG.md, contrib/pylightning/lightning/lightning.py, lightningd/jsonrpc.c, tests/test_misc.py
It started with travis hanging on this occasionally, and it ended with a thing of beauty!*
\* May be in the eye of the beholden...
=> Fix multirpc for real

lightningd/options.c, tests/test_misc.py, tests/utils.py
=> read config file before change working dir

doc/lightningd-config.5, doc/lightningd-config.5.txt
Reported-by: Greg Sanders @instagibbs 
=> doc: make it clearer that specifying addr etc disables autolisten.

CHANGELOG.md
Fixes: 3f420dc408af2ec862ef886e069ea9f6e017275b
=> CHANGELOG: update to mention new getinfo fields.

doc/plugins.md
=> emphasized that a plugin needs to be executable

lightningd/plugin.c
The transparent passthrough that was recently introduced would end up
causing phantom quotes to appear around IDs when one of them was a
string. This happened for example when using `lightning-cli`, the code
would copy the quotes from the original request, insert our u64 ID,
and then re-add them on the way back as well.
=> plugin: Fix an issue with string IDs ending up quoted twice

.github/CODEOWNERS, common/json_tok.h, common/param.h
No functionality changes. Just some miscellaneous updates.
Added myself as code owner of what I originally wrote or heavily modified (in the case of json stuff).
Added `LAST_ARG_NULL` compiler attribute to `param()`.
=> param cleanups and misc

ccan/README, ccan/ccan/pipecmd/test/run-preserve.c, ccan/ccan/tal/tal.c, ccan/ccan/tal/tal.h, ccan/ccan/tal/test/run-take-free-assert.c, ccan/ccan/tal/test/run-take.c
And add the missing unit test from my previous update.
=> ccan: update to latest version, which includes more take() checks.

lightningd/options.c
=> opts: Fix crossed wires in autocleaninvoice options

.gitignore
Add
```
.tmp.lightningrfc 
tools/headerversions
```
=> Git: ignore .tmp.lightningrfc  and tools/headerversions

doc/INSTALL.md
=> update raspberry cross build doc

doc/Makefile, doc/lightning-listchannels.7, doc/lightning-listchannels.7.txt
Continuation of work on issue #1360
Resubmitting pull request after accidentally closing #2197.  This request contains changes suggested by @cdecker
=> Manpage for lightning-listchannels created

CHANGELOG.md, configure, doc/PLUGINS.md, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, tests/fixtures.py, tests/test_plugin.py, tests/utils.py
=> Plugin restore

lightningd/plugin.c
Fixes #2253 and also seems relatively harmless.
=> Skip README.md when reading in plugins dir

Makefile
=> plugins: install pay plugin when 'make install'

.travis.yml
=> travis: fix cache directories syntax

ccan/README, ccan/ccan/pipecmd/pipecmd.c, ccan/tools/configurator/configurator.c
=> Update CCAN to pull in pipecmd fix

CHANGELOG.md, Makefile, contrib/plugins/helloworld.py, contrib/pylightning/lightning/lightning.py, contrib/pylightning/lightning/plugin.py, doc/PLUGINS.md, lightningd/jsonrpc.c, lightningd/jsonrpc.h, lightningd/lightningd.c, lightningd/memdump.c, lightningd/memdump.h, lightningd/plugin.c, lightningd/plugin.h, lightningd/test/run-find_my_abspath.c, lightningd/test/run-jsonrpc.c, plugins/libplugin.c, tests/test_misc.py, tests/test_plugin.py, wallet/walletrpc.c
This gathered some fixes along the way too...
See also: #2308
=> Plugin params passthru

CHANGELOG.md, configure, doc/INSTALL.md, external/Makefile, tools/build-release.sh, tools/check-setup_locale.sh
I am working on a simple reproducible build script, at least for ubuntu 18.04 LTS.  These cleanups make things simpler.
=> Use external libraries and neaten release

doc/lightning-getroute.7, doc/lightning-getroute.7.txt
Realized this change was unsaved when it turned up in an unrelated branch!
=> doc: update getroute manpage in line with last commit.

CHANGELOG.md, doc/MAKING-RELEASES.md, tools/repro-build.sh
Updates changelog, adds repro script for testing with rc1.  Will tag rc1 after this merge.
=> Prep for rc1

contrib/pylightning/lightning/lightning.py, contrib/pylightning/lightning/plugin.py, lightningd/plugin.c, tests/plugins/millisatoshis.py, tests/test_plugin.py
This is what happens when I get a spare 30 minutes and decide to write a simple 'rusty' plugin: a day spent learning more Python!
=> pylightning plugin cleanups

tools/build-release.sh
Please test by checking out this commit and doing:
./tools/build-release.sh --force-version=v0.7.0rc2 --force-mtime=2019-02-23 zipfile
The resulting `release/clightning-v0.7.0rc2.zip` should have sha256sum ~`d5842ca0e3f38ccaf3a16db5ac92af78c3b482bb43a6c57258876c0d666803f9`~
3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip
=> build-release.sh: fix zipfile determinism.

CHANGELOG.md, doc/MAKING-RELEASES.md, tools/build-release.sh, tools/repro-build.sh
And fix trivial typo in MAKING-RELEASES.md
=> Update CHANGELOG.md for -rc2.

README.md
Fixes: #2401
Reported-by: @stevenroose
=> README.md: update link from listpayments to listpays.

CHANGELOG.md
Side note: it's also a birthday, this is not the 0.7 release name :)
=> CHANGELOG.md: update for rc3.

doc/REPRODUCIBLE.md
The final commit contains instructions, but to reproduce the results listed there you need to use the ~PREVIOUS~ rc1 commit!
You can find my results and working at https://ozlabs.org/~rusty/clightning-repro
=> doc/REPRODUCIBLE.md: how to make a reproducible zipfile and Ubuntu build.

doc/lightning-getroute.7, doc/lightning-getroute.7.txt
=> doc: fill in parameters in getroute manpage.

CHANGELOG.md, tools/build-release.sh
=> CHANGELOG.md: v0.7.0

contrib/linuxarm32v7.Dockerfile
#2418 left out the fix on the arm build
=> Installing the Pay plugin in Dockerfile for arm32v7

connectd/connectd.c
=> Increase TCP socket backlog.

gossipd/test/run-bench-find_route.c
Reported-by: @cdecker
Fixes: #2440
=> test: fix thinko in gossipd/test/run-bench-find_route.c

contrib/pylightning/lightning/__init__.py, contrib/pylightning/lightning/lightning.py, contrib/pylightning/lightning/plugin.py, contrib/pylightning/setup.py, tests/plugins/utf8.py, tests/test_plugin.py
I enhanced my summry plugin to use UTF-8 for drawing bars, but it gets mangled into \uxxxx.  Fixing this took all morning, and you won't like the final patch, but I'm pretty sick of Python right now...
=> UTF-8 Passthough

common/amount.c, common/amount.h, doc/lightning-setchannelfee.7, doc/lightning-setchannelfee.7.txt, lightningd/peer_control.c
@m-schmoock I've added you to collaborators so I can assign review duties to you in future!  Congratulations, I think!
=> setchannelfee slight cleanup

doc/lightning-setchannelfee.7, doc/lightning-setchannelfee.7.txt, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/peer_control.c, tests/test_pay.py
based ontop of PR #2342 
Will give an option to use the `setchannelfee` command to update `all` channels at once.
Adds feature, doc and test.
=> setchannelfee for 'all' channels

tests/test_pay.py
gossipd in l1 might not have registered l2 reconnecting, thus considering
the channel local-disabled.
=> pytest: fix flaky test_setchannel_fee_restart test.

doc/TOR.md
Some cleanup of the tor doc file.
=> Cleanup tor doc

Makefile, channeld/channeld.c, channeld/commit_tx.c, channeld/full_channel.c, common/htlc_tx.c, common/initial_commit_tx.c, lightningd/peer_htlcs.c, wire/gen_onion_wire_csv
Mainly typo fixes, but we removed the INCORRECT_PAYMENT_AMOUNT error
altogether.
=> Documentation: Update to BOLT v1.0.

connectd/connectd.c, tests/test_misc.py
Stuff I ran across in my boltathon tutorial prep...
=> local socket fixes

devtools/create-gossipstore.c
=> Fix gossipstore build issues on gcc 7.4.0

contrib/startup_regtest.sh
small script to make setting up and tearing down a local/manual test environment a lot easier.
tries to be pretty idempotent, but it's definitely possible to get into a whack state with this.
=> Add a contrib script that makes it easier to test locally

gossipd/routing.c, gossipd/routing.h
fix `/* FIXME: Make this a htable! */` !
Change the pending_cannouncement (in `struct node`) from `struct list_head pending_cannouncement;` to `struct pending_cannouncement_map *pending_cannouncements;`
=> gossipd: change the pending_cannouncement list to htable

tools/generate-wire.py
Found a few bugs while debugging @rustyrussell's [`fun-with-tlvs`](https://github.com/rustyrussell/lightning-rfc/commits/fun-with-tlvs) branch.
=> Wire generator fixes

devtools/create-gossipstore.c
=> correct format long long unsigned int on 32bits linux

.gitignore, contrib/plugins/helloworld.py, tests/fixtures.py, tests/test_plugin.py
- gitignore some more generated artifacts
- Directory cleanups should not fail if setup already fails
- Remove `autopatch` arg from example plugin
- Pix the flaky `connect_hook`-test
Fixes #2604
=> Just some minor cleanups

tests/utils.py
For performance reasons we start the lightningd instances in
parallel. However, if we only assign the numeric ids (used for log-prefixes
and home directories) when we are already running in parallel, we are not
guaranteed to get the numeric ids matching the return value of `get_nodes` or
`line_graph`. With this patch we now select numeric ids before parallelizing
the start.
=> pytest: Ensure lightningd instances have the correct numeric ids

gossipd/routing.c
This `if` is repeated with the code above.
=> Gossipd: cleanup extra repeated code

doc/lightning-listfunds.7, doc/lightning-listfunds.7.txt
Some fields were returning values as msat while being described as returning values in sat. Also added a short description to some utxo fields and ordered them.
=> Update 'listfunds' doc and manpage

bitcoin/base58.c, bitcoin/base58.h, contrib/pylightning/lightning/plugin.py, contrib/pylightning/tests/test_plugin.py, devtools/bolt11-cli.c, lightningd/invoice.c, lightningd/jsonrpc.c, wallet/invoices.c, wallet/walletrpc.c
Just the usual cleanup collection. The one stands out is the pylightning fix where I removed the hand-woven binding and now just fallback on python's own binding logic. This should make optional argument handling work again.
=> Some driveby cleanups

contrib/pylightning/lightning/lightning.py
This PR orders alphabetically the RPC command methods in the LightningRpc class, and then add the missing ones.
=> Pylightning: reorder LightningRpc methods and add missing ones

gossipd/gossipd.c
=> gossipd: fix listnodes crash on non existing id

doc/lightning-waitsendpay.7, doc/lightning-waitsendpay.7.txt
=> Doc: update 'waitsendpay' manpage

lightningd/jsonrpc.c
The command list is easier to read when sorted.
=> Rpc: sort help output by command name

Makefile, doc/PLUGINS.md, lightningd/invoice.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/plugin.c, plugins/Makefile, plugins/autoclean.c, plugins/libplugin.c, plugins/libplugin.h, plugins/pay.c, wallet/invoices.c, wallet/wallet.c
First change was because I was really surprised at the empty string for missing options; I don't think it will break anyone to change that.
Closes: #2445 
We could move delinvoices out too, but one thing at a time; this is purely cosmetic, really.
=> Autoclean is now a plugin

CHANGELOG.md, doc/lightning-pay.7, doc/lightning-pay.7.txt, plugins/pay.c, tests/test_misc.py, tests/test_pay.py
Still have to fix the bad JSON problems, but that's a bigger effort.
=> Pay api fixes

contrib/pylightning/lightning/lightning.py, contrib/pylightning/tests/test_units.py
I reduced PR #2630 to just contain a reduced version of `to_approx_str`  and its testcase.
So you can quickly make a decision :D
=> Feat: msat to_approx_str

plugins/.gitignore, plugins/Makefile
=> Add plugin autoclean objs

devtools/decode-iolog, lightningd/json_stream.c, lightningd/json_stream.h, lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_hook.c
This is three levels deep of yak-shaving...
=> Plugin I/O logging

CHANGELOG.md, plugins/pay.c
=> plugins/pay.c: add curly braces arround JSON data field

wallet/txfilter.c
I was bumping against some blocksync performance issues with 12k+ keys, 24k+
scriptpubkeys being checked against, and migrating that list to a hashset is
an easy fix to shave off 99% of the time to process a block.
=> txfilter: Migrate the list of owned scriptPubKeys into a hashset

CHANGELOG.md
=> CHANGELOG.md: v0.7.1rc2

gossipd/gossip_store.c, gossipd/routing.c, gossipd/routing.h, tests/test_gossip.py
After the previous gossip_store bugs, @jb55 produced another one.  It's a corner case where the store is in a bad state due to truncation, but good to fix.  I also added extra tests for other similar cases!
=> Truncated gossip store fixes

CHANGELOG.md
=> CHANGELOG.md: note the db_write hook and listtransactions command.

common/gossip_store.c
This happened on Travis, and the gossip_store was a suspicious 4096
bytes long.  This implies they're using some non-atomic filesystem
(gossipd always does atomic writes to gossip_store), but if they are,
others surely are too.
=> common/gossip_store: handle short reads.

contrib/pylightning/lightning/lightning.py, wallet/walletrpc.c
Also add the method to pylightning for convenience and consistency.
=>  bugfix: Proper json for listtransactions' response

CHANGELOG.md
This has definitely reinforced that we need shorter release cycles!
=> v0.7.1rc5.

contrib/pylightning/lightning/plugin.py
The command description taken from the docstring is pretty handy as a default, but one might want to use it otherwise. This also adds the possibility to specify a long description.
=> Pylightning: allow to set description and long description manually

tests/plugins/hold_htlcs.py, tests/test_plugin.py
We were having a few issues with malformed data in the past, so this time we
really check that stuff.
=> pytest: Strengthen the htlc_accepted tests

lightningd/chaintopology.c
=> Log_info on broadcasting error

CHANGELOG.md
It was pointed out in #2816 that a CHANGELOG entry was missing.
=> docs: add entry to CHANGELOG about signet addition

lightningd/bitcoind.c
At the moment we simply get a crypto log line on exit:
bitcoin-cli getblockchaininfo: invalid response
Fixes: 6deed77d88944af253ce142277d40fa050d341cd
=> lightningd: fix fatal error on startup if bitcoind isn't ready.

devtools/Makefile, devtools/print_wire.h, tools/gen/impl_template, tools/gen/print_header_template, tools/gen/print_impl_template, tools/generate-wire.py, tools/test/test_cases, wire/Makefile, wire/wire.h
More adventures in gossip tlv.
This lets us parse https://github.com/lightningnetwork/lightning-rfc/pull/557#issuecomment-515346187 and generate correct code!
=> TLV generation fixes

CHANGELOG.md, cli/lightning-cli.c, cli/test/run-large-input.c, common/json.c, common/json.h, common/test/run-json_remove.c, doc/PLUGINS.md, lightningd/jsonrpc.c
I've wanted this for at least two plugins: `summary` and `helpme`, which are much more viewable with -H.  We already hard-code `help` so this seems a nice extension to have.
Happy to bikeshed over the names!
=> JSON RPC format hint

gossipd/routing.c
Hey, turns out this @m-schmoock was *not* due to some ancient curse!
=> gossipd: fix crash when we prune old, un-updated channel announcements.

lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_control.c, tests/plugins/slow_init.py, tests/test_plugin.py
Several corner cases I hit in practice.
=> lightningd: fix two crashes in plugin controller

Makefile
Only effects developers, but that's me :)
=> Fix update mocks

common/sphinx.c
- Fix build fail on 32-bit environment.
=> Fix build fail on 32bit environment.

common/wallet_tx.c, devtools/mkcommit.c, devtools/mkfunding.c, wallet/wallet.c
Two small tweaks to `mkfunding` / `mkcommit` tools. Also a fix for counting the segwit marker + flag toward the weight total when calculating fees (weight of 2).
=> Small Fixes

gossipd/gossip_store.c
We always know the length, so we don't need it.  It causes much extra work
when we want to delete a record, which I suspect may cause issues amongst
some users who've been seeing gossip_store corruption.
=> gossipd: don't use O_APPEND on the gossip_store.

lightningd/memdump.c
Since we are walking the entire allocation tree anyway, and access the tal
metadata anyway, we can just as well also track the size of the memory
allocations to simplify debugging of memory use.
=> json-rpc: Add size and cumulative size to dev-memdump

CHANGELOG.md, common/read_peer_msg.c, openingd/openingd.c
=> wire: always ignore unknown odd messages.

lightningd/notification.h, wallet/test/run-wallet.c
This broke `make update-mocks && make`.
=> lightningd/notification: Add missing includes for 'forward_event'

Makefile, README.md, doc/INSTALL.md
=> Correct version regex in Makefile, add git as dependency

gossipd/gossip_store.c
We ignored this before, which meant that the DEVELOPER-mode check that we
delete the correct record didn't check that it wasn't already deleted.
@m-schmoock has been running this for a week with no problems, so it's safe.
=> gossipd: check that we don't try to access a deleted gossip entry.

README.md
=> Bikeshedding on top of #2870

contrib/linuxarm64v8.Dockerfile
This is boring code, mostly repeating what is already in arm32 build.
The notable difference is that I needed to bump sqlite version because their autoconf on older version was not supporting arm64.
=> Add docker ARM64 support

Dockerfile
Signed-off-by: Cryptcoin Junkey <cryptcoin.junkey@gmail.com>
=> Enable to build the docker image (ElementsProject#2941).

contrib/linuxarm32v7.Dockerfile
This just match the amd64 and arm64 docker
=> [Docker] Fixing the environment variable for arm32

devtools/gossipwith.c, lightningd/bitcoind.c, lightningd/gossip_control.c, tests/test_gossip.py
This tickles two separate bugs.  I'll look at actually fixing them in about 4 hours.
See: #2968
=> Gossip announce problems

CHANGELOG.md
(Last-minute build fixes, all Rusty's fault!)
=> v0.7.2.1: Nakamoto's Pre-approval by US Congress

Makefile, configure, tools/Makefile, tools/test/Makefile
=> Makefile cleanup

lightningd/subd.c
We currently end up sleeping for 1 second for channeld and gossipd:
better to use a normal blocking waitpid and an alarm to wake us in
case they don't exit.
This speeds up `lightning-cli stop` on my machine from 2.008s to 0.008s:
a 286 times speedup!
=> json: speed up shutdown.

lightningd/plugin.c, tests/plugins/dblog.py, tests/plugins/slow_init.py, tests/test_plugin.py
Discovered while working on #2988
=> lightningd/plugin: fix plugins->startup member at lightning startup

Makefile, contrib/bootstrap-node.sh, contrib/startup_regtest.sh, doc/Makefile, tests/fixtures.py, tests/plugins/forward_payment_status.py, tests/test_closing.py, tests/test_db.py, tests/test_misc.py, tests/test_plugin.py, tests/utils.py, tools/Makefile
I'm testing a GCP 24x machine to replace travis, and it's revealed some flaky tests.  This branch is the fixes needed to make it reliable.
=> Test fixes for big machines

doc/Makefile, doc/index.rst
=> docs: Add the title of the manpage to TOC and sort alphabetically

README.md, contrib/Dockerfile.builder, contrib/Dockerfile.builder.i386, doc/INSTALL.md
This fixes broken links in the README and update installation instructions.
=> Minor fixes for markodwn manpages

lightningd/lightningd.c, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/peer_htlcs.c, lightningd/peer_htlcs.h, lightningd/test/run-find_my_abspath.c, lightningd/test/run-invoice-select-inchan.c, tests/plugins/hold_htlcs.py, tests/test_plugin.py, wallet/test/run-wallet.c
=> Call htlc accepted on startup after plugin init

doc/INSTALL.md
add install instruction; this way help docs get installed correctly!
=> docs: add install line

lightningd/plugin.c
Based on #3016, which does the work of adding a nice memleak helper hook we can use to fix this unrelated false positive.
=> Fix plugincmd memleak

CHANGELOG.md, Dockerfile, contrib/linuxarm32v7.Dockerfile, contrib/linuxarm64v8.Dockerfile, doc/INSTALL.md
Also adds a CHANGELOG line, as we did for `mako`.
=> doc: Document the new 'gettext' dependency (and add to docker files)

common/wireaddr.c, connectd/connectd.c
=> connectd: correct a segfault in add_seed_addrs

common/test/run-ip_port_parsing.c, common/wireaddr.c
=> Some more fixes in wireaddr

lightningd/channel_control.c
Subtle, but this should fix it.
=> Fix cancel channel crash

doc/PLUGINS.md
I was disturbed by the mix of tabs and spaces in these JSON snippets, so I reformatted everything. To not be biased by my own JSON-formatting preferences I ran all snippets through [jq](https://stedolan.github.io/jq/) (defaults) so hopefully everybody would approve the result.
=> format Plugin docs JSON snippets with jq.

gossipd/routing.c
Happened under Travis with --dev-fast-gossip (90 second prune time), but can
happen anyway if gossip is almost 2 weeks old when we receive it:
2019-09-20T19:16:51.367Z DEBUG lightning_gossipd(20972): Received node_announcement for node 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59
2019-09-20T19:16:51.376Z DEBUG lightning_gossipd(20972): Ignoring node_announcement timestamp 1569006918 for 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59
2019-09-20T19:16:51.669Z **BROKEN** lightning_gossipd(20972): pending node_announcement 01013094af771d60f4de69bb39ce045e4edf4a06fe6c80078dfa4fab58ab5617d6ad4fa34b6d3437380db0a8293cea348bbc77f714ef71fcd8515bfc82336667441f00005d852546022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59022d2253494c454e5441525 …
=> gossipd: fix corner case where gossip msg too old after pending delay.

connectd/tor_autoservice.c
Show the hidden onion service created by autotor in info log
=> Show in info log the name of the hidden onion service

common/test/run-ip_port_parsing.c, common/wireaddr.c, common/wireaddr.h, connectd/connectd.c
As per https://github.com/ElementsProject/lightning/pull/3058#pullrequestreview-288417100 : #3058 was merged because it patched the bug but it was quite dirty. This cleans up.
=> Tidy up parse_wireaddr_from_hostname

devtools/Makefile, devtools/checkchannels.c
Tool to check if channels are invalid, re: CVE-2019-12998
=> checkchannels tool.

lightningd/options.c
=> If tor V2/V3 addr used in startup cmdline don't fail

bitcoin/script.c, bitcoin/script.h, bitcoin/tx.c, bitcoin/varint.c, bitcoin/varint.h, common/json_helpers.c, common/json_helpers.h, common/json_tok.c, common/json_tok.h, common/test/run-param.c, contrib/startup_regtest.sh, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, openingd/openingd.c, tools/gen/header_template, tools/gen/impl_template, tools/generate-wire.py, tools/test/enum.h, tools/test/test_cases, wallet/test/run-wallet.c, wallet/walletrpc.c
Bunch of small things that came up while working on the dual-funding implementation.
=> Prep work for dual-funding branch (I of IV)

CHANGELOG.md
Forgot to add it in https://github.com/ElementsProject/lightning/pull/3123
=> Add a changelog line about behavior change on gossip_queries response

CHANGELOG.md
=> Tor CHANGELOG updates for 0.7.3

CHANGELOG.md
=> changelog: update to rc2

configure
=> configure: fix libsodium issues

gossipd/routing.c, gossipd/test/run-bench-find_route.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, gossipd/test/run-overlong.c, gossipd/test/run-txout_failure.c, tests/test_pay.py
1. memleak false positive,
2. bad gossip in test_pay_direct.
=> Test flakiness fixes

CHANGELOG.md
=> We're doing an RC3

configure
=> configure: fix FreeBSD which has sqlite3 in /usr/local

contrib/pylightning/lightning-pay, contrib/pylightning/lightning/lightning.py
I went ahead to try to fix https://github.com/ElementsProject/lightning/issues/3119, but actually I don't think it should be fixed on our end. Here are anyway some drive-by cleanups.
=> Pylightning cleanups

CHANGELOG.md
=> CHANGELOG.md: reset to Unreleased.

doc/MAKING-RELEASES.md
Updates `MAKING-RELEASES.md`, using things learned from this release process.
=> Release Process Note Updates

lightningd/bitcoind.c
It's less helpful, sure, but it's far better than someone
sending me their output and leaking this information.
Fixes: #3242
Reported-by: @JavierRSobrino
=> lightningd: obscure sensitive bitcoin args when bitcoind unreachable.

channeld/full_channel.c, tests/test_connection.py
As found by random breakage on Travis on #3221 !
=> Fix bad htlc add during reconnect

common/sphinx.c
Found these while manually verifying #3259
=> TLV Onion Fixes

gossipd/seeker.c
=> gossipd: don't crash if we have > 7000 stale short_channel_ids.

tools/gen/impl_template
=> TLV wire generation fixes

openingd/openingd.c, wallet/Makefile
Funny things which happened on the way to Base AMP :)
Changelog-None
=> Two minor fixes

tests/requirements.txt, tests/test_pay.py
Various updates, but overall this avoids the annoying deprecation warnings.
Changelog-None
=> Update test requirements

contrib/pyln-testing/pyln/testing/utils.py
This adds a `announce_channel` to `fund_channel` and slightly optimizes RPC usage in `wait_channel_active`.
Changelog-None
=> improve pyln a bit

channeld/channeld.c, common/sphinx.c, common/sphinx.h, contrib/pyln-testing/pyln/testing/fixtures.py, contrib/pyln-testing/pyln/testing/utils.py, devtools/onion.c, lightningd/pay.c, lightningd/peer_htlcs.c, tests/test_closing.py, tests/test_gossip.py, tests/test_misc.py, tests/test_pay.py, tests/test_wallet.py, wallet/test/run-wallet.c
My weekly cleanup PR, focused on pytest and elements compatibility. Some tests accidentally broke, so I had to parametrize them. Also the "Some node exited with a non-zero return code" was annoying since it gave absolutely no indication as to which node and what the return code was.
Changelog-None
=> Minor test cleanups

doc/lightningd-config.5, doc/lightningd-config.5.md
And `make doc-all` also updated `addr` doc.
Changelog-None
=> doc/lightningd-config: misc corrections

lightningd/peer_htlcs.c
Because my node runs under valgrind, it can take quite a while to
sync; nodes tend to disconnect and reconnect if you block too long.
This is particularly problematic since we often update fees: when the
other side sends its commitment_signed we block.
In particular, this triggers the corner case we have where we
update_fee twice, disconnecting each time, and our state machine gets
confused (which is why we never saw this exact corner case before this
change in 0.7.3!).
Changelog-None
=> lightningd: don't always defer commitment_signed if we're not synced.

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyln/client/lightning.py, devtools/changelog.py, wallet/db_common.h
=> Pre-release changes for 0.8.0-rc1

CHANGELOG.md
Just filling in the changes since rc1 :wink: 
Changelog-None
=> changelog: Update the changelog for 0.8.0rc2

doc/HACKING.md
The sqlite database location has been changed in aab83e72.
Changelog-None
=> doc: fix the path to the sqlite database file

contrib/pyln-client/pyln/client/lightning.py, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md, lightningd/opening_control.c, plugins/fundchannel.c, tests/test_connection.py
it's that time of year (merry xmas!) :santa: :mrs_claus: 
enables the ability to push_msat on fundchannel (and fundchannel_start)
=> funding: enable push_msat

doc/INSTALL.md, doc/lightningd-config.5, doc/lightningd-config.5.md
* INSTALL.md: FreeBSD
* lightningd-config: log-level 
Changelog-None
=> small documentation enhancement and correction

channeld/channeld.c, common/test/run-param.c, common/wallet_tx.c, connectd/tor_autoservice.c, contrib/plugins/fail/failtimeout.py, doc/HACKING.md, doc/lightning-listpeers.7, doc/lightning-listpeers.7.md, lightningd/bitcoind.c, lightningd/channel_control.c, lightningd/opening_control.c, lightningd/options.c, lightningd/peer_htlcs.c, lightningd/plugin.c, plugins/README.md, plugins/libplugin.c, tests/test_closing.py, wallet/test/run-wallet.c, wallet/wallet.c, wallet/walletrpc.c
Fix some typos, style, wording and comments.
Grouped in one PR as opening a separate PR for each one would be too noisy.
=> Minor fixups here and there

connectd/tor.c
For example:
"Tor connect out for host example.com error: 4 "
becomes:
"Error connecting to example.com: Tor server reply: host unreachable"
Also clarify the error:
"Connected out for example.com error"
to:
"Connected out for example.com error: authentication required"
because the only reason it could have failed is that the Tor socks5
server did not like any of our proposed auth methods and we only
proposed "no auth".
=> connectd: translate socks5 errors to human strings

.travis.yml, .travis/build.sh
Add arm32v7/arm64v8 cross build and unit test to travis-ci
Changelog-None
=> add arm32v7/arm64v8 unit test to travis-ci

common/sphinx.c, common/sphinx.h, lightningd/pay.c, tests/test_pay.py
=> Check that the createonion arguments don't exceed the onion payload size

lightningd/plugin.c, tests/test_closing.py, tests/test_connection.py, tests/test_gossip.py, tests/test_invoices.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py, tests/test_wallet.py
Just the drive-by fixups from #3400
Changelog-None
=> Misc fixups

doc/INSTALL.md
A double `git` and a `mode`.
Changelog-None
=> small typos in doc/INSTALL.md

doc/index.rst
It kept being updated as I `make`d.
Changelog-None
=> doc: update readthedocs index

doc/TOR.md
=> doc/TOR.md: Mention about `statictor`.

.editorconfig
Add .editorconfig to make it easier to obey style
=> Add .editorconfig to make it easier to obey style

channeld/channel_wire.csv, channeld/channeld.c, common/sphinx.c, common/sphinx.h, lightningd/channel_control.c, lightningd/options.c, lightningd/pay.c, lightningd/peer_htlcs.c, tests/test_misc.py
While cleaning up our handling of HTLC failures, I found a few bugs in the code.
Changelog-None
=> More malformed cleanups

doc/lightning-listpeers.7, doc/lightning-listpeers.7.md
ChangeLog-Fixed: Corrected and expanded `lightning-listpeers.7` documentation.
=> doc/lightning-listpeers.7.md: Expand and correct.

CHANGELOG.md
Changelog-None
^ That's a lie, FWIW.
=> CHANGELOG.md: v0.8.1rc2
