ElementsProject/lightning

contrib/pylightning/lightning/lightning.py
Removes `seed` and adds `maxhops`
=> pylightning: update getroute() parameters

Dockerfile, contrib/linuxarm32v7.Dockerfile
All Tini does is spawn a single child (Tini is meant to be run in a container), and wait for it to exit all the while reaping zombies and performing signal forwarding. (See [github](https://github.com/krallin/tini))
This is especially useful as by default Bash running in PID 1 does not forward SIGTERM to child processes.
Luckliy, we use `exec` which mean the signal is directly reaching `lightningd`. However, if the PID is 1, the program need to explicitly handle SIGTERM. (which we did recently, and it works great)
However, lightning might not properly reap zombie processes.
Also, if `EXPOSE_TCP` is used, we are spawning `socat` and running lightningd at the same time without using `exec`, meaning that lightningd will not receive SIGTERM.
=> Use tini as docker entrypoint

common/amount.c
run-commit_tx error on 32 bit os.
```
run-commit_tx: channeld/test/run-commit_tx.c:914: main: Assertion `tal_count(newtx->output) != tal_count(tx->output)' failed.
```
=> correct tx_fee in 32bit system

gossipd/gossip_wire.csv, tools/generate-wire.py
Turns out we now have more than `UINT16_MAX` channels to return, and we were just overflowing that field.
Fixes #2504
=> Do not overflow the u16 num_channels field in the gossip_getchannels_reply message

lightningd/options.c
This change should allow for plugin options to be included in the config file, currently it crashes, this patch ignores options not known by lightningd on the "early" pass, allowing plugins to be registered with options and use them on the second pass.  It will still crash on unknown options that are not part of lightningd known options or plugin registered options.
=> allow plugin opts in config

doc/TOR.md
Case 5 in the Tor documentation currently states that if you use `--bind-addr=autotor:127.0.0.1:9051`, you can get your onion address by running `lightning-cli getinfo`. I have not found that to be the case; with that flag no onion address will be generated at all.
On the other hand, if `--addr=autotor:127.0.0.1:9051` is used instead, an onion address is generated and `lightning-cli getinfo` behaves as the docs say.
This PR simply changes the Tor docs to reflect the above.
=> Clean Up Case #5 in Tor Documentation

lightningd/plugin.c
If a plugin fails to pass in a default value for an option,
c-lightning crashes. this fixes the crash.
Patches #2515
=> plugins: patch in empty string when no default given

gossipd/routing.c, gossipd/routing.h
If we asked `bitcoind` for a txout and it failed we were not storing that
information anywhere, meaning that when we see the channel announcement the
next time we'd be reaching out to `lightningd` and `bitcoind` again, just to
see it fail again. This adds an in-memory cache for these failures so we can
just ignore these the next time around.
Fixes #2503
=> gossip: Cache txout query failures

lightningd/bitcoind.c
This is a patch to fix #2424.
It modifies the `bcli_args` function to skip any arguments with sensitive RPC username/password data when printing `bitcoin-cli` data to logs.
This is my first code PR to the project; please accept my apologies ahead of time if I inadvertently violated any standards/procedures.
=> Remove Sensitive RPC Data from Logs

Makefile
In particular, `make unittest/bitcoin/test/run-secret_eq_consttime`
didn't set VALGRIND if it was set via config.vars, so runs for a *long*
time.
=> unittest: make sure VALGRIND env var set under valgrind.

channeld/channeld.c
I notice that: 
> FIXME BOLT QUOTE: https://github.com/lightningnetwork/lightning-rfc/pull/512 once merged
So add the content of BOLT#7 quote now.
=> Add comments of BOLT quote about 'htlc_maximum_mast' bound

devtools/decodemsg.c, tools/generate-wire.py, wire/fromwire.c
Fixup the `decodemsg` utility to also include abilities for TLVs...
=> Add TLV's to decodemsg utility

doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.txt, doc/lightning-withdraw.7, doc/lightning-withdraw.7.txt
This PR adds the doc for the `minconf` parameter that was not in the detailed help.
=> Update 'withdraw' and 'fundchannel' calls documentation

wallet/db.c
wallet/test/run-wallet was failing the valgrind check; turns out
`sqlite3_expanded_sql` expects you to manage the memory of strings
it returns. from `sqlite3.h`:
** ^The string returned by sqlite3_expanded_sql(P), on the other hand,
** is obtained from [sqlite3_malloc()] and must be free by the application
** by passing it to [sqlite3_free()].
=> fix memleak introduced with sqlite3_expanded_sql

CHANGELOG.md, common/amount.c, common/amount.h, common/initial_channel.c, common/initial_channel.h, common/initial_commit_tx.c, common/initial_commit_tx.h, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/lightningd.h, lightningd/opening_control.c, lightningd/options.c, openingd/openingd.c, tests/test_connection.py, wallet/test/test_utils.c
**SUMMARY**
In regards to the IRC meeting logs, as the first part of Issue #2483 I see the need to introduce a config value and switch to automatically reject channel opening requests for tiny channels. The second part of adding a channel accept plugin hook will be in a separate PR that I am already working on. This PR will:
- Remove magic value `min_effective_htlc_capacity = AMOUNT_MSAT(1000000)`
- Introduce `min_capacity_sat` config value and `--min-capacity-sat` config switch.
- Add testcase
- Add doc
- Fix memory leaks discussed in PR #2494.
=> Issue #2483 part1: min_capacity_sat config for rejecting tiny channels

devtools/create-gossipstore.c
This PR fixes the compilation of the current version on Raspberry Pi.
=> Use SCNu64 instead of ld when scanning for a 64-bit value

CHANGELOG.md, closingd/closing_wire.csv, closingd/closingd.c, lightningd/closing_control.c
Travis caught an error where this happened: when closingd reconnects it
was sending the reestablish message without the option_dataloss_protect
fields.  That causes the peer to fail the channel!
=> closingd: send option_dataloss_protect fields when reestablishing.

CHANGELOG.md, Makefile, lightningd/htlc_end.c, lightningd/htlc_end.h, lightningd/json.c, lightningd/json.h, lightningd/peer_htlcs.c, tests/test_pay.py, wallet/db.c, wallet/db.h, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
This adds a `received_time` timestamp to incoming HTLCs and adds both a `received_time` and resolved_time` timestamp to the channel `forwarded_payments`. This allows us to see how long an HTLC was pending before it was resolved (with a granularity of seconds).
If desired we could probably change the granularity to milliseconds, but I wanted to try this first since #2491 only talks about an absolute time.
Fixes #2491
=> Add the time we received and resolved a forwarding to `listforwards`

CHANGELOG.md, lightningd/gossip_control.c, lightningd/peer_control.c
=> JSON: remove fields deprecated in 0.6.2.

closingd/closing_wire.csv, closingd/closingd.c, lightningd/closing_control.c, tests/test_closing.py
make it a bit easier to track mutual channel closures by
adding broadcast txid to the listpeers billboard
fixes #2552
=> closing: add message to billboard when closing txn is broadcast

hsmd/hsmd.c
> /* FIXME(cdecker) Check the node announcement's content */
>  it needs to check that this is actually a node_announcement, but it doesn't need to check anything else. In fact, it could just check fromwire_peektype() and that it is at least 66 bytes long.
So now I add the check for `fromwire_peektype()` before sig generation!
=> hsmd: Add the check of node announcement context before sig generation

gossipd/routing.c
`empty_node_map()` sounds like a destructor. `new_node_map()` makes sense and is better. Just an advice :)
=> Rename empty_node_map() to new_node_map()

hsmd/hsmd.c
like #2535 :
`hsmd` needs to check that this is actually a `channel_announcement`, but it doesn't need to check anything else. In fact, it could just check fromwire_peektype() and that it is at least 258 bytes long.
So now I add the check for fromwire_peektype() before sig generation!
=> hsmd: add the check for channel_announcement

gossipd/broadcast.c
There should check if node_id_1 was stored in pubkeys, other than checking scid.
=> gossipd: fix the check for node announcement in broadcast_state_check()

common/pseudorand.c, common/pseudorand.h, lightningd/invoice.c, lightningd/test/run-invoice-select-inchan.c, tests/test_invoices.py
This is a follow up of #2532
Fix and refactor `select_inchan` for invoice route-hint, now use fractional excess as weight.
Refactored the weighted-reservoir-sampling algo to make it more straightforward.
It now uses the excess as percentage of capacity as weight. This favors channels that
are more _relatively_ unbalanced to be used for incoming payment.
Now passes test_invoice_routeboost_private() when using max fundamount=16777215.
Hope that this fixes some issues.
=> Lightningd: Refactor and improve incoming channel selection for invoice's route-hint

CHANGELOG.md, channeld/channeld.c
The spec says not to send a commitment_signed without any changes, but LND does this.  To understand why, you have to understand how LND works.  I haven't read the code, but I'm pretty sure it works like this:
1. lnd slows down to do garbage collection, because it's in Go.
2. When an alert timer goes off, noticing it's not making process, it sends a twitter message to @roasbeef.
3. @roasbeef sshs into the user's machine and binary patches lnd to send a commitment_signed message.
4. Unfortunately he works so fast that various laws of causality are broken, meaning sometimes the commitment_signed is sent before any of these other things happen.
I'm fairly sure that this will stop as @roasbeef ages, or lnd introduces some kind of causality enforcement fix.
=> channeld: give some tolerance for empty commitments.

CHANGELOG.md, common/amount.c, common/amount.h, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/opening_control.c, lightningd/options.c, tests/test_connection.py, tests/test_invoices.py, wallet/test/test_utils.c
The old value of 1000 sat was too small to cover the dust reserves and
initial commitment fees. This lead to the situation when trying to open
a channel with minimal amount, the channels got refused because
they were not able cover the commitment fees.
For this reason the minimal capacity should be increased to i.e. 10k
satoshi, as the technical minimum that also accounts for fees and
reserves is somewhere around 6k sat.
additionally we substract the dust reserves on the fly from that value,
so that a `cli fundchannel VALUE` is possible with the same VALUE.
=> Increase min capacity sat default

contrib/pylightning/lightning/lightning.py
Millisatoshi's inner representation expected to be an int, otherwise unwanted exceptions could occur.
The following example raises: TypeError: __int__ returned non-int (type decimal.Decimal)
from lightning import Millisatoshi
one_sat = Millisatoshi("1sat")
two_sats = one_sat * 2
=> pylightning: millisatoshis type is int

tests/test_pay.py
We generated blocks to announce the channel, but it can also expire
the HTLC if the timing is wrong.  We don't need to anyway, since we
fixed the FIXME; we store local unannounced channels for restoration
=> pytest: fix old code in test, which can cause spurious failures.

lightningd/channel_control.c
For me this happened only under valgrind with
test_option_upfront_shutdown_script (in a pending branch):
==5063==    by 0x51FC076: raise (raise.c:48)
==5063==    by 0x51DD534: abort (abort.c:79)
==5063==    by 0x1292D2: fatal (log.c:647)
==5063==    by 0x116570: channel_set_state (channel.c:340)
==5063==    by 0x116E04: lockin_complete (channel_control.c:73)
==5063==    by 0x116F15: peer_got_funding_locked (channel_control.c:108)
==5063==    by 0x117354: channel_msg (channel_control.c:208)
No CHANGELOG: this was introduced in a recent refactor.
=> lightningd: don't abort if funding locks in during shutdown.

CHANGELOG.md
I dont know why this got messed up in the release process,
but `setchannelfee` ist actually scheduled for 0.7.1 and
not contained in 0.7.0.
=> fix: changelog included setchannelfee for 0.7.0

CHANGELOG.md, wallet/wallet.c
68fe5eacdecdf4eae94b376b7c4d4fd954c55a36 introduced a skip in the iteration
of the available funds, which means utxos[i] may be off the end of utxos.
Reported-and-debugged-by: @nitramiz
=> wallet: fix crash when we have height requirement.

channeld/test/run-full_channel.c, common/daemon.c, common/test/run-bolt11.c, common/test/run-derive_basepoints.c, common/test/run-features.c, wallet/test/run-wallet.c
Also removes a workaround caused by bug in libwally (!95) which has
been fixed.
Signed-off-by: Lawrence Nahum <lawrence@greenaddress.it>
=> update libwally to latest version 0.6.9

CHANGELOG.md, doc/PLUGINS.md, lightningd/invoice.c, lightningd/peer_control.c, lightningd/plugin_hook.c, lightningd/plugin_hook.h, tests/plugins/reject.py, tests/plugins/reject_some_invoices.py, tests/test_plugin.py
This adds some minor functionality, and cleans up my mistake about the invoice API.
I this the simplification of removing the deserialization step is worthwhile, and I included it because my new fundchannel hook assumes it, but I remove that part if you really dislike it.
=> Plugin API refinement

contrib/pylightning/setup.py
Hi!
I didn't understand if this is the home for pylightning, but here's a quick fix for making pylightning work with Python 2.7. It seems to be a regression from 0.0.7.
Attempting to install pylightning==0.0.7 with Python 2.7 will end up with the following error:
```
File "setup.py", line 5, in <module>
with open('README.md', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```
The reason for the error is that the global scope open doesn't have the `encoding` argument in Python 2.7. The solution is to import the `open` function from the `io` package, which makes the script compatible with both Python 2 and 3.
This fix makes the installation of https://github.com/marzig76/fulmo less of a hassle.
Cheers
=> pylightning: Fixing incompatibility issue with Python 2.7

CHANGELOG.md, lightningd/peer_control.c
Without this, the connect command hangs in one of my branches.  This logic
is from the old days when gossipd handled connections, and we wanted
to make sure it didn't hang up on this client due to the error.
=> lightningd: make sure we correctly clear connections from connectd on error

doc/Makefile
If we have plugins configured in the default config location, then
`check-manpages` may fail due to plugin cli options being added to the
`--help` output.
=> check: Run `check-manpages` in /tmp/ instead of the user config

contrib/pylightning/lightning/lightning.py
Currently, when a multiplication operator is invoked that
does not result in an even integer result but a floating result,
the pylightning code will raise an exception:
Millisatoshi must be string with msat/sat/btc suffix or int
This is because the internal float result will be used as
contructor argument like this:  return Millisatoshi(10000.5)
This happens especially on fee calculations where small uneven amounts
are calculated.
=> fix: pylightning msat round multiply and division

common/wallet_tx.h, tests/test_misc.py
We are computing a `maxheight` that coins must have to be considered for coin selection by subtracting the current `minconf` parameter from the current `blockheight`. If the `minconf` parameter is larger than `blockheight` we were wrapping around and suddenly accepting all transactions with at least one confirmation.
We now clamp the `maxheight` requirement to `1` (since `0` is used to indicate no confirmations required), which is safe since we can't end up having an output at that height, resulting in us not selecting any coins which is desired in this case.
Fixes #2518
=> Fix bockheight underflow if `minconf` > `blockheight`

gossipd/gossip_store.c
Entries we've already loaded expect to exist in the store.  We could go back and remove them all, but instead just truncate at the known-good point.
Fixes  #2583
=> gossipd: fix crash if we truncate store.

common/daemon_conn.c, common/daemon_conn.h, common/msg_queue.c, common/msg_queue.h, common/status.c
We can be spammy, which is good for tests, but bad for our simple message queue.
This avoids breaking our tests but also avoid the worst case (1M entries and counting!)
for gossip status messages in the case where we're syncing a large peer.
[ This is less invasive than #2610 but in some ways less elegant.  Fixing those tests was non-trivial, and would have involved doing IO tracing for all of them... ]
Closes: #2610
=> status: suppress status_trace/status_debug messages if queue too long.

CHANGELOG.md, lightningd/peer_htlcs.c, tests/test_pay.py, wallet/db.c, wallet/wallet.c, wallet/wallet.h
Store failcode of local forward into DB, and thus listforwards will show the failcode for local failed forwarding payment.(issue #2435 )
- Add a new status for forward payment: FORWARD_LOCAL_FAILED.
It means we meet failure locally, and we can fetch and store the failcode.
- Add failcode field in `forwarded_payments` table;
- Add failcode arugument in function `wallet_forwarded_payment_add()`;
- Store local failure in forward process by calling `wallet_forwarded_payment_add()`;
Here are 5 case I think we should handle as `local_failed`:
**Case 1**. When Msater resolves the reply about the next peer infor(sent by Gossipd), and need handle unknown next peer failure in `channel_resolve_reply()`.
**Test for this case:** I ask l1 pay to l3 through l2 but close the channel between l2 and l3 …
=> Store failcode of local forward failure into DB (completed)

wallet/test/run-wallet.c
1. Fix the the description string of `CHECK_MSG` after loading the channel from DB. It should indicate the "`Load from DB`" step;
2. I think the `v6` and `v8` in
```
CHECK_MSG(channelseq(&c1, c2), "Compare loaded with saved (v6)");
CHECK_MSG(channelseq(&c1, c2), "Compare loaded with saved (v8)");
```
mean` variant 6` and `variant 8`. They should be `v3` and `v4`.
=> Fix the description string of CHECK_MSG in run_wallet

contrib/pylightning/lightning/lightning.py
The old codes if % 1000 statement logic was simply inverted
and produced the opposite output of the intention behind it.
Before Fix:
- `Millisatoshi('42sat').to_btc_str()` => `0.00000042000btc`
- `Millisatoshi('42001msat').to_btc_str()` => `0.00000042btc`
After  Fix:
- `Millisatoshi('42sat').to_btc_str()` => `0.00000042btc`
- `Millisatoshi('42001msat').to_btc_str()` => `0.00000042001btc`
=> fix: pylightning to_btc_str precision

CHANGELOG.md, common/bolt11.c, common/test/run-bolt11.c, tests/test_invoices.py
=> bolt11: fix decoding and encoding of unknown fields.

tests/utils.py
We try to look up the funding tx, but it's already spent that to fund
the channel, so we need txindex if this test is to work reliably.
It's not clear to me why this *ever* worked, but if fails on my new
ThreadRipper build machine with valgrind:
>	wallettx = l1.bitcoin.rpc.getrawtransaction(wallettxid, True)
...
E           bitcoin.rpc.InvalidAddressOrKeyError: {'code': -5, 'message': 'No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.'}
/usr/lib/python3/dist-packages/bitcoin/rpc.py:231: InvalidAddressOrKeyError
=> pytest: fix test_bech32_funding

contrib/init/lightningd.service
Prevents error when launching with bind-addr.
=> systemd: wait until network is up

openingd/openingd.c, tests/test_gossip.py
My raspberry pi node hung up on my other node:
lightning_openingd-... chan #1: Got bad message from gossipd: 0db1
This is because we didn't handle that message in one path.
=> openingd: fix hangup when gossipd compacts.

lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
The paramater `ctx` in `wallet_channels_load_active()` and `wallet_stmt2channel()` is unused.
I guess the original idea is to `tal` channels on the `ctx`(In fact, we'd like to set `ctx` as `ld`).
But we already `tal` channels on `ld` when `new_channel()` is called in `wallet_stmt2channel()`, so the paramater `ctx` is unused and repeated.
=> wallet: cleanup the tal context paramater in two functions

contrib/pylightning/lightning/lightning.py
This PR adds `listconfigs()` and `listsendpays()` methods to `LightningRpc` class. It also changes default value of `expiry_time` to 1 week in the `get_route()` method.
=> Pylightning: add some missing RPC methods and correct a docstring

CHANGELOG.md, doc/PLUGINS.md, lightningd/channel.c, lightningd/gossip_control.c, lightningd/invoice.c, lightningd/json.c, lightningd/json.h, lightningd/opening_control.c, lightningd/opening_control.h, lightningd/pay.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, lightningd/test/run-invoice-select-inchan.c, openingd/opening_wire.csv, openingd/openingd.c, tests/plugins/reject_odd_funding_amounts.py, tests/test_plugin.py, tools/generate-wire.py, wallet/test/run-wallet.c, wallet/walletrpc.c
Somehow I dropped this: I had a PR which I decided to split into pieces, and never resubmitted.  I was reviewing the milestones for 0.7.1 when I noticed.
Closes: #2483
=> Channel fund hook

CHANGELOG.md, lightningd/plugin.c, lightningd/plugin.h
Having a `plugins` directory in the configuration path can be very handy instead of manually adding `--plugin-dir=` or `--plugin=`, and it's easier to have it in the configuration directory than in the installation one.
This PR adds a function that will, if it exists, iterate through `<path_to_config_dir>/plugins` and add, without failing on error, each directory it contains as a new `plugin-dir`.
It permits to, for instance :
```shell
git clone https://github.com/lightningd/plugins ~/.lightning/plugins
```
and have (once requirements installed) all the community curated list of plugins available.
=> Plugins: add a default 'plugins' directory in the config dir

contrib/lightning-cli.bash-completion
The regex `^command=` is no longer valid to get the command list from the output of `lightning-cli -H help 2>/dev/null`
=> Fix bash completion

plugins/autoclean.c
DOES NOT correct #2660 , but we should be clean anyway.
=> plugins/autoclean.c: Remove unnecessary inclusions.

lightningd/plugin.c
Fixes: #2667
Really-by: @darwin
=> lightningd/plugin.c: Do not call `closedir` with NULL DIR*.

common/json_tok.h, contrib/startup_regtest.sh
Fixup a spelling whoops; always remove the pid files, even if the process has already died. Especially if the process has already died.
=> Small fixups

wallet/db.c
=> wallet/db.c: Be resilient against 32-bit time_t.

doc/lightning-pay.7, doc/lightning-pay.7.txt
Fixes: #2659
Value randomization is not implemented since `pay` was made into a plugin.
Nobody has been asking for it, so do not implement it and just remove
from documentation.
Shadow routes is implemented, and not describe, so describe it now.
=> doc/lightning-pay.7.txt: Remove references to value randomization, since it is no longer implemented, and describe shadow routes.

tests/test_closing.py
This is the warning I got from Python:
isAlive() is deprecated, use is_alive() instead
=> test_closing.py: isAlive -> is_alive

lightningd/subd.c, tests/test_closing.py, tests/test_connection.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py, tests/utils.py
Things that don't really fit in anywhere else:
- Avoid trying to restart the `bitcoind` proxy along with `lightingd`, removes the `unable to bind` warning
- A small fix to wait for a connection to be recognized before trying to use it
- Marking some flaky tests as `@flaky` (will do a stabilization pass later, but they were really annoying and were addressed only by restarting instead of fixing them).
- Remove the `UPDATE <message_type>` spam from `subd` which is really annoying in production.
=> cdecker's weekly cleanups

lightningd/json_stream.c, lightningd/json_stream.h, lightningd/jsonrpc.c, lightningd/jsonrpc.h, lightningd/log.c
Before this, the response of `getlog io` would blow up quickly
when called multiple times.
closes #2467
=> lightningd: don't log the response of getlog command

channeld/channeld.c, lightningd/chaintopology.c, lightningd/peer_control.c, lightningd/watch.c, tests/test_closing.py, tests/test_misc.py, tests/utils.py
Before this PR we calculate `short_channel_id` only once, when the funding tx reaches `minimum_depth` confirmations, the channel will then _lockin_ and can be used locally. For private channels we then stop watching the funding depth.
When `minimum_depth=1`, a chain reorganization of 1 block deep can change funding tx height and/or txindex after lockin. The probability for this to happen is small,  just a fraction of the _orphan rate_ (for bitcoin [0.5%](https://medium.com/@jb395official/orphan-blocks-june-16-2018-a8f4799dcc2c)) and I couldn't find any case of this ever happening.
But if we don't agree with our peer about `scid` a public channel will fail at announce depth or `channel_updates` are not recognized properly, making the channel partially unusable (not routable). If peers …
=> Fix for reorgs changing short_channel_id after lockin

doc/Makefile, doc/lightning-listforwards.7, doc/lightning-listforwards.7.txt
I don't understand how manpages are created automatically via the a2x tool. That is why id wrote both files manually. I guess I need only the .7 or the .7.txt file and the other one is automatically created. my machine always creates an xml file and then make produces an error. 
So I need some help and will then redo the PR
=> added manpage for listforwards command (needs change)

CHANGELOG.md, channeld/channel_wire.csv, channeld/channeld.c, lightningd/channel_control.c, wallet/db.c, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
Fixes #2409 
Here I add a new wire type:
**channel_got_announcement (1017)**
When Channeld receives the remote channel announcement signatures, it will generate a msg1 like:
**WIRE_CHANNEL_GOT_ANNOUNCEMENT + remote_ann_node_sig + remote_ann_bitcoin_sig**
and send this msg to Master. (After sending signatures, Channeld will be holding until receive the reply from Master.)
Master resolves msg and stores the signatures into DB. 
Like issue #2409 , the adventage is when we reenable our channel, you can init it with the remote announcement signatures from DB directly other than wasting your time to wait for remote peer's announce reply.
=> DB: Store the signatures of channel announcement sent from remote peer into DB

lightningd/channel.c, lightningd/lightningd.c, lightningd/subd.c, lightningd/subd.h
Fixes #2677 
I am unable to replicate 2677 in a test; it seems to me that there is something that prevents subdaemons of `lightningd` to respond quickly to communications with `lightningd`, but it is not present in our CI.
=>  lightningd/channel.c: Transfer peer to connectd only if connectd alive. 

lightningd/Makefile, lightningd/chaintopology.c, lightningd/io_loop_with_timers.c, lightningd/io_loop_with_timers.h, lightningd/lightningd.c, lightningd/test/run-find_my_abspath.c, tests/test_misc.py
=> lightningd/io_loop_with_timers.c: Move mainloop to its own source file, have chaintopology use it

contrib/pylightning/lightning/plugin.py, lightningd/plugin.c, plugins/autoclean.c, plugins/libplugin.c, plugins/libplugin.h
This PR adds the possibility to register plugin options of type `int`, `bool` in addition to `string`.
=> Plugin: accept different option types (str, int, bool)

tests/test_connection.py, tests/test_misc.py, tests/test_plugin.py
We had two tests that had a race condition when closing a channel and then doing `bitcoind.generate_block(1)` that the bitcoind did not have the close tx in the mempool yet.
This PR adds missing `wait_for(lambda: len(bitcoind.rpc.getrawmempool()) > 0)` before calling `generate_block`
=> Fix flakes funding_reorg_private openchannel_hook and no_fee_estimate

gossipd/gossip_store.c, gossipd/gossip_store.h, gossipd/routing.c, tests/fixtures.py, tests/test_gossip.py
As part of my final gossip optimizations PR, I tightened and added testing.  This revealed existing bugs: in particular, the "bad node_announcement" message we sometimes get loading store.
Fixing this revealed another nasty issue, where we tried to remove from the gossip_store as it was being loaded.  This is worked around for now: it will be fixed properly by rebasing #2644 on top of this....
=> Gossip store fixes

CHANGELOG.md, common/sphinx.c, common/sphinx.h, contrib/plugins/helloworld.py, doc/PLUGINS.md, lightningd/json.c, lightningd/json.h, lightningd/lightningd.c, lightningd/peer_htlcs.c, lightningd/test/run-find_my_abspath.c, lightningd/test/run-invoice-select-inchan.c, tests/plugins/fail_htlcs.py, tests/plugins/hold_htlcs.py, tests/plugins/shortcircuit.py, tests/test_closing.py, tests/test_plugin.py, wallet/test/run-wallet.c
This used to be part of #2237, but since there were some unaddressed concerns I split the two.
This PR builds on top of #2237, and implements the hook for `htlc_accepted` allowing a plugin to decide on what we should be doing with an HTLC that we just added to the commitment:
- `continue` proceeds as usual with the HTLC, attempting to resolve it if we are the recipient of the payment, or forward it if we just an intermediate hop. This can be used to apply some policy that can't be implemented in `lightningd` itself, or delay resolution to see that we can actually deliver whatever we promised in exchange of the payment.
- `resolve` claims the HTLC using a provided `payment_key`, this can be used to short-circuit payments, moving processing of the payment out (cross-chain atomic swaps), …
=> plugin: Implement the `htlc_accepted` hook

tests/test_misc.py, wallet/walletrpc.c
It would always return bech32; fix that, and don't bother printing
it if they use the (new) 'all' parameter.
This API was introduced in 3e67c09d5e6022300d785fbf5be76aeaa756c822,
which means it wasn't in a release so no CHANGELOG entry necessary.
=> newaddr: fix return value for deprecated "address" field.

tests/test_misc.py, tests/test_plugin.py, tests/utils.py
This will add an optional wait_for_mempool parametr to the `generate_block` function in the BitcoinD testsuite. Can help fix flaky tests and reduces code cuplications for all the `wait_for(lambda: len(self.rpc.getrawmempool()) > 0`
The new `wait_for_mempool` parameter can be:
- `True` to wait for 1 transaction in mempool
- `int > 0` to wait for N transactions in the mempool
- `"tx_id_str"` to wait for only one specific transaction ID
- `["tx_id_str_1", "tx_id_str_2", ...]` to wait for N specific transaction IDs
=> Test generate block wait mempool

.travis/build.sh
We currently set TIMEOUT and PYTEST_PAR in our Travis instance directly,
which is a bit unhelpful.  In particular, parallelism should be increased
when DEVELOPER isn't set since we spend 60 seconds waiting for gossip in
many cases.
If this doesn't stop timeouts, I'll have to mark more tests SLOW_MACHINE :(
331.24s call     tests/test_connection.py::test_opening_tiny_channel
245.45s call     tests/test_gossip.py::test_gossip_store_load_complex
215.35s call     tests/test_invoices.py::test_invoice_routeboost
194.04s call     tests/test_plugin.py::test_htlc_accepted_hook_forward_restart
182.62s call     tests/test_plugin.py::test_htlc_accepted_hook_fail
182.02s call     tests/test_plugin.py::test_htlc_accepted_hook_resolve
182.01s call     tests/test_pay.py::test_pay_limits
159.10s call …
=> Travis: set all vars inside build.sh, and increase parallelism for DEVELOPER=0

CHANGELOG.md, doc/PLUGINS.md, lightningd/json.c, lightningd/json.h, lightningd/lightningd.c, lightningd/log.c, lightningd/log.h, lightningd/log_status.c, lightningd/notification.c, lightningd/notification.h, lightningd/peer_control.c, lightningd/plugin.c, lightningd/test/run-find_my_abspath.c, lightningd/test/run-invoice-select-inchan.c, lightningd/test/run-jsonrpc.c, tests/plugins/pretend_badlog.py, tests/test_plugin.py, wallet/test/run-db.c, wallet/test/run-wallet.c
This notification bases on `LOG_BROKEN` and `LOG_UNUSUAL` level log. Hope it can help to deal with #2305 .
A notification for topic `warning` is sent every time a new `BROKEN`/`UNUSUAL` level(in plugins, we use `error`/`warn`) log generated, which means an unusual/borken thing happens, such as channel failed,
message resolving failed...
```json
{
"warning": {
"level": "warn",
"time": "1559743608.565342521",
"source": "lightningd(17652): 0821f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c chan #7854:",
"log": "Peer permanent failure in CHANNELD_NORMAL: lightning_channeld: sent ERROR bad reestablish dataloss msg"
}
}
```
1. `level` is `warn` or `error`:
`warn` means something seems bad happened and it's under control, but we'd better check it;
`error` means something …
=> plugin: A new notification type 'warning'

tests/test_pay.py
Broken by 909913c26543d7768d765dea49cb362bb740e011, but since Travis
skips this test ("temporarily", according to the commit msg in January!)
it wasn't caught.
=> pytest: fix test_hlcs_cltv_only_difference

configure
I noticed that DEVELOPER was being reset to 0 by ./configure --reconfigure;
that's because we set the defaults first, then --reconfigure would only
override *unset* vars.  We now set up defaults last.
We unify all our "find the default" functions, to neaten them; in
particular find_pytest and our open-coded valgrind testing function.
We can figure out whether valgrind works using /bin/true instead of waiting
until configurator is built.
We're also more careful with ${FOO-default} vs ${FOO:-default}; the former
does not replace if FOO is set to the empty string, which is possible for
some of our settings (COPTFLAGS, CDEBUGFLAGS in particular).
=> configure: fix --reconfigure, improve style, set defaults in one place.

channeld/channeld.c, channeld/full_channel.c, channeld/full_channel.h, channeld/test/run-full_channel.c
This will  pass HTLC fee amounts into the "Capacity exception" so they can be catched and parsed by a upper layer plugin (i.e. https://github.com/lightningd/plugins/pull/22 ). This change is useful, because the required HTLC fees cannot be computed/checked in advance.
currently, if a payment is made, the required HTLC onchain fees will be substracted from the `spendable` amount. This is a temporary hedge against the channel balance, if anything goes wrong. This is done in an opaque way, so the upper layers (like plugins) can't know the correct value that needs to be subtracted from the `spendable` amount, in order for the node to make the payment. For example the `drain` plugin has a ugly `while`   `try/except` loop to increase gradually until the `Capacity exceeded` exception is not …
=> Pass htlc amount exceeded to exception

common/Makefile, common/wallet.c, common/wallet.h, lightningd/Makefile, lightningd/chaintopology.c, lightningd/channel.c, lightningd/channel.h, lightningd/closing_control.c, lightningd/onchain_control.c, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, lightningd/test/run-invoice-select-inchan.c, onchaind/Makefile, onchaind/onchain_wire.csv, onchaind/onchaind.c, onchaind/test/run-grind_feerate.c, wallet/db.c, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c
This PR extends the capabilities of our internal transaction tracking by annotating transactions of interest with a transaction type and a `channel_id`. This allows us to group transactions by the channel they affected, trace the on-chain footprint of a channel (improving our debuggability) and showing on-chain transaction history in wallet UIs.
- The `channel_id` in the `transactions` table is not a foreign key into the `channels` table since we delete entries from that table, which would reset that grouping key. I found it better to keep them set, resulting in them being more of a grouping key rather than a real reference to a channel.
- Transactions are inserted and then annotated with their type aposteriori since we add transactions in the main daemon based on `tx_watches` or …
=> json-rpc: Annotate transactions of interest and add the `listtransactions` RPC method

CHANGELOG.md, channeld/channeld.c, tests/test_connection.py
@pm47 gave a great bug report showing c-lightning sending the same UPDATE_FEE over and over, with the final surprise result being that we blamed the peer for sending us multiple empty commits!
The spam is caused by us checking "are we at the desired feerate?" but then if we can't afford the desired feerate, setting the feerate we can afford, even though it's a duplicate.  Doing the feerate cap before we test if it's what we have already eliminates this.
But the empty commits was harder to find: it's caused by a heuristic in channel_rcvd_revoke_and_ack:
```
/* For funder, ack also means time to apply new feerate locally. */
if (channel->funder == LOCAL &&
(channel->view[LOCAL].feerate_per_kw
!= channel->view[REMOTE].feerate_per_kw)) {
status_trace("Applying feerate %u to LOCAL (was %u)", …
```
=> channeld: don't send feerate spam if we can't set it as high as we want.

lightningd/json.c, lightningd/json.h, lightningd/peer_htlcs.c, wallet/test/run-wallet.c
~Found this while trying to do some magic on top of `shared_secret`, turns out we were not keeping the secret around long enough, so now we just stash it in the `htlc_accepted_payload`.~
I had confused pointer and pointee :frowning_face:
=> plugin: Fix how we send the shared_secret to the plugin in htlc_accepted.

tests/test_gossip.py
Simply fixes another test flake using the new wait_for_mempool parameter with generate_block.
=> test: fix flaky test_gossip_notices_close with wait_for_mempool

common/gossip_store.h, tests/test_gossip.py
There were several gossip breakages in master; bumping version means
upgrades get a clean store (not just those upgrading from stable version).
Fixes: #2719
=> gossip: bump version to remove lingering issues with master.

CHANGELOG.md, common/json_helpers.c, common/json_helpers.h, common/wallet_tx.c, common/wallet_tx.h, contrib/pylightning/lightning/lightning.py, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.txt, lightningd/opening_control.c, tests/test_connection.py, wallet/wallet.c, wallet/wallet.h
Fixes #2682 .
This PR adds the possibility to specify a list of outpoints (`[\"txid:vout\", \"txid:vout\"]`) as the second parameter of the `fundchannel` call in addition to `'all'` or an amount in satoshis.
=> fundchannel: add the possibility to fund a channel with specific utxos

CHANGELOG.md, common/Makefile, common/addr.c, common/addr.h, contrib/pylightning/lightning/lightning.py, doc/Makefile, doc/lightning-fundchannel_cancel.7, doc/lightning-fundchannel_cancel.7.txt, doc/lightning-fundchannel_complete.7, doc/lightning-fundchannel_complete.7.txt, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.txt, lightningd/Makefile, lightningd/json.c, lightningd/opening_control.c, openingd/opening_wire.csv, openingd/openingd.c, tests/test_connection.py, tests/utils.py, wallet/walletrpc.c
Adds RPC commands for funding a channel via an external wallet.
There's a lot of caveats around the expected behavior of the wallet (uses SegWit ie non-malleable inputs, doesn't broadcast until `continue` has completed, provides the _correct_ funding amount to `fundchannel_start`) that this doesn't have any way of enforcing. As such, it's behind an experimental flag -- a good plugin could probably paper over the majority of these issues. 
RPCs added are as follows:
-  `fundchannel_start`. Returns a bech32 address that is the funding tx destination. 
- `fundchannel_continue`. Takes a funding txid and vout, returns the channel_id and confirmation that we've secured the commitment transactions for this channel.
- `fundchannel_cancel`. Instead of `continue`, halts the fund channel flow.
Fixes …
=> External wallet funding 

lightningd/opening_control.c
Compile broke because we were using low-level JSON primitives here (which, incidentally, would produce bad JSON now, since we can't just put a raw string inside an object!).
Tests broke because I changed the api of json_stream_success without changing the name :(
=> Fix compile error caused by merge.

lightningd/peer_control.c
Setting channel to NULL then iterating doesn't work!
Fixes: #2733
=> lightningd: fix bogus channel iteration on setchannelfee

gossipd/routing.c
We catch node_announcements for nodes where we haven't finished
analyzing the channel_announcement yet (either because we're still
checking UTXO, or in this case, because we're waiting for a channel_update).
But we reference count the pending_node_announce, so if we have
multiple channels pending, we might try to insert it twice.  Clear it
so this doesn't happen.
There's a second bug where we continue to catch node_announcements
until *all* the channel_announcements are no longer pending; this is fixed
by removing it from the map.
Fixes: #2735
=> gossipd: don't catch pending node_announcements more than once.

doc/PLUGINS.md
int and bool are now also accepted ! :)
=> plugins doc: remove the 'only string options' warning

lightningd/json_stream.c, lightningd/json_stream.h, lightningd/jsonrpc.c
It needs this in compat mode to detect old (pre-0.6.3) end of JSON.
But it always does the first command in compat mode.
This was never really reliable, since the first command could be to
a plugin for which we simply pass through the JSON (though, carefully
appending the expected '\n\n' if not already there).
Reported-by: @laanwj
Fixes: #2749 
(Tested by reverting adc4bf181735c943727d96842216806fe9a6ad16)
=> lightningd: restore ' ' before '}' for older pylightning.

tests/test_connection.py
Fix flakiness in test by using `wait_for_log`
=> connect test: use wait_for_log in test_funding_external_wallet

gossipd/gossip_store.c, tests/test_gossip.py
If something went wrong and there was an old one, we were appending to it!
Reported-by: @SimonVrouwe
=> gossipd: truncate gossip_store.tmp for compaction.

gossipd/gossip_store.c, gossipd/gossipd.c, gossipd/routing.c, gossipd/routing.h, tests/test_gossip.py
I cannot reproduce #2750 on my nodes.  However, they seem to mainly be caused by us attempting to recover a gossip_store which we've truncated.  Instead, this discards all gossip when that happens.
It should also make any corruption easier to diagnose, as the last patch means we save the corrupt gossip_store to `gossip_store.corrupt` for later diagnosis.
=> Simplified gossip_store recovery

gossipd/gossip_store.c, tests/test_gossip.py
This is based on #2757 (first 5 commits)
The last commit adds a simple offline compaction step, which is much simpler than the online compaction which seems to be causing problems for #2750
=> Offline compact: avoid automatic compaction

CHANGELOG.md, wallet/walletrpc.c
Given the number of open issues with the `listtransactions` RPC method I think it is probably best if we disable the method for the 0.7.1 release, and then fix it up for the next release.
=> json-rpc: Disable `listtransactions` for the 0.7.1 release

channeld/commit_tx.c, hsmd/hsmd.c, lightningd/peer_control.c, lightningd/peer_htlcs.c
Looks like old deployments have some of these, so add a workaround and a check.
Fixes: #2772 
Fixes: #2759
=> Handle zero output commitments

lightningd/chaintopology.c, lightningd/onchain_control.c, lightningd/peer_control.c, lightningd/peer_htlcs.h, lightningd/test/run-invoice-select-inchan.c, lightningd/watch.c, lightningd/watch.h, wallet/test/run-wallet.c
I was working on rewriting our (somewhat chaotic) tx watching code
for 0.7.2, when I found this bug: we don't always notice the funding
tx in corner cases where more than one block is detected at
once.
This is just the one commit needed to fix the problem: it has some
unnecessary changes, but I'd prefer not to diverge too far from my
cleanup-txwatch branch.
Fixes: #2352
=> lightningd: fix occasional missing txid detection.

lightningd/bitcoind.c, lightningd/chaintopology.c, lightningd/connect_control.c, lightningd/io_loop_with_timers.c, lightningd/jsonrpc.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/memdump.c, lightningd/pay.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, lightningd/plugin.c, wallet/txfilter.c
Reported-by: @niftynei 
None of these are unconstrained memory leaks, but it's nice to clean up on exit.
We could override the htable alloc routines to use tal off the htable, but that actually means each htable would have to be tal'ocated itself, which they currently are not (they're inside structures).  So we do this instead.
=> ASAN fixes

lightningd/channel.c, lightningd/channel_state.h, lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, tests/test_closing.py, tests/test_connection.py, wallet/wallet.c, wallet/wallet.h
Since we are starting to have some tables that reference the `channels` table using foreign keys and these survive the channel I think it's a good idea to keep a minimal version of the channels around. This ensures that foreign key relationships aren't broken once we fully resolve a channel, including access to channel-related fields, and it can allow us to recover some information about old channels for debugging or display purposes.
Fixes #2028
=> Don't delete channels once they are resolved, just mark them closed.

lightningd/peer_control.c
Caused by merge, and two files with autodata on same line.
Edit by ZmnSCPxj:
Fixes: #2782
=> peer_control: fix autodata compile issue.

Makefile
It fixes this error that happens in some configurations:
```
configure: creating ./config.status
./config.status: command substitution: line 547: unexpected EOF while looking for matching `"'
./config.status: command substitution: line 548: syntax error: unexpected end of file
./config.status: line 546: LDFLAGS=  -Og: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: line 688: -e: command not found
./config.status: …
```
=> makefiles: fix quotation of BINTOPKGLIBEXECDIR macro

channeld/full_channel.c, common/crypto_sync.c, lightningd/channel.c, lightningd/log.c, lightningd/peer_control.c, tests/fixtures.py, tests/test_closing.py, tests/test_connection.py, tests/test_gossip.py, tests/test_misc.py, tests/test_plugin.py, tests/utils.py
And clean up some dev ones which actually happen (mainly by calling
channel_fail_permanent which logs UNUSUAL, rather than
channel_internal_error which logs BROKEN).
=> pytest: fail tests if we get any LOG_BROKEN level messages, unless flagged

gossipd/gossip_store.c
Otherwise we fail at the write, and then it's not clear
*why* we couldn't open file:
lightning_gossipd: Writing version to store: Bad file descriptor (version v0.7.1-16-g7ea5c5c)
0x560dcf1a3779 send_backtrace common/daemon.c:40
0x560dcf1a634d status_failed common/status.c:192
0x560dcf19726a gossip_store_new gossipd/gossip_store.c:195
0x560dcf199fd0 new_routing_state gossipd/routing.c:177
0x560dcf1a098b gossip_init gossipd/gossipd.c:2113
0x560dcf1a197a recv_req gossipd/gossipd.c:2946
0x560dcf1a38cd handle_read common/daemon_conn.c:31
0x560dcf1bae2c next_plan ccan/ccan/io/io.c:59
0x560dcf1bb314 do_plan ccan/ccan/io/io.c:407
0x560dcf1bb341 io_ready ccan/ccan/io/io.c:417
0x560dcf1bcb13 io_loop ccan/ccan/io/poll.c:445
0x560dcf1a1ba0 main gossipd/gossipd.c:3073
Reported-by: @JavierRSobrino …
=> gossipd: fail clearly if we can't open/create gossip_store.

onchaind/onchaind.c
We shouldn't set out->resolved until we've actually resolved it.
=> onchaind: fix resolution detection of complex outputs, billboard

lightningd/opening_control.c
test_funding_cancel_race explicitly attempts to trigger this via a race
condition; this conflicts with our post-test checks that no broken
logs were logged. as a middle ground, we log it as unusual, not broken,
as it's possible for it to attempt to fail if it was begun at the same
time as the complete is (hence it's not *actually* broken, yet still unusual)
=> tests: log funder_faileds as unusual not broken

contrib/lightning-cli.bash-completion
`fundchannel_start` etc are not included in the bash-completion as
they include underscores in their names. this fixes this by including
underscores.
=> bash-completion: include underscores

CHANGELOG.md, plugins/pay.c
```
pay: ccan/ccan/json_out/json_out.c:144: check_fieldname: Assertion `!fieldname' failed.
pay: FATAL SIGNAL 6 (version v0.7.1rc4-1-gf1bea55)
0x11d914 send_backtrace
common/daemon.c:40
0x11d9ba crashdump
common/daemon.c:53
0x5430f1f ???
???:0
0x5430e97 ???
???:0
0x5432800 ???
???:0
0x5422399 ???
???:0
0x5422411 ???
???:0
0x1325c3 check_fieldname
ccan/ccan/json_out/json_out.c:144
0x132627 json_out_member_direct
ccan/ccan/json_out/json_out.c:162
0x10c4a4 json_out_add_raw_len
plugins/pay.c:122
0x10c4f9 json_out_add_raw
plugins/pay.c:130
0x10c9ae waitsendpay_expired
plugins/pay.c:236
0x10ce39 waitsendpay_error
plugins/pay.c:322
0x111aa7 handle_rpc_reply
plugins/libplugin.c:431
```
=> plugins/pay: fix crash when we reach retry timeout.

common/json_tok.c, common/json_tok.h, common/param.c, common/param.h, lightningd/jsonrpc.c, lightningd/test/run-jsonrpc.c, tests/test_misc.py
Our previous param support was a bit limited in this case, and we want it for #2771 
We replace some dev- commands with a multiplexer, so we can exercise it
=> param: implement helpers for multiplex commands.

gossipd/routing.c
==1503== Use of uninitialised value of size 8
==1503==    at 0x566786B: _itoa_word (_itoa.c:179)
==1503==    by 0x566AF0D: vfprintf (vfprintf.c:1642)
==1503==    by 0x569790F: vsnprintf (vsnprintf.c:114)
==1503==    by 0x156CCB: do_vfmt (str.c:66)
==1503==    by 0x156DB1: tal_vfmt_ (str.c:92)
==1503==    by 0x1289CD: status_vfmt (status.c:141)
==1503==    by 0x128AAC: status_fmt (status.c:151)
==1503==    by 0x118E05: route_prune (routing.c:2495)
==1503==    by 0x11DE2D: gossip_refresh_network (gossipd.c:1997)
==1503==    by 0x1292B8: timer_expired (timeout.c:39)
==1503==    by 0x12088C: main (gossipd.c:3075)
=> gossipd: fix inverted test in debug print.

doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/bitcoind.c, lightningd/bitcoind.h, lightningd/options.c
=> lightningd/options.c: Add option for setting how long to keep trying bitcoin-cli command.

bitcoin/chainparams.c, bitcoin/chainparams.h, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/jsonrpc.c, lightningd/options.c, wallet/wallet.c
This PR adds support for signet networks.
Blocked by: https://github.com/bitcoin/bitcoin/pull/16411
See also: https://en.bitcoin.it/wiki/Signet
=> add signet support

tools/generate-bolts.py
Use ordered dict for fields, whose order matters when iterated
through (especially for argument lists).  see #2830 
Reported-By: @mocacinno
=> bolt-gen: use ordered-dict for fields

.travis/build.sh
We're hitting OOM at the moment: reduce number of valgrinds
we run at once.
=> travis: reduce parallelism for valgrind

Makefile, tools/check-bolt.c, wire/Makefile
This means we don't check BOLTS when EXPERIMENTAL_FEATURES is enabled, except for those tagged with this specific version.  This allows you to check BOLT quotes without getting tangled in old BOLTs.
=> Make check fixes

lightningd/io_loop_with_timers.c
I mean, we still crash, but we give an error now :)
lightningd: FATAL SIGNAL 11 (version v0.7.1-82-g92c38a0)
0x5592e75e19c8 send_backtrace
common/daemon.c:40
0x5592e75e1a6e crashdump
common/daemon.c:53
0x7fad1514ef5f ???
???:0
0x5592e75b2f3a io_loop_with_timers
lightningd/io_loop_with_timers.c:29
0x5592e75d8a54 plugins_init
lightningd/plugin.c:1018
0x5592e75b8e22 main
lightningd/lightningd.c:671
0x7fad15131b6a ???
???:0
0x5592e75a10f9 ???
???:0
0xffffffffffffffff ???
???:0
Segmentation fault (core dumped)
=> plugins: don't crash if getmanifest times out.

Dockerfile
Fixes #2824 .
Maybe we prefer a requirements.txt instead ?
=> Install python3-mako in the Dockerfile

CHANGELOG.md, contrib/plugins/helloworld.py, doc/PLUGINS.md, lightningd/invoice.c, lightningd/notification.c, lightningd/notification.h, lightningd/test/run-invoice-select-inchan.c, tests/test_plugin.py
As discussed on IRC, a plugin might want to be notified on invoice payment without needing `lightningd` to wait for his response.
This PR adds an `invoice_payment` notification type similar to the same named hook.
=> Plugins: a notification for invoice payments

devtools/print_wire.c, tools/test/enum.c
```
tools/test/enum.c: In function ‘fromwire_test_enum’:
tools/test/enum.c:11:34: error: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
printf("fromwire_test_enum at %ld\n", *max);
```
=> tools: fix 32 bit compile error

CHANGELOG.md, doc/lightning-listfunds.7, doc/lightning-listfunds.7.txt, wallet/walletrpc.c
I am [working on a plug-in](https://github.com/kristapsk/lightning-feereport) that emulates `lncli feereport` command of LND for c-lightning. It needs to return `chan_point` for each channel, so I need not only channel funding txid, but also output index. This information is present anyways, why not to return, and, besides, it is already returned for onchain UTXOs.
=> RPC: Return output idx for a funding tx in a channel information in listfunds

CHANGELOG.md, common/peer_failed.c, common/peer_status_wire.csv, lightningd/channel.c, lightningd/channel.h, lightningd/channel_control.c, lightningd/closing_control.c, lightningd/connect_control.c, lightningd/invoice.c, lightningd/onchain_control.c, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/subd.c, lightningd/subd.h, lightningd/test/run-find_my_abspath.c
I think there are more than enough (too many?) snarky comments in the code itself, so I'll just leave it at that.
First commit is a drive-by fix for a bug I noticed.
Edit by ZmnSCPxj:
Fixes #2847
=> Be more forgiving with lnd

lightningd/options.c, lightningd/plugin.c, tests/test_connection.py
A few things I had in my TODO list:
~openingd: Fix the _fall through_ in `handle_peer_in` switch. It now errs when receiving msg type that is a protocol violation, which happens in `test_fee_limits`. So fixed that too and, while at it, also solved a FIXUP.~
~openingd: in  `handle_peer_in`, tidy up  the switch statement. Now easier to follow and more redundant.~
**EDIT2**: Dropped the above
pytest: solved a FIXUP in `test_fee_limits` 
Improve the description of `dev-no-reconnect`, it took me a while to figure out its behavior.
Log PID's of plugins, I needed this for the dbbackup plugin, but maybe it is also useful for debugging
=> plugins: log PID of starting plugins, and some other small fixes

tools/gen/impl_template, wire/tlvstream.c
- Small fix for the way 'variable-length, variable-sized' subtype objects are allocated. Discovered while working on wire-tests for the dual-funding proposal that nests witness_elements into witness_stacks.
- Allow `towire_`'s to pass NULL in for the TLV field, if they want to.
=> wire gen fixups

CHANGELOG.md, doc/PLUGINS.md, lightningd/notification.c, lightningd/notification.h, lightningd/opening_control.c, tests/plugins/misc_notifications.py, tests/test_plugin.py
This adds a new notification type : `channelopened`.
This notification is emitted if a peer successfully opened a channel to us, and sends the id of the peer, the funding amount, and the feerate.
=> Plugins: 'channel_opened' notification type

.travis/build.sh, CHANGELOG.md, contrib/pylightning/lightning/lightning.py, contrib/pylightning/lightning/plugin.py, doc/PLUGINS.md, doc/lightning-plugin.7, doc/lightning-plugin.7.txt, lightningd/Makefile, lightningd/lightningd.c, lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_control.c, lightningd/plugin_control.h, lightningd/plugin_hook.c, lightningd/plugin_hook.h, tests/plugins/static.py, tests/test_plugin.py
~~This PR adds a new RPC command : `reloadplugins`, which will initialize and configure each plugin from the default directory (`~/.lightning/plugins/`) *-or from another passed as parameter-* that were not already loaded at lightningd startup.~~
This PR has mutated to now add a `plugin` RPC command : https://github.com/ElementsProject/lightning/pull/2771#issuecomment-505914017.
This permits to manage plugins without having to restart lightningd.
=> RPC plugin management

Makefile, doc/INSTALL.md, tools/mockup.sh, tools/test/Makefile, tools/update-mocks.sh
This makes it build for me on FreeBSD 11:
1. $(MAKE) has to passed through into update-mocks.
2. FreeBSD sed doesn't turn \n into a newline on RHS.
3. Bash and mako dependencies were missing from INSTALL.md
Fixes: #2850
=> FreeBSD: fix build.

CHANGELOG.md, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/plugin.c
Load any plugins directly as well as subdirs.
@darosior What do you think?  Completely untested!
=> plugins: document and extend the ~/.lightning/plugins/ dir.

devtools/credit
Lisa's git name is lower-case, whereas CHANGELOG.md uses upper case,
so it doesn't realize she's named a commit already.
=> devtools: fix credit script.

tests/requirements.txt
this should partially fix #2879 
this dependency seems to be needed in `tools/generate-wire.py`
=> added mako dependency to tests/requirements.txt

doc/lightning-invoice.7, doc/lightning-invoice.7.txt, lightningd/invoice.c
Hopefully this helps confused users (like I was) better understand warnings "No channels have sufficient incoming capacity" after calling `invoice`.
=> doc: invoice manpage, add some details about route hint selection

CHANGELOG.md, lightningd/peer_control.c
The reason lnd was sending sync error was that we were taking more than
30 seconds to send the channel_reestablish after connect.  That's
understandable on my test node under valgrind, but shouldn't happen normally.
However, it seems it has at least once,
(see https://github.com/ElementsProject/lightning/issues/2847)
: space out startup so it's less likely to happen.
Suggested-by: @cfromknecht
=> lightningd: avoid thundering herd on restart.

CHANGELOG.md, doc/PLUGINS.md, lightningd/invoice.c, lightningd/notification.c, lightningd/notification.h, lightningd/peer_htlcs.c, lightningd/peer_htlcs.h, tests/plugins/forward_payment_status.py, tests/test_plugin.py, wallet/test/run-wallet.c, wallet/wallet.c
A notification for topic `forward_event` is sent every time the status of a forward payment is set. The json format is same as the API `listforwards`.
Now when the forwad payment status changes, we'll store forward payments with the new status into DB. This notification will notify subscribers after storing operation.
```json
{
"forward_event": {
"payment_hash": "f5a6a059a25d1e329d9b094aeeec8c2191ca037d3f5b0662e21ae850debe8ea2",
"in_channel": "103x2x1",
"out_channel": "103x1x1",
"in_msatoshi": 100001001,
"in_msat": "100001001msat",
"out_msatoshi": 100000000,
"out_msat": "100000000msat",
"fee": 1001,
"fee_msat": "1001msat",
"status": "settled",
"received_time": 1560696342.368,
"resolved_time": 1560696342.556
}
}
```
or
```json
{
"forward_event": {
"payment_hash": …
```
=> Plugin: Another new notification type, forward_event

gossipd/routing.c, tests/test_gossip.py
Found while reviewing code being modified for #2890
=> gossipd/routing.c: Correctly handle a duplicated entry in `exclude` of `getroute`.

channeld/channel_wire.csv, channeld/channeld.c, lightningd/channel_control.c
We currently send channel_announcement as soon as we and our
peer agree it's 6 blocks deep.  In theory, our other peers might
not have seen that block yet though, so delay a little.
This is mitigated by two factors:
1. lnd will stash any "not ready yet" channel_announcements anyway.
2. c-lightning doesn't enforce the 6 depth minimum at all.
We should not rely on other nodes' generosity or laxity, however!
Next release, we can start enforcing the depth limit, and maybe stashing
ones which don't quite make it (or simply enforce depth 5, not 6).
=> channeld: delay sending channel_announcement by 60 seconds.

CHANGELOG.md, Makefile, doc/PLUGINS.md, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/plugin.c, tests/test_closing.py, tests/test_pay.py, tests/test_plugin.py
Now we have dynamic plugins, the difference in cwd becomes an issue.  Make it uniform, and bandaid for now.
=> Plugin cwd cleanup

plugins/autoclean.c, plugins/libplugin.c, plugins/libplugin.h, plugins/pay.c
This adds the management of the two fields added in #2771 to libplugin and defaults the `dynamic` field to `false` for `pay` and `autoclean`.
For the `startup` field in `init` I added the configuration JSON token to the plugin's callback : so that if we add new fields they can be accessed too.
=> libplugin: add new 'getmanifest' field and pass configuration to init callback

contrib/plugins/helloworld.py, contrib/pylightning/lightning/plugin.py, tests/plugins/dblog.py, tests/plugins/fail_htlcs.py, tests/plugins/hold_htlcs.py, tests/plugins/hold_invoice.py, tests/plugins/pretend_badlog.py, tests/plugins/reject.py, tests/plugins/reject_odd_funding_amounts.py, tests/plugins/reject_some_invoices.py, tests/plugins/shortcircuit.py
We recently noticed that the way we unpack the call arguments for hooks and
notifications in pylightning breaks pretty quickly once you start changing the
hook and notification params. If you add params they will not get mapped
correctly causing the plugin to error out.
This can be fixed by adding a `VAR_KEYWORD` argument to the calbacks, i.e., by
adding a single `**kwargs` argument at the end of the signature. This commit
adds a check that such a catch-all argument exists, and emits a warning if it
doesn't.
It also fixes up the plugins that we ship ourselves.
=> pylightning: Warn users of plugins that may break due to extra args

lightningd/log.c
Otherwise we bleed plugin log messages to stderr, as they're initted before log-file.
=> log: make --log-file an early arg (since we move to dir early now).

lightningd/plugin.c
It's here, but we don't use it.
I think I forgot to remove it while moving the `dynamic` field to the `configuration` object in the `init` call in #2771.
=> Plugins nit: Remove the 'signal_startup' member of the plugin struct

lightningd/lightningd.c, tests/test_plugin.py
This is a followup to #2892. Since we now attempt to lock the PID file before
starting plugins we need to make sure that we actually use a unique lightning
directory for anything that attempts to call `--help`. If not we may be
conflicting with a `lightningd` that is running against that directory.
The we also defer creating the PID until we actually want to start. This was causing `--help` to fail if we already had a `lightningd` running
with the same `--lightning-dir`.
=> Help in testdir

contrib/pylightning/lightning/lightning.py, lightningd/jsonrpc.c
This removes the trailing `dev-rhash` code in lightningd/jsonrpc.c since it was replaced by `dev` in #2814. It updates Pylightning accordingly to #2814 changes (as in #2771 three methods `dev_rhash`, `dev_slowcmd` and `dev_crash` have been prefered upon a `dev` method with a subcommand parameter).
This finally adds a verbose description to the dev command and a CHANGELOG line for JSON API changes.
=> Remove trailing 'dev-rhash' code, updates about 'dev' command

tests/test_connection.py
This test is spawning 100 nodes concurrently, which is a lot even when not
running with `valgrind`, especially when executing tests in parallel.
=> pytest: Make test_funding_cancel_race SLOW_MACHINE compatible

lightningd/peer_htlcs.c, tests/test_misc.py
We're actually only killing the connection.  I saw this in my logs, but it was all OK.
=> lightningd: don't say 'killing channel' when HTLC times out.

cli/lightning-cli.c, tests/test_misc.py, tests/test_plugin.py
@renepickhardt has a shell script we broke (see https://github.com/renepickhardt/lightning-helpers/blob/master/listfunds/listfunds.sh).  While we still produce perfectly valid JSON, we should not gratuitously change tool output.
Plus, I prefer the missing space before the ':'.
I've tested that his script now works again.
=> cli: restore 0.7.0-style whitespace printing.

doc/PLUGINS.md, lightningd/lightningd.c
And make sure that plugins know that they should not touch things until their init call.
=> doc: fix up documentation about when we move into lightning-dir.

CHANGELOG.md, lightningd/bitcoind.c, lightningd/bitcoind.h, lightningd/gossip_control.c, tests/test_db.py, wallet/wallet.c, wallet/wallet.h
As noted in #2756 we were not closing old channels, i.e., channels below our
wallet birth height.The cause was that the outpoints where not re-initialized
upon restart, since we didn't store the result of the txout lookup in the
database at all, hence not looking for spends.
This PR addresses this by extending the way we backfill the blocks in the
database on demand as we get `channel_announcements`. Instead of fetching the
block header, the list of transaction IDs and then checking the single txout,
we now fetch the raw block, filter out any uninteresting outpoint, i.e., not
outpoints that are not P2WSH, and then look up all of the remaining outpoints
in `bitcoind`s UTXO.
This is much more involved, since we process the entire blocks and look up all
of the outpoints, instead of just the …
=> Backfill blocks in the database as needed for gossip

Makefile, doc/Makefile, doc/lightningd-config.5, doc/lightningd-config.5.txt, doc/lightningd.8.txt
=> doc/lightningd.8.txt: Initial manpage for lightningd itself.

contrib/startup_regtest.sh, devtools/mkcommit.c
Fixes a parameter mis-ordering in `mkcommit`; adds a flag to the `contrib/startup_regtest.sh`.
=> Some very tiny changes 

channeld/full_channel.c, doc/lightningd-config.5, doc/lightningd-config.5.txt, lightningd/lightningd.h, lightningd/opening_control.c, lightningd/options.c
Eclair has a default value of 30 and I thought why not going with their value and while doing so make it configureable.
@cdecker suggested to call the option  `max_concurrent_htlcs` instead of the name in the BOLTs `max_concurrent_htlcs`
Here is the relevant line in eclair:
https://github.com/ACINQ/eclair/blob/9afb26e09c69dd5d6a14732baf5dcdf2b7a9142b/eclair-core/src/main/resources/reference.conf#L62
=> Added possibility to configure max_concurrent_htlcs value 

CHANGELOG.md, contrib/pylightning/lightning/lightning.py, doc/lightning-close.7, doc/lightning-close.7.txt, lightningd/peer_control.c, tests/test_closing.py, tests/test_connection.py, tests/test_pay.py, wallet/test/run-wallet.c
Fixes: #2791 
Painful transition, but I think a long-term win for sane defaults.
=> close: change parameters, defaults

lightningd/opening_control.c
=> lightningd: fix crash when peer disconnects after fundchannel_start, before cancel/complete

README.md, doc/INSTALL.md, lightningd/opening_control.c
We haven't touched the readme for quite some time, just randomly added to it,
and it's starting to show. This is my attempt at cleaning it up a bit (more to
come):
- No longer discourage users from running on mainnet, we're way beyond that
point.
- No longer instruct users to build from source, when we have real binary
releases, on the PPA, the releases page and the docker images.
- Cut down on the docker specific instructions, they are taking a lot of room
when only a minority will likely run them that way
- Generally make the README more of a dispatch for more in-depth
documentation rather than trying to address everything right on the
front-page.
- Add a bit of context about running on top of a pruned node
This is by no means a final version, but I needed to get started somewhere, and …
=> readme: First pass at homogenizing the readme a bit

tests/test_connection.py
As per https://github.com/ElementsProject/lightning/pull/2931#pullrequestreview-273008099.
This tests using the reproducible informations given by @rsbondi in https://github.com/ElementsProject/lightning/issues/2831#issuecomment-517023112
=> fundchannel_start crash: Add a test

lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, tests/test_db.py, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
Fixes error introduced by 1dbdc74bc where fundchannel
can cause a crash after start if the max dbid is for a closed
channel.
=> Fix `fundchannel` crash

lightningd/jsonrpc.c
I suspect multiple plugins trying to connect at the same
time are overrunning the 1-deep listen queue:
From man listen(2):
The backlog argument defines the maximum length to which the  queue  of
pending  connections  for sockfd may grow.  If a connection request ar‐
rives when the queue is full, the client may receive an error  with  an
indication  of ECONNREFUSED
Fixes: #2922
=> lightingd: increase listen queue on rpc socket.

CHANGELOG.md, common/jsonrpc_errors.h, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.txt, lightningd/bitcoind.c, lightningd/bitcoind.h, lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, tests/btcproxy.py, tests/test_misc.py, tests/utils.py, wallet/test/run-wallet.c
This adds warning fields in getinfo, as well as preventing obviously-problematic operations when we're not synced.  We assume once we're synced, we stay synced, however.
Fixes: #2770
=> Bitcoin syncing checks

devtools/Makefile
=> devtools: make clean should remove devtools/gen_print_onion_wire.[c,h,o]

ccan/README, ccan/ccan/htable/htable.h, ccan/ccan/htable/htable_type.h, ccan/ccan/htable/test/run-type.c, ccan/ccan/htable/test/run.c, ccan/ccan/pipecmd/pipecmd.c, ccan/ccan/pipecmd/pipecmd.h, tests/test_invoices.py, tests/test_pay.py
Dynamic plugins were keeping fds open; they should not have these
at all anyway, but worse, they interfere with operation because
we don't notice they're closed.
The symptom was that shutdown of the test_plugin_slowinit and
test_plugin_command was 30 seconds (10 seconds grace to kill each daemon).
=> ccan: update to fix shutdown slowness after plugin load.

lightningd/peer_htlcs.c
Returning an UPDATE failcode from a plugin hook crashes, since the next hop's channel id
was passed in as NULL. Fixed by passing in channel id for next hop.
```
2019-08-15T00:19:49.639Z **BROKEN** lightningd(17070): FATAL SIGNAL 11 (version v0.7.2rc1-8-gbf3b77a-modded)
2019-08-15T00:19:49.639Z **BROKEN** lightningd(17070): backtrace: common/daemon.c:45 (send_backtrace) 0x55fef4ef036f
2019-08-15T00:19:49.639Z **BROKEN** lightningd(17070): backtrace: common/daemon.c:53 (crashdump) 0x55fef4ef03bf
2019-08-15T00:19:49.639Z **BROKEN** lightningd(17070): backtrace: (null):0 ((null)) 0x7f7762401f1f
2019-08-15T00:19:49.639Z **BROKEN** lightningd(17070): backtrace: lightningd/peer_htlcs.c:104 (fail_in_htlc) 0x55fef4edd9d7
2019-08-15T00:19:49.639Z **BROKEN** lightningd(17070): backtrace: …
```
=> Fix crash when failing add_htlc with UPDATE failcode

CHANGELOG.md, doc/lightning-listforwards.7, doc/lightning-listforwards.7.txt, lightningd/peer_htlcs.c
There's a forward on one of my node's that's missing a payment_hash, which caused a crash when calling `listforwards`. This patch fixes the crash, not sure what the root cause is.
```
2019-08-14T17:50:39.100Z **BROKEN** lightningd(11355): FATAL SIGNAL 11 (version v0.7.2rc1)
2019-08-14T17:50:39.100Z **BROKEN** lightningd(11355): backtrace: common/daemon.c:45 (send_backtrace) 0x563349d07879
2019-08-14T17:50:39.100Z **BROKEN** lightningd(11355): backtrace: common/daemon.c:53 (crashdump) 0x563349d078c9
2019-08-14T17:50:39.100Z **BROKEN** lightningd(11355): backtrace: (null):0 ((null)) 0x7efd7b996f1f
2019-08-14T17:50:39.100Z **BROKEN** lightningd(11355): backtrace: ccan/ccan/str/hex/hex.c:59 (hex_encode) 0x563349d57fec
2019-08-14T17:50:39.100Z **BROKEN** lightningd(11355): backtrace: …
```
=> rpc: fix crash 'listforwards' when payment_hash is empty

Makefile, tools/test/Makefile
This simplifies the dependencies:
1. Objs depend on headers, not other objs.
2. Programs depend on objs.
3. A .o file will generally implicitly depend on the .c file it's built from.
4. If a file has a build line, it's often better to list all deps there.
5. I spotted some missing 'make clean' files.
The particular problem in this case seems to be that make would use
tools/test/gen_test.c before it was ready.  It's probably confused by
the use of recursive make via update-mocks, so explicitly split that
into two stages.
=> Makefile: fix occasional race where we fail to compile tools/tests.

Makefile, doc/MAKING-RELEASES.md, tools/build-release.sh, tools/test/Makefile
You can apply the first two one-liners (by hand) temporarily to fix up the reproducible build for the v0.7.2 release too.
Fixes #2970
=> Release scripts and docs update, with YA build fix.

contrib/init/lightningd.service
I added `Wants=network-online.target` in #2643, but it looks like that's not enough. Adding `After` seems to help, at least on Ubuntu 18.04.
=> systemd: After=network-online.target

lightningd/jsonrpc.c
Though I don't know the meaning of name `ctx`, it's a most common abbreviation.
We'd better use `ctx` other than `cxt`.
...BTW, could you tell me what's the full name of `ctx`?
=> cleanup: Use the most common abbreviation of 'ctx' in `json_tok_address_scriptpubkey`

lightningd/invoice.c, lightningd/json.c, lightningd/json.h, lightningd/jsonrpc.c, lightningd/notification.c, lightningd/pay.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, lightningd/test/run-invoice-select-inchan.c, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
As [discussed](https://github.com/ElementsProject/lightning/pull/2799#discussion_r301034098), now the `payment_hash` use `struct sha256`.
=> Cleanup for `payment_hash`

tools/gen/impl_template, tools/generate-wire.py
Our TLV serializer relies on TLV outputs to be ordered by type
number. Prior to this commit we relied on 1) the ordering in the
RFC to be correct and 2) users to be using a version of Python that
respects stable ordering of dicts (i.e. Python 3.7+)
Instead of relying on these implicitly, we now explicitly sort messages
by type number when the TLV sets.
Resolves #2956.
Thanks-To: @ScottTre for the sort function
Reported-By: @ZmnSCPxj
=> wire-gen: ensure that tlv messages are correctly ordered

contrib/bootstrap-node.sh, contrib/startup_regtest.sh
In contrib/bootstrap-node.sh line 7:
if type lightning-cli >/dev/null 2>&1; then
^-- SC2039: In POSIX sh, 'type' is undefined.
In contrib/startup_regtest.sh line 41:
type lightning-cli || return
^-- SC2039: In POSIX sh, 'type' is undefined.
In contrib/startup_regtest.sh line 42:
type lightningd || return
^-- SC2039: In POSIX sh, 'type' is undefined.
=> contrib: make stricter shellcheck from Ubuntu 18.04 happy

doc/lightning-fundchannel_complete.7, doc/lightning-fundchannel_complete.7.md, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md
As per https://github.com/ElementsProject/lightning/issues/2983#issuecomment-523354987.
=> doc: fix wording for fundchannel_complete

Dockerfile
This one is not strictly needed, but I figured out that it is weird that arm32 and arm64 are on stretch, but not amd64.
It is also weird to download some third party binaries for having `glibc` available on alpine.
It is also one less moving part when trying to find a bug (like this one https://github.com/ElementsProject/lightning/issues/2977).
=> [Docker] Use stretch-slim instead of Alpine

contrib/pylightning/lightning/lightning.py, contrib/pylightning/tests/test_millisatoshi.py, doc/HACKING.md
This is useful when using stuff like `sum()` on an array of Millisatoshis etc. that would otherwise throw an TypeError, i.e.:
```
$ lightning-cli helpme
"Error while processing helpme: TypeError(\"unsupported operand type(s) for +: 'int' and 'Millisatoshi'\")"
```
I tested this RP with a version of the `helpme` plugin that was iterating on a `Millisatoshi` list.
Also a unittest is in-place that can/should be enriched with further `Millisatoshi` related tests.
=> pylightning: adds Millisatoshi __radd__ method

CHANGELOG.md, wallet/wallet.c, wallet/walletrpc.c
I thought I was going to need this for the `fundchannel` branch, but it ended up being extra. It's a nice thing to expose anyway, as plugins and other apps might need it.
=> listfunds: add 'blockheight' for confirmed transactions

openingd/openingd.c, tests/fixtures.py, tests/utils.py
Fixup a few gotchas with the test fixtures around it deleting log files and not killing all the nodes properly  on memleak errors.
Also fixes a memleak error in `openingd`; exposed by the fundchannel plugin move.
=> Test fixture fixes and a memleak

tests/test_wallet.py, wallet/wallet.c
Change outputs from withdrawn (and tx_prepare'd) transactions aren't being marked as confirmed since they aren't being added to our txfilter; this fixes this.
=> Track withdrawal change

CHANGELOG.md, lightningd/lightningd.c
This adds a custom `option_set_` function for the `config_dir` in order to handle relative paths for the `--lightning-dir` option.
Fixes #3023.
=> lightningd/options: Make a specified lightning_dir absolute

CHANGELOG.md, bitcoin/tx.c, bitcoin/tx.h, common/funding_tx.c, common/json_helpers.c, common/json_helpers.h, common/json_tok.c, common/json_tok.h, common/utxo.c, common/utxo.h, common/withdraw_tx.c, common/withdraw_tx.h, contrib/pylightning/lightning/lightning.py, doc/lightning-txprepare.7, doc/lightning-txprepare.7.md, hsmd/hsm_wire.csv, hsmd/hsmd.c, tests/test_wallet.py, tools/generate-wire.py, wallet/wallet.h, wallet/walletrpc.c, wire/fromwire.c, wire/towire.c, wire/wire.h
Fix #2679 
- Change the paramaters of ~`withdraw` and~ `txprepare` :
~*withdraw* 'output' ['feerate'] ['minconf']~
*txprepare* 'output' ['feerate'] ['minconf']
The 'output' is the array of outputs that must specify 'destination' and 'satoshi'.
Its format is like:
[{'destination': address1, 'satoshi': satoshi1}, {'destination': address2, 'satoshi': satoshi2}, ...]
or
[{'destination': address, 'satoshi': "all"}]).
~There's also 2 related questions:~
~1. Do you think this `output` array is suitable?~
~2. About the test `test_mutiple_withdraw`, it looks a bit duplicative with `test_withdraw`. Should I merge these two tests?~
**EDIT:** Remove the change of *withdraw*, only make *txprepare* support mutiple outputs.
---
=> API: `txprepare` for multiple outputs

CHANGELOG.md, common/bolt11.c, common/bolt11.h, common/features.c, common/features.h, common/test/run-bolt11.c, common/test/run-features.c, devtools/Makefile, devtools/bolt11-cli.c, lightningd/invoice.c, plugins/Makefile, tests/test_pay.py
=> BOLT11 feature support

tests/fixtures.py
My machine would accumulate a number of zombie lightningd and bitcoind
processes over time while testing. Investigating this showed that if a fixture
raised an exception during fixture teardown then other fixtures that have not
been torn down would linger around. The issue is that pytest treats exceptions
in fixtures as non-recoverable and therefore will not catch them and call the
remaining ones.
The first commit adds a new fixture, that is there just to collect eventual errors
from other fixtures and ensure that anything that needs to clean up something,
e.g., processes started by the fixture, are cleaned up before we raise an
eventual exception. This is achieved by making any fixture that needs cleaning
up dependent on the teardown_checks fixture, which also serves as central
point to …
=> pytest: Collect errors in teardowns and allow running in ramdisk

lightningd/notification.c, lightningd/notification.h, lightningd/peer_htlcs.h
I remember @rustyrussell  [said](https://github.com/ElementsProject/lightning/pull/2799#discussion_r308490161),  we should avoid the extra line change in `const char *notification_topics[]` when we plan to add new notifications(in fact, I want to add `sendpay_success` and `sendpay_failure` notifications).
I guess using `autodata` to register notifications is an available way and I rewrite notification interfaces.
=> Plugin: Use `autodata` to register notifications

lightningd/bitcoind.h
This type is unused. It seems can be removed?
=> bitcoind: Remove unused type `bitcoind_mode`

CHANGELOG.md, doc/PLUGINS.md, lightningd/notification.c, lightningd/notification.h, lightningd/pay.c, lightningd/pay.h, tests/plugins/sendpay_notifications.py, tests/test_plugin.py
Long long ago, @ZmnSCPxj [mentioned](https://github.com/ElementsProject/lightning/pull/2188#issuecomment-448423897) `sendpay_success` and `sendpay_failure` notifications.
My first thought was to combine these two case into one notification type, `sendpay_result`.
But I found the `json` fields are two different between `sendpay` success and failure, so finally I divided `sendpay_result` into `sendpay_success` and `sendpay_failure` again.
For these two notification type, I still use the original notification interface, because I'm not sure whether #2944 is valid.
~I pre-present these ideas here though I'll wait for 0.7.3 to add `CHANGELOG`,~
=> plugin: `sendpay_success` and `sendpay_failure` notifications

CHANGELOG.md, configure, gossipd/gossip_store.c
(tested locally by turning `#if HAVE_PWRITEV` into `#if 0`)
Fixes: #3041
=> Fix build if pwritev does not exist (Mac)

CHANGELOG.md, channeld/channel_wire.csv, channeld/channeld.c, doc/lightning-fundchannel_cancel.7, doc/lightning-fundchannel_cancel.7.md, lightningd/channel.c, lightningd/channel.h, lightningd/channel_control.c, lightningd/channel_control.h, lightningd/opening_control.c, lightningd/peer_control.c, tests/test_connection.py, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c
Fix #2740 
This PR try to make `fundchannel_cancel` can work after `fundchannel_complete` and before funding broadcast.
The extended process is:
For funder:
- At the first, funder used `funderchannel_complete`; 
- Then funder calls `funderchannel_cancel`:
- funder check if the `fundchannel` process completed ==>
- If completed, funder check if its clightning has broadcast the funding and check if the funding has been onchain ==>
- If these 2 check pass, funder ask its `channeld` send a error message to fundee ==> 
- After sending error message, the funder delete(forget) the channel(also delete the peer, it's the limit of `delete_channel()`)
For fundee:
- After funder's `funderchannel_complete`, the channel state is `AWAITING_LOCKIN`. And the fundee begin to wait for funding locked both …
=> Fundchannel: extend `fundchannel_cancel` to work before funding broadcast

README.md
Next command is 
```bash
lightningd --network=bitcoin --log-level=debug
```
=> README: Remove '-testnet' bitcoind's argument

Makefile
Looks like it was struck by lightning.
Fixes #3059.
=> Bring back `fundchannel`

CHANGELOG.md, contrib/pylightning/lightning/lightning.py, doc/lightning-getroute.7, doc/lightning-getroute.7.md, gossipd/gossip_wire.csv, gossipd/gossipd.c, gossipd/routing.c, gossipd/routing.h, gossipd/test/run-crc32_of_update.c, gossipd/test/run-extended-info.c, lightningd/gossip_control.c, lightningd/gossip_msg.c, lightningd/gossip_msg.h, plugins/pay.c, tests/plugins/fail_htlcs.py, tests/test_gossip.py, tests/test_pay.py, tests/test_plugin.py, tools/generate-wire.py
Fixed #2894 
Following @ZmnSCPxj 's nice and clear proposal in #2894 , now `getroute` supports excluding `node`s by excluding all incoming channels of nodes.
=> JSON-API: `getroute` supports excluding `node`s

Makefile, doc/INSTALL.md
Makefile wasn't respecting adding things to LDFLAGS or CPPFLAGS. Besides general goodness, this is necessary to add the proper include paths to avoid a sqlite mismatch error when running the build with a newer version of sqlite installed (e.g. via brew).
Removed -dn & -dy from LDLIBS because clang doesn't understand them and they will cause --enable-static to fail on macOS. Since these are just debugging flags, and can still be passed in if someone really needs them, seems fine.
v0.7.2 wants Python 3.x + mako and make wants xgettext. I updated the docs to reflect  instructions for these additional dependencies to fix those breaks.
=> fix macOS build & update docs

doc/Makefile
Being already placed first in doc/index.rst, running `make doc-all` would mix them with `lightning-` commands (alphabetical order). This updates the rule in the Makefile to first append `lightningd` manpages, and then `lightning-` ones.
Off-subject of this PR, but about markdown manpages : I noticed some formatting errors due to `mrkd`. Since [the upstream repo is still active](https://github.com/refi64/mrkd/pull/1) I'll propose some other modifications to (hopefully) fix them and ask the maintainer to make a new release so we can finally use it normally.
=> Update doc/Makefile to place lightningd manpages first in readthedocs

common/status.c, plugins/pay.c, tests/test_pay.py
Related with my ['question' comment](https://github.com/ElementsProject/lightning/issues/2665#issuecomment-531479284)
I guess the original idea is to use the reverse order to traverse the entire route collection to find the worst channel/hop. I think it's the reason of the 'abnormal performance' in `test_pay_limits` if I'm right...
But the reverse order is hard to implement for our json interface, so I fix the logic with `json_for_each_arr`.
=> Pay plugin: Fix the traversal order in `find_worst_channel`

wallet/db_sqlite3.c
Seems I accidentally broke the fallback mechanism while working on the DB
abstraction.
Fixes #3049 
Fixes #3055
=> db: Get old sqlite3_trace based db_changes working again

CHANGELOG.md, doc/lightning-listfunds.7, doc/lightning-listfunds.7.md, wallet/walletrpc.c
This avoids having to correlate with listpeers for the most pertinent information.
Closes: #2882
=> jsonrpc: add more fields to listfunds.

plugins/autoclean.c, plugins/fundchannel.c, plugins/libplugin.c, plugins/pay.c
~For `usage` request, we should return NULL when `param()` fails (it must fail).~
~For normal, we'd better return `command_param_failed()` and free `command`.~
Ok, I find I made a mistake.
Now I think we should return `command_param_failed()` whether it's the `usage` case or not.
=> plugins: Return `command_param_failed()` if `param()` fail

.gitignore, Makefile, configure, devtools/sql-rewrite.py, doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/lightningd.h, lightningd/options.c, requirements.txt, tests/db.py, tests/fixtures.py, tests/requirements.txt, tests/test_closing.py, tests/test_connection.py, tests/test_db.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py, tests/utils.py, wallet/Makefile, wallet/db.c, wallet/db.h, wallet/db_common.h, wallet/db_postgres.c, wallet/db_sqlite3.c, wallet/invoices.c, wallet/test/run-db.c, wallet/test/run-wallet.c, wallet/wallet.c
This is the counterpart to #2924. It implements the postgresql driver for `lightningd`, the changes to the query rewriting script and the changes to the testing framework to select the DB to test against.
The tests can be run, if you have postgresql installed, using the `TEST_DB_PROVIDER=postgres` environment variable. The tests pass, with one exception `test_reserve_enforcement`, which I am still investigating, and the tests are a bit flaky when running in parallel.
Sadly I had to modify the migrations in order to add the information that `sqlite3` just glossed over (field size, foreign key enforcement in a transaction, autoincrement primary keys). Changing the migrations is something that I warned against back when I created the migration system, however it is safe to do here since we …
=> Postgresql driver for the multi-database abstraction

wallet/db.c
Otherwise we don't have a nul terminator:
Sep 22 02:25:42 lntxbot lightningd[804]: 2019/09/22 02:25:42 plugin-jqmethods Initialized jqmethods plugin.
Sep 22 02:30:01 lntxbot lightningd[804]: lightningd: FATAL SIGNAL 11 (version v0.7.2.1-255-g7686068)
Sep 22 02:30:01 lntxbot lightningd[804]: 0x561b03a0c6be send_backtrace
Sep 22 02:30:01 lntxbot lightningd[804]:         common/daemon.c:40
Sep 22 02:30:01 lntxbot lightningd[804]: 0x561b03a0c751 crashdump
Sep 22 02:30:01 lntxbot lightningd[804]:         common/daemon.c:53
Sep 22 02:30:01 lntxbot lightningd[804]: 0x7f1654d30f1f ???                                                                                                                                                                            Sep 22 02:30:01 lntxbot lightningd[804]: …
=> db: use correct backend for retrieving text fields.

wallet/walletrpc.c
=> fix: remove extra semicolon in `json_prepare_tx`

gossipd/routing.c, gossipd/routing.h, gossipd/test/run-crc32_of_update.c, gossipd/test/run-extended-info.c, lightningd/gossip_control.c, plugins/pay.c
Add I think this deserve a new helper: `json_out_add_u32`
=> cleanup: Use `u32` as the type of `max_hops` and `cltv`

contrib/pylightning/lightning/lightning.py, lightningd/pay.c
`description` is renamed as `label` in 0.7.0, so now use `label` as the field name in pylightning.
=> pylightning: Fix the parameter `label` of `sendpay` 

doc/INSTALL.md
Add missing dependencies in the developers' sections and re-order sections so that command can be copy-pasted in the order they appear in the documentation.
=> Fix ubuntu install documentation

Dockerfile, lightningd/lightningd.c
This should limit the overhead introduced by 25ddb8082369451024f471bc2d77fa7e7207cc47, specifically the loop calling syscalls here:
https://github.com/ElementsProject/lightning/blob/25ddb8082369451024f471bc2d77fa7e7207cc47/ccan/ccan/pipecmd/pipecmd.c#L141-L145
In some environments this would be way larger (e.g., running as root in docker), resulting in way more `close()` calls than intended. This PR limits the number of concurrent open fds, so we have to check and close a smaller range.
Ping @NicolasDorier 
Fixes #2977 
Fixes #3074
=> Set the rlimit for NOFILE to 1024 to reduce the subprocess cleanup

contrib/pylightning/lightning/lightning.py
Sometimes when calling getinfo before the node has started I get an int (concretely 2019) instead of a dict in resp, resulting in a TypeError when ```"error" in resp``` is checked, for ints are not iterable in that way.
Not a big deal, but I think a ValueError like when no "result" field is present would be more appropriate and clear.
=> pylightning: Responses may not be dict

common/gossip_constants.h, gossipd/gossip_wire.csv, gossipd/gossipd.c, gossipd/routing.c, gossipd/routing.h, gossipd/test/run-bench-find_route.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, gossipd/test/run-overlong.c, lightningd/closing_control.c, lightningd/gossip_control.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, tests/test_gossip.py
I tried increasing the prune interval, but we still had issues with --dev-fast-gossip reducing the gossip timeout causing unexpected "bad gossip" messages.
We can't make it too big, or our prune test will simply time out, so return to the original version where we had a setting for this test specifically.
=> Dedicated flag to decrease prune timeout

connectd/connect_wire.csv, connectd/connectd.c, connectd/tor_autoservice.c, connectd/tor_autoservice.h, doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/connect_control.c, lightningd/lightningd.h, lightningd/options.c, wallet/test/test_utils.c
Since V3 onions are now supported on most platforms and distros we can default to V3 on autotor service onions.
=> Change default behavior of autotor onions to Version 3 onions.

doc/requirements.txt
The new tag includes @cdecker's modifications for better list handling.
I've also [asked refi64 to make a new Pypi release](https://github.com/refi64/mrkd/issues/3) so that we can hopefully get rid of my branch in the doc requirements.
=> doc: update mrkd version

CHANGELOG.md, contrib/plugins/cowsay.sh, doc/lightning-plugin.7, doc/lightning-plugin.7.md, lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_control.c, lightningd/plugin_control.h, tests/plugins/broken.py, tests/plugins/slow_init.py, tests/test_plugin.py
#2996, the discussion in #3013, and the `lightningd` crash due to dynamic plugin errors as mentioned by @jb55 on IRC (,[and some plugin developers not that fine with the current implementation](https://github.com/ElementsProject/lightning/pull/2771#issuecomment-523299808),) made me think that I was wrong in how I implemented dynamic plugins. Since we had to fix the dynamic plugins crashes anyway, I rewrited it all to separate runtime paths of dynamic plugins from startup (and potentially critic) plugins at the expense of some code duplication.
This PR :
- removes dynamic-plugins-specific logic from lightningd/plugin.
- removes the middle state were plugins could end up on error : at startup they are either started or killed, via RPC they are either started or killed.
- removes the …
=> Refactor dynamic plugins

gossipd/gossipd.c
After the dev-suppress-gossip flag has been set via RPC this PR forces gossipd to set gossip level to GOSSIP_NONE for new peers we connect to.
Currently setting this flag does not appear to suppress gossip.
Signed-off-by: willcl-ark <will8clark@gmail.com>
=> [dev-suppress-gossip] - Set new peers to GOSSIP_NONE with flag enabled

lightningd/options.c
Make --announce-addr with autotor: also
a meaningful use case.
The option  --announce-addr=autotor: is more
intuitive than to use the --addr=autotor: option
Signed-off-by: Saibato <saibato.naga@pm.me>
=> Allow --announce-addr to work also with autotor: prefix

channeld/channeld.c, channeld/full_channel.c, lightningd/peer_htlcs.c
WIRE_REQUIRED_CHANNEL_FEATURE_MISSING anticipates a glorious Wumbo future,
and is closer to correct (it's a PERM failure).
=> channeld: reject wumbo payments with more style.

contrib/short_channel_id-to-txid.sh
Currently, short_channel_id-to-txid.sh is able to convert only sid based on the old formalism (with : as delimiter). This pull requests adds compatibility with the new standard (with : as deliminer) and slightly improves error messages in case an invalid sid is provided.
=> Add compability to current formalism to short_channel_id-to-txid.sh 

.travis/build.sh
Flaky tests send wrong signals, and we restart anyway. We should rather track
flakiness an open issues when they become too regular.
I have a script that is already scraping the travis results for failed tests, and I plan
to add a small dashboard, or even have it file issues for tests that are detected as
flaky. For now this just forces all tests to be treated as flaky so they are retried on
failure, but still leave a trace in the logs which can be picked up by my script.
=> travis: Force flaky on travis, they are becoming really annoying

lightningd/lightningd.c
Fix #3134. What is fun is that I noticed it while locally testing https://github.com/ElementsProject/lightning/pull/3132, but that all Travis tests pass (we always pass a `--network` at daemon startup).
This makes it `testnet` by default but maybe we want to default to mainnet ? :-)
=> lightningd: initialize the chainparams global in main.

bitcoin/tx.c, common/wallet.h, lightningd/chaintopology.c, lightningd/onchain_control.c, lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, onchaind/onchain_wire.csv, onchaind/onchaind.c, onchaind/test/run-grind_feerate-bug.c, onchaind/test/run-grind_feerate.c, tests/test_wallet.py, wallet/db.c, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c
We've been promising `listtransactions` for a while now, but it was kept back due to the annotations not being too useful since they don't have any association with inputs and outputs, and channel references could get clobbered if a transaction is associated with multiple transactions (splice anyone?).
This PR attempts to fix both of these by associating the annotations with the inputs and outputs that really give a transaction that facette (no longer clobbering channel references). Since the migration is not complete we still hide the annotation in `listtransactions` so people don't rely on them just yet, but we make `listtransactions` itself available.
`listtransactions` has details attached to each transaction, in the same format as `bitcoin-cli`'s `decoderawtransaction`, but I decided …
=> Make `listtransactions` non-experimental but keep annotations hidden for now

lightningd/options.c, tests/test_misc.py
This fixes #3136 and also makes it easier for plugins (to which we pass `ld->config_dir`).
=> Make lightning-dir absolute

CHANGELOG.md, contrib/pylightning/lightning/lightning.py, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md, doc/lightning-txprepare.7, doc/lightning-txprepare.7.md, lightningd/invoice.c, lightningd/json.h, lightningd/jsonrpc.c, lightningd/opening_control.c, lightningd/test/run-invoice-select-inchan.c, plugins/fundchannel.c, tests/test_connection.py, tests/test_wallet.py, wallet/walletrpc.c
Based to the [comment](https://github.com/ElementsProject/lightning/pull/2964#discussion_r317824584) with @niftynei .
As she said, it's better to rename `satoshi` to `amount`. `satoshi` is a bit confusing that you can specify the `satoshi` field as `2.999btc`.
=> JSON-API: `fundchannel` and `fundchannel_start` use `amount` as fieldname to replace `satoshi`

gossipd/queries.c
This PR : 
- MUST make `handle_query_short_channel_ids` respond with `complete` flag set to `0` when we are queried for an unknown `chain_hash`.
- MAY make `handle_reply_channel_range` and `handle_reply_short_channel_ids_end` fail the connection if the peer says it does not have up to date informations about our network. (related to https://github.com/lightningnetwork/lightning-rfc/pull/678)
=> query_messages: fail the connection if the peer is not on the same network

CHANGELOG.md, README.md, common/daemon.c, doc/lightningd-config.5, doc/lightningd-config.5.md, hsmd/hsm_wire.csv, hsmd/hsmd.c, lightningd/hsm_control.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, tests/test_wallet.py, tests/utils.py
This adds a new startup option which allows one to encrypt its `hsm_secret`, bearer of all its secrets. This uses the already-included (and amazing!) [`libsodium`](https://download.libsodium.org/doc/) with defaults (i.e. [Argon2id](https://github.com/p-h-c/phc-winner-argon2) for deriving a key out of the provided password, and [XChacha20_Poly1305](https://tools.ietf.org/html/draft-arciszewski-xchacha-03) for stream encryption).
This and https://github.com/ElementsProject/lightning/pull/2925 put, I think, the basis to have wallet locking. A plugin using the `rpc_command` hook to restrict the use of some RPC commands against a password, which can easily be bypassed if [it / `lightningd`] is killed, but not with an encrypted `hsm_secret`.
=> hsm_secret encryption

Makefile, configure
And update --enable-static, since it doesn't actually create a static
binary since 65fa1c4f39418d1728cae09bd20e9c0c9476bbff.
This might break static building on MacOS, but that AFAICT is a secondary priority.
Closes: #3102 
@NicolasDorier does this actually fix it for you?
=> Makefile: fix static linking.

gossipd/routing.c, gossipd/seeker.c
1. We were tending to give up on streaming gossip too soon when we have no gossip_store,
since we didn't count channel_updates on new channels correctly.
2. Our node_announcement probe was a bit useless: make it sample randomly instead.
3. Choose 5, not 3, peers to stream us gossip in steady-state.  This is less aggressive until we
have evidence that 3 is sufficient (if it is!), or we move to a more dynamic basis.
=> gossip seeker fixes

CHANGELOG.md, channeld/channeld.c, contrib/pylightning/lightning/lightning.py, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md, lightningd/channel.c, lightningd/channel.h, lightningd/opening_control.c, lightningd/peer_control.c, openingd/opening_wire.csv, openingd/openingd.c, tests/test_connection.py
Allow users to specify the `upfront_shutdown_script` via a new parameter on `fundchannel_start`.
=> Add `close_to` param for specifying upfront shutdown script

lightningd/options.c
~~Noticed it while working on decryption with an `hsmtools` plugin.. This can be workarounded but since the encryption functionality was not merged long time ago and we haven't released yet, probably better to just correct it now.~~
Some `hsm_secret` encryption corrections : 
- don't take the newline character into account when deriving the encryption key
- correct the salt length (...)
=> hsm encryption fixups

gossipd/routing.c
When we're in remove_all_gossip, we *don't* call free_chan, but free it
manually.  This trips over the developer-mode check that we called free_chan!
Make it also insert the magic so that destroy_chan_check passes:
lightning_gossipd: gossipd/routing.c:496: destroy_chan_check: Assertion `chan->sat.satoshis == (u64)chan' failed.
lightning_gossipd: FATAL SIGNAL 6 (version v0.7.3rc2-2-gf89d7c1)
0x5632436a4544 send_backtrace
common/daemon.c:41
0x5632436a45ea crashdump
common/daemon.c:54
0x7f053c3c7f5f ???
???:0
0x7f053c3c7ed7 ???
???:0
0x7f053c3a9534 ???
???:0
0x7f053c3a940e ???
???:0
0x7f053c3b9011 ???
???:0
0x563243698b9d destroy_chan_check
gossipd/routing.c:496
0x5632436dca46 notify
ccan/ccan/tal/tal.c:235
0x5632436dcf35 del_tree
ccan/ccan/tal/tal.c:397
0x5632436dd2c1 tal_free …
=> gossipd: don't crash if we're forced to discard corrupt gossip store.

common/wallet_tx.c, tests/test_connection.py, wallet/db.c, wallet/db.h, wallet/wallet.c
As far as I know this could only be tickled when migrating a DB over from sqlite3, but better be safe than sorry. I added `_or_default` access functions for `int` and `amount_msat` and will add more as the need arises. Furthermore I added checks for null fields when accessing them, so we always have to explicitly say whether we are ok with a default value or not.
This also includes a drive-by fix of a test that was broken because it was making assumptions on the UTXO selection being used.
Fixes https://github.com/fiatjaf/mcldsp/issues/1
=> db: Be a bit more pedantic about accessing null columns in the database

connectd/connectd.c
We were using `i` as index variable in two nested loops. This works as long as
the DNS seed resolves to a single address, but will crash if the node has both
an A as well as an AAAA entry, at which point we'll try to index the hostname
without a matching entry.
=> connectd: Do not clobber the for-variable when resolving over DNS

bitcoin/tx.c
`libwally` was getting upset when we were trying to be helpful, and we weren't too happy to see blinded value or asset commitments.
=> Fix elements after the libwally upgrade

contrib/Dockerfile.builder, contrib/Dockerfile.builder.i386
new dependency for this release means we need it for the release builds. I couldn't figure out how to add it for the fedora builds, but this seems to fix the breaks.
=> add gettext to build release script

tests/fixtures.py, wallet/db.c, wallet/db_common.h, wallet/test/run-db.c, wallet/test/run-wallet.c
Reverts the `assert` into a warning that we can watch for in the tests and logs, so we can fix them as they come up and then re-arm the asserts once we're happy that we have caught all of them. On postgres we'll still catch them given the field length check,
We also fix an upgrade related null field (which was the real cause for #3189), where we'd have a null field if a payment was forwarded inbetween commits 66a47d2 (which started tracking forwardings) and d901304 (which added the received_time column). Since this is a rare thing, and we can't really just remove a compat check later, I opted to just set these cases to 0.
Fixes #3189
=> Make pedantic checks less fatal, fix an upgrade related null field access

doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md
Before this change there was paragraph describing `feerate`, then paragraph describing `announce`, then again paragraph explaining `feerate` in more details. Does not make sense for me.
=> Change order of paragraphs in manpage of fundchannel

gossipd/queries.c
This reverts commit 7fd2f6db6dd326cdbcfd96f052850b4638f5fc93.
We want to set 'complete' to false in future if we don't know
everything!
=> Revert "gossipd: query_messages: fail the connection if peer says it does not have up-to-date infos"

common/read_peer_msg.c
This can get pretty large in some cases.
=> common: remove spammy debug msg.

gossipd/routing.c
Fix build error on 32bit linux:
```
gossipd/routing.c:496:31: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
assert(chan->sat.satoshis == (u64)chan); /* Raw: dev-hack */
^
gossipd/routing.c:496:31: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
assert(chan->sat.satoshis == (u64)chan); /* Raw: dev-hack */
^
gossipd/routing.c: In function ‘free_chan’:
gossipd/routing.c:510:23: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
chan->sat.satoshis = (u64)chan; /* Raw: dev-hack */
^
gossipd/routing.c: In function ‘remove_all_gossip’:
gossipd/routing.c:2982:21: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
c->sat.satoshis = (u64)c; /* Raw: dev-hack */ …
```
=> Fix build fail on 32bit OS.

CHANGELOG.md, lightningd/channel_control.c, lightningd/peer_htlcs.c, tests/test_connection.py
Thanks to DarthCoin and Javier for reporting this; simple to diagnose once I reproduced.
@cdecker had reports of similar issues with LND under stress, which we assumed was their end.  Oops, it was us!
=> Fix "Bad commit_sig signature" error.

lightningd/peer_control.c
Close #3208
i named it `lightning-dir` instead of `lightningd-dir`
or did you meant lightningd-dir where the executable is after compiling? @niftynei
=> json-rpc: show lightning-dir in getinfo

bitcoin/signature.c, bitcoin/signature.h
Close #3210 
* in contrast to Core I didnt include `bool grind` as a function argument. I can do that too if wanted - calling sign_hash() would require that arg everywhere, since C doesnt support default arguments.
=> wallet: always create signatures with low r-value

plugins/pay.c
When trying to pay an invoice from another network, I get the error message 'Could not find a route' (code 205).
That's not bad, it has to fail trying to find a route indeed.
But I think it would be nicer if it returned an error explicitly pointing out that the invoice to pay doesn't correspond with the network/chain this node is operating with.
The code I have doesn't seem to be working though, so any advice on this is very welcomed, assuming of course the concept makes sense in the first place.
I'm testing this with https://github.com/jtimon/multi-ln-demo/pull/4 
This is where I check the error: https://github.com/jtimon/multi-ln-demo/blob/master/multiln/bin/demo.py#L114
I don't expect people to run that, but I'm basically using the method pay() from contrib/pylightning.
I'm confused …
=> Different error when trying to pay an invoice from another network

tests/requirements.txt
psycopg2 need libpq-dev and python-dev, psycopg2-binary not requiring a compiler or external libraries
=> change psycopg2 to psycopg2-binary

ccan/ccan/json_out/json_out.h, connectd/connectd.c, gossipd/seeker.c, hsmd/hsmd.c, lightningd/channel.h, lightningd/htlc_end.c, lightningd/json_stream.h, lightningd/log.c, lightningd/plugin.c, lightningd/plugin.h, plugins/libplugin.h
I was wondering why TAGS was missing some functions, and finally
tracked it down: PRINTF_FMT() confuses etags if it's at the start
of a function, and it ignores the rest of the file.
So we put PRINTF_FMT at the end, but that doesn't work for
*definitions*, only *declarations*.  So we remove it from definitions
and add gratuitous declarations in the few static places.1
=> TAGS: reformat to fix when PRINTF_FMT() used.

devtools/sql-rewrite.py
On python 3.4.2 having kwargs after unpacking a dict in a function call seems to be a syntax error. I know it's an old python version but if it doesn't break anything else it might be worth changing.
=> Fix python 3.4 syntax error in sql-rewrite.py

common/gossip_store.c, common/gossip_store.h, devtools/dump-gossipstore.c, gossipd/gossip_generation.c, gossipd/gossip_store.c, gossipd/gossip_store.h, gossipd/gossipd.c, gossipd/gossipd.h, gossipd/routing.c, gossipd/test/run-crc32_of_update.c, gossipd/test/run-txout_failure.c, tests/test_db.py, tests/test_gossip.py
One real test fix, and a rework of our slightly-broken "push this msg through despite timestamp_filter" option which was causing many more "Bad gossip" order messages.
=> pytest: fix flaky 'Bad gossip' errors

common/wallet_tx.c, tests/test_misc.py
If you're replaying or syncing with the blockchain, show that error
instead of 'cannot afford', in the case of not having enough utxos
to pay for a transaction. This is the 'more correct' error to show, as
there's a chance that the funds you're expecting to spend are in the
portion of the blockchain that hasn't been synced yet.
=> Warnings: if behind blockchain, don't show cannot afford

devtools/gossipwith.c, gossipd/gossipd.c, gossipd/routing.c, gossipd/routing.h, tests/test_connection.py, tests/test_gossip.py, tests/test_pay.py
Test fixes and an actual gossipd improvement which also fixes tests.
Changelog-none: no user-visible changes
=> No bad gossip after close

lightningd/options.c
The current master throws a false line number
```
gorazd@gorazd-MS-7C37:~/Projects/lightning$ ./lightningd/lightningd
lightning config file line 3: line6: unrecognized option
```
for the following config file
```
network=regtest
log-level=info
line6
```
It should be:
```
gorazd@gorazd-MS-7C37:~/Projects/lightning$ ./lightningd/lightningd
lightning config file line 6: line6: unrecognized option
```
Changelog-None
=> config file: fix line count in error message

devtools/changelog.py, doc/MAKING-RELEASES.md, doc/STYLE.md
Since the `CHANGELOG.md` file is a major source for merge conflicts I decided
to build a tiny tool that generates the entries for the changelog
automatically from the commit messages.
Changelog-None
=> changelog: Add a tool to extract changelog entries from the commits

common/json.c, common/json.h, contrib/pylightning/lightning/lightning.py, doc/lightning-pay.7, doc/lightning-pay.7.md, plugins/pay.c, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py
[It got stuck into the red part of a diff](https://github.com/ElementsProject/lightning/pull/2215/files#diff-fc86e59a6aa3bf284fbaf6be349102d7L536)
=> Restore payment amount fuzzing

common/sphinx.c, devtools/gossipwith.c, gossipd/gossipd.c, gossipd/routing.c, gossipd/routing.h, tests/test_gossip.py
[ Based on #3245 to keep Travis happy: just look at last commit ]
https://github.com/lightningnetwork/lightning-rfc/pull/697
https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-November/002288.html
Reported-by: @roasbeef
Changelog-None
=> sphinx: fix potential data leak.

README.md, tests/test_wallet.py, tools/Makefile, tools/hsmtool.c
This closes #3177 as it is a concurrent version of the `hsmtools` functionalities.
Changelog-None
=> Non-plugin version of hsmtool

devtools/mkcommit.c
Needs to initialize global now.
Changelog-None
=> devtools: fix mkcommit crash.

common/addr.c, common/addr.h, contrib/startup_regtest.sh, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, plugins/Makefile, plugins/fundchannel.c, tests/test_connection.py, wallet/test/run-wallet.c, wallet/walletrpc.c
Make close-to address more visible by printing in `listpeers` channels.
=> Display `close_to` address in `listpeers`

lightningd/lightningd.c, lightningd/lightningd.h, lightningd/opening_control.c, lightningd/options.c, openingd/opening_wire.csv, openingd/openingd.c
--dev-force-tmp-channel-id flag takes a 64-character hex string
to use as the temporary channel id. Useful for spec tests where we want
to test the 'opener's side of things.
=> dev: add option flag for specifying temporary channel id

.travis/build.sh, Makefile
Travis adds the correct PYTHONPATH, but "make check" doesn't.
Changelog-None
=> pytest: fix `make pytest`

devtools/onion.c
Fixed 'generate' and 'decode' methods to properly parse argv arguments.
Fixed so methods correctly use the associated data set by the --assoc-data flag.
I also added some examples to -h to better show how these methods work with real onion data.
Introduced a behavioral change to read the onion from a file instead of stdin; this makes it easier to debug in some IDEs (eg. vscode).
=> devtools/onion: fixed argument passing for generate and decode methods

lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/peer_htlcs.c
This is required for the protocol tests, which can be slow.
Changelog-None
=> dev: add option to prevent HTLC timeouts.

Dockerfile
This was working up to the latest release because it was statically linked to the c-lightning binary.
Also, this does not fix arm32 and arm64.
The reason why I was "building my own" was because of docker cache layers, you might end up in a situation where you compiled on the build image on a different version of dependency that what end up installed in the runtime image. This happened to me already.
The cause of https://github.com/ElementsProject/lightning/issues/3074 comes from somewhere else.
Probably a change in the build system which does not build statically anymore?
Changelog-None
=> Revert "docker: Use system libraries, don't bring your own"

tests/test_wallet.py, wallet/wallet.c
Fixes https://github.com/ElementsProject/lightning/issues/3231
Ready for Review and Merge
=> fix: listtransactions crash #3231

gossipd/routing.c
It really, really doesn't matter.  But we were dramatically reducing
our view of the network:
In my gossip_store (mainnet):
channel_announcement: 30349
channel_update: 55119
node_announcment: 1783
Fixes: #3194
=> gossipd: don't discard node_announcements with old timestamps.

lightningd/lightningd.c
==1310== Conditional jump or move depends on uninitialised value(s)
==1310==    at 0x127C7F: io_loop_with_timers (io_loop_with_timers.c:30)
==1310==    by 0x14F0E1: plugins_init (plugin.c:1019)
==1310==    by 0x12E4B1: main (lightningd.c:694)
==1310==
Changelog-None
=> lightningd: fix uninitialized variable

contrib/pyln-testing/pyln/testing/utils.py, devtools/gossipwith.c, gossipd/queries.c, tests/test_gossip.py
See https://github.com/lightningnetwork/lnd/issues/3728
Tested and verified on my node, under valgrind.
=> Handle reply_channel_range from LND (and enhance gossipwith)

wallet/wallet.c
This will patch the `listtransactions` command in a way that the hard assert regarding `txindex` and blockheight is removed (https://github.com/ElementsProject/lightning/issues/3265). We will now set the `txindex` only if a blockheight is known.
**Also:** I do not believe the missing blockheights are reorg artifacts for two reasons:
- The `txindex` we have in the DB are the correct onchain `txindex` when looking up the proper block. Incase of a reorg artifact they are expected to be different, as they would have been replaced by a block with different index. If this is still reorg related, the reorg code does not write the correct blockheight BUT the txindex into the DB, which would be bad.
- they are too many to be a coincident., in my case 4 transactions on two nodes: mainnet and …
=> fix: listtx set txindex only if blockheight is known

common/sphinx.c, tests/test_plugin.py
So far we've only handled legacy payloads, which meant we could drop the realm
byte since it was always 0x00. Once we start handling TLV payloads the first
byte, i.e., the former realm byte, is important since it gives us the length
of the payload. This is a breaking change, however I don't think there's
anyone using the `raw_payload` as of yet.
Changelog-Changed: JSON-RPC: the `raw_payload` now includes the first byte, i.e., the realm byte, of the payload as well. This allows correct decoding of a TLV payload in the plugins.
=> plugin: Pass the full raw_payload including realm to htlc_accepted

external/Makefile
Requesting them is done by setting BUILD=<target_arch>
Otherwise autotools (used by external dependencies like
libsodium) is not happy with setting cross-compilation
variables and may possibly lead to unexpected results.
Changelog-None
=> Add cross-compilation options only when requested

bitcoin/signature.c, bitcoin/signature.h, devtools/mkcommit.c, devtools/mkfunding.c, devtools/mkgossip.c
Recent updates to the protocol tests mean that we can now use a privkey + hash to verify a signature; this updates the relevant `mkcommit/mkgossip` devtools to now provide this info for signatures.
=> devtools: Print hashes + privkeys for sigs

lightningd/bitcoind.c, lightningd/chaintopology.c, tests/test_db.py, tests/test_misc.py
This solves the underlying reason why #3243 was such a problem!
=> Never follow bitcoind backwards

doc/PLUGINS.md, lightningd/opening_control.c, openingd/opening_wire.csv, openingd/openingd.c, tests/plugins/accepter_close_to.py, tests/test_connection.py
I wanted to add this to dual_funding, but decided that it's better to not cram too much more into that than need be, so instead did this off of master.  This is more of a 'nice to have' now, but will be much more important come dual funded channels.
Rounds out the application of `upfront_shutdown_script`, allowing
an accepting node to specify a close_to address.
Prior to this, only the opening node could specify one.
Changelog-Added: Plugins: Allow the 'accepter' to specify an upfront_shutdown_script for
a channel via a `close_to` field in the result.
=> openchannel hook: add new `close_to` field

channeld/full_channel.c
Travis randomly picked up an error in test_feerate_stress:
**BROKEN** 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-channeld-chan#1: Cannot add htlc #0 10000msat to LOCAL (version a2541b9-modded)
This is because it hit an unlikely corner case involving applying multiple HTLCs
(similar to the previous c96cee9b8d0333d90edd04e309dfc229b5ee1a49).
In this case, the test sends a 500,000,000 "balancing" setup payment L1->L2.
It waits for L2 to get the preimage (which is the when pay() helper returns),
but crucially, it starts spamming with HTLCs before that HTLC is completely
removed.
From L2's point of view, the setup HTLC is in state RCVD_REMOVE_REVOCATION;
gone from L1's commitment tx, but still waiting for the commitment_signed
from L1 to remove it from L2's.
Note that …
=> channeld: allow transient negative balance.

lightningd/plugin.c, tests/test_misc.py
Addresses https://github.com/ElementsProject/lightning/issues/3206 and https://github.com/ElementsProject/lightning/issues/3281
This will restructure the `lightning-cli listconfigs` output in a way that plugins are not duplicated and have their options within a substructure like this:
```JSON
{
"# version": "v0.7.3-141-gabdc4af",
"lightning-dir": "/home/will/.lightning",
"wallet": "sqlite3:///home/will/.lightning/lightningd.sqlite3",
"plugins": [
{
"name": "autoclean",
"path": "/home/will/projects/lightning.git/lightningd/../plugins/autoclean",
"options": {
"autocleaninvoice-cycle": null,
"autocleaninvoice-expired-by": null
}
},
{
"name": "fundchannel",
"path": "/home/will/projects/lightning.git/lightningd/../plugins/fundchannel"
},
{
"name": "pay",
"path": …
```
=> feat: restructure plugin and options in listconfigs #3206

common/bolt11.c
Although BOLT11 says "a reader MUST check" I'm not sure "reader" refers specifically to the Lightning server.
Sometimes the reader may be an application and the application may want to decode the invoice first before looking for the full description somewhere else and then proceeding to check either on its own or by calling `decodepay` again.
Sometimes the reader is a final payer, but there are some circumstances, like a custodial wallet provider or some other [odd situations](https://devpost.com/software/txawaitbot) in which the Lightning server is not the _final payer_ and thus not the "reader" that should care about this.
Sometimes the "full description" is not a UTF-8 string. In these cases they may still be checked against the `description_hash` but it will be impossible to pass it …
=> don't enforce description_hash checking

contrib/pyln-testing/pyln/testing/fixtures.py, contrib/pyln-testing/requirements.txt, lightningd/options.c, tests/test_wallet.py
Just my usual collection of cleanups:
- Add `psycopg2-binary` instead of `psycopg2` as a `pyln-testing` dependency
- Fix our implicit reliance on `conftest.py` annotating our tests for directory clean
- Stabilize the hsm encryption and decryption tests
Changelog-None
=> cleanup: Stabilize the hsm encryption tests and fix dependencies

tools/Makefile, tools/hsmtool.c
This is the `static_remotekey`-only version of #3217 (since I noticed `to_remote` keys are (/were) actually derived from the *local* `per_commitment_point`, by the way if someone [could explains me why](https://github.com/ElementsProject/lightning/issues/2665#issuecomment-547409859) I'd be interested ^^).
I added a note to the README about it since all major implementations [will](https://github.com/ACINQ/eclair/pull/1141) implement it, it's likely that most of the newly created channels will enable `option_static_remotekey` in the near future and that this might be useful.
=> tool/hsmtool: add a 'guesstoremote' command

doc/HACKING.md
This one got missing when introducing `pyln` modules.
Changelog-None
=> doc: adds pyln contrib dependencies to the command for running blackbox tests

contrib/pyln-client/pyln/client/lightning.py, tests/test_misc.py
Addresses issue #2753, which describes the problem and exception that was being seen.
This change enables non-ascii characters such as emojis to be included in the description field via pylightning:
Have done a bit of testing by passing in ascii strings:  `\ud83d\udc7d` `\\\\udc74`  and  `\\udc7d` seem to work as being interpreted as literal ascii rather than some unicode character, which is what is intended. I suspect the JSON encoding/decoding is handling this correctly in this mode.
=> Pylightning: pass through non-ascii characters in the JSON input formatting

lightningd/options.c
cppcheck found this:
[lightningd/options.c:1137] -> [lightningd/options.c:1120] -> [lightningd/options.c:1193]: (error) Using pointer to local variable 'buf' that is out of scope.
Indeed, answer can point into buf, which is no longer in scope at the end.
Changelog-None
=> lightningd: fix reference to out-of-scope var.

doc/lightning-invoice.7, doc/lightning-listinvoices.7, doc/lightning-listinvoices.7.md, lightningd/invoice.c, lightningd/json.c, lightningd/json.h, lightningd/pay.c, lightningd/test/run-invoice-select-inchan.c, tests/test_pay.py
I'm sorry for this silly PR, but this has been bugging me for a long time. Being able to see the preimages of invoices issued is good for overall understanding of the protocol and for easy checking of payment proofs from others, not to mention other advanced uses (which may be covered by passing your own preimage to `invoice` as the docs imply, but still).
The point is that this doesn't hurt and makes everything better.
---
On https://t.me/lntxbot I like to show a lot of debugging information (because I'm crazy and I think users will want to understand what is happening): ![2019-11-25-231518_445x806_scrot](https://user-images.githubusercontent.com/1653275/69593905-71d00700-0fd9-11ea-9d74-cc2123ea1be1.png)
However, because I can't get the preimages my invoices are using from the `invoice` …
=> 'invoice' command returning preimage.

common/Makefile, common/base64.c, common/base64.h, common/wireaddr.c, common/wireaddr.h, connectd/Makefile, connectd/connectd.c, connectd/tor_autoservice.c, connectd/tor_autoservice.h, devtools/gossipwith.c, doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/Makefile, lightningd/json.c, lightningd/lightningd.h, lightningd/options.c, tests/test_gossip.py
We now can generate a V3 tor service address from a blob 
--addr=**statictor**:127.0.0.1:9051[/**torblob**=[blob]]
Or generate a unique static tor address bound to our node id /pub key     
--addr=**statictor**:127.0.0.1:9051
TODO:
EDIT: With this you are able to keep your public known or group known tor address static
and independent of torrc file or the tor instance ( if multiple ), in case you have to  
move your node to an other PC or system/phone, as long as there is a tor service
your node will be reachable even if ip, NAT, firewall have changed by that static V3 address.
EDIT: related issues #2476  #3085
EDIT_2:
With this PR we can now also select the extern tor port we assign our local port to 
--addr=**statictor**:127.0.0.1:9051[/**torblob**=[blob]][/**torport**=EXTERNPORT]
Or …
=> generate a static tor onion address persistent unique to the node id

doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md
It has a whole *two paragraphs* on it:
*feerate* is an optional feerate used for the opening transaction and as
initial feerate for commitment and HTLC transactions. It can be one of
the strings *urgent* (aim for next block), *normal* (next 4 blocks or
so) or *slow* (next 100 blocks or so) to use lightningd’s internal
estimates: *normal* is the default.
Otherwise, *feerate* is a number, with an optional suffix: *perkw* means
the number is interpreted as satoshi-per-kilosipa (weight), and *perkb*
means it is interpreted bitcoind-style as satoshi-per-kilobyte. Omitting
the suffix is equivalent to *perkb*.
=> doc: feerate is not obvious, refer to fundchannel documentation:

connectd/connectd.c, plugins/fundchannel.c, tests/test_connection.py
supercedes #3307 
still unclear to me what cases you can reconnect to a peer without their IP address, however.
=> fundchannel connect

lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_hook.c, tests/plugins/rpc_command.py, tests/test_plugin.py
I was playing with it for my boltathon tutorial prep, and it didn't hand this case (which, admittedly, is very nasty!).
I've put in a "plugin was destroyed" infra; please merge before Saturday :)  I can generalize it in future to an "object was destroyed" since we have a few other similar places...
Changelog-None
=> Fix rpc command hook

lightningd/jsonrpc.c, tests/plugins/rpc_command.py, tests/test_plugin.py
We need the id field if we redirect to another plugin (which subs the id), yet we handed the wrong argument so we didn't actually give it the full array.
We also didn't check it exists in the response, nor document it.
This adds that test case, and ratchets up the sanity checks for the hook.
Changelog-None
=> Fix rpc command hook: the missing id

doc/PLUGINS.md
It's required, so at least hint about its presence!
Changelog-None
=> doc: add 'id' to rpc_command

tools/hsmtool.c
fixes seg fault encountered when entering in too few args to `decrypt`
assuming argv is zero indexed, we should check that the argc count
is at least as big as the desired args.
Changelog-None
=> hsmtool: fixup miscount on params

CHANGELOG.md
`This release named by XZY.` is not a good sentence...
Alternatively we could go for just "Release named by XYZ".
Changelog-None
=> doc: correct wording in changelog

channeld/channeld.c, closingd/closingd.c, common/peer_failed.c, common/peer_failed.h, common/read_peer_msg.c, common/read_peer_msg.h, openingd/openingd.c, tests/test_closing.py, tests/test_connection.py, tests/test_pay.py
We still close the channel if we *send* an error, but we seem to have hit
another case where LND sends an error which seems transient, so this will
make a best-effort attempt to preserve our channel in that case.
Some test have to be modified, since they don't terminate as they did
previously :(
=> channeld: treat all incoming errors as "soft", so we retry.

tools/gen/impl_template, wire/test/run-peer-wire.c
This was harmless: we considered a single-chainid init message to be a 32-chainid message, and were leaving the other 31 uninitialized.  But it might not have been harmless if we added other TLV array fields.
Changelog-none
Fixes: #3301
=> Tlv parse fix

.travis/build.sh
Travis seems to have upgraded to a newer minor version of python3, so let's be
way less picky about which exact version we want to run against.
Changelog-None
=> travis: Make python environment selection less picky

contrib/pyln-testing/requirements.txt, tests/requirements.txt
Trying to `pip install psycopg2-binary==2.8.3` raised an error for a
long time. Since version `2.8.4` is recent and also seem to work I
suggest updating the requirements so other users dont run into the
following error, where pip tries to use `pg_config` for the BINARY
package:
```
Collecting psycopg2-binary==2.8.3 (from -r contrib/pyln-testing/requirements.txt (line 6))
Using cached https://files.pythonhosted.org/packages/80/91/91911be01869fa877135946f928ed0004e62044bdd876c1e0f12e1b5fb90/psycopg2-binary-2.8.3.tar.gz
ERROR: Command errored out with exit status 1:
command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zapr0fhs/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zapr0fhs/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, …
```
=> fix: pip dependency version for psycopg2-binary

contrib/Dockerfile.builder, contrib/Dockerfile.builder.fedora, contrib/Dockerfile.builder.i386, contrib/pyln-testing/requirements.txt
This will change some `requirements.txt` of pyln-testing in a way that
it does not require different package version i.e. to `tests/requirements.txt`.
The reason for this is that users are not forced to hassle with pyenv
or virtualenv and could just use `--user`.
```bash
pip install --user -r tests/requirements.txt -r contrib/pyln-testing/requirements.txt  # ...
```
Changelog-None
=> fix: normalize pip requirements

.travis/build.sh, Dockerfile, contrib/Dockerfile.builder, contrib/Dockerfile.builder.fedora, contrib/Dockerfile.builder.i386, contrib/linuxarm32v7.Dockerfile, contrib/linuxarm64v8.Dockerfile
Bitcoin-core v0.18.X is now the more widely used, so seems better to run the tests again this version ?
source: https://luke.dashjr.org/programs/bitcoin/files/charts/software.html
Changelog-None
=> Update bitcoin-core version

cli/lightning-cli.c
fixes  #3352
I at first made the `--rpc-file` option take over the `--lightning_dir` one, but we don't seem to be using the config dir in the cli anyway, so ..
=> cli: allow to specify only the --rpc-file option

connectd/peer_exchange_initmsg.c
As per https://github.com/lightningnetwork/lightning-rfc/pull/682#issuecomment-566066644.
We would always check against the first element of the array.. Once again my bad.
This also cleans up a redundant check as [pointed out](https://github.com/ElementsProject/lightning/pull/3300#discussion_r352380389) by @rustyrussell.
Changelog-None
=> connectd: check all chain hashs of the network array in `init`

lightningd/plugin_control.c, tests/test_plugin.py
I found the json output
```
{
"": "Successfully stopped reckless.py."
}
```
a bit weird.
=> plugin_control: more descriptive key for 'plugin stop' result

lightningd/lightningd.c, lightningd/lightningd.h, lightningd/plugin_control.c
Since they are currently spawned with a umask of 0 (set when daemonizing), plugins will create files with 666 and directory with 777 permissions. This might not be a big deal but `22` may be a more expected default for plugin developers ?
=> "plugin start": spawn plugin processes with a non-0 umask

contrib/pyln-client/pyln/client/lightning.py, contrib/pyln-client/pyln/client/plugin.py, doc/PLUGINS.md, tests/test_closing.py, tests/test_misc.py
I bumped into a couple of issue with long path names for the lightning socket. This PR adds a wrapper for UNIX sockets that uses a short alias in `/proc/self/fd` if possible.
It also fixes a small issue with accessing `__annotations__` without checking whether it exists first (Reported by @jarret here https://github.com/lightningd/plugins/pull/70).
And finally the torture test is just really unreliable under `valgrind`, often timing out on Travis. The logic is tested in countless other tests, so there shouldn't be anything that `valgrind` can add here.
Changelog-None
=> Some minor cleanups for tests and pyln

lightningd/peer_control.c, lightningd/watch.c, wallet/wallet.c, wallet/wallet.h
we don't populate the tx item when we're running a transaction check from deep chain (prior to a chain replay). this change allows us to remove the null check on `tx` where we do verification on the funding tx.
I'm not sure this is a desirable change; these transactions have been seen and processed by c-lightning already, so the check is redundant. On the other hand, I think removing the possibility of skipping the check is worth the added lookup as it decreases the risk of new code changes inadvertently disabling it by failing to populate `tx`.
Changelog-None
=> wallet: remove edgecase around transaction checks

lightningd/plugin_hook.c, lightningd/plugin_hook.h, tests/test_db.py, wallet/db.c, wallet/db.h, wallet/db_common.h, wallet/test/run-db.c, wallet/test/run-wallet.c
Currently the `db_write` hook is a simple sink to which we write, but a plugin
has no way of telling whether there were any gaps or whether the `lightningd`
database lost some updates. This PR introduces a numeric `data_version` that
is incremented on any dirty transaction. A ditry transaction is a DB
transaction that performed some changes on the underlying database.
The `data_version` is guaranteed to change between successive changes, however
it does not guarantee monotonicity (i.e., it can wrap around at 2**32). Its
goal is to assert to a plugin that no changes to the DB have been performed by
c-lightning between successive calls to `db_write`. The `data_version`
persists across restarts so a plugin can check whether it matches a backup
after startup.
In addition this PR implements an …
=> Add a `data_version` to the `db_write` hook an implement optimistic locking

Makefile
https://github.com/ElementsProject/lightning/releases/download/v0.8.0/clightning-v0.8.0.zip
extracts into "clightning-v0.8.0".
https://github.com/ElementsProject/lightning/archive/v0.8.0.tar.gz
extracts into "lightning-0.8.0".
Tweak the regular expression in the Makefile to support both (extract
0.8.0 from either one). Also, downloading an arbitrary version, based on
git commit id:
https://codeload.github.com/ElementsProject/lightning/tar.gz/eb2b225c?dummy=/filename_this_is_irrelevant.tar.gz
extracts into "lightning-eb2b225c".
so, support extracting "eb2b225c" from that.
Changelog-None
=> build: fix version extraction from non-git directory

connectd/tor.c
The tor proxy might want auth 0x2 or answer what ever not defined
in https://tools.ietf.org/html/rfc1928.
Changelog-Fixed: We don't send any further request if the return code of connect is not zero or error.
=> Tor: Fix an edge case where the connect answer is not zero and not error.

doc/INSTALL.md
Given you're building `master`, OpenSSL is no longer required after https://github.com/bitcoin/bitcoin/pull/17265.
Libsodium has never been required to build bitcoind on macOS.
Changelog-None
=> doc: openSSL is no longer required to build bitcoind

tests/test_db.py, tests/test_gossip.py, tools/hsmtool.c
Fixing some pytest tests that were failing on my local machine or the CI I'm working on.
- `DEVELOPER=0` + `VALGRIND=1` + an expected node failure don't combine that well, since the backtrace can't find debug symbols
- The TOR tests didn't really format their options correctly, this remained undiscovered since apparently no dev is running TOR locally, except me ;-)
- `hsmtool` was assuming the `$cwd` is on the same partition as the lightning-dir.
=> Minor driveby cleanups

lightningd/notification.c, lightningd/notification.h, lightningd/pay.c, lightningd/pay.h, lightningd/peer_htlcs.c, tests/plugins/sendpay_notifications.py, tests/test_plugin.py, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
Sendpay notifications would get sent only if we have an active watcher, and multiple times if we have more than one watcher. This kind of defeats the point since we can't just fire and forget sendpay and wait for the notification if that notification is bound to the watchers.
This PR fixes that by pulling the notification out of the watcher loop, concentrating the error message allocation in a single place, and inverting ownership of `wallet_payment_store`. This also reduces a couple of useless allocations, since we don't store, free, then reload the `wallet_payment` anymore.
Fixes #3403
=> Always notify if a `sendpay` payment attempt is resolved

contrib/pyln-client/pyln/client/lightning.py
Little fix for `pyln-client`'s `super().__init__` call. Now passing `logger` instead of `logging`, otherwise keyword argument `logger` was not used.
=> pyln-client/LightningRpc: fixed logger in super()

Makefile
Before this change `make` would build everything but the docs.
They would be built during `make install` which is unexpected.
Add a dependency to `doc-all` to the `default` target so that docs are
build together with the rest of the programs. Leave the `install-data`
as is, to still build the docs if they are not built yet during install.
Changelog-None
=> doc: also build docs when building everything else

doc/INSTALL.md
Now that c-lightning is in the FreeBSD ports system (\o/)
update the installation instructions, which basically boil down
to just `pkg install c-lightning`.
Changelog-None
=> doc: update FreeBSD installation instructions

wire/Makefile
It's been brought to my attention that BusyBox's `patch` binary doesn't support the `--silent` option. (nor `quiet`, as of patch `020abc8856f94d6e355f4daa972ac75fb05ae113` on the busybox master branch).
This patch removes the silent flag from the patch command used to build the wire csv files. Only affects experimental builds.
Changelog-None
=> remove `--silent` flag from patch in wire/Makefile

common/jsonrpc_errors.h, doc/lightning-disconnect.7, doc/lightning-disconnect.7.md, doc/lightning-fundchannel_cancel.7, doc/lightning-fundchannel_cancel.7.md, doc/lightning-fundchannel_complete.7, doc/lightning-fundchannel_complete.7.md, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md, doc/lightning-listchannels.7, doc/lightning-listchannels.7.md, doc/lightning-listpeers.7, doc/lightning-listpeers.7.md, lightningd/opening_control.c
Add "peer not connected" and "unknown peer" as error codes, so that
users can check against numeric error codes instead of textual error
messages.
Will ease https://github.com/ElementsProject/lightning/issues/3366
Changelog-None
=> common: add 2 specific error codes wrt funding

channeld/channeld.c, common/sphinx.c, common/sphinx.h, devtools/onion.c, lightningd/peer_htlcs.c, wallet/test/run-wallet.c
Generally I prefer structures over u8, since the size is enforced at
runtime; and in several places we were doing conversions as the code
using Sphinx does treat struct secret as type of the secret.
Note that passing an array is the same as passing the address, so
changing from 'u8 secret[32]' to 'struct secret secret' means various
'secret' parameters change to '&secret'.  Technically, '&secret' also
would have worked before, since '&' is a noop on array, but that's
always seemed a bit weird.
Changelog-None
=> sphinx: use struct secret for shared secret.

contrib/pyln-client/pyln/client/lightning.py
We were not specifying the `jsonrpc` field in JSONRPC request produced by pyln. Uncovered this while refactoring libplugin, it made plugins crash (during functional tests, but not by-hand tests!) if we check for its presence.
=> pyln: actually specify jsonrpc in requests

doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/jsonrpc.c, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c
Fixes: #1366
Arguably also works for #3394.  It is probably more sensible to set permissions via this patch and `--rpc-file-mode`, since this will work in a new install or if you place the RPC file in a `tmpfs` (which might make more sense as well, so that at startup the rpc file does not exist yet, so you can wait on the file existing to determine if you can now connect to it and the correct lightningd already is listening).
=> lightningd/jsonrpc.c: Set JSON-RPC socket permissions by command line.

bitcoin/block.c, bitcoin/block.h, common/sphinx.c, devtools/onion.c, tests/test_pay.py
Turns out https://github.com/ElementsProject/lightning/pull/3246 did not actually do anything. We flipped two buffers and were not actually using the chacha20 stream. The buffer we were initializing with the chacha20 stream was simply being overwritten in the next iteration. We need to initialize the `packet->routinginfo` instead.
Keeping this as a draft until we've resolved the broken test-vectors in lightningnetwork/lightning-rfc#697
Changelog-None
=> sphinx: Actually use the pad stream to generate the packet

common/withdraw_tx.c, contrib/pyln-client/pyln/client/lightning.py, tests/test_wallet.py
Fixes two crashes/bugs I found in `txprepare`:
1) using `txprepare` in keywords mode in `pyln-client` would crash (fails an check for what version of the API you're using) 
2) crash when attempting to specify more than two outputs
=> txprepare fixes

.github/CODEOWNERS
This was factored out into a separate `plugins/pay`, though I
am still not prepared to take over that.
ChangeLog-none
=> .github/CODEOWNERS: Remove nonexistent module.

lightningd/options.c
Builds on @NicolasDorier previous fix, I think this is even more effective at avoiding the confusing doubling-up of rpc-file.
Changelog-None
=> Migration: remove rpc file

lightningd/options.c
json_listconfigs() returns in the middle; the name0 is not always freed.
It will be freed later with the response, but our memleak detection doesn't
know that, and Travis caught it:
```
Global errors:
E            - Node /tmp/ltests-5mfrzh5v/test_hsmtool_secret_decryption_1/lightning-1/ has memory leaks: [
E               {
E                   "backtrace": [
E                       "ccan/ccan/tal/tal.c:437 (tal_alloc_)",
E                       "ccan/ccan/tal/tal.c:466 (tal_alloc_arr_)",
E                       "ccan/ccan/tal/tal.c:794 (tal_dup_)",
E                       "ccan/ccan/tal/str/str.c:32 (tal_strndup_)",
E                       "lightningd/options.c:1122 (add_config)",
E                       "lightningd/options.c:1282 (json_listconfigs)",
E …
```
=> lightningd: fix memleak false positive.

bitcoin/block.c, bitcoin/block.h, contrib/pyln-testing/pyln/testing/utils.py
This implements support for the upcoming `elementsd` dynafed block header
format, which is slightly different from either the bitcoin block header
format as well as the `elementsd` <= 0.17.0 block header format. A couple of
fields were added, 3 different serialization formats for the information
(`null`, `compact` and `full`) and some of those fields are not hashed into
the block hash, since they'd be self-referential (like the pre-0.18.0 solution
field).
In order to implement this I chose to also simplify the block hash generation,
to happen in parallel with the deserialization. This has a couple of
side-effects:
- The block hash is computed only once, instead of multiple times when we
call `bitcoin_block_blkid`. For compatibility I left that function, but it
now just copies over the …
=> Implement dynafed block header support for elements >= 0.18.1

lightningd/chaintopology.c, lightningd/chaintopology.h
Note to the reader: this is a classic bug, and yes, it was me who made it (and realized what it was once I finally tracked it down, since I've made it before!).  Learn from my mistakes: comparing with a freed pointer is always dangerous, even if you think it's OK!
If the same memory gets reallocated, our "has the tip changed?" test
gets a false negative.  This happened for me about one time in 10,
causing tests/test_misc.py::test_funding_reorg_remote_lags to fail.
Changelog-None
=> lightningd: fix reorg bug where we don't fire watches.

lightningd/peer_htlcs.c, lightningd/plugin.c, tests/test_plugin.py
Changelog-Removed: Relative plugin paths are not relative to startup (deprecated v0.7.2.1)
Changelog-Removed: Dummy fields in listforwards (deprecated v0.7.2.1)
=> lightningd: remove things we deprecated 6 months ago.

common/Makefile, common/errcode.h, common/json.c, common/json.h, common/json_command.h, common/jsonrpc_errors.h, common/test/run-param.c, connectd/connect_wire.csv, connectd/connectd.c, doc/lightning-waitinvoice.7, doc/lightning-waitinvoice.7.md, lightningd/connect_control.c, lightningd/invoice.c, lightningd/jsonrpc.c, lightningd/jsonrpc.h, lightningd/notification.c, lightningd/notification.h, lightningd/pay.c, lightningd/pay.h, lightningd/test/run-invoice-select-inchan.c, lightningd/test/run-log-pruning.c, plugins/libplugin.c, plugins/libplugin.h, plugins/pay.c, tools/generate-wire.py, wallet/test/run-wallet.c, wire/fromwire.c, wire/towire.c, wire/wire.h
Before this patch we used `int` for error codes. The problem with
`int` is that we try to pass it to/from wire and the size of `int` is
not defined by the standard. So a sender with 4-byte `int` would write
4 bytes to the wire and a receiver with 2-byte `int` (for example) would
read just 2 bytes from the wire.
To resolve this:
* Introduce an error code type with a known size:
`typedef int32_t errcode_t`.
* Change all error code macros to constants of type `errcode_t`.
Constants also play better with gdb - it would visualize the name of
the constant instead of the numeric value.
* Change all functions that take error codes to take the new type
`errcode_t` instead of `int`.
* Introduce towire / fromwire functions to send / receive the newly added
type `errcode_t` and use it instead of …
=> Use dedicated type for error codes

.travis.yml, .travis/build.sh, Makefile, contrib/pylightning/lightning/__init__.py, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyln/proto/bech32.py, contrib/pyln-proto/pyln/proto/invoice.py, contrib/pyln-proto/requirements.txt, contrib/pyln-proto/tests/test_invoice.py
This is pretty much the lnaddr.py file created by @rustyrussell with some minor changes. I'm planning to clean this up further which is why I'm only exporting the `Invoice` class for now.
Changelog-None
=> pyln: Have travis check pyln-proto and add invoice utilities

doc/lightning-connect.7, doc/lightning-connect.7.md, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md, doc/lightningd.8, doc/lightningd.8.md
ChangeLog-Fixed: Clarified about connection in documentation.  Also, `fundchannel`  already `connect`s if your node knows how to contact the desired peer for a few versions now, so clarify documentation about this as well.
=> doc/: Doc clarifications regarding connecting and funding.

bitcoin/tx.c, bitcoin/tx.h, channeld/commit_tx.c, common/close_tx.c, common/funding_tx.c, common/htlc_tx.c, common/initial_commit_tx.c, common/utxo.c, common/utxo.h, common/withdraw_tx.c, common/withdraw_tx.h, devtools/mkclose.c, hsmd/hsm_wire.csv, hsmd/hsmd.c, onchaind/onchaind.c, tests/test_wallet.py, wallet/walletrpc.c
This sets the nLockTime to the tip (and accordingly each input's nSequence to
0xfffffffe) for withdrawal transactions.
Even if the anti fee-sniping argument might not be valid until some time yet,
this makes our regular wallet transactions far less distinguishable from
bitcoind's ones since it now defaults to using native Segwit transactions
(like us). Moreover other wallets are likely to implement this (if they
haven't already).
Changelog-Added: wallet: withdrawal transactions now sets nlocktime to the current tip.
=> wallet: set nLockTime to the tip for withdrawal transactions

bitcoin/tx.c, bitcoin/tx.h, channeld/channeld.c, channeld/commit_tx.c, common/initial_commit_tx.c, common/permute_tx.c, hsmd/hsm_wire.csv, hsmd/hsmd.c, openingd/openingd.c, tools/generate-wire.py, wire/fromwire.c, wire/towire.c, wire/wire.h
Added output_witscripts, remote_per_commit and option_static_remotekey  to hsm_sign_remote_commitment_tx to allow complete validation.
=> hsmd: Added fields to hsm_sign_remote_commitment_tx to allow complete validation.

doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/subd.c, lightningd/test/run-find_my_abspath.c
This PR adds --alt-subdaemon to facilitate substituting a standard subdaemon with an alternate.
Examples:
lightningd --alt-subdaemon=lightning_hsmd:remote_hsmd ...
lightningd --alt-subdaemon=lightning_hsmd:/some/where/remote_hsmd ...
=> lightningd: Added --alt-subdaemon command to allow alternate subdaemons.

Makefile, external/.gitignore, external/Makefile
Ideally we would support out-of-source-tree builds. But until then we can at least separate the external dependencies per architecture.
The problem I ran into is that we want to cache external dependencies in CI. But this means that the cached files are compiled for the wrong host when we cross-compile.
This PR will compile all dependencies outside their soure trees. The "native" files will stay in `external`. cross compiled files will go into `external/<host-triplet>` like `external/aarch64-linux-gnu`.
The first time you build this PR you might need to wipe your dependencies. Since currently we are building "in-source-tree" automake will complain loudly if you try to build "out-of-source-tree" without cleaning up first.
Changelog-None
=> Separate external by host

doc/PLUGINS.md, lightningd/invoice.c, lightningd/jsonrpc.c, lightningd/plugin_hook.c, tests/plugins/dblog.py, tests/plugins/hold_invoice.py, tests/plugins/reject_some_invoices.py, tests/plugins/rpc_command.py
Changelog-Changed: The hooks `db_write`, `invoice_payment`, and `rpc_command` now accept `{ "result": "continue" }` to mean "do default action", in addition to `true` (`db_write`), `{}` (`invoice_payment`), and `{"continue": true}` (`rpc_command`). Eventually the older "default" indicators will be deprecated, but for now they will be supported, but logged as `UNUSUAL` level.
=> lightningd/: Hooks now support a consistent interface for 'no operation'.

plugins/autoclean.c, plugins/fundchannel.c, plugins/libplugin.c, plugins/libplugin.h
A follow-up to #3443, requested [here](https://github.com/ElementsProject/lightning/pull/3443#discussion_r374413965).
Changelog-None
=> libplugin: make deprecated_apis a global, don't expose struct plugin

ccan/README, ccan/ccan/bitmap/bitmap.h, ccan/ccan/json_out/json_out.h, ccan/tools/configurator/configurator.c, configure
This was necessary for cross-compiling. Otherwise the configurator will be compiled for the host architecture.
Here are my scripts for cross compiling with docker, if you want to reproduce:
https://github.com/NickeZ/bitbox-base/commit/cf7c4e851638d547891351bf57dca8197310239e
Thanks
=> Add CONFIGURATOR_WRAPPER

bitcoin/tx.c, channeld/commit_tx.c, common/initial_commit_tx.c
Consider this a minimal fix of #3487, there are a couple of other places in which we don't `tal_resize` the `output_witscript` array to the correct length, but I'll fix those up in a cleanup PR.
Closes #3487 
Changelog-None
=> Fix regression in hsmd for elements-based chains

Makefile, ccan/ccan/opt/opt.c, ccan/ccan/opt/opt.h, lightningd/plugin.c, lightningd/plugin_control.c, plugins/autoclean.c, plugins/fundchannel.c, plugins/libplugin.c, plugins/libplugin.h, plugins/pay.c, tests/plugins/Makefile, tests/plugins/test_libplugin.c, tests/test_plugin.py
This is a follow-up to #3443 (based on it and implements the first of the left TODOs).
This moves all plugins from "raw" `jout`s to using higher-level `json_stream` helpers.
This also adds sanity functional tests for libplugin plugins, which uncovered a bug.
=> libplugin: use json stream helpers and add sanity tests

contrib/pyln-testing/pyln/testing/utils.py, tests/test_pay.py
This will add and use a simple wait_for_htlcs() helper that will resolve once
all HTLCs on all channels resolve. Just something I found out to be useful when writing some plugin tests.
=> pyln-testing: add wait_for_htlcs helper

doc/lightning-listchannels.7, doc/lightning-listchannels.7.md
Changelog-Fixed: Fixed factual errors in `lightning-listchannels.7` documentation.
`delay` is ***not*** the unilateral close delay for that channel-direction!
=> doc/lightning-listchannels.7.md: Fix factual errors.

channeld/channeld.c, lightningd/channel_control.c, lightningd/channel_control.h, tests/test_connection.py
There's a few small, subtle bugs currently in `fundchannel_cancel`:
-  one: the remote peer can call `fundchannel_cancel` while waiting for lockin. it's debatable whether or not this is desirable. for now it seems prudent to remove the capability altogether.
- two: if you attempt to cancel a channel while the peer is offline, your node will crash
this PR addresses both of these issues. note that `forget_channel` is currently exposed because in a later commit (in the dual funding branch) i'm using it elsewhere.
=> Fixup fundchannel_cancel

doc/PLUGINS.md, lightningd/invoice.c, lightningd/jsonrpc.c, lightningd/opening_control.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, lightningd/plugin_hook.c, lightningd/plugin_hook.h, tests/plugins/hook-chain-even.py, tests/plugins/hook-chain-odd.py, tests/test_plugin.py
This pull request creates the infrastructure for registering multiple plugins
for a given hook and showcases this new capability with the `htlc_accepted`
hook. The `htlc_accepted` hook was chosen due to its relative simple semantics
and because it currently is the hook with the most plugins making.
Before you could only use a single plugin that registers the `htlc_accepted`
hook at a time, which was severely limiting its uses. With this you can
finally run multiple at the same time.
The `htlc_accepted` hook returns one of the following three outcomes:
- `{"result": "continue"}`: the plugin signals that it could not handle the
HTLC internally, so the chain continues. If there are more plugins that
have registered for this hook they get called, otherwise we handle
internally.
- `{"result": …
=> Allow hook chaining for the `htlc_accepted` hook

ccan/README, ccan/ccan/opt/opt.c
This was caught by valgrind on Travis, and really confused me.
See https://github.com/rustyrussell/ccan/commit/4f20b75c6133425f2b8c369bb1ecfbd7d3410353
Changelog-None
=> ccan: update to include opt_unregister fix.

channeld/full_channel.c, lightningd/peer_control.c, tests/test_connection.py, tests/test_invoices.py, tests/test_pay.py
This is a previously-discussed problem (as shown in https://github.com/lightningnetwork/lightning-rfc/issues/728 ) but @m-schmoock wrote a proof-of-concept in #3498 so I am pushing a mitigation for the imminent release.
The funder pays the onchain fees: this keeps it simple.  If the funder has spent all their funds, they obv. can't use the channel, but the fundee also cannot: most implementations will not add an HTLC if the funder could not afford the resulting fee (c-lightning included).  If we were to loosen that, I'm not sure how other implementations would respond :(
The simplest workaround is to keep a little extra around if we're the funder.  It's still possible to get into a state (particularly with fee changes) where we're stuck, but this makes it less likely.
=> Channel lockup corner case workaround

tests/test_plugin.py
I'm pretty sure #3502 fixed the reason I made `test_libplugin` @flaky.
=> pytest: make the libplugin test non flaky

Makefile, common/jsonrpc_errors.h, lightningd/bitcoind.c, lightningd/bitcoind.h, lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/channel_control.c, lightningd/lightningd.c, lightningd/options.c, lightningd/peer_control.c, lightningd/plugin.c, lightningd/plugin.h, lightningd/test/run-invoice-select-inchan.c, plugins/Makefile, plugins/autoclean.c, plugins/bcli.c, plugins/libplugin.c, plugins/libplugin.h, tests/plugins/bitcoin/part1.py, tests/plugins/bitcoin/part2.py, tests/test_closing.py, tests/test_misc.py, tests/test_plugin.py, wallet/test/run-wallet.c, wallet/wallet.c, wallet/walletrpc.c
This standardizes our requests for Bitcoin data as a set of commands plugins can register, and makes our `bitcoind` interaction through `bitcoin-cli` the default plugin, which registers all of these commands.
This makes it possible to not rely on a bitcoin-core backend, which can help for instance for mobile integration (cf #3484).
See #3354 for some design decisions, but here is a summary:
- Separated plugins can register different calls, which allows plugins specialization (credits to @cdecker)
- Uses JSON-RPC commands instead of hooks (see #3354).
- Needs 5 commands to be registered by our plugin(s):
-  `getchaininfo` - called at startup to get infos about our network, and about the block chain.
-  `getrawblockatheight` - get the block at that height in hex format, along with its id.
- …
=> Bitcoin backend generalization

plugins/libplugin.c
Spark does this, for example:
{"method":"pay","params":["lnbc..."],"id":22}
Which doesn't have a jsonrpc field.  The result is that the command
doesn't terminate, there is nothing in the logs, stderr contains
"pay: JSON-RPC message does not contain "jsonrpc" field", and
from then on "Unknown command 'pay'".
Changelog-None (regression this version)
=> plugins: libplugin don't insist on 'jsonrpc' field from lightningd.

plugins/pay.c
If the attempt hasn't started yet, we can have an empty 'attempts' array
(while it's in listpeers, for example):
```
pay: plugins/pay.c:1457: json_paystatus: Assertion `tal_count(ps->attempts)' failed.
pay: FATAL SIGNAL 6 (version v0.8.1rc1-1-g946af3f)
0x55e895110543 send_backtrace
common/daemon.c:39
0x55e8951105e9 crashdump
common/daemon.c:52
0x7f92b0928f1f ???
???:0
0x7f92b0928e97 ???
???:0
0x7f92b092a800 ???
???:0
0x7f92b091a399 ???
???:0
0x7f92b091a411 ???
???:0
0x55e895100012 json_paystatus
plugins/pay.c:1457
0x55e895103aaa ld_command_handle
plugins/libplugin.c:968
0x55e895103bd4 ld_read_json_one
plugins/libplugin.c:1011
0x55e895103cd2 ld_read_json
plugins/libplugin.c:1030
0x55e895124cbd next_plan
ccan/ccan/io/io.c:59
0x55e89512583a do_plan
ccan/ccan/io/io.c:407
0x55e895125878 …
```
=> pay: fix crash when we paystatus too soon.

CHANGELOG.md, lightningd/notification.c, lightningd/notification.h, lightningd/peer_htlcs.c, wallet/test/run-wallet.c, wallet/wallet.c, wallet/wallet.h
If the peer is not connected, or other error which means we don't actually create an outgoing HTLC, we don't record the short_channel_id.  This is unhelpful!
Pass the scid down to the wallet code, and explicitly hand the scid and amount down to the notification code rather than handing it the htlc_out (which it doesn't need).
=> db: put scids in forwards even if we didn't actually send.

CHANGELOG.md, gossipd/routing.c
Thanks to @s-tikhomirov  for the great bug report!
Fixes: #3517
Changelog-None
=> Find shorter route assertion

lightningd/jsonrpc.c
I reproduced this by putting a sleep(60) in the pay plugin, then
'lightning-cli pay', 'lightning-cli plugin stop pay' and then ^C
the `lightning-cli pay`:
2020-02-14T00:33:11.217Z INFO plugin-pay: Killing plugin: pay stopped by lightningd via RPC
2020-02-14T00:33:15.250Z DEBUG lightningd: Still waiting for initial block download
==5157== Invalid read of size 8
==5157==    at 0x12A29C: destroy_jcon (jsonrpc.c:149)
==5157==    by 0x1C6F2A: notify (tal.c:235)
==5157==    by 0x1C7441: del_tree (tal.c:397)
==5157==    by 0x1C7493: del_tree (tal.c:407)
==5157==    by 0x1C77DD: tal_free (tal.c:481)
==5157==    by 0x1B7380: io_close (io.c:450)
==5157==    by 0x1B71A7: do_plan (io.c:401)
==5157==    by 0x1B7214: io_ready (io.c:417)
==5157==    by 0x1B94AC: io_loop (poll.c:445)
==5157==    by …
=> lightningd: fix crash when plugin has been unloaded and we abort cmd.

contrib/pyln-proto/requirements.txt, contrib/pyln-testing/pyln/testing/utils.py, doc/HACKING.md
- update dependency coincurve to version 13
- points out in HACKING that all requirements.txt are required
- testutils  ln.pay()  now checks return status of waitsendpay
=> cleanup requirements and minor stuff

lightningd/notification.c, openingd/openingd.c
We don't compile with NDEBUG defined, but if we did, this code would
vanish.  I did a quick audit, inspired by @ZmnSCPxj.
I actually hacked up something to compile with NDEBUG (many unused vars
resulted, and of course unit tests are allowed to rely on assert()), and
after this the testsuite still passes.
=> lightningd, openingd: remove active code inside assert().

doc/lightning-listpeers.7.md
=> doc/lightning-listpeers.7.md: Clarify `spendable_msat`.

common/wallet_tx.c, doc/lightning-txprepare.7, doc/lightning-txprepare.7.md, tests/test_wallet.py
fixes #3533.
Maybe we could allow unconfirmed utxos ?
=> txprepare: don't crash on unconfirmed utxos

Makefile
Don't let make pollute subprojects' environment with our own `CFLAGS`,
which are quite strict because that breaks at least libwally-core:
```sh
$ ./configure ...
$ CFLAGS=whatever_this_is_irrelevant make
...
cd external/libwally-core-build && ../libwally-core/configure ...
...
CFLAGS                  = -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\"" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -std=gnu11 -g -fstack-protector  -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/libbacktrace-build -I . -I/usr/local/include   -DCCAN_TAKE_DEBUG=1 -DCCAN_TAL_DEBUG=1 -DCCAN_JSON_OUT_DEBUG=1 -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS …
```
=> build: unbreak if CFLAGS is defined in make's env

lightningd/lightningd.c, lightningd/lightningd.h, lightningd/plugin.c, lightningd/plugin_control.c, lightningd/plugin_hook.c, tests/plugins/hook-crash.py, tests/plugins/slow_init.py, tests/test_plugin.py
Due to a bug in our plugin cleanup logic we'd be waiting for both the plugin's
`stdout` and `stdin` to get closed before cleaning it up. However, since we
only poll `stdout` for incoming messages from the plugin, and not poll its
`stdin`, we'd defer cleaning up indefinitely, until we either send something
to the plugin or we shut down the node entirely. This means that we'd also not
detect crashes in a reasonable time, and a plugin crashing while handling a
hook event could hang forever.
This PR first demonstrates this issue using a plugin that exits as soon as it
`htlc_accepted` hook is called, and then proceeds to fix the issue. We take
the closing of a plugin's `stdout` as the sole signal that the plugin is
exiting and trigger the cleanup immediately. This then surfaced a number of …
=> Handle plugins being terminated correctly

common/jsonrpc_errors.h, contrib/pyln-client/pyln/client/lightning.py, doc/Makefile, doc/index.rst, doc/lightning-getsharedsecret.7, doc/lightning-getsharedsecret.7.md, doc/lightning-listpeers.7, hsmd/hsmd.c, lightningd/hsm_control.c, tests/test_misc.py
Closes #3486
Alternate solution, where we use the exact same Lightning BOLT standard of hashing the point and returning that from `hsmd`.
I **strongly disagree** with this approach:
* If multiplying a secret scalar by an arbitrary SECP256K1 point and publicly revealing the resulting product risked revealing the secret scalar, then we should remember that the generator point `G` itself is an arbitrary SECP256K1 point (equal to `1 * G` i.e. having a "secret" scalar of 1) and public-private cryptography would not be secure in the first place.
* We can implement `getsharedsecret` in terms of `getecdh` (#3486) but not vice versa.  With `getecdh` exposed we can implement using ECIES *and* the Lightning BOLT (Bitcoin-ish?) ECDH key agreement standards, with only `getsharedsecret` like this we …
=> Implement `getsharedsecret`

lightningd/peer_htlcs.c, plugins/Makefile, wallet/wallet.c
- adds BCLI to check-source targets
- fixes two false positive check-source errors on uninitialized variable usage
`make check-source` fails on `Cppcheck 1.90` with two false positives that ignore the `NORETURN` directive on `fatal()`: 
```C
$> cppcheck wallet/wallet.c lightningd/peer_htlcs.c
Checking lightningd/peer_htlcs.c ...
lightningd/peer_htlcs.c:900:9: error: Uninitialized variable: result [uninitvar]
return result;
^
Checking wallet/wallet.c ...
wallet/wallet.c:3744:4: error: Uninitialized variable: ann [uninitvar]
ann->type = db_column_int(stmt, 8);
^
```
=> fix: check source

common/onion.c, common/onion.h, lightningd/peer_htlcs.c, tests/test_pay.py, wallet/test/run-wallet.c
Fixes a minor memory leak, return the necessary information when checking the TLV payload for validity and do not return using `local_fail_in_htlc_badonion` when the real issue is `INVALID_ONION_PAYLOAD`.
Changelog-None
=> Return the correct error when the TLV payload was not valid

common/onionreply.c, devtools/print_wire.c, lightningd/gossip_msg.c, wire/fromwire.c, wire/wire.h
Does the allocation and copying; this is useful because we can avoid being fooled into doing giant allocations.
This will be useful for #3557
Changelog-None
=> wire: add fromwire_tal_bytes() helper.

lightningd/closing_control.c, tests/test_closing.py
Before this patch we would only update `channel->last_tx` with the newly
proposed closure tx from the peer if the fee of the new one was lower.
In negotiations where we are at the higher end and the peer starts
lower, all peer's subsequent proposals will be higher than his initial
proposal and in this case we would never update `channel->last_tx` and
would wrongly broadcast his initial proposal at the end of the
negotiation.
Fixes https://github.com/ElementsProject/lightning/issues/3549
Changelog-Fixed: Always broadcast the latest close tx at the end of the close fee negotiation, instead of sometimes broadcasting the peer's initial proposal.
=> lightningd: always broadcast the latest close tx

contrib/pyln-client/pyln/client/plugin.py, contrib/pyln-testing/pyln/testing/utils.py, lightningd/plugin.c, lightningd/plugin.h, tests/plugins/options.py, tests/test_plugin.py
We're only passing string values of plugin options to plugins, despite soliticting a type from the plugin during the manifest pass. 
In this PR, I will now pass the values down to plugins as the type they've specified.
Additionally, makes the input option parsing stricter and adds a new testing feature where we can capture stderr logs to verify error messages in. If you want to.
=> Pass typed plugin option data to plugin in init

README.md
If the user has a funded bitcoin-cli, they will send from that wallet, if not they will send from a different wallet. 
It seems easier to follow funding instructions without bitcoin-cli reference
=> bitcoin-cli reference confusing

.travis.yml
Caching the `./external` directory means that any changes to
`external/Makefile` or any updates of the submodules in `./external/*`
would not be picked up and travis would run with old instances of those,
possibly "activating" such changes after weeks or months when the cache
is pruned eventually.
Changelog-None
=> travis: do not cache ./external

.editorconfig, doc/STYLE.md
This was extracted from #3572 as it is not part of anything special and considered general cleanup.
Changelog-None
=> doc: point out 8char visual tabs in STYLE.md

channeld/full_channel.c, lightningd/peer_control.c, tests/test_connection.py, tests/test_pay.py
This PR makes our channel lockup drain mitigation  86c28b22   compatible with the upcoming changes of the https://github.com/lightningnetwork/lightning-rfc/pull/740 wich will set this value to a factor of `2`.
=> lightning-rf #740 set feespike factor to 2

contrib/pyln-client/pyln/client/plugin.py, doc/PLUGINS.md, lightningd/options.c, lightningd/plugin.c, lightningd/plugin.h, tests/plugins/options.py, tests/test_plugin.py
Fix a syntactic mistake i made in #3582 
Also fix the option interop test so that it actually verifies the log messages.
=> quick fix: a blank plugin option should be true, not false

gossipd/routing.c
```
clang10 -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\"" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -std=gnu11 -g -fstack-protector  -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/libbacktrace-build -I . -I/usr/local/include   -DCCAN_TAKE_DEBUG=1 -DCCAN_TAL_DEBUG=1 -DCCAN_JSON_OUT_DEBUG=1 -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS   -DBUILD_ELEMENTS=1 -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\""  -c -o gossipd/routing.o gossipd/routing.c
gossipd/routing.c:651:10: error: implicit conversion from 'unsigned long' to 'double' changes value
from 18446744073709551615 to 18446744073709551616 …
```
=> gossipd: fix compilation warnings with clang 10

lightningd/channel_control.c, lightningd/closing_control.c, lightningd/opening_control.c
This is why I run a node.  Of course, I should have checked it two weeks ago!
=> Opening fail fixes

contrib/pyln-testing/pyln/testing/utils.py, doc/lightning-listpeers.7, doc/lightning-listpeers.7.md, lightningd/peer_control.c, tests/test_pay.py
This adds the `receivable_msat` amount to the `lightning-cli listpeers` output. The logic is similar to `spendable_msat` and applies for the maximum possible amount in one HTLC in that situation.
Adds code, test and manpage - Closes #3555
=> feat: receivable_msat to listpeers

lightningd/gossip_control.c, lightningd/opening_control.c, lightningd/pay.c, lightningd/peer_control.c, plugins/fundchannel.c, tests/test_closing.py, tests/test_connection.py
Not everything was in the Deprecated section of the changelog, so did a grep sweep.
=> v082 deprecations

common/amount.c, common/test/run-amount.c
Calling `bitcoind_getutxo()` on testnet transaction https://blockstream.info/testnet/tx/eca4cefef2a98de5df67a6630c63af5a72ab57583e0f3bf066d976f28213f447?expand crashed my node.
EDIT: found another one https://blockstream.info/testnet/tx/21f95a5dd990e9caba09cbafe73514d9322bd8d28d70204dd2b5cce5c9c3f2a8 ^^
Fixes  #3610
=> bcli: don't get upset at 0-value outputs

common/wallet_tx.c, tests/test_wallet.py
We were not taking into account the `minconf` param if the utxos were explicitly passed.
=> wallet: allow to withdraw with unconfirmed utxos

channeld/channel_wire.csv, channeld/channeld.c, devtools/Makefile, devtools/blindedpath.c, gossipd/gossipd.c, lightningd/Makefile, lightningd/channel_control.c, lightningd/onion_message.c, lightningd/onion_message.h, lightningd/pay.c, tests/plugins/onionmessage-reply.py, tests/test_misc.py, tools/check-spelling.sh, tools/generate-wire.py, wire/extracted_onion_experimental_1b1c9a71038bd72453cabefd3ace17ce8b8dd96e, wire/extracted_peer_experimental_1b1c9a71038bd72453cabefd3ace17ce8b8dd96e, wire/peer_wire.c, wire/wire.h
Based on #3599 this implements simple messaging across the lightning network.  There are no contents defined yet, except for those required for routing and replies, but the intent is to use this mechanism for offers.
The specification for messaging is in https://github.com/lightningnetwork/lightning-rfc/pull/759 but the blinded path implementation is stolen straight from https://github.com/lightningnetwork/lightning-rfc/blob/route-blinding/proposals/route-blinding.md.
We use route blinding for two things: one, you can place them inside an onion to send to an otherwise unknown destination, and also you can include a path for the recipient to use to reply.  Both are implemented here.
TODO:
1. We need to add a feature bit, so you know how to route these.
2. We still need to implement decoy …
=> Onion messages (EXPERIMENTAL)

contrib/pyln-testing/pyln/testing/utils.py, plugins/bcli.c, tests/test_closing.py, tests/test_connection.py, tests/test_misc.py, tests/test_pay.py
This builds upon #3570 to, now that we have a specific feerate for them, bump the feerate estimation target for HTLC resolution and penalty transactions.
=> Bump htlc resolution transactions feerate

README.md, doc/FAQ.md, doc/index.rst
This adds an FAQ, I mainly used the issues (thanks for the `question` label !) but also IRC and face-to-face questions.
Do you have an idea of another topic that could/should be covered here ?
closes https://github.com/ElementsProject/lightning/issues/3382
=> doc: Start an FAQ

plugins/pay.c
The shadow route algorithm is extending the route randomly using channels
adjacent to the current destination, in the hope to create a plausible route
extension. However, instead of only retrieving the channels adjacent to the
destination it was retrieving all channels in the entire topology, and
selecting a random channel from there. This resulted in a very large request
for all channels being processed, and then mostly not being used, but also in
shadow extensions to the path which were not plausible (they didn't extend the
real path, just random edges). This is fixed by restricting the call to
`listchannels` to the channels with the current destination as source.
On my laptop retrieving all channels in the current mainnet takes
approximately 1.2 seconds, and given the geometric series …
=> pay: Speed up `pay` and fix the shadow route construction

contrib/pyln-testing/pyln/testing/utils.py, tests/test_misc.py, tests/test_plugin.py, tests/utils.py
This adds a new environment var, `DEPRECATED_APIS`, to allow to quickly run the functional tests against the `lightningd` API users will likely use.
I wanted to also add a Travis job, but am not sure if it's possible to run another one at all. At least we can still set this locally.
=> pyln-testing: Also test against deprecated apis

plugins/fundchannel.c
Noticed while testing #3611 https://github.com/ElementsProject/lightning/pull/3603/commits/49e21538cc99e8f7340d174f02b853cc582dfd2a kept `satoshi` but did not make `fundchannel_start` accept it again.
Note that we run the functional tests with deprecated-apis=false so we did not catch this, but users run with deprecated-apis=true..
=> Fix fundchannel in deprecated-apis=false mode ('satoshi' param in fundchannel_start)

lightningd/peer_htlcs.c
This happened on my testnet node because I've been failing to reconnect to
a node which created a channel and never exchanged announcement sigs.
Changelog-None (change was introduced since last release)
=> lightningd: don't log BROKEN when we don't have a channel update.

doc/FAQ.md
Reading the final FAQ on readthedocs, I noticed I messed up the last rebase in #3551...
Changelog-None
=> doc: fix FAQ formatting

tools/gen/print_impl_template
We call tal_count(msg) after we've moved msg, and that causes an abort.
=> devtools/decodemsg: don't crash if we have multiple tlv options.

plugins/libplugin.c
They now use -fno-common by default, so duplicated variables cause
a link error:
/usr/bin/ld: common/utils.o:(.bss+0x10): multiple definition of `chainparams'; plugins/libplugin.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:408: plugins/autoclean] Error 1
This was introduced in 9ebfdf0b8c8faa0267cbc4c55474b968c2467c32.
Fixes: #3597
Changelog-Fixed: Multiple definition of chainparams on Fedora (or other really recent gcc)
=> libplugin: fix compilation issue on recent gccs.

plugins/pay.c
Fix a couple little crashes found by @fiatjaf
=> Fixup pay crashes

common/json_stream.c, common/json_stream.h, plugins/fundchannel.c, plugins/pay.c
=> common/json_stream.c: Implement a `json_add_jsonstr` to add already-JSON strings to `json_stream` objects

doc/PLUGINS.md
This finally closes #3354 by making the current API final.
There are still things that can get added to the process (namely, notifications for a more optimized polling) but I don't think we'd need to break the interface again (soon).
I have resigned from using WU for transaction sizes as most of the Bitcoin data source seem to actually prefer round ups, and that would have resulted in boutique transformation in plugins to pass from btc/kWU to btc/kVB..
=> doc: document the plugin interface to gather Bitcoin data

common/bolt11.c, contrib/pyln-testing/pyln/testing/utils.py, doc/PLUGINS.md, doc/lightningd-config.5, doc/lightningd-config.5.md, plugins/fundchannel.c, tests/test_pay.py
- Fixes a wrongly interpreted multiplier-less amount
- Allow directory reuse in `node_factory` (needed by some plugins that prepare the node directory before the node first starts, e.g., the backup plugin dropping a `backup.lock` file so the backend is ensured to stay the same).
- Remove the `satoshi` parameter from the `fundchannel_start` docs
- Add a demo of how the wallet DSN looks like for postgresql
=> Weekly cleanups

contrib/plugins/helloworld.py, contrib/pyln-client/pyln/client/plugin.py, tests/test_plugin.py
fixes #3638
Added @sr-gi as a co author as he did all the search and found the cause.
=> pyln-client: send proper JSONRPC2 errors on failed call

contrib/pyln-testing/pyln/testing/utils.py
The last versions (I think since 0.19.0.1 but not sure) of `bitcoind` disabled the fallbackfee by default, it screwed up my scripts but I just noticed `pyln` too now I installed it globally..
=> pyln-testing: specify fallbackfee for newer versions of bitcoind

connectd/connectd.c
I've been running a seednode at `lseed.darosior.ninja`, I think it would be good to add it for the next release.
It currently runs on https://github.com/cdecker/lseed/pull/2, but I plan to also add support for testnet.
Changelog-None
=> connectd: add a new seednode, mine

common/jsonrpc_errors.h, lightningd/plugin.c, lightningd/plugin.h, tests/plugins/hook-crash.py, tests/test_plugin.py
We now track all pending RPC passthrough calls, and terminate them with an
error if the plugin dies.
Changelog-Fixed: JSON-RPC: Pending RPC method calls are now terminated if the handling plugin exits prematurely.
Closes #3496
=> plugin: Ensure RPC passthrough calls are terminated when plugin dies

channeld/channeld.c, tests/test_connection.py, tests/test_pay.py
Sending update_fee immediately after channel establishment seems to
upset LND, so work around it by deferring it.  The reason we increase
the fee after establishment is because now we might need to close the
channel in a hurry due to htlcs, but until there are htlcs that's
unnecessary.
Workaround for #3596
=> channeld: defer first update_fee until we have an HTLC to send.

doc/lightning-invoice.7, doc/lightning-invoice.7.md, lightningd/invoice.c, tests/test_invoices.py, tests/test_pay.py
Reproduces the crash in #3607 which @niftynei fixed in #3630
=> Reproduce pay route crash

lightningd/htlc_set.c, lightningd/invoice.c, lightningd/peer_htlcs.c, lightningd/peer_htlcs.h, lightningd/test/run-invoice-select-inchan.c
We were reaching through it to get `ld`, but channeld is already dead.
Caught this on test_onchaind_replay (without valgrind) on my test machine:
INFO 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-chan#1: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
**BROKEN** lightningd: FATAL SIGNAL 11 (version f6e1735)
**BROKEN** lightningd: backtrace: common/daemon.c:44 (send_backtrace) 0x5634dc83dc55
**BROKEN** lightningd: backtrace: common/daemon.c:52 (crashdump) 0x5634dc83dca9
**BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fd4b7c0b46f
**BROKEN** lightningd: backtrace: lightningd/peer_htlcs.c:285 (failmsg_incorrect_or_unknown) 0x5634dc82625a
**BROKEN** lightningd: backtrace: lightningd/htlc_set.c:109 (htlc_set_add) …
=> lightningd: fix crash when failing htlc once channeld dies.

tests/test_pay.py
We weren't actually waiting until l3 got the channel_update from l2,
so it might not be able to create the routehint.
Changelog-None
=> pytest: fix flaky test_excluded_adjacent_routehint

.gitignore, common/features.c, common/features.h, contrib/pyln-proto/pyln/proto/onion.py, contrib/pyln-proto/tests/test_onion.py, doc/PLUGINS.md, lightningd/invoice.c, lightningd/lightningd.c, lightningd/peer_htlcs.c, lightningd/plugin.c, lightningd/plugin.h, lightningd/test/run-find_my_abspath.c, plugins/Makefile, plugins/autoclean.c, plugins/bcli.c, plugins/fundchannel.c, plugins/keysend.c, plugins/libplugin.c, plugins/libplugin.h, plugins/pay.c, tests/plugins/keysend.py, tests/plugins/replace_payload.py, tests/plugins/test_libplugin.c, tests/test_pay.py, tests/test_plugin.py, wire/tlvstream.c, wire/tlvstream.h
The `keysend` plugin implements the ability to receive spontaneous payments by
including the `payment_preimage` in the onion payload, thus giving the
recipient the ability to claim the payment without having to exchange invoices
first. This sometimes erroneously called a sphinx-send, and can lead to
confusion with the onion routing protocol based on the sphinx paper.
The plugin has the ability to extract the preimage from the payload and will
tell `lightningd` to resolve the HTLC with the provided preimage. As proposed
by @rustyrussell, in order to keep track of funds, `lightningd` will create an
ad-hoc invoice that is immediately fulfilled via the resolved HTLC. This
ensures that we have an entry in the incoming payments, even though we didn't
really have a matching invoice. The ad-hoc …
=> Plugin implementation of `keysend` spontaneous payments

CHANGELOG.md
The reproducible build won't work with `-`'s in the version label.
=> changelog: use correct format for label

lightningd/jsonrpc.c
Commit 9aedb0c61f changed this from allocating off `c` to allocating
off NULL, knowing that it's tal_steal() in the callback.  But before
that, it can be detected as a mem leak:
```
@pytest.fixture
def teardown_checks(request):
"""A simple fixture to collect errors during teardown.
We need to collect the errors and raise them as the very last step in the
fixture tree, otherwise some fixtures may not be cleaned up
correctly. Require this fixture in all other fixtures that need to either
cleanup before reporting an error or want to add an error that is to be
reported.
"""
errors = TeardownErrors()
yield errors
if errors.has_errors():
request.node.has_errors = True
>           raise ValueError(str(errors))
E           ValueError:
E           Node errors:
E           Global errors:
E …
```
=> lightningd: fix false positive on leak detection.

lightningd/chaintopology.c
We want to compare to `i`, the enum counter, not feerates[i], the
feerate value.
Without this fix, `feerates` appears as:
```
{
"perkw": {
"opening": 253,
"mutual_close": 253,
"unilateral_close": 253,
"delayed_to_us": 253,
"htlc_resolution": 253,
"penalty": 253,
"min_acceptable": 253,
"max_acceptable": 2500,
"min_acceptable": 253,
"max_acceptable": 4294967295,
"urgent": 253,
"normal": 253,
"slow": 506
},
"onchain_fee_estimates": {
"opening_channel_satoshis": 177,
"mutual_close_satoshis": 170,
"unilateral_close_satoshis": 151,
"htlc_timeout_satoshis": 167,
"htlc_success_satoshis": 177
}
}
```
bug introduced in "chaintopology: better feerate targets differentiation"
=> feerates: de-dupe min_ max_ printing twice when `feerates` called

lightningd/bitcoind.c, plugins/bcli.c
I think this fixes \ #3571, but I'd like to double check with @whitslack before auto closing the issue.
This comports two drive-by fixes in addition which I remarked while debugging https://github.com/ElementsProject/lightning/issues/3571.
=> Bitcoin: fail immediately if we lose connection to our backend

plugins/bcli.c
`sizeof` doesn't work as expected on pointers to arrays. found while working on the dual-funding branch. currently unused.
=> bugfix: don't truncate the `script` fetched from getutxout

lightningd/bitcoind.c
The define is a leftover from the init fixed timeout hack that was
removed recently (commit 678591d851).
Changelog-None
=> lightningd/bitcoind: remove unused BITCOIN_INIT_TIMEOUT

connectd/connectd.c
Usage of node_id was introduced with commit a2fa699e0e.
Changelog-None
=> connectd: fix '~' comment (s/pubkey/node_id/)

contrib/plugins/helloworld.py, doc/PLUGINS.md, lightningd/invoice.c, lightningd/notification.c, lightningd/notification.h, lightningd/test/run-invoice-select-inchan.c, tests/test_plugin.py
Hello everyone
This PR adds a new invoice_creation event which is triggered when a new invoice is created.
(This is my first PR to C-Lightning 🤓)
Changelog-Added: plugin: new invoice_creation event
=> plugin:added invoice creation event

contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/setup.py, contrib/pyln-testing/pyln/testing/utils.py, tests/plugins/bitcoin/part1.py
Sets the `$HOME` environment variable so that things that rely on user
configurations in the home directory, e.g., `bitcoin-cli`, will not find the
user's real configuration.
Fixes #3669
Fixes #3668
=> pyln: Set $HOME when running tests to avoid accessing real configs

plugins/pay.c, tests/test_pay.py
~~We claim to do so in the manpage.~~ [I was wrong](https://github.com/ElementsProject/lightning/pull/3693#issuecomment-623145123)
fixes https://github.com/ElementsProject/lightning/issues/3684
=> pay: respect maxfeepercent when choosing a shadow route

wallet/db_sqlite3.c
This probably happened through copy-and-paste from
db_sqlite3_begin_tx().
Changelog-None
=> db: fix error message in db_sqlite3_commit_tx()

channeld/channeld.c, common/onion.c, connectd/peer_exchange_initmsg.c, devtools/blindedpath.c, devtools/gossipwith.c, devtools/mkquery.c, gossipd/queries.c, gossipd/test/run-extended-info.c, lightningd/onion_message.c, tools/gen/header_template, tools/gen/impl_template, tools/generate-wire.py, wire/test/run-peer-wire.c, wire/test/run-tlvstream.c
When we have only a single member in a TLV (e.g. an optional u64),
wrapping it in a struct is awkward.  This changes it to directly
access those fields.
This is not only more elegant (60 fewer lines), it would also be
more cache friendly.  That's right: cache hot singles!
[I blame @niftynei for the nomenclature which lead to these awful puns, FWIW!]
=> tools/generate-wire: no more lonely messages!

contrib/pyln-proto/pyln/proto/invoice.py, contrib/pyln-proto/requirements.txt, contrib/pyln-proto/tests/test_invoice.py
secp256k1 Python library is not maintained anymore and coincurve was
already used in the `wire` module.
Changelog-None
Signed-off-by: Michal Rostecki <mrostecki@mailfence.com>
=> pyln-proto: Use only coincurve for libsecp256k1 bindings

devtools/credit
Output on master branch for a non-existing tag:
```
$ ./devtools/credit v1337
fatal: ambiguous argument 'v1337..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'v1337': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'v1337': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
./devtools/credit: 47: ./devtools/credit: arithmetic expression: expecting primary: " ( 1589109411 -  ) / (3600*24) "
```
Output on PR branch:
```
$ …
```
=> devtools/credit: check if tag exists first

tests/test_pay.py
We've been seeing some Travis timeouts under VALGRIND, with the
10 second timeout here: use TIMEOUT as per standard.
Changelog-None
=> pytest: extend timeout for test_payment_duplicate_uncommitted

Makefile
Hide our CFLAGS and LDFLAGS line noise each time an object file is compiled
or linked.
Also add a `make show-flags` command for displaying CC, LD, CFLAGS and
LDFLAG information. This is shown at the start of each build.
$ make
CC: gcc -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall [..]
LD: gcc   -Og    -Lexternal -lwallycore -lsecp256k1 -ljsmn  [..]
...
cc ccan/ccan/crypto/shachain/shachain.c -DSHACHAIN_BITS=48
cc lightningd/test/run-jsonrpc.c
cc lightningd/test/run-invoice-select-inchan.c
cc lightningd/test/run-log-pruning.c
cc lightningd/test/run-find_my_abspath.c
cc cli/test/run-large-input.c
cc cli/test/run-remove-hint.c
ld lightningd/lightning_hsmd
ld lightningd/lightning_gossipd
ld lightningd/lightning_openingd
ld lightningd/lightning_channeld
ld lightningd/lightning_closingd …
=> build: cleanup compiler output

contrib/pyln-proto/pyln/proto/bech32.py
```python
contrib/pyln-proto/pyln/proto/bech32.py:120
/home/rusty/devel/cvs/lightning/contrib/pyln-proto/pyln/proto/bech32.py:120: SyntaxWarning: "is not" with a literal. Did you mean "!="?
assert decode(hrp, ret) is not (None, None)
```
I think this warning is correct (though I don't see the warning once I installed coincurve:
are we suppressing warnings?)
Changelog-None
=> pyln: fix incorrect python syntax?

hsmd/hsmd.c
One must `return` the bad_req, otherwise you continue onward, usually
with bad or unexpected results.
introduced in 6b6b7eac61491c8a7ed4c6e939570221f1286f7e
Changelog-None
=> hsmd: fix missing return bug

contrib/startup_regtest.sh
Moves the 'daemon'ization from c-lightning to the process level, so that
stderr print messages appear in the terminal. Easier debugging!
=> contrib: allow stderr printing for startup_regtest

doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/lightningd.h, lightningd/options.c, plugins/bcli.c, tests/test_misc.py, wallet/test/test_utils.c
It has been ignored for quite some time apparently (a quick `git log -S` tells me we don't use it since `88bb38f63b46eeac6ea3f3a29b71dd9aca6cacd0`, but not sure though) and the doc was wrong.
=> Config: revive --commit-fee

tests/test_misc.py, wallet/walletrpc.c
This made my copy/paste to Esplora cumbersome :/
Was this intended ? If so maybe the changelog line is wrong and the old behaviour should be guarded behind `deprecated_apis` ...
=> listtransactions: represent txids as little endian

common/features.c, gossipd/routing.c, gossipd/test/Makefile, gossipd/test/run-bench-find_route.c, gossipd/test/run-check_channel_announcement.c, gossipd/test/run-crc32_of_update.c, gossipd/test/run-extended-info.c, gossipd/test/run-find_route-specific.c, gossipd/test/run-find_route.c, gossipd/test/run-next_block_range.c, gossipd/test/run-overlong.c, gossipd/test/run-txout_failure.c, tests/plugins/feature-test.py, tests/test_connection.py, tests/test_misc.py, tests/test_plugin.py, tests/utils.py
Turns out that we didn't do this the way the spec said, nor the way Eclair does.  This change is a compatibility break with existing 0.8.2 nodes, so I suggest we backport the minimal change (part of the final commit) and release 0.8.2.1.
There is no good alternative: once we find they've signed a different thing, we've already sent our signatures to them.
=> Fix: remove option_large_channels from channel_announcements.

wallet/invoices.c, wallet/wallet.c
I don't know about SQLite, but Postgres doesn't guarantee that rows are ordered by the id or insertion order, so I'm constantly getting bizarre sortings (like `125346`) that cause confusion when listing invoices and payments. This is an easy fix.
Changelog-None
=> sort listinvoices and listsendpays by order of creation.

tools/mockup.sh, tools/test/Makefile, tools/update-mocks.sh
test for #3226
pinging @willcl-ark for review
=> fixup clang error for update-mocks?

doc/INSTALL.md
the PPA is no longer maintained, the new hotness is the snapd install.
except that snapd does some weirdness with the binary names, calling it
bitcoin-core.daemon and bitcoin-core.cli. To get around this, you can
create a symbolic link to the snap binaries, which is what we outline
here.
=> doc: remove bitcoin PPA from install instructions

hsmd/hsm_wire.csv, hsmd/hsmd.c
We always treat it as a withdrawl.
Reported-by: @niftynei
=> hsmd: remove unused sign_funding_tx.

doc/lightning-listfunds.7, doc/lightning-listfunds.7.md, wallet/walletrpc.c
Currently 'listfunds' lies, a teensy eeinsy bit, in that it doesn't list
all of the funds in a wallet (it omits reserved wallet UTXOs). This
change makes the reserved outputs visible by listing them in the
'outputs' section along with a new field, 'reserved', which denotes the
UTXO's state
Changelog-Changed: JSON-RPC: `listfunds` 'outputs' now includes reserved outputs, designated as 'reserved' = true
=> listfunds: also list reserved outputs

lightningd/json.c, lightningd/jsonrpc.c, tests/test_wallet.py
90bce56: I regularly hit this corner case on a bloated-memory node
9230907 and 2fbd490 fix #3771.
Fixes #3771
=> An RPC connection fix and some vbyte fun

common/json.c, common/test/run-json.c
xref: https://lists.ozlabs.org/pipermail/c-lightning/2020-June/000188.html
=> common/json.c: Check that JSMN result is well-formed.

lightningd/opening_control.c, tests/test_connection.py
Changelog-Changed: `fundchannel_cancel` will now succeed even when executed while a `fundchannel_complete` is ongoing; in that case, it will be considered as cancelling the funding *after* the `fundchannel_complete` succeeds.
Let me introduce the concept of "Sequential Consistency":
All operations on parallel processes form a single total order agreed upon by all processes.
So for example, suppose we have parallel invocations of `fundchannel_complete` and `fundchannel_cancel`:
+--[fundchannel_complete]-->
|
--[fundchannel_start]-+
|
+--[fundchannel_cancel]---->
What "Sequential Consistency" means is that the above parallel operations can be serialized as a single total order as:
--[fundchannel_start]--[fundchannel_complete]--[fundchannel_cancel]-->
Or: …
=> lightningd/opening_control.c: Remove 'Try fundchannel_cancel again' error.

common/utils.c, tests/plugins/fail_htlcs_invalid.py, tests/test_pay.py
Fixes: #3757
Reported-by: @sumBTC
=> common/utils.c: Correctly handle NULL `take`n pointer in `tal_dup_talarr`.

bitcoin/psbt.c, bitcoin/psbt.h, bitcoin/tx.c, bitcoin/tx.h, channeld/channeld.c, common/json_helpers.c, common/json_helpers.h, common/type_to_string.h, common/utxo.c, common/withdraw_tx.c, common/withdraw_tx.h, hsmd/hsm_wire.csv, hsmd/hsmd.c, openingd/openingd.c, tests/plugins/onionmessage-reply.py, tools/generate-wire.py, wallet/db.c, wallet/wallet.h, wallet/walletrpc.c
Updates the HSM withdrawal to take a PSBT and utxo set. We sign the inputs that we've got utxos for, and return a psbt with the attached signatures.
This 'fully' integrates the PSBTs with our HSM for the first time, and gets us ready for a `signpsbt` command (coming soon).
Note that this is built atop #3740 
(new content begins at 
965014d), and requires https://github.com/ElementsProject/libwally-core/pull/203 to be merged in order to pass tests (as there's a number of P2SH-P2WPKH bugs in the existing libwally-psbt implementation)
Changelog-None
=> PSBTs, Meet the HSM

plugins/autoclean.c
The autocleaning will only happen if the autocleaninvoice-cycle startup
option is passed, which cannot happen if the plugin is started
post-startup.
Thus, it's less misleading for users to restrict its usage to startup.
Changelog-Added: plugins: The `autoclean` plugin is now static (you cannot manage it with the `plugin` RPC command anymore).
Signed-off-by: Antoine Poinsot <darosior@protonmail.com>
Related to  #3731.
=> plugins: make the autoclean plugin static

.travis.yml, .travis/build.sh, external/.gitignore, external/Makefile
=> travis: Actually build for arm

plugins/keysend.c
```
plugins/keysend.c:136:47: error: format specifies type 'unsigned long' but the argument has type 'time_t' (aka 'int') [-Werror,-Wformat]
ki->label = tal_fmt(ki, "keysend-%lu.%09lu", now.ts.tv_sec, now.ts.tv_nsec);
~~~         ^~~~~~~~~~~~~
%d
```
Changelog-None
=> build: fix compilation on i386

external/Makefile
The external Makefile hardcodes gcc to get the machine spec. This should use the configured C compiler instead.
This bug was introduced in 601464416b7d437409ceb8f7373115d2f14b21d1.
=> build: Make it possible to build without gcc

external/Makefile
Quote marks are not special to make: as it can't find
external/"x86_64-linux-gnu"/libwally-core-build/src/libwallycore.la
it always insists on rebuilding it (which rebuilds the world).
If we have spaces in TARGET_DIR, we're in trouble already.
=> external/Makefile: fix spurious rebuilds.

contrib/pyln-proto/Makefile, contrib/pyln-spec/Makefile
rusty$ make prod-release
make: *** No rule to make target 'test', needed by 'prod-release'.  Stop.
Changelog-None
=> pyln-proto, pyln-spec: fix 'make prod-release' target.

wallet/walletrpc.c
Seems an outright mistake: the containing loop is on `num_inputs`.
=> wallet/walletrpc.c: Show input annotations for inputs.

wallet/wallet.c
"backtrace": [
"ccan/ccan/tal/tal.c:442 (tal_alloc_)",
"wallet/wallet.c:154 (wallet_stmt2output)",
"wallet/wallet.c:275 (wallet_get_utxos)",
"wallet/wallet.c:3792 (wallet_clean_utxos)",
"lightningd/lightningd.c:914 (main)"
],
"label": "wallet/wallet.c:154:struct utxo",
"parents": [
"wallet/wallet.c:273:struct utxo*[]"
],
"value": "0x24c1be8"
Changelog-None
=> wallet: fix memleak if we get shut down before finishing utxo cleanup.

wallet/wallet.c
We were assuming `wallet_channel_insert` that there cannot be a matching peer
if our in-memory representation isn't bound to it (`dbid == 0`). If we then
attempt to create the peer, and we already had one it'd cause a unique
constraint violation. As far as I can tell this could end up happening if we
have an uncommitted channel, and then exited without cleanup (`tal_destructor`
on the uncommitted channel not running). This could then leave the peer in the
DB. This is because the constraint that every peer has at least one channel is
not enforce at DB level, but rather in destructors that may or may not run.
I tried to reproduce the issue in pytest, but was unsuccessful, suggesting I don't
fully capture the causes yet.
Notice that an alternative to this would be adding yet another …
=> db: Retrieve peer ID if it exists or create the peer if not

.gitignore, Makefile, doc/Makefile, doc/index.rst, doc/lightning-hsmtool.8, doc/lightning-hsmtool.8.md, doc/lightningd-config.5, doc/lightningd-config.5.md, doc/lightningd.8, doc/lightningd.8.md, tools/Makefile, tools/hsmtool.c
Changelog-Added: We now install `lightning-hsmtool` for your `hsm_secret` needs.
See: https://github.com/ElementsProject/lightning/issues/3717#issuecomment-644844594
It seems reasonable to add this to the standard install, and to document it properly as well, hopefully we can fill in the documentation better later on.
=> Makefile: Install `tools/hsmtool` as `lightning-hsmtool`.

connectd/connectd.c, connectd/connectd.h, connectd/tor.c, doc/TOR.md
- Reflect in TOR.md that we need a Tor version >= 0.3.2.2-alpha if we want to reach Tor V3 onions 
- change the error response  
fix #3642 reported by @thestick613
=> Reflect that Tor version must be  >= 0.3.2.2-alpha to reach V3 onions.

doc/lightning-sendonion.7, doc/lightning-sendonion.7.md, plugins/Makefile, plugins/libplugin-pay.c, plugins/libplugin-pay.h, plugins/pay.c, tests/test_pay.py, tools/gen/header_template, wire/tlvstream.c, wire/tlvstream.h
_This is only a partial implementation of the new payment flow, but given the
looming release deadline and the sheer size of the change, I thought it's best
to get some code reviews in now_
The current payment flow is a multi-step process in the `pay` plugin (and some
others) that grew organically as logic and more features were added over the
time. This PR is my attempt to reimagine and consolidate the payment flow, to
consolidate some commonalities, better compartmentalize the existing addons,
and facilitate future modifications of the flow.
In order to get to this lofty goal I separated the logic into two separate
parts: the `payment` which consists of the core functionality required to
perform a payment, and `payment_modifier`s which have associated data and are
called at each step of …
=> paymod: Payments reimagined (part 01)

tests/test_wallet.py, wallet/walletrpc.c
Changelog-Changed: `txprepare` now prepares transactions whose `nLockTime` is set to the tip blockheight, instead of using 0. `fundchannel` will use `nLockTime` set to the tip blockheight as well.
=> wallet/walletrpc.c: `txprepare`d transactions now use current tip blockheight by default.

common/jsonrpc_errors.h, doc/lightning-fundchannel_cancel.7, doc/lightning-fundchannel_cancel.7.md, lightningd/channel_control.c, lightningd/channel_control.h, lightningd/opening_control.c, tests/test_connection.py
Fixes: #3785
Changelog-Changed: `fundchannel_cancel` no longer requires its undocumented `channel_id` argument after `fundchannel_complete`.
Note: this implies changes in #3763.
=> lightningd/opening_control.c: `fundchannel_cancel` no longer requires a `channel_id` argument.

openingd/openingd.c
Fixes: #3815
Changelog-Fixed: Fixed a deviation from BOLT#2: if both nodes advertised `option_upfront_shutdown_script` feature: MUST include ... a zero-length `shutdown_scriptpubkey`.
@joemphilips can you check if this fixes #3815?
=> openingd/openingd.c: Fix a mild deviation from BOLT#2.

Dockerfile, tools/docker-entrypoint.sh
Before this, docker image will never detects that
`lightning-rpc` was created if it is running in regtest
or testnet, because the file will be created under
subfolder for each network name.
~By recursively checking the file creation, now docker
can be run in any network configuration.~
I had to deal the path for argument to the `socat` , so I added a new `ENV` entry in Dockerfile to detect the correct network.
=> Tweak docker entrypoint to support regtest, testnet

tools/hsmtool.c
Changelog-Fixed: Actually make the password argument optional for `guesstoremote` and `dumpcommitments` sub-commands, as shown in our documentation and help text.
Reported by `Barno` on #c-lightning IRC.
=> tools/hsmtool.c: Make password optional for `guesstoremote` and `dumpcommitments` commands.

Makefile, plugins/Makefile, plugins/libplugin-pay.c, plugins/libplugin.c
Changelog-None
Extracted the first commit from #3763 , because #3763 is stuck until we can get 0-output PSBTs working, for some reason.  Anyway *this* commit should be uncontroversial since it does not involve speculative new frameworks for plugin execution, and also fixes some source files that were not included in our standard source file checks.
=> plugins/Makefile: Change plugins build procedure.

doc/Makefile, doc/lightning-feerates.7, doc/lightning-feerates.7.md, doc/lightning-fundchannel.7.md, doc/lightning-txprepare.7.md, doc/lightning-withdraw.7.md
Makes sense to openly expose this command once we have `fundpsbt`, as `fundpsbt` requires the caller to compute the output feerates by itself.
=> doc/lightning-feerates.7.md: Document `feerates` command.

.travis/build.sh, plugins/libplugin-pay.c, plugins/pay.c, tests/test_misc.py, tests/test_pay.py
This is the last step in activating the new payment flow.
- It removes all the `compat` changes to tests done in the previous parts and now uses the updated RPC everywhere
- Added a `legacy` option to `pay` (and `legacypay` in order not to cause param failures) to fall back on the old implementation should there be an issue.
- Fixed a tiny regression with flapping payment status if we happen to wait for the blockheights to match up.
We informally decided to activate the new payment flow for everybody and provide an escape hatch, for users that require the legacy payment model.
Changelog-None
=> paymod: Activate the new payment flow for good (part 04)

CHANGELOG.md
This PR adds the changelog entries for the v0.9.0rc1 release. Once this is merged we can tag it :-)
Changelog-None
=> release: Add changelog entries for v0.9.0 release

CHANGELOG.md
The CVE was fully disclosed, so we can safely add it to the Security
field for the 0.7.1 changelog.
Also removed the "No security changes were necessary" text.
If we do this for releases, then either we lie about a CVE-level problem,
or we leak that a release fixes a CVE-level problem.
Changelog-None
=> CHANGELOG.md: Update security changes for 0.7.1.

contrib/pyln-client/pyln/client/lightning.py, doc/lightning-fundpsbt.7, doc/lightning-fundpsbt.7.md, tests/test_wallet.py, wallet/reservation.c
fundpsbt forces the caller to manually add their weight * feerate
to the satoshis they ask for.  That means no named feerates.
Instead, create a startweight parameter and do the calc for them
internally, and return the feerate we used (and, while we're at it,
the estimated final weight).
This API change is best done now, as it would otherwise have to
be appended as a parameter.
Changelog-None
=> fundpsbt: make parameters more usable.

ccan/README, ccan/ccan/htable/htable.c, ccan/ccan/htable/htable.h, ccan/ccan/htable/htable_type.h, ccan/ccan/htable/test/run-type.c, ccan/ccan/htable/test/run.c, ccan/ccan/tal/tal.h, ccan/tools/configurator/configurator.c
Otherwise we get a configurator failure:
In file included from /usr/include/string.h:495,
from configuratortest.c:2:
In function ‘strncpy’,
inlined from ‘main’ at configuratortest.c:6:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 8 equals destination size [-Wstringop-truncation]
106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Changelog-None
=> ccan: update so we can compile with -O2 on Ubuntu.

wire/Makefile, wire/extracted_onion_experimental_badonion_blinding
(cherry-picked from anchor-outputs, since it just hit me on my local machine)
Also, remove fuzz caused by varint->bigsize change.
For some reason my build machine sorts patches into another order, and fails
to patch:
patching file wire/gen_onion_wire_csv.104951
Hunk #1 succeeded at 52 with fuzz 1 (offset -19 lines).
patching file wire/gen_onion_wire_csv.104951
Hunk #1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file wire/gen_onion_wire_csv.104951.rej
make: *** [wire/Makefile:60: wire/gen_onion_wire_csv] Error 1
Changelog-None
=> wire: locale-independent patch order for EXPERIMENTAL_FEATURES patches

doc/lightning-sendpay.7, doc/lightning-sendpay.7.md, lightningd/pay.c, tests/test_pay.py
=> Core sendpay fixes

plugins/libplugin-pay.c
Split out from #3866 since it was unrelated and needs to go in independently.
Changelog-None
Closes #3866
=> paymod: fix typo which can cause memory overrun.

plugins/libplugin-pay.c, plugins/libplugin-pay.h, tests/test_pay.py
This PR re-establishes the old behavior of testing each routehint in the order they were specified, but keeps the routehints immutable, so each sub-payment decides whether to skip one or not:
- The root payment performs an initial `getroute` test for 1sat to see if the destination could be reached directly, if that's the case it add a `NULL` routehint to the end of the routehint array. This way using or not using a routehint is handled identically.
- Each payment has an offset internally that indexes into the root routehint array. When starting a new attempt it'll select the next working routehint by skipping the ones that might be known to fail due to a channel hint.
- On retry the child payment increments the parent's offset by 1 and continues from there
- On split the child payment …
=> Iterate through all the routehints in the specified

doc/lightning-sendonion.7, doc/lightning-sendonion.7.md, lightningd/pay.c, plugins/libplugin-pay.c, tests/test_pay.py
This PR proposed a solution to fix the problem mentioned at the following PR https://github.com/ElementsProject/lightning/pull/3876 
I can have some idea bug in my mind, so if this PR is wrong, I'm so sorry.
The json below is an example of use cases when I used the command keysend and pay (json_paymod).
```json
{
"pays": [
{
"bolt11": "lnbcrt100n1p03chsnpp5n72j2e0ykwz7ue37e60qn623z9elq4fguv52ny7jjqmv990zajeqdql2pshjmt9de6zqamfw35zqurp09kk2eqxqyjw5qcqp2sp5h0renl745kd7c86z2g49lkuhua3j66an80szd58qdpeyzhdkrl3srzjqfnup6dhq3xls5v5pw0ksgrx0gcerqpr2pd6y6ckhstql6qfncta6qq24qqqqqgqqqqqqqqpqqqqqzsqqc9qy9qsqfy8e5x6aya75n3ayd5e8rsvkmepgq9gwf8v9ram560y5vlrapk9pwjxcfewfpvvnw97v49xzlce6zqmc5znv0ke6e3un5lm4hk8uewqq5dug0s",
"status": "complete",
"preimage": …
```
=> A proposed solution to fix json null value for bolt11 key when is used the pay plugin

doc/lightning-sendonion.7, doc/lightning-sendonion.7.md, lightningd/pay.c, plugins/libplugin-pay.c, plugins/pay.c, tests/test_pay.py, wallet/wallet.c
Since we use `sendonion` in the new payment flow we end up not knowing the amount received by the destination, only the amount we sent (which includes fees).
This PR adds an optional annotation that tells us what the intended amount to be sent is.
Notice that it is still possible to call `sendonion` without the annotation and readers calling `listpays` or `listsendpays` should fall back to the amount being sent if the amount at the destination is unknown. The amount_sent is always guaranteed to be known and set.
Closes https://github.com/shesek/spark-wallet/issues/146
Changelog-None
=> Annotate payments initiated using sendonion with the amount at the destination

CHANGELOG.md
Only two minor display changes since v0.9.0rc3:
- Addition of `bolt11` argument to `sendonion`
- Addition of `msatoshi` argument to `sendonion`
Changelog-None: Well, really, this is the changelog...
=> release: Add changes since v0.9.0rc3 to changelog

lightningd/chaintopology.c, lightningd/chaintopology.h
Related to #3858
Code related to this field was last updated in 2017.  It is initialized to a pointless 0-length array, in code that was last touched in 2016.  No other code reads from it, writes to it, or even does something like extend the array.
Removing since I want to change the interface between `bcli` and `lightningd`, which implies that the `struct block` would actually be reported in JSON form by `bcli` to `lightningd`, and since `txnums` is unused anyway, we can remove it and simplify what we will eventually need from `bcli`.
=> lightningd/chaintopology.h: Remove unused `txnums` field from `struct block`.

common/jsonrpc_errors.h, doc/lightning-delinvoice.7, doc/lightning-delinvoice.7.md, lightningd/invoice.c
Changelog-Changed: JSON-RPC: `delinvoice` will now report specific error codes 905 for failing to find the invoice, 906 for the invoice status not matching the parameter.
=> lightningd/invoice.c: Improve programmatic error reporting for `delinvoice`.

README.md, contrib/pyln-testing/pyln/testing/utils.py, plugins/bcli.c, tests/test_misc.py
This adds a sanity check function to `bcli` which we could extend with other sanity checks in the future.
This was [brought up](https://github.com/ElementsProject/lightning/issues/3858#issuecomment-665619664) by @ZmnSCPxj.
=> Explictly check at startup that we don't support `bitcoind`'s `blocksonly` option.

plugins/libplugin-pay.c, plugins/libplugin-pay.h
Arguably a low-priority bug since no current node ever generates routehints longer
than one hop.
However, it is possible as an edge case, if the destination is directly accessible
*and* supports multiple channels, that we route through the destination, one of the
*other* channels it has not in the routehint, to the entry point, and then through
the routehint.
This change removes the risk of the above edge case.
Changelog-None: arguably a low-priority bug.
=> plugins/libplugin-pay.c: Properly handle exclusions for routehints with two hops or more.

lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/opening_control.c
We were basing the 2016 block timeout on the blockchain height that we had
processed at the time completed the funding, which could lag considerably
behind the network-wide blockheight. For example this could happen if we
started with `--rescan` from a low height, taking some time to catch up.
This means that we could end up forgetting channels even before reaching the
network blockheight. This patch instead uses the headercount reported by the
backend plugin if we aren't caught up yet. While the chances of this happening
are still there, the window it might happen are much reduced, since headers
can be synced in a couple of minutes.
=> channel: Base the channel forget timeout on the headercount

Makefile, doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/Makefile, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c, lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_control.c, lightningd/test/run-find_my_abspath.c, tests/plugins/suicidal_plugin.py, tests/test_misc.py, tests/test_plugin.py
Closes #3213
Builtin plugins are automatically made important.
=> Important plugin

requirements.txt
Supplements the consolidation in b68066e
Gets rid of complaints when running (on `v0.9.0rc2`)):
```sh
./configure --enable-developer
make
make check
```
=> Add missing test dependencies to requirements.txt

plugins/pay.c, tests/test_pay.py
=> Routehints get ignored if invoice >10,000 sats

contrib/pyln-proto/pyln/proto/message/message.py
We'll override them from field length anyway!
Changelog-None
=> pyln.proto.message: don't let Message() init set implicit lengths.

plugins/Makefile
Changelog-None: cleanup only.
Before this change:
```
$ ls -l plugins/bcli
-rwxrwxr-x 1 zmnscpxj zmnscpxj 1914976 Aug  5 21:54 plugins/bcli
```
After this change:
```
$ ls -l plugins/bcli
-rwxrwxr-x 1 zmnscpxj zmnscpxj 1830552 Aug  5 22:00 plugins/bcli
```
We already duplicate a lot of code between `lightningd` and eeach
builtin plugin because we do not use .so for `common/`, but including
an object file with code that is not referenced in the executable is
fairly low-hanging size optimization fruit.
=> plugins/Makefile: Only link in libplugin-pay for plugins that need it.

Makefile, common/Makefile, common/version.c
This prevents recompiling everything when you are changing just a doc, or
touching only one file among hundreds of sources, just because the
`gen_version.h` is changed, especially since only one source actually
depends on that header.
=> Makefile: Remove gen_version.h from ALL_GEN_HEADERS.

contrib/pyln-testing/pyln/testing/fixtures.py, contrib/pyln-testing/pyln/testing/utils.py, tests/test_closing.py, tests/test_connection.py, tests/test_gossip.py, tests/test_invoices.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py, tests/utils.py
1. A flake fix for  test_restart_many_payments.
2. A flake fix for test_onchain_their_unilateral_out
3. Mass conversion to get_nodes() which batches, vs. individual get_node() calls.
4. Turn off valgrind for SLOW_MACHINE slow tests, rather than skipping them entirely.
Changelog-None
=> More pytest optimizations

plugins/pay.c, tests/test_pay.py
Reported-By: Nadav Ivgi <@shesek>
Changelog-Added: JSON-RPC: The result returned by `listpays` now includes the timestamp of the first part of the payment
=> pay: Add timestamp of first part to `listpays`

doc/lightning-listpays.7, doc/lightning-listpays.7.md, doc/lightning-sendonion.7, doc/lightning-sendonion.7.md, lightningd/pay.c, plugins/libplugin-pay.c, plugins/pay.c, tests/test_pay.py
Hi all.
This PR proposes an update to the response of the `listpay` command, discussed inside [this issue](https://github.com/ElementsProject/lightning/issues/3880). In particular, the `listpays` could return a `bolt11: (null)` propriety if the payment was made with `keysend` or if the payment was didi during the [rc3 bug](https://github.com/ElementsProject/lightning/pull/3878).
In addition, this PR proposes the change inside the parameters accepted by `listpay`. In fact, the command could lose the meaning if I want to use `listpay` to filter the payment that I made with `keysend`. In other words, I can not require with `listpays` a single payment if it is made with `keysend`.
```json
{
"payment_hash": "7cdf931c7a23efb6815ff239517ef6d373bb8d040caefba96314368afd93252d",
"status": …
```
=> Update format response from listpay is the payment was did with keysend

contrib/plugins/fail/failtimeout.py, contrib/pyln-client/pyln/client/plugin.py, doc/PLUGINS.md, doc/STYLE.md, lightningd/jsonrpc.c, lightningd/pay.c, lightningd/plugin.c, lightningd/plugin.h, plugins/libplugin.c, plugins/libplugin.h, tests/plugins/test_libplugin.c, tests/test_plugin.py
I wrote all this then realized that the cmd I wanted to patch wasn't in a plugin at all!
Oh well!
=> Plugins can deprecate too!

plugins/libplugin-pay.c, plugins/pay.c, tests/test_pay.py
This fixes #3915, which could crash if the presplit modifier skipped the root payment, which was also the only payment annotated with the bolt11 string. It is addressed in two ways: we now annotate the first level of children in presplit (all other splits or skips act after the attempt was sent to `lightnignd` and thus there is at least one partial payment with the bolt11 annotation), and secondly we now aggregate via the `payment_hash` which is guaranteed to be non-null for all current payments, whereas the bolt11 string is only non-null if the payment was annotated with it.
Fixes #3915 
Fixes #3931
=> Fix aggregation of partial payments in the pay-plugin

tests/test_plugin.py
On my test machine, we queried bitcoind before the close tx was sent:
```
txo = l1.rpc.call("getutxout", {"txid": txid, "vout": 0})
>       assert txo["amount"] is txo["script"] is None
E       AssertionError: assert '20000000msat' is '00205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cd'
tests/test_plugin.py:1221: AssertionError
```
Changelog-None
=> pytest: fix race in test_bcli.

plugins/libplugin-pay.c, tests/test_pay.py
So I stumbled on a bug where the payee has a longer chain than the payer while developing #3913.
I wrote this little test plus fix, but it looks like we still have issues with being too aggressive in returning a *transient* error permanently!
Here are logs on the payer, after the (partial fix) is done on the payer side:
```
b'2020-08-09T07:12:07.387Z DEBUG plugin-pay: Added a channel hint for 103x1x1/1: enabled true, estimated capacity 4294967295msat'
b"2020-08-09T07:12:07.388Z DEBUG plugin-pay: After filtering routehints we're left with 1 usable hints"
b'2020-08-09T07:12:07.388Z DEBUG plugin-pay: Asking gossipd whether 035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d is reachable without routehints.'
b'2020-08-09T07:12:07.391Z DEBUG plugin-pay: Using routehint …
```
=> Waitblockheight MPP bugs

doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md, doc/lightning-listfunds.7, doc/lightning-listfunds.7.md, lightningd/chaintopology.c, lightningd/onchain_control.c, lightningd/peer_control.c, lightningd/test/run-invoice-select-inchan.c, plugins/fundchannel.c, tests/test_plugin.py, wallet/db.c, wallet/db.h, wallet/wallet.c, wallet/wallet.h, wallet/walletrpc.c
(Based on #3843 see last 3 commits)
This adds some more info to our JSON outputs, and pushes transactions from sendpsbt into the wallet (otherwise they're not noticed, which confuses various tests once we port the other things onto it).
We could argue that *signpsbt* is where we should notify the wallet (and maybe, bump reservation on the inputs?), since they might not use *sendpsbt* through us, though we'll notice the tx when it's onchain.  @niftynei @cdecker  thoughts?
=> Misc externally-visible cleanups (nothing urgent)

doc/Makefile, doc/index.rst, doc/lightning-fundpsbt.7, doc/lightning-fundpsbt.7.md, doc/lightning-utxopsbt.7, doc/lightning-utxopsbt.7.md, wallet/reservation.c
OK, after pondering @ZmnSCPxj 's feedback, I came up with a new helper to make life easier.
~It's on top of #3844 so see last commit...~ Now ready to go!
=> utxopsbt command

contrib/pyln-client/pyln/client/lightning.py, doc/lightning-fundpsbt.7, doc/lightning-fundpsbt.7.md, doc/lightning-utxopsbt.7, doc/lightning-utxopsbt.7.md, tests/test_wallet.py, wallet/reservation.c, wallet/walletrpc.c
Required for dual funding where the opener sets it.
Changelog-Added: JSON-RPC: fundpsbt takes a new `locktime` parameter
=> fundpsbt/utxopsbt: let caller specify locktime, signpsbt: signing restrictions.

bitcoin/psbt.c, bitcoin/psbt.h, bitcoin/tx.c, common/psbt_open.c, common/test/run-psbt_diff.c
I need this for adding an input to a PSBT, but it also moves us closer to weaning off bitcoin_tx...
Changelog-None
=> More psbt cleanups

common/json.c, common/json.h, common/test/run-json.c, common/test/run-json_remove.c, devtools/onion.c, lightningd/jsonrpc.c, lightningd/plugin.c, lightningd/plugin.h, lightningd/test/run-jsonrpc.c, plugins/bcli.c, plugins/libplugin.c, plugins/pay.c, wallet/db.c
@fiatjaf reported in #3941 that `listspays` was slow, and indeed, it was.
I created 50,000 payments, and ran some tests.
* With no optimization:
* `listsendpays` takes 0.983 seconds
* `listpays` takes 52.415 seconds
* With `-O3 -flto`:
* `listsendpays` takes 0.628 seconds
* `listpays` takes 43.104 seconds
After these optimizations (mostly FIXMEs!) the results are:
* With no optimization:
* `listsendpays` takes 0.676 seconds
* `listpays` takes 1.545 seconds.
* With `-O3 -flto`:
* `listsendpays` takes 0.416 seconds
* `listpays` takes 0.971 seconds.
=> JSON optimizations, cleanups and listsendpays optimizations

wallet/db.c
Otherwise valgrind gets upset when we *run* the statements: better
to get a backtrace when we bind, so we can tell which field it is!
Changelog-None
=> wallet: do valgrind checks when binding db statements.

Makefile, bitcoin/psbt.c, bitcoin/script.c, channeld/channeld.c, channeld/commit_tx.c, channeld/full_channel.c, channeld/test/run-commit_tx.c, common/bolt11.c, common/features.c, common/features.h, common/gossip_constants.h, common/htlc_tx.c, common/htlc_tx.h, common/initial_commit_tx.c, common/initial_commit_tx.h, common/key_derive.c, common/keyset.c, common/sphinx.c, common/test/run-bolt11.c, connectd/peer_exchange_initmsg.c, gossipd/gossipd.c, gossipd/routing.c, hsmd/hsmd.c, lightningd/options.c, lightningd/peer_control.c, lightningd/peer_htlcs.c, onchaind/onchaind.c, tests/test_invoices.py
Which actually have some side effects:
1. We increase our default delays as per new recommendations.
2. We prune channels which haven't been updated by *both* peers in 2 weeks.
=> BOLT updates to latest

doc/lightning-invoice.7, doc/lightning-invoice.7.md, lightningd/invoice.c, tests/test_invoices.py
You can't pay them anyway, and at least one person used 0 instead of "any".
Closes: #3808
Changelog-Changed: JSON-RPC: `invoice` no longer accepts zero amounts (did you mean "any"?)
=> invoice: don't allow zero-value invoices.

.gitignore
Recent merged PR added a bunch of wiregen files.
=> .gitignore: Add missing gitignores.

plugins/libplugin-pay.c, plugins/libplugin-pay.h
Changelog-None: internal debugging
Makes it easier to debug payments with tons of splits.
=> plugins/libplugin-pay.c: Give cmd id and partid for each log message.

contrib/pyln-proto/pyln/proto/wire.py
Updates wire for pyln-proto to use coincurve in the `PublicKey` and `PrivateKey` classes.
Still unsure about https://github.com/ElementsProject/lightning/issues/3751#issuecomment-674788115
I may add some additional tests before moving from draft to an actual PR.
Close #3751
=> Updates proto to use coincurve for Public and Private keys

contrib/pyln-testing/pyln/testing/utils.py, lightningd/channel.c, lightningd/channel.h, lightningd/invoice.c, lightningd/lightningd.c, lightningd/lightningd.h, plugins/libplugin-pay.c, plugins/libplugin-pay.h, tests/test_invoices.py, tests/test_pay.py, wallet/test/run-wallet.c
This implements part of my suggestions in #3894.
The drawback is that unpublished nodes with this commit could potentially be harder to pay by other implementations that do not have any MPP at all yet.
This change basically embraces MPP and holds onto it tight and whispers lovingly into its ears "I want the whole world to have MPP".  On the other hand it does show that our MPP impl seems to be working nicely enough.
It was implementing this that revealed #3908 , if you are curious.  Yet another reason to abolish unpublished channels....
There is yet another bug in our MPP that this code also reveals, which is basically that if we get a blockheight disagreement between payee and payer, we are too aggressive with advancing the routehint pointer.  I will make a new test and fix for that …
=> Invoice round robin

contrib/pyln-testing/pyln/testing/utils.py, gossipd/routing.c, tests/test_closing.py, tests/test_pay.py
We are logging way too much from gossipd, causing noisy logs. This PR reduces
logs for incoming messages to those that actually caused a change in our
internal state (duplicate and old messages are just dropped silently now).
Most of the changes are related to tests breaking due to the reduced logging,
and the fixups required to get them working again. We fix them by polling for
the desired resulting state rather than observing the ephemeral state changes
represented by the logs. This may slow down some of the tests, since we now
poll, but that time is likely going to be used by concurrent tests anyway, and
we end up with more stable tests, that don't rely on implicit log ordering..
Changelog-Changed: gossipd: The `gossipd` is now a lot quieter, and will log only when a message changed …
=> gossipd: Make gossipd shut up

plugins/libplugin-pay.c, tests/test_pay.py
This proposal is a simple solution to #3926 and an alternative to
#3942/#3951. It is very much in the spirit of the original `presplit` payment
modifier in that it will create parts with a fixed size (not considering the
amount fuzzing to obfuscate the remainder), mostly independently of the total
amount. I think this is import to make it harder for observers to invert the
split and derive the original amount.
The change consists in adjusting the target amount for the individual parts
upwards should the current split result in too many parts. We use powers of 16
as a step size between buckets, resulting in at most 16 parts, and all
payments whose total amount is in the range of `x < amount <= 16*x` result in
the same part amount.
Why 16 as the upper limit of parts? Because it is …
=> paymod: Scale presplit amounts to support larger payments while maintaining size buckets for privacy

contrib/pyln-proto/pyln/proto/message/message.py
There's more work to do on subtypes here, but this fixes one small problem with their parsing.
=> pyln-proto: use vals for subtype parsing

tests/test_pay.py
We're failing this too often: we'd fail it more but it's disabled
with VALGRIND (it shouldn't be: @slow_test removes VALGRIND if SLOW_MACHINE
is set).
See #3989
=> pytest: disable test_mpp_interference_2.

Makefile, configure, wallet/db_postgres.c
We were using an ubuntu specific path to look for the headers for postgresql, which meant that on some other operating systems they would not get picked up. This uses the `pg_config` tool as detailed by the `libpq` [docs] to locate the header location in a portable way.
Fixes #3937 
[docs]: https://www.postgresql.org/docs/9.2/libpq-build.html
=> configure: Use pg_config to locate the header location

contrib/startup_regtest.sh
Re-write start_ln such that we can create up to 10 nodes locally for
testing. Useful for scenarios where more than two nodes are needed
=> contrib: start_ln now creates variable number of nodes

channeld/channeld.c
Fixes: #3608
Changelog-Changed: protocol: Ignore (and log as "unusual") repeated `WIRE_CHANNEL_REESTABLISH` messages, to be compatible with buggy peer software that sometimes does this.
=> channeld/channeld.c: Log and ignore repeated WIRE_CHANNEL_REESTABLISH.

.travis/build.sh
Prior to v0.20.1, PSBT parsing is stricter and doesn't allow both a
witness_utxo and non_witness_utxo to be set.
Requires https://drive.google.com/file/d/1oN9Jkcf-K3mXjqJQNsJSVRp-NV8gGzkQ/view?usp=sharing to be uploaded to https://storage.googleapis.com/c-lightning-tests/bitcoin-0.20.1-x86_64-linux-gnu.tar.bz2. cc @cdecker is this a drive you have access to?
=> travis: use bitcoind v0.20.1

plugins/libplugin-pay.c
Some pointless micro-optimizations which you are never going to feel anyway.
`payment_root` is actually optimized very well by GCC 9 in `-O2`, it gets transformed into a `while` loop as a tail-recursion optimization, and is therefore not touched by this PR.
=> Paymod micro optimization

doc/lightning-listpeers.7, doc/lightning-listpeers.7.md, lightningd/opening_control.c, lightningd/peer_control.c, tests/test_connection.py
It's actually not possible to currently tell if you're using anchor_outputs
with a peer (since it depends on whether you both supported it at *channel open*).
Changelog-added: JSON-RPC: `listpeers` shows `features` list for each channel.
=> listpeers: add `features` array using BOLT9 names.

Makefile, configure
On some systems (e.g., Gentoo), there can be multiple major versions of the PostgreSQL client library installed in parallel. There exists a separate `pg_config` and `libpq.so*` for each major version. This Pull Request adds support to C-Lightning's build system to allow the user to choose a specific version of the PostgreSQL client library to build and link against.
**Summary of proposed changes:**
* Introduce a `POSTGRES_LDLIBS` config variable, analogous to the existing `POSTGRES_INCLUDE` variable, and use it in place of `-lpq`, both in `Makefile` and in the Configurator script.
* When running `configure`, allow the user to override the name of `pg_config` by setting the `PG_CONFIG` environment variable. If unset, the default continues to be `pg_config`, which preserves the existing …
=> configure: Use pg_config to locate the library location too

Makefile, configure, devtools/Makefile, tools/headerversions.c, wallet/db_common.h, wallet/db_postgres.c, wallet/db_sqlite3.c
**Summary of proposed changes:**
* Introduce `SQLITE3_CFLAGS` and `SQLITE3_LDLIBS` config variables, whose values are automagically populated by calling out to `pkg-config`. If `pkg-config` is not found, then the new variables are defaulted as `SQLITE3_CFLAGS=` and `SQLITE3_LDLIBS=-lsqlite3`, which allows `configure` to continue working as before on systems lacking `pkg-config`.
* When running `configure`, allow the user to override the name of `pkg-config` by setting the `PKG_CONFIG` environment variable. If unset, the default is `pkg-config`, which means to use the system default (i.e., in `$PATH`) copy of `pkg-config`. Cross-compiling users would set the `PKG_CONFIG` environment variable to the path of a `pkg-config` binary that provides information about packages built for the target …
=> Allow building without SQLite3

doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/opening_control.c, openingd/openingd.c, tests/test_connection.py, tests/test_gossip.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py
I disabled this initially for option_anchor_outputs.  I revisited it, and discovered strange semantics: we neither used the number of sats they gave as a minimum, nor used it as an actual capacity.
Clarify what this option does: tries to ensure reasonable throughput.
=> Fixup min-capacity-msat semantics in preparation for anchor outputs.

plugins/libplugin-pay.c
This was changed recently, but without a bolt quote, we didn't find
this.
=> libplugin-pay: fix default CLTV.

common/Makefile, common/peer_status_wiregen.c, common/status_wiregen.c, doc/lightningd-config.5
One slipped in from a PR which predated the shastamp changes, and the other was my missing var in the common/Makefile.
Changelog-None
=> Fix common regen

lightningd/options.c, tests/test_connection.py
[Based on #3963]
This means we at least check that non-static-remotekey peers are not completely broken!
Changelog-None
=> Dev flag to set features

bitcoin/block.c, bitcoin/block.h, lightningd/chaintopology.c, lightningd/chaintopology.h, lightningd/plugin.c, plugins/bcli.c
Inspired by #3957 I took some time to benchmark and improve the block sync
time as well. It's not as impressive as the 30x that #3957 achieved but it has
some incremental gains. The benchmarks use the following code, with a local
`bitcoind` and the default `bcli` backend:
```python3
from pyln.client import LightningRpc
import time
import subprocess
startheight = 600000
numblocks = 1000
targetheight = startheight + numblocks
proc = subprocess.Popen([
'lightningd/lightningd',
'--network=bitcoin',
'--log-level=debug',
'--rescan=-{}'.format(startheight),
'--lightning-dir=/tmp/ll'
])
time.sleep(5)
rpc = LightningRpc('/tmp/ll/bitcoin/lightning-rpc')
def height():
return rpc.getinfo()['blockheight']
def rate(first, last):
if first == last:
return 0
return (last[1] - first[1]) / (last[0] - …
```
=> blocksync: Some performance improvements on top of #3957

.gitattributes, doc/Makefile, wallet/Makefile
If I understand the `maintainer` / `developer` split correctly it should be possible for a developer not to have all the python dependencies to generate some of the derived files that are now checked in. Contrary to this the generated DB files where cleaned up with `make clean`, so I moved them to the `maintainer-clean` target instead (and fixed the `wallet-maintainer-clean` target which had a typo).
I then added the derived files to the `.gitattributes` file which will collapse these derived diffs in the Github interface, to cut down on he noise when reviewing changes.
Finally, `maintainer-clean` was deleting the `deployable-lightning.pdf` file which would not get regenerated, and has heavy dependencies to rebuild. I removed that cleanup of a document that hasn't seen any changes for …
=> Cleanups to derived resouces

doc/PLUGINS.md, lightningd/plugin.c
Hi all!
With this PR, I'm proposing my idea to add a couple of the information to the proxy during the plugin configuration.
Inside my test to develop a new plugin, I noted the necessity to know if the node has the proxy enabled, the solution was to add a plugin option but I think this is redundant propriety during the node setup!
Another solution is to use the `listconfigs` to set up the connection inside the plugin but in some cases the method plugin call before to start some plugin methods! For instance, an alternative backend bitcoin/element that overrides the plugin `bcli` 
I hope that I'm losing nothings.
=> Added proxy information to plugin configuration

lightningd/log.c
This aligns all log TAGs except \*\*BROKEN\*\* which would require too many spaces for all the other logs.
This makes reading the logs with human eyes easier as the log message payload always starts at the same character of a line.
Additionally, I suggest replacing "UNUSUAL" with "WARN" and "\*\*BROKEN\*\*" with "FATAL" which seems more standard and is shorter.
Changelog-None
=> log: align level tags IO DEBUG INFO and UNUSUAL

doc/Makefile, doc/index.rst, doc/lightning-getinfo.7, doc/lightning-getinfo.7.md, doc/lightning-getlog.7, doc/lightning-getlog.7.md, doc/lightning-help.7, doc/lightning-help.7.md, doc/lightning-listconfigs.7, doc/lightning-listconfigs.7.md, doc/lightning-listfunds.7, doc/lightning-listfunds.7.md, doc/lightning-listnodes.7, doc/lightning-listnodes.7.md, doc/lightning-listtransactions.7, doc/lightning-listtransactions.7.md, doc/lightning-newaddr.7, doc/lightning-newaddr.7.md, doc/lightning-ping.7, doc/lightning-ping.7.md, doc/lightning-sendpsbt.7, doc/lightning-sendpsbt.7.md, doc/lightning-signpsbt.7, doc/lightning-signpsbt.7.md, doc/lightning-stop.7, doc/lightning-stop.7.md
All commands without documentation are
~There are a couple of other commands such as `stop`, `ping`, `listconfigs`, `getlog`, `getinfo`, but I don't think these need a documentation file~
The complete list here 
```
"commands": [
"getinfo",
"getlog",
"help",
"listconfigs",
"listnodes",
"ping",
"sendpsbt",
"signpsbt",
"stop"
]
```
The complete list of the commands is.
=> Fixed doc missed

lightningd/chaintopology.c, wallet/db_postgres_sqlgen.c, wallet/db_sqlite3_sqlgen.c, wallet/statements_gettextgen.po, wallet/wallet.c, wallet/wallet.h
This all started with the big idea of not keeping a large (~140k entries) UTXO
filter in memory, along with all the associated overhead in the hope of
reducing the memory footprint, but failed miserably. The savings come down to
about 4MB in RSS, but the block sync loses almost 20% of speed (from a
baseline of 5.26 blocks/s down to 4.16 blocks/s).
I still like some of the changes, like simplifying the detection of spends
based solely on the DB and looking at the `spendheight`, allowing us to do
some other changes, like batching the notification to `gossipd` instead of
notifying for each spent short-channel-id individually (not yet implemented).
I'll let the review gods decide the fate of this one :wink:
<details>
Maximum resident set size (kbytes): 226884
speed 5.260800463705923 blocks / …
=> Use the DB utxoset to detect spends for gossipd

.github/CODEOWNERS, bitcoin/psbt.h, contrib/pyln-client/pyln/client/lightning.py, doc/Makefile, doc/index.rst, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md, doc/lightning-multifundchannel.7, doc/lightning-multifundchannel.7.md, plugins/.gitignore, plugins/Makefile, plugins/multifundchannel.c, tests/test_connection.py
=> Multifundchannel

tests/test_wallet.py, wallet/reservation.c
fundpsbt / utxopsbt create a (typically) output-less PSBT,
however for elements we require the fees to be encapsulated in an
output.
this patch updates fundpsbt / utxopsbt to add a fee output for elements
transactions. includes test updates.
Fixes #3998
Changelog-Changed: `utxopsbt` and `fundpsbt` now include a fee output iif on an Elements chain
=> elementsd: add a fee output to a fund/utxopsbt for elements transactions

devtools/changelog.py, doc/REPRODUCIBLE.md, tools/repro-build.sh
- Added the release link to the changelog tool since I kept forgetting it...
- Added ubuntu 20.04 as a repro-build config
- Rewrote the repro-build documentation to the new docker-based system.
One thing we have though is the Fedora build which is included in the `SHA256SUMS` file but is not built reproducibly (yet), so we should likely not list it in the manifest at all, otherwise we might get complaints that the hashes do not match. What do you think @rustyrussell?
The huge advantage we have with docker is that this can all be automated now, and we can setup a nightly build machine that can feed into a repository.
=> Repro builds

bitcoin/psbt.c, bitcoin/psbt.h, contrib/pyln-client/pyln/client/lightning.py, doc/Makefile, doc/index.rst, doc/lightning-multiwithdraw.7, doc/lightning-multiwithdraw.7.md, plugins/.gitignore, plugins/Makefile, plugins/spender/main.c, plugins/spender/multiwithdraw.c, plugins/spender/multiwithdraw.h, tests/test_wallet.py
=> Multiwithdraw

lightningd/bitcoind.c, lightningd/chaintopology.c
Fixing the following error by changing 'enum feerate' to int.
lightningd/bitcoind.c:183:29: error: result of comparison of constant 8 with expression of type 'enum feerate' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
for (enum feerate f = 0; f < NUM_FEERATES; f++) {
=> Avoid compile error on macos mojave

connectd/test/Makefile, external/Makefile
And add secp_recovery to headers, while we're at it.
```
./wire/wire.h:7:10: fatal error: secp256k1_recovery.h: No such file or directory
#include <secp256k1_recovery.h>
^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:254: recipe for target 'connectd/test/run-initiator-success.o' failed
make: *** [connectd/test/run-initiator-success.o] Error 1
m
```
Changelog-None
=> Makefile: fix typo which can cause build failures.

wire/.gitignore
Just so we don't have untracked git changes all over the place when building experimental features.
=> chore: .gitignore _exp_ wiregen

lightningd/channel_control.c, tools/Makefile
The fixups from #4013 (a mem fix detected by ASAN and a build cleanup), so they are part of 0.9.1 even if it takes more time to make Travis happy with ASAN builds.
=> 4013 fixups

contrib/pyln-testing/pyln/testing/utils.py, doc/PLUGINS.md, lightningd/channel.c, lightningd/notification.c, lightningd/notification.h, tests/plugins/misc_notifications.py, tests/test_plugin.py, wallet/db_postgres_sqlgen.c, wallet/db_sqlite3_sqlgen.c, wallet/statements_gettextgen.po, wallet/test/run-wallet.c
This adds a new plugin notification message `channel_state_changed` that is called when a channel changes its state.
This PR contains code, test and doc.
Addresses #4018 
```json
{
"channel_state_changed": {
"peer_id": "03bc9337c7a28bb784d67742ebedd30a93bacdf7e4ca16436ef3798000242b2251",
"channel_id": "a2d0851832f0e30a0cf778a826d72f077ca86b69f72677e0267f23f63a0599b4",
"short_channel_id" : "561820x1020x1",
"old_state": "CHANNELD_NORMAL",
"new_state": "CHANNELD_SHUTTING_DOWN"
}
}
```
@fiatjaf added the question if it would be possible to have some kind of a 'reason' for a state changed operation. From a user or plugin developer perspective, this is mostly the distinction if a channel was closed by remote or by the user or for other (internal) reasons. We could add an string indication to …
=> feat: notification channel_state_changed

contrib/pyln-client/pyln/client/plugin.py, tests/plugins/htlc_accepted-crash.py, tests/test_plugin.py
Hooks do not tolerate failures at all. If we return a JSON-RPC error to a hook
call the only thing the main daemon can really do is to crash. This commit
adds a mapping of error to a safe fallback result, including a warning to the
node operator that this should be addressed in the plugin. The warning is
reported as a `**BROKEN**` message, and should therefore fail any testing done
on the plugin.
The alternatives would have been
- Allow plugins to return errors on hook calls, requiring a similar mapping inside `lightningd`. But I don't like relaxing the requirements on this. It feels magic enough as it is, but prevents us from accidentally hanging due to a plugin.
- Killing the plugin outright, which is basically just going to use the default action, which in case of security related …
=> pyln: Add safe fallback results for hooks

bitcoin/psbt.c, bitcoin/psbt.h, bitcoin/tx.c, bitcoin/tx.h, plugins/multifundchannel.c, plugins/txprepare.c, tests/test_plugin.py, tests/test_wallet.py, wallet/reservation.c
We should be using the `elements` tx_output, which includes the value + asset info required by the PSBT's sighash signing algorithm. 
This fixes that, plus adds back in some 'nice to have' extra PSET info (value + assset fields) for PSBTs constructed by `utxopsbt` / `fundpsbt`.
Finally, we allow the `test_sign_and_send` test to run on travis!
Edit: there were some other elements failures, those should be fixed now.
=> Elements PSBT / test fixup

plugins/keysend.c, plugins/libplugin-pay.c, plugins/libplugin-pay.h, plugins/pay.c
As revealed by the failure of tests in #3936, where we ended up trying
to send a partial payment using legacy style, we are not handling
style properly.
1. BOLT9 has features, so we can *know* that the destination supports
MPP.  We may not have seen a node_announcement.
2. We can't assume that nodes inside routehints support TLV.
3. We can't assume direct peers support TLV.
The keysend code tried to fix this up, so I'm not sure that this caused
the issue in #3968, though.
=> pay: fix handling of legacy vs tlv encoding.

plugins/keysend.c, plugins/libplugin-pay.c, plugins/libplugin-pay.h, plugins/pay.c, tests/test_pay.py
=> MPP: limit the number of HTLCs based on destination connectivity

common/jsonrpc_errors.h, doc/Makefile, doc/index.rst, doc/lightning-delpay.7, doc/lightning-delpay.7.md, lightningd/pay.c, tests/test_pay.py, wallet/db_postgres_sqlgen.c, wallet/db_sqlite3_sqlgen.c, wallet/statements_gettextgen.po, wallet/wallet.c, wallet/wallet.h
Hi all.
This Draft implement a new RPC command to delete the payment with the status `complete` `failed` marked like good first issue https://github.com/ElementsProject/lightning/issues/1995
However, this PR depends from the PR where I proposed to update the result of listpays command with `payment_hash` inside the result https://github.com/ElementsProject/lightning/pull/3888. In addition, with the @cdecker suggestion to add the `payment_hash` in all cases of types of payments, the command `delpay` can use only the `payment_hash` to identify the payment to remove and not `bolt11`.
This PR is a draft yet because I have some point to clarify with the team, for instance, the type of error that the command should be returned in cases of error. In other words, I see that the `LIGHTNINGD` error …
=> delpay: introduced a new rpc method to delete a payment by hash

contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/setup.py
Since pyln-bolt* specify the 0.8.4 version which we didn't upload, and the
requirements.txt specify `==0.8.4`, we need to backfill that version, even if we
could just bump it directly to 0.9.1.
Changelog-None
=> pyln: Bump proto version to match pyln-bolt*

plugins/pay.c
Deprecated, but this can happen:
```
==1578== Conditional jump or move depends on uninitialised value(s)
==1578== at 0x12B30E: amount_msat_add (amount.c:224)
==1578== by 0x11270B: add_amount_sent (pay.c:1734)
==1578== by 0x112D89: listsendpays_done (pay.c:1831)
==1578== by 0x114F4B: handle_rpc_reply (libplugin.c:555)
==1578== by 0x115704: rpc_read_response_one (libplugin.c:685)
==1578== by 0x115821: rpc_conn_read_response (libplugin.c:705)
==1578== by 0x148E40: next_plan (io.c:59)
==1578== by 0x1499BD: do_plan (io.c:407)
==1578== by 0x1499FB: io_ready (io.c:417)
==1578== by 0x14BBC1: io_loop (poll.c:445)
==1578== by 0x117A82: plugin_main (libplugin.c:1322)
==1578== by 0x113ABC: main (pay.c:2096)
```
Changelog-None
=> plugins/pay: handle case where amount_msat is 'null'.

connectd/connectd.c, connectd/connectd_wire.csv, connectd/connectd_wiregen.c, connectd/connectd_wiregen.h, lightningd/connect_control.c, lightningd/lightningd.h, lightningd/options.c, tests/test_connection.py
Found this because multifundchannel hung.  Want it for rc2.
=> Connection timeout

contrib/pyln-proto/pyln/proto/wire.py
In the current version of `LightningConnection`,  `remote_pubkey` is set to `None` at the begining of the handshake if the node is not initiator. However, it is never set to the counterparty pubkey after the handshake is completed. 
This sets `remote_pubkey` to ``rs`` in act three from the receiver side so the pubkey of the initiator is known by the receiver after the handshake.
=> pyln: Sets remote_pubkey for LightningConnection if node is not the initiator

common/amount.c, lightningd/plugin.c
OpenBSD uses macros for these, and gets upset.
Fixes: #4044
Changelog-None
=> lightningd: don't declare local vars stdin and stdout.

lightningd/jsonrpc.c, lightningd/peer_htlcs.c, lightningd/plugin.c, lightningd/plugin_control.c, lightningd/plugin_hook.c
We skipped these last time, so I did two releases :)
=> Deprecations for v0.9.2

openingd/dualopend.c
```
openingd/dualopend.c:958:42: error: result of comparison of constant 'WIRE_DUAL_OPEN_FAIL' (7003) with expression of type 'u8' (aka 'unsigned char') is always false
[-Werror,-Wtautological-constant-out-of-range-compare]
if ((msg_type = fromwire_peektype(msg)) == WIRE_DUAL_OPEN_FAIL) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
```
Found while rebasing #4013
=> dual-openingd: msg_type should be dualopend_wire not u8

tests/test_db.py, wallet/db_postgres.c
It turns out that it isn't always possible to express the connection
parameters in a URI-style DSN. The postgresql primitives provide an
alternative in the form of key-value DSNs [1], which allow for a far wider
range of possible configuration parameters. Specifically in my case I wanted
to have mutual authentication using TLS/SSL server and client certificates, on
top of password authentication.
With this change we still use the `scheme://` portion of the DSN to select
which backend to use, while we attempt to parse the connection string without
it first (which is the key-value option) and if that fails we fall back to the
full URI connection. Since we only attempt to parse, and don't directly
connect we don't actually connect twice.
So this is now a possibility:
``` text …
```
=> db: Add support for key-value pair DSNs in postgresql

Makefile, configure
At least on my Ubuntu box, they're compatible. If they're not, we need
to disable regeneration altogether.
Fixes: #4075
Changelog-None
=> Makefile: work with shasum -a as well as sha256sum.

bitcoin/base58.c, bitcoin/psbt.c, bitcoin/psbt.h, bitcoin/tx.c, bitcoin/tx_parts.c, common/daemon.c, common/psbt_open.c, common/setup.c, common/test/exp-run-psbt_diff.c, common/utils.c, common/utils.h, hsmd/hsmd.c, lightningd/dual_open_control.c, wallet/reservation.c, wallet/walletrpc.c
This captures *all* libwally allocations, and also maintains logical structure around psbt and tx allocations (i.e. tx owns it parts, psbt owns its parts).
Changelog-None
=> Libwally: neaten tal capture.

contrib/pyln-proto/pyln/proto/onion.py, contrib/pyln-proto/tests/test_onion.py
This is a simple (insecure) implementation of the onion creation and processing functionality. It is mainly intended to be used in `lnprototest` and experimental code, but is not guaranteed to have constant-time execution, and should not be used in production.
The PR builds on top of #3811, so the real content is in the last 4 commits.
Depends #3811
=> Pure-python implementation of the Sphinx onion protocol

lightningd/opening_control.c, tests/test_plugin.py
... As discussed in yesterdays meeting, log BROKEN here is better, as a reliant plugin may behave incorrectly if that happens.
=> fix: openchannel_hook log BROKEN on duplicated close_to

tests/plugins/htlc_accepted-failcode.py, tests/test_plugin.py
We added a conversion of failcodes that do not have sufficient information in
faac4b28ad. That means that a failcode that'd require additional information
in order to be a correct error to return in an onion is mapped to a generic
one since we can't backfill the information.
This tests that the mapping is performed correctly and replicates the
situation in #4070
Closes #4070
Changelog-None
=> pytest: Add test for failcode conversion

configure, contrib/sanitizer_suppressions/asan, contrib/sanitizer_suppressions/lsan, openingd/dualopend.c
I'm looking at including some fuzz targets, and will probably use clang along with its address sanitizer (and hopefully many others!).
This removes the restriction on only using gcc with ASAN, by using suppressions instead when using clang (see #2285 for the reason).
This also enables ASAN on non-already-under-valgrind Travis jobs.
=> Re-enable ASAN when building with clang

tests/test_closing.py, tests/test_connection.py, tests/test_db.py, tests/test_gossip.py, tests/test_invoices.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py
See 668debb74f5d666d3bbe827ab0a406ee8afade73
Before this change warning were produced:
```
$ pytest tests
...
.../src/lightning-fixtures/contrib/pyln-testing/pyln/testing/utils.py:744: DeprecationWarning: LightningNode.fund_channel is deprecated in favor of LightningNode.fundchannel
warnings.warn("LightningNode.fund_channel is deprecated in favor of "
```
Changelog-None
=> pytest: Rename all fund_channel to fundchannel

.travis.yml, .travis/build.sh, contrib/pyln-testing/pyln/testing/db.py, contrib/pyln-testing/pyln/testing/fixtures.py
This should help locate and fix any issue that was casing the `TEST_DB_PROVIDER=postgres` test configuration on Travis CI to fail. In order to do this we reduce `--reruns` from 5 to 2, potentially showing more flaky tests, but we should address them anyway, and we fail on the first error we get, since the rest of the test run is doomed anyway, and the extra information about which other tests would also fail is not worth the extra wait time.
The `db_provider` fixture goes from being session-scoped to being test-scoped, so we start and stop a separate instance of postgresql on each test, but measuring the performance impact showed a mere slowdown of 20 seconds on a 1250 second overall test-time, so negligible. On the upside it massively improves test isolation, and we no longer have to …
=> Re-enable postgres test configuration after addressing issue 4080

lightningd/lightningd.c
The 100MB log buffer has been the biggest memory footprint for the daemon.
Keeping 10MB for emergency log dumps seems sufficient.
This has been mentioned in the last developer meeting.
**Update:** As @rustyrussell points out the log buffer always contains everything regardless of the config (io, esp and debug, ...). An average log entry has about 170Bytes, lets say 200Bytes with certain overhead. A well connected node may produce something like up to ~2 events per second depending on usage. Thus a 10MB buffer will last for ~8Hrs.
Changelog-Changed: In-memory log buffer reduced from 100MB to 10MB
=> chore: reduce log buffer from 100MB to 10MB

Makefile, contrib/pyln-client/Makefile, contrib/pyln-proto/pyln/proto/bech32.py, contrib/pyln-proto/pyln/proto/invoice.py, contrib/pyln-proto/pyln/proto/zbase32.py, contrib/pyln-testing/Makefile, contrib/pyln-testing/pyln/testing/btcproxy.py, contrib/pyln-testing/pyln/testing/db.py, contrib/pyln-testing/pyln/testing/utils.py
This adds `mypy` verification to `pyln-client` and `pyln-testing`, while also restructuring the Makefiles a bit.
I added the verification to the pyln module Makefiles and call it from the main Makefile in order to maintain logical separation between the main codebase and the python modules, which we might end up splitting out into a separate repository eventually.
I started annotating `pyln-proto` but the `messages` and `invoice` module turned out to be a rather deep rabbit-hole that need more refactoring. It is integrated into the main Makefile and progress can be checked with `make check-pyln-proto`, so I'll spin this out into a separate issue.
I chose to ignore any external dependency that doesn't have annotation stubs in the [typeshed](https://github.com/python/typeshed) repository …
=> Add mypy typing verification to `make check-python`

tests/test_wallet.py
Broken back in 3b8c0a7397cc0694117dfe63ecb2bff0b6957a4b which
changed the behavior of funding not to mark as immediately spent.
Changelog-None
=> pytest: fix experimental test.

contrib/pyln-testing/pyln/testing/fixtures.py
We were always deleting the directories.
Changelog-None
=> pytest: fix overzealous removal of directories on failure.

contrib/pyln-client/pyln/client/plugin.py
It is often pretty usefuk to use the builtin logging module to debug things,
including libraries that a plugin may use. This adds a simple
`PluginLogHandler` that maps the python logging levels to the `lightningd`
logging levels, and formats the record in a way that it doesn't clutter up the
`lightningd` logs (no duplicate timestamps and levels).
This allow us to tweak the log level that is reported to `lightningd` simply
using the following
```python3
import logging
logging.basicConfig(level=logging.DEBUG)
```
Notice that in order for the logs to be displayed on the terminal or the
logfile, both the logging level in the plugin _and_ the `--log-level`
`lightningd` is running need to be adjusted (the python logging level only
controls which messages get forwarded to `lightningd`, it does …
=> pyln: Add logging handler that passes records to lightningd

contrib/pyln-client/pyln/client/plugin.py, contrib/pyln-client/tests/test_plugin.py
We had a couple of instances where a plugin would be killed by `lightningd`
because we were returning a result of an exception twice, and it was hard to
trace down the logic error in the user plugin that caused that. This patch
adds a traceback the first time we return a result/exception, and raise an
exception with a stacktrace of the first termination when a second one comes
in.
This can still terminate the plugin, but the programmer gets a clear
indication where the result was set, and can potentially even recover from it.
Changelog-Added: pyln: Plugin method and hook requests prevent the plugin developer from accidentally setting the result multiple times, and will raise an exception detailing where the result was first set.
=> pyln: Plugin methods and hooks refuse to set results twice

doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/lightningd.h, lightningd/options.c, plugins/bcli.c, tests/test_closing.py, tests/test_misc.py, tests/test_plugin.py
Using bitcoind's `estimatesmartfee 4 ECONOMICAL` is extremely aggressive for mutual close; particularly since you can use CPFP if you really want to speed it along.  Drop to `100 ECONOMICAL` (i.e. "slow") by default.
=> Change mutual close feerate to be much less aggressive.

contrib/pyln-testing/pyln/testing/utils.py
When testing against current master (`209900`), I got errors about a non-existing wallet.
```
$ pytest tests
...
E           bitcoin.rpc.JSONRPCError: {'code': -32601, 'message': 'Method not found (wallet method is disabled because no wallet is loaded)'}
```
Changelog-None
=> pyln: Add a fixture for createwallet

lightningd/peer_htlcs.c
Great report from whitslack on this crash at startup:
```
2020-10-07T13:03:21.419Z **BROKEN** lightningd: FATAL SIGNAL 6 (version 0.9.1)
2020-10-07T13:03:21.419Z **BROKEN** lightningd: backtrace: common/daemon.c:51 (crashdump) 0x559fb67bcc76
2020-10-07T13:03:21.419Z **BROKEN** lightningd: backtrace: /var/tmp/portage/sys-libs/glibc-2.32-r2/work/glibc-2.32/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0 ((null)) 0x7f61cdca8baf
2020-10-07T13:03:21.419Z **BROKEN** lightningd: backtrace: ../sysdeps/unix/sysv/linux/raise.c:50 (__GI_raise) 0x7f61cdca8b31
2020-10-07T13:03:21.419Z **BROKEN** lightningd: backtrace: /var/tmp/portage/sys-libs/glibc-2.32-r2/work/glibc-2.32/stdlib/abort.c:79 (__GI_abort) 0x7f61cdc92535
2020-10-07T13:03:21.419Z **BROKEN** lightningd: backtrace: …
```
=> lightningd: fix crash when we try to send fail_htlc msg to onchaind.

channeld/channeld.c, channeld/full_channel.c, tests/test_connection.py
As noted in this morning's spec call, I tracked it down.
=> Fix HTLCs rexmit out of order

configure
OpenBSD's `sha256sum` equivalent is `sha256`. This adds support in `configure` for it.
=> Add sha256 check to configure for OpenBSD 

openingd/common.c
`test_opening_tiny_channel` fails if EXPERIMENTAL_FEATURES is on because
we don't include the anchor in our reserve if we're the channel opener.
Seems fine to include in all cases?
=> openingd: patch test_opening_tiny_channel under EXP_FEAT

contrib/pyln-client/pyln/client/lightning.py, contrib/pyln-testing/pyln/testing/utils.py, doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md, doc/lightning-multifundchannel.7, doc/lightning-multifundchannel.7.md, plugins/spender/fundchannel.c, plugins/spender/multifundchannel.c, tests/test_closing.py, tests/test_connection.py, tests/test_gossip.py, tests/test_invoices.py, tests/test_misc.py, tests/test_pay.py
We've had `close_to` available on `fundchannel_start` for a while now. This wires it all the way through to general `fundchannel` users.
=> Expose `close_to` up through `multifundchannel` + `fundchannel`

Makefile, wallet/Makefile
This adds an environment variable $NO_PYTHON check to Makefiles so that:
- It checks and runs into an defined error instead of some python hickup:
`ModuleNotFoundError: No module named 'mako'`
- makes it possible to manually export this environment variable NO_PYTHON=1
to run the same testcase that travis is running on job 1 which causes
so much pain ;)
Note: also we can use this to sure by bisecting each commit of a branch the correct SQL generations are being committed.
Changelog-None
=> chore: adds env NO_PYTHON check to Makefiles

doc/lightning-openchannel_init.7, doc/lightning-openchannel_init.7.md, lightningd/dual_open_control.c, openingd/dualopend.c, openingd/dualopend_wire.csv, openingd/dualopend_wiregen.c, openingd/dualopend_wiregen.h
This one's mostly small fixes found while running some tests. Plus we completely rework `check_balances`, the method that needed some help anyway.
Based on #4133, start at 3262c3a
=> cleanups for some dual-funding related code, II of III

channeld/channeld.c, channeld/channeld_wire.csv, channeld/channeld_wiregen.c, channeld/channeld_wiregen.h, common/psbt_open.c, common/psbt_open.h, doc/PLUGINS.md, lightningd/channel.h, lightningd/channel_control.c, lightningd/dual_open_control.c, lightningd/notification.c, lightningd/notification.h
This one's actually a big logical change. Prior to this (in #4069), we would wait until the user provided the signatures for `openchannel_signed` before we opened up a channeld and sent them to our peer. 
The problem with this is that we wouldn't receive the peer's sigs until after we've sent our sigs.  To make this work with `multifundchannel` (coming soon, watch this spaceTM), we need to be able to collect all of our peer's sigs first, collate them for all the other peer's we're signing with, and then present the collected sigs (ours plus all the other nodes) to the peers.
To do this, we go ahead and jump directly into channeld after we've collected the `commitment_sigs` from our peer. We can now call `openchannel_signed` at our leisure -- ideally as soon as you've got all the …
=> cleanups for some dual-funding related code, III of III

openingd/openingd.c
Fixes #4140
Reported-By: @PsySc0rpi0n
=> opening: use correct dust_limit for reserve floor

.gitignore, Makefile, common/amount.c, common/base64.c, common/base64.h, common/test/run-amount.c, configure, contrib/sanitizer_suppressions/asan, doc/FUZZING.md, tests/fuzz/Makefile, tests/fuzz/fuzz-addr.c, tests/fuzz/fuzz-amount.c, tests/fuzz/fuzz-base32-64.c, tests/fuzz/fuzz-bech32.c, tests/fuzz/fuzz-bigsize.c, tests/fuzz/fuzz-bip32.c, tests/fuzz/fuzz-channel_id.c, tests/fuzz/fuzz-close_tx.c, tests/fuzz/fuzz-initial_channel.c, tests/fuzz/libfuzz.c, tests/fuzz/libfuzz.h, tests/fuzz/run.py
This introduces coverage-guided fuzz testing using [libfuzzer](https://www.llvm.org/docs/LibFuzzer.html).
We've been[ talking about it](https://github.com/ElementsProject/lightning/issues/2662) for some time now, and i'm sure it could help us to uncover trivial bugs with minimal overhead, more sneaky ones more easily than with unit tests, and finally to avoid regressions by maintaining a seed corpus to ran patches against.
Going further, [structure-aware fuzzing](https://github.com/google/fuzzing/blob/master/docs/structure-aware-fuzzing.md) could help us with [Bitcoin Script creation](https://github.com/jonasnick/bitcoinconsensus_testcases) or even with the state machine  which while more intrusive because crypto seems plausible because of the daemons separation and messages.
For now, …
=> Fuzz testing integration

contrib/pyln-proto/pyln/proto/zbase32.py, contrib/pyln-proto/tests/test_primitives.py, contrib/pyln-proto/tests/test_zbase32.py
Before this PR, `zbase32.encode` could only be used for messages with length multiple of 5. This is because zbase32 encoding uses blocks of 5-bit words for the encoding. However, arbitrary length messages should be encodable as well by properly padding them to match the expected length.
The additions to this PR could be summarised as follows:
- Add helper functions to encode / decode arbitrary length data by padding / cutting the provided data (`_message_to_bitarray` and `_bitarray_to_message`).
- Mark any function that is not supposed to be used publicly as "private".
- Adds input checking to the public functions (`encode`, `decode`, `is_zbased32_encoded`) and raise exceptions accordingly.
- Add short descriptions to each function.
- Add tests for the whole module.
Changelog-None
=> pyln: Adds some improvements to pyln.proto.zbase32

bitcoin/script.c, bitcoin/script.h, channeld/channeld.c, common/psbt_internal.c, common/psbt_internal.h, openingd/dualopend.c
Few small things before we get into "dual-funding over multifundchannel" fun.
- 'finalize' the redeemscript (if present) at the same time that we set final witness-scripts. libwally `finalize` ignores unfinalized redeemscripts if `final_witness_stack` field is set.
- correctly handle dev-memleak calls that are made while we're doing tx output/input updates.
Changelog-None
=> Prelim patches for dual-funding/multifundchannel

Makefile, wallet/Makefile
== is a bash extension; in shell it's a single =:
```
/bin/sh: 1: [: unexpected operator
sql-rewrite wallet/db_postgres_sqlgen.c
```
Changelog-None
=> Makefile: fix bashism in NO_PYTHON

common/features.c, common/features.h, common/test/run-features.c, lightningd/options.c
Allows `dev-force-features` to also accept either '+231' or '-19' as a way to flag on or off a single feature.
This is probably the most likely usecase.
Changelog-None
=> Add second format for 'dev-force-features'

channeld/channeld.c, common/psbt_internal.c, common/psbt_open.c, common/psbt_open.h, common/test/exp-run-psbt_diff.c, lightningd/dual_open_control.c, openingd/dualopend.c, openingd/dualopend_wire.csv, openingd/dualopend_wiregen.c, openingd/dualopend_wiregen.h, tests/plugins/df_accepter.py, wire/extracted_peer_experimental_dual_fund_more
Here, we incorporate two new changes to the draft spec:
- `serial_id` goes from a u16 to u64 (this is to avoid collisions when doing multifundchannels)
- We update the feerate protocol. Instead of the opener setting a 'firm' feerate, we allow the accepter to choose a feerate within a provided range. This PR includes updates turn the current 'implicit' acceptable range to be explicit (in the role of the opener). In the accepter case, we merely delegate the decision to the plugin via the `openchannel2` hook.
=> Updates to dual-funding spec

common/gossmap.c, common/gossmap.h, plugins/libplugin-pay.c
1. One place returned false instead of -1.
2. The names implied it returned a bool, and it doesn't.
Fix both, and curse C's loose typing a little.
Changelog-None
=> gossmap: fix return of gossmap_xxx_has_feature, rename.

lightningd/htlc_set.c, tests/test_pay.py
(Somehow I missed pushing this up; was meant to be in previous release)
This will allow nodes (with log-level=debug) to gather how many payments
are made without payment_secrets.  We need to know this so we know when
we can make them compulsory.
Changelog-None
=> lightningd: note whether payment secret is used or not.

wire/tlvstream.h
Implementation of towire_tlvs was removed from wire/tlvstream.c at db92c2ac5ec5cf46bad6023f7560a3e06c7a9e39
Signed-off-by: YOSHIDA Masanori <masanori.yoshida@gmail.com>
Changelog-None
=> wire: remove declaration of towire_tlvs since its implementation is already removed

common/test/run-features.c
Just applied the same suppression as rusty in 6635fe12e4 
My cppcheck was complaining about the same issue in the following functions.
I wonder why travis does not care though, maybe its having another version.
Also, I must admit that I can't see why this is a 'false' positive :thinking: .
Update: Figured out myself :D 
Changelog-None
=> chore: fixes a cppcheck false positive

bitcoin/signature.c
If a tx is larger than 2k, libwally will do an alloc:
```
lightning_hsmd: common/setup.c:11: wally_tal: Assertion `wally_tal_ctx' failed.
0x11c283 wally_tal
common/setup.c:11
0x15ebd1 wally_malloc
../../../libwally-core/src/internal.c:233
0x171e9e tx_to_bip143_bytes
../../../libwally-core/src/transaction.c:1918
0x172cda tx_to_bytes
../../../libwally-core/src/transaction.c:2086
0x1759df tx_get_signature_hash
../../../libwally-core/src/transaction.c:2776
0x175afd wally_tx_get_signature_hash
../../../libwally-core/src/transaction.c:2800
0x175b62 wally_tx_get_btc_signature_hash
../../../libwally-core/src/transaction.c:2810
0x1297d9 bitcoin_tx_hash_for_sig
bitcoin/signature.c:139
0x1298ca sign_tx_input
bitcoin/signature.c:161
0x10e701 handle_sign_remote_commitment_tx
hsmd/hsmd.c:1011
0x110f7f …
```
=> bitcoin/signature: wrap libwally call.

channeld/channeld.c, lightningd/dual_open_control.c
We were silently converting a side enum (3 variants) to a tx_role enum
(2 variants).
Signed-off-by: Antoine Poinsot <darosior@protonmail.com>
Changelog-None
=> dual_open: correct silent enum conversions

lightningd/jsonrpc.c, lightningd/lightningd.c
The rpc_command hook means that we have a delay between receiving
a JSON command and actually calling the handler.  In this case, the
caller can go away:
```
==1348== Invalid write of size 1
==1348==    at 0x130EA6: json_notifications (jsonrpc.c:1350)
==1348==    by 0x12EE9E: command_exec (jsonrpc.c:636)
==1348==    by 0x12F3C6: rpc_command_hook_callback (jsonrpc.c:752)
==1348==    by 0x15AA08: plugin_hook_callback (plugin_hook.c:210)
==1348==    by 0x155C9D: plugin_response_handle (plugin.c:398)
==1348==    by 0x155E84: plugin_read_json_one (plugin.c:504)
==1348==    by 0x15603D: plugin_read_json (plugin.c:548)
==1348==    by 0x1D4AB3: next_plan (io.c:59)
==1348==    by 0x1D5630: do_plan (io.c:407)
==1348==    by 0x1D566E: io_ready (io.c:417)
==1348==    by 0x1D7834: io_loop (poll.c:445) …
```
=> lightningd: fix crash if we abort after enabling notifications.

lightningd/opening_common.c, lightningd/opening_common.h, lightningd/opening_control.c, tests/test_connection.py
Fixes: #4108
Requesting review from nifty and rusty, since my grasp of the openingd is not good.
As well, there may be a similar issue in dual-funding, so please consider as well for that point-of-view, I am much more ignorant about the dual-funding flow than openingd flow.
=> openingd/: Fail `fundchannel_start` if we already are, or will become, the fundee.

common/utils.h, contrib/pyln-client/pyln/client/plugin.py, doc/PLUGINS.md, doc/lightningd-config.5, doc/lightningd-config.5.md, lightningd/plugin.c, lightningd/plugin.h, lightningd/plugin_hook.c, lightningd/plugin_hook.h, plugins/libplugin.c, plugins/libplugin.h, tests/plugins/dep_a.py, tests/plugins/dep_b.py, tests/plugins/dep_c.py, tests/plugins/dep_d.py, tests/plugins/dep_e.py, tests/plugins/test_libplugin.c, tests/test_plugin.py
This allows hooks to specify they must be before/after some other plugins.  Either by basename or full pathname.
As our plugin ecosystem grows and gets more sophisticated, such conflicts will inevitably occur where multiple plugins want to ensure they are called in certain order.  
We could implement a priority number system, but that's usually just window-dressing on what people really want (though, unlike this, would allow you to specify that you must be first, or last: we could add wildcards if we wanted to).
Getting this in now means that after a few releases, plugin authors will simply be able to assume its existence.
Fixes: #4005 (thanks @m-schmoock for pointing that out!)
=> Order specifications for hooks

gossipd/gossipd.c, gossipd/gossipd.h, gossipd/queries.c, gossipd/queries.h, gossipd/seeker.c, gossipd/test/run-next_block_range.c, tests/test_gossip.py
We can use a counter not a bitmap since the spec insists replies be in order.
We remove an old LND workaround, and add another.
Then we make our code more efficient for the "query every single channel!" case.
=> Remove lnd gossip workaround, clean up for modern spec

doc/lightning-hsmtool.8, doc/lightning-hsmtool.8.md, tools/hsmtool.c
Add `generatehsm` method to hsmtool to derivate BIP32 seeds from a
mnemonic using the BIP39 standard.
The new method uses libwally for the BIP39 to BIP32 derivation. It also
fails if an hsm_secret file already exists, so we do not overwrite
someone else's wallet without noticing.
It allows the use of passphrases, the ECHO mode in the terminal is
disable for higher security.
=> `hsm_secret` generation from a seed-phrase

contrib/pyln-testing/pyln/testing/fixtures.py
With older bitcoind, PSBTs fail:
```
def test_utxopsbt(node_factory, bitcoind, chainparams):
...
>       psbt = bitcoind.rpc.decodepsbt(funding['psbt'])
tests/test_wallet.py:561: 
...
self = <bitcoin.rpc.RawProxy object at 0x7f4ec602e100>, service_name = 'decodepsbt'
args = ('cHNidP8BADMCAAAAAaoMihSVXlpdBHGcJePiroqtwq/b1zu09j8IkTG4OKs7AQAAAAD9////AGYAAAAAAQDeAgAAAAABAefqB6BkZE1/AqXaf36T02a7.../7Stf971PEgvUXgvASECXPTIO6tIVxDih6tfKy6suj6WJhhjycwoaTeuso/AQ8llAAAAAQEfQEIPAAAAAAAWABQB+tkKvNZml+JZIWRyLeSpXr7hZQA=',)
postdata = '{"version": "1.1", "method": "decodepsbt", "params": ["cHNidP8BADMCAAAAAaoMihSVXlpdBHGcJePiroqtwq/b1zu09j8IkTG4OKs7AQ...gvUXgvASECXPTIO6tIVxDih6tfKy6suj6WJhhjycwoaTeuso/AQ8llAAAAAQEfQEIPAAAAAAAWABQB+tkKvNZml+JZIWRyLeSpXr7hZQA="], "id": 1}'
headers = {'Authorization': …
```
=> pyln-testing: require bitcoin v0.20.1 for PSBT handling, and create wallet for v0.21

common/Makefile, common/descriptor_checksum.c, common/descriptor_checksum.h, contrib/pyln-testing/pyln/testing/fixtures.py, doc/FAQ.md, doc/lightning-hsmtool.8, doc/lightning-hsmtool.8.md, tests/fuzz/Makefile, tests/fuzz/fuzz-amount.c, tests/fuzz/fuzz-descriptor_checksum.c, tests/fuzz/libfuzz.c, tests/fuzz/libfuzz.h, tests/test_wallet.py, tools/Makefile, tools/hsmtool.c
This adds a new `dumponchaindescriptors` command to `hsmtool` which can:
- Dump 2 `xpub`-based descriptors (one for each scriptPubKey type we create)
- Useful for external service (see https://github.com/ElementsProject/lightning/issues/4110 for more details)
- ~~Possibly dump 2 `xpriv`-based descriptors (one for each scriptPubKey type we create)~~ Removed: footgun with anchor outputs (thanks niftynei!)
- ~~Useful for backing up / restoring the onchain wallet easily~~
TODO:
Fixes https://github.com/ElementsProject/lightning/issues/4110
Ping @jb55 : finally got to https://github.com/jb55/clightning-dumpkeys/issues/2 :-)
=> Hsmtool: enable dumping output descriptors of onchain wallet
