ElementsProject/lightning

lightning.proto

With upcoming proto3, I think it is better to specify the syntax in the proto file (protoc complains otherwise).
Btw, any reason why you didn't use the fixed64 hack for, say, bitcoin_pubkey/key field ? Why not define a "oneof" [fixed size 65-bytes key] or [fixed size 33-bytes key], for the sake of consistency ?
I am not saying I would do that, I would actually have just used bytes everywhere.

explicitely specified proto version

---

test/test_onion.c
test/test_onion.py

Here's a rough go at an alternative implementation of the onion routing proposal. Might be useful for validation / test suite / etc.

Python implementation of onion routing spitball

---

.gitignore
INSTALL.md
Makefile

These are the steps/changes needed to get the build to work locally.

doc: add install notes

---

daemon/peer.c

Hi,
I believe that there's a small bug in the current code which copies the local channel state, including the local fee rate, into the remote commit data. It should use the fee rate received in their open message instead. 
Thanks.

setup_first_commit: initialize their remote commit with their commit fee rate

---

Makefile

Added explicit compilation and linking of ccan/asort as needed by daemon/chaintopology

Makefile : adding ccan/asort.o target and binary

---

bitcoin/signature.c
bitcoin/signature.h
daemon/Makefile
daemon/chaintopology.c
daemon/chaintopology.h
daemon/irc_announce.c
daemon/irc_announce.h
daemon/lightningd.c
daemon/lightningd.h
irc.c
irc.h
utils.c
utils.h

Implements a simple IRC client on top of io_loop and uses it to announce existing channels periodically and collect announced channels to get a local view of the network's topology.

Implement IRC peer discovery

---

daemon/jsonrpc.c

A mixup between object and array notation in the getlog response was
resulting in invalid JSON.

log/jsonrpc: getlog was returning invalid JSON.

---

daemon/jsonrpc.c
daemon/jsonrpc.h
daemon/routing.c

'getchannels' returns a 'channels' array containing an object for each
known channel. Each channel object represents one direction of a
bidirectional channel, with a from and a to node ID along with the fees
for that direction. This matched the internal storage of channels and
allows unbalanced fees for each direction.

jsonrpc: Added 'getchannels' RPC method.

---

daemon/irc_announce.c
daemon/jsonrpc.c
daemon/jsonrpc.h
daemon/lightningd.h
daemon/routing.c
daemon/routing.h
irc.c
irc.h

Added IRC node annoucement. Each node now announces its existence on the IRC channel, with its ID, hostname and port. The announcements are signed by the node's ID and the external address/hostname is discovered by issuing a WHOIS to the IRC server. We'll need to figure out a better way of identifying our external IP if we drop IRC.
The `getnodes` JSON-RPC method was also added to see what nodes we know about.
Notice that there currently is no timeout for known nodes, nor is there permanent storage of any kind, so restarting the node is currently the only way to forget about nodes.

Added IRC node announcements to learn about nodes in the network

---

daemon/routing.c

Fixes #50. Was causing a segfault because it was creating an empty route
and was trying to extract the first hop as next hop. Routes through self
can still be created manually, but `sendpay` would still refuse to act
on them due to the missing self-link.

routing: Refuse self-route

---

daemon/jsonrpc.c
daemon/lightning-cli.c

The JSON-RPC was non-standard compliant in that it omitted the required
`jsonrpc` entry and it was returning both `error` as well as
`result`. This fixes both of these issues.

jsonrpc: Accomodate some pedantic JSON-RPC impls

---

daemon/invoice.c

`listinvoice` was not handling numeric labels correctly if they are not
passed in as JSON strings (which was the behavior of
`lightning-cli`). So now we accept both string labels as well as numeric
labels.
Fixes #47

jsonrpc: Correctly handle numeric invoice labels

---

daemon/irc_announce.c
daemon/routing.c
daemon/routing.h

So far we have been announcing the `locktime` instead of the `min_htlc_expiry` which would have been needed for route computation.
Aliases are now also handled, though not used anywhere yet

irc: Announce the correct expiry and handle aliases

---

daemon/db.c

db: store closing signature correctly.

---

daemon/test/Makefile
daemon/test/scripts/setup.sh
daemon/test/scripts/shutdown.sh
daemon/test/scripts/vars.sh
daemon/test/test.sh

This reduces runtime (particularly if eatmydata is installed), and allows some parallelism in running test.sh.  No changes to the tests themselves, though they can definitely be reduced.

Test speedups

---

daemon/peer.c

db_forget_peer() was harmless, but we haven't been entered into the
database yet anyway, and it asserted that we should have been STATE_CLOSED.
Closes: #67

peer_disconnect: simply free if in STATE_INIT.

---

daemon/peer.c

I must've left that on in, sorry about that. Fixes #89

bugfix: Removed spurious printf in peer.c

---

daemon/sphinx.c

Our HMACs are truncated to 20 byte, but sodium still generates 32 byte
HMACs and we were handing in a buffer that was too small, so we
overflowing the buffer by 12 bytes. This manifested itself only in the
32 bit variant because of different alignment in the 64bit version.
Fixes #94.

sphinx: Fixed a buffer overflow in hmac generation

---

daemon/lightningd.c
daemon/test/scripts/helpers.sh

When we support the Milan protocol, we'll use a default port.  But
for now, don't listen at all unless a port is specified.
Fixes: #54

lightningd: don't listen at all if no port number set.

---

daemon/cryptopkt.c
daemon/db.c
daemon/db.h
daemon/log.c
daemon/log.h
daemon/peer.c

So it builds on
```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
```
Thanks Christian for the insights on Lightning yesterday.

Fix warnings for clang build (-Werror)

---

wire/tools/generate-wire.py

It was failing the compile if we had a recent enough spec.

trivial: Add `addresses` field to generate-wire.py

---

bitcoin/pubkey.c
bitcoin/pubkey.h
daemon/Makefile
daemon/chaintopology.c
daemon/lightningd.c
daemon/lightningd.h
daemon/p2p_announce.c
daemon/p2p_announce.h
daemon/packets.c
daemon/packets.h
daemon/peer.c
daemon/peer.h
daemon/routing.c
daemon/routing.h
daemon/secrets.h
lightning.pb-c.c
lightning.pb-c.h
lightning.proto
wire/gen_wire_csv

Implementation of the gossip protocol as per spec (lightningnetwork/lightning-rfc@8c8664452b079e66bd3356cac9c73b8e878ccbb7). The following changes are included:
- A small shim that allows the new message format to be transported over the legacy transport layer
- Tracking transaction indexes so that we can check anchor transactions
- Creation and handling of `channel_announcement`, `channel_update` and `node_announcement`
- Regular broadcasts as heartbeat
- Triggering announcements on channel establishment
- Synchronization of routing tables upon connection
Signatures are partially populated, but aren't checked yet since we need to have the channel establishment implemented first, which provides us with the remote signatures as well.
Fixes #88

Implementation of the gossip protocol

---

daemon/Makefile

So far it was failing silently, now it diffs the Makefile state
against the directory listing. This also fixes a bug when the locale
was not set the sort order would not match.

makefile: Be more verbose in `check-daemon-makefile`

---

.gitignore
Makefile

Setting the environment variable `COVERAGE=1` allows us to turn coverage measurements on. This produces a number of auxiliary gcno and gcda files which can then be converted into coverage reports. `make coverage` then allows us to generate HTML reports.
I know line coverage and branch coverage is not a perfect metric, but it might get us some more visibility into where more tests might be needed.

Add coverage reporting

---

daemon/sphinx.c

The spec says that we use the libsecp256k1 style ECDH, which uses the
full compressed pubkey from the scalar multiplication which is then
hashed. This is in contrast to the btcsuite implementation which was
only using the hashed X-coordinate.

sphinx: Actually use the full pubkey in ECDH key generation

---

Makefile
contrib/pylightning/lightning/__init__.py
contrib/pylightning/lightning/lightning.py
contrib/pylightning/setup.py
daemon/log.c
tests/requirements.txt
tests/test_lightningd.py
tests/utils.py

This implements the python RPC framework in contrib, and uses it to build end-to-end integration tests that can spin up `lightningd` instances on the fly and run several scenarios. The scenarios are isolated so hopefully we get more relevant feedback of what is broken. We do collect valgrind information but we don't yet fail a test if valgrind reports an error.
This also includes flushing stdout on logs since we tail the subprocess to check actions instead of polling `getlog` all the time. It relies on `python-bitcoinrpc` for the communication with `bitcoind` so a `pip3 install -r tests/requirements.txt` is needed.

Python integration testing framework

---

contrib/pylightning/lightning/__init__.py
contrib/pylightning/lightning/lightning.py
daemon/log.c
tests/requirements.txt
tests/test_lightningd.py
tests/utils.py

Since we are splitting the monolithic daemon into smaller subdaemons we also need to test them both. This includes support for the new daemon, refactors some of the common things and adds the flushing to the new daemon as well.

pytest: Add support for both legacy and new daemons

---

daemon/chaintopology.c
daemon/irc_announce.c
daemon/p2p_announce.c
daemon/peer.c
daemon/timeout.c
daemon/timeout.h
lightningd/gossip/Makefile
lightningd/gossip/gossip.c

Added timer support to the gossip daemon, after refactoring the timers to use `struct timers` instead of the indirection through the `lightningd_state`.

Refactoring timers and adding them to gossip

---

daemon/peer.c

This seems rather easy to fix, the only case we do not want to set
`STATE_SHUTDOWN` us when we have updates which we have not committed
yet, which is handled separately in the other IF-branch.
Close #82

bugfix: Assert was killing daemon

---

daemon/pay.c
doc/lightning-getroute.7.txt

Two arguments were flipped and riskfactor was missing in the error
message returned from the JSON.

doc: Fixed two small mistakes in the `getroute` documentation

---

lightningd/Makefile
lightningd/channel/channel.c
lightningd/channel/channel_wire.csv
lightningd/connection.c
lightningd/connection.h
lightningd/gossip/gossip.c
lightningd/gossip_control.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/msg_queue.c
lightningd/msg_queue.h
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/subd.c

This is a complete rewrite of #124. We no longer bounce messages through `lightningd` instead passing over one socket endpoint to the owner, which can then communicate directly with `gossipd`.
The socket endpoint is passed back to `lightningd` immediately after `gossipd` finishes its initialization, and should `gossipd` not be the owner of the peer, it'll simply send the serialized gossip messages through its endpoint to the current owner.
The forwarding is currently implemented only in `channeld` since that is the daemon the peer is spending most time in, and since the other daemons are unlikely to actually do any forwarding.
~~There are two open improvements that I'd like to tackle outside of this PR:~~
- ~~`gossipd` does not yet use the `daemon_conn` abstraction~~
- ~~There is some …

Added handling of gossip messages either directly or through a separate owning daemon

---

lightningd/channel/channel.c
lightningd/channel/channel_wire.csv
lightningd/peer_control.c

If we complete the setup of a new channel announce it to `gossipd` and the peer we are connected to. Also create the first `channel_update` so that the channel becomes usable.
It still uses zeroed signatures and some dummy default data in the channel update, I'll fix those as soon as we have the `getroute` call out of the way.

Announce newly created channel upon `funding_locked`

---

lightningd/Makefile
lightningd/channel/channel_wire.csv
lightningd/gossip/gossip.c
lightningd/gossip/gossip_wire.csv
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h
lightningd/handshake/handshake_wire.csv
lightningd/hsm/hsm_wire.csv
lightningd/opening/opening_wire.csv
lightningd/utxo.c
lightningd/utxo.h
tools/generate-wire.py
wire/fromwire.c
wire/towire.c
wire/wire.h

Some much-needed rework of generate-wire.py make it easier to have generate-wire do all the marshaling for getnodes.
To be fair, we could have applied the last patch with the following csv, but it's a hack:
gossip_getnodes_reply,0,num_nodes,2,u16
gossip_getnodes_reply,2,nodes,num_nodes*100,struct gossip_getnodes_entry
Now we just do this:
gossip_getnodes_reply,0,num_nodes,u16
gossip_getnodes_reply,2,nodes,num_nodes*struct gossip_getnodes_entry

PR #130 refinements

---

lightningd/Makefile
lightningd/gossip/gossip.c
lightningd/gossip/gossip_wire.csv
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h

This is the first of the `gossipd` JSON-RPC calls. The PR adds a new `gossip_getnodes_entry` struct which can be serialized and deserialized from a byte stream. The reply itself is just a variable length byte stream containing the serialized structs.

Implement `getnodes` in the multi-daemon architecture

---

contrib/pylightning/lightning/lightning.py
lightningd/gossip_msg.c
lightningd/gossip_msg.h
tests/test_lightningd.py
tests/utils.py
tools/generate-wire.py

Some of the struct array helpers need to allocate data when
deserializing their fields. The `getnodes` reply is one such example
that allocates the hostname. Since the change to calling array helpers
the getnodes call was broken because it was attempting to allocate off
of the entry, which did not have a tal header, thus failing.

wiregen: Passing ctx to array helpers that require it

---

daemon/pay.c
daemon/routing.c
daemon/routing.h
lightningd/channel/channel.c
lightningd/gossip/gossip.c
lightningd/gossip/gossip_wire.csv
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h

This PR implements the `getroute` JSON-RPC call in the multi-daemon architecture. It refactors part of the routing algorithm to split the route generation from the JSON-handling in `pay.c` and it uses the `route_hop` struct to communicate the route across the wire.
This is a work-in-progress PR, and it depends on #130 (which covers the first few commits). There is a bug that causes the connection to the peer being killed, possibly when `getroute` is called before the announcements settle:
```
lightningd_channel(27778): FAILURE WIRE_CHANNEL_PEER_READ_FAILED: peer connection broken: Connection reset by peer
```
I think we have some wires crossed, possibly freeing the peer somewhere, but I didn't find it yet.

Implemented `getroute` JSON-RPC call in new daemon

---

lightningd/gossip/gossip.c
lightningd/gossip/gossip_wire.csv
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h

Same structure as the previous JSON-RPC requests. Since the request is empty for now, we don't even bother to parse it, but we might change that in the future, once we implement the paging of large results.

jsonrpc: Implemented `getchannels` JSON-RPC call

---

daemon/routing.c
daemon/routing.h
lightningd/channel/channel.c

The direction bit was computed in several spots and was inconsistent
in some cases. Now we compute it just in routing, and once when
starting up `channeld`, this avoids recomputing it all over the place.

gossip: Consolidated direction bit computation

---

daemon/routing.c
lightningd/Makefile
lightningd/channel/channel.c
lightningd/hsm/hsm.c
lightningd/hsm/hsm_client_wire_csv
lightningd/hsm/hsm_wire.csv
lightningd/hsm_control.c
lightningd/peer_control.c
tests/test_lightningd.py

We first pass a client socket to `channeld` so we they can communicate, and `channeld` can ask for signatures. Then we rewire the sending logic for `channel_announcement`s and `channel_update`s in order to handle the new async behavior needed to get the signatures. Finally we validate the signatures in `gossipd` and ignore them if validation fails.

Use HSM to compute signatures for channel_announcement and channel_update messages

---

daemon/cryptopkt.c

The callback on `key_negotiate` was closing the connection under
certain circumstances and would also `free` the key_negotiate, which
would then be freed again once it returns. We steal it off of the
connection during the callback and doing the free manually afterwards
to make sure this can't happen.
Thanks to @jgriffiths for tracking this one down.
Fixes #142
Reported-By: @bjd and @bgorlick

Fix a double-free bug in the negotiation phase

---

contrib/pylightning/lightning/lightning.py
tests/test_lightningd.py

Instead of having to define every single method we can now just call
any method, it'll fail upstream if it does not exist.

pytest: Added dynamic RPC call dispatch

---

Makefile
lightningd/Makefile
lightningd/sphinx.c
lightningd/sphinx.h
test/test_sphinx.c

This is the implementation of the encryption and decryption functionality for onion routed replies. It conforms with BOLT 04 at version lightningnetwork/lightning-rfc@4a2146b1edf6e5bbbd499c689b9df21d55a0c4ec. It does not yet include the integration with the new daemon since that is likely to clash with Rusty's HTLC forwarding patch.
It also creates a copy of the sphinx implementation in order to avoid having to maintain backward compatibility with the old daemon.

Sphinx reply encryption and decryption functionality

---

lightningd/gossip/gossip.c
lightningd/gossip/gossip_wire.csv
lightningd/gossip_control.c
lightningd/lightningd.c
lightningd/lightningd.h
tests/test_lightningd.py
tests/utils.py

Adds the `--dev-broadcast-interval` flag so we can finally add tests for this as well, and not have to manually add channels. This is don with a new `gossip_init` message that is just sent after the daemon is spun up, but before we actually pass any peers in.
This also fixes two annoying bugs where we were waiting on the wrong object for wakeups for peers that are no longer directly attached to `gossipd` and the `broadcast_index` on the peer being uninitialized, both of which would result in the broadcast being stopped.
It throws in a new integration test for good measure.

Make gossip broadcast interval configurable and fix two bugs

---

INSTALL.md

Fixed the Ubuntu install instructions -- previously it will break on being unable to find pip3. 
Tested this on Ubuntu 16.04 and 17+ server.

Update INSTALL.md to fix broken pip3 install

---

lightningd/sphinx.c
test/test_sphinx.c

Switches from truncated 20 byte HMACs to untruncated 32 byte HMACs as per lightningnetwork/lightning-rfc#158.

sphinx: Update the HMAC in onionreply to full length

---

lightningd/channel/channel.c
lightningd/channel/channel_wire.csv
lightningd/dev_newhtlc.c
lightningd/htlc_end.h
lightningd/pay.c
lightningd/peer_control.c
lightningd/sphinx.c
lightningd/sphinx.h
test/test_sphinx.c

This wires in the onion reply, by creating the message on failure origin, incrementally wrapping it in more encryption layers at each hops, and then unwrapping it at the recipient, i.e., the HTLC origin. Wrapping and unwrapping happens on the master daemon, and we store shared secrets in the `htlc_end` struct for easier access.
We could recompute the secrets on the final recipient since it has the pubkeys and the sessionkey, but we'd still need to keep track of those, so we just keep the secrets around. This also still uses the 20 byte HMACs matching the test vectors (see lightningnetwork/lightning-rfc#158 for details), not the corrected ones from lightningnetwork/lightning-rfc#158, but it'll be a 2 line fix once that has been merged.
Depends on #156, only the last 3 commits are actually …

Sphinx reply integration

---

.travis.yml
tests/test_lightningd.py

We had two flaky tests, mainly due to triggering due to things in the log that were either not seen in the logs or triggering too early. I also removed the legacy gossip test that was being skipped anyway, and improved the environment variable handling, including adding passthrough from the travis env when testing in docker. This last change shoudl allow us to turn `valgrind` on/off without having to create a new commit and turn log spewing on/off on demand on the config page (`https://travis-ci.org/<username>/lightning/settings`).

Fixing Travis-CI

---

INSTALL.md
README.md

* Added another faucet in the main `README.md`.
--- Reason being that the original faucet tends to be unresponsive for quite some time.
* Removed the additional dependency within the `INSTALL.md`
--- The `libsqlite3-dev` was mentioned twice for the installation making it a bit redundant.

Minor fixes

---

daemon/irc_announce.c
daemon/json.c
daemon/json.h
daemon/lightningd.h
daemon/options.c
daemon/routing.c
daemon/routing.h
daemon/routingrpc.c
lightningd/channel/channel.c
lightningd/channel/channel_wire.csv
lightningd/gossip/gossip.c
lightningd/gossip/gossip_wire.csv
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h
lightningd/hsm/hsm.c
lightningd/hsm/hsm_wire.csv
lightningd/hsm_control.c
lightningd/peer_control.c
wire/fromwire.c
wire/towire.c
wire/wire.h

Implement node announcements in the gossip protocol. `channeld` notifies the master daemon that it has announced its channel. The master daemon can then proceed to announce the node. This is necessary since peers will not accept node announcements if they do not know a channel for that node.
Placing this in the master daemon in order not to have to pass down all the information to a subdaemon. We could move it down to `gossipd`, however that would also require adding a new connection to the HSM from gossip to get the signatures.
We currently don't have a good way to detect our external IP. We used to use the IRC connection to retrieve it, but I'd like to retire IRC soonish. Speaking of which, I didn't bother to parse `struct ipaddr`s for announcements on IRC, since I think it'll go down …

Routing node announcements

---

tests/test_lightningd.py

Check and print all valgrind errors and fail tests that produce
errors. We abort using an exception since `fail()` is not allowed in
the teardown.

pytest: Fail tests that produce valgrind errors

---

daemon/routing.c
daemon/routing.h
wire/fromwire.c
wire/peer_wire.c
wire/peer_wire.h
wire/test/run-peer-wire.c
wire/towire.c
wire/wire.h

Fixes the `short_channel_id` being serialized as 4 bytes block height,
3 bytes transaction index and 1 byte output number, to use 3+3+2 as
the spec says.
The reordering in the unit test structs is mainly to be able to still
use `eq_upto` for tests.
Fixes #169

fix: Correctly serialize/deserialize short_channel_ids

---

Makefile

@cornwarecjp pointed this one out. Debian jessy cannot currently compile using `make` due to a number of issues. The first one is that it ships with a 4.x gcc version which doesn't default to the `gnu11` standard, fixed by adding `-std=gnu11` to the `CFLAGS`. The other one is that it ships with an older protobuf-c, and we apparently rely on some of the internal enumerations. I don't think we'll fix that since protobufs are only used in the legacy version. I was able to build the new daemon (and dependencies) with the following:
make daemon/lightning-cli lightningd/lightningd lightningd/lightningd_channel lightningd/lightningd_gossip lightningd/lightningd_handshake lightningd/lightningd_hsm lightningd/lightningd_opening
Notice that `daemon/lightningd` (the legacy daemon) is missing. Also …

[WIP] Get new daemon to compile on debian jessie

---

bitcoin/script.c
daemon/peer.c
daemon/sphinx.c
daemon/sphinx.h
lightningd/sphinx.c
lightningd/sphinx.h

Had this cleanup laying around for a while. It removes some duplicate functionality from sphinx, script and peer.

script: Consolidate scripts to use pubkey_to_hash160

---

lightningd/new_connection.c

We support a number of features already, so failing connections
whenever we see an even bit set is not a good idea. This turned out to
kill our connections to eclair.

peer: Check localfeatures and globalfeatures against what we support

---

lightningd/channel/channel.c

This was causing failures on testnet where confirmations are not
immediate.
Reported-by: Fabrice Drouin @sstone

fix: Allow pings while waiting for the channel to lock

---

daemon/routing.c

This happens when we either have no channel open, or didn't announce
the channel. This patch just fails the getroute request. I'll later
add the non-broadcast announcement for local channels that should fix
this for unannounced channels.

gossip: Fix crash of getroute if we don't know any channels

---

lightningd/handshake/handshake.c
lightningd/new_connection.c
wire/peer_wire.h

After quite some back and forth we seem to finally agree on the bit
3 (mask 0x08) to signal optional `initial_routing_sync`.
I extracted the constant into `peer_wire.h` to make it globally accessible.

gossip: Use bit 3 (mask 0x08) to signal initial routing sync

---

bitcoin/chainparams.c
daemon/bitcoind.c

This was causing calls to `bitcoin-cli` to fail on mainnet since it
was interpreting the empty string as the RPC method to call.
Fixes #208

fix: Only add cli_args if we have some defined

---

README.md

Added a small bit of information for the reader to avoid having to search for reasons why the setup doesn't work properly for regtest. Adding `--network=testnet` should make it clear to the reader that in case on regtest, all that needs to be done is change that parameter.

Update README.md for regtest

---

lightningd/lightningd.c
lightningd/lightningd.h
lightningd/peer_control.c
lightningd/peer_control.h
tests/test_lightningd.py
tests/utils.py
wallet/db.c
wallet/wallet.c
wallet/wallet.h
wallet/wallet_tests.c

Ok, this is finally the second half of the channel persistence. It integrates the persistence primitives with the lightningd and re-populates peers/channels.
I also stumbled over a number of small bugs, that got fixed along the way. This is still a bit of a sledhe hammer approach since it simply dumps everything on every update, and loads everything on startup, but it is a start.

Channel persistence strikes back

---

libwally-core/src/pbkdf2.c

The hmac_sha256() function got renamed to hmac_sha256_internal() in
9624a1a10eeec459ea0eaf57593c8bd8b9a16f31, but one obscure occasion
where it was used was missed and therefore it was still used with its
old name.

Fix build: Correct SHA_POST() macro in pbkdf2.c

---

lightningd/peer_htlcs.c
tests/test_lightningd.py
tests/utils.py

I was hoping to defer HTLC updates until we actually store HTLCs, but
we need to flush to DB whenever balances update as well.
Closes #228

lightningd: Fix channel-persistence for channels with commits

---

onchaind/onchain.c
wallet/wallet.c

This was causing some compilation trouble on 32bit systems, see #256.

WIP: fix: Do not assume size_t == u64

---

.travis.yml
lightningd/test/run-commit_tx.c

This came up a few times, so I decided to use travis to build `lightningd` in a 32bit docker image, just like we already do for the other builds. I decided against adding a valgrind version since it's extremely slow and potentially delays the CI results.

Added 32bit configuration for travis and fix a minor size_t == u64 assumption

---

channeld/channel.c
lightningd/peer_control.c
tests/test_lightningd.py
wallet/wallet.c
wallet/wallet.h
wallet/walletrpc.c

We are currently forgetting any change we get from a funding transaction. This PR changes that. It hooks into `hsm_funding_sig`, i.e., the place we use to broadcast the funding transaction, to grab our change outputs. While the outputs are not yet confirmed, they can already be used for further funding transactions or withdrawals, and it makes the marking of spent outputs and adding the change at the same time.

Remember change outputs

---

lightningd/jsonrpc.c
lightningd/lightningd.c
lightningd/pay.c
tests/test_lightningd.py
tests/utils.py

This amends the pytest framework with clean shutdowns of `lightningd` during the teardown after tests. It uses a three step approach: issue a JSON-RPC stop, wait for it to terminate for 10 seconds, if still running, issue a signal, wait for it to terminate for 10 seconds and if it is still alive, then be more persuasive a.k.a. kill it. This allows us to get rid of the wait loop for crashes since crashes can write their log during the timeouts. And we also get an indication whether we exited cleanly or not (non-zero return codes raise exceptions).
It took a bit longer to implement because it exposed a number of use-after-free bugs during the shutdown (and there may be more that may pop up later). These are all due to the coarse-grained lifetimes we give some of the allocations, i.e., …

pytest: Cleanly shut down lightningd after tests

---

channeld/channel_wire.csv
gossipd/gossip_wire.csv
handshaked/handshake_wire.csv
hsmd/hsm_client_wire_csv
hsmd/hsm_wire.csv
lightningd/peer_control.c
openingd/opening_wire.csv
tools/generate-wire.py
wire/Makefile
wire/wire_io.c
wire/wire_io.h
wire/wire_sync.c

TODO: include stress test that triggered it.

Larger internal messages

---

tests/utils.py

This broke somewhere in the recent changes, because we override
TailalbleProc stop().  Break out log extractor.

utils: save log file on failure.

---

lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
lightningd/peer_control.c

Especially when testing we might want to disable the automatic
reconnection logic in order not to masquerade bugs that disappear when
reconnecting.

Add --no-reconnect flag

---

common/htlc_state.h
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/invoice.c
lightningd/invoice.h
lightningd/lightningd.c
lightningd/peer_htlcs.c
lightningd/test/run-find_my_path.c
tests/test_lightningd.py
tests/utils.py
wallet/Makefile
wallet/db.c
wallet/db.h
wallet/wallet.c
wallet/wallet.h
wallet/wallet_tests.c

We now store HTLCs and invoices in the database. This allows us to recover the full channel state after a restart, including in-flight HTLCs. The patches should be pretty self-explanatory.
The following things are not addressed in this PR, but I thought it'd be good to sync up:
- If we restart a node that initiated the transfer it'll not be able to notify the JSON-RPC call and will likely segfault, will fix in another PR by persisting transfers we initiated so we can notify that record at least (see #302 for progress)
Furthermore I'll move more of the in-memory state to just load from DB on demand in future PRs.

HTLC and invoice persistence 

---

lightningd/lightningd.c
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/peer_htlcs.c
wallet/wallet.c
wallet/wallet.h

We'd like to not keep them in memory and retrieve them on-demand when
`onchaind` is launched. This uses the `channel_htlcs` table as backing
but only fetches the minimal necessary information.

peer: Do not keep the htlc_stubs in memory

---

Makefile
ccan/README
ccan/ccan/io/backend.h
ccan/ccan/io/io.c
ccan/ccan/io/io.h
ccan/ccan/io/poll.c
ccan/ccan/io/test/run-43-io_plan_in_started.c
ccan/ccan/io/test/run-44-io_plan_out_started.c
channeld/channel.c
common/cryptomsg.c
common/cryptomsg.h
gossipd/gossip.c
lightningd/hsm_control.c
lightningd/peer_control.c

A take() leak lead me to notice we had a crypto desynchronization: this fixes it.  We still have one in channeld (it will appear in closingd), but it will just cause a spurious reconnect, so I merely added a FIXME.

Fix gossip release

---

.travis.yml
contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386

Updates the docker CI builder images to use `bitcoind` v0.15.1 in order to fix #332. In addition it pipes `docker pull` through `tee` so we can see which images where used for the build, and collapses the build information in the Travis UI if building succeeds.
Closes #332

Update docker images for CI builds

---

wallet/db.c
wallet/db.h
wallet/wallet.c
wallet/wallet_tests.c

Thou shalt not build SQL queries as string, nor shalt you hex encode all binary fields because that's the only way to add them to string based queries...
This took way longer than expected because rebases kept introducing crashes and the slow Travis didn't help either.

Use native sqlite3 binding for queries and don't hex encode binary fields

---

README.md

Currently the only docker image that builds c-lightning master is cdecker/lightningd:latest.
Also, `lightning-cli sendpay` failed in my bash without quotes around `$route`.

Fix docker tag in README

---

contrib/pylightning/lightning/lightning.py

- connect_rpc() doesn't seem to exist anymore
- added description to l5.invoice()
- route needed 'route' key

Fix python-api example

---

lightningd/bitcoind.c
lightningd/bitcoind.h
lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/lightningd.c
lightningd/peer_control.c
lightningd/peer_htlcs.c
lightningd/subd.c
lightningd/subd.h
lightningd/test/run-find_my_path.c
wallet/db.c
wallet/db.h
wallet/db_tests.c
wallet/wallet.c
wallet/wallet.h
wallet/wallet_tests.c

This starts with the first patch on #307 then goes a different direction.  By the end:
1. All database failures are fatal().
2. Every database operation is inside a transaction.
3. No transactions are nested.
There are only five entry points, so we place transactions there:
1.  Setup.
2.  subd message receipt.
3.  json commands.
4.  timers.
5.  bitcoind results.

Radical database simplification: everything in transactions

---

Makefile
contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386
tests/test_lightningd.py

The py.test unit test runner offers a number of more advanced features
than simply running using unittest.main. In particular it allows us to
capture a tests output and print it if it fails. This change checks
whether we have pytest available and if yes, enables verbose tests and
runs using pytest. This'll give the usual experience (with colors!)
and show us the stdout if a test fails making travis a lot easier to
handle.

Switch to use the py.test test runner

---

lightningd/peer_htlcs.c
tests/test_lightningd.py

We were announcing that we are willing to accept incoming payments
with current_height + min_final_cltv_expiry + slack, assuming that the
sender adds some slack. In particular we'd reject the payment if
slack=0 which is allowed by the spec.
~Removing the slack when sending the payment is optional, but I'd like to keep the slack minimal until we actually implement shadow routes.~

htlc: Accept incoming htlcs with exactly the min_final_cltv_expiry delta

---

lightningd/invoice.c
tests/test_lightningd.py

There were two bugs: we weren't returning the next from the given
label but the one matching the label, and we were appending new
invoices to the head instead of the tail, which meant we'd be
traversing in the wrong order.
Fixes #350

invoice: Fix two bugs in waitinvoice

---

channeld/channel.c
tests/test_lightningd.py

While we correctly disable channels when our peer disconnect we were lacking the re-enable update. This just adds those 3 lines of code.
Closes #303

Re-enable channels upon reconnect

---

lightningd/invoice.c
lightningd/lightningd.c
lightningd/pay.c
wallet/db.c
wallet/wallet.c
wallet/wallet.h
wallet/wallet_tests.c

This implements the persistence of payments to the database as per #302. It serves the dual purpose of having some indication whether a payment failed or succeeded when restarting while sending, and it serves as backing for an eventual wallet listing the payment history.
Both incoming and outgoing payments are stored in the same table for ease of use. I had the `payment_key` duplicated in there as well, but thought keeping it in the HTLCs would suffice for now, therefore I removed it again.
When restarting the destructor of the HTLC will mark the payment as failed for now, which I think should be ok for now, but it may flip the payment from `failed` -> `completed` on reconnect and success, which may seem strange for now.
In addition this introduces a performance regression somewhere, …

Store pending and completed payments in DB

---

lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/pay.c
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h
tests/benchmark.py
tests/test_lightningd.py

This addresses a performance regression introduced by
6ceb375650af30682027cdc22e6d029b4382f423. We were storing it in an
otherwise empty DB transaction, which means that DB transaction was no
longer a no-op. Now we defer storing until we need to store the
corresponding HTLC anyway, so we can just piggyback on top of that
transaction.
This is also more consistent since we'd be forgetting the payment
anyway if we restart between adding the HTLC and committing to it.
The first commit also adds the benchmarks I've been using to find the regression.

htlc: Defer saving the outgoing payment until we store the HTLC

---

Makefile
bitcoin/Makefile
channeld/Makefile
closingd/Makefile
common/Makefile
external/Makefile
gossipd/Makefile
hsmd/Makefile
lightningd/Makefile
onchaind/Makefile
openingd/Makefile

I checked this with git status --ignored after a full build and 'make distclean'.

Makefile: clean needs to do more, distclean should remove everything.

---

wallet/wallet.c
wallet/wallet_tests.c

We weren't incrementing the `col` for the `local_shutdown_idx` field,
which meant that all following fields were incorrect. I removed the
`col` computation and opted for absolute indices instead, since they
are way less brittle. Just remember to add new fields to the query at
the end so we don't have to shift too often :-)
Fixes #377 
Reported-by: William Casarin @jb55

wallet: Fix a column mismatch and use absolute column indices

---

tests/benchmark.py
tests/test_lightningd.py
tests/utils.py

I noticed some breakage with git master:
1. getinfo no longer supported (for us, use getblockchaininfo)
2. generate no longer supported (use generatetoaddress)
Both these options are supported at least in 0.15, too.

tests: prepare for bitcoind 0.16.

---

hsmd/hsm.c
lightningd/Makefile
lightningd/bitcoind.c
lightningd/chaintopology.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/test/run-find_my_path.c
lightningd/txfilter.c
lightningd/txfilter.h
tests/test_lightningd.py
tests/utils.py
wallet/wallet.h
wallet/walletrpc.c

This fixes #219 by passing the transactions in incoming blocks to the wallet which then extracts its funds and records them in the database. It also records the transaction as being interesting so we keep them around to maybe check their confirmations later.

Scan incoming blocks for our transactions

---

channeld/channel.c

As per the spec fix: lightningnetwork/lightning-rfc#287
Reported-by: Pierre-Marie Padiou

channeld: channel_update must use peer's htlc_minimum_msat.

---

channeld/Makefile
channeld/channel.c
channeld/channel_wire.csv
channeld/channeld_htlc.h
channeld/full_channel.c
channeld/full_channel.h
channeld/test/run-full_channel.c
gossipd/gossip.c
gossipd/gossip_wire.csv
lightningd/gossip_control.c
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/pay.c
lightningd/peer_htlcs.c
tests/benchmark.py
tests/test_lightningd.py
tests/utils.py
wallet/wallet.c
wire/gen_peer_wire_csv

Kind of went the long way around: channeld needs to ask gossipd for update_channel, and that's our first request-response.  The best way to treat this is to make channeld do gossipd comms sync (like it does for master comms); cleanest way to do that is to remove ccan/io, which also fixes another potential bug.

Updates with messages

---

lightningd/peer_control.c

Remove redundant `remote_shutdown_scriptpubkey` assignment.

Remove redundant remote_shutdown_scriptpubkey assignment

---

wallet/walletrpc.c

`bitcoin_from_base58` returns a `testnet` flag, but `json_withdraw`
did not actually check it. Add a basic check that the given
withdraw address belongs to the same net `lightningd` is using.

Make json_withdraw check testnet flag.

---

channeld/full_channel.c

Avoid `NULL` pointer dereference when `new_initial_channel(...)` fails.

Avoid NULL pointer dereference when new_initial_channel(...) fails

---

bitcoin/script.c

Note that `bitcoin_witness_p2sh_p2wpkh` is not actually used in current
code.

Share similar code between bitcoin_witness_p2sh_p2wpkh and bitcoin_scriptsig_p2sh_p2wpkh.

---

wallet/wallet_tests.c

Avoid `NULL` pointer dereference in `channelseq(...)`.

Avoid NULL pointer dereference in channelseq(...)

---

.travis.yml
contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386
gossipd/handshake.c
wallet/wallet.h
wire/test/run-peer-wire.c

Clang doesn't like static inlines that are unused, so removing these fixes the clang build.

Remove static inline to fix the clang build and added clang travis build

---

README.md

Fixes: #439 
("fixes" in the sense that the issue requests a feature we already seem to have, and the likely reason, why the feature is requested is because the feature doc, while already documented in the meager documentation we have, is not linked to from the README.md file)

README.md: Add link to waitanyinvoice

---

channeld/Makefile
channeld/channel.c
lightningd/pay.c
tests/test_lightningd.py
wire/gen_onion_wire_csv

Also make logs more effective by printing error when we get one in channeld.

Don't think payment in progress if it fails locally.

---

channeld/channel.c
gossipd/gossip.c
gossipd/gossip_wire.csv
lightningd/gossip_control.c
tests/test_lightningd.py

This is an alternative to #414. The main difference is that instead of having unsigned `channel_announcement` and `channel_update` messages that are allowed through if they are local, we add a new message that `channeld` can send to `gossipd` when both sides lock. This message now contains only the necessary information for the outgoing direction, and will immediately activate the channel so we can use it.
Fixes #284 
Depends on #413 (only the last 4 commits are for this PR, all others are from #413)

Let channeld add the outgoing channel as soon as funding locked on both sides

---

gossipd/routing.c
gossipd/routing.h

I made it static in one PR (745c7b223a2dc5da0f115acd21a86b0b15b0d8e5),
Christian used it in another.

routing: re-expose half_add_connection.

---

channeld/channel.c
gossipd/broadcast.c
gossipd/broadcast.h
gossipd/routing.c
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/peer_htlcs.c

I noted a spurious failure on test_reconnect_sender_add1: we
actually sent an update_commit, which should have been suppressed.
Additionally, we have a gossip reorder issue, which I've fixed in the simplest way I can.
Finally, a destructor was printing out an uninitialized field in some cases.

Fix three causes of test fails.

---

common/status.h
gossipd/broadcast.c
gossipd/broadcast.h
gossipd/routing.c
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c

The error is caused by us incorrectly tracking the announcement state of a channel, and concluding that all channel_announcement were new announcements if the channel had already been added via side-loading, e.g., adding a local channel. It was flaky because only `valgrind` would give us enough time to actually observe this incorrect ordering.
I decided against the belt-and-suspenders solution of keeping in-place replacements and doing the check here, because the in-place replacement added more complexity and wasn't used at all anymore, hence the revert in the first commit. The eviction check when adding a new channel_announcement will make sure we don't accidentally replace an existing announcement so we'll catch this earlier in future.

Fix the channel announcement and update order error

---

tests/test_lightningd.py
tests/utils.py

With the upgrade to python-bitcoinlib==0.9.0 we seemingly lost the ability to specify the auth params in the service URL, so this just rips the service URL out and passes in the bitcoind config file. The RPC lib then goes and parses it. Rather annoying that it won't merge the two or allow specifying the RPC auth params in the constructor though.
Also temporarily disables test_reconnect_normal, which has been flaky lately. That status is tracked in #468 
Fixes #469

Use the bitcoind config file to discover auth params in pytest

---

bitcoin/block.c

lightningd(12615): Adding block UNKNOWN TYPE bitcoin_blkid

bitcoin: add formatting hook for printing bitcoin blockids

---

common/sphinx.c

Avoid writing uninitialized value `data->realm` in `serialize_hop_data(...)` (via `create_onionpacket(...)`).

Avoid writing uninitialized value data->realm in serialize_hop_data(...) (via create_onionpacket(...))

---

gossipd/test/run-initiator-success.c
gossipd/test/run-responder-success.c

Avoid passing uninitialized value `dummy` with uninitialized field `addrlen` to `{initiator,responder}_handshake_`.

Avoid passing uninitialized value dummy with uninitialized field addrlen to {initiator,responder}_handshake_

---

lightningd/invoice.c
tests/test_lightningd.py
wallet/db.c
wallet/wallet.c
wallet/wallet.h

Fixes: #442 
Eventually, anyway.  At this point, only a (failing) test is in this pull request.
The issue is the below:
1.  Make invoices A and B, in that order (make invoice A first, before making invoice B)
2.  Pay invoice B.
3.  Wait any invoice (no argument) -> return B (correct)
4.  Pay invoice A.
4.  Wait any invoice (argument: B) -> expect return A immediately, but blocks instead
Note that the documentation of `waitanyinvoice` indicates that it traverses in order of payment.  However currently the actual implementation traverses in order of invoice creation.  This is not reliable as it is external actors who will pay, and they may take random amounts of time to actually perform the payment.

Implement correct ordering of waitanyinvoice

---

lightningd/invoice.c
lightningd/invoice.h
tests/test_lightningd.py
wallet/wallet.c

Fixes: #444 
Eventually, anyway.  As of this time, this pull request only includes a failing test.  When completed it will include the solution also.
The issue is the below:
1.  Make invoice A and B.
2.  Wait invoice A, should block
3. Pay B -> the "Wait invoice A" returns at this point (it should not)
4.  Pay A -> the "Wait invoice A" should return at this point (not earlier)

Correctly implement waitinvoice

---

common/json.c

Add missing call to `va_end()`.
Each invocation of `va_start()` must be matched by a corresponding invocation of `va_end()` in the same function.

Add missing call to va_end()

---

gossipd/routing.c

As reported here: https://github.com/ElementsProject/lightning/commit/0db821e2cf3b61690cdf898093a7daa139a43607#diff-74b07f2f7fca9b628a3528312b240dd3R444

gossip: Fix a typo in the add_channel_direction logic

---

lightningd/test/run-commit_tx.c

Avoid out-of-bounds read in `increase(u32 feerate_per_kw)`.

Avoid out-of-bounds read in increase(u32 feerate_per_kw)

---

lightningd/peer_control.c
lightningd/peer_control.h
lightningd/peer_htlcs.c
lightningd/subd.c

Turns out everyone wanted a formatted string anyway.
Inspired-by: @practicalswift

lightningd: simplify permenant failure.

---

Makefile

Append contrib/pylightning instead of overriding PYTHONPATH for tests.
On my system (NixOS), libraries are loaded via PYTHONPATH when I launch a nix-shell with the libraries I need (kind of like a generalized virtualenv), instead of system paths.

make: append contrib/pylightning to PYTHONPATH

---

tests/utils.py

Use deterministic command-line ordering when executing `lightningd` from tests.
Iteration order of `dict`:s is non-deterministic in Python3. This results in randomized ordering of command-line options passed to `lightningd` between test runs which makes the options list harder to read :-)
```
valgrind -q --trace-children=yes --trace-children-skip=*bitcoin-cli* --error-exitcode=7 --log-file=/tmp/lightning-…/test_channel_persistence/lightning-2//valgrind-errors.%p lightningd/lightningd --bitcoin-datadir=/tmp/bitcoind-test --lightning-dir=/tmp/lightning-…/test_channel_persistence/lightning-2/ --port=16332 --override-fee-rates=15000/7500/1000 --network=regtest --dev-broadcast-interval=1000 --dev-hsm-seed=… 
--cltv-final=5 --locktime-blocks=5 --log-level=debug …
```

Use deterministic command-line ordering when executing lightningd from tests

---

wire/test/run-peer-wire.c

`memcmp((p1)->field, (p2)->field, ...)` results in undefined behaviour if `(p1)->field`, `(p2)->field` or both are `NULL`.
This holds also when the number of bytes to compare (`tal_count((p1)->field) * sizeof(*(p1)->field)`) is zero.

Avoid undefined behaviour in eq_var(p1, p2, field)

---

lightningd/jsonrpc.c

~Avoid potential unsigned integer overflow in `log_to_json(...)`.~
`assert(tal_count(log) > 0)` (now implicitly assumed) in `log_to_json(...)`.

assert(tal_count(log) > 0) (previously implicitly assumed) in log_to_json(...)

---

README.md

Make `README.md` install instructions consistent with `doc/INSTALL.md`:
* Remove python2 dependency.
* Add net-tools dependency.

Make README.md install instructions consistent with doc/INSTALL.md

---

lightningd/jsonrpc.c

Some nodes are adding padding entries that we faithfully returned as well in our JSON-RPC reply. They're pretty useless, so let's not print them.

gossip: Do not return empty address-objects for getnodes

---

tests/utils.py

Alternative take on #521, this time without registering an `atexit` callback, closing the fd where it is used. Still not perfect since we are opening in one thread and closing in the other, but should work fine. Reproduced the leak before and verified it's gone afterwards.

pytest: Avoid leaking stdout fds

---

bitcoin/tx.c
bitcoin/tx.h
common/htlc_wire.c
common/htlc_wire.h
common/permute_tx.c
common/utxo.c
common/utxo.h
hsmd/Makefile
hsmd/hsm.c
hsmd/hsm_client_wire_csv
lightningd/build_utxos.c
lightningd/peer_control.c
lightningd/test/run-funding_tx.c
lightningd/txfilter.c
lightningd/txfilter.h
onchaind/onchain.c
onchaind/onchain_wire.csv
tests/test_lightningd.py
tools/generate-wire.py
wallet/db.c
wallet/db.h
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h
wallet/walletrpc.c
wire/fromwire.c
wire/towire.c
wire/wire.h

This should get us all the funds that we own back, on unilateral close, cheat and collaborative close. First we make sure to remember all outputs that we are interested in and store them in the DB. Special care needs to be taken for the unilateral_close:to_us output, since it's the only p2wpkh output which we don't use keyindex for. For this case we need to extend the output data to include the peer_id, channel_id and commitment_point.
This also refactors the funding and withdrawal transaction generation to let `hsmd` generate the full TX instead of just the signatures. This de-duplicates and simplifies the creation of these transaction since we no longer need to generate them in two separate parts and ensure that they are identical.
Fixes #385

Remember and spend unilateral close outputs

---

channeld/Makefile
channeld/channel.c
closingd/Makefile
closingd/closing.c
common/Makefile
common/debug.h
common/subdaemon.c
common/subdaemon.h
gossipd/Makefile
gossipd/gossip.c
hsmd/Makefile
hsmd/hsm.c
onchaind/Makefile
onchaind/onchain.c
openingd/Makefile
openingd/opening.c

Our handling of SIGPIPE was incoherent and inconsistent, and we had much
cut & paste between the daemons.  They should *ALL* ignore SIGPIPE, and
much of the rest of the boilerplate can be shared, so should be.
Reported-by: @ZmnSCPxj
Fixes: #528

subdaemon.c: subdaemon_setup() routine for all daemons.

---

common/dev_disconnect.c
lightningd/subd.c

Check `lseek(...)` return value.

Check lseek(...) return value

---

lightningd/chaintopology.c

I've only seen this under travis, so I can't verify that this fixes it, but it's certainly a bug which could cause that issue.

chaintopology: fix use-after-free which sometimes causes fatal() in clear_otx_peer

---

hsmd/hsm.c
lightningd/jsonrpc.c
lightningd/subd.c

Make sure `fsync`, `connect` and `close` are never accidentally passed negative arguments.

Make sure fsync, connect and close are never accidentally passed negative arguments

---

contrib/pylightning/setup.py
tests/test_lightningd.py
tests/utils.py

These are some small improvements. I bumped pylightning 0.0.2 to get rid of the legacy support in the pypi package.
The only major change is that we no longer use a global `bitcoind` instance shared by all tests, instead we spawn a new one for each test in their respective test-directory. This enhances isolation between tests, and should make hacks like generating 100 blocks between tests obsolete. It's also now possible to inspect the final blockchain state in isolation as it is left by the test.
This change comes at a price however, since we need to spawn `bitcoind` and generate 432 blocks to enable segwit. My measurements show that the overhead is about 1-3 seconds per test, so not that massive compared to the rest of the tests:
|                    | No_valgrind   | Valgrind | …

pytest: Minor cleanups and bumping pylightning to 0.0.2

---

.dir-locals.el

This will automatically configure proper indent settings for new contributors using emacs.

emacs: add .dir-locals.el for linux style C

---

test/test_protocol.c

Check return value of `read_all(...)` call in `do_cmd(...)`.
All other users of `read_all(...)` check the return value:
```
hsmd/hsm.c:    if (!read_all(fd, &secretstuff.hsm_secret, sizeof(secretstuff.hsm_secret)))
test/test_protocol.c:    if (!read_all(fd, p, len))
wire/wire_sync.c:    if (!read_all(fd, &len, sizeof(len)))
wire/wire_sync.c:    if (!read_all(fd, msg, wirelen_to_cpu(len)))
```

Check return value of read_all(...) call in do_cmd(...)

---

hsmd/hsm.c

Check return value of `derive_simple_privkey(...)` call in `hsm_unilateral_close_privkey(...)`.
All other users of `derive_simple_privkey(...)` check the return value:
```
channeld/channel.c:     if (!derive_simple_privkey(&peer->our_secrets.htlc_basepoint_secret,
lightningd/test/run-commit_tx.c:        if (!derive_simple_privkey(&x_remote_htlc_basepoint_secret,
lightningd/test/run-commit_tx.c:        if (!derive_simple_privkey(&x_local_delayed_payment_basepoint_secret,
lightningd/test/run-commit_tx.c:        if (!derive_simple_privkey(&x_local_htlc_basepoint_secret,
lightningd/test/run-key_derive.c:       if (!derive_simple_privkey(&base_secret, &base_point,
onchaind/onchain.c:     if (!derive_simple_privkey(&secrets->delayed_payment_basepoint_secret,
onchaind/onchain.c:     if …
```

Check return value of derive_simple_privkey(...) call in hsm_unilateral_close_privkey(...)

---

lightningd/chaintopology.c

Every 30 seconds, these flood the logs.

lightningd: suppress feerate debug messages when nothing changes.

---

lightningd/jsonrpc.c
lightningd/peer_control.c

Check return value of `json_get_params(...)` call in `json_getlog(...)` and `json_getpeers(...)`.
All other users of `json_get_params(...)` check the return value:
```
lightningd/chaintopology.c:     if (!json_get_params(buffer, params,
lightningd/chaintopology.c:     if (!json_get_params(buffer, params,
lightningd/dev_ping.c:  if (!json_get_params(buffer, params,
lightningd/gossip_control.c:    if (!json_get_params(buffer, params,
lightningd/invoice.c:   if (!json_get_params(buffer, params,
lightningd/invoice.c:   if (!json_get_params(buffer, params,
lightningd/invoice.c:   if (!json_get_params(buffer, params,
lightningd/invoice.c:   if (!json_get_params(buffer, params,
lightningd/invoice.c:   if (!json_get_params(buffer, params, "label", &labeltok, NULL)) {
lightningd/invoice.c:   if …
```

Check return value of json_get_params(...) call in json_getlog(...) and json_getpeers(...)

---

lightningd/subd.c

Add assertion for the assumed `tal_count(msg) >= sizeof(be16)` in `subdaemon_malformed_msg(...)`.
An unsigned integer overflow will occur if `tal_count(msg) >= sizeof(be16)` does not hold true.
Explicit is better than implicit :-)

Add assertion for the assumed tal_count(msg) >= sizeof(be16) in subdaemon_malformed_msg(...)

---

lightningd/peer_control.c
tests/test_lightningd.py

Stops some transactions from failing on the other side due to insufficient funds.

peer_control: make hardcoded feerates consistent between json_fund_channel and peer_offer_channel

---

wallet/wallet.c

We were using int32 for msatoshi values for outputs, which would
overflow for values larger than 2^32. Would not have caused money 
to get lost since we create segwit transactions that commit to the value
the wallet believes to be in the output being spent.

wallet: Use int64 when deserializing output value from db

---

lightningd/peer_control.c

Since we now have addresses in the database, we can resend them as hints to gossipd on startup.
Fixes #527

peer_control: send addrhints in activate_peer

---

lightningd/invoice.c
lightningd/pay.c

For `invoice` RPC, use `msatoshi`, since our response uses `msatoshi` anyway, as well as our manfile and online help.  All invoice-related responses use `msatoshi` as field name, not amount.
For `listpayments` RPC, change the online help to use `msatoshi` instead of `amount`, in line with the actual response of `listpayments`.

Change some RPC fields from `amount` to `msatoshi`

---

gossipd/broadcast.c
gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
lightningd/gossip_control.c
lightningd/lightningd.h
lightningd/options.c
tests/test_lightningd.py

Implements the channel pruning recommendation as per BOLT 07. In order to keep the command line options to a minimum it derives a total of 3 intervals out of the `--channel-update-interval` flag:
- `channel_update_interval`: minimum time between sending `channel_update`s
- 2x `channel_update_interval`: maximum age that we keep channels around before pruning them from the local view
- `channel_update_interval`/2: time between pruning runs
By default `channel_update_interval` is set to 1 week, so the maximum age matches the spec.

Implement channel pruning specification

---

lightningd/bitcoind.c

exit status is not enough to detect spent outputs. gettxout will return a
success exit code and 0 bytes.
Almost Fixies #589, but there is still one more place it crashes after this patch

bitcoind: properly handle spent outputs in gettxout

---

lightningd/peer_control.c

Fixes #600 
Message buffer `why` is allocated in the `peer` context and also freed when peer is freed.
Only explicitly free the buffer when peer itself is not freed yet.

Fix double free of message buffer.

---

lightningd/memdump.c

Avoid segfault on CLI command `dev-memleak` when `$LIGHTNINGD_DEV_MEMLEAK` is not set.
```
$ cli/lightning-cli dev-memleak
lightning-cli: Non-object response ''
$ cli/lightning-cli dev-memleak
lightning-cli: Connecting to 'lightning-rpc': Connection refused
```
```
$ cli/lightning-cli dev-memleak
"Leak detection needs $LIGHTNINGD_DEV_MEMLEAK"
$ cli/lightning-cli dev-memleak
"Leak detection needs $LIGHTNINGD_DEV_MEMLEAK"
```

Avoid segfault on CLI command "dev-memleak" when $LIGHTNINGD_DEV_MEMLEAK is not set

---

lightningd/jsonrpc.c

* Use correct description for the `help` CLI command
* Use consistent formatting for CLI command descriptions

Use correct description for the "help" CLI command. 

---

common/permute_tx.c

permute_outputs is sometimes called with empty arguments from initial_commit_tx.
Make sure we guard against that case. We also do the same in permute_inputs for
good measure.

permute_tx: bail on empty permute_{inputs/outputs} arguments

---

lightningd/pay.c

json_get_params does this for us.
Fixes: 78adf0b (pay: allow 'null' msatoshi field.)
Reported-by: ZmnSCPxj

pay: remove gratuitous check for msatoshitok being 'null'.

---

lightningd/bitcoind.c
lightningd/gossip_control.c

Gossipd already correctly handles the "empty output means lookup failed" case.
Reported-by: @jb55 @shesek

lightningd: don't crash when txout lookup fails.

---

common/bolt11.c
tests/test_lightningd.py

Avoid segfault on CLI command `decodepay 1111111` (invalid short bech32 string).
```
$ cli/lightning-cli decodepay 1111111111
"Invalid bolt11: Bad bech32 string"
$ cli/lightning-cli decodepay 111111111
"Invalid bolt11: Bad bech32 string"
$ cli/lightning-cli decodepay 11111111
"Invalid bolt11: Bad bech32 string"
$ cli/lightning-cli decodepay 1111111
lightning-cli: Non-object response ''
$ cli/lightning-cli decodepay 1111111
lightning-cli: Connecting to 'lightning-rpc': Connection refused
```
```
$ cli/lightning-cli decodepay 1111111111
"Invalid bolt11: Bad bech32 string"
$ cli/lightning-cli decodepay 111111111
"Invalid bolt11: Bad bech32 string"
$ cli/lightning-cli decodepay 11111111
"Invalid bolt11: Bad bech32 string"
$ cli/lightning-cli decodepay …
```

Avoid segfault on CLI command "decodepay 1111111" (invalid short bech32 string)

---

lightningd/jsonrpc.c
lightningd/subd.c

Change log level for some commonly printed debug messages from `info` to `debug`.

Change log level for some commonly printed debug messages from "info" to "debug"

---

channeld/channel.c
lightningd/lightningd.h
lightningd/options.c
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/peer_htlcs.c
tests/test_lightningd.py
tests/utils.py

This, of course, should never be used.  But it helps maintain connections
for the moment while we dig deeper into feerates.

channeld: --ignore-fee-limits as a hack for fee disparities.

---

lightningd/invoice.c
lightningd/invoice.h
lightningd/lightningd.c
lightningd/peer_htlcs.c
lightningd/test/run-find_my_path.c
wallet/Makefile
wallet/invoices.c
wallet/invoices.h
wallet/test/Makefile
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

This reorganizes the invoices system so that the wallet provides a set of functions approximately described in the sketch here: https://github.com/ElementsProject/lightning/issues/570#issuecomment-357162858
As a reorganization it touches a significant number of files, sadly.
The advantages are:
1. The rest of the code serves as a client to the invoices system. That client is constrained not to manipulate invoice objects directly (i.e. it only gets `const struct invoice *`). Thus if a need to manipulate invoice objects occurs, we are reminded that we should instead update the invoices system appropriately.
2.  Future changes to how in-memory invoice structures are referred to in-memory can be kept only in the `wallet/invoices.c` file.  In particular, we should use something more efficient …

invoices: Extensive reorganization of invoice system.

---

wallet/walletrpc.c

Fixes #620 
Note that this reverses the 'satoshi' and 'destination' params in the 'withdraw' rpc method to match the online help.
I think this order makes more sense, but it's an API change. Hopefully we're at a stage where that is still OK.

withdraw: Swap 'satoshi' and 'destination' params to match online help.

---

README.md
doc/INSTALL.md

Tiny patch to documentation, adding missing `autoconf` dependency and fixing a dangling paren.

Tidy README Fix, add missing dependency

---

lightningd/invoice.c
lightningd/pay.c
wallet/db.c
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

(On top of #572 )
As noted when reviewing #545 we have redundant information between invoices and payments.  Yet the two uses are very different: a large server will issue many invoices which never get paid, but still won't make many payments.  A wallet may be the other way around.
(Incoming payments were also *inaccurate*, reflecting invoice amounts and not the actual payment).
@ZmnSCPxj also found that the dual-use was strained when "any" valued invoices were added.
These patches removes incoming invoices, for consideration of @cdecker 
Closes: #570

Remove incoming payments

---

lightningd/peer_control.c

Make `fundchannel` return txid too

---

wallet/wallet.c

Avoid potential `NULL` pointer dereference in `wallet_payment_store(...)`.

Avoid potential NULL pointer dereference in wallet_payment_store(...)

---

lightningd/jsonrpc.c

jsonrpc: Add the network name to the getinfo output

---

README.md
wallet/invoices.c

I basically changed one line of code extending the help message from `./lighting-cli --help` to point out that `./lighting-cli help` lists all the available commands
c.f.: https://github.com/ElementsProject/lightning/issues/662

quickfixing issue #662 to make CLI more userfriendly for inexperienced users

---

Makefile
README.md
tools/check-markdown.sh

Sync dependencies between `README.md` and `doc/INSTALL.md` and add a Travis/`check-source` check to make sure these do not get out of sync again :-)
```
$ diff -u <(egrep 'sudo apt-get install .*git' README.md) <(egrep 'sudo apt-get install .*git' doc/INSTALL.md)
--- /dev/fd/63    2018-01-18 17:26:34.330464546 +0100
+++ /dev/fd/62    2018-01-18 17:26:34.330464546 +0100
@@ -1 +1 @@
-sudo apt-get install -y autoconf build-essential git libtool libgmp-dev libsqlite3-dev python python3 net-tools
+sudo apt-get install -y autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python python3 net-tools
$
```
```
$ diff -u <(egrep 'sudo apt-get install .*git' README.md) <(egrep 'sudo apt-get install .*git' doc/INSTALL.md)
$
```

Sync dependencies between README.md and doc/INSTALL.md. Add dependency consistency check.

---

wallet/wallet.c

Fixes: #657
Decided not to add the route information here --- instead save in DB separately.
Needed for #638 to progress, we cannot find the routing failure if `path_secrets` is not accessible inside `payment_failed`.

[0.6] wallet: Properly save `wallet_payment::path_secrets`.

---

channeld/channel.c

Travis gave an error:
```
DEBUG:root:lightningd(16333): lightning_closingd(8004): STATUS_FAIL_PEER_BAD: Expected closing_signed:
0085b679bd79b836b05c649cad9af31156cb1d50de448a59c6359ab7c85f4b63913d2e3bc8ad4a80ab698558e5b4949b78dc36acc90dde4f5ac006fd6ca1d109feea03aef9c718e9ce09bbb52dc8308ba8f46b43808ea1a551d41aee72af7af77628d1
```
Which is caused by us not waiting for the revoke-and-ack from a feechange
when we're shutting down.

channeld: don't consider shutdown complete if feechange pending.

---

common/json.c
contrib/pylightning/lightning/lightning.py
doc/Makefile
doc/lightning-delinvoice.7
doc/lightning-delinvoice.7.txt
doc/lightning-getroute.7
doc/lightning-getroute.7.txt
doc/lightning-listinvoices.7
doc/lightning-listinvoices.7.txt
gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
lightningd/dev_ping.c
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/options.c
lightningd/options.h
lightningd/pay.c
lightningd/peer_control.c
tests/test_lightningd.py
tests/utils.py
wallet/invoices.c
wallet/wallet.c
wallet/wallet.h
wallet/walletrpc.c

(On top of previous payments rework patch, but you can ignore that for review).
If we don't fix up API warts now, we're stuck with them! We can always add new optional fields, but if anyone wants to review the current APIs for consistency, now would be a good time!
1. Make everything listy of form "list<plural>". getpeers->listpeers, getnotes->listnodes, getchannels->listchannels, getinvoice->getinvoices, listinvoice->listinvoices. 
2. Never return an undecorated JSON array.  It's redundant now, but if we want to add new toplevel fields, this will suck.
3. Use "id" instead of "peerid" consistently.
4. Keep listinvoice untouched for now, but deprecated (avoid breaking Lightning Charge).
5. Add --deprecated-apis=false option (defaults true) so you can test futureproofness of your stack.
6. …

Json api cleanup

---

lightningd/options.c

No reason to be gready on mainnet, and people can still adjust this with `--fee-base` :wink: 
Closes #673

options: Dropping default base_fee for mainnet to 1 satoshi

---

lightningd/options.c

Don't greet new users with an error message (`No such file or directory`) for an expected non-failure condition. The important failure case is handled a few lines down after the `chdir(…)` call has been is repeated post-`mkdir(…)`.
```
$ lightningd/lightningd
lightningd(PID): Creating lightningd dir /root/.lightning (because chdir gave No such file or directory)
lightningd(PID): Creating database
```
```
$ lightningd/lightningd
lightningd(PID): Creating lightningd dir /root/.lightning
lightningd(PID): Creating database
```

Don't greet new users with an error message

---

README.md

Changed`Receiving and receiving payments` to `Sending and receiving payments` in the readme.

Fix 'Receiving and receiving payments' in readme

---

lightningd/peer_control.c

Similar format as line 2719 in peer_control.c      
Changing this changes the description in `help`, right?

Added that peer id should be given to dev-sign-last-tx

---

README.md

Fixes a broken link in the README.md file as well as adds a few other links on the README to the RPC docs.

Fixed and updated README RPC doc links

---

cli/lightning-cli.c
doc/lightning-cli.1
doc/lightning-cli.1.txt

Fixes: #685 
Should now allow `lightning-cli pay $BOLT11 null null $RISKFACTOR` to skip over optional `msatoshi` and `description` arguments.

lightning-cli: Add support for null argument.

---

lightningd/chaintopology.c
lightningd/dev_ping.c
lightningd/gossip_control.c
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/memdump.c
lightningd/pay.c
lightningd/peer_control.c
wallet/walletrpc.c

Remove unused `help` field from `struct json_command`.
These texts are not visible for the user and thus redundant.
If we find some of the texts valuable I suggest we re-introduce them in a later PR by doing:
* a.) make them part of the description (which is visible),
* b.) implement `help [command]` which would show the texts, or
* c.) add the texts are comments.

Remove unused help text field from struct json_command. Use consistent wording.

---

common/json.c

Fix for crash issue #726 
Large buffers cause stack overflow.

Allocate hex buffer on heap since it can be very large.

---

Makefile
common/wireaddr.c
doc/INSTALL.md
lightningd/lightningd.c
lightningd/subd.c

- Now builds on FreeBSD 11.1-RELEASE with clang 4.0.0
- Still builds on Ubuntu
- New `#include`s make the codebase more UNIX compatible.
- Now correctly builds and links `ptr_valid`

Build fixes and increased cross-platform compatibility

---

contrib/pylightning/README.md
contrib/pylightning/lightning/lightning.py

Removed the example from the lighting python library code and started a README. I think this is better in terms of organization and allows the README to be extended in future with more elaborate examples.

pylightning: Add and move example to README

---

lightningd/htlc_end.c
lightningd/peer_htlcs.c
tests/test_lightningd.py

This is my preferred fix.
Note that I just discovered assertRaisesRegex which we should be using more widely (since *any* error on RPC raises ValueError).
Closes: #687

Fix zero msatoshi

---

lightningd/peer_control.c
tests/test_lightningd.py
wallet/wallet.c
wallet/wallet.h

This may cause the lingering `onchaind_mutual` channels in #721. Channels didn't get removed from the DB even though they were removed in memory. Alternatively we could mark the channels as resolved by setting their status to something that we ignore when loading.
Dropping the channels cascades to remove all dependent tables, so this suffices to clear everything.

Purge channels from the DB after they have been irrevocably committed

---

lightningd/chaintopology.c

Adjust log level for fee rate warnings.
This condition seems to be triggered quite common on testnet, so no need for warning floods unless we're running in debug mode :-)

Adjust log level for fee rate warnings

---

lightningd/bitcoind.c

Warn instead of crash when `extract_feerate(...)` fails.
Fixes: #722

Warn instead of crash when extract_feerate(...) fails

---

lightningd/peer_control.c

Onboarding: Adjust log level for common non-fatal peer state condition from info to debug.
These messages are commonly seen on testnet.

Onboarding: Adjust log level for common non-fatal peer state condition from info to debug

---

cli/lightning-cli.c
common/configdir.c

Make `lightning-cli` (without arguments) output the equivalent of `lightning-cli --help; lightning-cli help`
New users invoking `lightning-cli` are likely interested in what RPC commands they can invoke via the command.

Onboarding: Make "lightning-cli" (without arguments) output the equivalent of "lightning-cli --help; lightning-cli help"

---

common/json.c
common/json.h
lightningd/jsonrpc.c
lightningd/jsonrpc.h

http://www.jsonrpc.org/specification#error_object
Partly in preparation for #638, where we will modify `sendpay` to report routing failures via the `data` field of error objects. Since we currently do NOT actually use error objects, this PR is required first.

Properly comply with Error Objects of JSON-RPC 2.0

---

channeld/channel.c

Right now it allows ping but not pong. 
If A sends a ping expecting a pong to B during CHANNELD_AWAITING_LOCKIN,
It would result in 
`STATUS_FAIL_PEER_BAD: WIRE_PONG (19) before funding locked`    
resulting in an unilateral channel close by A.

Allow pong when in CHANNELD_AWAITING_LOCKIN

---

lightningd/bitcoind.c

We added code to allow a few spurious failures, but it didn't unmark
the request running.
IRC user 'mlz' provided logs from his stuck-at-old-block lightningd:
lightningd(31981): Adding block 1261159: 00000000da3890ccd0f313a74fccfd4789654b496836da5c28a8d2ad28852264
lightningd(31981): Adding block 1261160: 00000000f70938a33aecbdd7b047cb5cf5b095ea4770c1335acf1859bad1e767
lightningd(31981): bitcoin-cli -testnet estimatesmartfee 2 CONSERVATIVE exited with status 1
Fixes: #749
I wonder if this is also implicated in #803 ...

bitcoind: mark request no longer running, even if it fails.

---

channeld/channel.c
closingd/Makefile
closingd/closing.c
lightningd/log.c
lightningd/peer_control.c
lightningd/subd.c
openingd/opening.c
tests/test_lightningd.py

Common handling style for messages in daemons, plus better per-peer logging.

Better handling unexpected msgs

---

lightningd/peer_control.c
lightningd/watch.c
lightningd/watch.h
onchaind/onchain.c
onchaind/onchain_wire.csv
tests/test_lightningd.py
tests/utils.py
wallet/walletrpc.c

@cdecker reported we were using a heap of mem and falling behind in blocks which onchaind was spamming the logs with "Notified about tx %s output %u spend, but we don't care" messages.
Currently, we follow all txs from the funding tx onwards, in case onchaind is interested in them.  We have a FIXME to do something when onchaind says it's not interested, so this actually fixes that.

Unwatch for onchaind

---

channeld/channel.c

Fixes: #857 
Required for #638 to pass.
@cdecker a test similar to the new test in #638 would probably be a good addition to the Lightning integration test suite.

[0.6] channeld: Properly pad and HMAC onion replies that our masterd generated

---

gossipd/routing.c
lightningd/peer_control.c

This is just a quick fix to reduce the number of lookups, more elaborate optimizations coming soon.
This avoids duplicating lookups while we are already looking up txouts, and it avoids doing a lookup, only to discard it later because we already know about the channel.

Cache txouts and avoid duplicate lookups

---

gossipd/Makefile
gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
lightningd/gossip_control.c
lightningd/pay.c
lightningd/peer_htlcs.c
tests/test_lightningd.py
wallet/db.c
wallet/db.h
wallet/wallet.c
wallet/wallet.h

Fixes: #550 
Eventually.  Remaining:

pay hands back failures to gossipd

---

lightningd/bitcoind.c
lightningd/bitcoind.h
wallet/walletrpc.c

So many channels stuck in channeld_awaiting_lockin, and I don't like
suggesting manually editing the DB, so this adds a very simple way to
sync with bitcoind's UTXO view. `dev` since it is dangerous, then
again if bitcoind says those funds aren't available there's little we
can do anyway.

wallet: Add a simple txo rescan command to sync with bitcoind UTXO

---

tools/check-spelling.sh

The pagination causes it to wait for a keypress even with no output
under emacs (complaining about the terminal); we don't want it anyway.
Example output:
Makefile:228:#lighnting!
Identified a likely misspelling of the word "lightning" (see above). Please fix.
Is this warning incorrect? Please teach tools/check-spelling.sh about the exciting new word.
Makefile:230: recipe for target 'check-spelling' failed

check-spelling: don't paginate, and give file and line.

---

lightningd/log.c
lightningd/log.h
lightningd/peer_control.c

Prefix logging to standard output with [ISO 8601](https://sv.wikipedia.org/wiki/ISO_8601) formatted date and time in UTC.
```
$ lightningd/lightningd
lightningd(PID): Server started with public key …
```
```
$ lightningd/lightningd
2018-01-26T14:38:22.210Z lightningd(PID): Server started with public key …
```

Usability: Prefix logging to stdout with ISO 8601 formatted date and time in UTC

---

lightningd/chaintopology.c
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/pay.c
lightningd/peer_control.c
tests/test_lightningd.py

Capitalized all CLI (JSON) error responses in-line with the rest of the error responses. Some minor textual tweaks for some error responses.

Onboarding: tweak grammar conventions for RPC responses

---

channeld/channel.c
closingd/closing.c
closingd/closing_wire.csv
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/pay.c
lightningd/peer_control.c
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h
tests/test_lightningd.py
wallet/wallet.c

Builds on #841 
This is basically a rewrite of closingd to do negotiation properly.  Doing so revealed a spec bug, so I've created a patch for that too, and assumed it's going to be accepted.  If not, we don't really care; by default we just don't enforce sane negotiation anyway.

Shutdown fixes

---

lightningd/log.c

Mark last parameter of `log_to_stdout(...)` as intentionally unused.

Mark last parameter of log_to_stdout(...) as intentionally unused

---

gossipd/routing.c

Obvious spec noncompliance is obvious

routing: Correct the sense of "PERM bit is NOT set"

---

lightningd/jsonrpc.c
tests/test_lightningd.py

jsonrpc: Let failing of `cmd` free `names`

---

lightningd/pay.c

Fixes: #893 
In principle we gossipd should not route over channels we know are not simply going to work.  Until then, we can mitigate by reporting it as a route failure.
(we need to report it as a route failure anyway since race conditions may invalidate routing assumptions between the time we get the route and the time we actually start attempting to send the payment: i.e. (1) get route, see channel is OK now (2) return route using a currently-OK channel (3) channel gets problem (peer disconnect, big HTLC passes through) (4) send payment on now NG channel.

Report immediate fail of `send_htlc_out`

---

gossipd/routing.c
gossipd/routing.h

Fixes: #867 
Policy: disable failing channels for 20 seconds, or the next `channel_update`.
Implementation: Use a `u64 unroutable_until`, a UNIX-time variable, which prevents a channel from being used for routing if less than the current time in UNIX epoch.  Set this to 20+current time if routing failure reported.  Set to 0 on construction or `channel_update`.

Make gossipd more forgiving of temporary routing failures

---

lightningd/pay.c

Follow-up to #894; also report immediate routing failure if peer nonexistent.

pay: Also treat nonexistent peer as immediate routing failure.

---

cli/lightning-cli.c
common/json.c

jsmn_parse was returning 0 (it's supposed to return the number of tokens used), which made lightning-cli hang.  After some debugging, turns out this was fixed upstream:
edd751896de5de1fcee95cb65949e6784c726751
Author: Serge A. Zaitsev <zaitsev.serge@gmail.com>
Date:   Sat Oct 17 14:58:47 2015 +0200
fixed return value on incremental parting

Update jsmn: fix case where lightning-cli would hang

---

README.md
doc/INSTALL.md

As of recently I started to see:
```
/usr/bin/ld: cannot find -lsodium
collect2: error: ld returned 1 exit status
Makefile:271: recipe for target 'ccan/ccan/cdump/tools/cdump-enumstr' failed
make: *** [ccan/ccan/cdump/tools/cdump-enumstr] Error 1
```

[doc] install: add libsodium-dev

---

lightningd/peer_control.c

In `json_listpeers` there is no parameter named 'log'.

Fix listpeers JSON command description

---

bitcoin/short_channel_id.c
bitcoin/short_channel_id.h
gossipd/broadcast.c
gossipd/broadcast.h
gossipd/gossip.c
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
tests/test_lightningd.py

Replaces the list-based lookup of `node_connection`s with a channels `uintmap` that is indexed by the channel's `short_channel_id`. Node announcements are now also stored in a separate `pending_node_announcement_map` until the `txout` verification completes. Tracking `node_connection` and `node` state independently makes the logic easier.
We also reduce verbosity of `gossipd`, only replace updates with newer ones if the `txout` verification is pending, and remember pending `node_announcement`s that arrive while we are still verifying the `txout` (these were dropped before).

gossipd performance improvements

---

lightningd/log.c

libunwind does not accept a NULL parameter for the error callback. It will simply call into the NULL pointer. So add an error callback.
This makes the crash output somewhat more sensible on FreeBSD, where there is no libunwind stack trace available:
2018-02-05T20:24:50.598Z lightningd(75556): error getting backtrace: no stack trace because unwind library not available (0)

lightningd: Don't crash when libunwind backtrace not available

---

gossipd/routing.c
gossipd/routing.h

Commit a57a2dcb860ee315cb7ce04be9e37e16e5a6ae1e introduced a time_t in routing.h. So also move the time.h include to the header. This fixes the build on FreeBSD.

gossipd: Move include of time.h to routing.h

---

wallet/walletrpc.c

This was removed because withdraw-to-self results in more than the
change being sent to us.

wallet: Re-introduce change assertion for withdrawals

---

tests/test_lightningd.py

Fixes: #916
Makes it less flaky, as, the increased times reduce the
relative delay in processing by slower machines.

test_lightningd: Increase times in expiration waiting test.

---

wallet/walletrpc.c

Fix crash lightning when run dev-rescan-outputs with 0 outputs.
```shell
$ lightning-cli dev-rescan-outputs
lightning-cli: reading response: Success
```
log
```
2018-02-07T13:02:14.395Z lightningd(7759): Adding block 508096: 0000000000000000001530becd6a20abbb016c082d2ee33d692e38086344498c
2018-02-07T13:02:46.193Z lightningd(7759): Connected json input
2018-02-07T13:02:46.194Z lightningd(7759): FATAL SIGNAL 11 RECEIVED
2018-02-07T13:02:46.202Z lightningd(7759): backtrace: lightningd/log.c:473 (log_crash) 0x563834a27da1
2018-02-07T13:02:46.202Z lightningd(7759): backtrace: (null):0 ((null)) 0x7fb58378713f
2018-02-07T13:02:46.202Z lightningd(7759): backtrace: wallet/walletrpc.c:557 (json_dev_rescan_outputs) 0x563834a6c297
2018-02-07T13:02:46.203Z lightningd(7759): backtrace: …
```

Fix dev-rescan-outputs crash on 0 outputs

---

tests/test_lightningd.py

```
>       assert [c['active'] for c in l2.rpc.listchannels()['channels']] == [True, True]
E       AssertionError: assert [True, False] == [True, True]
E         At index 1 diff: False != True
E         Full diff:
E         - [True, False]
E         + [True, True]
```
We don't actually wait that l2's gossipd has also processed the message.

test_lightningd: race fix for activation of channels in test_gossip_jsonprc

---

lightningd/pay.c

Add assertion to clarify assumption made in order to avoid UB.
This assertion will help static (and human) analyzers identify the assumption made.

Add assertion to clarify assumption made in order to avoid UB

---

gossipd/gossip.c
gossipd/routing.c
tests/test_lightningd.py

We get intermittant failed: WIRE_UNKNOWN_NEXT_PEER (First peer not ready)
because CHANNELD_NORMAL and actually telling gossipd that the channel
is available are distinct things.
But we may also directly send the announcement sigs if the height is
sufficient, so the simplest is to unify the messages.

test_lightning: fix race on testing, esp. test_closing_different_fees.

---

lightningd/jsonrpc.c
lightningd/log.c

As reported by @practicalswift in #945 it is possible to inject
non-printable, or shell escape, characters in a json command, that
will fail to parse and then clear the shell.
The second commit also adds an error response when we're unable
to parse the request, just to be extra nice :wink: 
Fixes #945 
Fixes #908

Fix log injection attack and return on JSON parse failure

---

lightningd/gossip_control.c

getroute call computes route from caller to id.
adding optional from_id parameter allows caller to query routes from arbitrary point A to point B. if from_id is not passed code works as before, using caller's id as a starting point for the route

Add optional from_id parameter to getroute call

---

lightningd/peer_htlcs.c
tests/test_lightningd.py
wallet/db.c
wallet/wallet.c
wallet/wallet.h

As proposed by @rustyrussell we just clear any HTLC signatures for the channel in question and write them all, without associating them with the HTLCs they are bound to. The test runs through the failure case of a misbehaving peer that allows us to recover the funds in the HTLC.
Fixes #553

Store HTLC signatures in the database

---

README.md

For the impatient! First time users following these steps may get an error like "Unable to locate package libsodium-dev" if apt-get update is not run first.

doc: Include apt-get update as first step

---

gossipd/gossip.c

Improve log message when receiving unknown message type.
Now mirroring the terminology used in BOLTs (i.e. "unknown message types" in BOLT 1).

Improve log message when receiving packet with unknown message type

---

common/cryptomsg.c
common/cryptomsg.h
gossipd/gossip.c

EBUG:root:lightningd(16333): 2018-02-08T02:12:21.158Z lightningd(8262): lightning_openingd(0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199): Failed hdr decrypt with rn=2
We only hand off the peer if we've not started writing, but that was
insufficient: we increment the sn twice on encrypting packet, so there's
a window before we've actually started writing where this is now
wrong.
The simplest fix is only to hand off from master when we've just written,
and have the read-packet path simply wake the write-packet path.

gossipd: fix race where we can handoff peer with bad cryptostate.

---

openingd/opening.c

Fix typo in error message (funding_signed ids don't match).

Fix typo in error message (funding_signed ids don't match)

---

lightningd/peer_htlcs.c

We will have probably failed the others, but either way, don't try to
fulfill an HTLC we've already failed.
Fixes: #394

onchain: handle case where multiple HTLCs exist for same payment_hash.

---

lightningd/jsonrpc.c
tests/test_lightningd.py

Once we read a command, we are supposed to io_wait until it finishes.
However, we are actually woken in two places: when it's complete
(which is correct), and when it's written out (which is wrong).
~~~This was because the reader and writer were waiting on the same location: make the writer wait/wake on the output queue, instead.~~~
Indeed, when a command is finished, it's time to wake both the output and the input: 
by making the low-level `json_done` routine free the old cmd as well as queue the output,
we reduce code duplication and also make it clear what it's doing.
Fixes: #934

jsonrpc: don't crash on multiple commands at once.

---

bitcoin/chainparams.c
bitcoin/chainparams.h
lightningd/chaintopology.c
lightningd/lightningd.c
lightningd/test/run-find_my_path.c
tests/test_lightningd.py
wallet/wallet.c
wallet/wallet.h

This, I believe, is the proper solution to the problem in #990

UTXO high watermark in db

---

external/Makefile

This way one can pass BUILD and HOST vars in order to cross-compile. Such as:
`BUILD=x86_64 HOST=arm-linux-androideabi make`

Add cross-compilation terms to external submodule configurators

---

contrib/pylightning/lightning/lightning.py
tests/test_lightningd.py

Optional named args in pylightning were handled incorrectly:
dev_setfees(100, slow=100) -> {'immediate': 100, 'normal': 100}
pay(invoice, description='1000') -> {'invoice': invoice, 'msatoshi': 1000}
This branch changes behavior to always put args in correct places in RPC request and adds some tests to avoid regression.

Pylightning

---

lightningd/lightningd.c
lightningd/test/run-find_my_path.c
wallet/wallet.c
wallet/wallet.h

Adds a simple check that compares genesis-blockhashes from the
chainparams against the blockhash that the wallet was created
with. The wallet is network specific, so mixing is always a bad idea.

wallet: Add check that wallet matches the network on startup

---

wallet/walletrpc.c

Add dev-listaddrs command to show bip32 addresses list (up to bip32_max_index). From pr #940
``` shell
$ lightning-cli help
...
command=dev-listaddrs
description=Show addresses list up to derivation {index} (default is the last bip32 index)
...
```
``` shell
$ lightning-cli dev-listaddrs
{ "addresses" : 
[ 
{ 
"keyidx" : 0,
"pubkey" : "...",     
"p2sh": "...",   
"p2sh_redeemscript": "...",
"bech32": "...",
"bech32_redeemscript": "..." 
}, 
.... 
]
}
```
Set optional value {index} to show also future derivations up to {index}. This could be useful for testing and recovery. Default {index} value is `bip32_max_index` in `vars` table of sqlite file.
If you prefer, I can add an `address_type` option (bech32 or p2sh, like `get_newaddr`) to show only one kind of derivation address. 
In this …

Add dev-listaddrs option

---

lightningd/invoice.c

See: https://github.com/ElementsProject/lightning/pull/1020#pullrequestreview-97372207
Fixes: #1014

invoice: Disable overlong description.

---

lightningd/pay.c
lightningd/payalgo.c

Avoid using uninitialized values when calling `command_fail_detailed(...)`.

Add assertions to clarify our assumptions about msg != NULL

---

lightningd/pay.c
tests/test_lightningd.py
tests/utils.py
wallet/db.c
wallet/test/Makefile
wallet/wallet.c

There are several bug reports with similar backtraces; while searching I spotted one missing case, but also decided we should record the upgrades.
I've asked great user who entrusted me with their db file to test this...

Fix route payment failure when upgraded from old db

---

README.md

The more frequent question I ask to myself when initiating channels regards the amount field.
In this document we have three different denominations and the modification proposed aims to address the possible doubts or errors.
The names <amount_in_bitcoins>, <amount_in_satoshis> or <amount_in_millisatoshis> (this last is omitted because the denomination is in the description) are not so elegant but they could serve the purpose.

A more detailed description of the "amount" field

---

Makefile

When cross compiling it's important that the resulting config.h reflects the platform we are building for and not the one we are building on. Otherwise we end up with a config.h that defines headers that are not there on the target platform, wrong endianness and so on.
The -static flag is there to be able to easily run the configurator test executables on the build machine with qemu-*.
E.g. Without the -static flag the resulting dynamically linked ARM executables complain about the lack of linker (/lib/ld-linux-armhf.so or /system/bin/linker for Android), since these files are not usually available on the build machine building statically avoids this problem and results in a proper config.h for cross compiling.
Related to #653

Pass the $(CC) variable to the configurator executable when building config.h

---

Makefile

As of version 5.0 Android requires all dynamically linked executables to support PIE. This allows programs to be loaded at a different addresses, making it harder for attackers to target.
Enable with `PIE=1`
Somewhat related to #653

Add PIE option to Makefile to build position independent executables

---

lightningd/log.c

When we clear and recreate ltmp, we attach it to whatever logbook it's on.
This, of course, is fraught, since it may be freed.
We could make it NULL-parented, but that makes YA special-case to free
when we exit (we try to keep valgrind happy by freeing everything).  So
since the first log_book is the permanent one attached to lightningd,
just keep that parent when we re-build it after use.

log: fix ltmp crash.

---

channeld/test/run-full_channel.c

Make sure `msatoshi` and `sender` are not uninitialized when calling `channel_add_htlc(...)`.

Make sure msatoshi and sender are not uninitialized when calling channel_add_htlc(...)

---

lightningd/peer_htlcs.c

If the source channel is onchain, we try to send a message to onchaind
which (1) doesn't care, (2) doesn't take a channel_fail_htlc msg, and
(3) causes us to crash in subd.c:
assert(!strstarts(sd->msgname(fromwire_peektype(msg_out)), "INVALID"));
Fixes: #821

lightningd: fix crash when htlc failed and source is onchain.

---

lightningd/channel.c

In #1018 we got no information, except "Internal error".  At least
if we tell the other side what went wrong, we're more likely to get
an answer.

lightningd: expose internal error information.

---

common/status.c

Looking at an example log from #968, 288612 of 289244 lines were simply channeld logging incoming and outgoing gossip.

status: don't log gossip messages in channeld.

---

lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/options.c

Remove unused function `json_dev_broadcast(...)`.

Remove unused function json_dev_broadcast(...)

---

wallet/db.c

wallet: remove obsolete peers.

---

channeld/channel.c
common/ping.c
common/ping.h
gossipd/gossip.c
lightningd/options.c
tests/test_lightningd.py

This is helpful for debugging, as many bug reports could be caused by the remote end being old.

Expose version via default name and ping responses (if DEVELOPER=1)

---

Makefile

Fixes #1060 
Tested on Ubuntu 16.04.3 LTS

move library path to LDLIBS

---

lightningd/bitcoind.c
lightningd/bitcoind.h
lightningd/options.c
tests/test_lightningd.py

On IRC BearShark reported that his node always stopped updating blocks; then I noticed that my own node was mysteriously still running after I stopped bitcoind.
Indeed, it was the spurious failure handling which was biting us again.  This fixes and adds tests.

Better handling bitcoin cli fail

---

Makefile
contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386
tests/test_lightningd.py

This adds two new python dependencies to the CI builder:
- flake8: to check the coding style for python scripts
- pytest-rerunfailures: allows to rerun failed tests for a fixed number of times
The latter may hide some flaky tests, but it greatly reduces the need to manually kick travis, so I consider it a net plus. The goal should definitely be to reduce the number of flaky tests, but some tend to slip through anyway. I have an idea to collect flakyness records for tests to re-add the visibility we lose here, but it's not quite done yet.
Fixes #1078

contrib: Add flake8 and pytest-rerunfailures to builder image

---

tests/test_lightningd.py
tools/generate-wire.py

* Avoid using undefined variable `name` in `print_printwire_array(...)`. As discussed in #1071.
* Fix PEP-8 violation.
Fixes #1071.

Avoid using undefined variable "name" in print_printwire_array(...). Fix PEP-8 violation.

---

lightningd/peer_control.h

`opening_failed` `setup_listeners`

lightning/peer_control.h: Minor cleanup of nonexistent functions.

---

cli/lightning-cli.c

Fixes: #574
The issue states that we should follow the standard when
parsing the port for IPv6 [addr]:port syntax, but this is
actually already supported by the daemon. The issue arises
due to the `lightning-cli` misinterpreting [addr]:port as
an array. This modification makes [addr]:port interpreted
as a string.

lightning-cli: Be more discerning about literals.

---

doc/lightning-getroute.7
doc/lightning-getroute.7.txt
doc/lightning-pay.7
doc/lightning-pay.7.txt
gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
lightningd/gossip_control.c
lightningd/payalgo.c
wire/fromwire.c
wire/towire.c
wire/wire.h

Fixes: #928 
I want to integrate `pay` command also to use route randomization if the `maxfeepercent` is high enough, so, this will wait for #993 first so I can add it to `payalgo.c`.

Improve route randomization

---

contrib/pylightning/lightning/lightning.py
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/jsonrpc.h
tests/test_lightningd.py
wallet/walletrpc.c

This modifies invoice command to have the following format
invoice \<msatoshi> \<label> \<desc> <?expiry> <?fallbackaddr>
Note:
I copied the 2 static functions from walletrpc.c
`segwit_addr_net_decode`
`scriptpubkey_from_address`
Should we pull them into a common place so avoid code duplication?

invoice: fallback address argument to invoice command

---

common/test/run-ip_port_parsing.c
common/wireaddr.c
common/wireaddr.h
lightningd/connect_control.c
lightningd/options.c
wallet/wallet.c

Fixes: #834
I am a bit wary of doing it in `parse_wireaddr`, however; perhaps better to expose `separate_address_and_port`, then have `json_connect` only be the one that does hostname resolution.  `parse_wireaddr` is used in handling of `--ipaddr` argument and is somehow used to resolve addresses saved on DB.

wireaddr: Do hostname resolution in parse_wireaddr.

---

Makefile
ccan/README
ccan/tools/configurator/configurator.c

This is my preferred fix for #1090. @icota @arowser @Sjors ?

Configurator cross fix

---

tests/test_lightningd.py

Looks like rebasing the flake8 branch caused breakage, as new violations had occurred since that check was written.

test_lightningd.py: more minor flake8 fixes.

---

doc/INSTALL.md

Add Android build instructions

Update INSTALL.md with Android instructions

---

doc/lightning-pay.7
doc/lightning-pay.7.txt
lightningd/payalgo.c

Users are asking for more information from their failed payments, we should provide it on logs and `pay` return value.

payalgo: Improve telemetry

---

external/Makefile

To avoid failed linking of cross compiled binaries left out after an incomplete `make clean`

Add specific external libs to the makefile clean recipe

---

tests/test_lightningd.py

If bitcoind is still fetching blocks, we might accidentally inject
the failure between getblockhash and getblock.  That's OK, but
it's not the failure we test for.
Closes: #1116

test_lightningd.py: repair flaky test_bitcoin_failure

---

Makefile
external/Makefile

This is how the error before the fix looked like on Arch Linux with
GNU libtool 2.4.6.40-6ca5-dirty:
$ make installcheck
...
make[4]: Entering directory '/home/jasan/lightning/external/libwally-core/src/secp256k1'
/usr/bin/mkdir -p 'testinstall/home/jasan/lightning/external/libwally-core/..'
/bin/sh ./libtool   --mode=install /usr/bin/install -c   libsecp256k1.la 'testinstall/home/jasan/lightning/external/libwally-core/..'
Usage: /home/jasan/lightning/external/libwally-core/src/secp256k1/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: 'testinstall/home/jasan/lightning/external/libwally-core/..' must be an absolute directory name
make[4]: *** [Makefile:910: install-libLTLIBRARIES] Error 1
make[4]: Leaving directory …

Fix libtool error

---

lightningd/jsonrpc.c

Adjust log level for logging disconnected RPC users (`Abandoning command` + `Command returned result after jcon close`).
The following command can be used to trigger these messages:
```
$ timeout 0.01 cli/lightning-cli connect [insert-syntactically-valid-peer-id-here] 123.123.123.123 # where 123.123.123.123 is unreachable
```

Adjust log level for logging disconnected RPC users ("Abandoning command" + "Command returned result after jcon close")

---

lightningd/invoice.c
lightningd/peer_htlcs.c
tests/test_lightningd.py
wallet/invoices.c
wallet/invoices.h
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

Use the db directly as much as we can.
Lowers our memory footprint slightly (depending on how many invoices we have and how long the application keeps invoices alive after paying).

Remove persistent in-memory invoice structures

---

lightningd/jsonrpc.c

Adjust log level for logging disconnected RPC users (`Command failed after jcon close`).
This is a follow-up to #1121.

Adjust log level for logging disconnected RPC users ("Command failed after jcon close")

---

.travis.yml

Add `make clean` check to Travis.
This will guard against `make clean` breaking (see #1130 for context) :-)

Add "make clean" check to Travis

---

lightningd/jsonrpc.c

It turns out that #957 is insufficient to solve #908 . This fix is needed to really say "id": null instead of "id": (null).
This is probably an incomplete fix: it would be better to make sure that **all** cases of NULL are translated into "null". However, I didn't want to touch the tal_fmt implementation. What would be a good approach? make a json_fmt wrapper around tal_fmt to do this? I didn't do this yet: since I'm not too familiar with the code base yet, I didn't want to make too large changes without any guidance.

json-rpc: translate NULL into "null" instead of "(null)".

---

README.md

Can be tested by calling a following script
#!/bin/sh
FILE=${1:-"CONTRIBUTING.md"}
CUR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
{
git checkout $CUR_BRANCH
commonmarker $FILE | tidy > /tmp/aoeui.html
git checkout master >/dev/null
commonmarker $FILE | tidy | diff -u - /tmp/aoeui.html
git checkout $CUR_BRANCH
} 2>/dev/null

Reflow README.md with no changes to text

---

lightningd/channel.c
lightningd/channel.h
lightningd/peer_control.c

Second take of #987, this time we don't just drop the HTLCs on the floor, we outright refuse to forget the channel. `dev-forget-channel` was not intended as a long term solution and will be abandoned soon, but we should make sure we fail gracefully and don't crash.
Fixes #946

Refuse to forget a channel with HTLCs

---

README.md
contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386
tests/test_lightningd.py

Now seems to slightly overlap with #1127. Updates bitcoind to version 0.16.0 and reduces number of blocks pre-generated to 121, instead of 432. 121 are required at least so we have some mature funds.

Update CI builder image to use bitcoind 0.16.0 and reduce number of required blocks

---

lightningd/invoice.c
wallet/db.c
wallet/invoices.c
wallet/invoices.h
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

Rationale: sometimes debtors forget their debts and we have to remind them to pay. Most polite way would be to resend the bolt11 string. 
Say a dumb RPC client connects to the deamon and `listinvoices`. In case we have outstanding (non-paid, non-expired) invoices we should also have the bolt11 available to "share".
Here's a real world scenario on my side:
Let me know what you think!

Store invoice bolt11 in case an RPC client needs it later

---

tests/test_lightningd.py

I initially disabled this until 0.16 because the withdraw command
was modified to require 'brct1' addresses for regtest.
But commit bd07a9 allows a regular testnet address to work
just as well. So renable this check.

revert 0e40c8 and re-enable test_withdraw

---

bitcoin/short_channel_id.c
bitcoin/short_channel_id.h
channeld/channel.c
gossipd/gossip.c
gossipd/routing.c
gossipd/routing.h
lightningd/gossip_control.c
lightningd/pay.c
lightningd/peer_control.c
wallet/test/run-wallet.c
wire/fromwire.c
wire/test/run-peer-wire.c
wire/towire.c

Turns out bitfields were a mistake.  I knew this, but I've learned it again.

Short channel id cleanup

---

contrib/pylightning/lightning/lightning.py

This patch make sure label don't have default value.
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>

pylightning: label is required for waitinvoice()

---

ccan/README
ccan/ccan/intmap/intmap.c
ccan/ccan/intmap/intmap.h
ccan/ccan/intmap/test/run-order-smallsize.c
ccan/ccan/intmap/test/run-order.c
ccan/ccan/intmap/test/run-signed-int.c
ccan/ccan/intmap/test/run.c
ccan/ccan/tal/tal.c
channeld/channel.c
common/subdaemon.c
gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
tests/test_lightningd.py

(I accidentally messed up #1141: ignore that!)
By the end of this, struct routing_channel is king, though it kind of goes the long way around. struct node_connection becomes a member inside struct routing_channel, and struct node is deleted only when no more struct routing_channel point to it.
There are still redundant fields inside struct node_connection (marked with FIXME) but removing them means touching the core routing code, so I want to do that separately.

Routing graph lifetime rework

---

lightningd/onchain_control.c

When the subdaemon closes unexpectedly, clear the reference and
update the channel billboard with the description.
Fixes https://github.com/ElementsProject/lightning/issues/1114

clear onchaind subd in channel on error

---

gossipd/gossip.c
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c

This removes the redundant fields and finally renames everything into more uniform terms: 'node' 'chan' and 'half_chan'.

Routing cleanup finished

---

contrib/pylightning/lightning/lightning.py
lightningd/pay.c
lightningd/payalgo.c
tests/test_lightningd.py

pay/sendpay: Use spec names for rhash and r.

---

common/type_to_string.c
common/utils.c
lightningd/jsonrpc.c
lightningd/memdump.c
lightningd/opt_time.c
lightningd/options.c
lightningd/pay.c
lightningd/payalgo.c
lightningd/peer_htlcs.c
lightningd/subd.c
test/test_state_coverage.c

Also: since I didn't understand the tal_fmt occurrence in config_log_stderr_exit at first, I felt the need to rework the code quite a bit to make it easier to understand. It's still a bit of a hack - the only way to make it really clean is to either extend the opt library, or use something else.
I don't guarantee that this correctly covers all occurrences of tal_fmt. Such a guarantee wouldn't be very valuable anyway, since the code still changes a lot.

Add assertions in various places to ensure tal_fmt doesn't receive NULL as argument for strings.

---

.gitattributes

Not having this change make in a nightmare to code on windows while running on docker.

Add gitattribute to enforce lf on sh and py files

---

tests/test_lightningd.py

pytest: Re-enable formerly flaky test_reconnect_normal

---

lightningd/log.c

Multiple crashes accumulate in case you have some kind
of auto-restart for daemons.

Append to crash log instead of creating new one

---

lightningd/peer_control.c

Confusingly we only printed the `to_self_delay` we imposed on other side, not what the other side imposed on us.  Print both, attributing them correctly (our configuration is `their_to_self_delay`, their configuration is `our_to_self_delay`).

peer_control: Print both `to_self_delay` in listpeers.

---

gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
gossipd/routing.h
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h
wallet/wallet.c
wallet/wallet.h

This PR shortcircuits the txout check to use the internal utxoset if present, saving us from having to call out and parse a block. In addition we now annotate the channels in our routing view to have the total capacity of the channel, hopefully allowing us to make more informed routing decisions in the future.

gossip: Use the internal utxoset to verify channels and store capacity in routing table

---

contrib/pylightning/lightning/lightning.py
doc/Makefile
doc/lightning-sendpay.7
doc/lightning-waitsendpay.7.txt
lightningd/jsonrpc_errors.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/pay.c
lightningd/pay.h
lightningd/payalgo.c
lightningd/peer_htlcs.c
tests/test_lightningd.py
wallet/db.c
wallet/wallet.c
wallet/wallet.h

Part of fix for #1088 
It looks like we can store payments immediately as soon as `sendpay` would return, but now we need to clean up our code by removing "unstored" payments completely...
We also need to save routing failures on-disk; some of our tests need this (`test_pay0` particularly).  For now maybe store a single routing failure with the payment structure (this will get lost when we retry the payment).  For `pay` I intend to have `payalgo` store the series of routing failures for reporting to user on completion/timeout (and will do that in a later PR that finishes #1088).

Sendpay nonblock

---

doc/lightning-sendpay.7
doc/lightning-sendpay.7.txt
doc/lightning-waitsendpay.7
doc/lightning-waitsendpay.7.txt
lightningd/pay.c
lightningd/pay.h
tests/test_lightningd.py

Part of fix for #1088.
A note on `json_add_payment_fields`: I intend to reuse this function for the modification for `pay` output.  My intent is that `pay` displays the fields for the payment, but also adds some fields --- `getroute_tries`, `sendpay_tries`, `route`, `failures` --- indicating detailed information about the payment. Thus, the reason why `json_add_payment_fields` provides the payment details but does not open and close an object.

Change `sendpay` result to be nearer to `listpayments`

---

lightningd/chaintopology.c

We would `block_map_add` inside `add_tip`, but we never
`block_map_del` inside `remove_tip`, which is dangerous as
we actually `tal_free` the block inside `remove_tip`.
Our CI did not reliably trap this problem since block
hashes are random and rerunning the `test_blockchaintrack`
often passed spuriously.

chaintopology: Add missing `block_map_del`.

---

tools/rel.sh

Fixes: #1221
We were using `\x0` to match NUL chars in the input (on the
assumption that NUL chars are "impossible" for decent LFS-compliant
systems).
However `\x0` is a GNUism.
Use the `\n` and the newline character, which is supported by (most)
POSIX sed.

tools/rel.sh: Make POSIXLY compatible `sed` script.

---

lightningd/pay.c
tests/test_lightningd.py
wallet/wallet.c
wallet/wallet.h

I also note that we *never* delete HTLCs, though we can (and should!) once they're in the final revoked state.

Fix for crash when onchaind hits a deleted payment.

---

lightningd/channel.c
lightningd/opening_control.c
lightningd/peer_control.c
tests/test_lightningd.py

Fixes: #1229
The principle is that `error` should really be as specific as possible.  We also have vague plans to maybe, might be, have multiple channels per peer, in some possibility that may or may not be 0.

channel_fail_permanent: Use a channel-level error, not an all-channels error.

---

devtools/onion.c
lightningd/subd.c

Minor cleanups:
* Check `hex_decode(...)` return value
* Never pass a negative argument to `dup2(...)`

Check hex_decode(...) return value.  Never pass a negative argument to dup2(...)

---

lightningd/opening_control.c
lightningd/opening_control.h
lightningd/peer_control.c
wallet/test/run-wallet.c

Possibly related to #1235 and #1236, but not confirmed to fix that.

peer_control: Fix a use-after-free bug.

---

lightningd/chaintopology.c

Naively, this would be 250 satoshi per sipa, but it's not since bitcoind's
fee calculation was not rewritten to deal with weight, but instead bolted
on using vbytes.
The resulting calculations made me cry; I dried my tears on the thorns
of BUILD_ASSERT (I know that makes no sense, but bear with me here as I'm
trying not to swear at my bitcoind colleagues right now).
Fixes: #1194

chaintopology: set a fee floor to avoid creating unrelayable txs.

---

wallet/db.c
wallet/wallet.c

wallet: Remove onion-decoding information from db on payment success/fail

---

gossipd/test/run-find_route.c

Use correct privkey when calculating pubkey used in `new_routing_state(...)` call.
Prior to this commit `a` was uninitialized when calling `new_routing_state(...)`.
Context: https://github.com/ElementsProject/lightning/pull/1262#issuecomment-375627602

tests: Use correct privkey when calculating pubkey used in new_routing_state(...) call

---

lightningd/bitcoind.c
lightningd/bitcoind.h
lightningd/options.c

It's useful when we are connecting to a bitcoind set to a port other than default 8332

Add --bitcoin-rpcport option

---

.gitignore
.gitmodules
common/subdaemon.c
external/Makefile
lightningd/log.c

fix https://github.com/ElementsProject/lightning/issues/840
backtrace module does not support mac. So, disable crash log if BACKTRACE_SUPPORTED is 0.
The reason why this patch fix https://github.com/ElementsProject/lightning/issues/840 is not fully identified. On mac, SIGSEGV and SIGBUS signal happens after jsonrpc only when signal handlers are registered with ``sigaction()``.

Disable backtrace on mac

---

lightningd/subd.c
lightningd/subd.h

If not included, a source file containing only `#include<lightningd/subd.h>` will fail compilation.

lightningd/subd.h: Add missing wire/wire.h.

---

lightningd/json.c
lightningd/pay.c
wallet/db.c
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

Add `msatoshi_sent` field to payments, symmetrical to the `msatoshi_received` field of invoices.

pay: Also record how much we actually ended up sending.

---

wallet/test/run-wallet.c
wallet/wallet.c

As noted by @rustyrussell [here](https://github.com/ElementsProject/lightning/pull/1275#discussion_r176962952) I never got around to clear pruned outpoints from the filter, so this fixes that.

wallet: Remove pruned outpoints from utxoset outpoint_filter

---

common/utxo.h
lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/onchain_control.c
lightningd/opening_control.c
onchaind/onchain.c
onchaind/onchain_wire.csv
tests/test_lightningd.py
wallet/wallet.c
wallet/wallet.h

We were not tracking confirmations for change outputs and their_unilateral/to_us outputs:
- Scripts of change outputs were not being added to the txfilter, hence we didn't get a notification
- their_unilateral/to_us were not added to the txfilter and since we learnt about them only _after_ they were confirmed through `onchaind` we were missing its confirmation.
This PR fixes both, and includes a small fix.
Fixes #1209

Track confirmations for change and their_unilateral/to_us outputs

---

contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386

It's a check dependency from PR #1262.

travis: Updated docker builder images to include cppcheck

---

common/overflows.h

The overflow check `mul_overflows_s64(int64_t, int64_t)` overflows:
When doing say `mul_overflows_s64(9223372036854775807, 2)` a signed integer overflow occurs `mul_overflows_s64` when calculating `a * b`.
Since this is an signed integer overflow this triggers UB, which in turn means that we cannot trust the check.
Luckily `mul_overflows_s64(int64_t, int64_t)` is unused. Removing it.

Fix: Overflow check mul_overflows_s64(int64_t, int64_t) overflows and triggers UB

---

.gitignore

This, is generated, by `make check`.
Probably better to put it in some location elsewhere, though?

.gitignore: Ignore `gossip_store` file.

---

doc/lightning-sendpay.7
doc/lightning-sendpay.7.txt
lightningd/pay.c
lightningd/pay.h
lightningd/payalgo.c

This obscures how far an intermediate hop is from the ultimate
payee, and also obscures slightly the exact payment value.
Fixes: #1089

payalgo: Be willing to overpay up to maxfeepercent, for privacy.

---

wallet/db.c

The fact that we reopen the DB connection after a fork means that we also need to re-enable the foreign key support on that connection, otherwise we don't manage foreign keys and cascades correctly.
Fixes #1280

Enable foreign key constraints when running with --daemon

---

doc/lightning-pay.7
doc/lightning-pay.7.txt
lightningd/payalgo.c

Fixes: #1086
***NOTE*** Although I use `delay` here, I wonder if a better term would be  `locktime`.  This is because, in the worst case, this is the number of blocks that the money will get locked before it can be recovered.

payalgo: Add maximum delay.

---

gossipd/gossip.c

Adjust loglevel for error message "Failed to get peername for incoming conn".
I've seen this triggered on testnet. Likely not of interest for an end-user running with the default loglevel.

Adjust loglevel for error message "Failed to get peername for incoming conn"

---

Makefile
common/version.c

Before this commit:
```
$ lightningd/lightningd --version
v0.5.2-2016-11-21-2451-gcd1eb52-dirty
aka. Bitcoin Savings & Trust Daily Interest II
Built with:
```
After this commit:
```
$ lightningd/lightningd --version
v0.5.2-2016-11-21-2451-gcd1eb52-with-local-modifications
```

Simplify version output (lightningd --version)

---

common/daemon.c

Fixes: #1328
In commit https://github.com/ElementsProject/lightning/commit/feb6b52f0f83ac1f6f2a35537e6e541f9d3a3110 some conditionals were put around the declaration of `bt_print` and `bt_exit`'s declaration.  When I pull the repo down and `make` it on my system, I get the following errors:
```
common/daemon.c:87:2: error: use of undeclared identifier 'bt_print'
bt_print = backtrace_print;
^
common/daemon.c:88:2: error: use of undeclared identifier 'bt_exit'
bt_exit = backtrace_exit;
^
2 errors generated.
make: *** [common/daemon.o] Error 1
```
Which make sense since those declarations are not actually present.
This commit encloses the calls to `bt_print` and `bt_exit` in the `BACKTRACE_SUPPORTED` conditional.

bt_print and bt_exit is enclosed in the conditional

---

lightningd/lightningd.c

Creating the pid-file before daemonizing results in the pid-file containing the
pid of the process that started the daemon, but is now dead.
Fixes #1338

master: Move pid-file creation after the daemonization

---

Makefile

Accidentally disabled in 9c3691340fa430ed1daf08dc40f76bd7369f66cc.

shellcheck: restore the check.

---

common/json.c
common/test/run-json.c

Just a small cleanup of the indentation code, so we don't have to reformat all
the issue reports to become readable. This is much closer to what `jq` or
`json_pp` spit out and doesn't have those infinitely long lines.

jsonrpc: Pretty-print the json results

---

gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
gossipd/routing.h
lightningd/gossip_msg.c
lightningd/pay.c
lightningd/payalgo.c

Fixes: #1344
Internally both payment and routing use 64-bit, but the interface
between them used 32-bit.
Since both components already support 64-bit we should use that.

routing: Use 64-bit msatoshi for messages to and from routing.

---

lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/onchain_control.c
lightningd/peer_control.c
lightningd/watch.c
lightningd/watch.h
wallet/db.c
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

This is some preparatory work to get to no-rescan startups. We store transactions we own, watch or broadcast in a DB table. This allows us to track their depth and recover the transactions for debugging purposes. The transactions will also be used by the `onchaind` replay (next PR) to feed transactions in and restore its state.

Persistence transaction tracking in the database

---

closingd/closing.c
lightningd/closing_control.c

Fixes: #1361 
Reported-by: @nayuta-ueno

closingd: Correct whose turn it is when moving from initial negotiation to continuous negotiation.

---

lightningd/bitcoind.c

fix https://github.com/ElementsProject/lightning/issues/1093
Running with lldb cause SIGINT, which makes waitpid(), read()
returns error with errno as EINTR. This patch retry these calls
to ignore EINTR errors.
Tested only on macOS.

Support debugging with lldb

---

common/test/run-ip_port_parsing.c

Assert our `parse_wireaddr` assumptions in `run-ip_port_parsing.c`.
We assume that the `parse_wireaddr(...)` calls return `true`. Otherwise `addr.port` will be uninitialized.

Assert our parse_wireaddr assumptions in run-ip_port_parsing.c

---

lightningd/pay.c
lightningd/payalgo.c
wallet/db.c
wallet/wallet.c
wallet/wallet.h

Pointless for remote failures as those are never sent by
the erring node, but for local failures we can give more
detail.

wallet, payalgo: Save detail of payment failures for later reporting.

---

doc/lightning-autocleaninvoice.7

Strange behavior where `a2x` sometimes does not work at all.

lightning-autocleaninvoice.7: Properly generate instead of using an empty file.

---

gossipd/routing.c
hsmd/hsm.c
lightningd/gossip_msg.c
lightningd/opening_control.c
wallet/walletrpc.c

There were 7 spaces in routing.c and 4 spaces in other files. Replaced them with tabs.
I searched them with this script and edited manually.
```
grep -r --exclude bech32.c --exclude signature.c --exclude chainparams.c --exclude options.c --exclude netaddress.c --exclude db.c --exclude wallet.c --exclude *wire.c '^    ' */*.c | grep -v '        '
```

Clean up codes by adjusting wrong indents

---

gossipd/gossip.c
gossipd/gossip_store.c
gossipd/gossip_store.csv
gossipd/gossip_store.h
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
tests/test_lightningd.py

The following would lead to an unusable channel until `announce_depth` was reached:
- Fund a channel
- Wait for funding locked
- Restart
This PR simply stores locally added channels (not yet at `funding_depth` or not public) and replays the `local_add_channel` on `gossip_store` read.
Fixes #1367

Store locally added channels to the gossip_store

---

contrib/pylightning/lightning/lightning.py
doc/Makefile
doc/lightning-close.7
doc/lightning-close.7.txt
lightningd/channel.c
lightningd/closing_control.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/peer_control.c
lightningd/peer_control.h
tests/test_lightningd.py
wallet/test/run-wallet.c

Also report tx and txid, and whether we closed unilaterally or
bilaterally, if we could close the channel.
Also make a manpage.
Fixes: #1207
Fixes: #714
Fixes: #622

peer_control: Make close wait for complete closure, with timeout.

---

lightningd/chaintopology.c
lightningd/channel.c
lightningd/channel.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/onchain_control.c
lightningd/onchain_control.h
lightningd/options.c
lightningd/peer_control.c
lightningd/test/run-find_my_path.c
tests/test_lightningd.py
tests/utils.py
wallet/db.c
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

With these changes `onchaind` no longer relies on rescanning the blockchain from the wallet's birth height on each startup. Instead we remember the transactions that triggered some behavior in `onchaind` and replay them before syncing with the blockchain.
This is the continuation of #1364 which took care of storing transactions we are interested in and tracking their confirmations when syncing. The `onchaind` persistence is a small layer on top of those transactions remembering which transaction triggered what notification to `onchaind`.
In addition the sync offset calculation was simplified, and we can now use the `--rescan` command line option to specify either a relative or absolute height to continue syncing from. The default is 30 blocks for testnet and 15 for mainnet, to counter …

Store onchaind state in the database and reduce rescan on startup

---

wallet/wallet.c

I have a more thorough fix which wraps sqlite3_stmt, so we get told about leaks in general, but this is the immediate fix.

wallet: free sql statement in wallet_onchaind_channels.

---

lightningd/chaintopology.c

Fixes: #1423
(Hopefully)
Reported-by: @NicolasDorier

chaintopology: Protect against underflow when computing first_blocknum.

---

gossipd/gossip.c
tests/test_lightningd.py

So we can get via address hint, DNS seed, or node_announcement
gossip.

gossip: Use gossiped node_announcement to locate nodes.

---

gossipd/gossip.c
gossipd/gossip_wire.csv
lightningd/gossip_control.c
lightningd/gossip_control.h
lightningd/lightningd.c
lightningd/test/run-find_my_path.c

If we start accepting peer connections before we initialized some of the other
parts (mainly the chaintopology) we could end up asking for stuff that isn't
ready yet (blockchain head for example).
Fixes #1437

master: Move the gossipd initialization after the other inits

---

lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/opening_control.c
lightningd/peer_control.c
tests/test_lightningd.py
wallet/test/run-wallet.c

We're getting spurious closures, even on mainnet.  Using --ignore-fee-limits
is dangerous; it's slightly less so to lower the minimum (which is the
usual cause of problems).
So let's halve it.
This is a workaround, until we get independent feerates in the spec.
(Note: I've labeled this as fixes #613 but that should have been fixed by previous update_fee fixes; this addresses more the other comments on that issue which refer to spontaneous closures without --override-fee-rates).

lightningd: loosen feerate minimum.

---

lightningd/lightningd.c

Fixes: #1445
Hacky fix, possibly.  First cut at avoiding starting up onchaind and gossipd (which might make queries of chaintopology, which might start up a bitcoin-cli) before we can daemonize.
Please ignore the unnecessary merge commit for now, I will fix that later, the other commit is the one I want to merge in.  @Sjors, could you try this branch?

lightningd: Move onchaind replay and gossipd activation after daemonization

---

Makefile

We had quite a few users running into issues because the `--dev-xyz` options and
`dev-xyz` RPC calls were available. Before a release we should make sure that
the default compilation flags are safe.

make: Disable DEVELOPER by default

---

gossipd/gossip_store.c

gossipd: Handle failed lseek(...)

---

channeld/channel.c
gossipd/gossip.c
gossipd/routing.c
tests/test_lightningd.py

This should make PR #1330 testable: we send a channel_update for non-public channel directions so that our peer can make use of the channel for incoming payments.

Send a local channel_update upon funding_locked so that the incoming halfchan becomes announceable

---

Makefile
contrib/Dockerfile.builder
contrib/Dockerfile.builder.fedora
contrib/Dockerfile.builder.i386
tests/fixtures.py
tests/requirements.txt
tests/test_gossip.py
tests/test_lightningd.py
tests/utils.py

I got a bit sidetracked while implementing the `local_channel_updates` patch (that's going to be my next PR). This PR modernizes the integration test environment using the pytest style fixtures, flattening the test structure (functions instead of class methods) and begins the migrating the tests into smaller, better structured test files. The goal is to split the huge `test_lightningd` into smaller, topic based test files that can be selectively executed for changes, e.g., executing `test_gossip.py` if we changed gossip and don't expect failures in other parts of the suite (CI will still catch those).
One major change is that we now have the tests isolated into their own directory and selecting random ports for all daemons, which means that we can run the tests in parallel with …

pytest: Enable parallel test execution and start migration to modern fixtures

---

tests/test_closing.py
tests/test_lightningd.py

It simply wasn't waiting for us to register the peer before attempting to open a
connection. Moved into a separate test to be able rerun multiple times.

pytest: Fix flaky `test_closing_id` test

---

lightningd/payalgo.c

We allocate the reason to delay, if any, from the `pay->try_parent`.
So we should not clear the `pay->try_parent` until after we print
the reason.

payalgo: Report reason to delay before clearing try memory.

---

doc/Makefile
doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt

This describes `fundchannel` as it works today (as I understand it). #1360
It definitely could use better error codes instead of -1 for everything.
Is there a better way to tell if the channel is ready than the one I described?

doc: Added fundchannel man page.

---

gossipd/gossip.c
tests/test_closing.py
tests/test_lightningd.py

My weekly cleanups, this week early, since the parallel merge of the network rework PR #1450 and my PR #1473 unfixed the fix right away.

A number of pytest fixes and a minor cleanup in gossip

---

closingd/Makefile
closingd/closing.c
common/Makefile
common/socket_close.c
common/socket_close.h
tests/test_lightningd.py

If not properly closed (as described in [this document](http://ia800504.us.archive.org/3/items/TheUltimateSo_lingerPageOrWhyIsMyTcpNotReliable/the-ultimate-so_linger-page-or-why-is-my-tcp-not-reliable.html)), the last message may not get sent when the socket is closed.  This affects `closingd` primarily, since we should send a final `closing_signed` before disconnecting.
The added `test_closing_torture` attempts to trigger the bug but even with 15 tries it often passes prior to the fix.  A higher value takes too long and may trigger the CI giving up on a VALGRIND run.

Properly close TCP sockets

---

common/wireaddr.c
common/wireaddr.h

Fix BUILD_ASSERT failure on macOS, introduced in https://github.com/ElementsProject/lightning/commit/6b2282fc1dd9f09cf238340d9e1daa9de424b098
Fixes: #1478

Fix BUILD_ASSERT failure in wireaddr_to_sockname

---

gossipd/gossip.c

Looks like old connection got a callback, and we blew up since
the old peer was freed:
2018-05-06T10:57:11.865Z lightning_gossipd(14387): ...will try again in 300 seconds
2018-05-06T10:57:16.397Z lightning_gossipd(14387): peer_out WIRE_INIT
2018-05-06T10:57:16.405Z lightning_gossipd(14387): peer_in WIRE_INIT
2018-05-06T10:57:16.406Z lightning_gossipd(14387): peer 03b30e131241fe28fc923d74a060a8c7abfcc91323c485f8a9cf964575cb4fd3f4: reconnect for local peer
2018-05-06T10:57:16.406Z lightning_gossipd(14387): peer 03b30e131241fe28fc923d74a060a8c7abfcc91323c485f8a9cf964575cb4fd3f4 now remote
2018-05-06T10:57:16.406Z lightning_gossipd(14387): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-05-06T10:57:16.406Z lightning_gossipd(14387): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-05-06T10:57:16.406Z …

gossipd: when reconnecting, make sure we free old connection.

---

gossipd/tor_autoservice.c

Avoid static analyzer warning about integer wraparound.

Avoid static analyzer warning about integer wraparound

---

common/wireaddr.c

`addrstr` is an array of 35 bytes (`char addrstr[LARGEST_ADDRLEN] `).
In the case of an IPv6 address we execute:
```
case ADDR_TYPE_IPV6:
if (!inet_ntop(AF_INET6, a->addr, addrstr, INET6_ADDRSTRLEN))
return "Unprintable-ipv6-address";
return tal_fmt(ctx, "[%s]", addrstr);
```
Since `INET6_ADDRSTRLEN > LARGEST_ADDRLEN` we trigger a buffer overflow when calling `inet_ntop(…)`.
```
$ git grep -E '#define.*(LARGEST_ADDRLEN|TOR_V3_ADDRLEN)'
common/wireaddr.h:#define       TOR_V3_ADDRLEN 35
common/wireaddr.h:#define       LARGEST_ADDRLEN TOR_V3_ADDRLEN
$ grep INET6_ADDRSTRLEN /usr/src/linux-headers-4.4.0-116/include/linux/inet.h
#define INET6_ADDRSTRLEN	(48)
$ grep INET6_ADDRSTRLEN /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/netinet6 …
```

wireaddr: Avoid buffer overflow in fmt_wireaddr_without_port()

---

ccan/README
ccan/ccan/endian/endian.h
ccan/ccan/opt/usage.c
ccan/tools/configurator/configurator.c

Will allow me to build on alpine, fix this error I get on https://github.com/ElementsProject/lightning/pull/1318
```
In file included from ./bitcoin/block.h:5:0,
from ./wire/wire.h:4,
from ./common/sphinx.h:12,
from devtools/onion.c:5:
ccan/ccan/endian/endian.h:116:0: error: "__BYTE_ORDER" redefined [-Werror]
#define __BYTE_ORDER __LITTLE_ENDIAN
In file included from /usr/include/sys/types.h:70:0,
from external/libsodium/src/libsodium/include/sodium/randombytes.h:5,
from ./common/sphinx.h:11,
from devtools/onion.c:5:
/usr/include/endian.h:11:0: note: this is the location of the previous definition
#define __BYTE_ORDER __BYTE_ORDER__
cc1: all warnings being treated as errors
make: *** [<builtin>: devtools/onion.o] Error 1
make: *** Waiting for unfinished jobs....
```
Should be fixed …

Fix build on linux-musl

---

lightningd/options.c

Do not use potentially uninitialized value `needed_dns`.

Do not use potentially uninitialized value needed_dns

---

wire/Makefile

It's no longer functional, and is being removed upstream.

wire: remove --check-alignment arg from spec parsing tool.

---

Makefile

Setting these options could fail the `pytest` target if `pytest-test-groups` is
not installed.
Fixes #1508

pytest: Do not set test-groups unless explicitly requested

---

channeld/channel.c
gossipd/gossip.c
gossipd/gossip_wire.csv
gossipd/routing.c
lightningd/gossip_control.c

Rather than having gossipd and channeld both generate signed updates, have gossipd always do it.

Fix channel_update timestamp races

---

lightningd/log.c

Low hanging fruit taking quite of CPU.
(was log level debug)

Do not call strlen for every character in the log entry

---

lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/channel.h
lightningd/channel_control.c
lightningd/channel_control.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/opening_control.c
lightningd/options.c
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h
lightningd/test/run-find_my_path.c
tests/test_lightningd.py

As per BOLT spec:
> A non-funding node (fundee):
>   - SHOULD forget the channel if it does not see the
> funding transaction after a reasonable timeout.
We use blocks as unit of timeout.  We forget the channel, if we are the fundee, if it has been 2016 blocks (`--max-funding-unconfirmed-blocks`, two weeks) since the channel was opened, and we have not seen it locked in yet.

Forget channel if we are fundee and it has not confirmed yet for a long time

---

doc/INSTALL.md
external/Makefile

Proposed fix for issue #1231 - FreeBSD (tcsh) build problem due
to HOST environment variable.

external/Makefile: Change HOST to MAKE_HOST

---

lightningd/payalgo.c

Just a modification of comments.
Rationale
1. The loss of precision will be like feepercent of 3.0000..(some dots)..1 % vs 3.0 %.
2. The loss of 0.0000..(some dots)..1 above is not representable in double.
I mean, the loss of precision in msatoshi might be significant but the loss of precision in feepercent is not significant (Or there is no loss of precision in feepercent, I'm not sure).

Modify comments about the precision

---

common/wallet_tx.c
lightningd/chaintopology.c
lightningd/connect_control.c
lightningd/dev_ping.c
lightningd/gossip_control.c
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/jsonrpc_errors.h
lightningd/log.c
lightningd/memdump.c
lightningd/opening_control.c
lightningd/options.c
lightningd/pay.c
lightningd/payalgo.c
lightningd/peer_control.c
lightningd/peer_htlcs.c
wallet/test/run-wallet.c
wallet/walletrpc.c

Until now, `command_fail()` reported an error code of -1 for all uses.
This PR adds an `int code` parameter to `command_fail()`, requiring the
caller to explicitly include the error code.
This is part of #1464.
The majority of the calls are used during parameter validation and
their error code is now JSONRPC2_INVALID_PARAMS.
The rest of the calls report an error code of LIGHTNINGD, which I defined to
-1 in `jsonrpc_errors.h`.  The intention here is that as we improve our error
reporting all occurenaces of LIGHTNINGD will go away and we can eventually
remove it.
I also converted calls to `command_fail_detailed()` that took a `NULL` `data`
parameter to use the new `command_fail()`.
The only difference from an end user perspecive is that bad input errors that
used to be -1 will now be -32602 …

Added error code parameter to command_fail

---

channeld/full_channel.c

This is the cause of linear slow down in payment in https://github.com/ElementsProject/lightning/issues/1506
Thanks to @Saibato  and @ZmnSCPxj 
Before
After

Make dump_htlcs SUPERVERBOSE

---

Makefile

Previously, by uncommenting NO_VALGRIND in Makefile, the variable
was not propagated and the children processes would still try to
use Valgrind.
Tested on Alpine Linux:
make NO_VALGRIND=1 check
Also works after uncommenting both related lines in Makefile.

Makefile: Propagate `NO_VALGRIND` to `py.test` invocation.

---

Makefile
gossipd/gossip.c
gossipd/gossip_wire.csv
lightningd/channel.c
lightningd/closing_control.c
lightningd/gossip_control.c
tests/test_gossip.py
tests/test_lightningd.py
tests/utils.py
wallet/test/run-wallet.c

The flaky pruning tests were really annoying, so I took a closer look at them. It turns out that we were relying on a `channel_update` being sent before actually closing the connection, otherwise we were not disabling both directions.
This now explicitly disables both directions on close, and on disconnect. While not a big issue before, with the `r` fields being merged soon, we could end up sending a disabled channel as a `contact_point` if we didn't disable them.
Other changes include better handling of concurrent opens and watching to logs for the wrong signals, and filtering out some output (looking at you Fee Estimator)
Fixes #1515 since I now feel much better about the test stability.

Stabilize a number of flaky tests and fix some gossip semantics while we're at it

---

lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/gossip_control.c
lightningd/lightningd.c
lightningd/test/run-find_my_path.c
wallet/wallet.c
wallet/wallet.h

We now remember the block range that we have stored in the DB and don't go ask for outpoints that we would know if they'd exist.
This was a common problem before: we'd receive a `channel_announcement` for a spent outpoint (the remote node didn't prune) and we'd always call out to `bitcoind` even though we removed the outpoint earlier and it not existing should have been the signal to ignore the announcement.

Do not ask bitcoind for outpoints we should know

---

.gitignore
tests/fixtures.py
tests/test_lightningd.py
wallet/test/run-wallet.c

With the isolated and parallel testing each test run now produces about 25 MB of data in the form of the bitcoin datadir and logs, which pretty quickly accumulates. This simply removes the test directory if the test completed successfully.

pytest: Clean up test directories and files if the tests succeeded

---

doc/deployable-lightning.lyx

The schnorr signatures link have been update now.

udpate broken link in deployable-lightning.lyx

---

README.md

Now required, after the changes in https://github.com/ElementsProject/lightning/commit/c49765553ffc352e678684703c513351d418969e.

README: Add ./configure to installation instructions

---

common/daemon.c

Sometimes people only send us the crash, not the logs.

daemon: print version in crash backtrace.

---

tests/test_closing.py
tests/test_gossip.py
tests/test_lightningd.py

72d103d6bb8ddc3b06fb980946ab75e055f7a8a1 deprecated DEVELOPER env var
in favor of config.vars, but didn't update test_closing.py or test_gossip.py.
5d0a54b7f0880c22afc2e9082bd9e89f2cf61fbe then removed the explicit
DEVELOPER= setting from Travis.

tests: reenable developer tests.

---

lightningd/lightningd.h
lightningd/options.c
lightningd/peer_control.c
tests/test_lightningd.py

This has been brought up a few times, and I think we should at least ensure that the default parameters of the three implementations match. Together with #1551 this obviates all the workarounds I had in the integration testing suite. I still think our old defaults were better, but maybe we can go back to saner defaults over time.
I added the `max_fee_multiplier` as an option since it was the only non-configurable parameter that needed to be changed for this.
Closes #1110 
Closes #1560

opts: Be more lenient about locktime_max and fee range by default

---

lightningd/invoice.c

satoshis.place was slowing to a crawl, c-lightning was unresponsive.
Logs revealed charged doing many, many listinvoice <label> RPCs.
We were iterating the entire db every time: stop that!

listinvoice: speed up single-invoice case.

---

common/wireaddr.c

2018-06-14T01:09:03.495Z lightningd(23766): HSM: created new hsm_secret file
==23785== Syscall param socketcall.bind(my_addr.sin6_flowinfo) points to uninitialised byte(s)
==23785==    at 0x5731877: bind (syscall-template.S:78)
==23785==    by 0x11767C: make_listen_fd (gossip.c:2405)
==23785==    by 0x117DA2: handle_wireaddr_listen (gossip.c:2558)
==23785==    by 0x1183B7: setup_listeners (gossip.c:2653)
==23785==    by 0x118E86: gossip_activate (gossip.c:2871)
==23785==    by 0x11AC42: recv_req (gossip.c:3543)
==23785==    by 0x143FF1: next_plan (io.c:59)
==23785==    by 0x144AEE: do_plan (io.c:387)
==23785==    by 0x144B2C: io_ready (io.c:397)
==23785==    by 0x146719: io_loop (poll.c:310)
==23785==    by 0x11B0B0: main (gossip.c:3687)
==23785==  Address 0x1ffeffffa4 is on thread 1's …

Fix valgrind warning with IPv6 sockets

---

lightningd/options.c

I think it's better if the default value works with other implementations. If you want to be more aggressive, you'd start lightningd with `--cltv-final=6` for instance.
As explained in https://github.com/ACINQ/eclair/issues/526, Eclair won't accept payment requests with `cltv_final` too low. Error message from Eclair for any value below 10:
```
1 attempts:
- (remote) payment expiry is too close to the current block height for safe handling by the final node
```

Increase cltv_final

---

gossipd/gossip.c

I think this is what is causing #1536: getting disconnected causes gossipd to
attempt to reach the peer again, unconditionally setting the flag to tell the
master. At the same time the master also issues a reaching command (which is
allowed since it is its first), but then it clashes on the already set
flag. Setting this flag only when the master actually needs to be told should
fix this.
Haven't touched this code in a while so @rustyrussell will have to pitch in about its correctness :wink: 
Fixes #1536

gossip: Fix "already reaching" issue

---

channeld/channel.c
gossipd/gossip.c
lightningd/bitcoind.c
lightningd/bitcoind.h

We've had some weird crashes on sleepyark, so I audited gossipd.  Found some lifetime issues, and user-after-free in corner cases, but no smoking gun.
I also fixed an overzealous assert in lightning_channeld.

Gossip leak plugging/neatening and channeld crash fix.

---

Makefile
doc/HACKING.md

Personally, I find it difficult to grok the Lightningd source code. I hope this helps.

Add 'make ncc' target, for source code analysis.

---

lightningd/options.c
lightningd/payalgo.c

Proposed by @rustyrussell.
Fixes #1586

pay: Use `locktime_max` as maximum cumulative CLTV delta

---

common/wallet_tx.c
doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt
doc/lightning-withdraw.7
doc/lightning-withdraw.7.txt
lightningd/jsonrpc_errors.h
lightningd/opening_control.c
tests/test_lightningd.py

New codes: FUND_MAX_EXCEEDED, FUND_CANNOT_AFFORD, FUND_DUST_LIMIT_UNMET.
The error message "Cannot afford fee" was not exactly correct because
it would also occur if the amount requested could not be afforded.  So
I changed it to the more generic "Cannot afford transaction".
Other things:
* Fixed off-by-one satoshi in fundchannel manpage.
* Changed 'arror' to 'error' because we are not pirates.

Added wallet related error codes

---

common/wireaddr.c
common/wireaddr.h
doc/lightningd-config.5
doc/lightningd-config.5.txt
gossipd/gossip.c
gossipd/gossip_wire.csv
lightningd/gossip_control.c
lightningd/lightningd.h
lightningd/options.c
tests/utils.py

This is a more durable fix of #1600 I think. It adds the option to disable DNS lookups of node IDs, uses that option while testing, and also tries to identify a misbehaving DNS ISP resolver that hijacks NXDOMAIN replies, like @gwillen pointed out might happen. It's best effort, but even if it fails, it'll just perform a failing connect attempt.
What do you think @rustyrussell, shall we keep that last commit in there?

Add cli option to disable DNS node ID lookup

---

doc/INSTALL.md
tools/check-manpage.sh

I actually fired up a Fedora instance, and a FreeBSD instance.  I couldn't get the python stuff working on FreeBSD, so couldn't run `make check` there though.

Update install instructions

---

Makefile
contrib/Dockerfile.builder.fedora

- Sets the commit ID length to 7 on all platforms
- Adds two more dependencies to the fedora build so it can build the tarball

Two small changes for the release targets

---

.gitattributes

Without this, building the `dockerfile` on windows will likely fail.

Add configure and .gitmodules to .gitattributes

---

Dockerfile
README.md
tools/docker-entrypoint.sh

A bug in the dockerfile has been introduced because of unclear `LIGHTNINGD_PORT` environment variable.
`socat` was trying to bind on the same port as lightning, while it should have been on a different one exposing the API by TCP. 
As such I renamed `LIGHTNINGD_PORT` to `LIGHTNINGD_RPC_PORT`, and made sure it is properly used.

[Docker] Fix: Bind socat to the right port

---

contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386

travis: Add asciidoc, excluding latex, to the builder images

---

contrib/pylightning/lightning/__init__.py
contrib/pylightning/lightning/lightning.py
tests/test_lightningd.py

Based on @marzig76's proposal to expose the returned error in its parsed form for further handling.
Fixes #1638 
Closes #1644

pylightning: Subclass ValueError to access the returned error

---

doc/INSTALL.md

There's more pies than the Raspberry.
Armbian uses Ubuntu 16.04 / 18.04 to build images that you can then put on an SD card. You can pass extra commands to that process which I've used to compile c-lightning. This works fine using just the regular Ubuntu instructions, but it's pretty slow. I'm not entirely sure how Armbian tricks the build process into creating the correct binary for the device architecture, but it does.
Based on experience cross-compiling Bitcoin Core, I suspect cross-compiling c-lightning will be much faster if done on the Ubuntu VM, rather than during the Armbian build process. However I wasn't able to figure out how to tweak the Raspberry Pi instructions to do this.
Perhaps these instructions are useful as-is, but otherwise we can leave this open until someone figures …

Armbian build instructions

---

contrib/pylightning/lightning/lightning.py
lightningd/chaintopology.c

`getinfo` has been providing the blockheight for a good while and doesn't
require the `DEVELOPER=1` flag during compilation, so it should be the preferred
method to retrieve the blockchain height.
I also think we don't need to go through the deprecation since this was a dev-only RPC call.

jsonrpc: Remove `dev-blockheight` in favor of `getinfo`

---

tools/check-includes.sh

```
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.5.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
In tools/check-includes.sh line 14:
if [[ $(grep -cE "^#((ifndef|define) ${HEADER_ID}|endif /\* ${HEADER_ID} \*/)$" "${HEADER_FILE}") != 3 ]]; then
^-- SC1117: Backslash is literal in "\*". Prefer explicit escaping: "\\*".
In tools/check-includes.sh line 28:
git ls-files | grep -v 'ccan/' | grep -E "\.${1}"'$'
^-- SC1117: Backslash is literal in "\.". Prefer explicit escaping: "\\.".
```

tools/check-includes.sh: shellcheck recommended fixes

---

cli/lightning-cli.c

Lift it to the start of main, so that it can short-circuit the lightningd
connection. It does not need to be running for this to work.
example:
lightning-cli help pay
lightning-cli help cli

cli: launch a manpage when help is passed an argument

---

lightningd/params.h
lightningd/test/run-params.c

typesafe_cb isn't suitable here, as it is simply a conditional cast,
and the result is passed through '...' and doesn't matter.
Reported-by: @wythe

lightningd/params: fix typesafe check.

---

channeld/channel.c
channeld/channeld_htlc.h
channeld/full_channel.c
channeld/full_channel.h
channeld/test/run-full_channel.c
common/htlc_wire.c
common/htlc_wire.h
lightningd/peer_htlcs.c

==1224== Uninitialised byte(s) found during client check request
==1224==    at 0x152CAD: memcheck_ (mem.h:247)
==1224==    by 0x152D18: towire (towire.c:17)
==1224==    by 0x152DA1: towire_u16 (towire.c:28)
==1224==    by 0x142189: towire_failed_htlc (htlc_wire.c:29)
==1224==    by 0x16343F: towire_channel_init (gen_channel_wire.c:596)
==1224==    by 0x115C2C: peer_start_channeld (channel_control.c:249)
==1224==    by 0x131701: peer_connected (peer_control.c:503)
==1224==    by 0x117820: gossip_msg (gossip_control.c:182)
==1224==    by 0x139D97: sd_msg_read (subd.c:500)
==1224==    by 0x139676: read_fds (subd.c:327)
==1224==    by 0x179D52: next_plan (io.c:59)
==1224==    by 0x17A84F: do_plan (io.c:387)
==1224==  Address 0x1ffefffabe is on thread 1's stack
==1224==  in frame #2, created …

lightningd: don't send uninialized malformed fields to channeld.

---

README.md

The README currently says the docker-compose file will "expose litecoin's rpc interface on default ports 18332". This is confusing because I don't see litecoin being used anywhere.
It looks like 18332 is the default RPC port for bitcoind on testnet.

README.md: 18332 is default bitcoind rpc port for testnet.

---

gossipd/gossip.c

PR #1618 in parallel with the migration to macro `structeq` created this.
Fixes #1674

gossip: Fix concurrent PR merge issue with structeq

---

lightningd/params.h

Fixes #1668
Making the explicit cast to `size_t` fixes the issue. I'm not sure exactly what the architectural difference is. The type sizes seem to all be the same as my desktop.  However he is using gcc 7.3 and I'm using 7.2.

params: Fix arg size

---

lightningd/params.c
lightningd/params.h
lightningd/test/run-params.c

This is a cosmetic change only. No functional changes.
I shortened the names of macros and changed param_parse() to param().
Also went through params.h with a fine-toothed comb and updated the comments
to reflect the current API.
I wanted to change the files:
params.c -> param.c
params.h -> param.h
run-params.c -> run->param.c
but that confused `git diff` for params.h so its best left for another PR.
I'm keeping #1682 updated locally with all these changes.

params: shortened names

---

lightningd/chaintopology.c
lightningd/chaintopology.h

- fixes problem with polling interval > 150 * 0.9
- fixes log message `feerate hit floor` at every feerate change
- smoothed fee now reaches 90% of (exp weighted) fee estimates polled in last
120s, independent of polling interval
- only apply smoothing when effect > 10 percent so it doesn't correct forever
- fix indentation
NOTE: Currently when starting a node, the first fee estimate always is `default_fee_rate = 40000`. So it takes about 4min for smoothed fee to reach _normal_ values, see #1698. Not sure if that is a problem.

improves exponential smoothing of feerate estimates

---

contrib/pylightning/lightning/lightning.py

pylightning: incorrect description for disconnect() method

---

tests/test_lightningd.py

The bad gossip order bug is going to take a while to fix; see #1706

pytest: mark test_reconnect_normal flaky for now.

---

tests/utils.py

I could not figure out why test_announce_address suddenly stopped working:
I had previously been using DEVELOPER=1 on the cmdline for historical
reasons when testing locally.

pytest: make utils.py read config.vars.

---

lightningd/chaintopology.c

I am trying to build the master branch with clang 3.8.0 on Ubuntu 16.04 and I am having a compile error.
This error does not occur with gcc 5.4.0.
> make CC=clang
> clang -DBINTOPKGLIBEXECDIR='"'../libexec/c-lightning'"' -Werror -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -std=gnu11 -g -fstack-protector -I ccan -I external/libsodium/src/libsodium/include -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbase58/ -I external/libbacktrace/ -I external/libbacktrace-build -I . -I/usr/local/include    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DBINTOPKGLIBEXECDIR='"'../libexec/c-lightning'"'  -c -o lightningd/chaintopology.o lightningd/chaintopology.c
> …

fix: compile error with clang

---

lightningd/param.h

I am trying to build the master branch with clang 3.8.0(not gcc) on Ubuntu 16.04.
lightningd crashs on rpc.invoice.
There is type mismatch of variable argument.
```
./configure 
make NO_VALGRIND=1 CC=clang
PYTHONPATH=contrib/pylightning:$PYTHONPATH DEVELOPER=0 VALGRIND=0 pytest tests/test_lightningd.py::LightningDTests::test_invoice
```
and lightningd is crashed.
> +0.144888971 lightningd(22121):DEBUG: Connected json input
> +0.144913591 lightningd(22121):jcon fd 16:IO_IN: 7b226964223a20302c20226d6574686f64223a2022696e766f696365222c2022706172616d73223a207b226465736372697074696f6e223a2022646573637269
> +0.144920203 lightningd(22121):jcon fd 16:IO_IN: 7074696f6e222c20226c6162656c223a20226c6162656c222c2022657870697279223a202233373030222c20226d7361746f736869223a203132333030302c20
> …

lightningd: fix crash by rpc.invoice with clang

---

doc/lightning-withdraw.7
doc/lightning-withdraw.7.txt

The failure outcome of withdraw method mentioned channel not being funded - but it should refer to withdrawal transaction not being created.

Change withdrawal documentation failure outcome - referred to channel not transaction.

---

doc/lightning-newaddr.7
doc/lightning-newaddr.7.txt
wallet/walletrpc.c

#1729
Also:
The manpage did not specify the name of the named parameter (addresstype).
It does now.
Fixed manpage grammar errors.

Updated docs to reflect bech32 default

---

channeld/channel.c

We shouldn't unconditionally free msg in enqueue_peer_msg:
DEBUG: lightning_channeld-0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 chan #1: dev_disconnect: @WIRE_REVOKE_AND_ACK
BROKEN: lightning_channeld-0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 chan #1: FATAL SIGNAL 6 (version 8aae6a8)
...
BROKEN: lightning_channeld-0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 chan #1: backtrace: ccan/ccan/tal/tal.c:98 (call_error) 0x80855d1
BROKEN: lightning_channeld-0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 chan #1: backtrace: ccan/ccan/tal/tal.c:170 (check_bounds) 0x8085730
BROKEN: lightning_channeld-0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 chan #1: backtrace: ccan/ccan/tal/tal.c:181 …

channeld: fix dev_disconnect doublefree crash.

---

lightningd/jsonrpc.c
lightningd/lightningd.c
lightningd/lightningd.h
tests/test_rpc.py

This is the cause for #1737: some destructors need to be run in a DB transaction.
Fixes #1737

Separately shut down the JSON-RPC subsystem in a DB transaction

---

README.md

I was confused at first as to whether or not you can connect to a remote Bitcoin full node. This clarifies that you can in the README.

added (or remotely) to README

---

lightningd/chaintopology.c

More verbose log messages about feerate estimates, to make more clear what is happening

more descriptive log messages about feerate estimates

---

doc/lightning-pay.7
doc/lightning-pay.7.txt
lightningd/payalgo.c
wallet/invoices.h

Several users have noticed that they cannot pay satoshis.place or similar places
that have tiny payment amounts if they are not directly connected. This is due
to the forwarding fee dominating the transferred amount.
This commit adds a new option, exempting tiny fees (up to 5 satoshis by default)
from having to pass the maxfeepercent flag. While we could have told users to
tweak maxfeepercent I think it is usefull to have a default exemption.
Not sure about the name of the option just yet, the current naming is based on
exempting it from the check, which feels clunky. Maybe someone else has a
good idea?
Fixes #1746 
Ping @SerafinTech, @renepickhardt, @jonathancross

pay: Exempt a fee from the maxfeepercent rule it is still tiny

---

Makefile
channeld/full_channel.c
cli/lightning-cli.c
common/json_escaped.c
lightningd/bitcoind.c
lightningd/log.c
lightningd/memdump.c
tools/generate-wire.py

Use `snprintf(...)` instead of `sprintf(...)`.
Better safe than sorry.
Before:
```
$ git grep [^a-z/]sprintf -- "*.h" "*.c" | grep -v ccan/ | wc -l
11
$ git grep [^a-z/]snprintf -- "*.h" "*.c" | grep -v ccan/ | wc -l
5
```
After:
```
$ git grep [^a-z/]sprintf -- "*.h" "*.c" | grep -v ccan/ | wc -l
0
$ git grep [^a-z/]snprintf -- "*.h" "*.c" | grep -v ccan/ | wc -l
16
```
**Note to reviewers**: The `snprintf` call in `common/json_escaped.c` is the only not using `sizeof(…)`.

Use snprintf(...) instead of sprintf(...)

---

README.md

docker-compose treats `command` field as args to `ENTRYPOINT` if `ENTRYPOINT` exists in Dockerfile.
And, [c-lightning's Dockerfile](https://github.com/ElementsProject/lightning/blob/master/Dockerfile#L103) contains `ENTRYPOINT`.
So, removed line causes `lightningd lightningd --bitcoin-rpcconnect=bitcoind ...` to be executed and lightningd returns an error
> lightningd: no arguments accepted

Fix example docker-compose.yml

---

CHANGELOG.md
wallet/invoices.c

@shesek pointed out that listing a specific invoices would contain the description, but iterating over all invoices would not include them. Looks like we were not retrieving the description in the iteration.

wallet: Add missing description field to the invoices iteration

---

Makefile
channeld/channel.c
closingd/closing.c
common/crypto_sync.c
common/crypto_sync.h
common/memleak.c
common/peer_failed.c
common/peer_failed.h
common/read_peer_msg.c
common/read_peer_msg.h
common/utils.c
common/utils.h
connectd/Makefile
connectd/connect.c
gossipd/Makefile
lightningd/channel.c
lightningd/channel_control.c
lightningd/lightningd.c
lightningd/opening_control.c
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/subd.c
openingd/opening.c

These are accumulated cleanups I did on the way to changing openingd to take care of a peer before either side opens a channel.
The main change is to tear apart read_peer_msg() which was trying to handle too much (and it gets even worse after openingd changes to not fail the peer on non-catastrophic error).

Pre openingd enhance cleanups

---

CHANGELOG.md
channeld/channel.c
gossipd/gossip_wire.csv
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c

So far we were ignoring the channel capacity and the self-declared `htlc_minimum_msat`. This PR changes that, returning fewer results when looking for a route, and reducing the number of failed attempts.

Consider channel parameters before selecting for a route

---

cli/lightning-cli.c

I got a user report with a strange error like this:
lightning-cli invoice msatoshi="any" label="" description=""
{ "code" : -32602, "message" : "Missing 'description' parameter" }
It turns out that
* The shell translates foo="" into an argv element "foo="
* lightning-cli correctly sees a parameter with name "foo" and value ""
* lightning-cli then incorrectly considers "" to be a literal value, because it consists entirely of decimal characters
* lightning-cli then does *not* put quotes around the empty string, which messes up the JSON-formatted command
This patch fixes this behavior by always considering empty values to be strings (which are then quoted in the JSON command).

lightning-cli: consider empty inputs to be strings

---

CHANGELOG.md
contrib/pylightning/lightning/lightning.py

They're much more useful being programatically-accessible, AFAICT.
The string stays the same so they're backwards compatible.

pylightning: add method and payload as proper fields.

---

tests/test_gossip.py

Saw this in Travis: technically we return from the dev_set_max_scids...
cmd after sending it to gossipd, but we should wait for it to log.
Adding an internal reply message for a dev command seems overkill.

pytest: fix flaky test.

---

tests/utils.py

This explains the very-very occasional issue we had parsing (hence the
random-looking fixes!).  The decoderawtransaction heuristic sometimes
thinks it's a zero-input tx, not a segwit tx.  Setting 'iswitness' to
true makes it reliable.
Here's the example I finally caught:
```
rusty$ bitcoin-cli decoderawtransaction  0200000000010180f80017ceb208d84cd5be0d4e21c1acb91798c55ada6541f7633a2739453b4e0100000000ffffffff0269300f0000000000160014774b1c651a1b409213057783547e2bd37a71731240420f00000000002200205f743123f9584a76058bac1142ec2bc6c60b4b2af1d3145e74418d41ae51009e02483045022100ba65a905cf4ebbb9728dc682fcf17cb73ade0ca224729a1878f689a8afa9a49e02206f323f224c5171d170aafb8ff57e2761411a27dea304ac8f9a3663c456d21f3e012102225ce166e84b3833d9f620863b4e713099de616f559e8768f44ff674054bb07d00000000
{
"txid": …
```

pytest: hand 'True' to decoderawtransaction so it doesn't get confused.

---

README.md

The docker-compose file didn’t expose the bitcoind and lightningd ports. Other nodes are not able to connect to nodes set up with the previous docker-compose script.

Fix readme docker-compose port setting

---

.travis.yml

Somewhere along the way we renamed `CC` to `COMPILER`, which effectively disabled the `clang` config on travis when we switched to `./configure`. This just re-enables `clang`

travis: Actually build with clang if we want to

---

lightningd/param.c
lightningd/param.h
lightningd/test/run-param.c

This adds and tests two new macros; `p_req_tal()` and `p_opt_tal()`. They support
callbacks that take a ~~`tal_t *`~~ `struct command *`  context.  Example:
static char *json_tok_label_x(struct command *cmd,
const char *buffer,
const jsmntok_t *tok,
struct json_escaped **label)
The above is taken from the run-param unit test (near the bottom of the diff).
On success, `*label` is allocated and initialized, and NULL is returned. On failure, an error string
is returned.
`param()` will take care of calling `command_fail` with the error message.
We can pretty much remove all remaining usage of `json_tok_tok` in the codebase
with this type of callback.
The question remains: Should we convert all existing `json_tok_X()` functions to
this new form or leave them alone?

Enhanced param parsing

---

Dockerfile

Some firewalls may block port 11371.

Use port 80 instead of 11371 for accessing the keyserver.

---

contrib/init/lightningd.service

Similar to init/bitcoind.service, this patch
includes an initial lightningd.service.

contrib: add init file for systemd

---

lightningd/options.c

When `./lightningd --help` is called, show for which network the default values are shown. 
Before this PR, user had to scroll down to find out that `testnet` is the default network for which default value are shown.

in ./lightningd --help, tell for which network the default values are shown

---

lightningd/chaintopology.c

To remove  _fee estimation_ log messages in certain cases:
- Disable fee estimation (loop) completely when `--dev-override-fee-rates` is used
- Because fee estimates is not needed when overridden
- Fixes #1806

do not start fee estimation with option: --dev-override-fee-rates

---

gossipd/gossip.c
tests/test_misc.py

ping_req() should be outside of DEVELOPER guard now.
#1811 has omitted this.

Fix DEVELOPER guard for ping

---

tools/refresh-submodules.sh

Hi,
i built c-lighning on OpenBSD-current today and run into a problem with the use of the non-standard `mv -n` flag in `refresh-submodules.sh`.
The FreeBSD man page says that this flag should be avoided in scripts if possible.
See https://man.openbsd.org/FreeBSD-11.1/mv#COMPATIBILITY.
This PR replaces the use of `mv -n`. Now we first test if the file is there. If it is, we exit. If it is not we write the current PID to it.
Cheers,
Fabian

replace use of non standard mv -n flag

---

tests/test_connection.py

In one case, the channel_update which we expected to activate the channel
from l2 was suppressed as redundant.  This is certainly valid, so just
check the results.

pytest: fix flakiness in test_channel_reenable.

---

lightningd/chaintopology.c
lightningd/onchain_control.c
lightningd/peer_control.c
lightningd/watch.c
lightningd/watch.h
tests/test_closing.py
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

Came across this bug while completing the implementation of option_dataloss_protect.
I think this shows fairly nicely that we should be using BIP32 for the to-remote outputs in a future version of the spec.  We'd still need a different base for the output, but it'd be far simpler.

Fix confirmation of to-us outputs on reorganization or restart.

---

lightningd/chaintopology.c

We only did this when we were first creating a wallet, or when we
asked for a relative rescan, not in the normal case!
Fixes: #1843

chaintopology: always cap max block to bitcoind's block height.

---

Dockerfile

This was suggested via mail: the SHA256 sums should be extracted from the
sha256sums file we are checking against, which also allows us to switch bitcoind
version at build time.
Suggested-by: Giles Hall <@vishnubob>
Signed-off-by: Christian Decker <@cdecker>

docker: Make the bitcoind version configurable at build time

---

CHANGELOG.md
doc/lightningd-config.5
doc/lightningd-config.5.txt
lightningd/log.c
tests/test_misc.py

This is based on ~~~#1846~~~ #1863 because I needed the start flag to get_node(), but it's basically the last two commits.

Support log rotation, don't append crash.log files but use per-peer.

---

hsmd/hsm.c

We can otherwise deadlock against lightningd which also talks to us sync.
Fixes: #1759

hsmd: use async for status reporting.

---

lightningd/peer_htlcs.c

We can close a connection with a peer to timeout an HTLC, but
we need to clear the pointer otherwise next time we try, we'll
free an expired pointer:
```
lightningd: Fatal signal 6 (version v0.6-336-gfcd1eb5-modded)
0x13ce86 crashdump
common/daemon.c:37
0x5739f1f ???
???:0
0x5739e97 ???
???:0
0x573b800 ???
???:0
0x1850c3 call_error
ccan/ccan/tal/tal.c:93
0x18528b check_bounds
ccan/ccan/tal/tal.c:165
0x1852ca to_tal_hdr
ccan/ccan/tal/tal.c:174
0x185bfb tal_free
ccan/ccan/tal/tal.c:472
0x1343a8 peer_sending_commitsig
lightningd/peer_htlcs.c:1035
0x114f25 channel_msg
lightningd/channel_control.c:159
0x13756b sd_msg_read
lightningd/subd.c:474
0x177c1f next_plan
ccan/ccan/io/io.c:59
0x178717 do_plan
ccan/ccan/io/io.c:387
0x178755 io_ready
ccan/ccan/io/io.c:397
0x17a336 io_loop …
```

lightningd: fix double-free on multiple HTLC timeouts.

---

contrib/pylightning/lightning/lightning.py
lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/channel_control.c
lightningd/closing_control.c
lightningd/onchain_control.c
lightningd/opening_control.c
lightningd/options.c
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h
tests/test_closing.py
tests/test_connection.py
tests/test_misc.py
tests/test_pay.py
wallet/test/run-wallet.c
wallet/walletrpc.c

This is based on #1863 and #1861 (merged)
It's the basically the middle part of #1846 .
Things this fixes:
1.  There was a window on startup where we'd use default feerate. Instead, we wait.
2.  We did not correctly update fees when restarting, or if they changed before funding tx locked in.
3.  If we couldn't get a fee estimate on startup, we put zeroes into the averager, which meant when bitcoind started giving estimates, we'd be low for quite a while.
4.  Since we hid the default feerate in the estimator, callers couldn't know when it was being used.
In practice, they either have other sources to estimate feerate (existing tx), or should refuse
(opening channels, withdrawing funds).

Never guess feerate

---

contrib/pylightning/lightning/lightning.py

No semantical change but when using the python lib for the rpc-api it is confusing that my developing environment suggests that I should fund a channel and pass a channel_id when in fact I want to pass a node_id

channel_id unknown at funding time. Needs to be node_id

---

lightningd/lightningd.c

lightningd: clean up tmpctx on exit before freeing ld.

---

Makefile

This is part of our new "Python programmers are people too" policy.

TAGS: add python files.

---

devtools/.gitignore
devtools/Makefile
devtools/dump-gossipstore.c
gossipd/gossip_store.c
gossipd/gossip_store.h

Not very useful by itself, but when combined with decodemsg it can tell us quite a bit.
I also noticed that my mainnet node is compacting the store every hour.  I think we should increase the compaction threshold significantly; say from 1.25 to 10?  Or maybe this needs to be combined with something more clever, like deleting by flipping the type of the gossip_store_channel_announce in-place to something else, so we can ignore it on read and don't do extra work setting it up then tearing it down?

devtools: dump-gossipstore.

---

common/json.c
common/json.h
common/json_escaped.c
common/json_escaped.h
lightningd/connect_control.c
lightningd/gossip_control.c
lightningd/invoice.c
lightningd/json.c
lightningd/json.h
lightningd/param.c
lightningd/param.h
lightningd/pay.c
lightningd/payalgo.c
lightningd/test/run-param.c

Although quite a few commits, each one is independent and straightforward.
I replaced most of the uses of `json_tok_tok`.  The remaining ones would require a bit more thought and are best saved for later.
But yes, we now have `json_tok_string` (and `json_tok_escaped_string`).

The Great Param Cleanup

---

lightningd/chaintopology.c

This was found because it means we have a non-zero feerate without
filling in the history of that feerate:
==15895== Conditional jump or move depends on uninitialised value(s)
==15895==    at 0x408699: feerate_max (chaintopology.c:828)
==15895==    by 0x41BE49: peer_start_openingd (opening_control.c:733)
==15895==    by 0x425FE9: peer_connected (peer_control.c:515)
==15895==    by 0x40CB8F: connectd_msg (connect_control.c:304)
==15895==    by 0x42DB4E: sd_msg_read (subd.c:475)
==15895==    by 0x42D499: read_fds (subd.c:302)
==15895==    by 0x46EB18: next_plan (io.c:59)
==15895==    by 0x46F5E9: do_plan (io.c:387)
==15895==    by 0x46F627: io_ready (io.c:397)
==15895==    by 0x471187: io_loop (poll.c:310)
==15895==    by 0x41683D: main (lightningd.c:732)

chaintopology: don't "fix" unknown feerate against known one.

---

Makefile
configure

Running `make pytest` when pytest is not installed, results in a message instructing the user to install it using `pip3`.
However, after installing it using `pip3`, `configure` still can't find it.
This PR addresses this issue by letting `configure` find if the module is accessible to `python3` and setting the command as `python3 -m pytest`.

pytest: Fix configure to find pytest when installed using pip3.

---

doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt
doc/lightning-listfunds.7
doc/lightning-listfunds.7.txt
doc/lightning-pay.7
doc/lightning-pay.7.txt
doc/lightning-waitinvoice.7
doc/lightning-waitinvoice.7.txt
doc/lightningd-config.5
doc/lightningd-config.5.txt

While working on the rust bindings I noticed some English spelling errors in the doc, so I've done an `aspell` run.
Second commit regenerates the man-pages from the source files.

Doc spelling corrections

---

lightningd/ping.c

The first argument of 'ping' was documented as 'peerid', however internally it is expected to be just 'id'.
To avoid breaking the API, opt to fix the documentation.

ping: First parameter is called 'id' not 'peerid', fix help

---

README.md

Added "`AWAITING_UNILATERAL` means that we're waiting for a unilateral close to hit the blockchain." to Readme.

Update Readme to include new channel state AWAITING_UNILATERAL

---

Makefile
contrib/Dockerfile.builder
contrib/Dockerfile.builder.i386
tests/btcproxy.py
tests/fixtures.py
tests/requirements.txt
tests/test_connection.py
tests/test_misc.py
tests/utils.py

Replace the fake-bitcoin-cli with a proxy that can be instrumented from tests

---

doc/lightning-getroute.7
doc/lightning-getroute.7.txt
doc/lightning-listfunds.7
lightningd/gossip_control.c
lightningd/json.c
lightningd/test/run-param.c

The `json_tok_percentage` parser is used for the `fuzzpercent` in `getroute` and
`maxfeepercent` in `pay`. In both cases it seems reasonable to allow values
larger than 100%. This has bitten users in the past when they transferred single
satoshis to things like satoshis.place over a route longer than 2 hops.
Fixes #1914

Remove 100% upper limit for percentage arguments

---

openingd/openingd.c

openingd: prioritize incoming peer traffic over handling (and sendind out) gossip
- reduces probability for a deadlock where we block on sending data because
the other peer cannot receive because it blocks on sending data etc.
- when either side sends so much data that it fills up the kernel/network buffer
- however sending out gossip can still block when (malicious) peer never receives
Fixes #1943 
thanks to the advice of @rustyrussell

Openingd: prioritize incoming peer traffic over sending out gossip

---

common/wireaddr.c

this enables addr like --addr=autotor:127.0.0.1 or
--addr=autotor:localhost to just use the default tor service port
fixes: #1938
Signed-off-by: Saibato <Saibato.naga@pm.me>

parse autotor: address before separate_address_and_port

---

tests/btcproxy.py
tests/utils.py

Got a spurious failure in test_no_fee_estimate; we fired too soon from the logs (presumably
we raced in on the first response, but estimatesmartfee gets called 3 times).

pytest: wait until mock is called for set_feerates.

---

doc/HACKING.md

Otherwise you won't run `check-source` and your Travis build will
fail on you.
Also remove comment about how it's currently disabled cuz that's a lie.

HACKING.md: Update rec'd test cmd to `full-check`

---

CHANGELOG.md
Makefile
channeld/commit_tx.c
common/bolt11.c
common/initial_commit_tx.c
gossipd/gossipd.c
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
hsmd/hsmd.c
lightningd/gossip_control.c
lightningd/gossip_msg.c
lightningd/gossip_msg.h
openingd/openingd.c
tests/utils.py
wire/gen_peer_wire_csv
wire/test/run-peer-wire.c

Updates to BOLTs. Mostly copy changes, except for flag breakout in BOLT7.
BOLT 7's been [updated](https://github.com/lightningnetwork/lightning-rfc/commit/0891374d47ddffa64c5a2e6ad151247e3d6b7a59) to split the flags field in `channel_update`
into two: `channel_flags` and `message_flags`. This changeset does the
minimal necessary to get to building with the new flags.

BOLT updates, up to and incl split flags in `channel_update`

---

tests/test_closing.py
tests/utils.py

We extract the tx from the logs, and then we wait until that hits
the mempool.  This is more reliable than 'sendrawtx' in the logs,
which might catch a previous sendrawtx; it's also more explicit
that we expect that tx exactly.

pytest: more reliable onchain tests, ie. YA Travis Failure

---

Makefile

The code to regenerate the local BOLT copy was causing eternal rebuild.
So only build if it's wrong.

Makefile: don't rebuild all the time

---

tools/generate-wire.py

This looked like a mistake. Small grammar fix in wire gen tool.

tools/gen-wire: 3th -> 3rd

---

common/json.c
common/json.h
common/test/run-json.c

It turns out we were heavily relying on the fact that after each message from
the client there'd be a flush, and that there would not be anything after the
JSON object we read. This will no longer be the case once we start streaming
things or we are very quick in issuing the JSON-RPC requests.
This just takes one of the error paths (incomplete read) and makes it into a
successful path if we have indeed read a full root element.

json: Support streaming JSON messages

---

lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/memdump.c
lightningd/param.c
lightningd/test/run-param.c
tests/test_misc.py
wallet/walletrpc.c

The help command now adds command usage to its output.
Instead of seeing, for example:
decodepay
Decode {bolt11}, using {description} if necessary
we see:
decodepay bolt11 [description]
Decode {bolt11}, using {description} if necessary
Note: Removed discussion of `check` command.  It was removed and saved for later patch.
This patch is a big step toward allowing us to write tests that:
1. Verify the manpage SYNOPSIS is correct.
2. Exhaustively test the API.
The first three commits adds the infrastructure.  The approach I took
is to introduce different command modes.  And the behavior of `param()` changes based on the mode.
Inspired-By: discussions with @rustyrussell

Help usage

---

.gitignore

I wanted to add a couple recently created unit tests to the
.gitignore file, but instead I replaced all the names of tests with a simple
regex.
This works because git doesn't ignore files that are already in git. So
source and header file are safe.

git: ignore all current and future unit tests

---

.gitignore

Vim's c-tags file is all lowercase, unlike some other text editor's, which appears to be all caps.

git: ignore vim's c-tags 'tags' file

---

tests/test_misc.py

Travis failures:
valgrind: m_scheduler/sema.c:104 (vgModuleLocal_sema_down): Assertion 'sema->owner_lwpid != lwpid' failed.
host stacktrace:
==1296==    at 0x38083F48: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x38084064: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x380841F1: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x38135DAE: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x380D328D: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x3809A4AC: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x3809AE43: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==1296==    by 0x380988CF: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
sched status:
running_tid=0
Thread 1: status = …

pytest: don't test crashing under valgrind at all.

---

tests/benchmark.py
tests/requirements.txt

Back when we migrated to pure `py.test` based tests we broke some of the benchmarks.

pytest: Fix benchmarks after the fixture migration

---

Makefile
doc/HACKING.md
lightningd/jsonrpc.c

I finally figured out why `cppcheck` and `shellcheck` weren't working for me -- I didn't have them installed. :man_facepalming: 
This updates the notes in HACKING.md to include them as a part of the setup instructions for the test infrastructure.
Once they were running, `cppcheck` was failing because of a warning. This also adds a null pointer check to quiet down the warning so that the check will pass.

Make it more obvious that you need to install cppcheck + fix warning

---

devtools/gossipwith.c

It seems to be having a bit of trouble understanding the control flow to realize
it's not actually uninitialized.
Add an error handler after the switch in case we miss a real uninitialized error
in the future.

build: fix compile error on gcc ~7.3.0

---

Makefile

It looks like a printf was missing for the bolt-check error message

make: fix broken error message in bolt-check

---

CHANGELOG.md
Makefile
channeld/channeld.c
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/pay.c
lightningd/peer_htlcs.c
tests/test_connection.py
tests/test_invoices.py
tests/test_pay.py
tests/utils.py
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

Puzzled about two PR's, I wrote a stress test, which revealed a number of bugs, including those which caused the horrific issues #1960 and #1993.
It also triggers a yet-to-be-diagnosed occasional issue where we dislike the peer's option_dataloss_protect; I have temporarily disabled that check in order to resolve these more important issues, but am now chasing that one.
Fixes: #1960 
Fixes: #1993

Fixes for HTLC db issues

---

lightningd/bitcoind.c
tests/test_connection.py
tests/test_gossip.py
tests/test_misc.py
tests/utils.py

We seem to be getting some spurious Travis failures, but the logs are too long and Travis kills it.   Half the logs are bitcoin-cli messages, so let's only log those if a request takes a ridiculous period of time (10 seconds).  The other cause of log spam is the 600 times we try a command in wait_for(), so make that do exponential backoff; here that made basically no difference to the test time with -n10.

Reduce logging spam, especially when testing.

---

channeld/full_channel.c

Avoid applying the unary minus operator to an unsigned operand.
Rationale:
```
[cling]$ #include <stdint.h>
[cling]$ typedef uint64_t u64;
[cling]$ typedef int64_t s64;
[cling]$ u64 msatoshi = 5
(unsigned long) 5
[cling]$ -msatoshi
(unsigned long) 18446744073709551611
[cling]$ -(s64)msatoshi
(long) -5
```
Explicit is better than implicit – also when it comes to conversions :-)

Avoid applying the unary minus operator to an unsigned operand

---

lightningd/opening_control.c

With `fundchannel` command, check that the user-supplied feerate is not below `feerate_floor`. Otherwise we solely rely on the _receiver_ to do that check.
Fixes #1990
Note: if the _receiver_ allows feerates below `feerate_floor,` it is not [BOLT](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#the-open_channel-message) compliant.
> The receiving node MUST fail the channel if:
> ..
>    it considers feerate_per_kw too small for timely processing or unreasonably large.
and
> The sending node SHOULD:
> ...
>    set feerate_per_kw to at least the rate it estimates would cause the transaction to be immediately included in a block.

lightningd: fail fundchannel command when feerate is below feerate_floor

---

lightningd/jsonrpc.c

It went something like:
@niftynei: Hey, cppcheck complains this might be NULL, so I put in a check.
@rustyrussell : cppcheck is dumb.  Make it an assert("Rusty always right!").
@niftynei: You seem certain of this so I shall do that.
https://github.com/ElementsProject/lightning/pull/1994
...
@renepickhardt: I asked fiatjaf to run `lightning-cli sendpay "[{'id':'02db8f487fcc0a'}]" 4efe0ba89b`  and his node crashed!
@rustyrussell: grep Assertion logs/*
`lightningd/jsonrpc.c:326: connection_complete_error: Assertion 'Rusty is always right!' failed.`
It turns out that in the 'can't parse' error case, we hand NULL cmd to connection_compete_error.
Next time, less asserting, more grepping!
(As see in #2010)

jsonrpc: fix crash on bad JSON input.

---

CHANGELOG.md
doc/lightningd-config.5
doc/lightningd-config.5.txt
lightningd/options.c

lightningd does not respect `lightning-dir` configuration option; always uses `$HOME/.lighting` instead
Set `lightning-dir` in user's `config` file
`lightningd/lightningd --conf=config`
Working directory is path set by `lightning-dir` in user's `config` file
`$HOME/.lightning` is always used
Right now, the `config` file is read *after* the configuration working directory is moved to in the software. However one configuration option `lightning-dir` settable in the `config` file sets this working directory. As the directory is already opened (which defaults to `$HOME/.lightning`) before the configuration is read, the configured directory will not be used.
This patch parses the configuration file before opening the working directory, fixing this bug.

options: Parse config file before opening working directory

---

channeld/channeld.c

LND does this, and we get upset with it.  I had assumed we would only
do this after funding_locked (since we don't consider the channel
shortid stable until that point), but TBH 6 confirms is probably
enough.
Fixes: #1985
Note that this is talked about in spec commit https://github.com/lightningnetwork/lightning-rfc/pull/474

channeld: allow WIRE_ANNOUNCEMENT_SIGNATURES before funding_locked.

---

CHANGELOG.md
tests/benchmark.py
tests/test_pay.py
wallet/wallet.c

Turns out we weren't really loading channel stats, instead returning only 0 for all stats. Probably this is why people assumed their nodes were not forwarding anything and were surprised when the balances changed without any apparent forwarding.

Fix channel stats

---

gossipd/gossip_wire.csv
gossipd/gossipd.c
lightningd/gossip_control.c
lightningd/lightningd.h
lightningd/options.c
lightningd/peer_htlcs.c
tests/test_invoices.py
wallet/test/run-wallet.c

More side-effects of writing documentation and re-reading the code:
1. Don't leak private channels in routeboost.
2. Don't accept non-local short-channel-ids when forwarding.
3. Clarify the gossip timer expiry setting.

gossipd: minor fixes.

---

Dockerfile
README.md
contrib/Dockerfile.builder
contrib/Dockerfile.builder.fedora
contrib/Dockerfile.builder.i386

While not strictly necessary it's certainly a good idea to test
against the latest one and not encourage users to use old versions.
Doesn't seem big enough of a change to note in the changelog.
Fixes #2020

docker: Update docker images and docs to non-CVE-2018-17144 bitcoind

---

channeld/channeld.c
common/initial_channel.h
gossipd/gossip_wire.csv
gossipd/gossipd.c
hsmd/hsmd.c
tests/test_pay.py

Have c-lightning nodes advertise their `htlc_maximum_msat` value, to help other nodes make intelligent routing decisions. As written, this potentially leaks the joint channel reserve amount. Is this ok?
Also, the function definition for `htlc_maximum_msat()` is in a sort of weird place. It doesn't really pertain to the `initial_channel` flow, but it *is* right next to the function for `htlc_minimum_msat()`...
Todo: still needs tests. There didn't seem to be much ready infrastructure for manipulating the `max_inflight_htlc` (ie it's not currently configurable)

Send max msat field in `channel_update`

---

common/bolt11.c

Give a clear error at the beginning if it's not bolt11 payment,
rather than falling foul of other checks.
This will work at least until some altcoin adapts the 'ln' prefix :)

bolt11: better message when you try to 'lightning-cli pay' an onchain addr

---

CHANGELOG.md
contrib/pylightning/lightning/lightning.py
lightningd/jsonrpc.c
lightningd/peer_htlcs.c
tests/test_pay.py
tests/utils.py
wallet/db.c
wallet/wallet.c
wallet/wallet.h

New attempt at tracking fees. This supersedes #2018, and tries to things a bit differently: we use a separate table to track forwarded payments individually and add a new `listforwardings` JSON-RPC command that lists them, as well as spitting out some overall statistics.
Not so sure about the name `forwardings`, maybe @rustyrussell or @niftynei have a better idea? Alternatives include `forwards`, `routedpayments`, `forwardedpayments`, ... but I'd like to stick with a single word, instead of tacking `payments` at the end.
The table persists its entries even after the HTLC or the channel has been deleted, in order to avoid bumpy stats.
Closes #2018

Fee tracking2

---

CHANGELOG.md
channeld/commit_tx.c
channeld/commit_tx.h
common/close_tx.c
common/funding_tx.c
common/initial_commit_tx.c
common/permute_tx.c
common/permute_tx.h
common/withdraw_tx.c
lightningd/htlc_end.c
lightningd/onchain_control.c
lightningd/options.c
lightningd/payalgo.c
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h
onchaind/onchain_wire.c
onchaind/onchain_wire.h
onchaind/onchaind.c
tests/test_closing.py
tests/test_misc.py
tests/test_pay.py
tools/check-spelling.sh
wallet/wallet.c

First, make sure we spell it correctly! Then, fix channeld's HTLC signature confusion (thanks to lightningnetwork/lightning-rfc#491). Then, fix onchaind's HTLC confusion.
This is all due to a great bug report by molz on #c-lightning on Freenode, who reported that this fixed his issue.

WIP: Deal with confusion with HTLCs with same preimage, esp. different CLTVs.

---

tests/utils.py

Occasional failure in test_fulfill_incoming_first where the channel
closed before the final message from dev_disonnect was read.  Cause
was the peer writing a gossip msg and failing due to ECONNRESET, before
it read the final message.
(Managed to reproduce under strace -f, FTW).
This is really a symptom of the fact that line_graph's announce=True
didn't wait for node announcements.  Let's do that.

pytest: make sure we wait for node announcements in line_graph too.

---

lightningd/peer_control.c

Fixes: #2056
(Another Rusty mistake, I'm thinking about how to detect these...)

lightningd: fix crash on failed close.

---

Makefile
common/wireaddr.c
common/wireaddr.h
connectd/connectd.c
connectd/netaddress.c
devtools/gossipwith.c
gossipd/routing.c
lightningd/json.c
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/peer_htlcs.c
wallet/test/run-wallet.c
wallet/wallet.c
wire/gen_onion_wire_csv

The only change is that the final_incorrect_htlc_amount field is now 64
bit.  Since no implementation yet parses that field, we just updated it
quietly in the spec.

WIP: Update for latest bolt version: bca814e270dcbee2fea51c0a26ca99efef261f2b

---

closingd/closing_wire.csv
closingd/closingd.c
lightningd/closing_control.c

The spec says so, and it's right: with the right pattern of packet loss
(thanks Travis!) the other end can still be in channeld, waiting for our
`shutdown` message.

closingd: retransmit `shutdown` on reconnect.

---

CHANGELOG.md
common/bech32.c
common/bolt11.c
common/test/run-bolt11.c

That time Pieter Wuille tested us all and we failed him

---

ccan/README
ccan/ccan/opt/opt.c
ccan/ccan/opt/opt.h
ccan/ccan/opt/parse.c
ccan/ccan/opt/private.h
ccan/ccan/opt/test/run-early_incomplete.c
ccan/ccan/opt/test/utils.c
ccan/ccan/opt/test/utils.h
contrib/helloworld-plugin/main.py
doc/lightningd-config.5
doc/lightningd-config.5.txt
doc/plugins.md
gossipd/test/run-bench-find_route.c
gossipd/test/run-find_route-specific.c
gossipd/test/run-find_route.c
lightningd/Makefile
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
lightningd/options.h
lightningd/plugin.c
lightningd/plugin.h
lightningd/test/run-find_my_abspath.c

This is the first part of the plugin subsystem. It includes the following steps:
- Creates a sample plugin
- Adds the `--plugin` cli option to register a plugin
- Manages the plugin process
- Sets up connectivity over `stdin` and `stdout` with the plugin and adds processing and multiplexing of JSON-RPC commands (`lightningd` as client to the plugin)
- Splits the option parsing, asks plugins for any options they'd like to expose, and exposes them
- Collects options for plugins and then configures the plugin.
Still to be done:

The endless plugin saga (Part 1)

---

README.md

The `GOSSIPING` state was removed some time ago: see [CHANGELOG](https://github.com/ElementsProject/lightning/blame/master/CHANGELOG.md#L133-L136)
I think it's confusing to keep it here since it's not an actual  internal state or text that can be returned from the RPC.

[doc] Remove old GOSSIPING state from README

---

CHANGELOG.md
lightningd/Makefile
lightningd/connect_control.c
lightningd/json.c
lightningd/json.h
lightningd/json_stream.c
lightningd/json_stream.h
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/test/run-invoice-select-inchan.c
lightningd/test/run-jsonrpc.c
lightningd/test/run-param.c
tests/test_misc.py
wallet/test/run-wallet.c

(On top of #2081)
This also opens the door to notifications, AFAICT.

Restore multiplexed JSONRPC command support

---

CHANGELOG.md
common/bolt11.c
tests/test_pay.py

The Blockstream store produces these, for example, so let's ignore them.

bolt11: accept lightning: prefix.

---

channeld/test/run-full_channel.c
common/daemon.c
common/key_derive.c
common/test/run-bolt11.c
common/test/run-derive_basepoints.c
common/test/run-features.c
wallet/test/run-wallet.c

You may want to do something else with wally_init, but skipping the wasted hash seems like a no-brainer.

(Trivial) Wally updates

---

CHANGELOG.md
channeld/channeld.c

As long as they don't try to send commitment_signed, it's OK.  Just a bit
weird.
Closes: #2100

channeld: accept update_fee before funding_locked.

---

common/daemon.c

FIx build error on Mac OS:
```
common/daemon.c:101:13: error: function 'add_steal_notifiers' is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]
```

enable add_steal_notifiers only support backtrace library

---

.clang-format
.github/CODEOWNERS
tests/test_closing.py
tests/test_misc.py
tests/utils.py

- Adds `.clang-format` matching our own formatting rules as closely as I could get it
- Adds codeowners so PRs get assigned reviewers automatically
- Pretty printing of memleak output so we can read it a bit better
- `test_reserve_enforcement` is flaky/leaky
- One test no longer requires `DEVELOPER=1`

Minor cleanups

---

lightningd/plugin.c

Fix build error on MacOS:
```
lightningd/plugin.c:111:2: error: implicit declaration of function 'kill' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
kill(plugin->pid, SIGKILL);
^
```

add needed include file

---

contrib/plugins/helloworld.py
doc/plugins.md
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/jsonrpc_errors.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/plugin.c
lightningd/plugin.h
lightningd/test/run-find_my_abspath.c
tests/test_plugin.py

This is the second major plugin feature: plugins can register RPC methods with `lightningd`'s JSON-RPC interface, and calls to those methods will be transparently routed to the plugin.
The preparatory work requires wrapping the information related to the JSON-RPC in a new struct. This also gives us a clean root object for all related objects as well, which was so far done with the listener object. Furthermore the JSON-RPC instantiation and initialization (listening) was split so we can instantiate and add new methods before starting to listen, and the example plugin now handles exceptions and array-based as well as dict-based arguments correctly (I plan on formalizing this in a utility Plugin class for python plugins once we have plugin -> lightningd notifications for logging).

JSON-RPC passthrough for plugin (Endless plugin saga Part 2)

---

CHANGELOG.md
common/utils.c
common/utils.h
contrib/plugins/fail/failtimeout.py
lightningd/jsonrpc.c
lightningd/plugin.c
tests/test_plugin.py

- Changelog entry
- `tal_arr_remove`
- Timeout for `getmanifest` call
- Double free issue when killing a plugin.

plugin: Some cleanups that didn't make it into part 2 of the plugin saga

---

contrib/plugins/helloworld.py
lightningd/lightningd.c
lightningd/plugin.c
lightningd/plugin.h
lightningd/test/run-find_my_abspath.c

This tells the plugin both the `lightning-dir` as well as the
`rpc-filename` to use to talk to `lightningd`. Prior to this they'd
had to guess.
This was supposed to be in #2131, but I had it stashed and forgot about it :slightly_frowning_face:

plugin: Added .params.configuration to init call

---

CHANGELOG.md
channeld/channeld.c
contrib/pylightning/lightning/lightning.py
doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt
lightningd/opening_control.c
tests/benchmark.py
tests/test_closing.py
tests/test_connection.py
tests/test_gossip.py
tests/test_invoices.py
tests/test_pay.py
tests/utils.py

Allows users to create private channels, solves #2125

Private Channels

---

lightningd/lightningd.c

My 'pay' plugin failed because the socket didn't exist.  That's bad...

lightningd: only initialize plugins once we're ready for them to connect

---

contrib/pylightning/README.md

I found the script useful since it uses the [default socket](https://github.com/ElementsProject/lightning/blob/master/contrib/pylightning/lightning-pay#L15-L23) to setup the LightningRPC object, which I imagine other people will want to do when playing with the library.

[doc] Add lightning-pay script as example for pylightning

---

contrib/plugins/fail/failtimeout.py
contrib/plugins/helloworld.py

Fixes some lint errors with unused variables when running
make full-check:
contrib/plugins/fail/failtimeout.py:48:5:
F841 local variable 'e' is assigned to but never used
contrib/plugins/helloworld.py:86:5:
F841 local variable 'e' is assigned to but never used

python: fix lint errors in plugins

---

contrib/plugins/helloworld.py
lightningd/plugin.c
tests/test_plugin.py

Adds notification handling to `lightningd` so that we can start injecting logs into the main daemon output. Should make it easier to follow what happens in the plugins.

Make plugins more talkative (log notifications plugin->lightningd)

---

Makefile
lightningd/lightningd.c
tools/headerversions.c
wallet/db.c

@arowser 's #2158 PR drew my attention to this problem.  We have two other libraries for which this could be an issue, and generally static linking is a bad idea, as security updates are then omitted.
Unfortunately I can't find a statement on sqlite3's versioning which guarantees ABI compatibility across minor versions, so I'm reluctant to loosen the ABI check.  Though ubuntu obviously thought it ABI compatible...

Check system-provided library versions

---

tools/mockup.sh

This was introduced in ed268d6c, which broke the mocks
generation. This just filters out the invalid sentinel value.

mocks: Drop invalid __sentinel__ value in generated mocks

---

CHANGELOG.md
channeld/commit_tx.c
channeld/full_channel.c
channeld/test/run-commit_tx.c
common/initial_commit_tx.c
common/initial_commit_tx.h
lightningd/closing_control.c
tests/test_invoices.py
tests/test_pay.py

Funder can't spend the fee it needs to pay for the commitment transaction:
we were not converting to millisatoshis, however!
This breaks our routeboost test, which no longer has sufficient funds to make payment.

channeld: fix fee calculation.

---

contrib/plugins/helloworld.py
contrib/pylightning/lightning/__init__.py
contrib/pylightning/lightning/plugin.py
contrib/pylightning/tests/test_plugin.py
lightningd/plugin.c
tests/test_plugin.py

This framework is very much inspired by flask, in that I wanted to make it as trivial as possible to get started. I had to jump through some hoops but I'm rather happy with the end result. A plugin with an option and a RPC passthrough is as simple as this:
```python
from lightning import Plugin, monkey_patch
plugin = Plugin(autopatch=True)
@plugin.method("hello")
def hello(name, plugin):
"""Say hello"""
greeting = plugin.get_option('greeting')
plugin.log('{} {}'.format(greeting, name))
return s
plugin.add_option('greeting', 'Hello', 'The greeting I should use.')
plugin.run()
````
It has support for monkey-patching `stdout` and `stderr` by default so that if run by `lightningd` it'll automatically wrap anything written to those streams into log notifications that get displayed nicely. …

pylightning: Add a plugin framework

---

tools/mockup.sh

Turns out that I should have tested these with a new dependency
instead of just submitting. `sed` was missing the s command :slightly_frowning_face:

mocks: Fix the mocks generation fix

---

lightningd/plugin.c

Seems the context parameter got lost somewhere.
Partial fix for #2179

plugin: Add missing context to tal_fmt call on error message

---

Makefile
configure

As @NicolasDorier suggestion, in #2175,  add a optional static link for sqlite3, gmp, zlib, its useful in cross build to avoid rebuild these library in raspberry.

add optional static link options

---

lightningd/log.c

We need to set logging levels and prefix earlier, otherwise we miss log_debug() events.  But we should also replay any prior log messages when opening the log file.

Fix logging race

---

Makefile
configure

If no pytest in system:
1. The configure show importError, its better to hide this message.
```
./configure
File "<string>", line 1, in <module>
ImportError: No module named 'pytest'
```
2. configure print PYTEST is null.
```
Setting COMPAT... 1
Setting PYTEST... 
Setting STATIC... 0
```
So this PR hide the pytest check message, and set PYTEST var to 0 if not find pytest.

update pytest check when configure

---

lightningd/plugin.c

When issuing command `check PLUGIN_COMMAND` from the CLI or through RPC, the lightningd daemon crashes, using the helloworld example, PLUGIN_COMMAND would be "hello"

fix crash on check with plugin command

---

lightningd/lightningd.c

Addresses #2074.
I made`ld` a file global variable in order to do this. @rustyrussell already admitted it was "basically a global variable" in the comment below :-)
It seems the code really wants to exit via `io_break` so that's the approach I took.
I tried to just set a `bool` and exit the `main()` `for(;;)` loop by checking it.  But it was not very responsive and I got an error from `hsmd` with SIGINT.

Handle SIGTERM and SIGINT

---

CHANGELOG.md
cli/lightning-cli.c
lightningd/jsonrpc.c

Include the `jsonrpc` version on plugin commands that get called. (this was causing an error)

Add jsonrpc version to command calls 

---

contrib/pylightning/lightning/lightning.py

This was causing `listchannels` to be incredibly slow. The response is
several megabyte in size, and we were only buffering 1Kb on each
iteration.
We can be at most a factor of 2 away from what was actually needed, and it considerably reduces parse time.

pylightning: Increase buffer size for big JSON-RPC responses

---

tools/headerversions.c

`close` was implicitly defined, include `unistd.h` to define it explicitly so that the FreeBSD compile succeeds. Fixes the following error:
```
tools/headerversions.c:70:3: error: implicit declaration of function 'close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
close(fd);
^
tools/headerversions.c:70:3: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
2 errors generated.
```

tools: Add missing unistd.h header

---

contrib/plugins/helloworld.py
contrib/pylightning/lightning/plugin.py
doc/plugins.md
lightningd/Makefile
lightningd/json_stream.c
lightningd/json_stream.h
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/notification.c
lightningd/notification.h
lightningd/opening_control.c
lightningd/peer_control.c
lightningd/plugin.c
lightningd/plugin.h
lightningd/test/run-invoice-select-inchan.c
tests/test_plugin.py
tests/utils.py
wallet/test/run-wallet.c

We're nearing the end of the endless plugin saga, with this new feature. It allows plugins to subscribe to a number of notifications/events that will then be streamed from `lightningd` to the plugin when something happens.
Notice that, while this provides the infrastructure, I've only implemented two very simple notification topics (`connect` and `disconnect`). We can (and will) add more as we come up with new use-cases.

plugin: Add notifications from lightningd to plugins (Plugin Saga, 3rd reprise)

---

Makefile

Changed `Makefile` to check only once for `config.vars`, instead of twice.
Also changed the funny message about the 1990s to something more informative (the new message is quite boring though).
I think it fixes #2130.

Removed duplicate error message in build

---

contrib/plugins/helloworld.py

The example code had the `plugin` argument as the last argument. this disallows arguments that have a standard value. As far as I understand the dispatching code the order of arguments does not matter since it is the name `plugin` that is relevant. Therefor I changed the order so that newbe's don't have to read the entire code and can easily add optional arguments

[plugin] Improved the example code to encourage usage of optional arguments

---

lightningd/peer_htlcs.c

Seems like someone is sending out zero-cltv HTLCs, which is we weren't catching correctly, thus failing on a sanity check.

lightningd: don't allow zero cltv HTLCs.

---

contrib/linuxarm32v7.Dockerfile

Following discussion on https://github.com/ElementsProject/lightning/issues/2195#issuecomment-449435677
This is the direct application of the documentation update at https://github.com/ElementsProject/lightning/pull/2175 by @arowser .
I called the file `linuxarm32v7.Dockerfile` instead of `Dockerfile.linuxarm32v7` because most IDE infers the syntax colorization based on the extension of the file.
Once merged, I will do a follow up pull request to setup CircleCI to build docker multi arch images on tagging.

Add dockerfile for cross compiling arm32v7 image

---

lightningd/lightningd.c

The processes that were used to test the subdaemon versions were not
reaped correctly keeping some resources bound.
Fixes #779
Fixes #978

init: Reap tested subdaemon processes to release OS resources

---

CHANGELOG.md
lightningd/peer_control.c
tests/test_connection.py

Reveal channel's 'privacy' in `listpeers` output
Suggested-By: @shesek

listpeers: include `private` field in `channels` output

---

contrib/pylightning/lightning/plugin.py
contrib/pylightning/lightning/test_plugin.py

If the `request` or `plugin` parameter that are injected by the
framework where before or inbetween positional arguments we'd be
injecting them incorrectly, i.e., we'd be providing them both as
`args` (and mismapping another argument) as well as `kwargs`.
This is a better way to map arguments, which takes advantage of the
fact that JSON-RPC calls are either all positional or named arguments.
I also included a test for various scenarios, that hopefull cover the
most common cases.
Fixes #2217 
Reported-by: Rene Pickhardt <@renepickhardt>

pylightning: Better inject arguments in plugin method calls

---

CHANGELOG.md
Makefile
channeld/channeld.c
channeld/channeld_htlc.h
common/sphinx.c
common/sphinx.h
connectd/connectd.c
connectd/handshake.c
connectd/handshake.h
connectd/test/run-initiator-success.c
connectd/test/run-responder-success.c
devtools/Makefile
devtools/gossipwith.c
devtools/onion.c
hsmd/hsmd.c
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/pay.c
lightningd/peer_htlcs.c
tests/test_misc.py
wallet/test/run-wallet.c
wallet/wallet.c

I was writing a pay test when I got a non-decodable onion.  Turns out our handling of "update_fail_malformed_htlc" (where the next peer can't decrypt the onion) is completely wrong, and results in us packaging up incorrect data.  This is easy to duplicate by simply lying to 'sendpay' about what id the next hop is.
The resulting cleanups and fixes solve this.

Do not produce bad onions on malformed

---

doc/lightning-listpeers.7
doc/lightning-listpeers.7.txt

Adding description of `level` command line option for the `listpeers` command, since it was missing form the manpage

[docs] Add missing 'level' description for listpeers manpage.

---

CHANGELOG.md

eg. see https://github.com/ElementsProject/lightning/issues/2231

Release of 0.6.3-rc1: hastened by 0-HTLC crash reports.

---

Makefile

git is needed to generate version information
Add a sanity check so that the build doesn't continue with an empty VERSION. This
is useful for sandboxed build where we might have forgot to include git.
Fixes #2238

make: fail build if git isn't present

---

CHANGELOG.md
configure
doc/plugins.md
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
tests/fixtures.py
tests/test_plugin.py
tests/utils.py

[ Actual work done by Christian, I just made it a new configure flag and tweaked docs --RR]
Since we are planning to release a bug fix release, and the plugin
subsystem is not yet complete, it is better to make plugin support
opt-in while we continue testing.

plugin: Gate the plugin subsystem with the --enable-plugins configure flag

---

contrib/pylightning/lightning/plugin.py

after this code change people can use `plugin.rpc_interface()` from anywhere in their plugin code this is much nicer than going this way within the init function (or somewhere else):
```
@plugin.method("init")
def init(options, configuration, plugin):
global rpc_interface
basedir = plugin.lightning_dir 
rpc_filename = plugin.rpc_filename 
path = join(basedir, rpc_filename)
rpc_interface = LightningRpc(path)
```
or similarly that way: 
```
@plugin.method("init")
def init(options, configuration, plugin):
global rpc_interface
basedir = configuration['lightning-dir']
rpc_filename = configuration['rpc-file']
path = join(basedir, rpc_filename)
rpc_interface = LightningRpc(path)
```
also the imports have been sorted alphabetically

[plugin] Made rpc_interface a public member of Plugin class and sorted imports

---

CHANGELOG.md
bitcoin/short_channel_id.c
gossipd/test/run-find_route-specific.c
tests/test_closing.py
tests/test_connection.py
tests/test_gossip.py
tests/test_pay.py
tests/utils.py

Only the changes in `bitcoin/short_channel_id.c` are important, everything else is just test compat cleanup.
Fixes #2239

misc: Update short_channel_id representation to use 'x' separators

---

lightningd/bitcoind.c

It fixes a bad assumption in the code which consider error code  of `bitcoin-cli` different than 0 as a transient issue.
If `bitcoin-cli` returns 1, then [bcli_failure](https://github.com/ElementsProject/lightning/blob/7b7a1b70403009ca726645783bf2144fa275f4d8/lightningd/bitcoind.c#L133) get called, which will try again every second for 1 minute then crash the process.
So what happen on a pruned node?
A gossip come, then c-lightning try to check if the channel exists by fetching the block via `getblock`.
`bitcoin-cli`, not having the block, returns "block-not-found" but also the error code of `bitcoin-cli` is 1.
The caller's callback [process_block](https://github.com/ElementsProject/lightning/blob/7b7a1b70403009ca726645783bf2144fa275f4d8/lightningd/bitcoind.c#L607) expects to process the …

Do not consider bitcoin-cli as a failed call if it returns error code 1

---

CHANGELOG.md
lightningd/peer_control.c

A redo of #2207 
The point is the know the initial state of funding allocated to the channel by the funder / fundee. At the moment there are only one-sided channel opens, but dual-funded channels will be available in the near future :crossed_fingers: 
This change also implicitly let's you know who initiated the channel open, which was the original intent of #2207

[rpc] Add funding allocation map to listpeers command

---

common/json.c
common/json.h
common/param.c
common/test/run-json.c
common/test/run-param.c
lightningd/gossip_control.c
lightningd/invoice.c
lightningd/pay.c
plugins/pay.c

Built on top of #2215 simply because that's where @cdecker pointed out we weren't using tok->size for iteration and thus doing twice the work we needed to.
So just review the last 4 ("common/test/run-json: check tok->size is as expected" onwards)

Json tok speedup

---

contrib/plugins/fail/failtimeout.py
lightningd/plugin.c

Valgrind seems to be slowing the pay-plugin down enough for the 10
seconds timeout to get triggered on a semi-regular basis.
Reported-by: Rusty Russell <@rustyrussell>

plugin: Increase manifest timeout to 60 seconds

---

CHANGELOG.md
common/features.c
tests/test_connection.py

Just removed the bare minimum to get `option_data_loss_protect` to be enabled by default. 
@rustyrussell should I also remove the EXPERIMENTAL_FEATURES flag?

option_data_loss_protect: reenable by default

---

common/param.c
tests/test_plugin.py

Internally libplugin turns ' into ", which causes these messages to produce bad JSON.
The real fix is to remove the '->" convenience substitution and port the JSON creation APIs into common/ from lightningd/
Fixes #2278

libplugin: quick fix for bad JSON produced by plugins on bad paramters.

---

README.md

The previous faucets don't work and appear abandoned.
This is the only one I found that works  this morning.
Note: This faucet uses 40% of your CPU to mine monero!

docs: Changed testnet faucet

---

doc/lightning-getroute.7
doc/lightning-getroute.7.txt

The curly braces are causing missing text in the resulting man page.
I switched them to quotes and it works fine. This is somewhat more consistent
with our other man pages anyway.

docs: fix getroute manpage rendering

---

contrib/pylightning/lightning/plugin.py

Fix make check-python error:
```
contrib/pylightning/lightning/plugin.py:230:9: F841 local variable '_' is assigned to but never used
```

remove unused local var in plugin.py

---

common/jsonrpc_errors.h
doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt
lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/opening_control.c
tests/btcproxy.py
tests/test_connection.py

openingd/json_fund_channel:
- result fundchannel command now depends on successful or failed broadcast of the funding tx
- failure returns error code FUNDING_BROADCAST_FAIL
- don't fail the channel when broadcast failed, but keep in CHANNELD_AWAITING_LOCKIN
- after fixing the initial broadcast failure, the user could manually rebroadcast the tx and
keep the channel
openingd/opening_funder_finished:
- broadcast_tx callback function now handles both success and failure
jsonrpc: added error code FUNDING_BROADCAST_FAIL
manpage: added error code returned by fundchannel command
This makes the user more aware of broadcast failure, so it hopefully doesn't
try to broadcast new tx's that depend on its change_outputs. Some users have reported (see
issue #2171) a whole sequence of fundings failing, …

fundchannel command: return an error when broadcast fails

---

CHANGELOG.md
channeld/channeld.c
common/read_peer_msg.c

channeld: prioritize read from peer over write to peer
This solves (or at least reduces probability of) a deadlock in channeld
when there is lot of gossip traffic, see issue #2286. That issue is
almost identical to #1943 (deadlock in openingd) and so is the fix.
I did a simple test, monitoring socket traffic Recv-Q and Send-Q at 1 second interval, using `ss -4 -t -p | egrep "lightning|State"` during startup. The node has one channel with satoshisplace, so I don't know if this problem is specific to that node, but this solved the deadlock for me.
Result after this commit:
```
State   Recv-Q Send-Q Local Address:Port                 Peer Address:Port                
ESTAB 0 107 192.168.1.166:44902 88.98.213.235:9735 users:(("lightning_conne",pid=30591,fd=6))
ESTAB 0 106833 …
```

channeld: prioritize read from peer over write to peer

---

Makefile

Otherwise a straight "make install" gives:
install: cannot stat 'plugins/pay': No such file or directory
make: *** [Makefile:482: install-program] Error 1
Fixes: #2288

Makefile: fix make install to depend on plugins.

---

Makefile
configure

Currently only works with `gcc` due to google/sanitizers#1028, so
configure makes sure we warn if clang with ASAN is attempted.
According to [my benchmarks][benchmarks] the performance degradation
is small enough to have it active always.
Would be nice to eventually get `clang` working as well, since it has some additional sanitizers, such as the memory sanitizer which guards uninitialized values.
Fixes #2277 
[benchmarks]: https://github.com/ElementsProject/lightning/issues/2277#issuecomment-455897417

make: Add an option to compile with address sanitizer

---

wallet/wallet.c
wallet/walletrpc.c

Add the change output to owned_txfilter so its entry in db will
get a confirmation_height when detected in a block by filter_block_txs
before this commit, after a 'withdraw' command, 'listfunds' would
not show our change outputs as confirmed. This was mentioned in #2300 
Modified the log message in wallet_extract_owned_outputs to
append 'CONFIRMED' when it is called with a blockheight arg.
To make distinction between (1st call) when adding owned output to the
db and (2th call) when confirmed in block.

json_withdraw: fix change_outputs showing forever as unconfirmed in listfunds

---

.travis.yml
.travis/build.sh
Makefile

I decided to give a "bare-metal' Travis configuration another go, since I was expecting to gain some performance from not having to run on virtualized hardware, which is required to run `docker` with `sudo`. As a side-effect we also remove the need to run everything through the `docker run` key-hole.
The downside is that we lose the ability to compile for 32bit systems out of the box, but we may be able to regain that later via cross-compilation again.
The results of running `master` with `sudo` and `docker`, are compared with the `bare-metal` version in the table below:
| Job | Configuration                                                                                                | sudo+docker | baremetal          | savings   | …

travis: Attempt to setup travis without docker and without sudo

---

Dockerfile
contrib/linuxarm32v7.Dockerfile

This was failing the docker hub builds, since the git-config retains
an absolute path to the worktree location when cloning. Copying it
over from the host system means that this path now points to a
non-existent location, which then interfered with the submodule
initialization.
This fixes it by not using the copy directly, but rather it creates a
clean clone from the copied location, including a submodule init.
Fixes #2309

Fix docker image build from fresh clone

---

doc/INSTALL.md

Skip installing GUI dependencies and building bitcoin-qt.

doc: skip building bitcoin-qt on macOS

---

tests/test_gossip.py
tests/test_pay.py
tests/utils.py

It was waiting for a remote channel, but not for all the interesting
channels we want to check. It can sometimes happen that further away
channels are added before closer ones are added, depending on
propagation path, flush timers and bitcoind poll timers. This now just
checks for all channels, which also reduces the ambiguity of whether
we selected a path solely because we were lacking alternatives.
The rename of `wait_for_route` to `wait_for_channel_updates` is a bit of a drive-by fix, but makes it a bit clearer I think.

pytest: Stabilize the test_pay_direct test

---

CHANGELOG.md
bitcoin/short_channel_id.c
bitcoin/short_channel_id.h
common/json_helpers.c
common/json_helpers.h
gossipd/test/run-find_route-specific.c
lightningd/gossip_control.c
lightningd/invoice.c
lightningd/json.c
lightningd/peer_control.c
lightningd/test/run-invoice-select-inchan.c
lightningd/test/run-jsonrpc.c
plugins/pay.c
wallet/db.c
wallet/test/run-wallet.c

We need to still accept it when parsing the database, but this flag
should allow upgrade testing for devs building on top.

short_channel_id: don't accept :-separated in JSON if --allow-deprecated-apis=false

---

doc/HACKING.md

As a newbie, I forgot to re-enable the dev options that are required to run the tests...

doc: add configure --enable-dev in testing chapter

---

lightningd/options.c
lightningd/plugin.c
lightningd/plugin.h

**Problem:** 
when running the daemon that loads a plugin with options, then starting lightning-charge the daemon crashes
**Resolution**
in `options.c`, `add_config` is called with a `opt->cb_arg` of type `plugin_opt_set`, I added a check for this
I am not sure why this is called in this manner so this may not be the desired solution, but I thought it best to show my findings in code rather than open an issue.

fix crash with lightning charge and plugin opts

---

doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt
doc/lightning-getroute.7
doc/lightning-getroute.7.txt
lightningd/opening_control.c
lightningd/peer_control.c
wallet/wallet.c

Hope this is allowed to bundle in single PR, can make separate if needed.
- doc: improve explanation of getroute command 
(as commented in PR #2307)
- doc: fundchannel command, clarify optional `feerate`
(mentioned in issue #2354)
- remove trailing space in logline and small coding style fix
(as commented in PR #2310)
- lightningd/json_dev_forget_channel: clarify message when both peer_id and scid are given
(mentioned in issue #2298)
- lightningd/json_fundchannel: use json_add_string to add hex_tx to response, similar as in json_withdraw

Small fixes to docs, json_dev_forget_channel, json_fundchannel and trailing space in logline

---

tests/test_connection.py
tests/test_gossip.py
tests/test_invoices.py
tests/test_pay.py

The non-developer tests are failing on Travis due to the long gossip synchronization. I don't think there is much value in testing these in non-developer mode given that the only difference is the longer wait time, so I marked them as `@unittest.skipIf(not DEVELOPER, ...)`.
The alternative would be to split the non-developer tests like we already do with the valgrind tests, but I doubt that anything substantial was ever learned from the disabled test scenarios.

pytest: Mark the worst gossip offenders as developer-only tests

---

doc/INSTALL.md

For some reason, without this extra option the `./configure` script in `gmp-6.1.2` would fail with a:
```
configure: error: could not find a working compiler, see config.log for details
```
Adding this option changes one of the first line of output from "host system: x86_64-pc-linux-gnu" to "host system: arm-unknown-linux-gnueabihf".
This issue occurred with the following cross-compiling toolchain, I have not tested that with any other compilers/toolchains.
```
[user@arm-cross-compile gmp-6.1.2]$ arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Linaro GCC 7.3-2018.05) 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO …
```

doc: fix the command to cross-compile libgmp

---

lightningd/lightningd.h
lightningd/options.c

fix: change type of config->fee_per_satoshi to uint32
This patch will properly set fee_per_satoshi to _unsigned_ integer,
as support for negative fees was removed from overall design.
This change does not break any tests, so I assume its better this way.

fix: change type of config->fee_per_satoshi to uint32

---

Makefile
gossipd/routing.c

Recent cppcheck version (at least 1.86) will have a false positive in `gossipd/routing.c` line 903. The cppcheck misunderstands ccan's external memory management by assigning it to a local struct pointer:
```C
struct pending_cannouncement *pending;
pending = tal(rstate, struct pending_cannouncement); 
// ... 
*scid = &pending->short_channel_id;
```
It complains with `[gossipd/routing.c:903]: (error) Address of local auto-variable assigned to a function parameter.` 
When the diff is applied, test are able to run normally, as cppcheck is a required precondition. I didnt find a better way than to add and enable a exception.

fix: add inline exception for recent cppcheck false positive

---

contrib/pylightning/lightning/lightning.py

We read a JSON message from the buffer, after converting it from raw bytes to
UTF-8, and returning the remainder of the byte array back to the
caller. However the return value of `raw_decode` refers to symbols in the
UTF-8 decoded string, not the raw bytes underlying byte-array, which means
that if we have multi-byte encoded UTF-8 symbols in the byte-array we end up
with a misaligned offset and will return part of the message as
remainder. This would then end up being interpreted as the result of the next
call.
This could not be exploited currently since we use a socket only for a single
JSON-RPC call and will close the connection afterwards, but since we want to
eventually recycle connections for multiple calls, this could have been very
dangerous.
Signed-off-by: Christian Decker …

pylightning: Correctly return the remainder of a message back

---

lightningd/lightningd.c
tests/test_misc.py
wallet/db.c

We were not correctly allocating the `db->filename`, failing to copy the
null-terminator. This was causing and error when reopening the database after
the call to `fork()`.
Fixes #2348

daemon: Fix issue 2348, db->filenam not being correctly initialized

---

lightningd/pay.c
tests/test_pay.py

I got a spurious failure because the final node gave a CLTV error and
so it decided to use a different channel.  It should probably handle
this corner case better, but meanwhile make the test robust.

pytest: fix race in test_pay_direct.

---

.gitignore

Files are generated if you run
```
python3 setup.py install
```
for `contrib/pylightning`

Add generated python and pylightning files to .gitignore

---

CHANGELOG.md
channeld/channeld.c

LND seems to do this occasionally, though fixed in new versions.  Workaround
in the meantime.
I tested this by hacking our code to send it prematurely, and this worked.
Fixes: #2219

channeld: handle funding_locked message before reestablish.

---

doc/PLUGINS.md
lightningd/json.c
lightningd/json.h
lightningd/peer_control.c
lightningd/test/run-invoice-select-inchan.c
tests/plugins/reject.py
tests/test_plugin.py
wallet/test/run-wallet.c
wire/fromwire.c
wire/wire.h

This is a simpler example than the `htlc_accepted` hook that I'm still working on, but it already allows us to do quite some interesting things. For example it'd allow us to implement a drain-plugin that allows connections to and from peers we are still negotiating a close with, but reject all connections that could result in a new channel.
It also serves as an example on how hooks are implemented.

plugin: Connected hook

---

README.md
doc/INSTALL.md

`libsodium-dev` was removed in #1462 then added backed in #2319 - BUT as `libsodium`, which is not found. This updates to `libsodium-dev`

Switch to libsodium-dev for ubuntu install instructions

---

contrib/pylightning/lightning/plugin.py

At the moment if you have the rpc method
```python
@plugin.method("hello")
def hello(plugin, name, punctuation="!"):
```
And call it from the cli, with
```
lightning-cli hello
```
Currently, the arg for `name` will default to `inspect._empty`, which is a bit clumsy. 
This change instead returns the error message:
```
"Error while processing hello: TypeError('Missing required parameter: name',)"
```

Pylightning: Raise error if required argument is missing

---

lightningd/lightningd.c
lightningd/log.c

This will make the logger write 4 newlines to re-attached logfiles.
The newlines wont appear on logfiles that are just created.
Additionally the server prints 50 '-' dashes before printing his
startup message, which also help increase readability on logfile.
This was inspired by the way Bitcoin Core handles logfiles.

feat: block of newlines when attaching a logfile

---

CHANGELOG.md
common/wallet_tx.c
common/wallet_tx.h
contrib/pylightning/lightning/lightning.py
lightningd/opening_control.c
tests/test_closing.py
tests/test_connection.py
tests/test_misc.py
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h
wallet/walletrpc.c

We had quite a few cases in which one failed transaction (potentially due to insufficient fees) was causing all following transactions to remain in limbo as well.
This PR adds a `minconf` argument inspired by `bitcoind` that allows us to determine how many confirmations an output must have before being considered for coin selection. The default of 1 confirmation mitigates the risk of chainge chaining, with the drawback of failing a few more transactions at selection than strictly necessary.

Reduce the risk of change chaining transactions

---

contrib/pylightning/lightning/lightning.py

Without this the RPC will fail to continue buffering if the response does not
fit in the first read, and if we don't switch over to the non-compat
mode. This was introduced by our mitigation of the UTF-8 misalignment (#2355 ), but I
missed this path.

pylightning: Fix missing encode if first pass fails

---

CHANGELOG.md
common/utxo.c
common/utxo.h
lightningd/onchain_control.c
onchaind/onchain_wire.csv
onchaind/onchaind.c
onchaind/test/run-grind_feerate.c
tests/test_closing.py
wallet/db.c
wallet/wallet.c
wallet/walletrpc.c

This was the only type of outputs we didn't show addresses until now, since it was a bit more involved, being derived from a combination of the outpoint and the private key. I decided to add the `scriptPubKey` to the outputs in these cases since otherwise we'd have to go talk to `hsmd` just to derive the pubkey and then hash it in order to generate the address, which is basically already what is in the `scriptPubKey`.
However I haven't found a good and clean way to backfill the missing ones for existing wallets since we don't track the utxos, and we can't call out to the `hsmd` in migrations. The number of affected users is minimal and it falls back gracefully to just not showing the address in those cases, so I decided not to add more code just to cover that corner case that'll quickly …

Show addresses for their_unilateral/to_us outputs as well

---

CHANGELOG.md
Makefile
configure
tools/build-release.sh

I want to merge the repro script immediately before rc1.  That is two commits: one to add the script (ideally that would be rc1), and one to document (using real examples from the previous commit).
Then I'm happy to refine it during the rc process.
So this gets the precursor cleanups out the way.

Build cleanups for release

---

lightningd/opening_control.c

tiny fixup to use chainparams instead of inline constant.

opening_control: use chainparams for dust_limit in channel config

---

CHANGELOG.md
common/amount.c
common/amount.h
common/test/run-amount.c
doc/lightning-fundchannel.7
doc/lightning-fundchannel.7.txt
doc/lightning-invoice.7
doc/lightning-invoice.7.txt
doc/lightning-pay.7
doc/lightning-pay.7.txt
doc/lightning-sendpay.7
doc/lightning-sendpay.7.txt
doc/lightning-withdraw.7
doc/lightning-withdraw.7.txt

I tried to fundchannel 0.01btc, and of course it wanted 8 decimals exactly.
If I can't get this right, it's probably a bad idea.
I still don't allow whole number of btc though, since that's probably a mistake
and you're not supposed to put that much in c-lightning yet :)

JSON: allow any number of decimal points when parsing 'btc' suffix.

---

Dockerfile
README.md

This is a proposed fix for #2377.
**Current behavior**
When following instructions in readme.md with using docker image, running `lightning-cli` Pay will generate:  ` { "code" : -32601, "message" : "Unknown command 'pay'" }`
**Proposed fix**
Copy the Pay plugin to `/usr/libexec/c-lightning/plugins/` and use --plugin-dir argument to point to the plugins directory.
**Note to the maintainers**
After applying this fix, the docker image `elementsproject/lightningd` should be updated and uploaded to Dockerhub

Installing the Pay plugin in Dockerfile

---

plugins/pay.c

`*best` is checked for null before the comparison against the uninitialized
variable ever happens, so this isn't a real issue.
Initialize it to zero so that we don't fail to compile on certain gcc versions.
plugins/pay.c: In function ‘add_shadow_route’:
plugins/pay.c:644:18: error: ‘sample’ may be used uninitialized in this function
if (!best || v > sample) {
~~^~~~~~~~

build: fix uninitialized variable error on gcc 7.4.0

---

wallet/db.c
wallet/db.h
wallet/test/run-db.c
wallet/test/run-wallet.c
wallet/wallet.c

A minor fix, but the second one should help #2342

DB: more advanced upgrade

---

configure

It seems libsodium broke their public interface at some point by switching
from upper-case IETF in constants to lower-case. This adds a check for the
lower-case version which seems to be what they are going with.
Fixes #2425 
Reported-by: Zoltán Gálli <@gallizoltan>

build: libsodium switched case in constants, add check for compat

---

lightningd/peer_control.c

I orginally added the `num_x_channels` fields to `getinfo`, and wasn't quite sure how to handle the case of `peer->uncommitted_channel`, so I lumped it into `pending_channels`.
I now think this is a bit wrong, as it can stay in this state indefinitely if no channel is made, and it might be misleading to show it as pending.

Don't count uncommitted channels towards num_pending in getinfo

---

wallet/test/run-db.c
wallet/test/run-wallet.c

Will prevent calling a DB migrate hook without the `*ld` context.
Unit tests not giving `*ld` cant rely on correct migration.
Don't know if its a elegant solution, but does its job.

fix: only call DB migration hook if *ld was defined

---

README.md

During installation I noticed that the README suggests using a config option "port=9735". Unfortunately lightningd rejects this option with error "unrecognized option". As this is the default port anyway, I simple removed this option.

Remove missing config option "port"

---

lightningd/plugin.c

As pointed out by `bitonic-cjp` in the IRC log, there was a closedir missing.
**Note:** I do not check the return code of this operation by intention, as there would not be any meaningful error correction or notification at this point.

fix: missing closedir in plugin.c

---

Dockerfile
README.md
contrib/linuxarm32v7.Dockerfile

**Current state**
In docker, the lightning installation is achieved by copying binaries one by one ‘manually’.  As soon as a new binary is added, the dockerfile become outdated. See #2377 
**What has been done**
Binaries are installed into a temporary directory using `configure --prefix=` and `make install`, then the installation directory is copied ‘as-it-is’ to the final image in the second phase of the build. This will guarantee that any new lib/binary/plugin generated from `make install` will be reflected in the docker images, and more important, the docker image configuration is closer to the normal build.
**Note to the maintainers**
Update the official docker image after the merge of this PR.

Fix installing plugins in dockerfile

---

wallet/test/run-db.c
wallet/test/run-wallet.c
wallet/test/test_utils.c
wallet/test/test_utils.h

PR #2444 introduced a problem where valgrind complained ab usage of otherwise uninitialized space in the `*ld` unittest stub.
We will reuse the testnet config and put it in testuitls.c ...

fix: fix a pr2444 introduced valgrind complaint

---

tools/repro-build.sh

make check-source error in my ubuntu 18.04
```
In tools/repro-build.sh line 33:
elif type lsb_release >/dev/null 2>&1; then
^-- SC2039: In POSIX sh, 'type' is undefined.
```
change `type` to `which` follow  https://wiki.ubuntu.com/DashAsBinSh#type suggestion.

Compatible posix sh

---

CHANGELOG.md
bitcoin/chainparams.c
bitcoin/chainparams.h
hsmd/hsm_wire.csv
hsmd/hsmd.c
lightningd/hsm_control.c
wire/fromwire.c
wire/towire.c
wire/wire.h

Thanks for @rustyrussell 's [advice](https://github.com/ElementsProject/lightning/pull/2436#issuecomment-469083795), now I set the version BIP32_VER_TEST_PRIVATE for testnet/regtest to generate BIP32 privkey with libwally-core, and set BIP32_VER_MAIN_PRIVATE for mainnet.
For litecoin, we also set the version like bitcoin else.
There are 3 changes:
1. Add the mainnet flag(bool) paramater in `hsm_init` wire in hsmd/hsm_wire.csv;
2. Add the mainnet flag(bool) paramater in `populate_secretstuff()` and `load_hsm()` function in hsmd/hsmd.c;
3. Set BIP32_VER_MAIN_PRIVATE for mainnet or BIP32_VER_TEST_PRIVATE for testnet/regtest in `bip32_key_from_seed()` corresponding to mainnet flag(bool) paramater in  `populate_secretstuff()` .

Fix: fix the version of bip32 private_key generation

---

openingd/openingd.c

Foud this in my test:
```
You gave bad parameters: channel capacity with funding 600sat, reserves 6sat/6sat, max_htlc_value_in_flight_msat 18446744073709551615msat is 588sat msat, which is below 1000000msat msat'
```

correct messge format
