CHANGELOG.md
=> CHANGELOG.md: 0.8.1rc3

CHANGELOG.md, doc/MAKING-RELEASES.md
=> Release 0.8.1

ccan/README, ccan/ccan/tal/tal.c, ccan/ccan/tal/tal.h, ccan/ccan/tal/test/run-destructor.c, ccan/ccan/timer/timer.c
Also, a fix for compiling with NDEBUG.
=> ccan: update to latest version which allows destructors to self-delete.

plugins/libplugin.c, plugins/libplugin.h
=> libplugin: use a typesafe_cb for plugin_timer

doc/HACKING.md
=> doc: add pyln-proto to PYTHONPATH for pytest in HACKING

lightningd/bitcoind.c, plugins/bcli.c
Reported-by: Vasil Dimov <@vasild>
fixes #3562
Changelog-None
=> bitcoind: timeout if the Bitcoin plugin never completes the handshake

doc/lightning-listchannels.7.md
I added a hint how to specify source but not short channel id.
Changelog-None
=> Use of null

doc/lightning-listchannels.7
#3576 [didn't update the manpages..](https://github.com/ElementsProject/lightning/pull/3576#issuecomment-596080445)
Changelog-None
=> doc: update listchannels manpage

lightningd/bitcoind.c
On plugin failure, this is cleaner than having a backtrace to `plugin_request_send`.
Changelog-None
=> bitcoind: check that Bitcoin plugin is alive before sending a request

common/onion.c, common/onion.h, common/sphinx.c, common/sphinx.h, devtools/onion.c, lightningd/peer_htlcs.c, tests/test_misc.py, wallet/test/run-wallet.c
Prep work for messages.
Changelog-None
=> Onion tool and sphinx minor cleanups

channeld/Makefile, common/Makefile, common/hmac.c, common/hmac.h, common/sphinx.c, common/sphinx.h, common/test/run-sphinx.c, devtools/Makefile, devtools/onion.c, lightningd/Makefile
No real changes, just using modern types and extracting hmac into another file for reuse.
Changelog-None
=> Sphinx cleanups

devtools/.gitignore, doc/lightning-close.7, doc/lightning-close.7.md, lightningd/peer_control.c
* git ignore devtools/blindedpath
* followup to https://github.com/ElementsProject/lightning/pull/3390 - fix typo
* followup to https://github.com/ElementsProject/lightning/pull/3390 - don't accept 0 satoshi
=> Minor tweaks

channeld/channeld.c, channeld/full_channel.c, channeld/full_channel.h, channeld/test/run-full_channel.c, common/htlc_tx.c, devtools/mkcommit.c
That has unwanted libwally changes, so reproduced here without them
Closes: #3536
Changelog-None
=> #3536 cleaned up

CHANGELOG.md, channeld/channeld.c, contrib/Dockerfile.builder, contrib/Dockerfile.builder.fedora, tools/build-release.sh
Changelog updates for the RC1, 0.8.2
=> v0.8.2-rc1 

Makefile
Small oversight on my part, thanks for noticing it @whitslack :+1:
Changelog-None
=> plugin: Add the keysend plugin to the list of installable plugins

CHANGELOG.md
Includes small fix for occasional test suite memleak with rpc_hook_payload.
=> Release Candidate 2 for 0.8.2

doc/PLUGINS.md
=> doc: bitcoin backend must return sat/kVB not btc/kVB on `estimatefees`

CHANGELOG.md
=> v0.8.2rc3 changelog updates

CHANGELOG.md
0.8.2, we're doing it.
Also updates the named by tag-line to say 'was'.
=> 0.8.2 Changelog Update

.gitignore, wire/Makefile
- Have make be a bit quieter when patching files
- ignore a few more things
=> build and gitignore updates

wallet/wallet.h
=> wallet: fix typo in wallet_can_spend() comment

doc/STYLE.md
=> doc: fix typo in STYLE.md (s/chanelog/changelog/)

wallet/db_sqlite3.c
For sqlite3 versions < 3.14 (i.e. HAVE_SQLITE3_EXPANDED_SQL is not set),
tracing is used to dump statements. The function db_sqlite3_exec()
registers a tracing callback in the beginning and unregisters it at the
end to "avoid it accessing the potentially stale pointer to stmt".
However, the unregistering so far only happened in the success case,
i.e. if the prepare or step calls failed, the callback was still set!
Running the test wallet/test/db-run with sqlite 3.11 leads to a
segmentation fault in the last call to db_commit_transaction():
the tested transaction contains an invalid statement and the (still
registered) trace callback is triggered then by sqlite3_exec() in
db_sqlite3_commit_tx(), leading to a segfault in db_changes_add()
(according to gdb), where it tries to access …
=> db: unregister sqlite3 trace callback also in error case

channeld/channeld.c, channeld/watchtower.c, channeld/watchtower.h
Some minor cleanups I noticed in review.  Wasn't worth delaying merge for.
Changelog-None
=> channeld watchtower cleanups

contrib/pyln-client/pyln/client/lightning.py
I quickly ran through the comments in lightning.py and saw a few small inconsistencies:
- upper/lower case for the "B" in "Bitcoin" unified (see https://github.com/lnbook/lnbook/pull/98)
- added missing "." after a complete sentence
- removed unnecessary double spaces
Changelog-None
=> Comment optimisations

channeld/channeld.c
Commit b0c9059602ea2f84ba6507372919b5140e56e302 broke the case where next_node_id is NULL:
```
[libsecp256k1] illegal argument: pubkey != NULL
lightning_channeld: FATAL SIGNAL 6 (version 13d9c27)
0x55b4cd261b64 send_backtrace
common/daemon.c:39
0x55b4cd261c0e crashdump
common/daemon.c:52
0x7fc60307746f ???
???:0
0x7fc6030773eb ???
???:0
0x7fc603056898 ???
???:0
0x55b4cd2c7cee ???
???:0
0x55b4cd2d74d4 ???
???:0
0x55b4cd26ac62 node_id_from_pubkey
common/node_id.c:12
0x55b4cd24e194 handle_onion_message
channeld/channeld.c:1890
0x55b4cd24e697 peer_in
channeld/channeld.c:2001
0x55b4cd2521f4 main
channeld/channeld.c:3419
0x7fc6030581e2 ???
???:0
0x55b4cd24881d ???
???:0
0xffffffffffffffff ???
???:0
```
Changelog-None
=> lightningd: EXPERIMENTAL_FEATURES: fix crash caused by test_sendonionmessage

bitcoin/script.h, bitcoin/tx.h, external/Makefile
And a makefile cleanup I noticed on the way...
Changelog-None
=> Bitcoin tx cleanups

lightningd/lightningd.c
It's now a wrapper for wally_tx, so update example.
Reported-by: @niftynei
Changelog-None
=> doc: lightningd comment refers to obsolete bitcoin_tx.

Makefile
Changelog-None
Reported-by: @niftynei
=> Makefile: don't print out what we're doing if --quiet/-s

bitcoin/test/run-bitcoin_block_from_hex.c, bitcoin/test/run-tx-encode.c, bitcoin/tx.c, common/test/run-amount.c, common/test/run-bigsize.c, common/test/run-cryptomsg.c, common/test/run-derive_basepoints.c, common/test/run-features.c, common/test/run-funding_tx.c, common/test/run-ip_port_parsing.c, common/test/run-json_remove.c, common/test/run-key_derive.c, common/test/run-lock.c, common/test/run-softref.c, connectd/test/run-initiator-success.c, connectd/test/run-responder-success.c, lightningd/gossip_msg.c, onchaind/test/run-grind_feerate-bug.c, onchaind/test/run-grind_feerate.c, wire/fromwire.c, wire/wire.h
=> Serialization cleanups and fromwire_bitcoin_tx fix

contrib/pyln-proto/Makefile, contrib/pyln-proto/pyln/proto/__init__.py, doc/lightning-pay.7.md, tests/test_connection.py
Just a minor typo and a test exclusion I couldn't fit in anywhere else
Changelog-None
=> Weekly cleanups 2020/23

contrib/pyln-proto/pyln/proto/message/array_types.py, contrib/pyln-proto/pyln/proto/message/fundamental_types.py, contrib/pyln-proto/pyln/proto/message/message.py, contrib/pyln-proto/tests/test_message.py
My tests weren't exhaustive, and now I'm hitting things in more complex testing of the spec.
Changelog-None
=> pyln.proto.message minor fixes

doc/lightning-autocleaninvoice.7, doc/lightning-decodepay.7, doc/lightning-dev-sendcustommsg.7, doc/lightning-listforwards.7, doc/lightning-pay.7, doc/lightning-plugin.7, doc/lightning-setchannelfee.7, doc/lightning-txdiscard.7, doc/lightning-txsend.7, doc/lightning-waitblockheight.7, doc/lightning-withdraw.7
My node tried to rebuild one of them because it was lagging (I noticed
because mrkd was not installed).
Turns out a few were lagging, and lightning-dev-sendcustommsg.7 was totally
empty!
Changelog-None
=> doc: regenerate and update.

tests/test_closing.py, tests/test_wallet.py
Two so far, but I'm sure there are more...
Changelog-None
=> Test flake fixes

tests/test_misc.py
By setting nLocktime to the current block, the reorg test
"test_funding_reorg_remote_lags" actually drops the funding transaction
entirely when a reorg happens.
Except the 1 in 10 cases where nLocktime is randomly set to 1-10
blocks earlier.
This implies, strongly, that we hit "restart" too often on Travis.
Changelog-None
=> pytest: fix test breakage added by d0c85033d2e5fe83861af7badb577e7cef86a310

tests/test_pay.py
Make sure we've actually confirmed the HTLC; if it's not confirmed yet
then we won't fast-fail it, and we'll timeout instead:
```
>           l1.rpc.waitsendpay(payment_hash=inv['payment_hash'], timeout=TIMEOUT, partid=1)
E           AssertionError: Pattern 'WIRE_PERMANENT_CHANNEL_FAILURE \\(reply from remote\\)' not found in "RPC call failed: method: waitsendpay, payload: {'payment_hash': 'c186643391469aa8190415496c85b1eb789cb2b756a76d4c9ce21dd34c698d92', 'timeout': 30, 'partid': 1}, error: {'code': 200, 'message': 'Timed out while waiting'}"
```
Changelog-None
=> tests: fix flake in test_partial_payment_htlc_loss

doc/index.rst, doc/lightning-fundchannel.7, doc/lightning-txprepare.7, doc/lightning-withdraw.7
Not quite sure why this didn't Just Work...
Changelog-None
=> doc: update since addition of feerate(7)

doc/STYLE.md, lightningd/chaintopology.c, plugins/libplugin-pay.c, tests/test_misc.py
=> JSON API advice, and warnings cleanup

doc/STYLE.md
Suggested-by: @ZmnSCPxj
Changelog-None
=> doc/STYLE.md: be clear we're talking about JSON output.

CHANGELOG.md, plugins/libplugin-pay.c, plugins/pay.c, tests/plugins/hold_htlcs.py, tests/test_plugin.py
Thanks @rustyrussell for pointing these out, they slipped through in the midst of other edits :frowning: 
I'll keep this PR open for now in case other changes need to be added, but merge before tagging the final release.
Fixes #3836 
Fixes #3846
Fixes #3847
=> release: Fixes for rc2

plugins/libplugin-pay.c
Reported-by: @thestick613
Fixes #3848
Changelog-None
=> plugin: Always set the completion time, independently of outcome

contrib/pyln-testing/pyln/testing/utils.py, lightningd/lightningd.c, lightningd/lightningd.h, lightningd/options.c
@cdecker I suggest these might make testing a little easier?
Changelog-None
=> Speed travis

doc/PLUGINS.md
=> doc/PLUGINS.md: Correct misspelling of `getchaininfo`.

tests/test_pay.py
```
>       assert len(status) == 2
E       assert 1 == 2
E         -1
E         +2
```
The invoice we use at the end has a routehint: 50% of the time it's
to l2 (which fails), 50% to l5 (which succeeds).
Change it to create invoice before channel with l5 so it does the
retry like we expect here.
Changelog-None
=> pytest: fix flake in tests/test_pay.py::test_pay_exclude_node

plugins/libplugin-pay.c
We'd previously take the failed attempt and estimate the failing channel's
capacity at 3/4 of the attempted amount, which is rather aggressive. This
reduces this aggressiveness to use the exact amount tried, but excluding on
equality. This still skips attempting the same route with the same amount, but
also permits attempts that are in the range [3/4, 1] of the failed attempt
amount to still be attempted.
=> pay: Be less aggressive when estimating channel capacity

.gitmodules, bitcoin/psbt.c, bitcoin/psbt.h, bitcoin/tx.c, bitcoin/tx.h, channeld/channeld.c, hsmd/hsmd.c, openingd/openingd.c, wallet/db.c
Update to latest wally candidate
This will require re-working of #3902 somewhat, since that code uses the old PSBT interfaces. I'll comment there on what needs updating.
Changelog-None
=> Jon wally update

bitcoin/psbt.c, bitcoin/psbt.h, bitcoin/script.c, bitcoin/script.h, bitcoin/test/run-bitcoin_block_from_hex.c, bitcoin/test/run-tx-encode.c, bitcoin/tx.c, bitcoin/tx.h, common/json_tok.c, common/json_tok.h, common/utxo.c, common/utxo.h, lightningd/json.c, lightningd/json.h, wallet/reservation.c, wallet/wallet.c, wallet/walletrpc.c
=> Misc internal cleanups (nothing urgent)

common/json_helpers.c, tests/test_closing.py, tests/test_wallet.py
=> Minor test flake fixes

contrib/linuxarm32v7.Dockerfile, contrib/linuxarm64v8.Dockerfile
=> Add python to runtime docker image (arm32/64)

bitcoin/psbt.c, common/json_helpers.c, common/json_helpers.h, common/psbt_open.c
Few small things I found while working on the dual-funding accepter branch.
=> Small PSBT updates, precursor for dual-funding

common/onion.c, plugins/libplugin-pay.c
We've got some recently-added primitives which help.
Changelog-None
=> amount: cleanup usage.

common/json_command.h, common/json_tok.c, common/test/run-param.c, lightningd/gossip_control.c, lightningd/invoice.c, lightningd/json.c, lightningd/log.c, lightningd/onion_message.c, lightningd/pay.c, lightningd/peer_control.c, tests/test_invoices.py, tests/test_misc.py, tests/test_pay.py, tools/gen/header_template, tools/gen/impl_template, wallet/db.c, wallet/db.h, wallet/invoices.c, wallet/wallet.c
From my offers tree (which I dug out of cold storage, dammit I will make some progress!)
Changelog-None
=> generation and misc cleanups

doc/PLUGINS.md
Hi all.
I noted that the doc of init method inside the PLUGIN.md was a little old, and with this PR I'm updating it.
I hope I'm losing nothings
=> Alignment doc with the actual implementation

doc/Makefile, wallet/Makefile, wallet/db_postgres_sqlgen.c, wallet/db_sqlite3_sqlgen.c, wallet/statements_gettextgen.po
Omitted in commit d8e8426b52d9dd097c361e3cf405edbdfc20cffe
Changelog-None
=> Makefile: fix up sqlgen and docgen rules.

tests/test_plugin.py
I believe Christian has a more complex rewrite, but this fixes the main
flake I was seeing.
Changelog-None
=> pytest: work around flaky test.

CHANGELOG.md, devtools/credit
=> Fix credit script, and CHANGELOG.md

contrib/startup_regtest.sh
sometimes it's handy to be able to get access to an elements daemon and
nodeset also
=> contrib: add ability to start/stop elements nodeset

doc/PLUGINS.md
=> Fixed json format inside doc file introduced inside the PR #4010

CHANGELOG.md
This assumes we merge #3899 and #3936 (BTW: devtools/changelog doesn't include Changelog lines if it can't find a PR, it seems?)
=> Release 0.9.1 rc1

doc/lightningd-config.5, doc/lightningd-config.5.md
=> doc: note default proxy port.

CHANGELOG.md
=> CHANGELOG.md: 0.9.1rc2

CHANGELOG.md
=> Ready for release!

Dockerfile, Makefile, contrib/reprobuild/Dockerfile.bionic, contrib/reprobuild/Dockerfile.focal, tools/repro-build.sh
=> Add missing Dockerfiles for the reprobuilds

contrib/startup_regtest.sh, doc/lightning-fundpsbt.7, doc/lightning-fundpsbt.7.md, tests/plugins/df_accepter.py
Update the docs for `fundpsbt` to have the correct numbers; make bitcoin polling and gossip propagation faster for the regtest utility daemons.
=> doc and contrib fixes/nits

lightningd/peer_control.c
With dual-funded channels, it's possible for the funding allocation of
the non-opener to not be zero.
=> listpeers: show correct amounts for starting funding allocation

configure
=> configure: refuse to compile without any database.

configure
=> configure: clean up tmpfile if we fail.

.travis.yml
I don't have time to diagnose why it's failing all the time right now.
Changelog-None
=> Travis: disable postgres test.

.gitignore, common/bigsize.h, devtools/mkquery.c, devtools/print_wire.h, gossipd/queries.c, gossipd/test/run-extended-info.c, openingd/dualopend.c, plugins/keysend.c
It's not part of the spec anymore
=> Remove varint typedef for bigsize

doc/lightningd-config.5, doc/lightningd-config.5.md
While preparing for #4080 I found this little nit.
=> nit: doc/lightningd-config.5: Remove redundancy

tests/test_connection.py
```
@unittest.skipIf(TEST_NETWORK != 'regtest', "External wallet support doesn't work with elements yet.")
def test_funding_close_upfront(node_factory, bitcoind):
...
addr = l1.rpc.newaddr()['bech32']
>       _fundchannel(l1, l2, amt_normal, addr)
...
pyln.client.lightning.RpcError: RPC call failed: method: fundchannel_start, payload: {'id': '022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59', 'amount': 100000, 'announce': True, 'close_to': 'bcrt1qctx2k9cu9fd7nk449mzphqjcvvpyc4rxh6826x'}, error: {'code': -1, 'message': 'They sent error channel 2a1ca624cd1127761cb7a4395df2c3fd6d0abb3732c1f85a5345b0da716540d0: Multiple channels unsupported'}
```
Changelog-None
=> pytest: fix flaky test if one side hasn't processed close yet.

common/configdir.c, devtools/gossipwith.c, doc/lightningd-config.5, doc/lightningd-config.5.md
=> doc: Add missing signet to --help and man

doc/INSTALL.md
=> Add OpenBSD instructions to INSTALL.md 

README.md
=> removed unwanted lines and added punctuation marks

bitcoin/feerate.c, bitcoin/feerate.h, bitcoin/psbt.c, bitcoin/psbt.h, channeld/Makefile, channeld/channeld.c, closingd/Makefile, common/Makefile, common/json_helpers.c, common/json_helpers.h, common/psbt_internal.c, common/psbt_internal.h, common/psbt_open.c, common/psbt_open.h, common/test/exp-run-psbt_diff.c, connectd/Makefile, devtools/Makefile, gossipd/Makefile, hsmd/Makefile, lightningd/Makefile, lightningd/dual_open_control.c, lightningd/notification.c, onchaind/Makefile, openingd/Makefile, openingd/dualopend.c
Bunch of code move + rework patches for the next big dual-funding patchset
Built on top of #4055, start at 927277a
=> cleanups for some dual-funding related code, I of III

doc/HACKING.md, doc/lightning-setchannelfee.7, doc/lightning-setchannelfee.7.md
Some typos and additions to the `HACKING.md` I found to be useful for others.
=> chore: doc typo and hacking

contrib/pyln-testing/pyln/testing/db.py
On my Archlinux system the current way of looking up the PostgreSQL binaries does not work.
I replaced the current hardwired way of looking up binaries by using the `pg_config --bindir` tool that should
work better on most distributions.
Changelog-None
=> chore: optimize postgres binary lookup

lightningd/lightningd.c
This is yet another proof of work. Does not really need to be merged as all the changes are purely cosmetical.
=> nit: lightningd.c: fix a cople of comments

doc/STYLE.md
=> doc: STYLE.md fix "parameters get"

lightningd/lightningd.c
See https://github.com/rustyrussell/ccan/pull/88
Changelog-None
=> nit: lightningd.c: fix "Richard Stevens' advice"

.travis.yml
We weren't testing the actual nodes, config 5 is just a compilation smoketest.
Changelog-None
=> travis: Add a pytest run with EXPERIMENTAL_FEATURES=1

doc/PLUGINS.md
To match reality.
Changelog-None
=> doc: move "next_onion" and "shared_secret" to inside "onion".

devtools/print_wire.c, gossipd/queries.c
=> Scids query fix

CHANGELOG.md
But actually... changelog - all :P
=> v0.9.2rc1 - Changelog

CHANGELOG.md
=> Bump CHANGELOG to v0.9.2rc2

CHANGELOG.md
=> Update to v0.9.2

doc/PLUGINS.md
I actually noticed this some time ago while making CLBOSS.... https://github.com/ZmnSCPxj/clboss/blob/33b0f1b113084642d2d6ad4ca5bf73011f2f63e3/Boss/Mod/Manifester.cpp#L31-L33 and only got around to it now, LOL.
Changelog-None
=> doc/PLUGINS.md: Fix typo.

doc/TOR.md
=> doc/TOR.md: Add missing instructions to add user to Tor group.

contrib/pyln-testing/pyln/testing/utils.py, tests/test_plugin.py
=> Minor pyln and pytest cleanups

connectd/netaddress.c
As seen in #4222 (thanks @laanwj !)
Changelog-None
=> Fix freebsd valgrind err

doc/INSTALL.md, tools/refresh-submodules.sh
libwally added libsecp256k1 as a submodule, so we need to recursively
update the submodules now
=> make: have `git submodule update` be recursive

doc/BACKUP.md
=> doc/BACKUP.md: Minor typo due to rearranged text.

common/param.c
This may help with https://github.com/ElementsProject/lightning/issues/4287.
=> add a note to "unknown parameter" error about -k autodetect failure.

configure, contrib/pyln-proto/pyln/proto/onion.py, contrib/pyln-proto/tests/test_onion.py, doc/lightning-sendpay.7, doc/lightning-sendpay.7.md, tests/test_closing.py, tests/test_pay.py
=> Weekly cdecker cleanups

channeld/channeld.c, common/amount.c, common/amount.h, common/test/run-amount.c, doc/lightning-offer.7, doc/lightning-offer.7.md, gossipd/gossipd.c, gossipd/gossipd_wire.csv, gossipd/gossipd_wiregen.c, gossipd/gossipd_wiregen.h, lightningd/onion_message.c, plugins/fetchinvoice.c, plugins/offers_inv_hook.c, plugins/offers_invreq_hook.c, plugins/offers_offer.c, plugins/pay.c, plugins/spender/multifundchannel.c, plugins/spender/openchannel.c, tests/plugins/currencyUSDAUD5000.py, tests/plugins/onionmessage-reply.py, tests/test_misc.py, tests/test_pay.py, wire/extracted_peer_experimental_varonionmessage
Based on #4271, this is an ongoing effort to fix the FIXMEs.
See "onion_message: support variable-length onion messages" onwards (last 4 commits)
Changelog-None: experimental stuff...
=> Offers: the bonus bits!

README.md
=> Added link to https://lightning.readthedocs.io/

Dockerfile, contrib/linuxarm32v7.Dockerfile, contrib/linuxarm64v8.Dockerfile
Fix #4353 as well as matching the other dockerfile from different architecture.
=> Fix dockerfiles

tests/test_connection.py, tests/test_pay.py
Testing on builder revealed these two.
=> More flakes

doc/BACKUP.md
=> Fix typo in doc/BACKUP.md

bitcoin/psbt.c, bitcoin/psbt.h, lightningd/dual_open_control.c, openingd/dualopend.c, tests/test_connection.py
Collection of nits + helpers found on the way to an RBF implementation.
Changelog-None
=> RBF I: pre-work

doc/lightning-checkmessage.7, doc/lightning-checkmessage.7.md
=> Minor wording

hsmd/hsmd.c
Just a security measure to avoid alternative use-cases of the hsmd
running into the issue that they need to send a `WIRE_HSMD_INIT`
message as first message. If that is not done, the `secretstuff` won't
get initialized and we'd be producing signatures from uninitialized
memory, which are completely useless.
Changelog-None: Internal change only
=> hsmd: Ensure the hsmd is initialized before anything else is called

CHANGELOG.md, doc/MAKING-RELEASES.md
devtools/credits relies on this to choose the next namer.
=> CHANGELOG: add title and namer to last release.

doc/Makefile, doc/PLUGINS.md, doc/index.rst, doc/lightning-fundchannel_complete.7, doc/lightning-fundchannel_complete.7.md, doc/lightning-fundchannel_start.7, doc/lightning-fundchannel_start.7.md, doc/lightning-openchannel_bump.7, doc/lightning-openchannel_bump.7.md, doc/lightning-openchannel_init.7, doc/lightning-openchannel_init.7.md, doc/lightning-openchannel_signed.7, doc/lightning-openchannel_signed.7.md, doc/lightning-openchannel_update.7, doc/lightning-openchannel_update.7.md, lightningd/dual_open_control.c, tests/plugins/df_accepter.py
Update the docs for all of the v2 channel open RPC commands, hooks and notifications.
=> Dual-funding, doc update

contrib/startup_regtest.sh
=> Fix wallet creation in contrib/startup_regtest.sh

CHANGELOG.md
=> 0.10.0-rc1

connectd/connectd.c, connectd/connectd.h, connectd/peer_exchange_initmsg.c, connectd/peer_exchange_initmsg.h
This should make it clearer where the problem seen in
https://github.com/ElementsProject/lightning/issues/4297 is.
Changelog-None
=> connectd: clearly differentiate incoming and outgoing paths.

CHANGELOG.md
=> v0.10.0 rc2

common/gossip_store.c, gossipd/gossip_store.c
This is to track down https://github.com/ElementsProject/lightning/issues/4288 and also clean up a bogus assumption @whitslack noted.
Changelog-None
=> Allow nonatomic writes

CHANGELOG.md
=> CHANGELOG.md: update for v0.10.0

plugins/libplugin-pay.c
We can simplify the `pay` plugin by not relying on `getroute` anymore and instead use the faster and more flexible `gossmap` implementation. This removes the one last use of `getroute` in the `libplugin-pay` library, and simplifies the reachability check to juts be locally executed.
There is one remaining `getroute` use in `plugins/pay.c`, however that is accessed exclusively through the `legacypay` JSON-RPC method, which is scheduled for removal in 4 months anyway, so I didn't bother to actually remove it. Looking forward to removing `legacypay` :-)
Changelog-None
=> pay: Use gossmap for reachability check

.github/scripts/build.sh, .github/workflows/ci.yaml, tests/fuzz/fuzz-amount.c, tests/fuzz/libfuzz.c
Christian Reitter noted that it was currently broken: fix, and add (build) to CI.
Changelog-None
=> Fuzz update

tests/test_closing.py, tests/test_connection.py, tests/test_misc.py, tests/test_wallet.py, tests/utils.py
They seem to have changed the JSON output.
Changelog-None
=> pytest: make it work with latest bitcoind master branch.

tests/test_pay.py
I'm still diagnosing exactly why this fails, but it will need Christian's
help at this stage.
Changelog-None
=> pytest: disable mpp test which is blocking merges.

.github/workflows/ci.yaml
=> Restore CI for EXPERIMENTAL_FEATURES

.github/workflows/ci.yaml, plugins/libplugin-pay.c, tests/test_connection.py, tests/test_pay.py
=> CI: give nicer names to Ci runners, disable DF tests due to chronic timeouts

doc/lightning-fundchannel.7, doc/lightning-fundchannel.7.md
This should hopefully alleviate the pain of figuring out how to properly quote utxos in fundchannel command :) It took me a while to figure it out and I would be lost without @cdecker s help on IRC.
Changelog-None: Docs change only
=> doc: fundchannel example

lightningd/closing_control.c
Check closing transaction signature in lightningd closing_received_signature message as well. Fixes small in-code FIXME. Guessing this is a small enough change that it doesn't require a changelog.
=> lightningd: check closing tx signature

lightningd/pay.c
The need for this `direction` property has always puzzled and confused me, as it should be implied from the route direction and the channel. Today I learned it is being required but not being used at all, so I removed it.
This seems to work fine, but maybe I'm making a huge mistake somewhere.
=> remove checking for unused "direction" property in `sendpay`.

lightningd/lightningd.c
Looking at #4575, I'm not sure what happened.  This prints it out, at least.
Changelog-None
=> lightningd: print out what errno we got if unexpected in sigchild.

doc/lightning-listpeers.7, doc/lightning-listpeers.7.md, doc/lightning-openchannel_abort.7, doc/lightning-openchannel_abort.7.md, doc/lightning-openchannel_init.7, doc/lightning-openchannel_init.7.md, doc/lightning-openchannel_update.7, doc/lightning-openchannel_update.7.md, doc/schemas/listpeers.schema.json, doc/schemas/openchannel_abort.schema.json, doc/schemas/openchannel_init.schema.json, doc/schemas/openchannel_update.schema.json, tests/test_opening.py, tests/test_plugin.py
Seems like there's a few bugs in master with schemas; also the coin-moves test is off by 1695sats for the dual-funding tests.
=> Schema and other fixes

common/Makefile
And add checks for any others!
=> common: fix up missing file which can cause parallel build issues.

doc/BACKUP.md
diff does not have -R, it has -r
=> diff -R to diff -r

.github/workflows/ci.yaml, lightningd/dual_open_control.c, lightningd/opening_common.c, openingd/dualopend.c, openingd/dualopend_wire.csv, openingd/dualopend_wiregen.c, openingd/dualopend_wiregen.h, tests/test_connection.py, tests/test_opening.py
I just realized this isn't being tested!  Did some quick fixes, but it still fails.
=> Restore dual-funding GitHub CI

CHANGELOG.md
=> changelog: v0.10.1  release notes

doc/lightning-close.7, doc/lightning-close.7.md
=> new line for default value, makes it more visable

CHANGELOG.md
Suggested-By: @nalinbhardwaj
Changelog-Changed.
=> changelog: fix typo in release notes

configure, tools/test/Makefile
=> Build race fixes: create ccan/config.h atomically, make tools/test/test_gen.c depend on it

bitcoin/tx.c, common/setup.c
=> Extract obvious fixes from darosior's  #4527

contrib/pyln-client/README.md, contrib/pyln-client/pyln/client/plugin.py, tests/plugins/selfdisable.py, tests/test_plugin.py
mypy says it returns None, but it actually doesn't have to!
Changelog-None
=> pyln-client: document and test that init can self-disable.

plugins/fetchinvoice.c, tests/test_pay.py
This will be used for bootstrap.bolt12.org to provide a raw request API.
@adi2011
Changelog-None: dev-only addition
=> fetchinvoice: add developer option to send raw invoice_request.

doc/lightning-fetchinvoice.7, doc/lightning-fetchinvoice.7.md
=> docs/fetchinvoice: document payer_note

wallet/db.c, wallet/db_postgres_sqlgen.c, wallet/db_sqlite3_sqlgen.c, wallet/statements_gettextgen.po
Fixes: #4718
Changelog-Changed: db: A new database index improves the performance of the `listpeers` command and dependents.
=> db: simple index addition to speed listpeers.

plugins/funder.c
An explanation for noobs is needed here -- without it they may be confused by some of the documation.
Changelog-None
=> Critical funder flaw

tests/test_wallet.py
This may be causing the test flakiness we sometimes see in CI.
Changelog-None
=> pytest: ensure hsmtool tests do complete writes.

.gitignore
It is the last auto-gen file in the tree
Changelog-None
=> Ignore last autogenerated file from the git tree.

doc/BACKUP.md
=> Correcting typo

wallet/db_sqlite3.c
Because db->conn is a void *, changing it (from a direct pointer to
a pointer to a pair of pointers) did not break compile if one place hadn't
been update.
The result was a confusing failure: sqlite3 complaining about API misuse,
since the db->conn pointer was not a valid db handle any more.
This is one case where avoiding a void * is hard: we might not even
have the postgresql types, since it might not be installed.  But a union
would have been superior here.
Changelog-None
=> wallet: fix sqlite3 column renaming since db backup merge.

doc/lightning-datastore.7.md
=> doc/lightning-datastore.7.md: Fix typos.

.github/workflows/bsd.yml
As @jsarenik proposed in #4900 we test in isolate the solution to fix the ci flakiness.
Changelog-None
=> ci: Fix FreeBSD workflow

contrib/linuxarm32v7.Dockerfile, contrib/linuxarm64v8.Dockerfile
Missing fixes from https://github.com/ElementsProject/lightning/pull/4922
=> Fix dockerfile for arm32/64

plugins/libplugin-pay.c
Since we have the exact state of the channels from the `listpeers`
response we can filter out the ones that are not yet normal or not
anymore. This is more of a safety net, given that the `gossip_store`
should contain local disables, but better not be racy :-)
This was found while working on greenlight, where the time between
receiving a local update and it being reflected in the `gossip_store` can
take some time.
Changelog-None
=> pay: Disable channels that are not in normal state

Makefile, ccan/README, ccan/ccan/graphql/LICENSE, ccan/ccan/graphql/_info, ccan/ccan/graphql/graphql.c, ccan/ccan/graphql/graphql.h, ccan/ccan/graphql/test/run.c
This is prep for https://github.com/ElementsProject/lightning/pull/4862
=> ccan: update, add graphql module.

common/errcode.h, common/hsm_encryption.c, common/hsm_encryption.h, doc/lightningd.8.md, lightningd/hsm_control.c, lightningd/options.c, tests/test_wallet.py, tools/hsmtool.c
This tries to introduce a more specific error code to fix the following issue on raspiblitz https://github.com/rootzoll/raspiblitz/issues/2691#issuecomment-956565146
For now, it is only a proof of concept, nothing here.
ping @openoms for testing on `raspiblitz`
=> Introducing hsm error code and support exit code in ccan

doc/INSTALL.md
=> Add pip requirements install to Mac instructions

Dockerfile
Add mistune==0.8.4
https://github.com/ElementsProject/lightning/pull/4965/files
=> fix dockerifle

Makefile
=> make: add ctags target

contrib/pyln-testing/pyln/testing/utils.py, tests/test_closing.py, tests/test_gossip.py, tests/test_wallet.py
New machine, new bitcoind, new API breakage.
Plus it uncovered an error in our Tor test (since my new machine has Tor enabled, this test actually runs).
=> Fix new bitcoind compat

tests/test_closing.py
This is breaking CI too much :(
=> pytest: remove test_htlc_rexmit_while_closing as too flaky.

channeld/channeld.c
Receiving gossip is now handled globally by connectd
=> channeld: Comment update for channeld

plugins/bcli.c
```
plugin-bcli: MEMLEAK: 0x1d2a118
plugin-bcli:   label=plugins/bcli.c:636:const char *[]
plugin-bcli:   backtrace:
plugin-bcli:     ccan/ccan/tal/tal.c:442 (tal_alloc_)
plugin-bcli:     ccan/ccan/tal/tal.c:471 (tal_alloc_arr_)
plugin-bcli:     plugins/bcli.c:636 (estimatefees_next)
plugin-bcli:     plugins/bcli.c:684 (estimatefees)
plugin-bcli:     plugins/libplugin.c:1307 (ld_command_handle)
plugin-bcli:     plugins/libplugin.c:1348 (ld_read_json_one)
plugin-bcli:     plugins/libplugin.c:1368 (ld_read_json)
plugin-bcli:     ccan/ccan/io/io.c:59 (next_plan)
plugin-bcli:     ccan/ccan/io/io.c:407 (do_plan)
plugin-bcli:     ccan/ccan/io/io.c:417 (io_ready)
plugin-bcli:     ccan/ccan/io/poll.c:453 (io_loop)
plugin-bcli:     plugins/libplugin.c:1565 (plugin_main)
plugin-bcli: …
```
=> plugins/bcli: neaten to fix spurious leak report.

db/exec.c
While ago during the Review of #5017 I found this simplification in the code that can introduce some simplification in the code IMO.
=> db: small code cleanup

doc/FAQ.md, doc/TOR.md, doc/lightningd-config.5.md
Tell our users about how to use IPv4/6 auto discovery behind NAT routers...
=> doc: update faq and docs for IP discovery

doc/lightning-sendonionmessage.7.md
It's a low-level interface now, expecting you to build your own TLVs.
Reported-by: @valentinewallace
Changelog-None
=> doc: fix sendonionmessage documentation.

Dockerfile
Changelog-Fixed: docker: The docker image is now built with postgresql support
=> docker: Build the docker image with psql support

bitcoin/base58.c, bitcoin/psbt.c, bitcoin/tx.c, bitcoin/tx_parts.c, common/psbt_internal.c, common/utils.c, common/utils.h, lightningd/dual_open_control.c, plugins/spender/multifundchannel.c, plugins/spender/openchannel.c
Found by CI for #5108, but reproduced locally.
=> More leaking, better diags

connectd/connectd.c
Zombie sighting from jb55.
Fixes: #5092
=> connectd: use closefrom for faster forking, and ignore children

bitcoin/test/run-secret_eq_consttime.c
It's failing under CI, but loadavg is under 1.  Simply remove it.
Changelog-None
=> test: avoid testing for secret_eq under CI.

cln-grpc/src/server.rs, cln-rpc/examples/getinfo.rs
=> rust: fixed compiler warnings

tests/test_pay.py
This is the part which works: we have another old PR (or simply
uncomment the FIXME section) for the routehint case.
Closes: #4781
See-also: #4808
=> tests: add test that pay gets update correct.

wallet/test/run-db.c, wallet/test/run-wallet.c
=> unit tests: don't crash if !HAVE_SQLITE3.

.github/scripts/build.sh, Dockerfile, contrib/docker/linuxarm32v7.Dockerfile, contrib/docker/linuxarm64v8.Dockerfile, contrib/docker/scripts/build.sh, doc/INSTALL.md
Fixes https://github.com/ElementsProject/lightning/issues/5160
=> build: bump zlib dependency

.editorconfig, README.md, doc/HACKING.md
Could very well be mistaken but it looks like Travis has been out of service for this repo for 1 year+.
=> Couple of test cleanups

CHANGELOG.md
One "my node won't start" fix, but lots of doc updates.
There will be an rc3: the cln-rpc plugin needs some love.
Changelog-None
=> release: v0.11.0rc2

plugins/examples/cln-plugin-startup.rs, plugins/grpc-plugin/src/main.rs, plugins/src/lib.rs
We now have ternary outcomes for `Builder.configure()` and
`Builder.start()`:
- `Ok(Some(p))` means we were configured correctly, and can continue
with our work normally
- `Ok(None)` means that `lightningd` was invoked with `--help`, we
weren't configured (which is not an error since the `lightningd` just
implicitly told us to shut down) and user code should clean up and
exit as well
- `Err(e)` something went wrong, user code may report an error and exit.
The ternary outcome is a bit unwieldy, with two nested `.unwrap()`s,
but I think this is better than exiting outright in case the user has
initialized some resources (which we discourage but can't prevent).
Changelog-None: Unreleased, not adding noise to the changelog
=> cln-plugin: Handle --help invocations better

configure, doc/Makefile, doc/lightningd-config.5.md, plugins/Makefile, tests/test_cln_rs.py
=> plugins: add grpc-plugin to PLUGINS, so it gets started and installed.

CHANGELOG.md
This time for sure!
Changelog-None
=> CHANGELOG.md: rc3

CHANGELOG.md
=> v0.11.0rc4

lightningd/dual_open_control.c, tests/test_connection.py
Changelog-None: introduced in this release.
=> Fix listpeers crash while initially opening dual funding channel

CHANGELOG.md
=> CHANGELOG: rc5

CHANGELOG.md
=> CHANGELOG.md: Looks like rc5 was the ticket!

Makefile
In particular, it's started complaining about "sudo make install"
and the .git directory being owned by someone else :(
Fixes: #5221
Fixes: #5189
Changelog-None
=> Makefile: stumble along if git does not work.

Dockerfile, contrib/docker/linuxarm32v7.Dockerfile, doc/conf.py, doc/lightning-feerates.7.md, doc/lightning-parsefeerate.7.md, tools/docker-entrypoint.sh
=> doc: Rename all mentions from c-lightning to Core-Lightning following rebrand

README.md
=> README: add links to discord + telegram so people can easily find us!

.msggen.json, cln-grpc/proto/node.proto, cln-grpc/src/convert.rs, cln-rpc/src/model.rs
Changing the JSON schemas changes this, and I didn't rebuild!
@cdecker would be nice if CI had complained about this?
Changelog-None
=> cln-grpc: API updates after 8dd51d127fff01b9302009906dcbdc83ea3b6548

doc/PLUGINS.md
directory .lightningd -> .lightning
=> Mistaken default directory in plugin docs

bitcoin/Makefile, bitcoin/block.c, bitcoin/psbt.c, bitcoin/script.c, bitcoin/tx.c
=> bitcoin: add to check-source-bolt, and (minor) quotes fixup.

doc/TOR.md
This paragraph is really hard to parse. I'm not a native speaker but I think this version would be a bit easier to understand
=> Fix typo and convert paragraph to a list

hsmd/hsmd.c
=> Update hsm error formatting.

.gitignore
Changes that are too small for their own PR.
Changelog-None
=> Cleanups for week 2022/25

doc/lightningd-config.5.md
=> doc: document the [] IPv6 address hack.

lightningd/invoice.c
We had this assertion fail, and I can't see a clear reason why.  Remove it
(i.e. don't crash because we're having trouble with creating invoice routehints)
and add logging.
```
Assertion failed: a->c->rr_number < b->c->rr_number (lightningd/invoice.c: cmp_rr_number: 623)
lightningd: FATAL SIGNAL 6 (version v0.10.2-modded)
0x5654f1c40061 send_backtrace
0x5654f1c400e9 crashdump
common/daemon.c:46
0x7efd87da6c8a ???
???:0
```
There are several possible causes for this:
1. We have two channels with the same rr_number. A quick audit shows we always set that rr_number to a unique value (and 64 bits, so wrap is not possible between the release and now!).
2. It's theoretically possible that sort() could compare a value with itself, but that would be really dumb: it doesn't that …
=> invoice: turn assert failure into more informative log_broken message.

plugins/src/lib.rs, plugins/src/messages.rs
Without this I can't use `lightning-cli plugin stop` etc.
=> cln_plugin: Configure "dynamic" field in "getmanifest" message

common/gossip_store.c, common/gossip_store.h, connectd/connectd.h, connectd/multiplex.c, devtools/dump-gossipstore.c
This doesn't do the "optimize our own gossip" yet, as that is a bigger job.  But it does the normal gossip optimizations.
=> Connectd gossip timestamp filtering optimizations

doc/INSTALL.md
Otherwise users might be running master unintentionally.
=> Add instructions to INSTALL.md for checking out a release tag

contrib/pyln-client/README.md, contrib/pyln-proto/README.md, contrib/pyln-testing/README.md
Update README.md for the following modules indicating poetry migration changes.
`pyln-client` `pyln-proto` `pyln-testing`
Fixes #5407
=> docs: fix contrib/ docs

devtools/.gitignore, plugins/.gitignore
These two files should not be tracked?
=> Nit: Add rune and commando to gitignore.

openingd/dualopend.c, tests/test_opening.py
Fixed the reconnect issue in the test, stumbled across a memleak report.
=> Fix df flake, plug tiny memleak

.github/scripts/build.sh, Makefile, tests/fuzz/Makefile, tests/fuzz/fuzz-close_tx.c, tests/fuzz/fuzz-hsm_encryption.c, tests/fuzz/fuzz-initial_channel.c
We were supposed to be testing compilation in CI.  We didn't (see second fix), so it bitrotted.
Would be great to get someone to write more fuzzing, and actually run these too!
Changelog-None
=> Fix fuzzing build

tests/test_misc.py, tests/test_plugin.py
=> Fix flakes number 4

common/test/run-bolt12_merkle-json.c, connectd/connectd.c, connectd/connectd_wire.csv, lightningd/channel.c, lightningd/channel.h, lightningd/connect_control.c, lightningd/connect_control.h, lightningd/dual_open_control.c, lightningd/opening_control.c, lightningd/options.c, lightningd/peer_control.c, lightningd/peer_control.h, lightningd/test/run-invoice-select-inchan.c, tests/test_connection.py, tests/test_gossip.py, wallet/test/run-wallet.c
Also fix a flake I hit testing this locally...
Changelog-None
=> Reconnection simplification, get less aggressive.

doc/lightning-invoice.7.md
Small typo fix that confused me!
=> Fix doc: lightning-invoice `deschashonly`

db/utils.c, db/utils.h, plugins/bkpr/bookkeeper.c, plugins/bkpr/db.c, plugins/bkpr/db.h, plugins/bkpr/test/run-bkpr_db.c, plugins/bkpr/test/run-recorder.c
The initial snapshots on an already-running lightningd are expected to
be unbalanced, but this shouldn't cause users to long for the green,
green grass of home.
This controls the Art of Noise.
Changelog-None
=> bkpr: insert obscure 60s pop references.

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-testing/pyln/testing/__init__.py, devtools/changelog.py
Changelog et al for v0.12.0rc1
=> v0.12.0rc1 changelog :taco: 

CHANGELOG.md
First is just typos, second is content, so you can pick and choose...
=> Changelog neaten for v0.12

tests/test_closing.py
Rewrite them so we won't get flaky behaviour anymore.
=> Thoroughly address multihtlc flakes

doc/lightning-setchannel.7.md
=> doc: note that setchannel maxhtlc/minhtlc only apply to *forwards*.

hsmd/libhsmd.c, tests/test_misc.py, tests/test_plugin.py
This is 5510 with test fixes (I can't force push to their branch)
Closes: #5510
=> Fix derived_secret, use correct size of secretstuff.derived secret

CHANGELOG.md
=> CHANGELOG: v0.12.0rc2

hsmd/hsmd_wire.csv
Requests in `hsmd_wire.csv` are numbered between 1 and 30, replies are request number + 100.
=> Renumber hsmd_derive_secret for consistency with other hsmd messages

CHANGELOG.md
Release Candidate 3 for v0.12.0.
Now with more bugfixes!
Changelog-None: it's already done! --RR
=> v0.12.0rc3 - Release Candidate numero tres

CHANGELOG.md
=> v0.12.0 release changelog

contrib/docker/scripts/build.sh, doc/INSTALL.md
What if we use pip install for our builds? Just a thought.
Changelog-None
=> what if we just didn't use poetry install

contrib/giantnode.py, contrib/startup_regtest.sh
As promised to @ShahanaFarooqui this gives us the ability to make a giant test node.  There are also some optimizations required for doing it in a sane timeframe (I will create another PR for them!) but meanwhile you can simply download a pre-made one from https://ozlabs.org/~rusty/giantnodes.tar.xz
Changelog-None
=> contrib/startup_ln.sh updates, new contrib/giantnode.py

lightningd/chaintopology.c
Currently channeld will get announcements of feerates even if the prior *modified* feerate was the one already reported prior. F.e., the floor is 253, but grabbed rate from bitcoind was 250, but we report it again based on 250(which is never stored!), not 253.
Only report if historical data didn't exist(which is backfilled for smoothing), or if the final computed feerate doesn't match historical.
Changelog-None
=> Don't report redundant feerates to subdaemons

.github/scripts/build.sh, .github/scripts/setup.sh, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml
Pointed out by @rustyrussell we were too restrictive in many cases.
=> pyln: Reduce dependency strictness for pyln-testing

.gitattributes
These should never be merged manually, rather have the local copy remain untouched and ask them to regenerate altogether. Also not showing in Github so reviewers don't get confused.
Changelog-None
=> gh: Mark some derived files as such

tests/test_closing.py, tests/test_pay.py
=> Fix two new flakes

contrib/init/lightningd.service
- Rename project in the description of the service file.
- Add missing `ConfigurationDirectory` section.
=> The project is called Core Lightning

tools/reckless
Removes the requests dependency, using urllib3 instead (only python standard modules are now used) and neatens some file path operations.
=> Reckless cleanups

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml
Nothing to see here, just getting ready for the release ^^
=> Tagging v22.11rc1

tools/gen/impl_template, wallet/wallet.c
I couldn't build with clang15 due to these warnings.  Easy to fix though.
Changelog-None
=> Trivial Clang15 warnings fixes

contrib/pyln-proto/pyln/proto/wire.py
We may end up with a short read, that is not empty, when a message gets fragmented during transport, so we need to loop until we either reach the full size or we have an empty read indicating a dropped connection.
Changelog-None
=> pyln: Fix an issue with the LightningConnection short-reading

wallet/db.c
This was reported, but the channel was closed.  So however we ended up with a duplicate, we're no *worse* off than we were before migration?
Fixes: #5760
Changelog-None
=> wallet: only log broken if we have duplicate scids in channels.

Dockerfile, contrib/docker/linuxarm32v7.Dockerfile, contrib/docker/linuxarm64v8.Dockerfile
Sweeping the dust out of the contrib dockerfiles so it is as near as possible as the amd64 Dockerfile
Note we need https://github.com/ElementsProject/lightning/pull/5785 for arm32 to build properly.
Changelog-None
=> Update the contrib arm32v7 and arm64v8 dockerfiles

CHANGELOG.md
=> meta: Add changelog for hotfix release v22.11.1

contrib/pyln-testing/pyln/testing/utils.py
Basic developer quality of life improvement
Changelog-None Mostly used by devs when testing
=> Turn on mempool,mempoolrej,rpc,validation logging for bitcoind blackbox tests

doc/INSTALL.md
It just updates the release tag.
=> docs: Update release tag

cln-grpc/Cargo.toml, cln-rpc/Cargo.toml, plugins/Cargo.toml
=> rs: Fix up the metadata for the crates on crates.io

contrib/bootstrap-node.sh
I have noticed that `contrib/bootstrap-node.sh` uses `head -n $(($(date +%s) % (NUM - 3) ))` to get a random selection of peers.
It's a neat trick but... why not just use `sort -R`? That also works with `/bin/sh` and gives a better random selection.
Additionally, using `sort -R` doesn't break if the current seconds is a multiple of the amount of listed peers:
```
Timestamp: 1672214119
Trying to connect to random peer 02f40890af885da4673f0ee9725ee74bb2c66d6491cc4334056a2701057993e61d@88.198.91.250...
Trying to connect to random peer 02fd98ebd4cbedd1317d629d62d192cf943f0134c61464de48f1e232d861de4ef9@52.55.248.131...
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Timestamp: 1672214120
Trying to connect to random peer …
```
=> Replace head -n with sort -R for better random peer selection

doc/lightning-listconfigs.7.md, doc/schemas/listconfigs.schema.json
Just a minor correction I came across.
=> doc: fix accept-htlc-tlv-types description

doc/Makefile
GitHub's master branch is called "main" apparently.
Changelog-None
=> CI: fix schema diff check.

.github/scripts/install-bitcoind.sh, .github/workflows/ci.yaml, .github/workflows/prototest.yaml, Makefile, cln-rpc/Makefile, common/test/run-onion-test-vector.c, plugins/Makefile, tests/test_cln_rs.py, tests/test_plugin.py
Just a bunch of changes that I'm working on to speed up and deduplicate work in CI.
=> Rework the CI system

common/bolt11.c
Fixes d9fed06b900368e59f4d1f432b87d40fd28ce8d3:
```
common/bolt11.c:868:31: error: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'u64' (aka 'unsigned long long') [-Werror,-Wformat]
bech32_charset[type], field_len);
^~~~~~~~~
```
Changelog-None: introduced since last release.
=> common/bolt11: fix 32-bit compilation.

doc/BACKUP.md
Changelog-None
The sections on SQLite Litestream, sqlite3 .dump and VACUUM INTO commands were to be removed six months after 0.10.3, due to issues observed in #4857.
We now recommend using --wallet=sqlite3://${main}:${backup} instead.
=> doc: remove sections on litestream, .dump and vacuum into

doc/lightning-sql.7.md, plugins/sql.c, tests/test_closing.py, tests/test_plugin.py
Changelog-None: sql plugin is new in this release.
=> Sql plugin fix (plus flake fix I found along the way)

connectd/connectd.c, connectd/connectd.h, connectd/connectd_wire.csv, connectd/multiplex.c, lightningd/connect_control.c, lightningd/connect_control.h, lightningd/lightningd.c, lightningd/test/run-find_my_abspath.c, lightningd/test/run-invoice-select-inchan.c
This seems a no-brainer addition, to help with the issues described in #5932 
Changelog-None
=> Stop new connections on shutdown

doc/Makefile, plugins/Makefile
Fixes: #5940
Changelog-None: introduced this release
=> Makefile: don't try to build sql plugin if there's no sqlite3 support.

SECURITY.md
Added Alex since he's Release Captain this time.
Closes: #5686
=> SECURITY.md: Tell them to spam me, and include our GPG fingerprints.

common/initial_commit_tx.h, tests/test_connection.py, tests/test_gossip.py, tests/utils.py
It seems to be missing some overhead; adjust it to be closer to what it really is and adjust tests as required.
Changelog-None
=> More accurate elements commitment tx size estimation

plugins/.gitignore
This is just a cleanup to avoid pushing binary in the repository
=> ignore sql plugin binary

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml
=> meta: Add changelog for 23.02rc1

CHANGELOG.md
=> meta: Add changelog for 23.02rc2

LICENSE
=> Change year to 2023 in LICENSE

CHANGELOG.md
=> meta: Update changelog for 23.02rc3

wallet/db.c
Missed a DEFAULT in the db clause.
Feb 15 16:02:12 citrine lightningd[902093]: Accessing a null column lease_satoshi/15 in query SELECT  funding_tx_id, funding_tx_outnum, funding_feerate, funding_satoshi, our_funding_satoshi, funding_psbt, last_tx, last_sig, funding_tx_remote_sigs_received, lease_expiry, lease_commit_sig, lease_chan_max_msat, lease_chan_max_ppt, lease_blockheight_start, lease_fee, lease_satoshi FROM channel_funding_inflights WHERE channel_id = ? ORDER BY funding_feerate
Fixes #6016
=> db-fix: update NULL lease_satoshi fields to zero

plugins/sql.c, tests/test_plugin.py
TIL we do not run openchannel("v2") tests in CI!  Oops.
=> Fix sql crash, update test, make it run under CI

contrib/reprobuild/Dockerfile.bionic, contrib/reprobuild/Dockerfile.focal, contrib/reprobuild/Dockerfile.jammy
Reported-by: Alex Myers @endothermicdev
=> repro: Add `protoc` dependency to repro-build

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml
=> meta: update changelog and pyln version for 23.02 release

doc/MAKING-RELEASES.md, doc/REPRODUCIBLE.md
Added clarification for sums signing, file ownership, and pyln publishing as well as a reminder to update pyln version for the release.
Changelog-None
=> doc: update release procedure

.gitmodules
This reintroduced lnprototest after 2 releases,
there was a lot of breaking around it and this
will patch them (most of them)!
However, there are issues related to channel opening and 
closing that needs some additional love and is disabled for now, 
but I think it is good to introduce lnprototest now again in the CI,
to be able to stress the fix for now and see if there are other problems around.
I will take care of it!
Fixes https://github.com/ElementsProject/lightning/issues/5683
Fixes https://github.com/ElementsProject/lightning/issues/5755
P.S: This also makes the debugging of lnprototest more lovely in the CI, each test failure will report 
the cln log on to the terminal
=> fix: partial fix lnprototest runner

doc/lightning-listfunds.7.md
Introduced in https://github.com/ElementsProject/lightning/pull/6029 but not autogenerate, worried about why the CI did not check it
Any idea @cdecker ?
=> docs: update autogenerate file

doc/lightning-commando-listrunes.7.md
=> doc: fix commando-listrunes SHA256SUM line.

common/daemon.c, common/daemon.h, connectd/connectd.c, connectd/connectd.h, connectd/connectd_wire.csv, connectd/handshake.c, connectd/handshake.h, connectd/multiplex.c, connectd/peer_exchange_initmsg.c, connectd/peer_exchange_initmsg.h, connectd/test/run-initiator-success.c, connectd/test/run-responder-success.c, contrib/pyln-testing/pyln/testing/utils.py, devtools/gossipwith.c, lightningd/connect_control.c
This resurrects some long-standing connectd checks I had, which are useful for CI as well (no change in production).
Changelog-None
=> Connectd UNUSUAL message fix, and more fd debugging infra

lightningd/peer_htlcs.c
We were debugging a number of issues related to the forwarding logic, when using public scids on private channels, and we noticed that we are very verbose everywhere, except where it counts, i.e., what decisions are being taken. So we add a couple of debug logs, and a final info one that tells the operator which resolution was chosen in the end.
Changelog-None
=> ld: Add a couple of logging statements when forwarding

lightningd/lightningd.c, tests/test_closing.py, tests/test_misc.py
This does not fix the CI hang, but it contains other CI fixes.
Changelog-None
=> Fix CI flakiness

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml
Changelog-None
[23.05rc1]: https://github.com/ElementsProject/lightning/releases/tag/v23.05rc1
=> meta: Add changelog for 23.05rc1

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml
=> meta: update changelog and pyln version for 23.05 release

doc/lightning-listconfigs.7.md
Removes the duplicate "wumbo" key from listconfis.7
Changelog-None
=> doc: remove duplicate wumbo key from listconfigs

.github/scripts/setup.sh, .github/workflows/bsd.yml, .github/workflows/ci.yaml, .github/workflows/macos.yaml
cc @instagibbs 
Changelog-None
=> ci: use Bitcoin Core 24.1

common/test/run-param.c, contrib/pyln-testing/pyln/testing/utils.py, tests/test_wallet.py
Testing that the outputs that are created match expected, and added a unit test for invalid addresses from the BIP
=> Add some additional bech32(m) testing

db/bindings.c
In conjunction with https://github.com/ElementsProject/libwally-core/pull/399 this may make diagnosing issues like https://github.com/ElementsProject/lightning/issues/6185 much easier.
=> db_col_tx: report txn hex if transaction pulled is invalid

.github/scripts/setup.sh, .github/workflows/bsd.yml, .github/workflows/ci.yaml, .github/workflows/macos.yaml
=> ci: use Bitcoin Core 25.0

bitcoin/psbt.c
cc: @instagibbs 
Changelog-None: internal cleanups
=> psbt: minor wally cleanups

doc/MAKING-RELEASES.md
- Removed Libera and added Discord announcement
- Added blog post release and tweet step
Changelog-None
=> doc: making release document update

lightningd/plugin.c
defaults were deprecated in 0df97547dd13dff42b512fb48aa7a9b74017d891, but that was a bit harsh as several plugins do that (summary, for example).  So allow false, but warn that we ignore anything else.
Reported-by: @microsatoshi on Discord.
=> lightningd: allow `false` as a default for flags.

README.md, contrib/config-example
@vincenzopalazzo I closed the last PR since I updated my branch incorrectly, sorry. I'm resubmitting the PR with your suggestions and the fixes implemented.
=> Added sample config and amended it to README

lightningd/channel_control.c, tests/test_misc.py, tests/test_plugin.py
One is a real (but trivial, as it's on shutdown) crash
=> More test flakes

.github/workflows/bsd.yml, .github/workflows/ci.yaml, .github/workflows/macos.yaml, .github/workflows/prototest.yaml, .github/workflows/pypi.yml, CHANGELOG.md, cln-grpc/proto/primitives.proto, common/bolt11.c, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyln/client/lightning.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyln/proto/message/__init__.py, contrib/pyln-proto/pyproject.toml, doc/Makefile, lightningd/invoice.c, plugins/pay.c, tests/test_invoices.py, tests/test_pay.py, tests/test_wallet.py, wallet/walletrpc.c
YA bugfix release, please review carefully!
=> Release 23.05.2

.gitignore, Dockerfile, contrib/docker/Dockerfile.arm32v7, contrib/docker/Dockerfile.arm64v8, contrib/reprobuild/Dockerfile.bionic, contrib/reprobuild/Dockerfile.focal, contrib/reprobuild/Dockerfile.jammy, doc/MAKING-RELEASES.md, doc/REPRODUCIBLE.md, tools/build-release.sh, tools/repro-build.sh
Once was https://github.com/ElementsProject/lightning/pull/6367
=> Build release docs

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml
These are the changes which were in the 23.05.2 branch, and not here.
=> Updates from 23.05.2

Makefile, tests/test_gossip.py
Recent cppcheck doesn't like our code; until we fix that, make it easy to run every other source check.
=> Makefile: check-source-no-cppcheck.

cln-rpc/src/primitives.rs
Added PartialEq for ChannelState enum which allows basic operations with channel states.
Changelog-None
=> Partial eq

lightningd/pay.c
Looks like there was a PR that was merged without being rebased on top of master first. Don't to that!
Changelog-None
=> pay: Fix a non-rebased PR merge error

SECURITY.md
Seems important to fix this typo.
=> SECURITY.md: fix email address

common/Makefile, common/trace.c, common/trace.h, configure, doc/developers-guide/tracing.md, lightningd/Makefile, lightningd/bitcoind.c, lightningd/chaintopology.c, lightningd/jsonrpc.c, lightningd/lightningd.c, lightningd/test/run-find_my_abspath.c, lightningd/test/run-jsonrpc.c, wallet/test/Makefile, wallet/test/run-db.c, wallet/test/run-wallet.c, wallet/wallet.c
This is as experimental as it gets, but I had some fun trying to shoehorn a tracing library into CLN. Putting it here so I don't lose it, and hopefully get some feedback on the API.
Ideally I'd love to integrate closer with `io_loop`, namely having it suspend and resume based on the `io_plan` automatically so users don't have to when suspending on a higher level. Then it boils down to starting and ending spans at the entry and exit point of logical calls.
=> Opentracing library

doc/contribute-to-core-lightning/contributor-workflow.md
=> Update dead links in contributor workflow doc

contrib/pyln-testing/pyln/testing/utils.py, plugins/Makefile, tests/test_closing.py, tests/test_gossip.py
=> More test flake fixes

plugins/clnrest/README.md, plugins/clnrest/clnrest.py, plugins/clnrest/requirements.txt
plugin/clnrest: updated readme instructions and comments.
Changelog-None
=> Clnrest readme and comments updates

contrib/startup_regtest.sh
Bash script `contrib/startup_regtest.sh` checks if the environment variable `PATH_TO_BITCOIN` is set, and if not it selects a default value for it `$HOME/.bitcoin`. The check is meant to allow `regtest` tests to run bitcoin on custom paths; for example `PATH_TO_BITCOIN=/tmp/bitcoin`. 
However, the script further on does not use `PATH_TO_BITCOIN` to start `bitcoind`, or to start `lightnind`. 
As a result, `bitcoind` will always run on `$HOME/.bitcoin` and `PATH_TO_BITCOIN` has no effect in the execution of the commands.
This PR fixes this. By initializing `bitcoind` with the flag `-datadir=$PATH_TO_BITCOIN` and `lightningd` with the flag `--bitcoin-datadir=$PATH_TO_BITCOIN`. 
After this fix, `PATH_TO_BITCOIN` is actually used and the user can define it before executing …
=> use of PATH_TO_BITCOIN in regtest

Dockerfile, contrib/docker/Dockerfile.arm32v7, contrib/docker/Dockerfile.arm64v8, contrib/docker/Dockerfile.builder.fedora, plugins/clnrest/requirements.txt, tools/build-release.sh
- Building pyln in Docker image
- Added clnrest dependencies
Changelog-None
=> Docker pyln clnrest images

.github/workflows/rdme-docs-sync.yml, doc/beginners-guide/beginners-guide.md
=> fix workflow file and test changes

.github/workflows/rdme-docs-sync.yml, doc/developers-guide/tracing-cln-performance.md
=> fix readme workflow (yet again) and test a dummy change

.github/workflows/rdme-docs-sync.yml
=> Fixing env reference for API key and path to doc

doc/lightning-multifundchannel.7.md
=> doc: give an example for multifundchannel

Dockerfile, contrib/docker/Dockerfile.arm32v7, contrib/docker/Dockerfile.arm64v8, contrib/docker/Dockerfile.builder.fedora, contrib/reprobuild/Dockerfile.focal, contrib/reprobuild/Dockerfile.jammy, plugins/clnrest/requirements.txt, tools/build-release.sh
=> Install clnrest dependencies from rquirements.txt in Dockerfiles

lightningd/log.c, tests/plugins/log.py, tests/test_misc.py
Changelog-None: regression since last release
Fixes https://github.com/ElementsProject/lightning/issues/6503
=> Logging filter fix

channeld/channeld.c, common/test/run-codex32.c, plugins/renepay/test/run-payflow_map.c
Reported-by: Shahana
Changelog-None: since master.
=> build: more 32-bit printf fixes.

.github/scripts/sync-rpc-cmds.py, .github/workflows/readme-rpc-sync.yml, doc/developers-guide/tracing-cln-performance.md, doc/lightning-offer.7.md
=> Add workflow and script to sync rpc command files to docs

channeld/channeld.c
This make ACINQ seize up, and not send revoke_and_ack.  Eventually, this can cause a bad signature error, should payments go in both directions, which is a separate bug, but this is the trigger.
See: #6500
=> channeld: don't send splice TLV fields unless negotiated.

lightningd/plugin.c, tests/test_plugin.py
Suggested-by: @Lagrang3
Fixes https://github.com/ElementsProject/lightning/issues/6493#issuecomment-1667236524
=> renepay: allow it to die gracefully without crashing lightningd.

.github/scripts/sync-rpc-cmds.py
=> fix flake8 errors in the script file

.github/workflows/pypi.yml
Cut & paste bug from test repo section?
Changelog-None: infrastructure
=> Pypi: publish to real repository.

channeld/channeld.c
There is a small chance these can fire during a splice or other STFU mode activity which shouldn’t be allowed to happen.
Could be causing Issue #6551
=> splice: STFU -> disable announce and commit timers

.github/workflows/ci.yaml, channeld/channeld.c, common/sphinx.c, common/test/run-bolt12_decode.c, lightningd/runes.c, plugins/renepay/payment.c
First commit makes one of the CI runs build with -O3 so these don't creep in in future.
=> Various -O3 fixes

doc/getting-started/getting-started/installation.md
Needed to change a few things to get CLN building on a fresh NixOS box.
Ideally we'd move this over to a flake.nix for devshell etc.
=> nixos install: tweaks to get CLN building from fresh start

CHANGELOG.md
"This time for sure!"
There are outstanding issues with splicing and renepay, but they're both experimental and under active development, so :shrug:!
=> CHANGELOG.md: Update for -rc3

plugins/.gitignore
This is just a meta work that helps to fix the error that I found 
while review the https://github.com/ElementsProject/lightning/pull/6585
=> meta: ignore renepay binary 

contrib/docker/Dockerfile.arm32v7
=> docker: bookworm image for arm32v7

doc/beginners-guide/backup-and-recovery.md
As discussed with @ShahanaFarooqui, I have added 2 sections in backup-and-recover.md to explain in detail how to use emergencyrecover and --recover so that users can use it effectively.
=> Update backup-and-recover.md with the info about emergencyrecover and --recover.

Cargo.lock, Cargo.toml, cln-grpc/Cargo.toml, cln-rpc/Cargo.toml, plugins/Cargo.toml, plugins/grpc-plugin/Cargo.toml
=> rs: Bump crate versions before publishing

doc/getting-started/getting-started/installation.md
How and where to extract the binaries has come up on Discord at least a couple of times. Hopefully this tip will help.
=> doc: add tip on extracting binary release

.dockerignore
Make it smoother to debug docker images.
=> Dockerfiles must not invalidate the docker cache

README.md
This sort of thing should also be in release notes: https://github.com/ElementsProject/lightning/releases/tag/v23.08
=> doc: update to reflect new bitcoind requirement

configure
Fix typo in configure script
ChangeLog-None
=> configure: typo fix

doc/beginners-guide/backup-and-recovery/advanced-db-backup.md, doc/beginners-guide/backup-and-recovery/hsm-secret.md, doc/beginners-guide/beginners-guide.md, doc/developers-guide/app-development.md, doc/developers-guide/app-development/rest.md
=> fix paths for doc files and make them public

doc/developers-guide/app-development/rest.md, doc/lightningd-config.5.md, plugins/clnrest/clnrest.py, plugins/clnrest/requirements.txt, plugins/clnrest/utilities/generate_certs.py, plugins/clnrest/utilities/rpc_plugin.py, plugins/clnrest/utilities/rpc_routes.py, plugins/clnrest/utilities/shared.py
- Generating three certs (CA, client and server) if they do not exist already
- Added rune authentication for websocket server as well
- Added two new clnrest config options for CORS and CSP headers
Changelog-Added: New configurable Content-Security-Policy (CSP) header for clnrest
Changelog-Added: New configurable Cross-Origin-Resource-Sharing(CSP) header for clnrest
=> plugin/clnrest: security improvements

wallet/test/run-db.c, wallet/test/run-wallet.c
=> wallet/test: regenerate mocks to fix build.

cln-grpc/proto/primitives.proto, cln-rpc/src/primitives.rs
I think there is more missing within cln-grpc but i wasnt 100% sure so this pr only has the ones for cln-rpc
=> add CHANNELD_AWAITING_SPLICE state to cln-rpc

channeld/channeld.c
=> channeld: comment typo fix

connectd/connectd.c
On Mac most tests report BROKEN because sodium creating an untracked fd pointing to /dev/random. dev_report_fd’s finds it at tear down and reports a BROKEN message.
Tracking the fd used by sodium allows us to squeltch this message and make tests more usable on Mac.
While we’re here we added the fd mode to the log to help with future rogue fd issues.
ChangeLog-None
=> connectd: Track sodium_fd for Mac tests

.github/scripts/setup.sh, .github/workflows/bsd.yml, .github/workflows/ci.yaml, .github/workflows/macos.yaml
=> ci: use Bitcoin Core 25.1

poetry.lock, pyproject.toml
The requests module is required by `devtools/changelog.py`
=> Add requests dependency to pyproject.toml

channeld/channeld.c
I think we lost these two deltas while rebasing, apologies ...
=> Fix two splicing/vls omissions

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml, plugins/clnrest/pyproject.toml, poetry.lock
Update changelog, pyln versions, clnrest version and poetry.lock.
I will add another PR adding clnrest and poetry.lock to the release checklist.
=> CHANGELOG.md: Update for 23.11rc1

CHANGELOG.md
Please check the repro builds for this commit and send me your signatures.
=> CHANGELOG.md: Update for 23.11 final

doc/developers-guide/plugin-development/event-notifications.md, doc/developers-guide/plugin-development/hooks.md
- **Commit-1** Fixes the documentation for `invoice_payment` hook and notification.
- **Commit-2** Formatting of json-structs (tabs vs spaces)
=> Doc fix invoice payment hook and notification

doc/getting-started/advanced-setup/bitcoin-core.md, doc/getting-started/getting-started/installation.md, doc/node-operators-guide/analytics.md, doc/node-operators-guide/faq.md
=> fix typos and add suggested edits from community

doc/contribute-to-core-lightning/testing.md, doc/developers-guide/plugin-development/hooks.md
Based upon:
https://dash.readme.com/project/blockstream-core-lightning/v1/suggested/update/655c70ab0077d2003b3b657b
https://dash.readme.com/project/blockstream-core-lightning/v1/suggested/update/655c8b912adff80063e82be8
=> doc: documentation update for hooks and testing

doc/contribute-to-core-lightning/code-generation.md
Set the hidden tag to false and make this article public.
=> Publish code-generation.md

plugins/src/lib.rs
The `cln-plugin` can be used to create a plugin that registers additional rpc-methods. However, it doesn't allow to specify the `usage` of the command.
This change makes it possible to specify the `usage`. It should not contain any breaking changes.
I've opted to add a new method called `rpcmethod_from_builder` to the `Builder` struct. This approach allows us to add new parameters in the future.
=> cln-plugin: Allow setting `usage` of RPC-method

doc/contribute-to-core-lightning/contributor-workflow.md
This is good info to have, that I often forget and have to spend time looking for. It'd be nice to have it documented in the project somewhere so people new the project (or new to maintaining maybe?) know where to find it.
Open to suggestions of other places to put this; totally understandable if it's not useful to have in this repo, particularly.
=> doc: add a nice explainer about how to update PR branches

doc/getting-started/getting-started/configuration.md
Simple addition for completeness
=> Doc: Update configuration.md

plugins/bkpr/bookkeeper.c, plugins/bkpr/db.c, plugins/bkpr/db.h, plugins/bkpr/test/run-bkpr_db.c, plugins/bkpr/test/run-recorder.c, tests/test_bookkeeper.py, tests/test_pay.py
The bookkeeper is unnecessarily noisy. I can fix her :toolbox:
=> bookkeeper, stop spamming to logs

.github/workflows/crate-io.yml
Looks like that my ci configuration was not complete, sorry :/
=> ci: fix the CI configuration for rust release

channeld/channeld.c
Changelog-None: fixes hole in ([#7010]), see ([#7026])
Explicit hsmd_revoke_commitment_tx instead of get_per_commitment_point needed when revokes are retried. The hsmd_revoke_commitment_tx message is idempotent.
=> channeld: use explicit revoke on retry when HSM_VERSION >= 5

doc/developers-guide/app-development/rest.md, doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md, doc/developers-guide/plugin-development/event-notifications.md, doc/developers-guide/plugin-development/hooks.md, doc/lightning-cli.1.md, doc/lightning-decode.7.md, doc/lightning-fundchannel.7.md, doc/lightning-funderupdate.7.md, doc/lightning-listclosedchannels.7.md, doc/lightning-listforwards.7.md, doc/lightning-listpeerchannels.7.md, doc/lightning-listpeers.7.md, doc/lightning-wait.7.md, doc/lightningd-config.5.md, doc/lightningd-rpc.7.md
=> doc: fix typos

doc/developers-guide/plugin-development/event-notifications.md
The previous example was updated.
=> Docfix: connec-notification

tests/test_misc.py
Just a small stabilization of the one test that is giving me a headache.
=> pytest: Stabilize the `test_recover_plugin` test

.gitignore
compile_commands.json helps my editor with intellisense. Gitignore it!
Also clangd creates a .cache directory. Gitignore it!
=> gitignore: Ignore compile_commands.json

ccan/ccan/crypto/siphash24/siphash24.h, channeld/channeld.c
=> fix some typos

tests/test_db.py, tests/test_plugin.py
This can happen, so allow them.
=> pytest: catch more broken messages in test_important_plugins.

doc/developers-guide/plugin-development/bitcoin-backend.md
Fixes https://github.com/ElementsProject/lightning/issues/7294
Trivial doc fix
=> docs: fixing the json response in documentation

plugins/bcli.c, plugins/renepay/mods.c, tests/test_cln_rs.py
=> bcli: fix compilation on 32-bit platforms.

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml, plugins/clnrest/pyproject.toml, plugins/wss-proxy/pyproject.toml, poetry.lock
Added several rc1 PRs to the changelog as well (which I felt deserved an entry even if there was not a Changelog tag included in the commit.)
=> meta: update changelog for 24.05rc2

README.md
- Added badges for BoL2, Telegram and Discord.
- Rearranged chat links.
=> docs: Update chat links

doc/contribute-to-core-lightning/release-checklist.md
=> doc: fixed broken link to `setting-up-multiarchqemu-user-static`

.github/scripts/setup.sh, .github/workflows/bsd.yml, .github/workflows/ci.yaml, .github/workflows/macos.yaml
=> ci: use Bitcoin Core 27.1

.github/scripts/install-bitcoind.sh, .github/scripts/setup.sh, .github/workflows/ci.yaml
We have them spread everywhere: unify them, and make setup.sh use install-bitcoind.sh
Changelog-None
=> CI: set elements and bitcoind versions in one place.

.github/scripts/sync-rpc-cmds.py
Documents which are deleted from lightning schema were still listed on readme server.
This script was adding or updating the list but delete action was missing.
=> script: Adding Delete action for readme docs

Makefile, doc/Makefile, lightningd/Makefile
This has been bugging me for a while, so make our "noop" compilation faster.
=> Speed compilation times

ccan/README, ccan/ccan/io/fdpass/fdpass.c, common/msg_queue.c, connectd/connectd.c, connectd/multiplex.c
Started hitting a flake in test_feerate_stress more regularly, finally chased it down.  And found some other latent bugs along the way...
=> connectd timeout flake fix

contrib/msggen/msggen/schema.json, doc/schemas/lightning-disconnect.json, doc/schemas/lightning-plugin.json
=> doc: Tiny corrections in documentation

lightningd/memdump.c
We ask each channeld to report its leaks, and keep a refcount of how many are outstanding.  When the channeld replies, or dies, we decrement the count in a destructor.
But if the last channeld we're waiting for dies, we can call the destructor in an unexpected place, and thus run leak detection when we were partway through some operation, which gives a false positive. Here's a backtrace showing it:
```
0x5f93405897e3 send_backtrace
0x5f93405381cf finish_report
lightningd/memdump.c:139
0x5f93405382a0 leak_detect_req_done
lightningd/memdump.c:172
0x5f9340705c41 notify
ccan/ccan/tal/tal.c:243
0x5f9340705ca5 del_tree
ccan/ccan/tal/tal.c:437
0x5f9340705ce8 del_tree
ccan/ccan/tal/tal.c:447
0x5f93407061f3 tal_free
ccan/ccan/tal/tal.c:532
0x5f9340563f5a subd_release_channel …
```
=> lightningd: fix false positive in leak detection.

plugins/fetchinvoice.c
In CI, this would sometimes fail: we would timeout waiting for the fetchinvoice reply.  Never happened locally, so was annoying to debug.
What happened was simple: we called injectonionmessage then when it returned, put the "sent" object in the linked list so we could recognize any reply onion messages.
However, we were getting that reply before the plugin processed the response to injectonionmessage.  This is possible because there are two fds for plugins: one for it to receive notifications and hooks (like onion messages) and one for normal RPC usage (like commands to inject onion messages).
The fix is simple: put in the list *before* calling JSON RPC.
This race is unlikely in real life, so no Changelog.  It's probably more likely due to our speedup of IO.
Closes: #7523
=> offers: fix flake in fetchinvoice.

lightningd/onchain_control.c
We used to always target `now() + 300`, which ends up never really
confirming, as the fee estimate bumps into the min-relay-fee
limit. With this commit we set an absolute target of 2 weeks, and a
linear fee rampup, until we are at T-2h, at which point we just stick
with the estimate, and try with this increased feerate to try and get
the sweep confirmed.
This ought to make RBF transactions much more efficient for closing
channels.
Changelog-Changed onchaind: When sweeping funds from channel closes we now use an absolute deadline of 2 weeks, rather than a relative deadline which causes sweeps not confirm for prolonged times.
=> onchaind: Adjust the sweep fee estimation

plugins/askrene/askrene.c, plugins/askrene/askrene.h, plugins/askrene/reserve.c, plugins/askrene/reserve.h
=> Askrene fixup memleak

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml, devtools/.gitignore, devtools/changelog.py, plugins/.gitignore, plugins/clnrest/pyproject.toml, plugins/wss-proxy/pyproject.toml, poetry.lock
Release candidate 1 for v24.08.
=> Release 24.08rc1

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml, plugins/clnrest/pyproject.toml, plugins/wss-proxy/pyproject.toml, poetry.lock
Release candidate 2 for v24.08.
=> Release 24.08rc2

contrib/msggen/msggen/schema.json, doc/schemas/lightning-getroutes.json, plugins/askrene/askrene.c, tests/test_askrene.py
Changelog-None: this is experimental anyway, and introduced this release.
=> getroutes updates

.github/PULL_REQUEST_TEMPLATE.md
=> git: Update PR template

.github/workflows/pypi.yml
>
>
Changelog-Fixed: Fixed the already existing Pypi publishing actions file.
=> Update Github actions for Pypi publishing

doc/beginners-guide/backup-and-recovery/advanced-db-backup.md
=> docs: Added info for NFS version for db backup

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml, plugins/clnrest/pyproject.toml, plugins/wss-proxy/pyproject.toml, poetry.lock
>
>
Release candidate 3 for v24.08
=> meta: Update changelog for 24.08rc3

CHANGELOG.md
=> meta: Add changelog for hotfix release v24.08.1

gossipd/gossmap_manage.c
The "init_cupdate" message is for gossipd to tell lightningd about our *own* latest channel_update messages, not the remote ones!  The "remote_channel_update" message is for messages from the peer.
This appeared as an occasional BROKEN message in CI:
```
**BROKEN** 035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d-chan#4: gossipd gave us channel_update for channel in gossip_state CGOSSIP_NEED_PEER_SIGS
```
Where we had sent (and not received) announcement_signatures, and restarted: the peer had meanwhile sent us their channel_announcement and channel_update.
=> gossipd: at startup don't send remote channel_update as init update from us

CHANGELOG.md, contrib/pyln-client/pyln/client/__init__.py, contrib/pyln-client/pyproject.toml, contrib/pyln-proto/pyln/proto/__init__.py, contrib/pyln-proto/pyproject.toml, contrib/pyln-testing/pyln/testing/__init__.py, contrib/pyln-testing/pyproject.toml, plugins/clnrest/pyproject.toml, plugins/wss-proxy/pyproject.toml, poetry.lock
=> release: Update the changelog for point release v24.08.2

README.md
* fix a typo about the number of supported installation options
* ONLY 3 are enumerated before
=> doc(README.md): fix typo about supported installation options

doc/schemas/lightning-openchannel_abort.json
=> docs: openchannel_abort correction

contrib/msggen/msggen/schema.json
Looks like https://github.com/ElementsProject/lightning/pull/7762 forgot to re-run `msggen`. Here is the updated `schema.json` file to hopefully fix the build.
> [!IMPORTANT]
=> docs: Fix openchannel_abort generated JSON schema.

.github/PULL_REQUEST_TEMPLATE.md
=> Github: Belated warning about 24.11 freeze.

tests/test_closing.py, tests/test_pay.py
=> More CI flake fixes

contrib/msggen/msggen/schema.json, doc/Makefile, doc/index.rst, doc/schemas/lightning-askrene-age.json, doc/schemas/lightning-askrene-bias-channel.json, doc/schemas/lightning-askrene-create-channel.json, doc/schemas/lightning-askrene-create-layer.json, doc/schemas/lightning-askrene-disable-node.json, doc/schemas/lightning-askrene-inform-channel.json, doc/schemas/lightning-askrene-listlayers.json, doc/schemas/lightning-askrene-listreservations.json, doc/schemas/lightning-askrene-remove-layer.json, doc/schemas/lightning-askrene-reserve.json, doc/schemas/lightning-askrene-unreserve.json, doc/schemas/lightning-askrene-update-channel.json, doc/schemas/lightning-getroutes.json, plugins/askrene/askrene.c, plugins/askrene/askrene.h, plugins/askrene/layer.c, plugins/askrene/layer.h, plugins/askrene/mcf.c, tests/test_askrene.py
@cdecker particularly asked for a way to bias against certain nodes/channels, so this adds that.  It also makes sense for biassing against slow nodes, for example.
@Lagrang3 might have interesting things to say about my bias function :)
=> Askrene refinements: better documentation, channel biases

tests/test_reckless.py
=> ci: Fix reckless source paths

common/gossip_constants.h, lightningd/options.c, lightningd/plugin.c, plugins/askrene/layer.c, plugins/xpay/xpay.c, tests/test_connection.py, tests/test_gossip.py, tests/test_misc.py, tests/test_pay.py, tests/test_plugin.py
=> more flake fixes

contrib/msggen/msggen/schema.json, doc/schemas/lightning-commando.json, doc/schemas/lightning-getinfo.json
Temporary fix for the broken pre-build CI. The permanent fix will be merged with #7872. 
=> doc: pre-build CI fix due to newly tagged version

contrib/startup_regtest.sh
Came for the grpc clash, found the clnrest issue...
=> Fix startup_regtest script

doc/contribute-to-core-lightning/release-checklist.md, doc/getting-started/advanced-setup/repro.md
=> doc: Update info on 'cl-repro' script

plugins/xpay/xpay.c, tests/test_xpay.py
=> xpay maxfee fix

CHANGELOG.md
Changelog-None: The changelog itself was changed.
=> CHANGELOG: update for rc3.

common/status.c, contrib/pyln-testing/pyln/testing/utils.py, gossipd/gossmap_manage.c, tests/autogenerate-rpc-examples.py
This should help https://github.com/ElementsProject/lightning/issues/7899 though I'm not sure why their node isn't quickly gossip-synced?
=> Quieten gossipd

lightningd/pay.c, tests/test_xpay.py
Thanks @michael1011 for the report!
=> xpay unannounced chan fix

plugins/xpay/xpay.c, tests/test_xpay.py
Closes: #7949 (included)
Fixes: #7947 
Changelog-None: covered by existing Changelog messages
=> Xpay more compatibility

tools/repro-build.sh
=> ci: Fix for reproducible noble build failure

gossipd/gossmap_manage.c
=> gossipd: fix typo

plugins/offers.c, plugins/topology.c, tests/test_pay.py
=> Fix blinded path peer selection

.github/workflows/pypi.yml, Dockerfile, tools/build-release.sh
=> Ci build fixes

README.md
=> docs: Remove lightning-dev mailing list from README

README.md, SECURITY.md
=> docs: Update Security Information

common/trace.c
chanbackup with many peers can do more than 128 concurrent rpc commands. autoclean is the other plugin which can do many requests at once, so I expect a similar issue there.
I tested this by rebuilding with `MAX_ACTIVE_SPANS` 1, which autoclean tests triggered immediately.
The real fix is probably to use a hash table with a large initial size.
```
Mar 24 06:30:45 mlbb2 sh[28000]: chanbackup: common/trace.c:190: trace_span_slot: Assertion `s' failed.
Mar 24 06:30:45 mlbb2 sh[28000]: chanbackup: FATAL SIGNAL 6 (version v25.02)
Mar 24 06:30:45 mlbb2 sh[28000]: 0x5575232bac4f send_backtrace
Mar 24 06:30:45 mlbb2 sh[28000]:         common/daemon.c:33
Mar 24 06:30:45 mlbb2 sh[28000]: 0x5575232baceb crashdump
Mar 24 06:30:45 mlbb2 sh[28000]:         common/daemon.c:78
Mar 24 06:30:45 mlbb2 …
```
=> trace: minimal fix to avoid crash when > 128 traces active.

.github/PULL_REQUEST_TEMPLATE.md
=> doc: Update May release dates

contrib/pyln-testing/pyln/testing/fixtures.py, tests/test_opening.py, tests/test_pay.py
This is my version of https://github.com/ElementsProject/lightning/pull/8262 which I did in parallel.
Changelog-None
=> More test fixes

gossipd/seeker.c
Reported-by: JssDWt
Closes: https://github.com/ElementsProject/lightning/issues/8200
Changelog-None: trivial
=> gossipd: don't try to connect to ourselves if we need more peers.

contrib/pyln-testing/pyln/testing/utils.py, tests/test_connection.py, tests/test_opening.py, tests/test_pay.py
=> Fix flakes18

channeld/channeld.c
Handle a specific corner case where Eclair expects us to re-send splice_locked.
Changelog-None
=> splice: Eclair Interop — reestablish corner case

devtools/Makefile, devtools/gossipwith.c, lightningd/channel_gossip.c, tests/test_gossip.py
=> Gossip flake fixes

tools/repro-build.sh
=> ci: Shasums updated for libsqlite in Ubuntu Noble

doc/lightning-cli.1.md, plugins/bkpr/README.md, plugins/renepay/mcf.h
> [!IMPORTANT]
>
> 25.09 FREEZE July 28TH: Non-bugfix PRs not ready by this date will wait for 25.12.
>
> RC1 is scheduled on _August 11th_
>
> The final release is scheduled for September 1st.
fix some minor issues
Changelog-None: typo fixes only
=> chore: fix some minor issues

.github/workflows/release.yml, contrib/docker/Dockerfile.builder.fedora, contrib/reprobuild/Dockerfile.focal, contrib/reprobuild/Dockerfile.jammy, contrib/reprobuild/Dockerfile.noble, tools/build-release.sh
- Updates rust version from 1.75 to 1.85 for Ubuntu
- Poetry to UV update for Fedora
- Removed fetch-tag from release github action to be able to checkout the tag without conflict
=> Fix reproducible build errors

common/coin_mvt.c, contrib/msggen/msggen/schema.json, doc/schemas/listchannelmoves.json, tests/test_bookkeeper.py, tests/test_coinmoves.py, wallet/account_migration.c
I did an account migration on my node, and this fixes two of the issues.  I've asked Lisa to look at the other differences, to make sure they're OK.
Changelog-None
=> Fix account migration issues

.github/PULL_REQUEST_TEMPLATE.md, Makefile, tests/test_pay.py, tests/test_xpay.py
- Update CLN_NEXT_VERSION
- Update PR template
Changelog-None: release stuff
=> Post release v25.09
