ElementsProject/lightning

tests/conftest.py

Silence pytest warning about unknown mark.

pytest: silence pytest warnings about unregistered 'slow_test' marker

---

doc/PLUGINS.md
lightningd/peer_htlcs.c
tests/plugins/htlc_accepted-failonion.py
tests/test_plugin.py

I need this feature to be able to use "shadow" last hops with fake nodes on [@lntxbot](https://t.me/lntxbot) and [Etleneum](https://etleneum.com) and return proper `incorrect_or_unknown_payment_details` for the pre-pay probes with the wrong `payment_hash` that Zap, Strike and BoS wallets send. These wallets will not attempt the actual payment if the pre-pay probe fail with any other error -- and it must come from the final destination, which means that in my case I must parse `onion.next_onion` and extract the ephemeral key, compute the shared secret then encode the onion and return it in the special field `"failure_onion"` this PR introduces.
The above paragraph is just for the context.
In reality a feature like this is also necessary if we are to write plugins that interface between two …

optional "failure_onion" in reply to htlc_accepted hook.

---

lightningd/plugin_control.c

This adds a missing `plugins_send_getmanifest()` call in the rescan function
that lead to a RPC hangup. Not sure though if this is the proper fix.
Addresses https://github.com/ElementsProject/lightning/issues/4176
Changelog-None

fix: hangup in plugin rescan

---

lightningd/channel.c
tests/test_connection.py
tests/test_plugin.py

Currently we set the `lightning-cli listpeers` channel `closer` to `null` if we have been offline and detected a force closed channel on us. This was because in theory it could have been ourself that used some scratching/recovery script for our private keys. Since this is topmost unlikely scenario, especially since someone doing this would certainly not fire up the daemon again and expect it to do something useful, we are better of to set the `closer` to `remote` as it should be.

fix: channel closer on unilateral to remote

---

tests/test_plugin.py

It seems like all we're really trying to do is test that we load more than one plugin from a directory. Using the `test/plugins` directory is a miserable idea, as new additions tend to clobber each other (and some only get loaded if experimental is turned on). Instead, we use the more mundane `contrib/plugins` folder.
Alternately, we can probably remove this test entirely, as the first load tests the exact thing (and actually verifies they're used).

pytest: use the 'contrib' plugin set, not the 'test' set

---

connectd/connectd.c
tests/plugins/slow_start.py
tests/test_connection.py

If we're already attempting to connect to a peer, we would ignore
new connection requests. This is problematic if your node has bad
connection details for the node -- you can't update it while inflight.
This patch appends new connection suggestions to the list of connections
to try.
Fixes #4154
Changelog-None

connectd: Update connection list with new address

---

plugins/libplugin-pay.c
plugins/libplugin-pay.h

Due to the asynchronous `getroute` and `createonion` calls we were issuing multiple concurrent `getroute` calls for multi-part payments. This is particularly painful with the `presplit` modifier which causes all of the initial parts to be scheduled at the same time, competing for a route.
Since #4093 we no longer have an asynchronous call to `getroute` which alleviates the problem, but doesn't resolve it: `createonion` is still asynchronous and we were only updating the channel_hints after it was called. In addition plugins can yield control of the `io_loop` if they perform any asynchronous RPC call, resulting in the same issue again.
This PR moves the application of the route to the channel_hints up to just before the `createonion` call, which makes the route creation and postprocessing …

pay: Avoid clobbering the channel_hints at all costs

---

CHANGELOG.md
lightningd/plugin.c

This effectively reverts ac93b780d5a457f8f304d658e80b4d531fb3b0e4.
Christian points out that plugins need time before we deprecate
the old options (probably 6 months) as they need to work with
both old and new.
Changelog-Deprecated: **UNDO** plugins: hooks should now be specified using objects, not raw names.
Suggested-by: @cdecker

plugins: undeprecate old form of hooks.

---

lightningd/lightningd.h

Remove `pid_fd` from `struct lightningd` since `pid_fd` is not used anywhere.

lightningd: remove unused pid_fd member in struct lightningd

---

common/htlc.h

Drive by fixup.
Changelog-None

htlc.h: move NUM_SIDES to define, not enum member

---

common/psbt_open.c
common/psbt_open.h
doc/lightning-openchannel_update.7
doc/lightning-openchannel_update.7.md
lightningd/dual_open_control.c
openingd/dualopend.c
plugins/Makefile
plugins/spender/main.c
plugins/spender/multifundchannel.c
plugins/spender/multifundchannel.h
plugins/spender/openchannel.c
plugins/spender/openchannel.h
requirements.txt
tests/plugins/df_accepter.py
tests/test_connection.py

This PR is ambitious in the absolute.
First, we add functionality for how to handle v2 openchannel destinations to `multifundchannel`.
(This will allow us to seamlessly use `fundchannel` to open v2 channels.)
Then, we merge the v2 and v1 of 'openchannel' protocols under the multifundchannel
umbrella, such that you can request to open channels with a plurality
of nodes using `multifundchannel` and it will just *do the right thing*
under the hood.
This requires a bit of finesse, as these two RPC protocols must be
interleaved correctly.
`multifundchannel` first gets a 'starter' PSBT from c-lightning.
This remains unchanged.
Then, we go ahead and start calling the init/start functions for each
peer (we can tell which is the appropriate protocol to use depending
on the feature flags set on the …

Dual-funding over multi-channels

---

external/Makefile

And get rid of the now-obsolete PYTHON_VERSION hack.

libwally: update to latest which uses libsecp-zkp submodule

---

bitcoin/psbt.c
bitcoin/tx.c

Just a minor nit now that wally supports clearing structs on PSBT members.

tx: Remove wally workaround that is no longer needed

---

doc/PLUGINS.md
lightningd/plugin.c
lightningd/plugin.h
lightningd/plugin_hook.c
tests/plugins/dbdummy.py
tests/test_plugin.py

Support multiple plugins hooking into `db_write`

---

external/Makefile
tools/refresh-submodules.sh

external/Makefile: fix parallel build with missing secp headers.

---

contrib/pyln-testing/pyln/testing/utils.py
tests/test_plugin.py

Since we are already using `10**6` as default amount on e.g. `line_graph` we could also use this for fundchannel and openchannel. This makes testcases where we e.g.  link a circle using `line_graph` a tiny bit simpler.

pyln: default fundamount for fundchannel and openchannel

---

contrib/pyln-client/pyln/client/lightning.py
contrib/pyln-client/tests/test_units.py

Currently we are not able to create pyln Millisatoshi from floats, e.g.:
- "0.01btc"
- "0.1sat"
- ...
This adds a test that is currently expected to fail because of this bug.
Changelog-None

pyln: failing test msat from float str

---

Makefile
ccan/README
ccan/ccan/utf8/test/run-decode.c
ccan/ccan/utf8/utf8.c
ccan/ccan/utf8/utf8.h
common/bolt11.c
common/json.c
common/json.h
common/json_tok.c
common/test/run-bolt11.c
common/test/run-json.c
common/utils.c
common/utils.h
gossipd/routing.c
lightningd/test/run-jsonrpc.c
plugins/libplugin.c
plugins/libplugin.h

Misc stuff which happened on the way to offers.

Simple misc cleanups

---

lightningd/invoice.c

We register on it for offers, and without this nobody else can.
Changelog-Changed: plugins: more than one plugin can now register invoice_payment hook.

invoice: make invoice_payment hook a multi-user hook.

---

lightningd/log.c
tests/test_misc.py

Fixes: #4240 
I also had all signals blocked while in the SIGHUP handler, for additional safety.

Fix sighup

---

lightningd/invoice.c
lightningd/test/run-invoice-select-inchan.c
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/invoices.c
wallet/invoices.h
wallet/statements_gettextgen.po
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

There's actually a (very unlikely) race here: we would previously have
crashed with an assertion in invoices_resolve.
Changelog-None

invoice: fix potential race where invoice is paid/expired while we're calling hook

---

channeld/channeld.c

```
channeld/channeld.c:237:2: error: ‘shutdown_status’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
```
Reported-by: az0re on IRC
Changelog-None

channeld: fix gcc warning on gcc 8.3.0 (Debian 8.3.0-6)

---

contrib/pyln-testing/pyln/testing/fixtures.py
contrib/pyln-testing/pyln/testing/utils.py
lightningd/peer_htlcs.c

Upgraded builder, and it doesn't work any more.  Suggested by @achow101 that we make older versions behave like new ones, with `-nowallet`.
Also found an unrelated taken() leak while testing.
Changelog-None

pytest: recreate wallet on bitcoind restart (for master branch of bitcoind)

---

plugins/.gitignore

A binary is missing in plugins/.gitignore: txprepare. This means that when someone tries to modify the project with the compiled binaries, txprepare binary is added to their commit.

Add txprepare to plugins/.gitignore

---

doc/lightning-listpeers.7
doc/lightning-listpeers.7.md
lightningd/peer_control.c
lightningd/test/run-invoice-select-inchan.c
tests/test_pay.py

As mentioned in the last developer meeting and additional to #4221 we want to have the local half-channel fees (the ones that are applied when a payment is routed though our node) as part of the `listpeers` output. Motivation is that this data is non-gossip and currently only available via gossip `listchannels`.
Example
```
{
...
"fee_base_msat" : "100msat",
"fee_proportinal_millionths" : 1000,
...
}
```
This PR adds feature, test and doc.

feat: fees on listpeers rpc output

---

tests/test_connection.py

This test has been causing most CI runs to fail. See tracking issue #4265
for discussion on fixing and re-enabling it.

pytest: Disable flaky test_fundchannel_start_alternate

---

channeld/channeld.c

While debugging a hanging channel with a user I noticed that they
called `close` on a channel, resulting in the channel showing
`CHANNELD_SHUTTING_DOWN`, but the billboard seemed to show the
information the wrong way around:
```json
{
"peers": [
{
"connected": true,
// ...
"channels": [
{
"state": "CHANNELD_SHUTTING_DOWN",
// ...
"status": [
"CHANNELD_SHUTTING_DOWN:Reconnected, and reestablished.",
"CHANNELD_SHUTTING_DOWN:Funding transaction locked. They need our announcement signatures. They've sent shutdown, waiting for ours"
],
// ...
}
]
}
]
}
```
Aside from the hung channel, the switch in direction of the status
seemed weird. Checking the billboard code seems to have the status
switched as well:
https://github.com/ElementsProject/lightning/blob/ff8830876dc2ead010dc4a6453abb7e30ec637ce …

channeld: Fix the shutdown_sent billboard direction

---

contrib/pyln-client/pyln/client/lightning.py
contrib/pyln-client/tests/test_units.py

I was rethinking PR #4237 and discovered that we are not done yet.
This adds two more xfail'ing testcases to show that the current way of
parsing Millisatoshi decimals is not yet optimal.
Testcases: `test_round_zero` and `test_round_down` fail.
Changelog-None

pyln: extend msat floating testcases

---

bitcoin/tx.h
cli/lightning-cli.c
common/json_helpers.c
common/json_helpers.h
common/json_tok.c
common/json_tok.h
common/param.c
common/test/run-param.c
contrib/pyln-client/pyln/client/lightning.py
lightningd/jsonrpc.c
plugins/txprepare.c
tests/test_wallet.py

There are two issues we address in this PR:
- Broken JSON strings when forwarding params as raw strings to further JSON-RPC calls, causing the infamous `id is null` error because the side receiving the mangled request cannot extract the `id` and returns a generic error instead, which doesn't match up with our expectations.
- Interpreting a string param as an array, resulting in an empty array, and thus only adding the change output to a prepared tx.
In a couple of places we accept arrays of strings and don't validate
them. If we forward them, e.g., call a JSON-RPC method from the
plugin, we end up embedding the unverified string in the JSON-RPC
call without escaping, which then leads to invalid JSON being passed
on.
We were not checking that outputs is indeed an array, and just going …

Improve validation of `txprepare` arguments

---

wallet/reservation.c

Left over from e81d78ec4cad288f1ae42aff935e59e149fb4b9e.
Changelog-None

wallet: remove debugging fprintf.

---

contrib/pyln-proto/pyln/proto/wire.py
contrib/pyln-proto/requirements.txt

I wanted to talk to TOR-based nodes, so here comes TOR support :-)
Changelog-None

pyln: Add TOR and SOCKS5 support in pyln.proto.wire.connect

---

plugins/keysend.c
tests/test_pay.py

We weren't checking whether the recipient supports `keysend` or not before trying to pay. This could lead to rather unhelpful 16399 errors, because the recipient simply doesn't understand what we're trying to do.
This might be the cause for https://github.com/ElementsProject/lightning/issues/3968, but I can't verify that that's the case.
Fixes #3968

Check whether the recipient supports keysend

---

common/test/run-sphinx-xor_cipher_stream.c

Seems that I broke the mocks by merging two PRs that both modified the tests, thus overwriting each others set of mocks.
Changelog-None

tests: Update mocks after breaking them via interleaved merges

---

contrib/pyln-client/pyln/client/lightning.py
contrib/pyln-client/tests/test_units.py

Current implementation does not allow dividing two msat's to get the ratio between them.
It fails with `unsupported operand type(s)`:
```python
from pyln.client import Millisatoshi
foo = Millisatoshi(42) / Millisatoshi(2)
```
- This PR changes this to return the `float` ratio between the two `msat's` for `__truediv__` and an `int` for `__floordiv__`. 
- Also adds an exception and a check that `Millisatoshi(float)` initialization is currently not allowed, except for whole float numbers, e.g. `42.0` this is currently required by some existing testcases: e.g. `tests/test_wallet.py::test_txprepare`
See https://github.com/ElementsProject/lightning/pull/4273#discussion_r540369093).

pyln: fix div with Millisatoshi itself

---

.github/CODEOWNERS
doc/BACKUP.md
doc/FAQ.md
doc/index.rst

Requested by @d4amenace here: https://github.com/ElementsProject/lightning/issues/4200#issuecomment-727642350
@cdecker to finish up the document re: PostgreSQL.  I remember somebody made a medium article on C-Lightning PostgreSQL but I did not save the link...
Changelog-None

doc/BACKUP.md: Document backup strategies for `lightningd`.

---

common/configdir.c

Changelog-changed: Default network on both new and old
installs is now bitcoin. The warning "default network
changing in 2020" was removed.
Reverts 36c517bac59521dbf012c1faa29c012cfe48deae (except the comment)
Fixes #4159

common: change default network to mainnet

---

contrib/pyln-client/README.md
contrib/pyln-client/pyln/client/__init__.py
contrib/pyln-client/pyln/client/plugin.py
contrib/pyln-client/tests/test_plugin.py

Allows caller to set code and exact message to be returned.
Changelog-Added: pyln-client: plugins can now return RPCException for finer control over error returns.
THE BIG QUESTION: RPCException or RpcException?!? :scream:

pyln: add RPCException for finer method failure control.

---

lightningd/peer_control.c

You can't fail a cmd when you've already started streaming
a successful response:
lightningd: ccan/ccan/json_out/json_out.c:343: json_out_finished: Assertion `tal_count(jout->wrapping) == 0' failed.
lightningd: FATAL SIGNAL 6 (version v0.9.2-119-gf7cdf1d)
0x1847d1 send_backtrace
common/daemon.c:38
0x184877 crashdump
common/daemon.c:51
0x5bda03f ???
???:0
0x5bd9fb7 ???
???:0
0x5bdb920 ???
???:0
0x5bcb489 ???
???:0
0x5bcb501 ???
???:0
0x1e07a8 json_out_finished
ccan/ccan/json_out/json_out.c:343
0x18db0a json_stream_double_cr
common/json_stream.c:95
0x18dbf3 json_stream_close
common/json_stream.c:117
0x12fd98 command_raw_complete
lightningd/jsonrpc.c:459
0x12fec9 command_failed
lightningd/jsonrpc.c:488
0x12ffb9 command_fail
lightningd/jsonrpc.c:503
0x14dc20 json_setchannelfee …

setchannelfee: fix crash when channel is not in valid state.

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-listfunds.7
doc/lightning-listfunds.7.md
tests/test_misc.py
wallet/walletrpc.c

Added a `spent` option (a boolean) to `listfunds` which adds spent outputs to the `outputs` if set to true.
I didn't see any `test_listfunds` Python test so I thought I'd write one but then I couldn't figure out how to actually run these Python tests after reading `HACKING.md` :) 
* **blackbox tests** - These tests setup a mini-regtest environment and test
lightningd as a whole.  They can be run individually:
`PYTHONPATH=contrib/pylightning:contrib/pyln-client:contrib/pyln-testing:contrib/pyln-proto py.test -v tests/`
What's `py.test` ?
I checked `travis.yml` to see how it does that and it sets up bitcoind and elements and it's Linux specific but I'm using a Mac. If anyone knows how to run `tests/test_misc.py` on a Mac and could share this info with me I'd appreciate it.
Fixes #4291

Added spent option to listfunds

---

plugins/bcli.c

Really minor tweaks to how bcli handles responses to bitcoind `sendrawtransaction`. Printing the error code is useful for failures in tests; the others changes are nice but not have to haves.

Bcli tweaks

---

tests/test_wallet.py
tools/Makefile
tools/hsmtool.c

Fixes https://github.com/ElementsProject/lightning/issues/4186, based on #4284 
Went for the procedure [here](https://github.com/ElementsProject/lightning/issues/4186#issuecomment-723579122) for the API break. Should we instead support both for 3 releases ? It seemed overkill to me as it's a command-line tool and worse case the user has to input their password twice.

Take hsm_secret password from stdin, even for hsmtool!

---

tests/test_wallet.py
tools/hsmtool.c

Based on #4284 , fixes https://github.com/ElementsProject/lightning/issues/4302 .

hsmtool: fix hsm_secret generation

---

common/json_helpers.c
contrib/pyln-client/pyln/client/lightning.py
lightningd/dual_open_control.c
openingd/dualopend.c
tests/plugins/df_accepter.py

A few small things found while testing the dual-funding pathways.

Small fixes: dual-funding

---

contrib/pyln-testing/pyln/testing/utils.py

3.0.12 here:
```
pyln/testing/utils.py:9: error: Cannot find implementation or library stub for module named 'filelock'
pyln/testing/utils.py:9: error: Cannot find implementation or library stub for module named 'filelock'
pyln/testing/utils.py:9: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```
Changelog-None

pyln-testing: suppress mypy on FileLock

---

common/Makefile
common/hsm_encryption.c
common/hsm_encryption.h
hsmd/Makefile
hsmd/hsmd.c
lightningd/Makefile
lightningd/hsm_control.c
lightningd/lightningd.c
lightningd/options.c
lightningd/test/run-find_my_abspath.c
tests/fuzz/Makefile
tests/fuzz/fuzz-hsm_encryption.c
tests/fuzz/libfuzz.c
tests/test_wallet.py
tools/Makefile
tools/hsmtool.c

This is a bunch of cleanups on top of https://github.com/ElementsProject/lightning/pull/4303 .
Mainly, this makes the `hsm_encryption` contained into a common/ module, shared by `hsmd`, `lightningd` (options and hsm_control) and `hsmtool`. This then allows us to fuzz a roundtrip sanity check of our encryption.
Also:
- Cleanup errors in `hsmtool`
- Confirm password on `encrypt` in `hsmtool`
- Be stricter on `hsm_secret` validity (only accept 32-bytes (plaintext) and 73-bytes (encrypted) seeds)
There are still some cleanups left to be done (the channel seed derivation function is still duplicated, we could use `opt` for argument parsing).

Hsmtool (and hsm_secret encryption) refactorings

---

plugins/spender/multifundchannel.c
plugins/spender/openchannel.c

Fixes a few problems found while running tests against the v2 open pathways.
Update: this now depends on #4295, as we use the `take()` semantic for `json_add_psbt` in this patchset. First 'new commit' is `6cb23fb`

mfc: bug fixes for v2 opens

---

channeld/full_channel.c

I saw this message:
```
lightning_channeld: outstanding taken(): channeld/channeld.c:3087:blinding
lightning_channeld: outstanding taken(): channeld/channeld.c:3087:blinding
lightning_channeld: outstanding taken(): channeld/channeld.c:3087:blinding
```
The caller does take(blinding), but blinding can be NULL.  We should
move the code around to do the take() earlier anyway.
Changelog-None

channeld: stop taken() leak.

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-listinvoices.7
doc/lightning-listinvoices.7.md
lightningd/invoice.c
lightningd/test/run-invoice-select-inchan.c
tests/test_invoices.py

A user reported that it is sometimes cumbersome to search an invoice
based on the payment hash or the bolt11 string in the full list, which
may be required when we don't have the label available.
This adds support for querying / filtering based on the `payment_hash`
or `bolt11` string.

json-rpc: Add support for querying by hash or bolt11 to `listinvoices`

---

contrib/pyln-client/pyln/client/lightning.py
contrib/pyln-client/pyln/client/plugin.py
tests/plugins/countdown.py
tests/test_plugin.py

Adds command notification support to both the RPC client library as
well as the plugin library. This allows RPC clients to register a
notification callback that gets called for each notification, and
allows plugin methods to report status or progress using the
`Request.notify` method.

pyln: Add command notifications support

---

wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

This reverts commit c239a7161bb6080ad1e7a9b98ec240d256df3ce9.
The goal of c239a716 was to reduce the memory footprint of our
internal UTXO set tracking, and testing against the sqlite3 backend
showed no performance impact. We have since found that the added
roundtrips to the DB server with postgres was having a considerable
performance impact, and backups would also bloat due to the increased
number of queries.
Undoing this change skips the noop updates that were causing this
regression.
Changelog-Fixed: db: Fixed a performance regression during block sync, resulting in many more queries against the DB than necessary.

Revert "wallet: Remove in-memory utxoset filter"

---

common/jsonrpc_errors.h
doc/lightning-waitblockheight.7
doc/lightning-waitblockheight.7.md
lightningd/peer_control.c
plugins/libplugin-pay.c
tests/plugins/endlesswaitblockheight.py
tests/test_pay.py

We would `plugin_err()` if the call to `waitblockheight` in the
corresponding modifier timed out, instead of returning after
successful sync. We now catch that and terminate the payment on
timeout. Since we only react to errors containing a blockheight from
the last node, not being in sync is fatal for that payment.
Fixes #4269
Fixes #4309
Changelog-Fixed: pay: Fixed an issue where waiting for the blockchain height to sync could time out.

pay: Fix a crash when waitblockheight times out

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-invoice.7
doc/lightning-invoice.7.md
lightningd/invoice.c
tests/test_invoices.py

This is required if we want to create a "bouncer" plugin (in my copious free time!)
Changelog-Added: JSON-RPC: `invoice` now takes an optional `cltv` parameter.

invoice: add ctlv option.

---

lightningd/peer_control.c

payload is owned by the peer, which is freed in this case, then we
free payload (again).
```
==1404== Invalid read of size 8
==1404==    at 0x1F39E8: to_tal_hdr (tal.c:174)
==1404==    by 0x1F43A4: tal_free (tal.c:479)
==1404==    by 0x14B3D1: peer_connected_hook_cb (peer_control.c:1087)
==1404==    by 0x15D6E9: plugin_hook_call_ (plugin_hook.c:288)
==1404==    by 0x14B40E: plugin_hook_call_peer_connected (peer_control.c:1090)
==1404==    by 0x14B5B8: peer_connected (peer_control.c:1135)
==1404==    by 0x122FCF: connectd_msg (connect_control.c:310)
==1404==    by 0x160291: sd_msg_read (subd.c:480)
==1404==    by 0x15FBE7: read_fds (subd.c:308)
==1404==    by 0x1E37D1: next_plan (io.c:59)
==1404==    by 0x1E434E: do_plan (io.c:407)
==1404==    by 0x1E438C: io_ready (io.c:417)
==1404== …
```

lightningd: fix double-free when forking subdaemon fails.

---

doc/Makefile
doc/PLUGINS.md
doc/index.rst
doc/lightning-createinvoice.7
doc/lightning-createinvoice.7.md
doc/lightning-decode.7
doc/lightning-decode.7.md
doc/lightning-fetchinvoice.7
doc/lightning-fetchinvoice.7.md
doc/lightning-listpays.7
doc/lightning-listpays.7.md
doc/lightning-listsendpays.7
doc/lightning-listsendpays.7.md
doc/lightning-offer.7
doc/lightning-offer.7.md
doc/lightning-offerout.7
doc/lightning-offerout.7.md
doc/lightning-pay.7
doc/lightning-pay.7.md
doc/lightning-sendinvoice.7
doc/lightning-sendinvoice.7.md
doc/lightning-sendonionmessage.7
doc/lightning-sendonionmessage.7.md
doc/lightningd-config.5
doc/lightningd-config.5.md
lightningd/options.c

Update docs now offers are not only EXPERIMENTAL_FEATURES

---

wallet/db.c
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po

Fixes #4325
I petition adding this to the 0.9.3 release candidate, as, it gives a massive speedup on peer deletion, does not change semantics of the database, just pure speedup, and the change is very small.

wallet/db.c: Speed up deletion of single peers.

---

tools/hsmtool.c

fixes https://github.com/ElementsProject/lightning/issues/4339

hsmtool: fix a segfault on `dumponchaindescriptors` default network parameter

---

.gitignore
contrib/pyln-proto/requirements.txt
devtools/changelog.py
devtools/credit
doc/MAKING-RELEASES.md
external/Makefile
tools/build-release.sh

Mostly some cosmetic changes to the release tools, but they address some pitfalls that caused my to restart the release process a couple of times (`0.9.3` vs `v0.9.3` in the changelog for example).
Changelog-None

Weekly cleanups -- release edition

---

doc/PLUGINS.md
lightningd/peer_control.c
tests/plugins/custommsg.py
tests/plugins/custommsg_a.py
tests/plugins/custommsg_b.py
tests/test_misc.py
tests/test_plugin.py

This PR will also make the `custommsg` hook chainable.
Adds: Feature, documentation and tests.
Note: I made the hooks response `{'result': 'continue'}` mandatory since this is cleaner for a chained hook.

feat: chain hook custommsg

---

doc/PLUGINS.md
lightningd/dual_open_control.c
lightningd/opening_control.c
lightningd/peer_control.c
tests/plugins/peer_connected_logger_a.py
tests/plugins/peer_connected_logger_b.py
tests/test_plugin.py

Makes the `peer_connected` hook chainable.
Adds feature, doc and tests.

feat: peer_connected hook chainable

---

lightningd/bitcoind.c
lightningd/pay.c
plugins/pay.c

As promised in the 0.9.1 CHANGELOG.md

Deprecations for v0.9.4

---

doc/lightningd-config.5
doc/lightningd-config.5.md
lightningd/options.c

From #clightning:
(11:24:10) andytoshi: hiya, i'm trying to set up a new lightningd node, and when i run lightningd --network=bitcoin --log-level=debug --daemon
(11:24:17) andytoshi: i get errors of the form fetchinvoice: Malformed JSON reply '2021-01-25T00:51:16.655Z DEBUG   plugin-offers: disabled itself at init: offers not enabled in config
(11:24:43) andytoshi: there are a couple variants of this, but always some form of "something: failed to parse <a log line> as json"
Indeed, we close stdout, and it ends up being reused for some plugin.
But the real problem is that we log to stdout by default, which doesn't
make sense.  If they really want to discard logs, they can use
--log-file=/dev/null.

lightningd: disallow --daemon without --log-file.

---

connectd/connectd.c

Took me a while (stressing under valgrind) to reproduce this,
then longer to figure out how it happened.
Turns out io_new_conn() can fail if the init function fails.
In our case, this can happen if connect() immediately returns
an error (inside io_connect).  But we've already set the finish
function, which (if this was the last address), will free connect,
making the assignment `connect->conn = ...` write to a freed address.
Either way, if it fails, try_connect_one_addr() has taken care to
update connect->conn, or free connect, and the caller should not do it.
Here's the valgrind trace:
```
==384981== Invalid write of size 8
==384981==    at 0x11127C: try_connect_one_addr (connectd.c:880)
==384981==    by 0x112BA1: destroy_io_conn (connectd.c:708)
==384981==    by 0x141459: destroy_conn …
```

connectd: don't crash if connect() fails immediately.

---

contrib/pyln-testing/pyln/testing/utils.py

- Improves `wait_for` a bit and makes it more readable.
- Adds parameter `scids` (`list`, default `None`) to `wait_for_scids` so it can wait on just a set of channels to settle open HTLCs.
Changelog-None

chore: pyln-testing improvements

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-fundpsbt.7
doc/lightning-fundpsbt.7.md
doc/lightning-utxopsbt.7
doc/lightning-utxopsbt.7.md
tests/plugins/df_accepter.py
tests/test_connection.py
tests/test_wallet.py
wallet/reservation.c

For convenience, it's easier to allow the caller to request that a change output be added to a PSBT.

Add `excess_as_change` flag to fundpsbt/utxopsbt

---

doc/conf.py
wire/peer_printgen.c
wire/peer_printgen.h
wire/peer_wiregen.c
wire/peer_wiregen.h

Somewhere along the way ReadTheDocs upgraded to Sphinx 3.4.3 to build the docs and the recommonmark extension we used to render Markdown documents broke.
Testing locally this fixes that.
Changelog-None

doc: Update the recommonmark extension for RTD compilation

---

doc/lightning-cli.1.md

network was missing regtest as an option. 
The example was too simple, so I added a second one so show how the k option works.
The explanation of how k works should let the user know that in some cases lightningd will interpret the position of an argument which can lead to a weird response from lightningd.
let the users know that using null is not encouraged
@cdecker said "I think we should definitely not encourage null, since that is very brittle and forces us to keep argument ordering, and deprecating arguments is practically impossible."
Changelog-None

Added regtest, example, k and null explanation

---

plugins/libplugin-pay.c
plugins/pay.c
tests/test_pay.py

As pointed out by #4345 we lost the check for zero-length routes in the `pay` plugin somewhere along the lines: `gossipd.getroute` refused to generate them, `gossmap` is happy to return an empty result, which is more correct, but also causes this regression, since we implicitly assumed that the route would never be empty and just access `p->route[0]` without checking.
While I'd like to make self-payments supported, there is currently no way of mapping a payment that doesn't result in HTLCs to a successful attempt, thus disabling self-payments and being verbose about it is the next best thing.
Note: the original issue arose during an attempt to rebalance using the `pay` plugin, which cannot possibly work, and the [rebalance plugin](https://github.com/lightningd/plugins/tree/master/rebalance …

Prevent pay from accepting a zero-length route (self-payments)

---

wallet/db.c
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/wallet.c

We fix it twice: once when accessing the field, and a second time by
inserting the default value `0` on insert. The latter is likely to be
preferred, but the latter former is also need to fix existing wallets.
Fixes: #4363
Reported-by: Zoltán Gálli <@gallizoltan>
Changelog-Fixed: db: Fixed an access to a NULL-field in the `channel_htlcs` table and resulting warning.

db: Guard access to channel_htlcs.malformed_onion with a NULL check

---

Makefile
bitcoin/signature.c
channeld/channeld.c
channeld/commit_tx.c
closingd/closingd.c
common/initial_commit_tx.c
gossipd/gossipd.h
gossipd/queries.c
gossipd/queries.h
gossipd/seeker.c
gossipd/test/run-next_block_range.c
lightningd/onchain_control.c
onchaind/onchaind.c
openingd/dualopend.c
openingd/openingd.c
wire/peer_printgen.c
wire/peer_printgen.h
wire/peer_wire.csv
wire/peer_wiregen.c
wire/peer_wiregen.h

As I promised at the last spec meeting...

Gossip `sync_complete` marker, and catch up the BOLT docs.

---

lightningd/lightningd.c
lightningd/plugin.c
lightningd/plugin.h
lightningd/plugin_control.c
tests/test_plugin.py

@jsarenik commented that he saw zombie plugins, and I reproduced that here.  This handles SIGCHLD in a way which tries not to interfere with the synchronous handling of waitpid() in the subd code.
Fixes #4381
Changelog-None

Plugins: don't leave zombies

---

lightningd/chaintopology.c
plugins/bcli.c
tests/test_connection.py
tests/test_misc.py

We have a dev knob to disable it for testing, but this is what everyone actually wants when using regtest, AFAICT.
During a recent demo I had one regtest peer send out an update_fee with a 0 rate.  To my consternation, I have been unable to reproduce this.  Is bitcoind giving wild fee estimates in some regtest setups?

Regtest feerate setting

---

bitcoin/script.c
bitcoin/script.h
common/Makefile
common/features.c
common/features.h
common/shutdown_scriptpubkey.c
common/shutdown_scriptpubkey.h
lightningd/Makefile
lightningd/channel_control.c
lightningd/lightningd.c
openingd/Makefile
openingd/openingd.c
tests/test_closing.py
tests/test_misc.py
tests/utils.py

See https://github.com/lightningnetwork/lightning-rfc/pull/672
Changelog-None: Experimental only

EXPERIMENTAL support for option_shutdown_anysegwit

---

common/json_stream.c
doc/PLUGINS.md
lightningd/jsonrpc.c
tests/plugins/rpc_command_1.py
tests/plugins/rpc_command_2.py
tests/test_plugin.py

This chains the last remaining single hook `rpc_command`
Adds: feature, doc and modified testcase.
This is in draft as there is an open issue that will crash the test that I don't fully understand yet.
It seems like `rpc_command_hook_payload *p` or at least `p->custom_result` is freed with `tal_free()` somewhere,
so that we cant read the JSON `p->custom_result` (via `command_raw_complete`) anymore and give it to the daemon.
If we modify the code so that `rpc_command_hook_final` is explicitly called in the `rpc_command_hook_callback`, we have a similar situation where it then wants to `tal_free()` the `rpc_command_hook_payload` which is already freed.
Ideally I want to call `rpc_command_hook_final` just implicitly (just like the current code does) in order to detect if two or multiple …

feat: chain hook rpc command

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-listforwards.7
doc/lightning-listforwards.7.md
lightningd/peer_htlcs.c
tests/test_misc.py
wallet/db.c
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/wallet.c
wallet/wallet.h

I've added in_channel,out_channel and state params to listforwards.
I also added an index to forwarded_payments.state to speed up lookups that use this column (eg. getinfo).
TODO:
* tests (struggling with a broken Python atm)
* docs

Issue 4305 - Added in_channel,out_channel,state params to listforwards

---

common/Makefile
wire/Makefile
wire/bolt12_wiregen.c
wire/bolt12_wiregen.h
wire/common_wiregen.c
wire/common_wiregen.h
wire/onion_printgen.c
wire/onion_printgen.h
wire/onion_wiregen.c
wire/onion_wiregen.h
wire/peer_printgen.c
wire/peer_printgen.h
wire/peer_wiregen.c
wire/peer_wiregen.h

Makefile fixes

---

channeld/channeld.c
lightningd/peer_control.c
openingd/dualopend.c
openingd/openingd.c
tests/test_misc.py

Well this is embarassing 🙄
Looks like #4394 treated a symptom but not the root cause. We were
actually sending the message framed with the WIRE_CUSTOMMSG_OUT and
the length prefix over the encrypted connection to the peer. It just
happened to be a valid custommsg...
This fixes the issue, and this time I made sure we actually send the
raw message over the wire. However for backward compatibility we
needed to imitate the faulty behavior which is 90% of this patch :-)
Changelog-Fixed: plugin: `dev-sendcustommsg` included the type and length prefix when sending a message.

plugin: Do not send the internal framed message over the wire

---

contrib/pyln-client/pyln/client/plugin.py

I had way too much fun with this and got a bit carried away with the
letter writing. The idea is to be helpful when users start the plugin
from the command line, rather than run it under the control of
lightningd. We also print detailed information about the user-visible
things such as the methods and options exposed by the plugin.
Changelog-Added: pyln: Plugins that are run from the command line print helpful information on how to configure c-lightning to include them and print metadata about what RPC methods and options are exposed.
Suggested-by: Rusty Russell <@rustyrussell>

pyln: Plugins can be nice if invoked from CLI too

---

lightningd/lightningd.c
lightningd/plugin.c

There are ways to misconfigure plugins that will cause us to shut
down. These include having an important plugin fight for a method name
with another plugin, e.g., by loading the same plugin twice. Until now
we would happily continue with the startup sequence only to later
realize that we were supposed to shutdown, but by then we'd have
buried the error message in the logs.
This PR just adds a check for misconfigurations before we even start
the normal `io_loop`, avoiding expensive initializations and not
hiding the log entries about the cause. This works if we're just using
`--help` as well, and produces a much clearer picture of what is going
on.
I also added the name of the plugin that was clashing with RPC methods.
Fixes #4415
Reported-by: PsySc0rpi0n
Reported-by: Ján Sáreník …

Add early abort in case of misconfigured plugins

---

common/bolt12.c
common/bolt12.h
plugins/keysend.c
plugins/libplugin-pay.c
plugins/libplugin-pay.h
plugins/pay.c
tests/test_pay.py

This started out as a quick fix for #4299, but while debugging I
stumbled over a couple of easy optimizations:
- Keysend no longer requires featurebit 55 to be signaled by the
destination, instead requiring only TLV. This is because apparently
keysend is not formally proposed to the spec, and the featurebit is
not reserved. We now will report a more meaningful error message if
the recipient returns an `INVALID_ONION_PAYLOAD` error.
- We now filter routehints whose entrypoints we cannot reach, since
there is no point in trying them if we can't even get to the
entrypoint. This considers two different scenarios: entrypoint is
unknown and entrypoint is unreachable.
- Added `payment_abort` to set a top-level error message in the `pay`
result, which should make it easier for modifiers to be …

`pay` optimizations round 1

---

plugins/spender/multifundchannel.c

Originally written in an inverted style to allow for a more 'natural reading', which relies heavily on forward declarations and allows for an inversion in the normal flow of C code.
This PR removes all the forward declarations, and inverts the code to conform with the style of every other C file in this project.

Invert multifundchannel.c

---

README.md
contrib/startup_regtest.sh

We scan config.vars to figure out if you configured developer on or off.
If it's on, we add the dev-only options to the config.
Fixes: #4400
Reported-By: Jonathan Harvey-Buschel @jharveyb
Changelog-None

contrib: add the dev- options to the config iff DEVELOPER=1 configured

---

contrib/startup_regtest.sh

The `contrib/startup_regtest.sh` script does not work out of the box on mac os as the default bitcoin dir in mac os is not `~/.bitcoin` but rather `~/Library/Application Support/Bitcoin/` so I added that

added the default bitcoin path for macos to startup_regtest.sh

---

connectd/connectd.c
doc/FAQ.md
lightningd/bitcoind.c
plugins/bcli.c
plugins/libplugin.c

See https://en.wikipedia.org/wiki/Information
In libplugin.c also the word "details" was added (without removing
the 'information').
Changelog-None
Discussion welcome.
FYI: @darosior
Nice discussion of the topic is at [Englishforums](https://www.englishforums.com/English/InformationOrInformations/gzdmw/post.htm)

typo: information is an uncountable mass noun

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-fundchannel_complete.7
doc/lightning-fundchannel_complete.7.md
doc/lightning-txprepare.7
doc/lightning-txprepare.7.md
doc/lightning-withdraw.7
doc/lightning-withdraw.7.md
lightningd/opening_common.h
lightningd/opening_control.c
plugins/spender/multifundchannel.c
plugins/txprepare.c
tests/test_connection.py

This prevents the footgun from #4416

Fundchannel complete psbt not txid

---

tests/test_closing.py

This was merged almost at the same time as the API change.
Changelog-None

pytest: fix now-obsolete use of fundchannel_complete via txid.

---

channeld/full_channel.c

We try not to exceed either side, but the spec still allows them to
(we don't, but older nodes would have, as could other implementations).
Fixes: #3953
Changelog-Fixed: protocol: overzealous close when peer sent more HTLCs than they'd told us we could send.

channeld: allow remote node to exceed their own HTLC count limits.

---

doc/lightning-connect.7
doc/lightning-connect.7.md
lightningd/connect_control.c
lightningd/connect_control.h
lightningd/peer_control.c
lightningd/test/run-invoice-select-inchan.c
tests/test_connection.py
tests/test_gossip.py
tests/test_misc.py
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/test/run-wallet.c

Otherwise, we might find an address other than the one given and
the user might think that address worked.
Fixes: #4185

connect: return address we actually connected to.

---

lightningd/channel.c
lightningd/channel.h
lightningd/dual_open_control.c
openingd/dualopend.c
tests/test_opening.py
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/wallet.c

Better testing of packet-drops and reconnects during/when we're doing the signature exchange. This was hard to test exactly because of the damn reconnect logic which resends sigs on reconnect.
"Fixes" the "race" found in #4431's tests.

Dual-funding: more reconnection fail

---

plugins/Makefile

Get rid of unuseful "UNKNOWN TYPE channel_id" prints in logs; only
affected usage for `type_to_string` of plugins/Makefile built things
```
lightningd-1: 2021-03-16T20:22:16.033Z DEBUG   plugin-spenderp: mfc 25, dest 0: `openchannel_signed` UNKNOWN TYPE channel_id psbt cHNidP8BAH0CAAAAAdDqv81NxTlsoSS7Glg4hxv9zc7mrgdxqCx7HHuOkcdpAQAAAAD9////AqCGAQAAAAAAIgAgW4zTuRTPZ83Y+mJzyTA1PdNkdnNPvZYhAsLfU7kIgM2yqQ0BAAAAABYA
FMLMqxccKlvp2rUuxBuCWGMCTFRmZgAAAAABAN4CAAAAAAEB0ZZNgU/XMipFydK/OaoZtNuh5nzl7rTGetG5/gETlrsAAAAAAP7///8CM6/2KAEAAAAWABQYE5O31J0/eswToHXSj8fiPjG6dEBCDwEAAAAAFgAUAfrZCrzWZpfiWSFkci3kqV6+4WUCRzBEAiBNLHSLQpGEiL3hVdg1FqjEJv+5TdNwtDOs/lDlY9oYZQIgSD00h264sETD6qelP767Q4PEkjpa5+74oV
GiL3rAsjIBIQJQpPejKThSde0+mBgOic2ZVZE1YZ+xVqTTf/x3ad4ghGUAAAABAR9AQg8BAAAAABYAFAH62Qq81maX4lkhZHIt5KlevuFlAQhr …
```

mfc: turn "UNKNOWN TYPE channel_id" logs into actually the channel id

---

lightningd/channel.c

valgrind rightfully complains:
```
Valgrind error file: valgrind-errors.182892
==182892== Conditional jump or move depends on uninitialised value(s)
==182892==    at 0x16B381: handle_peer_tx_sigs_sent (dual_open_control.c:1415)
==182892==    by 0x16E9F4: dual_opend_msg (dual_open_control.c:2681)
==182892==    by 0x165759: sd_msg_read (subd.c:480)
==182892==    by 0x1EECCB: next_plan (io.c:59)
==182892==    by 0x1EF8B0: do_plan (io.c:407)
==182892==    by 0x1EF8F2: io_ready (io.c:417)
==182892==    by 0x1F1B8A: io_loop (poll.c:445)
==182892==    by 0x131332: io_loop_with_timers (io_loop_with_timers.c:24)
==182892==    by 0x13711B: main (lightningd.c:1102)
==182892==
--------------------------------------------------------------------------------
------------------------------- Valgrind …
```

channel: initialize inflight->tx_broadcast (EXPERIMENTAL_FEATURES)

---

.github/workflows/ci.yaml
lightningd/invoice.c
plugins/keysend.c
tests/test_pay.py

All of these are just single-commit fixes, so I didn't open a new PR for each:
- We were stealing the plugin's read buffer in keysend and freeing it, causing a use-after-free on the next call.
- Self-payments in `keysend` could result in a crash due to an empty route being returned.
- The order in which the `invoice_payment` hook and notification were called was switched around (we were notifying about still to accept invoices being paid, when the hook could also reject it)
Fixes #4438 
Fixes #4434

Various minor fixes

---

ccan/README
ccan/ccan/timer/timer.c
common/htlc_wire.c

Handle time going backwards (a little) on OpenBSD 6.8 under Virtualbox, and fix a clang warning.

Minor post-rc1 fixes.

---

tests/test_opening.py

We updated the "UNKNOWN TYPE channel_id" -> the actual channel id;
the reason for why the error fails shouldn't be restrictive (we just
know that it fails)
Changelog-None

df-tests: make bad tests a bit better, maybe

---

gossipd/gossip_store.c

If gossip_store is an incorrect version, we will recreate it: with an incorrect
version!  This means we never get persistent gossip, *and* the pay plugin will
fail to map the gossip_store.  Everyone will be sad.
Debugged-by: Matt Whitlock
Fixes: #4376
Fixes: #4288
Typing-by: Rusty Russell <rusty@rustcorp.com.au>

gossipd: fix rolling corruption.

---

plugins/spender/multifundchannel.c
plugins/spender/multifundchannel.h
plugins/spender/openchannel.c

It's unlikely but possible that a race condition will result in us not
being at the 'secured' state yet here.
Crashlogs. All required msgs are received (in order)
from peers, but the crash suggests they weren't relayed/processed by the
spender plugin in the order received.
WIRE_TX_SIGNATURES is passed the the plugin via a notification;
WIRE_COMMITMENT_SIGNED is returned as the result of an RPC call.
```
021-03-25T12:12:33.5213247Z lightningd-1: 2021-03-25T11:50:13.351Z DEBUG   035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d-dualopend-chan#3: peer_in WIRE_COMMITMENT_SIGNED
2021-03-25T12:12:33.5221140Z lightningd-1: 2021-03-25T11:50:13.659Z DEBUG   022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-dualopend-chan#1: peer_in WIRE_COMMITMENT_SIGNED …
```

dual-funding: introduce racy state

---

contrib/pyln-proto/pyln/proto/message/array_types.py
contrib/pyln-proto/pyln/proto/message/message.py
contrib/pyln-proto/tests/test_message.py

We weren't correctly adding the length of an array type in a subtype to the message when writing them out.
We need to iterate through the fields of the subtype to do this, as well as 'descending' through the otherfield vals as we go.
(The `witness_stack` subtype includes two layers of variable length nested subtypes.)
Changelog-None

pyln-proto: write subtype arrays out correctly

---

channeld/channeld.c
common/status.c
common/status_wire.csv
common/status_wiregen.c
common/status_wiregen.h
contrib/pyln-testing/pyln/testing/utils.py
gossipd/gossipd.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/subd.c
lightningd/subd.h
lightningd/test/run-find_my_abspath.c
tests/plugins/badopeningd.sh
tests/test_misc.py

This catches the "oops, per-peer daemons have been upgraded underneath me!" problem; it still logs a BROKEN message, but it tried to re-exec itself.
We still have the version check at startup, so we don't infinite loop if we have a half-installed setup somehow.

subd version messages

---

channeld/channeld.c
channeld/full_channel.c
common/fee_states.c
common/fee_states.h
tests/test_closing.py

There are several reports of desynchronizaion with LND here; a simple
approach is to only have one feerate change in flight at any time.
But I also found that our fee state machine was a bit screwed (thanks to CI flake!), so that may also have caused this problem.
Fixes: #4152

channeld: don't ever send back-to-back feerate changes, fix feerate logic.

---

bitcoin/signature.c
channeld/commit_tx.c
channeld/test/run-commit_tx.c

This implements generation of test vectors to replicate https://github.com/lightningnetwork/lightning-rfc/pull/539 (merged) and does it in the cleaned-up format proposed in https://github.com/lightningnetwork/lightning-rfc/pull/852.  (When that is merged, we'll need to update some internal bolt quotes, but they're easy).
Changelog-None

HTLC test vector update

---

Makefile
contrib/pyln-client/pyln/client/plugin.py
doc/PLUGINS.md
lightningd/notification.c
lightningd/notification.h
lightningd/plugin.c
lightningd/plugin.h
plugins/autoclean.c
plugins/bcli.c
plugins/fetchinvoice.c
plugins/keysend.c
plugins/libplugin-pay.c
plugins/libplugin.c
plugins/libplugin.h
plugins/offers.c
plugins/pay.c
plugins/spender/main.c
plugins/txprepare.c
tests/plugins/custom_notifications.py
tests/plugins/test_libplugin.c
tests/test_plugin.py

So far plugins could only subscribe to native notifications that originated in `lightningd` and which were limited to a few topics directly built into the daemon. With this PR we enable plugins to announce their intention to publish notifications to custom topics, and for other plugins to subscribe to those topics and receive the notifications.
Custom topics are required to be announced as part of the `getmanifest` call, allowing us to verify that subscriptions match the announced topics at startup, and print a warning message should a plugin subscribe to a topic that wasn't announced, and therefore will never receive a notification. Trying to send a notification with an unannounced topic will result in a warning being logged, and the message _not_ being delivered to subscribers.
To allow …

plugin: Allow plugins to publish and subscribe to custom notifications

---

plugins/bcli.c

plugins/bcli: strip trailing whitespace appropriately

---

doc/lightningd-config.5
doc/lightningd-config.5.md
lightningd/log.c
tests/test_misc.py

Fixes: #4494
Changelog-Added: config: New option `log-timestamps` allow disabling of timestamp prefix in logs.

lightningd: implement --log-timestamps=false.

---

lightningd/dual_open_control.c

This gets called from channel_set_owner, which both `delete_channel` and
the `channel_fail_reconnect` pathways call.
Fixes crash
------------------------------------------------------ Captured stderr teardown -------------------------------------------------------
lightning_connectd: peer_disconnected unknown peer: 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518 (version v0.10.0-144-gfaf98c9)
0x560e90d59d08 send_backtrace
common/daemon.c:39
0x560e90d648a5 status_failed
common/status.c:214
0x560e90d50e8f peer_disconnected
connectd/connectd.c:1606
0x560e90d510d5 recv_req
connectd/connectd.c:1662
0x560e90d5a266 handle_read
common/daemon_conn.c:31
0x560e90d98ccb next_plan
ccan/ccan/io/io.c:59
0x560e90d998b0 do_plan
ccan/ccan/io/io.c:407
0x560e90d998f2 io_ready …

df-bugs: rm duplicate call to channeld

---

lightningd/plugin.c
plugins/libplugin-pay.c

So minor I didn't want to hold up @cdecker's excellent PR from merging.
1. We don't need to check for NULL before tal_count(NULL).
2. Use of json_for_each_arr iterator is probably better.
3. Weird indent fixed.
Changelog-None

plugin notifications: minor cleanups.

---

tests/test_connection.py

If l2 didn't get FUNDING_LOCKED from l1 before it disconnected, it
won't be in state CHANNELD_NORMAL: it will be in DUALOPEND_AWAITING_LOCKIN.
Changelog-None

pytest: fix flake in test_reconnect_no_update

---

lightningd/channel.c
lightningd/channel.h
lightningd/htlc_end.c
lightningd/htlc_end.h
lightningd/peer_htlcs.c
tests/test_connection.py
tests/test_misc.py

~As a side-effect, this fixes our MPP flake :)~ No, it does not.

Fix htlc error causing connclose

---

plugins/funder.c
plugins/funder_policy.c
plugins/funder_policy.h
plugins/test/run-funder_policy.c
tests/test_connection.py
tests/test_opening.py
wallet/reservation.c

Not accounting for our fees when we're calculating the total available for funding bit @fiatjaf 
If a utxo isn't economical, we shouldn't add it to the transaction.

Funder fees

---

lightningd/dual_open_control.c
tests/test_connection.py

In 0f79b1bd805ba6b1d2aaf0cd0737f8aef830ffd9, we mark a bunch of tests as 'v1' only. Here we translate as many of those as possible/logical to have 'v2' counterparts.
Changelog-None

Dual-funding, last of the CI tests

---

doc/FAQ.md
doc/lightning-utxopsbt.7
doc/lightning-utxopsbt.7.md

Added FAQ on getting a PSBT.  Also when I read the RETURN VALUE for utxopsbt the first time, I didn't realize this command produces (or recreates) the psbt that I need.  The change I made makes that more obvious when it's presented as a hit by GH for a search for psbt.

Improve documentation for calls that use psbt

---

README.md

I have verified that this results in working bitcoin core and c-lightning on fresh Ubuntu 20.04 server installation.
This is also consistent with instructions in doc/INSTALL.md
Fixes: #4539
Fixes:  #4538
Reported-By: @urza
Changelog-None: just readme

readme: fix ubuntu installation instructions

---

devtools/onion.c
doc/lightning-createonion.7
doc/lightning-createonion.7.md
lightningd/pay.c
tests/test_pay.py

I'm trying to make a trampoline routing plugin and I'm hoping this very small change will be enough to allow me to make the custom trampoline onions to be built without me having to reimplement onion-making functions from scratch.

`createonion` to accept an optional custom `onion_size`

---

plugins/libplugin-pay.c
tests/test_pay.py

pay: fix corner case where we eliminate our own hint.

---

common/read_peer_msg.c
tests/test_gossip.py

Fixes in code `FIXME` for checking chain hash in gossip_timestamp_filter messages. Updates tests to follow that as well.

common: Check chain hash in gossip_timestamp_filter

---

doc/lightning-listpays.7
doc/lightning-listpays.7.md
doc/lightning-listsendpays.7
doc/lightning-listsendpays.7.md
plugins/pay.c
tests/test_pay.py
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/wallet.c

listpays: sort output payments

---

channeld/channeld.c
channeld/channeld_wire.csv
channeld/channeld_wiregen.c
channeld/channeld_wiregen.h
channeld/full_channel.c
channeld/full_channel.h
gossipd/gossipd.c
lightningd/channel_control.c
openingd/dualopend.c
tests/test_connection.py
wire/extracted_peer_exp_quiescence-protocol.patch
wire/peer_wire.c

Implementation of https://github.com/lightningnetwork/lightning-rfc/pull/869
Changelog-None

EXPERIMENTAL: quiesence protocol

---

bitcoin/psbt.c
common/setup.c
requirements.txt

Fixes the 'empty-psbt' problem etc. We also remove outdated/unnecessary wallycore python deps, as we no longer use it for integration tests.
Changelog-None

Update libwally to v0.8.3

---

tests/test_wallet.py

I don't see any reason for checking whether the stdout is a tty. In addition i'm pretty sure `pytest` captures `stdout` and that means this test was actually never run.
I did a first dry-run on my fork's Github Action, and it doesn't need it either.

Revert "pytest: Skip hsm encryption test if we don't have a TTY"

---

tests/test_connection.py

Otherwise it hangs on cleanup, as l2 is waiting for l1 to respond (and
it's not going to), so the memleak call hangs.

tests: cleanup any unfinished/hanging channel opens

---

lightningd/opening_control.c

Fixes #4562
New error message:
```
zircon:lightning (nifty/fix-4562)$ l1-cli fundchannel_start 03fce775508719e4064b7f19d4e884ddaf51db23bbfc560286ce872f9ed106fee0 10000 253perkw
{
"code": 312,
"message": "Peer negotiated `option_dual_fund`, must use `openchannel_init` not `fundchannel_start`."
}
```
Changelog-None

openingd: return more informative error message for v2 opens

---

channeld/full_channel.c
plugins/libplugin-pay.c
plugins/pay.c
tests/test_pay.py

Didn't fix the problem, broke pay :(  Help @cdecker !

Pay: handle when we're close to htlc limit

---

common/hsm_encryption.c
lightningd/options.c

fixes: #4570 as discussed.
The temporary terminal with ECHO disabled is not created if the input is piped instead of typed in a terminal.
Passwords are still not visible when typed, but allows for automation.

hsm_encryption: read from STDIN if not in a TTY

---

doc/lightning-sendonion.7
doc/lightning-sendonion.7.md
lightningd/pay.c
plugins/libplugin-pay.c

Does this make sense?
Untested, wanted to make sure it made sense first.

stop requiring channel and direction on `sendonion` since they're not used.

---

contrib/pyln-testing/pyln/testing/utils.py
tests/test_opening.py

This test takes 695 seconds, because fundwallet waits for the wallet to
notice the tx, which takes 60 seconds if not DEVELOPER.  Do all the waiting
at once, and this speeds the test up to 153 seconds.
Found by CI in https://github.com/ElementsProject/lightning/pull/4581
Changelog-None

pytest: speed up test_opening.py::test_funder_contribution_limits when !DEVELOPER

---

plugins/libplugin-pay.c

There are a couple of ways this can happen, but we shouldn't crash.
Fixed #4488
Fixes #4533

pay: Do not attempt to filter routehints if we can't find ourselves

---

plugins/keysend.c

Hi all! I'm working on making Rust-Lightning compatible with CL's keysend.
Would you all be open to a change like this? Rust-Lightning is a bit more conservative than the default 18 for `min_final_cltv_expiry`, so I thought it might be reasonable to make CL use a bit more conservative value too. Let me know what you think.

Make cltv_expiry for keysends slightly more conservative

---

bitcoin/signature.c

The local struct `hash` was read before it was initialized.
Changelog-None

chore: fix compile issue discovered by gcc

---

lightningd/pay.c

An "active" channel may still be CHANNELD_AWAITING_LOCKIN, so have ->scid NULL.
You can only trigger this by trying to sendpay to the node using a
manual route, since routing would never use such a channel.
```
lightningd: FATAL SIGNAL 11 (version v0.10.0-319-g81cbc20-modded)
0x55e79d194e17 send_backtrace
common/daemon.c:39
0x55e79d194ec1 crashdump
common/daemon.c:52
0x7fce2d79920f ???
???:0
0x7fce2d8e16f7 ???
???:0
0x55e79d2019eb tal_dup_
ccan/ccan/tal/tal.c:801
0x55e79d14e1d9 immediate_routing_failure
lightningd/pay.c:365
0x55e79d14fe91 send_payment_core
lightningd/pay.c:1022
0x55e79d150995 send_payment
lightningd/pay.c:1180
0x55e79d151975 json_sendpay
lightningd/pay.c:1462
```
Changelog-None

lightning/pay: don't crash when trying to send payment down unconfirmed channel

---

wire/Makefile
wire/bolt12_wiregen.c
wire/bolt12_wiregen.h
wire/common_wiregen.c
wire/common_wiregen.h
wire/onion_printgen.c
wire/onion_printgen.h
wire/onion_wiregen.c
wire/onion_wiregen.h
wire/peer_printgen.c
wire/peer_printgen.h
wire/peer_wiregen.c
wire/peer_wiregen.h
wire/test/Makefile

I wasn't regenerating these when I changed dependencies, because I was
configured with --enable-experimental-features.  Putting them in
ALL_C_HEADERS and ALL_C_SOURCES means they'll be regenerated, even
though nothing depends on them.
Changelog-None

wire/Makefile: always generate non-exp files.

---

tests/test_misc.py

If l2 doesn't have the funding locked in, the rest of the test fails
(we got a timeout on `wait_for(lambda: [c['active'] for c in l2.rpc.listchannels('103x1x0')['channels']] == [False, False])`)
Changelog-None

pytest: fix flake in test_misc.py::test_funding_reorg_*

---

plugins/bcli.c

We didn't set this to false on non-regtest!
Changelog-None
```
==198363== Conditional jump or move depends on uninitialised value(s)
==198363==    at 0x10EF88: estimatefees_parse_feerate (bcli.c:443)
==198363==    by 0x10F3BF: estimatefees_second_step (bcli.c:550)
==198363==    by 0x10E720: bcli_finished (bcli.c:258)
==198363==    by 0x1438A7: destroy_conn (poll.c:244)
==198363==    by 0x1438CB: destroy_conn_close_fd (poll.c:250)
==198363==    by 0x151A7A: notify (tal.c:240)
==198363==    by 0x151F91: del_tree (tal.c:402)
==198363==    by 0x15232D: tal_free (tal.c:486)
==198363==    by 0x141EB8: io_close (io.c:450)
==198363==    by 0x14400B: io_loop (poll.c:449)
==198363==    by 0x114BB0: plugin_main (libplugin.c:1414)
==198363==    by 0x1105C4: main (bcli.c:973)
```
Signed-off-by: Rusty …

plugins/bcli: fix uninitialized variable.

---

contrib/pyln-client/pyln/client/plugin.py

Just adds some help text that I thought that might be helpful to newbies.

pyln: adds a help text to start plugins manually

---

common/hsm_encryption.c
contrib/pyln-testing/pyln/testing/utils.py
tests/test_wallet.py
tools/hsmtool.c

This includes a test from https://github.com/ElementsProject/lightning/pull/4571#issuecomment-861047543 for roundtrip between stdin and non-stdin, as well as a cleanup in the line reader to avoid any possibility of divergence between the two.
Changelog-None

hsmtool: test password input from stdin

---

lightningd/invoice.c
tests/test_invoices.py

https://github.com/lightningnetwork/lightning-rfc/pull/877 talks about
removing this restriction (only Electrum actually enforced it on
receive), so start by allowing creation of giant invoices, though
we mark them as requiring mpp.

invoice: allow creation of giant invoices.

---

plugins/libplugin-pay.c

Found another instance of the same issue that we addressed in #4581.
Changelog-None

pay: Fix another instance of a crash when we can't find ourselves

---

common/initial_channel.c
contrib/pyln-proto/pyln/proto/message/message.py
contrib/pyln-spec/bolt1/boltsetup.py
contrib/pyln-spec/bolt2/boltsetup.py
contrib/pyln-spec/bolt4/boltsetup.py
contrib/pyln-spec/bolt7/boltsetup.py

This pairs well with the lnprototest updates for testing channel_types:  https://github.com/rustyrussell/lnprototest/pull/15
Changelog-None

Pyln fixes and misc cleanups

---

.gitmodules

I followed the last update of lnprototest and I hope to avoid mistakes with this PR.
The actual version of lnprototest is a couple of comments back, and it missing the update with bitcoin 0.21.0 made by this PR https://github.com/rustyrussell/lnprototest/pull/10.
I made a double-check, and I think that the previous version of lnprototest is fully contained inside the master, with the following PR https://github.com/rustyrussell/lnprototest/pull/5.
Correct me if I'm wrong @niftynei 😄 
let see what GitHub action react to this change💺 
Closing #4516

Update lnprototest with the last version of master

---

tools/check-spelling.sh
tools/mockup.sh

Fixes #3203 and another issue I was seeing on my local build.

macOS build fixes

---

plugins/topology.c

This simply removes the two spammy debug log statements introduced by e81e640
Turns out that these statements were slowing down `getroute` even on `log-level=info`.
Fixes https://github.com/ElementsProject/lightning/issues/4617
Changelog-None

fix: remove spammy debug statements from getroute

---

channeld/channeld.c
doc/lightning-listconfigs.7
doc/lightning-listconfigs.7.md
doc/lightningd-config.5
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
lightningd/bitcoind.c
lightningd/chaintopology.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
tests/test_misc.py

Got a report from @gijswijs that we were sending 0 update_fee on regtest; I've seen this complaint before, but this time we fixed it.
Also, @t-bast wanted to override regtest fees: we used to have a dev option which we removed in favor of direct control, I think that was probably overzealous (it's far easier that writing a bcli replacement!).  Of course we recommend this be in the regtest-specific config!

Regtest fee control

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-listchannels.7
doc/lightning-listchannels.7.md
plugins/topology.c
tests/test_gossip.py

When writing feeadjuster https://github.com/lightningd/plugins/pull/256 I figured there is a usecase for having `listchannels` be queried also by `destination`
Adds feature, doc and test.

feat: listchannels filter by destination

---

common/json_tok.c
common/json_tok.h
common/test/run-param.c
lightningd/options.c
plugins/keysend.c
tests/test_pay.py

So far we could not reach non-publicly reachable nodes with the
keysend command since we couldn't compute a route to them. With this
change we can add some routehints that we may have gotten from an
address book or a previous invoice, and make it more likely that we
can reach the destination.
Builds on top of #4610 to avoid rebase conflicts, but I can separate them out if that's preferred. This PR consists only of the last 3 commits.

keysend: Add routehints argument to the keysend command

---

lightningd/plugin.c
lightningd/plugin.h
tests/test_plugin.py

This adds a `u32 checksum` field to the plugin struct that is used
to identify if a plugin is outdated and needs to be restarted on `rescan`.
Useful for developing and debugging plugins.
Note: only affects non-important plugins.
Changelog-Added: Plugin: Restarts a plugin on `rescan` when its binary was changed.

plugin: rescan restarts plugin on update

---

tools/hsmtool.c

Not every user know the minimum word list that is needed.
Below 12 words the output is:
`lightning-hsmtool: Invalid mnemonic:`

added minimum word list needed

---

doc/lightningd-config.5
doc/lightningd-config.5.md

docs: fix typo and wording

---

.github/workflows/ci.yaml

Setting VALGRIND=1 actually does nothing here; reduce it to two cases,
covering gcc and clang, sqlite3 and postgres.

Github actions: reduce lnprototest.

---

doc/Makefile
doc/index.rst
doc/lightning-funderupdate.7
doc/lightning-funderupdate.7.md
doc/schemas/funderupdate.schema.json
plugins/funder.c
tests/test_opening.py

Documentation for the funderupdate command on the funder plugin.
Realized we were missing the "leases_only" in the output; also adds
'_msat' to msat denominated outputs so they're parsed correctly by our
python bindings (also matches our naming conventions)
Changelog-EXPERIMENTAL: funder: `funderupdate` command to view and update params for contributing our wallet funds to v2 channel openings. Provides params for enabling `option_will_fund`.

funderupdate: add documentation, update some params

---

CHANGELOG.md

Changelog for v0.10.1 release

---

contrib/pyln-spec/requirements.txt

This PR increases the version of the `pyln-proto` in the `pyln-spec` package.
This help to fix the following error on `lnprototest`:
```
ERROR: pyln-bolt7 1.0.1.137 has requirement pyln.proto==0.8.4, but you'll have pyln-proto 0.10.0 which is incompatible.
ERROR: pyln-bolt4 1.0.1.137 has requirement pyln.proto==0.8.4, but you'll have pyln-proto 0.10.0 which is incompatible.
ERROR: pyln-bolt2 1.0.1.137 has requirement pyln.proto==0.8.4, but you'll have pyln-proto 0.10.0 which is incompatible.
ERROR: pyln-bolt1 1.0.1.137 has requirement pyln.proto==0.8.4, but you'll have pyln-proto 0.10.0 which is incompatible.
```

Moving the dependency to the minimum required

---

channeld/channeld.c

otherwise the peer may not know to expect it.

channel lease: only send update_blockheight iff has channel lease

---

channeld/channeld.c
tests/test_connection.py

Pointed out by @fiatjaf, and indeed it happened to me as well; a peer with a high feerate reconnects and sends a similar (but now ludicrous) feerate, and we get upset:
```
$ lightning-cli listpeers 039c73f53daad1050a6a72afb5353a2152f3152ee17168cd0ab28c2cb3e0050e36
{
"peers": [
{
"id": "039c73f53daad1050a6a72afb5353a2152f3152ee17168cd0ab28c2cb3e0050e36",
"connected": false,
"channels": [
{
"state": "CHANNELD_NORMAL",
"scratch_txid": "d796aa9c44920cc7169cdb61e36437bf180cedaec44103a69591ce2baac9b1d9",
"last_tx_fee": "14329000msat",
"last_tx_fee_msat": "14329000msat",
"feerate": {
"perkw": 19791,
"perkb": 79164
},
```
Then in the logs:
```
2021-07-23T19:34:56.227Z DEBUG   039c73f53daad1050a6a72afb5353a2152f3152ee17168cd0ab28c2cb3e0050e36-channeld-chan#39381: billboard perm: update_fee 17055 …
```

connectd: allow out-of-bounds fees unless they're actually getting *worse*

---

contrib/pyln-client/pyln/client/lightning.py

The issue is that the new keyword `force_lease_closed` was being set
even if the user didn't specify it, which results in breakage if this
new pyln version talks to older c-lightning nodes that don't have this
keyword yet. By setting the default to `None` it gets filtered out if
the user has not explicitly set it, but still retains the `True` /
`False` values if they did.
Changelog-None Issue is not present in released versions

pyln: Fix backward compat issue in `LightningRpc.close`

---

CHANGELOG.md

(Should have been a Changelog-Changed line, bad Rusty!)

CHANGELOG.md: note the broadening in fee_update accept behavior.

---

doc/lightning-decode.7
doc/lightning-decode.7.md
plugins/offers.c
plugins/offers_offer.c
plugins/offers_offer.h
tests/test_pay.py

It subsumes `decodepay`, and it's nicer if people can just assume it's
available at all times.
Changelog-Added: JSON-RPC: `decode` now available without `experimental-offers`

offers: make `decode` command available even without experimental-offers

---

doc/lightning-openchannel_bump.7
doc/lightning-openchannel_bump.7.md
plugins/funder.c
plugins/funder_policy.c
plugins/test/run-funder_policy.c
tests/test_closing.py
tests/test_connection.py
tests/test_opening.py
tests/utils.py

Quick patch to default to only 'lease-only' channel leases. Effectively shuts off putting money into channels on RBF attempts in the default case.

Default to lease-only for funder plugin

---

lightningd/chaintopology.c
tests/test_misc.py
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/wallet.c
wallet/wallet.h

This actually caused the flake in test_funding_reorg_private, where
l1 and l2 might not mark the original channel disabled.  In fact, they
should *remove* it as it gets reorged out.

chaintopology: tell gossipd that channels no longer exist on reorg.

---

tests/test_closing.py

If l3 is too slow, it can get channel_announcement after channel
is closed, so it gets upset at the node_announcement which follows:
022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-gossipd: Updated pending announce with update 103x1x1/1
022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-gossipd: channel_announcement: no unspent txout 103x1x1
022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-gossipd: Bad gossip order: WIRE_NODE_ANNOUNCEMENT before announcement 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518

pytest: fix bad gossip flake.

---

tests/test_closing.py

We fail waiting for 'Resolved OUR_UNILATERAL/DELAYED_OUTPUT_TO_US by our proposal OUR_DELAYED_RETURN_TO_WALLET'
because we close *two* channels, but only wait for one transaction before mining a block.
This means we might only have one, and we immediately mine the next wait_for_mempool=1,
so the OUR_DELAYED_RETURN_TO_WALLET isn't mined.
Changelog-None

pytest: fix test_channel_lease_unilat_closes flake

---

tests/test_closing.py

We actually were waiting for l3 to disconnect, not l2.
But in general we should be looking for status rather than grovelling
in the logs where possible, so I changed all those.
```
2021-08-17T04:40:34.9015538Z         # l2 leases a channel from l3
2021-08-17T04:40:34.9016520Z         l2.rpc.connect(l3.info['id'], 'localhost', l3.port)
2021-08-17T04:40:34.9017570Z         rates = l2.rpc.dev_queryrates(l3.info['id'], amount, amount)
2021-08-17T04:40:34.9018724Z         l3.daemon.wait_for_log('disconnect')
2021-08-17T04:40:34.9019851Z         l2.rpc.connect(l3.info['id'], 'localhost', l3.port)
2021-08-17T04:40:34.9021467Z         l2.rpc.fundchannel(l3.info['id'], amount, request_amt=amount,
2021-08-17T04:40:34.9022865Z                            feerate='{}perkw'.format(feerate), minconf=0, …
```

pytest: fix flake in test_channel_lease_unilat_closes

---

connectd/connectd.c
doc/PLUGINS.md
lightningd/connect_control.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
lightningd/plugin.c

This does:
- remove duplicate connection attempt if addr_hint was set and also added by gossip.
- try non-tor connections first as they are usually faster and more reliable.
- renames variable "use_proxy_always" to "always_use_proxy" to match config.

Improve connectd to try non-tor connection first and filter duplicates

---

tests/test_pay.py

The function is already provided in contrib/pyln-testing/pyln/testing/utils.py (which is also imported in this module), so there is no need to define it a second time.

pytest: remove only_one() duplicate

---

common/gossmap.c
common/gossmap.h
common/test/run-gossmap_local.c
common/test/run-route-specific.c
common/test/run-route.c
devtools/route.c
devtools/topology.c
plugins/fetchinvoice.c
plugins/libplugin-pay.c
plugins/test/run-route-overlong.c
plugins/topology.c

gossmap: don't spew to stderr, include counter for callers.

---

doc/BACKUP.md

It seems that the plugin require `--lightning-dir` , using without `--lightning-dir` result with an error.
Also the exact backup file has to be stated.

missing --lightning-dir and exact backup file

---

lightningd/jsonrpc.c

I discovered that my java RPC wrapper has some missing requirements with the jsonrpc 2.0 protocol, and the unusual thing is that it is accepted inside c-lightning a quest without `"jsonrpc":"2.0"` and as specified in [the specification protocol](https://www.jsonrpc.org/specification) the string must be present inside the request.

Required jsonrpc string propriety inside the JSON rpc method request.

---

contrib/pyln-client/Makefile
contrib/pyln-proto/requirements.txt
contrib/pyln-testing/Makefile
contrib/pyln-testing/pyln/testing/btcproxy.py

Fixes the following error https://github.com/vincenzopalazzo/lnprototest/runs/3401023486?check_suite_focus=true#step:3:5839 on `lnprototest`, we can safely require the minimum version instead of a fixed oneversion.

Move to minimum required mypy dependeces

---

doc/conf.py

Turns out sphinx added native markdown support, so this config was now failing.
Changelog-None

docs: Remove explicit markdown configuration for rtd

---

wire/extracted_peer_04_opt_will_fund.patch

Running `make extract-peer-csv` gives the wrong result, so fix the patch.

wire: fix up lease_rates patch to what was actually applied

---

lightningd/peer_htlcs.c
tests/test_gossip.py

From a report in IRC channel, I noted that the order of the parameters are wrong in the rpc command.
I assumed that the code take the wrong order because for us (programmers) write documentation is costly more than code :-)
In addition, I think is more natural to have as the first parameter the status, in my opinion, it is more frequently have a filter by the status instant of the filter by channel id.
In conclusion, I can revert the change and modify the docs, or if this change is good, I'm happy to know if the place where I wrote the test is a correct place (test_peers.py or test_rpc.py file is missed).

Fixed order parameter in the listforwards command

---

common/initial_commit_tx.c
configure

First patch simple enables CI to find the bug, second fixes it.  If there's a third, that means we found more!

Detect and fix stack overflows!

---

doc/lightning-listnodes.7
doc/lightning-listnodes.7.md
doc/lightning-multiwithdraw.7
doc/lightningd-config.5
doc/schemas/listnodes.schema.json

Shows the dangers of "additionalProperties": true.  We didn't have an else
clause, so our incorrect (and, with DF, incomplete!) schema was accepted.
I despair of getting anyone else to write a decent schema with these
semantics :(
Changelog-Fixed: doc: listnodes fields now correctly documented.

doc: fix listnodes schema, doc.

---

doc/PLUGINS.md
lightningd/peer_htlcs.c
tests/plugins/watchtower.py
tests/test_plugin.py

I thought having the `channel_id` and `commitnum` might be a useful addition to the  `commitment_revocation` hook

feat: add  channel_id and commitnum to  commitment_revocation hook

---

doc/PLUGINS.md
lightningd/bitcoind.h
lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/lightningd.c
lightningd/notification.c
lightningd/notification.h
lightningd/plugin.c
lightningd/plugin.h
lightningd/plugin_control.c
lightningd/test/run-find_my_abspath.c
plugins/libplugin.c
plugins/libplugin.h
tests/plugins/test_libplugin.c
tests/test_misc.py
tests/test_plugin.py

As suggested by @cdecker .  A followup PR uses this in developer mode to do leak detection.

Plugin: shutdown notification

---

tools/build-release.sh
tools/mockup.sh

Updates from output of latest version of shellcheck as per SC2268
“Avoid x-prefix in comparisons as it no longer serves a purpose”
https://www.shellcheck.net/wiki/SC2268
Changelog-None

Shellcheck cleanup

---

.gitignore

[QOL] Mac OS X generates these files automatically.

---

lightningd/notification.c

fixes #4778
My `make check` is broken, so hope for the best.

plugin: register `shutdown` instead of `plugin_shutdown` in notifications list

---

contrib/pyln-testing/pyln/testing/utils.py

On my machine it should have produced:
/tmp/ltests-1p0v5z1j/.locks/lock-1631090663.1066182
but instead it produced:
/private/tmp/ltests-1p0v5z1j/.locks/lock-1631090663.105848
The mismatch resulted in a hang inside flock.
Path .resolve() seems to be causing problems for others as well. It appears the library was not meant to handle complex path situations and isn't maintained as such (see link reference).
Since we have already built a full path here anyway, the call to .resolve() appears redundant.
Tested on python 3.9.6 on my Mac OS X 11.4 (20F71), Xcode 12.5.1 (12E507)
Relevant discussion: https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573
Changelog-None

resolve() appears broken on Python 3.7+ on Mac

---

common/crypto_sync.c
common/dev_disconnect.c
lightningd/lightningd.c
lightningd/lightningd.h
plugins/libplugin-pay.c

After recent header files clean-up it was not possible to
build c-lightning 7401b2682. This patch fixes it for me.

Fix build on Alpine Linux and OpenBSD

---

contrib/pyln-client/pyln/client/lightning.py
doc/lightning-listpays.7
doc/lightning-listpays.7.md
doc/lightning-listsendpays.7
doc/lightning-listsendpays.7.md
lightningd/offer.c
lightningd/pay.c
plugins/pay.c
tests/test_pay.py
wallet/db_postgres_sqlgen.c
wallet/db_sqlite3_sqlgen.c
wallet/statements_gettextgen.po
wallet/wallet.c
wallet/wallet.h
wire/channel_type_printgen.c
wire/channel_type_wiregen.c

This is a working in progress feature and it is a proposal to give the user to see the possibility to see the payment filtered by status.
Fixes #4588

Support the the filtering option by status in the listpays and listsendpays

---

tests/test_gossip.py

We can miss it in both logs, so wait for it instead:
```
2021-09-22T07:25:59.1582950Z >       l3.rpc.addgossip(ann.split()[3])
2021-09-22T07:25:59.1583911Z E       AttributeError: 'NoneType' object has no attribute 'split'
```
Changelog-None

pytest: fix flake in test_gossip.py::test_addgossip

---

common/wireaddr.c
connectd/connectd.c
tools/headerversions.c

- `netinet/in.h`: struct sockaddr_in, struct sockaddr_in6
- `unistd.h`: close()

Add missing headers for compiling on FreeBSD 13

---

.github/workflows/macos.yaml

First part of https://github.com/ElementsProject/lightning/issues/4708, building Mac OS on every push and pull request, to make sure we don't break it accidentally.
We don't test since `make pytest` on Github Actions + Mac OS is very flaky, I'll continue working on enabling testing, but that might take a while.
Changelog-None

gci: Add macOS configuration to test compatibility

---

.gitignore

Slightly more precise than #4815 with less risk of accidentally ignoring a file we actually want.
Changelog-None

misc: Add generated files to .gitignore

---

tests/test_gossip.py

It was incredibly flaky due to the potential for l2 announcing the
channel before l1 could get to it, thus suppressing the outgoing
announcement which we were looking for. This now checks either
direction.
Before this fix the failure rate was 24% (out of 100 runs), afterwards
it's 0%.
Changelog-None

pytest: Stabilize `test_addgossip`

---

doc/PLUGINS.md
gossipd/Makefile
gossipd/gossipd.c
gossipd/gossipd_wire.csv
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/onion_message.c
lightningd/options.c
lightningd/plugin_hook.c
plugins/fetchinvoice.c
plugins/offers.c
plugins/offers.h
plugins/offers_inv_hook.c
plugins/offers_inv_hook.h
plugins/offers_invreq_hook.c
plugins/offers_invreq_hook.h
tests/test_pay.py

New onion_message support 3/3: Make fetchinvoice/offers send/receive both

---

contrib/pylightning/README.md

I don't think there are any contributing guidelines so hopefully this is ok :)

pylightning: Make it clear pyln-client should be used instead

---

common/json.c

The current `json_add_literal` does not use its `len` argument, at all:
https://github.com/ElementsProject/lightning/blob/09c2fef4a409d70f4be150e8b4c8900d5c1c5d88/common/json.c#L1076-L1083
Which is something of a WTF, why even require the `len` argument if it
is not even used in the function?
This would have been acceptable if it were a callback and the
callback-requiring function passed it in always, but this function is
not intended to be a callback but instead to be called directly.
Existing callers always pass in `strlen(literal)`, so this bug was not
noticed before:
https://github.com/ElementsProject/lightning/blob/09c2fef4a409d70f4be150e8b4c8900d5c1c5d88/lightningd/jsonrpc.c#L511
https://github.com/ElementsProject/lightning/blob/09c2fef4a409d70f4be150e8b4c8900d5c1c5d88/lightningd/jso …

common/json.c: Have `json_add_literal` *use* `len` argument.

---

plugins/funder.c
plugins/libplugin.c
plugins/libplugin.h
plugins/spender/openchannel.c
tests/plugins/test_libplugin.c

We always allocate a new `struct command` when we get a full JSON
object from stdin:
https://github.com/ElementsProject/lightning/blob/b2df01dc73ea7a51ae2a495281bf4d775eafa0a4/plugins/libplugin.c#L1229-L1233
If it happens to be a notification, we pass the `struct command` to
the handler, and not free it ourselves:
https://github.com/ElementsProject/lightning/blob/b2df01dc73ea7a51ae2a495281bf4d775eafa0a4/plugins/libplugin.c#L1270-L1275
There are only nine points in `plugins/libplugin.c` where we `tal_free`
anything, and only one of them frees a `struct command`:
https://github.com/ElementsProject/lightning/blob/b2df01dc73ea7a51ae2a495281bf4d775eafa0a4/plugins/libplugin.c#L224-L234
The above function `command_complete` is not appropriate for
notification handlers; the above function sends …

plugins/libplugin.c: Allow freeing notification `struct command *`.

---

common/daemon.c
tests/test_connection.py
tests/test_opening.py

* A memory leak detected (in debug mode only)
* Fix raised error testing regex to work on Mac OS X in a few places

Small Mac OS X python test fixes

---

channeld/channeld.c
channeld/channeld_wire.csv
closingd/Makefile
common/ping.c
common/ping.h
common/read_peer_msg.c
common/read_peer_msg.h
doc/lightning-ping.7.md
gossipd/gossipd.c
gossipd/gossipd.h
gossipd/gossipd_wire.csv
lightningd/channel_control.c
lightningd/gossip_control.c
lightningd/ping.c
openingd/Makefile
tests/test_connection.py
tests/test_misc.py
wire/peer_wire.c

This might help stability of Tor connections, but I made it universal since it's easier (in particular, it's hard to tell which *incoming* connections are Tor, since they usually come from localhost).

Rework ping logic, have channeld ping regularly.

---

openingd/common.c
plugins/offers.c
tests/test_connection.py

Fixes https://github.com/ElementsProject/lightning/issues/4827
Preferring to round from `msat to sat,` instant to fail from `sat to msat`
Changelog-None: Avoid mixing different currency conventions in a generic error message.

Fixes msat and sat convention in the error message.

---

lightningd/options.c

Fixes https://github.com/ElementsProject/lightning/issues/4869.
I agree with the idea that we need to give the possibility to run a log in a quiet way.
Changelog-None: Move log level from warning to info when creating a new ln directory.

Move log level from warning to info when create a new ln directory

---

plugins/spender/fundchannel.c

During my walk throw the code, I found this typo in the error message.
Changelog-None: Fix typo in the fund channel error message

Fix typo in the fund channel error message

---

devtools/sql-rewrite.py
lightningd/peer_htlcs.c
wallet/db.c

Fixes #4887
Fixes #4879 
Fixes #4891

Fix out-of-sync sequence for psql and wrap destructor in optional DB transaction

---

.github/workflows/ci.yaml
doc/lightning-check.7.md
doc/lightning-cli.1.md
doc/lightning-close.7.md
doc/lightning-connect.7.md
doc/lightning-createonion.7.md
doc/lightning-disconnect.7.md
doc/lightning-fundchannel.7.md
doc/lightning-fundpsbt.7.md
doc/lightning-getroute.7.md
doc/lightning-invoice.7.md
doc/lightning-listfunds.7.md
doc/lightning-multifundchannel.7.md
doc/lightning-multiwithdraw.7.md
doc/lightning-txprepare.7.md
doc/lightning-withdraw.7.md
doc/lightningd-config.5.md
doc/lightningd.8.md

Testing the reproducible build with rc1 showed a couple of issues:
- `mrkd` on ubuntu:18.04 doesn't like non-ASCII characters
- Fetching tags and branches can cause conflicts on CI
- Missing `websocketd` ignore

Intra-release candidates fix

---

Makefile

On some distributions (e.g. Gnu Guix) Python packages are not installed in
some standard directory, rather they are installed in different places and
the `PYTHONPATH` variable is modified to include the different places.
So, we must not use the name `PYTHONPATH` in our `Makefile` since `make`
will replace the `PYTHONPATH` environment variable, preventing e.g.
`tools/generate-wire.py` from finding `python-mako` installed on such
distributions.

Makefile: Avoid overriding `PYTHONPATH`.

---

.gitignore
doc/HACKING.md
doc/INSTALL.md

In my quest to get `make -j12 full-check PYTEST_PAR=24 DEVELOPER=1 VALGRIND=0` to work on Ubuntu from [HACKING.md](https://github.com/ElementsProject/lightning/blob/master/doc/HACKING.md#testing), I came across some directories not ignored and had to install some dependencies. Updated the deps install docs and added some dirs to gitignore.

Update install docs and add some files to gitignore

---

plugins/pay.c

It's always been there:
```
{
"pay": [
{
"bolt11": "...",
"amount_msat": "1000msat",
"amount_msat": "1000msat",
"destination": "03...",
"attempts": [
{
"strategy": "Initial attempt",
"start_time": "2021-11-06T04:20:20.135Z",
"age_in_seconds": 229032,
"end_time": "2021-11-06T04:20:27.792Z",
"state": "completed",
"success": {
"id": 31994,
"payment_preimage": "..."
}
}
]
}
]
}
```
Reported-by: denis2342 on IRC
Changelog-Fixed: JSON-RPC: `paystatus` entries no longer have two identical `amount_msat` entries.

paystatus: remove doubled amount_msat.

---

contrib/pyln-spec/bolt1/requirements.txt
contrib/pyln-spec/bolt2/requirements.txt
contrib/pyln-spec/bolt4/requirements.txt
contrib/pyln-spec/bolt7/requirements.txt

The correct package name is [pyln-proto](https://github.com/ElementsProject/lightning/blob/12689674c7546a6b6ee70839e3867e04dcd33a2f/contrib/pyln-proto/setup.py#L22). H/T @erikarvstedt

pyln-bolt7: fix requirements.txt

---

doc/BACKUP.md
doc/lightningd-config.5.md
tests/test_db.py
wallet/db_sqlite3.c

ChangeLog-Added: With the `sqlite3://` scheme for `--wallet` option, you can now specify a second file path for real-time database backup by separating it from the main file path with a `:` character.
Created as draft since not yet sufficiently tested, lemme check a bit.  Milestoned next version

wallet/db_sqlite3.c: Support direct replication of SQLITE3 backends.

---

lightningd/subd.c

```
cc lightningd/subd.c
lightningd/subd.c:216:7: error: expected identifier or '('
int stdout = STDOUT_FILENO, stderr = STDERR_FILENO;
^
/usr/include/stdio.h:198:17: note: expanded from macro 'stdout'
^
lightningd/subd.c:216:7: error: expected ')'
/usr/include/stdio.h:198:17: note: expanded from macro 'stdout'
^
lightningd/subd.c:216:7: note: to match this '('
/usr/include/stdio.h:198:16: note: expanded from macro 'stdout'
^
lightningd/subd.c:224:12: error: cannot take the address of an rvalue of type 'FILE *' (aka 'struct __sFILE *')
fds[1] = &stdout;
^~~~~~~
lightningd/subd.c:225:12: error: cannot take the address of an rvalue of type 'FILE *' (aka 'struct __sFILE *')
fds[2] = &stderr;
^~~~~~~
4 errors generated.
gmake: *** [Makefile:279: lightningd/subd.o] Error 1
```
Changelog-None: …

lightningd: fix compilation error on OpenBSD

---

doc/BACKUP.md

ChangeLog-None
#4857 suggests that even if we indicate a 60-second timer, `litestream` might still lead to crashes.  Given #4890 is already merged in, we should encourage use of that instead.

doc/BACKUP.md: Discourage litestream use.

---

doc/PLUGINS.md

I noticed that `wallet/db_postgres.c` never actually calls `db_changes_add`.
PostgreSQL arguably has a better replication system (a PostgreSQL cluster)
than what `db_write` hook can offer, so rather than make `db_write` work on
PostgreSQL, just document that it does not actually work there.
ChangeLog-none

doc/PLUGINS.md: Clarify that `db_write` hook only works on SQLITE3.

---

contrib/pyln-testing/pyln/testing/utils.py
tests/test_plugin.py

This should reduce the flakes we're getting due to kill -9, which I suspect is OOM killer.
I printed out the total %mem, mem and vsz every 5 seconds and ran the full testsuite with VALGRIND=1 SLOW_MACHINE=1 (non-parallel).  The largest mem users were those creating many nodes (of course), and this should help with that.
Changelog-None

Reduce mem usage for CI with valgrind

---

bitcoin/chainparams.c

Fixes: #4924
ChangeLog-Changed: `signet` addresses and invoices now use `tbs` instead of `tb`.

bitcoin/chainparams.c: Change `signet` BIP173 name to `tbs`.

---

.gitignore
common/json_helpers.c
common/test/run-ip_port_parsing.c
common/wireaddr.c
common/wireaddr.h
connectd/connectd.c
connectd/netaddress.c
devtools/gossipwith.c
doc/lightning-getinfo.7.md
doc/lightning-listnodes.7.md
doc/schemas/getinfo.schema.json
doc/schemas/listnodes.schema.json
lightningd/options.c
tests/test_gossip.py

This implements RFC https://github.com/lightningnetwork/lightning-rfc/pull/911 to allow annoucements of DNS hostnames.
The feature can only be used with `EXPERIMENTAL`.
The bold quotes are disabled in the topmost commit to please CI.
Adds:
- related fixes and changes (i.e. announce up to two addresses of the same type)
- feature itself
- and tests

bolt7: dns support

---

common/hsm_encryption.c
common/jsonrpc_errors.h
doc/PLUGINS.md
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/lightningd.c
lightningd/plugin.c
lightningd/plugin.h
lightningd/plugin_hook.c
plugins/libplugin-pay.c
tests/plugins/misc_notifications.py
tests/test_closing.py
tests/test_connection.py
tests/test_misc.py
tests/test_plugin.py
wallet/db.c
wallet/db.h
wallet/db_common.h
wallet/wallet.c
wallet/wallet.h

Another proof of concept (should I make this a draft PR?), to address issues raised in #4785 #4790 and  #4883 
The point of shutdown is to break-down or reduce activity. Starting a new `io_loop` in order to write `shutdown` notifications to plugins and wait for them to terminate, should not trigger new activity other then logging and (maybe?) notifications.
So before restarting this `io_loop` we shutdown subdaemons and disable handling of all JSON RPC requests and responses with an "id" field in it. Hook callback's will abandon already and without subdaemons or JSON RPC no new hooks can be called. All of that should prevent any `db_write`'s and we can safely start the `io_loop` and shutdown all plugins.
Also cleans up some dead code related to unused `destroy_utxos` destructor.
TODO:

lightningd: make shutdown smoother and safer

---

tests/test_connection.py

As noted in https://github.com/ElementsProject/lightning/pull/4897/commits/0a406230d051a83f9f029054efe2dd24e87887a8#diff-5871d4c569454db5e625383975462132da0bd03d32df145d8d72d8fafd86d952R3544-R3546
Turns out we sometimes hang up before l2 sees the previous tx revoked,
so we get a normal unilateral close, not a cheat.
Reported-by: Simon Vrouwe
Changelog-None

pytest: fix flake in testing.

---

wallet/db.c
wallet/wallet.c

Closes: #4901
Tested by `EXPLAIN QUERY PLAN` on sqlite3; #4901 shows the result from
@whitslack doing a similar partial index on PostgreSQL on his ~1000 chan
node.

wallet/db.c, wallet/wallet.c: Add a partial index to speed up startup.

---

common/json_tok.c
common/json_tok.h
common/route.h
contrib/pyln-client/pyln/client/lightning.py
doc/lightning-pay.7.md
plugins/libplugin-pay.c
plugins/libplugin-pay.h
plugins/pay.c
plugins/topology.c
tests/test_pay.py
tests/test_plugin.py

This adds an `exclude` option to the `pay` command, similar to the `exclude` option of the `getroute` command. This is motivated by https://github.com/ElementsProject/lightning/issues/2529, and can be closed via plugin after this is merged.

Add exclude option to pay

---

common/status.c

Debug logging of ping and pong packets turned out to be
too excessive since this is now done on all channels
and without config option.
Changelog-None

status: do not log ping and pong packets

---

common/wireaddr.c
common/wireaddr.h
connectd/connectd.c
lightningd/options.c
tests/test_connection.py

I noticed that experimental-websocket-port didn't work on my node (it crashed).  Along the way, I found a bug in DNS handling.

Websocket fix

---

tests/test_gossip.py

We make sure the gossip msg was sent, but the other node might not
have digested it yet:
```
>       addresses = l2.rpc.listnodes(l1.info['id'])['nodes'][0]['addresses']
E       KeyError: 'addresses'
```
Changelog-None

pytest: fix occasional flake in test_announce_address

---

Makefile
wallet/Makefile

This updates `make clean` to also remove all generated source and header files. This would have resolved https://github.com/ElementsProject/lightning/issues/4939 with a `make clean`, but instead the user ended up nuking the repo and cloning again.
There is a comment about only removing generated files with `make maintainer-clean`:
> This command is intended for maintainers to use; it deletes files that may need special tools to rebuild.
I checked and all generated files are not checked in source control, so anything that succeeds in building already has all available tools. Not sure if that comment is out of date or if there is some history behind it that I'm not aware of, but it seems that it is safe to remove these generated source and header files on `make clean`.

make: remove generated files when running clean

---

Dockerfile

Bitcoin-cli deployed in the docker image is a bit old (0.18.1).
We can update it to 0.21.1

Update bitcoin-cli to 0.21.1

---

tests/test_plugin.py

The last line of the testcase was checking on the wrong node l3
instead of l1. l3 didn't had the plugins configured that would
produce the log entry we were looking for not to be present.
Changelog-None

pytest: fix test_pluginconnected_hook_chaining

---

connectd/connectd.c
tests/test_gossip.py

1. Adds the missing DNS error massages so they can be handled by
connect_control.
2. Prepends a 'All addresses failed' to code 401 message, so we
always have at least some error message to the user.
Changelog-None

connectd: fix empty error message

---

.gitignore

`.tmp` files are generated from compiling the docs, these should be ignored by git

Update .gitignore for tmp files

---

channeld/channeld.c
common/timeout.c
common/timeout.h
connectd/connectd.c
gossipd/gossipd.c
gossipd/test/run-onion_message.c
gossipd/test/run-txout_failure.c
lightningd/io_loop_with_timers.c
lightningd/lightningd.c
lightningd/plugin.c
lightningd/plugin.h
lightningd/plugin_hook.c
lightningd/test/run-find_my_abspath.c
tests/plugins/misc_notifications.py
tests/test_pay.py
tests/test_plugin.py
wallet/db.c
wallet/db.h
wallet/db_common.h

Follow up of #4897, fixes the issues raised in that PR. (similar to #4947, but could not reopen it after force push)
- Simply close the `db` in the `shutdown_plugins`, this partially reverts 5f69674faaf4763e4457431e27c35147e0d52bc5 (the part that touched  `wallet` code).
- Use a simpler `io_loop` in `shutdown_plugins`
- Removed `test_htlc_accepted_hook_shutdown`, moved relevant parts into `test_plugin_shutdown`
Some cleanup: `timer_expired()` had an obsolete parameter.
BTW I found below comment inside `io_loop` confusing:
https://github.com/ElementsProject/lightning/blob/5a5cf8c69678fa73f211f391a9e938a0b991bb95/ccan/ccan/io/poll.c#L402-L403
Maybe more descriptive would be: `/* Look for expired timers. */`

lightningd: make shutdown smoother and safer, PART II (again)

---

doc/Makefile

Don't do this on every build, it takes 4 seconds.  And split it
into individual targets, so make can parallelize (1.6 seconds here).
Changelog-None

doc/Makefile: speed up schema check, only do on check-doc.

---

channeld/channeld.c
hsmd/hsmd.c
hsmd/hsmd_wire.csv
hsmd/libhsmd.c

Adds hsmd wire-protocol message which allows independent validation of prior state revocation. This allows the signer to ensure the state is fully committed. Provided hsmd handler is a stub.
Please see [Lightning Signer C-Lightning Modification Summary](https://gitlab.com/lightning-signer/docs/-/wikis/C-Lightning-Modifications) for the plan to enable Lightning Signer support.

hsmd: Add hsmd_validate_revocation.

---

plugins/topology.c

incoming_capacity_msat field showed the value as microsat.
before:
{
"incoming": [
{
"id": "02c75ea34304029851769b13e9ccfddf03166562cc045023d7565aefdd26d74a6c",
"short_channel_id": "704410x1060x1",
"fee_base_msat": "0msat",
"fee_proportional_millionths": 1,
"cltv_expiry_delta": 40,
"incoming_capacity_msat": "11972018176000msat"
},.....
after the patch:
{
"incoming": [
{
"id": "02c75ea34304029851769b13e9ccfddf03166562cc045023d7565aefdd26d74a6c",
"short_channel_id": "704410x1060x1",
"fee_base_msat": "0msat",
"fee_proportional_millionths": 1,
"cltv_expiry_delta": 40,
"incoming_capacity_msat": "11972018176msat"
},.....

fix 'listincoming' field incoming_capacity_msat.

---

bitcoin/chainparams.c
bitcoin/chainparams.h
common/addr.c
common/bolt11.c
common/bolt11_json.c
common/json_tok.c
devtools/bolt11-cli.c
devtools/bolt12-cli.c
lightningd/coin_mvts.c
plugins/offers.c
wallet/walletrpc.c

Fixes: #4937
Splitting the field into two fields with completely different names is much safer than adding a new name for one or the other, as the compiler can now be used to audit each site where the original fieldname was used and forces a decision on which of the new fields to use.
**REVIEWERS** Please check each site of each change!  It is important to use the correct field name, whether the offchain or the onchain name.

bitcoin/chainparams.h: Split BIP173 name into onchain and offchain HRPs.

---

hsmd/hsmd.c
hsmd/hsmd_wire.csv
hsmd/libhsmd.c
lightningd/channel.c
lightningd/dual_open_control.c
lightningd/opening_common.c
lightningd/opening_control.c
openingd/dualopend.c
openingd/dualopend_wire.csv
openingd/openingd.c
openingd/openingd_wire.csv
wallet/test/run-wallet.c
wallet/wallet.c
wallet/wallet.h

This PR adds two messages (& replies) to `hsmd_wire.csv`. 
Summary of changes needed to support fully validating signers here:
https://gitlab.com/-/snippets/2179274

hsmd: Add hsmd_new_channel and hsmd_ready_channel messages for validating signers

---

common/ping.c

It seems as if  [PR 918](https://github.com/lightning/bolts/pull/918) will be merged to the bolts so this requirement will be dropped from the spec and we do not need to have a FIXME in the code base.
Yes I know that this is a somewhat silly PR.

Removed FIXME to match bolts PR 918

---

doc/INSTALL.md

This PR will add tips in the docs because on IRC there are some reports on bad resolution versions caused by this bug of `mrkd` https://github.com/refi64/mrkd/pull/6#issue-1073838481
Basically, the package has no fixed version and this gives them the power to pip to pull the last version of the `mistune` dependence, which will break the `mrkd` package.
P.S: The change should be forwarded also to all the docker files, but we hope that release the new version of the package takes only a few days
Changelog-None: doc: force mistune==0.8.4 during pip package resolution.

doc: force mistune==0.8.4 during pip package resolution.

---

tests/test_gossip.py

Follows #4900 which I've now merged.
Changelog-None

pytest: restore gossip advertizement tests for default port.

---

wire/extracted_onion_02_modernonion.patch

You have to manually run "make extract-bolt-csv" to recreate the
spec files, so we didn't notice that I forgot to check this in :(
Changelog-None

wire: add missing spec patch.

---

lightningd/lightningd.c

The comment mentions a 100MB log book, but the code was modified 15 months ago to allocate a 10MB log book to preserve memory.

Fix comment to reflect the code

---

lightningd/options.c
tests/test_gossip.py

Since upcoming https://github.com/lightning/bolts/pull/911 will likely contain `- MUST NOT announce more than one "type 5" DNS hostname.` we need to add this.
Changelog-None

dns: only allow one DNS announcement

---

contrib/pyln-client/pyln/client/lightning.py

Not sure why socket does not accept pathlib, but just added some code to transform the path to string.
It is not the most pretty code, but better than these:
https://stackoverflow.com/questions/58647584/how-to-test-if-object-is-a-pathlib-path

LightningRpc should accept pathlib Path

---

cli/config_cli.h
cli/lightning-cli.c
cli/test/config_test.h
cli/test/run-human-mode.c
cli/test/run-large-input.c
cli/test/run-remove-hint.c

Procedure redefinition is a very cool feature but when other libraries redefine the same function can be very tricky to avoid compilation errors.
This PR proposed a change of logic and use a customization function definition to read from the stdin, so we can avoid future errors at compile time.
However, we could be check also the os or compiler that cause the error and redefine the missing function.
Compilation success on alpine is reported here https://github.com/vincenzopalazzo/lightning/runs/4795110552?check_suite_focus=true
If this PR will be merged the #4987 should be compiled on alpine to each new changes
Fixes https://github.com/ElementsProject/lightning/issues/4918 (really fixes)

cli: change the redefine logic to read from the stdin

---

common/coin_mvt.c
common/coin_mvt.h
common/psbt_open.c
common/psbt_open.h
doc/PLUGINS.md
lightningd/notification.c
lightningd/onchain_control.c
plugins/spender/multiwithdraw.c
plugins/txprepare.c
tests/test_misc.py
tests/test_wallet.py
tests/utils.py
wallet/walletrpc.c

While working on the accounting plugin, I ran into some problems/limitations of our current event emissions.
1) We weren't tracking withdrawals to external wallets (initiated via `withdraw`/`multiwithdraw`). This makes it really difficult to see where our funds are going, as well as confuses the onchain fee tracker that the accountant plugin has. Now, we emit a `coin_movement` for 
2) Funds sent to 'external' accounts don't say which account they originated from. While it's possible to figure this out from the utxo tracking, that's sometimes difficult to reconstruct. Instead, for every `external` deposit, we now record what internal account the payment originated from. For example, wallet payments to an external account will be tagged 'wallet'. Payments to the peer in a channel will …

`coin_movement` updates

---

common/coin_mvt.c
common/coin_mvt.h
doc/PLUGINS.md
doc/lightning-listpeers.7.md
doc/schemas/listpeers.schema.json
lightningd/Makefile
lightningd/coin_mvts.h
lightningd/peer_control.c
wallet/wallet.c

Things found while working on the accountant plugin.
I have no idea how the wallet error made it past previous checks. Whoops.
The `listchannels` addition of the funding_outnum is extremely useful for backfilling missed channel open events.

Nits and fixups

---

wallet/db_sqlite3.c

With this change, we get more fine-grained error messages if something goes wrong in the course of communicating with the SQLite database. To pick some random examples, the error codes SQLITE_IOERR_NOMEM, SQLITE_IOERR_CORRUPTFS or SQLITE_IOERR_FSYNC are way more specific than just a plain SQLITE_IOERR, and the corresponding error messages generated by sqlite3_errstr() will hence give a better hint to the user (or also to the developers, if an error report is sent) what the cause for a failure is.
See the SQLite documentation
https://www.sqlite.org/c3ref/extended_result_codes.html
https://www.sqlite.org/c3ref/c_abort_rollback.html
> In its default configuration, SQLite API routines return one of 30 integer result codes. However, experience has shown that many of these result codes are too …

db: enable SQLite extended result codes

---

doc/lightning-listfunds.7.md
doc/schemas/listfunds.schema.json

I tried to build lightning following the steps here:
https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md
On a box (via ssh) with LC_ALL=C and LANG=C.
I am aware this issue could probably be avoided by setting the locale.
However in my setup I received the following build error
```
$ make
...<snip>
mrkd doc/lightning-listfunds.7.md
File "/home/user/.local/bin/mrkd", line 8, in <module>
sys.exit(main())
File "/home/user/.local/lib/python3.6/site-packages/mrkd.py", line 254, in main
plac.call(entry_point)
File "/home/user/.local/lib/python3.6/site-packages/plac_core.py", line 436, in call
cmd, result = parser.consume(arglist)
File "/home/user/.local/lib/python3.6/site-packages/plac_core.py", line 287, in consume
return cmd, …
```

fix UnicodeDecodeError in doc/lightning-listfunds.7.md

---

bitcoin/tx.c

This define is unused since commit 509bb2c7aee5887a96e8966869c39bb4d5aba766.

bitcoin/tx: remove unused SEGREGATED_WITNESS_FLAG

---

Dockerfile
configure
tools/build-release.sh

The tarball needs to materialze all submodules, and git needs to be
removed as a build dependency. I thought @rustyrussell might find these
useful, so we can distribute the deb packages via the releases page. The
tarball is conforming to the debuild format, hence the extra work.
Changelog-None

misc: Add build targets for the tarball and debian packages

---

doc/Makefile

For some reason, there is no fmt schema command anymore, but just a check it.
So, this command now it is introduced by a helper command that needs to be expressed called by the human with `fmt-schemas`, and it help to format a very big JSON schema like the one introduced in this PR https://github.com/ElementsProject/lightning/pull/5022
Changelog-None

doc: reintroduce the fmt command to fmt the schema

---

contrib/linuxarm32v7.Dockerfile
contrib/linuxarm64v8.Dockerfile

As the `LIGHTNINGD_NETWORK` env variable was added to the Dockerfile in #3813, I added it to the Dockerfile for ARM.

Add LIGHTNINGD_NETWORK env variable to Dockerfile for ARM

---

lightningd/invoice.c

If this field is missing for whatever reason (weird db state?)
clightning will crash when listing invoices.
This started happening when I pulled the latest master. I haven't bisected to see where it was introduced yet, if I even can anymore due to db upgrade.
Changelog-Fixed: jsonrpc: Fixed a crash caused by a missing invoice string in `listinvoices`

json_add_invoice: fix crash if missing invstring

---

common/bolt11.c

When decoding bolt11 tags, it looks like there are checks (`have_c`, `have_x`,
etc) which prevent duplicate tags. Unfortunately `decode_c` doesn't set
`have_c` unlike the other `decode_` methods. At the start of the function,
`decode_c` checks `have_c` to see if it's set, but it is never set. It seems
like this could allow for duplicate `c` tags, which is probably not intended.
It looks like there's the same issue with the `x` (expiry) tag as well.

bolt11: prevent duplicate min_final_cltv_expiry and expiry tags

---

gossipd/gossip_generation.c
tests/test_pay.py

This restores the behaviour prior to `lightningd: use our cached
channel_update for errors instead of asking gossipd.`, where gossipd
would refuse to give us channel_updates for unannounced channels.
@t-bast pinged for opinions!

gossipd: don't send updates in error messages for unannounced channels.

---

hsmd/hsmd.c

`client_read_next(…)` calls `io_read_wire(…)`, passing `&c->msg_in` as the address of a pointer that will be set to the address of the buffer that `io_read_wire_(…)` will allocate, and passing `c` (a pointer to the `struct client` instance) as the parent for the new allocation. As long as the `struct client` instance eventually gets freed, the allocated message buffer will be freed too, so there is no *leak* in the strict sense of the term, but the freeing of the buffer may not occur for an arbitrarily long time after the buffer has become disused, and indeed many millions of message buffers may be allocated within the lifetime of one `struct client` instance.
`handle_client(…)` ultimately hands off the `c->msg_in` to one of several message-type-specific handler functions, and those …

hsmd: don't leak message buffers

---

tests/test_closing.py
tests/test_connection.py

These tests have proven to be:
- very expensive, as they spin up many nodes, and perform long setup
- are not testing anything specific, they just fuzz functionality
that is already tested otherwise
- have not helped pinpoint any issues in living memory
- are very flaky, making for really bad signal-to-noise, so much
that devs usually just restart without even looking at the logs
- even if we were to look at the logs, we'd be unable to reproduce
due to the inherent randomness involved in these tests
- are really noisy neighbors, causing other tests to flake as well,
further muddying the water
All in all, these tests are a waste of time, and source of
frustration.
Changelog-None

pytest: Remove 3 stress-tests

---

configure

Reverts change in 1ef77504b1b8c00fe41e82b205177463924dea6c.

configure: restore -Og default on non-developer builds.

---

bitcoin/test/run-tx-bitcoin_tx_2of2_input_witness_weight.c
contrib/pyln-client/pyln/client/plugin.py
contrib/pyln-testing/pyln/testing/utils.py
devtools/decodemsg.c
devtools/print_wire.c
doc/lightning-connect.7.md
doc/lightning-getinfo.7.md
doc/lightning-listchannels.7.md
doc/lightning-listnodes.7.md
doc/lightningd-config.5.md
doc/schemas/getinfo.schema.json
doc/undoc-flags.json
gossipd/gossip_generation.c
lightningd/options.c
lightningd/peer_control.c
lightningd/test/run-invoice-select-inchan.c
plugins/funder.c
tests/test_closing.py
tests/test_connection.py
tests/test_gossip.py
tests/test_misc.py
tests/test_opening.py
tests/test_plugin.py

So I was trying to connect the dots to understand dual-fund and leases and then give it a shot.
Did my first dual-fund on mainnet a couple of days ago and then a lease, it all worked out, very cool.
I needed to run custom pytest's, looked up Bolt pull-requests, to get some confidence in the meaning of various options and parameters. And came across a few issues during my journey.
For which I propose fixes in this PR:
- a single location to see our features (bits) would be handy (proposed in issue [#4310](https://github.com/ElementsProject/lightning/issues/4310)) **edit:** just found out plugin [init](https://lightning.readthedocs.io/PLUGINS.html#the-init-method) `configuration` has these also and a [plugin](https://github.com/ElementsProject/lightning/blob/master/tests/plugins/feature-test …

Improve UX of experimental options/features and other small fixes

---

tests/test_closing.py

Flake on CI coming from `penalty_in/outhtlc` due to the fact that all
the events haven't arrived for the check.
If we wait to sync `l1` as well as `l2`, this should resolve the flake.
>       tags = check_utxos_channel(l1, [channel_id], expected_1)
tests/test_closing.py:726:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:321: in check_utxos_channel
txid = matchup_events(u_set, evs, chans, tag_list)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
u_set = [[{'account_id': 'external', 'blockheight': 104, 'coin_type': 'bcrt', 'credit': '100000000msat', ...}, None]]
evs = [('external', ['penalty'], None, None), ('external', ['penalty'], None, None), ('external', ['penalty'], None, None)]
chans = …

test_close: sync l1 to the blockchain, so that the events are there

---

bitcoin/tx_parts.c
common/coin_mvt.c
common/coin_mvt.h
common/json_helpers.c
common/json_helpers.h
common/test/Makefile
devtools/Makefile
doc/PLUGINS.md
doc/lightning-listpeers.7.md
doc/schemas/listpeers.schema.json
gossipd/test/Makefile
lightningd/channel_control.c
lightningd/coin_mvts.c
lightningd/notification.c
lightningd/onchain_control.c
lightningd/peer_control.c
onchaind/onchaind.c
onchaind/test/run-grind_feerate-bug.c
onchaind/test/run-grind_feerate.c
plugins/Makefile
tests/test_closing.py

A few more things fell out in the wash, so to speak, while working on the upcoming `bookkeeper` plugin.

More coin_move adjustments

---

connectd/connectd.c
connectd/connectd.h
connectd/connectd_wire.csv
connectd/tor_autoservice.c
connectd/tor_autoservice.h
lightningd/connect_control.c

Aditya had this issue due to a config line, and the result was hard to diagnose even for me.
It's now:
```
$ ./lightningd/lightningd --network=regtest --addr=:18444
2022-02-26T05:01:28.705Z **BROKEN** connectd: Failed to bind socket for 0.0.0.0:18444: Address already in use
```
Whereas before it doesn't even give the address it's trying to bind:
```
rusty@rusty-XPS-13-9370:~/devel/cvs/lightning (master)$ ./lightningd/lightningd --network=regtest --addr=:18444
lightning_connectd: Failed to bind on 2 socket: Address already in use (version v0.10.2-331-g86b83e4)
0x558a8b8d9a12 send_backtrace
0x558a8b8e91e1 status_failed
common/status.c:221
0x558a8b8c8e4f make_listen_fd
connectd/connectd.c:1090
0x558a8b8c8f55 handle_wireaddr_listen
connectd/connectd.c:1129
0x558a8b8c993d …
```

connectd: be more graceful when an address is in use.

---

gossipd/gossip_generation.c
gossipd/gossipd.c
gossipd/gossipd.h
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-check_node_announcement.c
gossipd/test/run-crc32_of_update.c

This should do something to mitigate the propagation issues seen in https://github.com/ElementsProject/lightning/issues/5037, as well as the problem reported that some LND nodes are scheduling daily downtime which causes 2 updates per day.

Gossip node_announcement more aggressively, allow 2 updates per day for gossip.

---

Cargo.toml
cln-rpc/examples/getinfo.rs
doc/HACKING.md
plugins/Cargo.toml
plugins/Makefile
plugins/examples/cln-plugin-startup.rs
plugins/src/codec.rs
plugins/src/lib.rs
plugins/src/logging.rs
plugins/src/messages.rs
plugins/src/options.rs
tests/fixtures.py
tests/test_cln_rs.py
tests/valgrind-suppressions.txt

This is likely the least mature crate of the cln-* series. It just implements the bare minimum of a plugin's lifetime such that it stays alive when run by `lightningd`. It doesn't yet have custom RPC methods support, nor config support, but I intend to build these out as we go. It is pretty much just the minimum to get us into a situation we can write the `grpc-plugin` plugin.

cln-plugin: Write your plugins in rust

---

doc/BACKUP.md

Backup is a critical field, so we referer to some functionality with "after the vx.x.x". 
P.S: The human brain works better with "not in" evaluation.
Fixes https://github.com/ElementsProject/lightning/issues/5026
Changelog-None: remove ambiguity for functionality enabled after a release version

doc: remove ambiguity for functionality enabled after a release version

---

doc/TOR.md

Updated systemd syntax to prevent issues with initial tor systemd service activation and ensure that the systemd service is refreshed when the /etc/tor/torrc config is updated. 
Changelog-None

Goofy af tor.md systemd syntax update

---

contrib/pyln-client/pyln/client/lightning.py

We must use `None` for default arguments since otherwise they aren't
filtered out when serializing the request. In addition default
arguments to functions are initialized once and, if mutable, could
persist internal changes across function calls.
Changelog-None

pyln: Change the default argument to `exclude` in `pay`

---

channeld/channeld.c
common/htlc_wire.c
common/htlc_wire.h
gossipd/Makefile
hsmd/Makefile
hsmd/hsmd_wire.csv
hsmd/libhsmd.c
lightningd/peer_control.c
lightningd/test/Makefile
lightningd/test/run-invoice-select-inchan.c
openingd/dualopend.c
openingd/openingd.c
tools/generate-wire.py
wallet/test/run-wallet.c

Add to hsmd_sign_remote_commitment_tx:
- commitment_number
- feerate
- htlcs
Add to hsmd_sign_commitment_tx:
- commitment_number
These fields are needed for validating signers.
[Summary of all changes for validating signers](https://gitlab.com/lightning-signer/docs/-/wikis/C-Lightning-Modifications)

hsmd: Add fields to hsmd_sign_commitment_tx and hsmd_sign_remote_commitment_tx

---

doc/lightning-help.7.md

This fixes one leftover backslash from #5018.

fix: Remove \ from help documentation

---

common/memleak.c

By not recursing into "notleak" children, we could miss other "notleak"
pointers:
```
2022-03-15T05:25:33.9759500Z lightningd-1: 2022-03-15T05:00:15.998Z **BROKEN** connectd: MEMLEAK: 0x55b29c3d0cc8
2022-03-15T05:25:33.9759901Z lightningd-1: 2022-03-15T05:00:16.003Z **BROKEN** connectd:   label=common/timeout.c:22:struct oneshot **NOTLEAK**
2022-03-15T05:25:33.9760195Z lightningd-1: 2022-03-15T05:00:16.003Z **BROKEN** connectd:   backtrace:
2022-03-15T05:25:33.9760555Z lightningd-1: 2022-03-15T05:00:16.003Z **BROKEN** connectd:     ccan/ccan/tal/tal.c:442 (tal_alloc_)
2022-03-15T05:25:33.9760905Z lightningd-1: 2022-03-15T05:00:16.003Z **BROKEN** connectd:     common/timeout.c:22 (new_reltimer_)
2022-03-15T05:25:33.9761272Z lightningd-1: 2022-03-15T05:00:16.003Z **BROKEN** connectd: …
```

memleak: make sure we catch children which are also "notleak".

---

contrib/pyln-client/pyln/client/lightning.py
contrib/pyln-client/pyproject.toml
contrib/pyln-proto/pyproject.toml
contrib/pyln-spec/bolt1/pyproject.toml
contrib/pyln-spec/bolt2/pyproject.toml
contrib/pyln-spec/bolt4/pyproject.toml
contrib/pyln-spec/bolt7/pyproject.toml
contrib/pyln-testing/pyproject.toml
poetry.lock
pyproject.toml

Turns out that the pyln-proto dependency in the bolt packages is only
needed for testing, not for production. Making it a dev-dependency
means it isn't considered in resolution anymore.
Since the bolt, testing and client packages are to be used outside
from the project we can't use relative dependencies either, so make
then dependent on the version on PyPI. This also means we had to push
a couple of updated to PyPI.
Changelog-None

py: Disentangle pyln dependencies

---

common/errcode.h
common/hsm_encryption.c
common/hsm_encryption.h
lightningd/hsm_control.c
lightningd/options.c
tests/test_pay.py
tests/test_wallet.py
tools/hsmtool.c

Fixes https://github.com/ElementsProject/lightning/issues/5073
Fixes https://github.com/ElementsProject/lightning/issues/4623
This is one of my first attempts to improve the command line UX when we are asking a password to decrypt an `hsm_secret` already encrypted.
In addition, this introduces the check between the password and password confirmation in the cmd option when the password confirmation is provided

cli: make the command line more user friendly.

---

doc/PLUGINS.md
doc/lightning-createonion.7.md
doc/lightning-getroute.7.md
doc/schemas/getroute.schema.json
lightningd/pay.c
plugins/bcli.c

We keep the parameter around for future use (e.g. PTLC support?), but clboss
master still sets 'style' to "legacy".  Accept, but ignore it.
Reported-by: grubman on #c-lightning (IRC)
Changelog-None: change introduced this release

lightningd: allow 'style' 'legacy' for clboss compat (with deprecated_apis)

---

doc/lightning-fundchannel_start.7.md
doc/schemas/fundchannel_start.schema.json
lightningd/opening_control.c

"A friend" nearly shot himself in the foot by prematurely sending coins to the address returned by this. Apparently he managed to cancel the transaction with a double-spend just in time.
This PR adds some bigger warnings.
Changelog-None

Add more warnings to fundchannel_start

---

lightningd/pay.c

fail can be NULL here.
Reported-by: https://github.com/shafemtol
Fixes: #5053
Changelog-None

pay: fix crash on invalid onion in reply in some cases.

---

common/gossmap.c

There's a race under CI, where a channel is deleted then we see the
channel_update in the gossip store.  We assumed this wouldn't happen,
but it can!
```
[gw1] [ 95%] FAILED tests/test_connection.py::test_multichan
[gw1] [ 95%] ERROR tests/test_connection.py::test_multichan
...
>           raise ValueError(str(errors))
E           ValueError:
E           Node errors:
E            - lightningd-3: had BROKEN messages
E            - lightningd-3: Node exited with return code 1
E           Global errors:
...
lightningd-3: 2022-03-28T00:11:42.160Z DEBUG   wallet: Owning output 0 100000sat (SEGWIT) txid 30616903feba1839a3834e2b3b6123759ce1fe0d76414ca77e2dbc17414772e0 CONFIRMED
lightningd-3: 2022-03-28T00:11:42.392Z DEBUG   hsmd: Client: Received message 5 from client
lightningd-3: …
```

plugins/topology: don't get upset if we hit deleted channel.

---

.github/workflows/pypi.yml
contrib/pyln-client/pyproject.toml
contrib/pyln-proto/pyproject.toml
contrib/pyln-testing/pyproject.toml

Seems PyPI have recently bumped the `long_description` warning to become an error. This PR addresses that by adding the README.md as the `long_description` where we have one, and using `poetry` for publication as well, instead of mixing tools.
Changelog-None

py: Update the PyPI job to use poetry and correct versions

---

lightningd/channel_control.c
lightningd/closing_control.c
lightningd/dual_open_control.c
lightningd/onchain_control.c
lightningd/opening_control.c
lightningd/subd.c
lightningd/subd.h

We get some memleak reports because ld owns the subd, but once
the peer/channel is freed, there's no reference for the brief time
until the subd exits.
This happens for both opening and closingd.  For openingd, the
peer owns it, for others (including dualopend) the channel owns it.

subd: make channel/peer own the subd.

---

Cargo.toml
Makefile
cln-grpc/Cargo.toml
cln-grpc/proto/node.proto
cln-grpc/src/convert.rs
cln-grpc/src/server.rs
cln-rpc/src/model.rs
contrib/msggen/msggen/__main__.py
doc/schemas/connect.request.json
plugins/Makefile
plugins/grpc-plugin/Cargo.toml
plugins/grpc-plugin/src/main.rs
plugins/grpc-plugin/src/tls.rs
plugins/src/lib.rs
poetry.lock
pyproject.toml
tests/test_cln_rs.py
tools/build-release.sh

This is the final PR in the cln-* series. It uses all the primitives we built in the previous 3 PRs and uses them to expose the JSON-RPC over grpc, with mTLS authentication builtin.

cln-grpc-plugin: Secure access to your node over the network

---

plugins/pay.c

See: https://github.com/ElementsProject/lightning/issues/4991
We seem to correctly set end_time everywhere, so this looks like
a use-after-free somehow?  But this will fix the crash right here :(
@cdecker can you see if you can see anything?  Some weird stuff happening in that log...
Changelog-None

plugins/pay: don't crash on malformed time.

---

.github/workflows/ci.yaml
contrib/docker/Dockerfile.ubuntu
contrib/docker/scripts/build.sh
contrib/docker/scripts/entrypoint.sh
contrib/docker/scripts/setup.sh

I noted that some protocol tests takes a while and rusty find a bug in lnprototest, but the lnprototest still is stuck https://github.com/ElementsProject/lightning/pull/5125
With this PR I'm trying to migrate the work on the Docker image because in the lnprototest integration testing works like a charm in only 12 minutes https://github.com/rustyrussell/lnprototest/runs/5670869353?check_suite_focus=true

ci: migrate the protocol test inside the docker image

---

channeld/full_channel.c
connectd/connectd.c
connectd/connectd.h
connectd/connectd_wire.csv
connectd/multiplex.c
lightningd/connect_control.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/onchain_control.c
lightningd/options.c
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h
onchaind/onchaind.c
tests/test_closing.py

Firstly, I added an explicit test to try to mirror https://github.com/ElementsProject/lightning/issues/4649
Then I added more debugging and checks if it happens again.

HTLC upstream close debugging additions

---

doc/lightning-listconfigs.7
doc/lightning-listconfigs.7.md
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
lightningd/lightningd.h
lightningd/opening_common.c
lightningd/opening_control.c
lightningd/options.c
lightningd/peer_control.c
tests/test_connection.py
tests/test_pay.py

This adds config and commanline switches for HTLC min/max values and announcement of auto discovered IPs

feat: config additions

---

wallet/wallet.c

User grubman on IRC reported a crash due to new HTLC checks (update: my node too!)
```
2022-04-05T01:15:17.707Z **BROKEN** wallet: Missing preimage for orphaned HTLC; replacing with zeros
...
2022-04-05T01:15:44.950Z **BROKEN** lightningd: check_already_failed:Both failed and succeeded?
2022-04-05T01:15:45.020Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.11.0rc1-modded)
2022-04-05T01:15:45.020Z **BROKEN** lightningd: backtrace: common/daemon.c:38 (send_backtrace) 0xaaaab8f7f8bb
2022-04-05T01:15:45.020Z **BROKEN** lightningd: backtrace: common/daemon.c:46 (crashdump) 0xaaaab8f7f91b
2022-04-05T01:15:45.020Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffa4a315bf
2022-04-05T01:15:45.020Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffa45c6cd8 …
```

wallet: don't get so upset on orphaned HTLC.

---

doc/INSTALL.md

During some onboarding of summer of bitcoin guys, I noted that our installation process for osx was outdated
Fixes https://github.com/ElementsProject/lightning/issues/5156
Changelog-None: docs: use poetry in the osx installation process

docs: use poetry in the osx installation process

---

plugins/grpc-plugin/src/main.rs
plugins/src/lib.rs
plugins/src/messages.rs
tests/test_cln_rs.py

Alternative to #5173. This is relatively simple, and just disables listening, but doesn't exit if `grpc-port` isn't set, so we don't need to disable the plugin itself.
This is a quick fix, until we find a good way of doing `init` callbacks that are clean.

Disable grpc plugin if `grpc-port` is not set

---

doc/HACKING.md

The relative path makes for a difficult experience when people are reading on `https://lightning.readthedocs.io/`. Directly linking saves the reader a few clicks hunting down the correct location :)
Current experience:

use full path to reference `lightningd.c`

---

common/blinding.c
common/bolt12.c
common/key_derive.c
devtools/bolt12-cli.c
hsmd/libhsmd.c
lightningd/offer.c
plugins/fetchinvoice.c
plugins/offers_inv_hook.c
plugins/offers_invreq_hook.c

Combined with the following commit which is required to
update against changed libsecp256k1 APIs:
Updated deprecated function calls
This is #5172 squished into a single commit (so it doesn't break bisect!) and removing the extraneous commit.
Changelog-None

Changed external/libwally-core to 0.8.5 release

---

openingd/dualopend.c

Happens in CI:
```
lightningd-2: 2022-04-10T15:30:40.788Z **BROKEN** 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-dualopend-chan#1: STATUS_FAIL_MASTER_IO: Error parsing 7507: 1b79
```
Changelog-None

dualopend: handle dev_memleak during RBF.

---

lightningd/peer_control.c

This was hit on my node.
Changelog-None: introduced since last release.
Fixes: #5185

lightningd: remove over-zealous assert.

---

connectd/connectd.c

I was seeing a strange crash:
Connectd gave bad CONNECT_PEER_CONNECTED message
The message is indeed mangled, around the remote_addr!
A quick review of the code revealed that we were not making a copy
when it was a reconnect, and so the remote_addr pointer was pointing
to memory which was freed.
Changelog-None

connectd: avoid use-after-free on reconnect with remote_addr.

---

lightningd/htlc_end.c

```
+11.668971802 lightningdBROKEN: backtrace: lightningd/log.c:821 (fatal_vfmt) 0x558c893c997f
+11.668978165 lightningdBROKEN: backtrace: lightningd/log.c:829 (fatal) 0x558c893c9a30
+11.668984935 lightningdBROKEN: backtrace: lightningd/htlc_end.c:87 (corrupt) 0x558c893b9b7d
+11.668991262 lightningdBROKEN: backtrace: lightningd/htlc_end.c:205 (htlc_out_check) 0x558c893ba352
+11.669016705 lightningdBROKEN: backtrace: lightningd/peer_htlcs.c:1471 (check_already_failed) 0x558c893ea9c9
+11.669023345 lightningdBROKEN: backtrace: lightningd/peer_htlcs.c:1575 (onchain_failed_our_htlc) 0x558c893eb098
+11.669043122 lightningdBROKEN: backtrace: lightningd/onchain_control.c:438 (handle_onchain_htlc_timeout) 0x558c893cd6ec
+11.669049818 lightningdBROKEN: backtrace: lightningd/onchain_control.c:548 …
```

lightningd: fix overzealous check in htlc_out_check:

---

CHANGELOG.md
common/gossip_store.c
common/gossip_store.h
connectd/connectd.c
connectd/connectd.h
connectd/connectd_wire.csv
connectd/multiplex.c
gossipd/gossip_generation.c
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-check_node_announcement.c
gossipd/test/run-crc32_of_update.c
lightningd/connect_control.c
tests/test_gossip.py

The #5196 issue had me look harder at the propagation improvements, and doing some real life testing.
This is a larger PR than I would have liked, but the previous propagation "improvements" were woefully under tested.  That's my fault, as I figured they couldn't make things worse (true, but they didn't make things better either!).

connectd: fix and further enhance our own gossip promotion

---

cln-rpc/src/model.rs
contrib/msggen/msggen/rust.py

This commit fixes a bug in a function `gen_enum`, which
is not caught because so far we have no non-required field in enums
defined in json schema.
Changelog-None

cln-grpc: Fix minor bug in rust client generator.

---

contrib/reprobuild/Dockerfile.bionic
contrib/reprobuild/Dockerfile.jammy
doc/REPRODUCIBLE.md
tools/repro-build.sh

This should fix the reprobuilds for v0.11.0.1. Due to us not being able to move the tag, we need to use the new reprobuild images with the tag checked out:
- Check out this PR's head
- Follow the instructions in `doc/REPRODUCIBLE.md` to create the base and builder images, but stop before the section `Building using the builder image`
- Check out tag `v0.11.0.1`
- Now call the two repro builds: `sudo docker run --rm -v $(pwd):/repo -ti cl-repro-bionic` and `sudo docker run --rm -v $(pwd):/repo -ti cl-repro-focal` (the config for `jammy` was added in this PR, but is not available in the tarball yet, so attempting to build it will yield an `Unsupported OS` error)
My hashes are these:
```
9dbc98c20df37eee6d7ae6ea8b5feedb51d69b3a62028a309ddd3c67aa70d476 …
```

Reproducibility fixes for v0.11.0

---

contrib/pyln-client/.gitignore
contrib/pyln-client/Makefile
contrib/pyln-client/pyproject.toml
contrib/pyln-proto/.gitignore
contrib/pyln-proto/Makefile
contrib/pyln-proto/pyproject.toml
contrib/pyln-testing/.gitignore
contrib/pyln-testing/Makefile
contrib/pyln-testing/pyproject.toml

`poetry` does handle a couple of things better, but we needed to adjust the makefile targets to use it too.
Changelog-None

pyln: Update the makefile to use poetry for publishing

---

configure

I noticed that the help for each configure option was a little out of sync at the bottom and there was no help text for `--enable/disable-fuzzing`. Not sure on the exact language I should use, because I don't know what fuzzing is in this context.
Changelog-None

Slight problem with `./configure help`

---

external/Makefile

Really fixes https://github.com/ElementsProject/lightning/pull/5225
We can't run refresh-submodules without a working git, either:
```
$ sudo make install
mkdir -p /usr/local/bin
mkdir -p /usr/local/libexec/c-lightning
mkdir -p /usr/local/libexec/c-lightning/plugins
mkdir -p /usr/local/share/man/man1
mkdir -p /usr/local/share/man/man5
mkdir -p /usr/local/share/man/man7
mkdir -p /usr/local/share/man/man8
mkdir -p /usr/local/share/doc/c-lightning
fatal: unsafe repository ('/home/rusty/lightning' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /home/rusty/lightning
Reinitializing submodules external/libsodium external/libwally-core external/gheap external/jsmn external/libbacktrace external/lnprototest ...
fatal: unsafe …
```

external/Makefile: fix `submodcheck` for sudo make install and modern git

---

tests/test_connection.py

test_connection.py::test_websocket was failing due to the advertisement of an ipv6 address by the peer. test_websocket now validates the websocket address irrespective of additional addresses.

pytest: websocket test can tolerate ipv6 address

---

contrib/msggen/examples/generator_example.py
contrib/msggen/msggen/__main__.py
contrib/msggen/msggen/gen/__init__.py
contrib/msggen/msggen/gen/generator.py
contrib/msggen/msggen/gen/grpc.py
contrib/msggen/msggen/gen/rust.py
contrib/msggen/msggen/utils/__init__.py
contrib/msggen/msggen/utils/utils.py

This abstraction was easy beceuse @cdecker make a great work
So, when mssgen will be released like a library, the user can create their own generator that extends IGenerator, and put it inside the following configuration
```
def gen_dotnet(generator_chain: GeneratorChain):
fname = "<your path>"
dest = open(fname, "w")
generator_chain.add_generator(DotnetGenerator(dest))
if __name__ == "__main__":
service = load_jsonrpc_service(schema_dir="<json schema path>")
generator_chain = GeneratorChain()
gen_dotnet(generator_chain, meta)
generator_chain.generate(service)
```
Pro:
- We don't need to trust the user to push code that works in the own repository, but now the user can generate and test the code in the repository that depended on the model that is generated;
- The user can export this …

msggen: introduce chain of responsibility pattern to make `msggen` extensible

---

.github/CODEOWNERS

Github was complaining about the CODEOWNERS file, since it seems @wythe is no longer active, or able to see the repository? I took the opportunity of refining my own ownership, which means I should get added as an automatic reviewer for the paths that I am responsible for.

gh: Update codeowners

---

devtools/.gitignore

I start to noded this binary generated during the build process and maybe this can be excluded!

ignore generic binary from github tree

---

CHANGELOG.md
connectd/connectd.c
connectd/connectd.h

We had multiple reports of channels being unilaterally closed because
it seemed like the peer was sending old revocation numbers.
Turns out, it was actually old reestablish messages!  When we have a
reconnection, we would put the new connection aside, and tell lightningd
to close the current connection: when it did, we would restart
processing of the initial reconnection.
However, we could end up with *multiple* "reconnecting" connections,
while waiting for an existing connection to close.  Though the
connections were long gone, there could still be messages queued
(particularly the channel_reestablish message, which comes early on).
Eventually, a normal reconnection would cause us to process one of
these reconnecting connections, and channeld would see the (perhaps
very old!) messages, …

connectd: fix accidental handling of old reconnections.

---

doc/lightning-listfunds.7.md
doc/schemas/listfunds.schema.json

Restore description of `"reserved"` field for `listfunds`

---

.github/scripts/build.sh
Makefile
doc/HACKING.md

Wasn't clear to me where things were being searched for, or how to re-do regeneration from the text there.
Second commit probably breaks something in github actions, but I felt by default picking the name most new checkouts would use is best? Could be dropped.

update bolt spec regeneration text

---

Dockerfile

This fixes #5276 
I've tested the upgrade with plugins that requires GLIBC 2.29+ when compiled with Rust and it works, shall I test something more for this PR?
This is is my first contribution here, guidance is very welcome

Fixes #5276 by using debian bullseye instead of buster

---

common/route.c
plugins/topology.c

I found these while working on `zeroconf` and took me a while to track down:
- We were considering the maximum number of HTLCs on the wrong direction, i.e. we were trying to go from A->B but were considering B->A. This is usually not an issue as long as we have `channel_update`s from both endpoints, but if that's not the case we'd be unable to use either direction (if A->B is missing/disabled we'd discard the channel right away, if B->A is missing we'd consider the channel, but then read that the maximum number of HTLCs is 0, thus indirectly discarding it too)
- We were requiring both directions to be enabled, likely as a shorthand for a node dying and only the peer disabling their direction. This is unnecessary as a dying node would get isolated by all of its peers, thus we couldn't …

Fix two small topology issues

---

doc/lightning-plugin.7.md
lightningd/plugin_control.c

When starting a plugin, if the plugin path cannot be found in
absolute context, assume it is a relative path to the default
plugins dir. As a result, the following now works when my_plugin.py
is installed in the default plugins dir:
lightning-cli plugin start my_plugin.py
Changelog-Added: plugin start RPC subcommand now assumes relative path to default plugins dir if the path is not found in absolute context. i.e. lightning-cli plugin start my_plugin.py
modified:   plugin_control.c

lightning-cli plugin start - Assume default relative path

---

contrib/startup_regtest.sh

Also fix an occasional quirk of bitcoin-cli where you have to call loadwallet

devtools: Add fund_nodes command to startup_regtest.sh

---

common/wireaddr.c
common/wireaddr.h
connectd/connectd.c
connectd/peer_exchange_initmsg.c
doc/lightning-listpeers.7.md
doc/schemas/listpeers.schema.json
gossipd/gossip_generation.c
lightningd/peer_control.c
lightningd/peer_control.h
tests/test_connection.py
tests/test_plugin.py

Now that the feature is out in the wild, I see several improvements that can be made:

Polish feature remote_addr  

---

doc/PLUGINS.md
lightningd/peer_htlcs.c

I believe this is necessary for low-level stuff that deals with MPP, for example, although I am not entirely sure.

Expose htlc id to `htlc_accepted` hook

---

doc/PLUGINS.md

Adds some warning/documentation about the `println!`/`dbg!` causing my bad times as a plugin developer.  =)

Warning added to PLUGIN documentation re: `stdin`

---

lightningd/log.c
lightningd/options.c
tests/test_misc.py

This PR solves an issue that appears when building cln as a nix derivation with the "--enable-developer" config flag set. In this case the build crashes with the following error:
```
In file included from /nix/store/bd9k3zwm0b3p8k3qw0nlk71vzfa5hn8n-glibc-2.34-115-dev/include/string.h:519,
from ccan/ccan/str/str.h:5,
from ccan/ccan/tal/tal.h:8,
from ccan/ccan/io/io.h:4,
from lightningd/log.c:3:
In function 'strncpy',
inlined from 'show_log_prefix' at lightningd/log.c:617:2:
/nix/store/bd9k3zwm0b3p8k3qw0nlk71vzfa5hn8n-glibc-2.34-115-dev/include/bits/string_fortified.h:95:10: error: '__builtin_strncpy' specified bound 80 equals destination size [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-truncation-Werror=stringop-truncation8;;]
95 |   return …
```

Fix broken length on show_log_prefix

---

plugins/src/lib.rs
plugins/src/messages.rs

`cln-plugin` throws away the "configuration" field from the "init" message.

cln-plugin: Save "configuration" from "init" method

---

doc/TOR.md

The message was
[warn] CookieAuthFileGroupReadable is set, but will have no effect: you must specify an explicit CookieAuthFile to have it group-readable.
Changelog-None

doc: Tor needs CookieAuthFile set

---

lightningd/peer_control.c

This is being hit: it's possible if connectd and lightningd get desynchronized,
and we'll handle this later when peer is activated.
Fixes: #5337 
Changelog-None

lightningd: remove overzealous assertion.

---

common/gossip_store.c
gossipd/gossip_store.c

@whitslack complained of large CPU usage by connectd at startup;
I ran perf record on connectd on my machine (which sees a little spike, only)
and I see the cost of reading and discarding the entries:
```
-   95.52%     5.24%  lightning_conne  lightning_connectd  [.] gossip_store_next
- 90.28% gossip_store_next 
+ 40.27% tal_alloc_arr_ 
+ 22.78% tal_free
+ 11.74% crc32c
+ 9.32% fromwire_peektype
+ 4.10% __libc_pread64 (inlined)
1.70% be32_to_cpu
```
Much of this is caused by the search for our own gossip: keeping this separately
would be even better, but this fix is minimal.

common/gossip_store: optimize case where entries are filtered out.

---

lightningd/signmessage.c
tests/test_misc.py

This PR improves the UX of the RPC command when `zbase` is not a valid one because we have a crash on bad `zbase`!
Fixes https://github.com/ElementsProject/lightning/issues/5293

signmessage: improve the UX of the rpc command when zbase is not a valid one

---

CHANGELOG.md
connectd/connectd.c

This is based on v0.11.1 (first three commits), and consists entirely of commits cherry-picked from master (and pending PRs), and will be committed to its own branch after review and testing.

Release 0.11.2

---

common/peer_failed.c

Prior to 0.11.0 we had cases where we would treat errors
as warnings: regretfully, this is still needed.  This message
in particular has been widely reported, and it now causes
channel force closes.
Downgrade and log.  I did insert some snarky log message earlier,
but hey, I'm sure CLN has done worse things to our peers!
Fixes: #5102 
Changelog-None: Changelog is updated in v0.11.2 branch, which will be merged after that is released.

common: downgrade "internal error" errors from lnd.

---

contrib/pyln-client/pyproject.toml
contrib/pyln-proto/pyproject.toml
contrib/pyln-testing/pyproject.toml

So this was quite a journey:
- We want relative depdendencies (using the `path` argument) whenever
developing locally. Otherwise we would have to install each
dependency every time we change a single character, which
undoubtedly would cause us to waste time trying to debug an issue
just because we forgot to install.
- When publishing however we want to rely on the version number,
since the repo context gets lost upon publishing, and path
dependencies cause failures.
The solution then it seems is to use `dev-dependencies` (not that
surprising once you find it) with relative paths, so that `poetry
install` uses these over the normal dependencies (no idea how they
dedup them) and use `dependencies` when publishing. The paths are
still in there when publishing, but `pip install` ignores them. …

pyln: Fix relative path dependencies when publishing to PyPI

---

connectd/connectd.c

The crash below from @zerofeerouting left me confused.  The invalid
value in fmt_wireaddr_internal is a telltale sign of use-after-free.
This backtrace shows us destroying the conn *twice*: what's happening?
Well, tal carefully protects against destroying twice: it's not that
unusual to free something in a destructor which has already been freed.
So this indicates that there are *two* io_conn hanging off one
struct connecting, which isn't supposed to happen!  We deliberately
call try_connect_one_addr() initially, then inside the io_conn destructor.
But due to races in connectd vs lightningd connection state, we added
a fix which allows a connect command to sit around while the peer is
cleaning up (6cc9f37cab26a01bcc93ccda2fcc048a55e869a1) and get fired
off when it's done.
But what if, in …

connectd: don't start connecting in parallel in peer_conn_closed.

---

connectd/connectd.c
connectd/connectd.h
connectd/peer_exchange_initmsg.c
lightningd/peer_control.c

`peer_reconnected` was freeing a `struct peer_reconnected` instance while a pointer to that instance was registered to be passed as an argument to the `retry_peer_connected` callback function. This caused a use-after-free crash when `retry_peer_connected` attempted to reparent the instance to the temporary context.
Instead, never have `peer_reconnected` free a `struct peer_reconnected` instance, and only ever allow such an instance to be freed after the `retry_peer_connected` callback has finished with it. To ensure that the instance is freed even if the connection is closed before the callback can be invoked, parent the instance to the connection rather than to the daemon.
Absent the need to free `struct peer_reconnected` instances outside of the `retry_peer_connected` callback, there is …

connectd: avoid use-after-free upon multiple reconnections by a peer

---

cln-grpc/README.md

Some users might be unaware of `cln-grpc`, which leads to hacky setups and fragmentation. This PR mostly contains the relevant parts of @cdecker [post on Medium](https://medium.com/blockstream/core-lightning-v0-11-0-channel-multiplexing-a-new-api-and-much-more-5d34df8cfeb5), which explains the reasons for adding this API and that it's going to be officially maintained moving forward.
It would also be nice to add a link to this page from the main `README.md`

doc: cln-grpc

---

.github/workflows/ci.yaml
contrib/pyln-testing/pyln/testing/utils.py

Build on top of https://github.com/ElementsProject/lightning/pull/5359
Ok this should fixes the following stack trace
```
2022-06-29T14:19:41.183Z DEBUG   lightningd: Command returned result after jcon close
------------------------------- Valgrind errors --------------------------------
Valgrind error file: valgrind-errors.55581
==55581== Syscall param statx(file_name) points to unaddressable byte(s)
==55581==    at 0x4B0188E: statx (statx.c:29)
==55581==    by 0x1133481: std::sys::unix::fs::try_statx (weak.rs:178)
==55581==    by 0x11265E0: std::fs::buffer_capacity_required (fs.rs:851)
==55581==    by 0x112675B: <std::fs::File as std::io::Read>::read_to_string (fs.rs:644)
==55581==    by 0x10DACA8: num_cpus::linux::Cgroup::param (linux.rs:214)
==55581==    by 0x10DAB39: …
```

valgrind: ignore plugin built with rust

---

doc/lightning-listconfigs.7

This seems to have been missed by a recent PR.
Changelog-None

doc: Fix generated `listconfigs` man-page

---

lightningd/peer_control.c

Check funding_outnum validity first to avoid reading invalid outputs.
Changelog-Fixed: Fixed a potential issue if the number of outputs decreases in a dualopen RBF or splice.

peer_control: Fix check_funding_details assert

---

lightningd/dual_open_control.c
tests/test_connection.py

Build on top of https://github.com/ElementsProject/lightning/pull/5367
The @niftynei patch finally fixed the lnprototest failure https://github.com/rustyrussell/lnprototest/issues/31 and with the stress test that I added on lnprototest CI that ran lnprototest 20 times, I found another strange failure  https://github.com/rustyrussell/lnprototest/issues/56 that I'm no longer able to reproduce, so I added a couple of logging call.
In addition, I enable the CI lnprototest that run the test 2 time, in this way we can try to find the bug before we fall into the lucky case forever. if we fall in the lucky case 2 time? well, we are lucky no?
let's see what the full CI tells us now, and if we finally have the CI clean!
Fixes https://github.com/ElementsProject/lightning/issues/5148

lnprototest: updating and patch lnprototest

---

connectd/connectd.c
connectd/connectd.h
connectd/multiplex.c
tests/test_connection.py
tests/test_gossip.py

Got complaints about us hanging up on some nodes because they don't respond
to pings in a timely manner (e.g. ACINQ?).  This only matters to us if no
other traffic is flowing, so mitigate that.
This may solve the problem because we've previously seen implementations
badly prioritize gossip traffic, and thus important messages can get queued
behind gossip dumps!

connectd: don't insist on ping replies when other traffic is flowing.

---

lightningd/closing_control.c
lightningd/peer_control.c
lightningd/peer_control.h

libwally asserts() when trying to calculate the txid: we report it as
invalid elsewhere, but then crash:
```
May 19 20:37:03 c-lightning lightningd[26236]: 2022-05-19T20:37:03.689Z DEBUG   lightningd: close_command: timeout = 1
May 19 20:37:04 c-lightning lightningd[26236]: 2022-05-19T20:37:04.689Z UNUSUAL 037f32400c108f8385db94371bfcef08948bc0042069c1ef6f39086cdf23420ee5-chan#91: Peer permanent failure in CHANNELD_SHUTTING_DOWN: Forcibly closed by `close` command timeout
May 19 20:37:04 c-lightning lightningd[26236]: 2022-05-19T20:37:04.689Z **BROKEN** 037f32400c108f8385db94371bfcef08948bc0042069c1ef6f39086cdf23420ee5-chan#91: Cannot broadcast our commitment tx: it's invalid! (ancient channel?)
May 19 20:37:04 c-lightning lightningd[26236]: lightningd: bitcoin/tx.c:485: wally_txid: …
```

lightningd: fix close of ancient all-dust channel.

---

lightningd/chaintopology.c

We noticed bogus behavior where (with 200 blocks added at once)
lightningd didn't see a DF channel open: this is because we told
lightningd about the new blocks (and it timed out channel) before
the watches for the transaction are fired.

lightningd: fire watches on blocks before telling lightningd.

---

doc/PLUGINS.md
doc/lightning-listconfigs.7
doc/lightning-listconfigs.7.md
doc/lightning-plugin.7.md
doc/schemas/plugin.schema.json
lightningd/options.c
lightningd/plugin.c
lightningd/plugin_control.c
tests/plugins/options.py
tests/test_plugin.py

Some issues I came across looking at #5294 (that discussion is ongoing, this PR adds some context)
Converts `plugin->cmd` to a full path immediately (couldn't find a reason not to), ensures only one instance can run.
Plugin command line options should have unique names (and no aliases).
Update plugin documentation.
**edit** ~Last 2~ [8be7693](https://github.com/ElementsProject/lightning/pull/5343/commits/8be769345a6b3b869022bcb7ae3cd107ffb162d5) and  [cf2dbbb](https://github.com/ElementsProject/lightning/pull/5343/commits/cf2dbbbe6a71b6a383f5126778e74bd915443641) ~commits is an idea for plugins that do configs internally, not fully worked out.~
**edit** Add "dynamic" field to `plugin list` result, some builtin plugins are dynamic !

plugins: unique command line options, small fixes and plugin documentation

---

Makefile
configure
external/.gitignore

The M1 Macs support both x86_64 and arm64 architectures, which forced
homebrew to use a different path for its storage (`/opt/homebrew/`
instead of `/usr/local`). If we don't adjust the path we'd mix x86_64
and arm64 libraries which can lead to weird compiler and linker
errors.
This patch just introduces `CPATH` and `LIBRARY_PATH` as suggested by
the homebrew team, and detects the current architecture automatically.
Changelog-Added: macos: Added m1 architecture support for macos

make: Add macos M1 support

---

doc/lightning-listforwards.7.md
doc/schemas/listforwards.schema.json
lightningd/peer_htlcs.c
tests/test_pay.py
wallet/wallet.c

There are more cases where we can populate out_channel; we definitely need to fix the case where we failed locally because the outgoing channel didn't have capacity, but we should also try anywhere that they gave us a channel to fwd to, even if it doesn't exist, for example.

listforwards localfail out_channel

---

connectd/multiplex.c
tests/test_gossip.py

his is a side-effect of fixing aging: sometimes, we age our rcvd_filter cache too fast, and thus re-xmit.  This breaks our test, since it used dev-disconnect on the channel_announce, but that closes to l3, not l1!
```
>       assert l1.rpc.listchannels()['channels'] == []
E       AssertionError: assert [{'active': T...ags': 1, ...}] == []
E         Left contains 2 more items, first extra item: {'active': True, 'amount_msat': 100000000msat, 'base_fee_millisatoshi': 1, 'channel_flags': 0, ...}
```
Fix this flushing properly, remove previous workaround in another test.    
Fixes: #5403

pytest: fix test_gossip_no_empty_announcements flake.

---

common/param.c
common/param.h
lightningd/pay.c
tests/test_pay.py

Changelog-None: regression during this release cycle

Allow old "msatoshi" as well as "amount_msat" in sendpay route

---

gossipd/routing.c

Node announcement indices reinitialized after deleting the referenced announcement.  Debugging output also corrected.
Fixes this crash in CI:
FAILED tests/test_closing.py::test_closing_specified_destination - Connection...
DEBUG   gossipd: Deleting channel 107x1x0 due to the funding outpoint being spent
**BROKEN** gossipd: gossip_store: get delete entry offset 4291/5445 (version ddf8fbd-modded)
**BROKEN** gossipd: backtrace: common/daemon.c:38 (send_backtrace) 0x56405b5da570
**BROKEN** gossipd: backtrace: common/status.c:221 (status_failed) 0x56405b5e5f9d
**BROKEN** gossipd: backtrace: gossipd/gossip_store.c:703 (gossip_store_get) 0x56405b5c857c
**BROKEN** gossipd: backtrace: gossipd/gossip_store.c:635 (delete_by_index) 0x56405b5c8285
**BROKEN** gossipd: backtrace: …

gossipd: fix of gossip v10 channel removal handling

---

lightningd/lightningd.c
lightningd/peer_control.c
lightningd/peer_control.h
lightningd/test/run-find_my_abspath.c
tests/test_closing.py

In diagnosing a users' issue, I noted we didn't try to rexmit transactions on startup.  Bitcoind is usually really good at keeping transactions around, but we should not count on it.

Fix awaiting unilateral rexmit

---

lightningd/opening_control.c
tests/test_plugin.py

Previously we wouldn't notify when a channel moves into state
"CHANNELD_AWAITING_LOCKIN", as this is the original state (so there's
no movement btw states). This meant that it's impossible to track when a
channel's commitment txs have been exchanged and we're waiting for
onchain confirmation.
It's useful to have notice of this initialization though, all in one
place so that the `channel_state_changed` notification can successfully
track the entire lifecycle of a channel, from inception to close.
Note that for v2 "dual-funded" channels, we already notify at the same place, at
"DUALOPEND_AWAITING_LOCKIN" (the initial state for a dualopend channel
is "DUALOPEND_OPEN_INIT" -- this is the only state we don't get notified
at now...)
Changelog-Added: Plugins: `channel_state_changed` now triggers …

notify: `channel_state_changed` now receives notice when channel opens

---

lightningd/plugin.c

During the debugging of a summer of the bitcoin project with @swaptr, core lightning lies in the error message when receiving a notification with an invalid JSON, it tells that the object did not contains the `jsonrpc` filed, but if I send a string with a valid json inside like `"{valid json rpc 2.0 notification}"` cln should tell us that we are sending somethings that it is not a json object
Having a better error message can speed up the debugging process, and from our point of view it is just an `if`
Still thinking about how to make a test for this, any suggestions?

plugin: add check on the type json object during the IO message handling

---

onchaind/onchaind.c
tests/test_closing.py

Fix flake fail from race on coin-movement reporting for htlc_timeout transactions (external)

flake htlc_tx timeout

---

contrib/pyln-testing/pyln/testing/fixtures.py
plugins/autoclean.c
tests/test_invoices.py

Plugin `autoclean` crashes with below backtrace after disable and re-enable.
Strangely I mostly reproduces with the sequence disable-enable-disable-sleep-enable, see added test.
Also modifies `pyln-testing` to add stderr `errlog` (with backtrace etc.) to CI report after unexpected test failure.
I have the fix, but I am just curious if below backtrace shows up in the test results.
```
autoclean: FATAL SIGNAL 6 (version v0.11.0.1-240-gbd239d2)
0x55a26e53adf4 send_backtrace
0x55a26e53ae9a crashdump
common/daemon.c:46
0x7fed8b8d783f ???
/build/glibc-fWwxX8/glibc-2.28/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7fed8b8d77bb __GI_raise
../sysdeps/unix/sysv/linux/raise.c:51
0x7fed8b8c2534 __GI_abort
/build/glibc-fWwxX8/glibc-2.28/stdlib/abort.c:79
0x55a26e57a98c …
```

plugin: autoclean fix crash + pyln-testing: print stderr from errlog

---

lightningd/options.c
tests/test_gossip.py

Currently when we announce a DNS address without specifying the port, lightningd will announce it with port 0, which is invalid.
EXPERIMENTAL builds with DNS announcement
This will fix set it to the corresponding network port.

fix: dns announcement without port

---

lightningd/peer_control.c

It's available in listpeers() if you want to see it, otherwise it's not
really something users want to see in the normal course of operation.
Changelog-None

lightningd: reduce log level for remote address reporting.

---

contrib/startup_regtest.sh

Here are a few additions to `startup_regtest.sh` to make it easier to connect nodes via a new `connect` command.
Also add `experimental-offers` to the node configs for testing offers.

startup_regtest.sh: add connect helper and experimental-offers

---

cln-grpc/proto/node.proto
cln-grpc/src/convert.rs
cln-rpc/src/model.rs
common/jsonrpc_errors.h
doc/lightning-checkmessage.7.md
doc/schemas/checkmessage.schema.json
lightningd/signmessage.c
tests/test_misc.py

Returning a warning message when the pub key is not specified and there is no node in the graph.
We try to help people that use core lightning as a signer and nothing else.
Fixes https://github.com/ElementsProject/lightning/issues/5247
Changelog-Added: rpc: checkmessage return an warning msg when no node is found in the graph and no pubkey is provided.

rpc: checkmessage return an error is the pubkey is not found in the graph

---

contrib/pyln-testing/pyln/testing/utils.py
plugins/commando.c
plugins/libplugin.c
tests/test_db.py
tests/test_gossip.py
tests/test_misc.py
tests/test_plugin.py
tests/test_wallet.py

The callbacks-after-command-completed can particularly happen with commando:
```
commando: FATAL SIGNAL 11 (version 06b36d3)
0x55609e953d51 send_backtrace
0x55609e953dfb crashdump
common/daemon.c:46
0x7f665e3b908f ???
/build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x55609e9387a3 send_more_cmd
plugins/commando.c:632
0x55609e93b270 handle_rpc_reply
plugins/libplugin.c:669
0x55609e93bd50 rpc_read_response_one
plugins/libplugin.c:842
0x55609e93be86 rpc_conn_read_response
plugins/libplugin.c:862
0x55609e9f4f68 next_plan
ccan/ccan/io/io.c:59
0x55609e9f5b70 do_plan
ccan/ccan/io/io.c:407
0x55609e9f5bb2 io_ready
ccan/ccan/io/io.c:417
0x55609e9f7ea5 io_loop
ccan/ccan/io/poll.c:453
0x55609e93eb20 plugin_main
plugins/libplugin.c:1676 …
```

libplugin: don't call callbacks if cmd completed before response, and fix another commando crash

---

doc/lightning-hsmtool.8.md
tests/test_wallet.py
tools/hsmtool.c

This gives a nice way to ensure your secret is the correct one.
Also, we don't need to suppress VALGRIND for this test, now the output
races are fixed.
Changelog-Added: `hsmtool`: new command `checkhsm` to check BIP39 passphrase against hsm_secret.

hsmtool: implement checkhsm.

---

tests/test_opening.py

pay failed (non-DEVELOPER) because one node didn't see blocks in time:
```
inv = l3.rpc.invoice(42 * 10**6, 'inv1', 'desc')['bolt11']
>       l1.rpc.pay(inv)
tests/test_opening.py:1394:
...
>           raise RpcError(method, payload, resp['error'])
E           pyln.client.lightning.RpcError: RPC call failed: method: pay, payload: {'bolt11': 'lnbcrt420u1p3dnwv7sp5qnquuwndgz35ywfg3p3dtu07ywmju78r8s0379eaxjxkv5d8jueqpp5kmaxgsye02dzmdlkqkedqvrh2evdl45sz7njrm5dff42dvp4v5qsdq8v3jhxccxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4n0wkf0y9gwfwhgqqqqqpqqqqqzsqqc9qyysgqad2x2zv0axa3hrfz7nurw4plvspvxlld9wtcg3xxjyxqlzm773a4fkyl09gs8uskj4m7len8r4pf4rh7v9snh3grrpawhk9qsd7vwmcqa9rgxg'}, error: {'code': 210, 'message': 'Ran out of routes to try after 176 attempts: see `paystatus`', …
```

pytest: fix flake in test_zeroconf_forward

---

contrib/startup_regtest.sh
plugins/pay.c
plugins/spender/multifundchannel.c

`listpays` was missing the updated "no strings in msat responses" cleanup, since we were using `json_add_str` there instead of an msat helper.
Also went ahead and updated the `startup_regtest` to turn off deprecated apis and updated a now deprecated option for the `funder` plugin that it loads for dev builds.
Changelog-None

msat string miss

---

tests/test_connection.py

`l1` got their tx in before `l2`, but we're waiting for `l2`'s
commitment tx. (l2 sends an error message to l1 when we call dev-fail,
l1 broadcasts their commitment tx when they get the error)
Instead, we let l1 send their commitment tx, except we blackhole it.
```
l2.rpc.dev_fail(l1.info['id'])
l2.daemon.wait_for_log('Failing due to dev-fail command')
>       l2.wait_for_channel_onchain(l1.info['id'])
tests/test_connection.py:2275:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
contrib/pyln-testing/pyln/testing/utils.py:1043: in wait_for_channel_onchain
wait_for(lambda: txid inself.bitcoin.rpc.getrawmempool())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
success = <function …
```

test-flake: dont let `l1` send their unilateral tx

---

lightningd/connect_control.c
lightningd/connect_control.h
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
tests/test_misc.py

I was getting consistent test failures for these when looking at the `bookkeeper` test fails; mostly these were timing bugs!

test timing fixes/stderr redirect 

---

lightningd/log.c

The one to stderr is fine, the log one gets corrupted, like so:
```
2022-07-24T07:20:08.6250702Z lightningd-2 2022-07-24T06:49:19.494Z **BROKEN** lightningd: Plugin '????UH??SH??8H?}?H?u?H?U?H?M?H?M?H?E?H?????' returned an invalid response to the db_write hook: (F???U
```
Changelog-None

lightningd: fix fatal() log message in log.

---

doc/lightning-decode.7.md
doc/schemas/decode.schema.json
plugins/offers.c
tests/test_plugin.py

If rune contains invalid UTF-8, offers (which implements decode) would
produce JSON with invalid UTF-8, which causes lightningd to complain
and kill it, and then die because it's an important plugin.
So don't decode invalid UTF-8!
Reported-by: @jb55
Changelog-None: introduced in this release.

decode: fix crash when decoding invalid rune.

---

connectd/connectd.c

Don't log_io final messages twice (multiplex_final_message already does
this, so it's confusing to see us send e.g. WIRE_ERROR twice!).
And report that the peer has failed to connect out *before* telling
lightningd, otherwise we get a very confusing ordering, e.g.:
```
2022-07-23T05:17:36.096Z DEBUG   027d0de66d08f956a8d606c0d1c34e59bda38c05a3b1cc738fdd6378716c644997-lightningd: Reconnecting in 4 seconds
2022-07-23T05:17:36.096Z DEBUG   027d0de66d08f956a8d606c0d1c34e59bda38c05a3b1cc738fdd6378716c644997-lightningd: Will try reconnect in 4 seconds
2022-07-23T05:17:36.096Z DEBUG   027d0de66d08f956a8d606c0d1c34e59bda38c05a3b1cc738fdd6378716c644997-connectd: Failed connected out:
```
Changelog-None

connectd: two logging cleanups.

---

lightningd/plugin.c
plugins/commando.c
tests/fixtures.py
tests/test_connection.py
tests/test_plugin.py

Turns out python plugins saw the string "null" as their options if there was no default value.  Best to fix this in core, and ship in 0.12.
I appended two commando fixes which I found while testing this locally...

Fix default args, fix flake

---

contrib/msggen/msggen/__main__.py

This was causing issues when multiple instances of msggen were running
in parallel on CI.
Changelog-None

msggen: Use tempfile + rename to make changes to .msggen.json atomic

---

common/wireaddr.c
lightningd/options.c
plugins/libplugin.c
tests/test_misc.py

Valgrind was choking on some things while running tests locally for the `bookkeeper`; this fixes those up.
Also speeds up a test's reconnect, which would flake locally when TIMEOUT is set low.

Test flakes?? (works for me)

---

plugins/spender/openchannel.c
tests/test_connection.py
tests/test_opening.py

The `funder_contribution_limits` test hang is kind of interesting -- I was assuming that the RPC response to openchannel_update would always beat the notification of tx_signatures arriving since the spec says they MUST always arrive one after the other (and in fact the code doesn't work if they get called out of order). In rare cases however the notification arrives before the RPC response, which causes the hang we've been seeing.
Really easy to fix, but kind of interesting!
The other flake has to do with how fast the connection drops -- if it drops too fast we get an RPC error; otherwise the RPC returns correctly. We don't really care if the RPC works we just need to call it.
"needing to call this RPC no matter if it returns ok or not" has a bit of a smell; I'm planning to do some work …

v2 opens and funder flakes

---

doc/lightning-decode.7.md

It's weird that readthedocs.io drops the ".md" suffix though;
let's see if this fixes it.
Changelog-None
Fixes: #5462

doc: fix bolt 12 link (it's not in master), update bolt 11 to new "bolts" repo

---

doc/lightning-commando-rune.7.md
doc/schemas/commando-rune.schema.json
plugins/commando.c

Changelog-Added: Show warning when creating runes with no restrictions

commando-rune: show warning when creating runes with no restrictions

---

plugins/bkpr/test/run-bkpr_db.c
plugins/bkpr/test/run-recorder.c

We rely on sqlite3 being present to run unit tests for some bookkeeper
tests; here we effectively disable these tests if not available
Fixes report in #4928
Reported-By: @whitslack

bkpr: make unit tests not fail if !HAVE_SQLITE3

---

lightningd/dual_open_control.c
lightningd/notification.c
lightningd/notification.h
lightningd/opening_control.c

Previously, "funding_locked" was always "true"!
(It's actually been wrong since its introduction in v0.7.3!)
Changelog-Fixed: Plugins: `channel_opened` notification `funding_locked` field is now accurate: was always `true`.

lightningd: fix funding_locked in channel_opened notification.

---

plugins/libplugin-pay.c

If we retry a getroute call we could end up losing track of a prior route. This could happen if we were unable to apply the channel hints due to insufficient balance or number of HTLCs.

pay: Fix a memory leak when retrying getroute

---

doc/INSTALL.md

This will clarify the different ways to build core lightning, and also we speed up the core lightning building process for the people that want just to install cln.
The procedure is already tested by my docker image on alpine is available [here](https://github.com/clightning4j/clightning4j-node/runs/7356637044?check_suite_focus=true)
Just thinking also to add how to disable rust if the user does not want to compile the plugin.

docs: clarify the different way to build cln

---

plugins/pay.c

We were completing unrelated `pay` calls due to:
- Not identifying suspended calls correctly when completing the original `pay` call
- Iterating over a list while modifying it at the same time
Also fixed a small use-after-free bug.
Thanks @rustyrussell for pointing out where this might go wrong.
Fixes #5443

Prevent a crash in `pay` when calling it in close succession

---

.gitignore
doc/lightning-bkpr-listaccountevents.7.md
doc/schemas/bkpr-listaccountevents.schema.json
plugins/bkpr/account_entry.c
plugins/bkpr/account_entry.h
plugins/bkpr/bookkeeper.c
plugins/bkpr/chain_event.h
plugins/bkpr/channel_event.c
plugins/bkpr/channel_event.h
plugins/bkpr/db.c
plugins/bkpr/incomestmt.c
plugins/bkpr/recorder.c
plugins/bkpr/recorder.h
plugins/bkpr/test/run-recorder.c
tests/test_bookkeeper.py

Self-transfers should really be ignored for income reports. This change adds rebalance tracking,
which allows us to report the right thing for `listincome`.
Tracks rebalances, and report income events for them.
Previously `listincome` would report:
- invoice event, debit, outgoing channel
- invoice_fee event, debit, outgoing channel
- invoice event, credit, inbound channel
Now reports:
- rebalance_fee, debit, outgoing channel
(same value as invoice_fee above)
Note: only applies on channel events; if a rebalance falls to chain
we'll use the older style of accounting.
Changelog-None

bkpr: track channel rebalances, display in listincome

---

contrib/pyln-testing/pyln/testing/utils.py
doc/lightning-sendonion.7.md
lightningd/pay.c
tests/test_closing.py
tests/test_connection.py
tests/test_pay.py
tests/utils.py

Fixes: #5504 
@niftynei Note new Changelog entries!!

Dont ignore first scid for sendpay, sendonion

---

plugins/bkpr/bookkeeper.c
plugins/bkpr/incomestmt.c
plugins/bkpr/recorder.c
plugins/bkpr/recorder.h
plugins/bkpr/test/run-recorder.c
tests/test_bookkeeper.py
tests/test_pay.py

We weren't adding zero balance channels during "catch up starts (accounting for things missing while bookkeeper wasn't running)", which resulted in a crash/restart when any payment got routed through these channels.
Also patches a flake (which really needs a nicer fix than this line/by line patch but yolo) and removes a duplicated log statement.

bookkeeper: dont skip zero balance channels that are missing

---

hsmd/libhsmd.c
tests/test_wallet.py
wallet/walletrpc.c

If you pass in a PSBT that's invalid (no inputs/outputs for example), lightningd blows up in the HSM.
Instead, let's catch bad PSBTs before we get that far.
Also uncovered a kinda fun "double entrance" into `tal_wally` code.
Waiting for confirmation from @fiatjaf

Don't crash if the PSBT is junk

---

devtools/sql-rewrite.py
plugins/bkpr/recorder.c
plugins/bkpr/test/run-recorder.c

Keywords were added "recently" (2019) and were causing silent failures in updates on machines using older versions of sqlite3.
These patches strip the keywords out for sqlite3 (which is fine, nulls first *is* the default behavior on sqlite3, it was only problematic on postgres). 
Nicer fix would be to allow for versioning of queries depending on sqlite3 version but yolo?
Changelog-None

Strip "NULLS FIRST" from sqlite3 queries

---

lightningd/peer_htlcs.c
tests/test_opening.py

When forwarding an HTLC we're allowed to pick another channel than the one specified in the onion. We do so if using another channel is advantageous. In this case we'd have a confirmed channel and a zeroconf channel in parallel, and the latter would be picked because it is advantageous (more `spendable_msat`), and we'd try to log its `scid`. However the `scid` for a zeroconf channel is not set until it gets at least one confirmation, causing a NULL-access.

fix: Zeroconf in combination with multiple channels tries to log a non-existent scid

---

doc/lightning-invoice.7.md

The new parameter name (this version) is amount_msat: msatoshi is
deprecated.   The doc/schemas/invoice.request.json has this correct
(but we don't generate teh *usage* line from that yet!)

doc: update usage of lightning-invoice.

---

doc/lightning-staticbackup.7.md
lightningd/opening_control.c
tests/test_misc.py

Currently, If a user uses `emergencyrecover` and they already have the channels stored in the Database, it throws a UNIQUE constraint error and the node goes down. Which is horrible UX. So now, we check for every channel and skip over those which are already stored.
This completely slipped out of my mind while developing, All thanks to @niftynei for being patient with me, and reminding me about this.

Skip over saved channels while recovering from emergencyrecover

---

.github/workflows/macos.yaml

Homebrew decided to switch from pyth3.9 to python3.10, breaking our paths.
Changelog-None

ci: Fix the Mac OS build test

---

common/billboard.c

It was backwards, which made #5496 confusing.
Changelog-Fixed: `listpeers` `status` "They've sent shutdown" and "We've sent shutdown" were backwards.

channeld: correct reversed shutdown message in billboard.

---

doc/BACKUP.md

Apologies @lightningorb, I have no idea what happened to #5521, so I'm reopening the PR with this amended changeset.

docs: use 'postgres' driver (not postgresql). Include plain url to guide

---

tests/test_gossip.py

It looks like we still occasionally hit this flake. It has been difficult to reproduce, so let's dump the gossip store to aid in debugging. See issue #5410.
Changelog-None

pytest: Add debugging to test_gossip_store_compact_on_load

---

doc/INSTALL.md

The only caveat I'm aware of is the fact that `./configure` will misbehave [here](https://github.com/ElementsProject/lightning/blob/e6442d798ef24e1f868ca6003cad6e20a4d8dd5e/configure#L68) and [here](https://github.com/ElementsProject/lightning/blob/e6442d798ef24e1f868ca6003cad6e20a4d8dd5e/configure#L77) (it won't process those errors but it will conclude that `PYTEST not found` when it's in fact present). To address that, `which` can be added to the list of deps, or we can replace those `which` calls with `command -v`, which is safer since this approach is POSIX-compatible and it does exactly the same thing

Add Arch Linux build instructions

---

tests/test_plugin.py

The test fails because the closed channel is deleted by the time we
check the state change history.
It appears the test was intended to only mine 100 blocks originally,
but had an accidental copy-paste in it.

pytest: fix test_channel_state_change_history

---

plugins/bkpr/bookkeeper.c
plugins/bkpr/db.c

Merged a commit that broke everything with shadows, which turned out to
be the bookkeeper code.

build, shadows: fix broken build (no shadows)

---

contrib/pyln-client/pyln/client/lightning.py
tests/test_misc.py

This happens with deprecated-apis and listconfigs, breaking some
python plugins!
Fixes: #5546
Fixes: #5563

pyln-client: allow 'msat' fields to be 'null'

---

common/gossip_store.c

Should help diagnose https://github.com/ElementsProject/lightning/issues/5572
which hit the invalid csum on a >64MB entry, if it happens again.
Changelog-None

connectd: better diagnostics on invalid gossip_store entries.

---

doc/INSTALL.md

People who copy paste the commands might not realize this chunk is not copy paste-able.

docs: Clear up Ubutu documentation

---

.github/workflows/ci.yaml
.gitmodules
contrib/docker/Dockerfile.ubuntu
contrib/docker/scripts/setup.sh
poetry.lock
pyproject.toml

Turns out we can update to ubuntu 22.04 LTS and that fixes all the `mako` problems (for now, should def be addressed more widely for everyone that can't update). This required a bit of a detour into `hashlib` (but thankfully python-bitcoinlib had already taken care of an update for this, so we just re-use their implementation)
Also fixes up a few tiny things I found.
Points at my `lnprototest` branch, which has updates needed to make the move to 22.04 LTS work; we can update it back once that's merged (or gate this PR on that one being merged to mainline).

lnprototest build fix

---

lightningd/peer_control.c

This fixes a visual bug in `getinfo` output, which contained unannounced
auto discovered IP addresses when announcement of discovered IPs
was actually turned off.
Addresses #5553

fix: getinfo showing unannounced discovered IPs

---

connectd/connectd.c
lightningd/options.c
tests/test_gossip.py

This has been merged https://github.com/lightning/bolts/pull/911
Should we remove EXPERIMENTAL?
Changelog-Changed: DNS annoucenent support is no longer EXPERIMENTAL

chore: remove EXPERIMENTAL for DNS Bolt7

---

common/gossip_store.c

This took more effort to debug than it appears, but I believe this is ultimately the source of the gossip_store offset error!  Some of the previously reported node announcement propagation issues may have originated here as well.  Accounting for the gossip_store's leading version byte is a simple fix.

Fix for #5572 and #5565

---

lightningd/invoice.c

We can (and probably should!) allocate this off tmpctx rather than off the response.
Also, json_add_invoice doesn't actually match the normal pattern, so fix that.
```
E           ValueError: 
E           Node errors:
E           Global errors:
E            - Node /tmp/ltests-_vbj8az8/test_pay_fail_unconfirmed_channel_1/lightning-2/ has memory leaks: [
E               {
E                   "backtrace": [
E                       "ccan/ccan/tal/tal.c:442 (tal_alloc_)",
E                       "wallet/invoices.c:81 (wallet_stmt2invoice_details)",
E                       "wallet/invoices.c:697 (invoices_get_details)",
E                       "wallet/wallet.c:2946 (wallet_invoice_details)",
E                       "lightningd/invoice.c:1296 (json_add_invoices)",
E …
```

lightningd: fix spurious leak report.

---

common/gossmap.c

Apparently we had two private channel announcements (the !private assert failed).  While this shouldn't happen, don't crash because of it.
Fixes: #5578
Changelog-Fixed: Plugins: topology plugin could crash when it sees duplicate private channel announcements.

gossmap: don't crash if we see a duplicate channel_announce.

---

plugins/bcli.c

Passing a RPC password via cli argument (`-rpcpassword`) can leak auth secrets to other users on a system (at least on Linux). This PR tries to pass the RPC password through a stdin using a `-stdinrpcpass`
Refs.:
- Fixes #3984
- https://man.archlinux.org/man/bitcoin-cli.1.en
Fixes #3984

plugins/bcli: load RPC password from stdin instead of an argument

---

doc/lightning-listconfigs.7.md
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
tests/test_db.py
tests/test_misc.py
wallet/db.c

This is a good sanity check that users understand that if they upgrade
to master mid-cycle they can't go back!
Suggested-by: @wtogami
Changelog-Added: Config: `--database-upgrade=true` required if a non-release version wants to (irrevocably!) upgrade the db.

lightningd: refuse to upgrade db on non-released versions by default.

---

gossipd/gossip_generation.c
gossipd/gossipd.c
gossipd/gossipd.h
gossipd/gossipd_wire.csv
lightningd/gossip_control.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/peer_control.c
lightningd/test/run-invoice-select-inchan.c
tests/test_connection.py
wallet/test/run-wallet.c

Before this patch, getinfo shows incorrect ports on `getinfo` auto discovered IP addresses.
It also just showed (not announced) unconfirmed addresses.
Addresses #5553
Changelog-Fixed: peer_control: getinfo shows the correct port on discovered IPs

fix: peer_control getinfo to show correct port on discovered IPs

---

.github/scripts/setup.sh

Nightly occasionally breaks, so use stable instead.
Changelog-None

gci: Use stable rust instead of nightly

---

contrib/pyln-testing/pyproject.toml

While testing plugins in the community repo I found that these two are missing.
Changelog-None

pyln: Add grpcio and protobuf dependencies to pyln-testing

---

channeld/channeld.c
openingd/dualopend.c
openingd/openingd.c

1) dualopen has fd to connectd
2) channeld needs to take over
3) dualopen passes fd that leads to a connectd over for channeld to use
4) lightningd must receive the fd transfer request and process it
5) dualopen shuts down and closes everything it owns
4 & 5 end up in a race. If 5 happens before 4, channeld ends up with an invalid fd for connectd — leaving it in a position to not receive messages.
Lingering for a second makes 4 win the race. Since the daemon is closing anyway, waiting for a second should be alright.

connectd+: Flake/race fix for new channels

---

contrib/pyln-client/pyln/client/lightning.py
tests/test_misc.py

We don't really support using pyln-client with older Core Lightning versions, but this is neater anyway.  I checked: f-strings go back to python 3.6, so we can use them (I think this may be the first!).
Suggested-by: @MiWCryptAnalytics
Fixes: #5609
Changelog-None: introduced since 0.12 with chained ids

pyln-client: use f strings to concatenate JSON ids, handle older integer ids

---

doc/lightning-keysend.7.md
doc/lightning-listconfigs.7.md
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
doc/undoc-flags.json
lightningd/options.c
plugins/keysend.c
tests/test_pay.py

Sure, it's probably a JSON monstrosity, but that's not really our problem.
Also removed some experimental ifdefs: @cdecker?
Requested-by: @EvanFeenstra on Discord.

keysend text fields

---

tools/build-release.sh

We added a submod dep (lowdown) that requires config to run first.
Changelog-None

build-release: configure before submodcheck

---

cln-grpc/src/convert.rs
cln-grpc/src/pb.rs
cln-grpc/src/server.rs
cln-grpc/src/test.rs
contrib/msggen/msggen/gen/grpc.py
contrib/pyln-testing/pyln/testing/utils.py
plugins/Cargo.toml
plugins/examples/cln-plugin-startup.rs
plugins/grpc-plugin/src/main.rs
plugins/src/lib.rs
plugins/src/logging.rs

These are based on feedback and dogfooding experiences, please keep them coming :wink:

Some minor changes in the CLN crates

---

channeld/channeld.c
tests/test_connection.py

This is the minimal change to meet the desired outcome of https://github.com/lightning/bolts/issues/934
which wants to give obsolete-db nodes a chance to fix things up, before we
close the channel.
We need to dance around a bit here, since we *will* close the channel if
we receive an ERROR, so we suppress that.

channeld: send warning, not error if peer has old commitment number.

---

doc/PLUGINS.md
lightningd/channel.h
lightningd/peer_htlcs.c
tests/plugins/htlc_accepted-fwdto.py
tests/test_opening.py
tests/test_plugin.py
wallet/test/run-wallet.c

Otherwise what the hook sees is actually a lie, and if it sets it we might override it.
The side effect is that we add an explicit "forward_to" field, and allow hooks to override it.  This lets a *hook* control channel choice explicitly.
Changelod-Added: Plugins: `htlc_accepted_hook` return can specify what channel to forward htlc to.
(Interestingly, this fell out of the blinded payments work, where we can be given the peer, rather than the channel, to forward to).

lightningd: figure out optimal channel *before* forward_htlc hook, allow override

---

Cargo.lock
cln-grpc/Cargo.toml
cln-grpc/src/convert.rs
cln-grpc/src/pb.rs
cln-rpc/Cargo.toml
cln-rpc/src/lib.rs
cln-rpc/src/model.rs
cln-rpc/src/primitives.rs
contrib/msggen/msggen/gen/grpc.py
contrib/msggen/msggen/gen/rust.py

While using the rust RPC library I noticed a few unidiomatic/unergonomic API details. This PR proposes fixes to some of them that I'd like to discuss. If you think certain changes should be merged and wish to split them up that should be easily possible.
Changes:
* Implement `Error` for `RpcError` so that `?` works with `anyhow`
* Implement a "typed" version of `call` that knows which return type it expects, so users don't need to match over the entire `Response` enum
* Use `bitcoin_hashes` and `secp256k1` instead of custom implementations (that are lacking a lot of convenience methods already present in these crates)
* Implement `Debug` for the client struct
* Make more types `Copy`
* Add arithmetic functions to the `Amount` type. I'm not sure what's the best way. Ideally we would …

cln-rpc: API improvements

---

contrib/pyln-client/pyln/client/__init__.py
contrib/pyln-client/pyproject.toml
contrib/pyln-proto/pyproject.toml
contrib/pyln-testing/pyln/testing/__init__.py
contrib/pyln-testing/pyproject.toml

This is just before the introduction of `get_json_id`, but has the correct dependency constraints such that all packages can be updated to >=v0.12 and we don't mix minor versions.
This addresses a couple of issues:
- The `pyln-client=^0.11` constraint would end up picking an older version
- The `PrettyPrintingLightningRpc` published in `pyln-testing` already uses `get_json_id` which is not defined in `LightningRpc`, but intercepted via `__getattr__` call, and interpreted as a JSON-RPC call, which caused a recursive call.
This fixes both of them by publishing an earlier `pyln-testing` and fixing the constraints in `pyln-testing`.
Changelog-None

pyln: Bump versions to v0.12.1

---

tests/test_gossip.py
tests/test_opening.py

Second pay can fail if first is not completely settled:
```
def test_zeroconf_forward(node_factory, bitcoind):
"""Ensure that we can use zeroconf channels in forwards.
...
sync_blockheight(bitcoind, [l1, l2, l3])
inv = l3.rpc.invoice(42 * 10**6, 'inv1', 'desc')['bolt11']
l1.rpc.pay(inv)
wait_for(lambda: len(l3.rpc.listchannels()['channels']) == 4)
inv = l1.rpc.invoice(42, 'back1', 'desc')['bolt11']
>       l3.rpc.pay(inv)
...
>           raise RpcError(method, payload, resp['error'])
E           pyln.client.lightning.RpcError: RPC call failed: method: pay, payload: {'bolt11': 'lnbcrt420p1p3junrssp588gtjzmlrr4pfj7ssmdlulzhhushrpq3rdqxjuz2m33scsvzdjlspp5fk5yhu6netc0d0sgp8es52vjk6akhd3uayr08u8max4d8rwzpjuqdq8v3jhxccxqyjw5qcqp99qyysgqcpyyugejv4nya97v6gw8fhtr0ru3vq87jjlltav99wlat436a95n0z8yzdp6 …
```

pytest: fix flakes in test_zeroconf_forward, test_gossip_persistence

---

channeld/full_channel.c

If a channel goes offline while the count of outstanding outgoing HTLCs exceeds the limit that we enforce against the peer, then the channel could never be brought online again because `add_htlc` called by `channel_force_htlcs` in `channeld/full_channel.c` would return `CHANNEL_ERR_TOO_MANY_HTLCS`. The protocol specification actually does allow us to exceed the limits that we are enforcing against the peer; we are only prohibited from exceeding the limits that the peer is enforcing against us. `add_htlc` takes an `enforce_aggregate_limits` parameter that appears to have been intended for `channel_force_htlcs` to exempt the local node from obeying the limits that it is enforcing against the peer, but this parameter was only being respected for the total HTLC value-in-flight check but not …

channeld: do not enforce max_accepted_htlcs on LOCAL in channel reinit

---

contrib/startup_regtest.sh

Mac is updating to using zsh in general.
The “for i in” reads strings with spaces as a single entry instead of multiple entries as sh did.
Using “while read” … “<<< $var” makes it treat each space as a new entry.
Changelog-None

devtools: Make fund_nodes compatible w/zsh

---

cln-rpc/src/primitives.rs

Support direct value-to-value conversion between payment `Secret` and a `[u8;32]`. Helps the rpc user skip a heap allocation.
Enables:
```
struct Preimage([u8; 32]);
let response = cln_rpc.lock().await.call({}).await?;
let preimage = Preimage(response.payment_preimage.into());
```
Where we would require:
```
...
let slice: [u8; 32] = response
.payment_preimage
.to_vec()
.try_into()
.expect("invalid payment preimage");
let preimage = Preimage(slice);
```
Changelog-None

cln-rpc: implement from Secret to slice conversion

---

contrib/pyln-testing/pyproject.toml
poetry.lock

Dependabot is complaining that we have an outdated `protobuf` version in our lockfile, let's fix that.

poetry: Update python dependencies

---

tests/test_misc.py

Make sure bitcoind sees tx before we mine blocks!
Changelog-None

pytest: fix flake in test_emergencyrecover

---

Dockerfile

See release notes on https://zlib.net/:

zlib 1.2.12 yanked, update to 1.2.13 in Dockerfile

---

devtools/mkfunding.c

It works now! Walked through with @TKChattoraj :+1:

Fixup mkfunding

---

common/Makefile
common/interactivetx.c
common/interactivetx.h

Takes @niftynei's dualopen collaborative transaction building and makes it available for other daemons to use.
This is to make it available for channeld to do splicing and also other code that may want to us it in the future!

Collaborative transaction building

---

gossipd/routing.c
tests/test_gossip.py

gossipd: ensure old private channel updates are properly deleted
When private channel updates exceed the gossip ratelimit, the previous gossip store entry was not deleted even though all private channel updates are stored. This caused gossip store corruption due to duplicate entries for the same channel.
Fixes: #5656
Changelog-Fixed: Fixed gossip_store corruption from duplicate private channel update

Fix undeleted private channel update gossip_store entry

---

common/sphinx.c
common/sphinx.h
lightningd/options.c
tests/test_plugin.py
wire/fromwire.c

Turns out we *didn't* handle this correctly, sorry Joost!
See https://github.com/lightning/bolts/pull/1021

Handle non-standard onion reply size

---

.gitignore
external/.gitignore

I think the 2 lines in the gitignores speak for themselves.
- ignore pyenv with a local python version
- ignore x86_64-apple-darwin artifacts

add some stuff to gitignores

---

lightningd/chaintopology.c
lightningd/chaintopology.h

@whitslack did an in-depth analysis of the issue at hand, and it turns out we were doing quadratic lookups on an ever increasing list of transactions we broadcast, with ever rebroadcast doubling the size of the rebroadcast list.
The first commit avoids adding the same TX multiple times, while the following two commit replace the entire list with an `htable` instead, reducing complexity to linear.
Fixes #5682

ld: Use `htable` to detect own transactions

---

Cargo.lock
Dockerfile
Makefile
cln-grpc/Cargo.toml
cln-grpc/build.rs
cln-rpc/Cargo.toml
contrib/msggen/msggen/__main__.py
contrib/msggen/msggen/utils/__init__.py
contrib/msggen/msggen/utils/utils.py
external/Makefile
plugins/Cargo.toml

Just some drive-by fixes.
Fixes #5693

Weekly @cdecker cleanups for 2022/45

---

contrib/pyln-client/pyln/client/plugin.py
doc/PLUGINS.md
doc/lightningd-rpc.7.md
lightningd/bitcoind.c
lightningd/invoice.c
lightningd/jsonrpc.c
lightningd/jsonrpc.h
lightningd/plugin.c
lightningd/plugin.h
lightningd/plugin_hook.c
lightningd/signmessage.c
lightningd/test/run-invoice-select-inchan.c
plugins/libplugin.c
plugins/src/lib.rs
plugins/src/messages.rs
tests/test_plugin.py

This is not actually as bad as you'd think; we already handle arbitrary ids, it's just that we need to remember if this request id is a string or not.  Most of the code is plumbing, to only set the flag when the plugin says we can.
This fixes clboss!
I get a new rust warning, though, suspect my monkey coding there is wrong:
```
warning: field is never read: `nonnumericids`
--> plugins/src/lib.rs:49:5
|
49 |     nonnumericids: bool,
|     ^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```

Make modern string-based JSON ids opt in, deprecate numeric ones

---

plugins/autoclean.c

The autoclean plugin would assume we have a `resolved_time` which may not be true for oldish nodes that predate our annotations.
Changelog-None Unreleased change
Reported-by: <@devastgh>
Fixes #5731

autoclean: Fix a null-pointer derefence when checking HTLC age

---

CHANGELOG.md

And internal changes don't get CHANGELOG entries, so removed "- Added interactive transaction building routine ([#5287])".
We need to come up with some way of marking rust crate changes, as it's not immediately obvious what "- cln-plugin" means?
Maybe we switch from JSON-RPC to Control as a more general prefix?
Changelog-None

CHANGELOG.md: order into a more user-first ordering.

---

plugins/src/codec.rs
plugins/src/lib.rs
plugins/src/messages.rs

It was set to crate level visibility for some reason, not all that helpful :-)
Suggested-by: Sergi Delgado Segura <@sr-gi>

cln-plugin: Make the configuration in `init` public

---

lightningd/plugin.c
tests/test_plugin.py

This is a minimal fix: we wait until all plugins reply from init before continuing.  Really large or busy nodes can have other things monopolize lightningd, then the timer goes off and we blame the plugin (which has responded, we just haven't read it yet!).
The real answer is to have some timeouts only advance when we're idle, or have them low-priority so we only activate them when we're idle (this doesn't apply to all timers: some are probably important!).  But this is a minimal fix for -rc3.
Fixes: https://github.com/ElementsProject/lightning/issues/5736

lightningd: don't timeout plugins if init is slow!

---

CHANGELOG.md

Just the diff from the last one, and we remove the reference to semantic versioning as requested in #5716 :-)

meta: Adjust changelog for v22.11rc3

---

devtools/sql-rewrite.py
tests/test_db.py
wallet/db.c

We have a primary key that is spanning the `in_channel_id` and the `in_htcl_id`. The latter gets set to NULL when the HTLC and channel gets deleted, so we coalesce with a random large number that is unlikely to collide for the primary key.
The goal here is not to clean up the issue, that should rather be done by dropping the primary key, but to get the release going again.
This is yet another alternative to #5733 and #5735

db: Backfill missing HTLC IDs in the forwards table

---

.github/workflows/ci.yaml

They are broken, and not a good signal. They should be fixed, but they tend to mark the CI runs as failed, and that's incredibly annoying.

ci: Temporarily disable lnprototest tests

---

.gitmodules

This is the official root repository, and some tools (pip for example) doesn't like pointing to repos that don't actually contain the commit that we point to. Funny that Github actually shows non-existent commits in clones (bitcoin/bitcoin has been impersonated before too).
Changelog-None

submod: Switch lnprototest to clone from github.com/rustyrussell/lnprototest

---

lightningd/chaintopology.c
lightningd/lightningd.c
lightningd/plugin.c
lightningd/plugin.h
lightningd/test/run-find_my_abspath.c

This was found by tests/test_plugin.py::test_important_plugin and was NOT a flake!
Changelog-None: only just committed
See: https://github.com/ElementsProject/lightning/pull/5741

lightningd: correctly exit when an important-plugin fails to start.

---

.gitignore
doc/Makefile
doc/index.rst

docs: Add the `reckless` manpage to the readthedocs generation

---

lightningd/options.c

This is a mistake that I introduced while I implemented the lightningd custom error for hsmd.
In particular, when the command line parser check
if the file is encrypted make an additional check regarding the existence of the file.
This can be a not useful check, but due to the delicate nature of the hsm file, it is better to check if exist and if it doesn't exist an informative line inside the log is emitted that notifies the user that the file does not exist.
This log may return useful while debugging disaster
(that can happen) to understand that there is something strange (eg. the user moves the hsm file somewhere else).
Fixes https://github.com/ElementsProject/lightning/issues/5719

lightningd: do not abort while parsing hsm pwd

---

connectd/multiplex.c

This happens a lot with my node with rc2, so drop it to debug.
Changelog-None

connectd: don't spam logs when we're under load.

---

tools/reckless

In the switch to the logging library for debug output, the verbosity flag was ignored.  This is a simple fix to have the flag set the appropriate log level.  Also squashed the bug causing reckless to add bitcoin-reckless.conf multiple times.
Changelog-Fixed: reckless verbosity properly applied.

Reckless verbose fix

---

lightningd/jsonrpc.c

This reverts commit 43b037ab0b372397cecc477a50fef201b0b313ed.
@NicholasDorier says BTC Payserver still wants this for another year or so.
Changelog-Added: JSON-RPC: reverts requirement for "jsonrpc" "2.0" inside requests (still deprecated though, just for a while longer!)
Fixes: #5782

Revert "lightningd: always require "jsonrpc": "2.0"  in request."

---

common/bolt12.c
common/bolt12.h

It's obviously the incorrect type, while our CI didn't catch it, Nicholas did:
```
plugins/fetchinvoice.c:1362:30: error: conversion from 'long long unsigned int' to 'size_t' {aka 'unsigned int'} changes value from '18446744073709551615' to '4294967295' [-Werror=overflow]
1362 |      || tlv_span(wire, 1001, UINT64_MAX, NULL) != 0) {
```
Reported-by: @NicholasDorier
Changelog-Fixed: Build: arm32 compiler error in fetchinvoice, due to bad types on 32-bit platforms.
Fixes: #5776

common: fix arm32 compile breakage.

---

doc/lightningd-config.5.md
lightningd/options.c

This adds documentation on `man 5 lightningd-config` about the usage of DNS hostnames for `--addr`, `--bind-addr` and `--announce-addr`.
I tried the cases described on a testnet node.
Things we can think about to improve on:
- maybe disallow the announcement of stuff like `localhost.localdomain` (unless DEVELOPER)
- maybe accept upper/mixedcase DNS input like `eXAmPLE.com` and convert on the fly to lowercase instead of throwing an error.
- if we receive a DNS name via p2p gossip, maybe also apply `is_dnsaddr` check before asking the operating system.

doc: document the usage of DNS hostnames

---

common/test/run-ip_port_parsing.c
common/wireaddr.c

This further relaxes the DNS hostname checks to allow for uppercase input.
Changelog-None

wireaddr: allow for UpperCase DNS names

---

doc/REPRODUCIBLE.md

This is a bit of a rabbit hole but the table looks like not supported in the docs site https://lightning.readthedocs.io/REPRODUCIBLE.html we should add additional dependencies, but I find the table is not accessible at all so I'm proposing a new list format.
In addition, other small commits to introduce the manpage for reckless and fix a small typo found in my emacs spellchecker

docs: remove the table inside the reprobuild docs 

---

doc/lightning-fundchannel.7.md
doc/lightning-multifundchannel.7.md

The reserve parameter was missing from the docs. Added the parameter to FundChannel and MultiFundChannel.
I'm not sure whether I used the right format or not, please check.
The reserve parameter was added in this PR: https://github.com/ElementsProject/lightning/pull/5315
Changelog-None: doc only.

add reserve to the fundchannel docs

---

doc/lightning-fetchinvoice.7.md
doc/lightning-getroute.7.md
doc/lightning-invoice.7.md
doc/lightning-keysend.7.md
doc/lightning-pay.7.md
doc/lightning-sendinvoice.7.md
doc/lightning-sendonion.7.md
doc/lightning-sendpay.7.md

To encourage developers to not use deprecated API's and not scare them away with faulty documentation.
I used ripgrep to see where "msatoshi" is used in doc
```
rg -Pg '*.md' -e 'msatoshi' doc/
```
and checked
```
rg -Pg '*.{c,h}' -e 'p_.*\(".*msatoshi"'
```
to see where it is used as jsonrpc input parameter, or as alias for "amount_msat"
BTW `json_sendinvoice` has no "msatoshi" alias, I guess because that command is too new.

doc: replace deprecated param keyword "msatoshi" with "amount_msat"

---

plugins/src/options.rs

This is heavily based on https://github.com/serde-rs/json/blob/master/src/value/mod.rs
Not sure if the `Opt{String, Integer, Boolean}` also need to be covered.

Adds helper functions to cast Value variants in cln-plugin

---

.github/scripts/setup.sh
.github/workflows/ci.yaml
Cargo.lock
cln-grpc/Cargo.toml
cln-grpc/src/convert.rs
cln-grpc/src/pb.rs
cln-rpc/Cargo.toml
cln-rpc/src/primitives.rs
contrib/msggen/msggen/gen/grpc.py
plugins/Cargo.toml
plugins/grpc-plugin/Cargo.toml
plugins/grpc-plugin/src/tls.rs

Some of the dependencies were getting a bit long in the teeth, so let's update them here.
I also added a simplification, in that we rely on the `bitcoin` crate to pull in the `bitcoin_hashes` and `secp256k1` crates, so at least they shouldn't get out of sync, and we can bump just that one dependency.
This also bumps the cln-* crate versions, so we can publish them as soon as this PR gets merged/
Changelog-None No user-visible changes in the API in this PR (prior PRs waiting to be published do, but they have their own entries)

rust: Simplify and update dependencies

---

doc/INSTALL.md

```
error: failed to run custom build command for `cln-grpc v0.1.2 (/home/rusty/devel/cvs/lightning/cln-grpc)`
Caused by:
process didn't exit successfully: `/home/rusty/devel/cvs/lightning/target/debug/build/cln-grpc-933c4bf5006f522c/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=proto/node.proto
cargo:rerun-if-changed=proto
--- stderr
thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
this knowledge. If `protoc` is installed and this crate had trouble finding
it, you can set the `PROTOC` environment variable with the specific path to your
installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases
For more …
```

doc: note that grpc needs the protobuf-compiler

---

Cargo.lock
plugins/src/lib.rs

I think this will complete the work started in https://github.com/ElementsProject/lightning/pull/5717
There are several cases where you want to access to the configuration,
and given the nature of the rust API, there is no way to access to
the `configuration` field at any point after the configuration logic.
Suggested-by: Sergi Delgado Segura <@sr-gi>

cln-plugin: make available the configuration in plugin

---

README.md

Alright, I know this is just a nitpick but I am not sure if that was done on purpose.
The link to github.com/lightningd/plugins is not clickable in the README. One has to copy it and paste it themselves:
Github provides a copy button, but still, I am not sure if that is rendering as intended (instead of just indented).
Looking at the code, I think that this is just unfortunately rendered as a code block which makes the link not clickable since it was only indented (and not explicitly marked as a code block using ```).
Consider this PR as a discussion about this. Didn't want to create a ticket about such a minor issue first, haha

Fix link to github.com/lightningd/plugins not clickable in README

---

contrib/pyln-client/pyln/client/lightning.py

This often helps the msat purge, pyln msat replacement and deprecated-apis mischmasch issues. I changed it in a way that the `AttributeError: 'int' object has no attribute 'millisatoshis'` Error will still be raised whever a `Millisatoshi` is compared to something else then a `Millisatoshi` or `int`.
Also, since we already allow compare equal on `Millisatoshi` and `int`, we should do the same for lower/greater comparison.
Changelog-None

pyln-client: make Millisatoshi comparable to int

---

contrib/pyln-client/tests/test_millisatoshi.py

Sorry, I forgot to include a dedicated test for the last PR.
I think its important so things do not change by accident.

pytest: adds test for msat to int comparison

---

wallet/wallet.c

I discovered this while reworking the CI workflow, and it seems like the HTLC queries do not order, while the tests assume a specific order. This matches sqlite3 which without an explicit ORDER clause will use insertion order, while postgres does not keep things in insertion order, thus breaking the assumption. Ordering by `id` re-establishes that implicit assumption
Changelog-Changed: postgres: Ordering of HTLCs in `listhtlcs` are now ordered by time of creation

db: Fix the ordering of `channel_htlcs` in postgres

---

connectd/connectd.c
connectd/connectd_wire.csv
lightningd/connect_control.c

We were stressing the servers if node cannot be found.  Only do lookup on manual connect commands.

connectd: don't ask DNS seeds for addresses on every reconnect.

---

plugins/topology.c

`local_connected` allocates a `struct node_map` off of the `struct listchannels_opts` but fails to ever release the internal table, so those table allocations hang around forever. Add `node_map_clear` as a destructor for the `struct node_map` to ensure that the internal table is freed when the enclosing struct is freed.

topology: fix memleak in listchannels

---

lightningd/pay.c

When a channel is not yet confirmed onchain and only has an alias, `getroute` will (arguably correctly) return the alias under the "channel" key. However, if you supply that to `sendpay`, it will not be able to find the channel and will fail since it calls `find_channel_for_htlc_add` and that only looks for channels by their scid and doesn't consider their aliases.
This patch makes `find_channel_for_htlc_add` also consider channel aliases when looking for channels.
Partly resolves #5803, but not entirely.

lightningd: Look for channels by alias when finding channels

---

bitcoin/test/run-bitcoin_block_from_hex.c

bitcoin/test/run-bitcoin_block_from_hex run failed in bigendian architecture before change.
The byte order conversion have done in bitcoin_block_from_hex function.
Changelog-None

remove unnecessary CPU_TO_LE32

---

cli/lightning-cli.c

Fortunately it's only used in the test framework (see #5685)
Reported-by: @cdecker

cli: fix buffer overflow in (currently unused!) code for progress bars.

---

common/json_param.h

The file common/json_tok.c has been removed in a previous commit.
Changelog-None

common: update comments documenting the use of param()

---

.github/scripts/build.sh
Dockerfile
contrib/docker/linuxarm32v7.Dockerfile
contrib/docker/linuxarm64v8.Dockerfile
contrib/docker/scripts/build.sh
doc/INSTALL.md

1. The https://zlib.net/zlib-1.2.12.tar.gz change to https://zlib.net/fossils/zlib-1.2.12.tar.gz after zlib 1.2.13 released.
2.  To avoid simlar issue in future ,change https://zlib.net/zlib-1.2.13.tar.gz to https://zlib.net/fossils/zlib-1.2.13.tar.gz
3.  Unified the zlib version in doc and build script files.
Changelog-None

Change the zlib download url

---

common/test/run-bolt12_merkle.c

Reported-by: @jkczyz
Changelog-None
See: https://github.com/lightning/bolts/pull/798#discussion_r1033660687

common/test: fix typo in bolt12 test vector generation.

---

external/.gitignore
tests/test_mkfunding.py

Issue #5363 documented an earlier bug in mkfunding. These tests validate that fix as well as checking that basic usage produces the proper response and exit status.
Changelog-None

pytest: add tests for devtools/mkfunding

---

cli/lightning-cli.c
common/json_parse_simple.c
common/json_parse_simple.h
common/json_stream.c
common/json_stream.h
doc/lightning-cli.1.md
doc/schemas/commando.request.json
lightningd/jsonrpc.c
lightningd/plugin.c
plugins/commando.c
plugins/libplugin.c
plugins/libplugin.h
plugins/test/run-route-overlong.c
tests/test_invoices.py
tests/test_misc.py
tests/test_plugin.py
tests/test_wallet.py

- Clean up our JSON id handling generally.
- Clean up JSON ids in commando commands specifically.
- Support filtering on server-side via `filter` parameter for `commando` cmd.
- Add `--commando=peerid/rune` convenience wrapper for `lightning-cli`.

Commando enhancements and integrated cli support

---

tests/test_bookkeeper.py
tests/test_closing.py
tests/utils.py

#5849 moves to hashmaps, not linked lists. This removes ordering of RPC call output, which the test assertion utility `check_balance_snaps` relied on.
Changelog-None

Compare balance entries by account_id, not assumed order

---

channeld/full_channel.c
common/gossmap.c
common/memleak.c
common/setup.c
connectd/connectd.c
connectd/connectd.h
connectd/gossip_rcvd_filter.c
connectd/multiplex.c
connectd/onion_message.c
connectd/test/run-gossip_rcvd_filter.c
gossipd/gossip_store.c
gossipd/routing.c
gossipd/routing.h
lightningd/chaintopology.c
lightningd/chaintopology.h
lightningd/channel.c
lightningd/htlc_set.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/memdump.c
lightningd/onchain_control.c
lightningd/peer_control.c
lightningd/peer_htlcs.c
lightningd/plugin_hook.c
lightningd/test/run-invoice-select-inchan.c
lightningd/watch.c
plugins/commando.c
plugins/pay.c
wallet/test/run-wallet.c
wallet/txfilter.c

This would catch memory leaks like the one found by @whitslack in #5865 but requires us to allocate htable structs rather than embed them.
Changelog-None

All hash tables should use tal

---

cln-grpc/src/pb.rs
cln-grpc/src/test.rs

`cargo test` is failing under `/cln-grpc` because a coupe of static json (result from listpeers) have not been updated with new fields as the model.
Fixes https://github.com/ElementsProject/lightning/issues/5899

cln-grpc: update listpeers json fixing tests

---

gossipd/routing.c

We removed a warning about the channel_update being malformed since the warning could cause lnd to disconnect (seems they treat channel-unrelated warnings as fatal?). This was caused by lnd not enforcing the `htlc_maximum`, thus the parsing would fail. We can re-add the warning once our assumption that `htlc_maximum` being set is valid.
Changelog-Fixed: gossip: We no longer send warning that lnd would not understand if we get outdated gossip

gossip: Do not send warnings if we fail to parse a `channel_update`

---

ccan/README
ccan/ccan/tcon/tcon.h
lightningd/lightningd.c
lightningd/peer_htlcs.c
lightningd/peer_htlcs.h

(Breaking my build machine, so extracted as standalone from #5892 )
```
lightningd/jsonrpc.c: In function ‘destroy_json_command’:
lightningd/jsonrpc.c:1180:63: error: the comparison will always evaluate as ‘false’ for the address of ‘canary’ will never be NULL [-Werror=address]
lightningd/jsonrpc.c:108:53: note: ‘canary’ declared here
```
Changelog-None

ccan: update to fix recent gcc "comparison will always evaluate as 'false'" warning

---

common/test/Makefile
common/test/run-version.c
common/version.c
common/version.h
wallet/db.c

Rework the logic of the version check used in the
database migration, and make sure
that it is full functional to avoid confusion
at release time.
Fixes https://github.com/ElementsProject/lightning/issues/5870
Reported-by: @urza

comm: make sure that our version check is reliable

---

cln-rpc/src/primitives.rs

PartialEq makes it possible to compare 2 ShortChannelIds for equality which i found often helpful

add PartialEq to ShortChannelId

---

channeld/channeld_htlc.h
channeld/full_channel.c
channeld/test/run-full_channel.c

The `channel->htlcs` map was exhibiting unbounded growth, as elements were never removed from it. This was causing `lightning_channeld` processes to consume ever-increasing amounts of memory, and iterating over the map was causing ever-increasing CPU utilization. There were `FIXME` comments suggesting that the intention was to remove HTLCs from the map upon their deaths. This PR implements that intention.

channeld: remove dead HTLCs from htable and free them (eventually)

---

doc/FAQ.md
doc/Makefile
doc/TOR.md
doc/lightning-listconfigs.7.md
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
gossipd/gossip_generation.c
gossipd/gossipd.c
gossipd/gossipd.h
gossipd/gossipd_wire.csv
lightningd/gossip_control.c
lightningd/lightningd.c
lightningd/lightningd.h
lightningd/options.c
lightningd/options.h
lightningd/peer_control.c
tests/test_connection.py

This adds an 'AUTOBOOL' config switch that explicitly enables the IP discovery feature by `announce-addr-discovered`, as users may also want to have IP discovery plus TOR just as fallback to increase overall connectivity.
Currently its still a bit tricky to use IP discovery as one need to disable any usable addresses i.e. by binding just to a specific interface and configure without TOR. This will enable 'default' behavior: when there are no usable addresses try ip discovery. Without this trick, when a node finds just a single (a likely changing IP address), it will announce this forever and IP discovery is disabled and never rechecks addresses bound to initially.
If unset, the default/auto behavior stays the same, meaning only do IP discovery when there are no usable addresses.
**NOTE: …

ipdiscovery: adds autobool config switch

---

doc/lightning-listconfigs.7.md
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
lightningd/lightningd.h
lightningd/options.c
lightningd/peer_control.c
tests/test_connection.py

This adds a config option `--announce-addr-discovered-port` that can set a non default port when using IP discovery on `node_announcement` updates. Currently and without this only the selected networks default port will be used.

ipdiscovery: adds custom port parameter

---

cln-rpc/src/model.rs
contrib/msggen/msggen/gen/rust.py

rename is necessary to roundtrip, otherwise the rust name is used.
This also remove the rename if they are not necessary.
Note that:
```
#[serde(rename="foo", skip_serializing_if=="bar")]
pub field: bool,
```
is equivalent to:
```
#[serde(rename="foo")]
#[serde(skip_serializing_if=="bar")]
pub field: bool,
```
and for simplicity of construction the latter is used

cln-rpc: use serde rename instead of alias

---

Dockerfile

I needed to install `protobuf-compiler` to the builder for it to work.
Otherwise I would receive this error message:
```
cargo build --profile=release --quiet --example cln-plugin-startup
error: failed to run custom build command for `cln-grpc v0.1.2 (/opt/lightningd/cln-grpc)`
Caused by:
process didn't exit successfully: `/opt/lightningd/target/release/build/cln-grpc-eaabe37d9f29a125/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=proto/node.proto
cargo:rerun-if-changed=proto
--- stderr
thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
this knowledge. If `protoc` is installed and this crate had trouble finding
it, you can set the `PROTOC` environment variable with the specific path to your
installed …
```

docker: Install protobuf-compiler for builder

---

gossipd/routing.c

Followup for #5897, since `node_announcement` parsing could result in a warning being sent too.

gossipd: Do not send warning when node_announcement parsing fails

---

common/gossip_store.h
common/gossmap.c
devtools/dump-gossipstore.c
gossipd/gossip_generation.c
gossipd/gossip_store.c
gossipd/gossip_store.h
gossipd/gossipd.c
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-check_channel_announcement.c
gossipd/test/run-txout_failure.c
tests/test_gossip.py

BOLT 7 allows pruning channels when one side's `channel_update` expires.  This results in the `channel_announcement` being deleted.  When the offline node sends a new `channel_update`, the `channel_announcement` will be unavailable and the channel is not reestablished.
Here instead of being deleted entirely, the channel is zombified: the `channel_announcement` is maintained along with the still relevant `channel_update` in case the expired `channel_update` is ever refreshed.  These are marked with a zombie bit in the gossip store so that they are available to gossipd, but ignored by gossmap and other consumers.  In the case that all channels of a node become zombies, the node_announcement is tagged as well.
Two valid `channel_update`s will resurrect a channel (and possibly a node), …

Keep channel announcements when pruning channels

---

lightningd/datastore.c
tests/test_misc.py

We need to check if the key parameter is an empty array in `datastore` commands as we expect a `key` to be at least of len 1 in _wallet.c_.
Changelog-None

Add check for empty key array on datastore commands.

---

db/exec.c

Avoids the following when postgres returns no query result: ==63458== Conditional jump or move depends on uninitialised value(s)
==63458==    at 0x226A1F: db_postgres_step (db_postgres.c:156)
==63458==    by 0x22535B: db_step (utils.c:155)
==63458==    by 0x1E089A: db_data_version_get (exec.c:49)
==63458==    by 0x194F6F: db_setup (db.c:1029)
==63458==    by 0x199A2F: wallet_new (wallet.c:101)
==63458==    by 0x154B70: main (lightningd.c:1035)
Changelog-None

db: catch postgres error on uninitialized database

---

doc/Makefile

This seems to fix issue #5941 ( `/bin/sh: line 1: 1.2.md: No such file or directory` )
Looks to me like certain make versions(?) will parse the ')' as function end when not inside " " but ' ' . That will terminate the sed string too early, leaving the unexpanded '1.2.md'.
Changelog-None

make: fix make doc error

---

cln-grpc/src/convert.rs
cln-rpc/src/model.rs
doc/lightning-getinfo.7.md
doc/schemas/getinfo.schema.json
lightningd/peer_control.c

~~Since it is always returned even if empty~~ this was false, see https://github.com/ElementsProject/lightning/pull/5904#issuecomment-1386475617 , there are cases where address field is not returned, but since there are also cases where is returned empty the issue remains. 
alternative to #5902 
Closes #5902 
Changelog-None

doc-schema: make address field in getinfo response required

---

plugins/libplugin-pay.c

Valgrind correctly reports it as uninitialized for this log message, and the only way this can happen is channel_hints_update() when we receive a temporary_channel_failure.  Put a dummy value here in this case.
```
Valgrind error file: valgrind-errors.23404
==23404== Conditional jump or move depends on uninitialised value(s)
==23404==    at 0x49E4B56: __vfprintf_internal (vfprintf-internal.c:1516)
==23404==    by 0x49F6519: __vsnprintf_internal (vsnprintf.c:114)
==23404==    by 0x1EBCEB: do_vfmt (str.c:66)
==23404==    by 0x1EBDF8: tal_vfmt_ (str.c:92)
==23404==    by 0x11A336: paymod_log (libplugin-pay.c:167)
==23404==    by 0x11B4B2: payment_chanhints_apply_route (libplugin-pay.c:534)
==23404==    by 0x11E999: payment_compute_onion_payloads (libplugin-pay.c:1707)
==23404==    by …
```

plugins/pay: fix htlc_budget calc when we get temporary_channel_failure

---

lightningd/lightningd.c

I believe our memleak detection is limited in the context of lightningd's main(). This has not been an issue until recently when the 100k peers changes introduced just enough delay on the postgres CI test that `unconnected_htlcs_in` is unable to be freed before tests/test_misc.py::test_logging kills lightningd.
After investigating, it appears the memory is appropriately freed and reallocated during map_copy, so the only thing to do is flag this with `notleak` as is done with `sigchld_conn` and `orig_argv`.  Alternatively, adding `l2.stop()` to the end of the test in question allows allows time for the memory to be freed and results in no test errors.
The CI flake this addresses:
```
E           ValueError: 
E           Node errors:
E           Global errors:
E            - Node …
```

Flag false-positive memleak in lightningd

---

contrib/pyln-testing/pyln/testing/utils.py

When doing the updates on the plugin repo ( https://github.com/lightningd/plugins/pull/422 ), I discovered that the `wait_for_htlcs()` helper function got broken by the `listpeerchannels` upgrade. It's rarely used in the main repo, just at the end of the pyln-testing 'pay' helper.
If unfixed, this bug may result in test flakes when using the `pay` helper, because its not correctly waiting for all HTLCs to be resolved before returning.
Changelog-None

pyln-testing: fix wait_for_htlcs helper

---

plugins/libplugin-pay.c
tests/plugins/zeroconf-selective.py
tests/test_pay.py

I ported @dongcarl 's test and found two bugs, one minor (temporary memleak), one major (pay didn't specify which channel to use, so we always used the first one with peer!).

Fix pay with multiple channels

---

lightningd/connect_control.c
lightningd/lightningd.h

In various circumstances we can start a reconnection while one is already going on.  These can stockpile if the node really is unreachable.
Fixes: #5654
Changelog-Fixed: lightningd: we no longer stack multiple reconnection attempts if connections fail.

lightningd: don't run more than one reconnect timer at once.

---

plugins/libplugin-pay.c
plugins/libplugin-pay.h

Note: updates/overwrites fix from `6176912683ef10e86c3fc119f6641f3a9d0ef56d`; this is a nicer update since it categorically removes the error (embeds the field w/in the 'local-ness' of the hint).
The htlc_budget only exists iff the hint is a 'local' one; we were failing to write to the htlc_budget field for non-local cases.
To avoid this, we make `local` into a struct that contains the fields that pertain to local-only payments (in this case, `htlc_budget`).
Valgrind error file: valgrind-errors.1813487
==1813487== Conditional jump or move depends on uninitialised value(s)
==1813487==    at 0x4A9C958: __vfprintf_internal (vfprintf-internal.c:1687)
==1813487==    by 0x4AB0F99: __vsnprintf_internal (vsnprintf.c:114)
==1813487==    by 0x1D2EF9: do_vfmt (str.c:66)
==1813487==    by 0x1D3006: …

valgrind-fix: patch valgrind error on log statement in pay plugin

---

contrib/pyln-client/pyln/client/clnutils.py
contrib/pyln-client/tests/test_clnutils.py

This adds the `cln_parse_rpcversion` helper that is already used in various plugins to pyln-client, so it does not need to be copied around anymore.
Changelog-None

pyln-client: adds utils cln_parse_rpcversion

---

doc/INSTALL.md

See GitHub Issue [here](https://github.com/pyenv/pyenv/issues/1737#issuecomment-794592631):
```
Python versions without https://github.com/python/cpython/pull/21113 and its backports are incompatible with MacOS 11 and cannot be built on it.
Releases with the fix are: 3.7.8+, 3.8.4+, 3.9.0+
Any earlier versions can't be built.
```
I'm making the assumption that there wasn't any specific reason that `3.7.4` was required vs `3.7.8`
`cargo build --quiet --bin cln-grpc`

Some Updates to macOS Install Instructions

---

.github/workflows/ci.yaml
tests/test_closing.py

Fixups included for https://github.com/ElementsProject/lightning/pull/5910 while I try to fix remaining failing tests
Other PR included the wrong build which lacked experimental features, causing random-seeming failures.
Maybe a good idea to hard fail if experimental flag is given on a non-experimental build?

gci: Re-Add `TEST_NETWORK=liquid-regtest` to CI run

---

lightningd/peer_htlcs.c

```
----------------------------- Captured stderr call -----------------------------
Sending onchaind an invalid message 03ed00000000000000004e52a9129a66619d6809b1024eb9a0159f173a988f3a5d0bdd2447b4fcc24cef
lightningd: FATAL SIGNAL 6 (version 3c57147-modded)
```
The channel state can also be `FUNDING_SPEND_SEEN` if onchaind is still starting up.
Changelog-None: Not reported by any user, mainly a test race AFAICT.

lightningd: don't send channeld message to onchaind.

---

common/peer_failed.c
common/peer_failed.h
common/wire_error.c
lightningd/channel.c
lightningd/channel.h
lightningd/dual_open_control.c
lightningd/peer_control.c
lightningd/test/run-find_my_abspath.c
lightningd/test/run-invoice-select-inchan.c
openingd/dualopend.c
tests/test_closing.py
tests/test_connection.py
tests/test_opening.py
tests/test_pay.py
tests/test_plugin.py

Built on #5670. Starts at `fa30d80d5ad1151f5374e72158038f02b46dc33b`
Kind of a fun one. We've got a fancy new message (tx-abort) which will signal we're ending a channel open negotiation. 
What's fun about this is that now when we abort/end an open channel negotiation (v2s only), we don't disconnect from the peer. Instead the subdaemon for the open dies. If the peer retries, we restart the daemon.
What's nice about this is that we now keep the connection open for any other channels that we may or may not currently have with the peer we're talking to.

dual-funding -> use tx-abort now

---

tests/test_closing.py

We might be disconnected, but the subd isn't dead yet:
```
>       assert out[0] == '# peer is offline, will negotiate once they reconnect (5 seconds before unilateral close).'
E       AssertionError: assert '# Timed out, forcing close.' == ('# peer is offline, will negotiate once they reconnect (5 seconds before '\n 'unilateral close).')
E         - # peer is offline, will negotiate once they reconnect (5 seconds before unilateral close).
E         + # Timed out, forcing close.
tests/test_closing.py:164: AssertionError
```
Changelog-None

pytest: fix flake in test_closing_disconnected_notify

---

Makefile

It gets partially regenerated, so include it in the check. This is the root cause for the v22.11-modded issue some have noticed.

make: Add doc/index.rst to generated files

---

.msggen.json
cln-grpc/proto/node.proto
cln-grpc/src/convert.rs
cln-grpc/src/server.rs
cln-rpc/src/model.rs
contrib/msggen/msggen/utils/utils.py
contrib/pyln-testing/pyln/testing/grpc2py.py
doc/Makefile
doc/index.rst
doc/lightning-createinvoice.7.md
doc/lightning-signinvoice.7.md
doc/schemas/signinvoice.request.json
doc/schemas/signinvoice.schema.json
lightningd/invoice.c
tests/test_invoices.py

```
Though there's already a `createinvoice` command, there are usecases where a
user may want to sign an invoice that they don't yet have the preimage to. For
example, they may have an htlc_accepted plugin that pays to obtain the preimage
from someone else and returns a `{ "result": "resolve", ... }`.
This RPC command addresses this usecase without overly complicating the
semantics of the existing `createinvoice` command.
Changlog-Added: JSON-RPC: `signinvoice` new command to sign BOLT11
invoices.
```
Also adds a commit to correct `createinvoice`'s `invstring` description. (See the commit message for more details)
One main question for reviewers is whether this PR is acceptable without support for BOLT12 invoices. I'm not familiar enough with them to write code for them. Perhaps it can …

lightningd: Add `signinvoice` to sign a BOLT11 invoice. 

---

.msggen.json
cln-grpc/proto/node.proto
cln-grpc/src/convert.rs
cln-rpc/src/model.rs
contrib/pyln-testing/pyln/testing/grpc2py.py
doc/lightning-listpeers.7.md
doc/lightning-sql.7.md
doc/schemas/listpeers.schema.json
lightningd/peer_control.c
tests/test_connection.py

This will be helpful for plugins and because of the `listpeerchannels` `listpeers` split, so that we can reduce unnecessary RPC ping/pong calls when `num_channels` is 0.
A lot of plugins still need to iterate both calls, so then they can save some IO load and delays.

listpeers: add num_channels

---

channeld/channeld.c

Currently it is impossible for the log line to be hit since the value is set to 1, then reset immediately after to 0. Makes it hard to see if this is happening in a degenerate way. 
Changelog-None

Bugfix: Fix 'extreme cases' logging of many commit timer failures

---

.github/scripts/install-bitcoind.sh
.github/workflows/bsd.yml
.github/workflows/ci.yaml
.github/workflows/macos.yaml

Looks like we missed some spots in https://github.com/ElementsProject/lightning/pull/5813, next time we need to check the right binary is actually being used in CI...

Update Bitcoin Core to 24.0.1 in other git ci locations

---

common/features.c
common/psbt_internal.c
openingd/dualopend.c
wire/extracted_peer_07_openchannelv2_updates.patch
wire/peer_wire.csv

Adds requested spec proposal changes, including addition of `est_witness_weight` field and `second_commitment_point` to the open/accept_channel2 messages.
(Note that `accept_channel2` also includes `second_commitment_point`, per commit https://github.com/lightning/bolts/pull/851/commits/ee5bef78aba209ad9f28fbf1f40fb432fea6d108).
Built on top of #5900.
@t-bast this is a good one to test for interop!

Last(?) Updates to dual-funding Spec

---

channeld/channeld.c
common/features.c
common/features.h
connectd/gossip_rcvd_filter.c
connectd/gossip_store.c
connectd/multiplex.c
doc/lightning-listconfigs.7.md
doc/lightningd-config.5.md
doc/schemas/listconfigs.schema.json
gossipd/gossipd.c
lightningd/connect_control.c
lightningd/options.c
lightningd/peer_control.c
openingd/dualopend.c
plugins/chanbackup.c
tests/test_misc.py
wire/extracted_peer_07_peer_storage.patch
wire/extracted_peer_exp_upgradable.patch
wire/peer_wire.c
wire/peer_wire.csv
wire/peer_wire.h

This PR implements `peer storage backup` which will enable nodes to exchange their respective SCBs (Static channel backup), This will be useful in case of complete data loss.
One of the major features of lightning is that the transactions are off-chain and are stored in a local database, which makes this DB highly dynamic and complex to backup.
Peer storage backup will allow users to send their encrypted backup to their peers, which can be used to recover their funds in case of complete data loss.
The strategy is that we'll store the data received in the [datastore](https://lightning.readthedocs.io/lightning-datastore.7.html).
So to implement this I've introduced 2 new messages i.e. `PEER_STORAGE` and `YOUR_PEER_STORAGE`, these will be used to exchange the data stored between the nodes. …

Peer storage feature

---

.github/workflows/ci.yaml
cln-grpc/src/pb.rs
cln-grpc/src/test.rs

This adds some clean-up code on the rust side and also includes a pre-build check test on the rust side.
Currently, we do not have a strong test suite for rust that can fall inside our own task, maybe we could include it inside our make file logic in the future?
Fixes https://github.com/ElementsProject/lightning/issues/5971

fix(grpc): add the num_channels field inside the tests

---

doc/lightning-listpeerchannels.7.md
doc/schemas/listpeerchannels.schema.json
lightningd/peer_control.c

These were deprecated in v0.12.0, hence scheduled for removal next version anyway (use local_fund_msat and remote_funds_msat).
Changelog-None: introduced in this release

lightningd: don't put old deprecated `local_msat` and `remote_msat` in listpeerchannels.

---

wallet/db.c

Fixes https://github.com/ElementsProject/lightning/issues/5972
People are upgrading to 22.11.1 not, and in some configurations like the one 
mentioned in the issue, we should 
put some info information in the log when we are not able to upgrade.

add a log message when it is not possible upgrade the db

---

gossipd/routing.c

As reported by @whitslack a channel_update is retrieved which appears to have already been deleted.  Check that it exists before resurrecting!
Fixes #5989
Changelog-None

Fix channel resurrection where a channel update is missing

---

lightningd/dual_open_control.c

This fixes the following compilation error
and allow rebuilding again on 32-bit platform.
```
lightningd/dual_open_control.c: In function 'validate_input_unspent':
lightningd/dual_open_control.c:2627:43: error: format '%llu' expects argument of type 'long long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
2627 |                         err = tal_fmt(pv, "PSBT input at index %"PRIu64
|                                           ^~~~~~~~~~~~~~~~~~~~~~~
2628 |                                       " missing serial id", i);
|                                                             ~
|                                                             |
|                                                             size_t {aka unsigned int} …
```

fix: compilation error on armv7l 32 bit

---

lightningd/options.c

Properly sets the peer storage feature bits as optional (odd):
40 -> 41
42 -> 43
Fixes: #6002

peer storage: advertise features as optional

---

tests/test_gossip.py

The test runs fine on CI but can fail locally on IPv6 systems, as the address descriptor is just checked agains IPv4.
Changelog-None

pytest: allow ipv6 in test_announce_dns_suppressed

---

common/gossmap.c

This will fix a crash that I caused on armv7
and by looking inside the coredump with gdb
(by adding an assert on n that must be
different from null) I get the following stacktrace
```
(gdb) bt
#0  0x00000000 in ?? ()
#1  0x0043a038 in send_backtrace (why=0xbe9e3600 "FATAL SIGNAL 11") at common/daemon.c:36
#2  0x0043a0ec in crashdump (sig=11) at common/daemon.c:46
#3  <signal handler called>
#4  0x00406d04 in node_announcement (map=0x938ecc, nann_off=495146) at common/gossmap.c:586
#5  0x00406fec in map_catchup (map=0x938ecc, num_rejected=0xbe9e3a40) at common/gossmap.c:643
#6  0x004073a4 in load_gossip_store (map=0x938ecc, num_rejected=0xbe9e3a40) at common/gossmap.c:697
#7  0x00408244 in gossmap_load (ctx=0x0, filename=0x4e16b8 "gossip_store", num_channel_updates_rejected=0xbe9e3a40) at …
```

[PATCH] fixes `FATAL SIGNAL 11` on loading gossmap

---

devtools/dump-gossipstore.c
gossipd/gossip_generation.c
gossipd/gossip_store.c
gossipd/gossip_store.h
gossipd/routing.c
gossipd/routing.h
gossipd/test/run-check_channel_announcement.c
gossipd/test/run-check_node_announcement.c
gossipd/test/run-crc32_of_update.c
gossipd/test/run-txout_failure.c

This does some cleanups: by getting rid of node_announcements associated with all-zombie nodes, it should fix the underlying issue, too.
Changelog-None (fixes within this release cycle)

Fix zombie node_announcement handling

---

plugins/autoclean.c
tests/test_plugin.py

If we had two things to clean, we fired off two requests (eg. listforwards and listinvoices) and both marked the timer as finished, triggering an assert.
We already have a refcount for outstanding requests to avoid this for e.g. outstanding del commands, so use it here too!
```
Jan 19 19:20:00  lightningd[748044]: autoclean: plugins/libplugin.c:445: timer_complete: Assertion `p->in_timer > 0' failed.
Jan 19 19:20:00  lightningd[748044]: autoclean: FATAL SIGNAL 6 (version v22.11.1)
Jan 19 19:20:00  lightningd[748044]: 0x562c388136e4 send_backtrace
Jan 19 19:20:00  lightningd[748044]:         common/daemon.c:33
Jan 19 19:20:00  lightningd[748044]: 0x562c3881376c crashdump
Jan 19 19:20:00  lightningd[748044]:         common/daemon.c:46
Jan 19 19:20:00  lightningd[748044]: 0x7f26d0898d5f ??? …
```

autoclean: fix timer crash when we're cleaning two things at once.

---

lightningd/pay.c
tests/test_pay.py

It works for the trivial case, where groupid and partid are the same, but silently deletes nothing in the other cases (or worse, deletes the wrong entry!).
See: #5835
Changelog-Fixed: `delpay`: actually delete the specified payment (mainly found by `autoclean`).

pay: fix delpay to actually delete.

---

plugins/chanbackup.c

This commit will disable the peer-storage plugins
when the feature is not enabled.
I found this issue with lnprototest, and I guess
we did not find it with a normal run because
other the unknown messages are ignored?
I did a monkey fix, please @adi2011 check the sanity of my patch
Changelog-Fixed: Disable the protocol messages when peerstorage is disabled.

[PATCH] do not send send peerstorage msg when disabled

---

common/json_parse.c
common/json_parse.h
plugins/keysend.c
plugins/libplugin.c
plugins/libplugin.h
tests/test_pay.py

This is a followup on https://github.com/ElementsProject/lightning/pull/5645 which started stripping TLV fields that have an unknown even TLV type, which is correct.
However we also have an allowlist facility in the form of `--accept-extra-tlv-types` that tells `lightningd` that some unknown TLV types can be accepted despite not knowing their semantics. This allows simpler composition of functionality since `keysend` still handles the common functionality of accepting, backfilling the invoice and resolving a payment, while others (plugins or apps) can rely on the `invoice_payment` hook to extract those types. This is for example how Sphinx is implemented.

keysend: Do not strip TLV types that were allowlisted in `lightningd`

---

gossipd/gossip_store.c
gossipd/routing.c
gossipd/routing.h

As reported by @m-schmoock, some nodes and channels went missing from the gossmap while running 23.02rc3.  This occurred after restarting the node, which possibly lost some state on the zombie channels.
Changelog-None

Zombie channel patch

---

gossipd/routing.c

This channel update should not have been left behind and it results in a corrupted gossip_store.

gossipd: delete zombie spam channel update when resurrecting

---

plugins/sql.c

It wasn't updating, and thus failing locally: perhaps the test is not working properly under valgrind?

Fix sql nodes table (again)

---

connectd/connectd.c

ccan/io stores the context pointer for io_new_conn, but we were using `daemon->listeners` which we reallocate, so it can use a stale pointer.
```
0x3e1700 call_error
ccan/ccan/tal/tal.c:93
0x3e1700 check_bounds
ccan/ccan/tal/tal.c:165
0x3e1700 to_tal_hdr
ccan/ccan/tal/tal.c:174
0x3e1211 to_tal_hdr_or_null
ccan/ccan/tal/tal.c:186
0x3e1211 tal_alloc_
ccan/ccan/tal/tal.c:426
0x3db8f4 io_new_conn_
ccan/ccan/io/io.c:91
0x3dd2e1 accept_conn
ccan/ccan/io/poll.c:277
0x3dd2e1 io_loop
ccan/ccan/io/poll.c:444
0x3419fa main
connectd/connectd.c:2081
```
Fixes: #6060

connectd: fix crash on freed context for new connections.

---

wallet/db.c

e778ebb9af5a6157a4b605a77f87b2c48b9d03b0 ("wallet: only log broken if we have duplicate scids in channels.") downgraded the fatal() to a broken log message, but the user reports it still won't start up.
Perhaps they're hitting the fatal() outside the loop?  (And we're not getting that output).
Maybe-fixes: #6063 ?

wallet: really allow broken migrations.

---

plugins/chanbackup.c

Seems like LND is hanging up on receiving these messages, even though they're odd :(
So, when a peer connects, check if it supplies or wants peer backup (even if it doesn't support both, it shouldn't hang up, and I didn't want to separate the two paths).
And when we go to send our own, updated backup, check features before sending.
Fixes: #6065
Changelog-EXPERIMENTAL: `experimental-peer-storage` caused LND to hang up on us, so only send to peers which support it.

chanbackup: even if they enable experimental-peer-storage, check peers

---

doc/Makefile
doc/index.rst
doc/lightning-disableinvoicerequest.7.md
doc/lightning-fetchinvoice.7.md
doc/lightning-invoicerequest.7.md
doc/lightning-listinvoicerequests.7.md
doc/lightning-offer.7.md
doc/lightning-sendinvoice.7.md
doc/schemas/disableinvoicerequest.request.json
doc/schemas/disableinvoicerequest.schema.json
doc/schemas/invoicerequest.request.json
doc/schemas/invoicerequest.schema.json
doc/schemas/listinvoicerequests.request.json
doc/schemas/listinvoicerequests.schema.json
plugins/offers_offer.c

As reported on Discord, these are undocumented.  And thus, um, hard to find!
Also, sendinvoice documentation was out-of-date, fix that too.
Reported-by: Aaron Barnard
Changelog-None

doc: add documentation for invoicerequest commands.

---

CHANGELOG.md
plugins/pay.c

It's still deprecated: we need the description since
1. This information is useful for any validation we want to do, such as the HSM, or runes.
2. We want this information in listpays so we can tell what we actually paid.
3. In general, we should never sign commitments to things we don't have!
I expect to have this information about payments *whatever the frontend* is, which is why we deprecated (and then removed) this unintended use.  The spec is pretty clear on this:
BOLT 11 (https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#requirements-3)
```
A reader:
...
- MUST check that the SHA2 256-bit hash in the `h` field exactly matches the hashed
description.
```
However, neither BTCPayServer nor lnbits updated despite the long deprecation period, so revert …

plugins/pay: revert removal of paying invoice without description.

---

plugins/src/lib.rs

This helps avoid a pain-point where [plugin authors need to do shutdown-related cleanup in 2 places](https://github.com/ElementsProject/lightning/issues/6040). Now plugins can just call `plugin.shutdown()` when they receive "shutdown" notification, and do all cleanup in that one place when `plugin.join()` is triggered.
Changelog-None

cln_plugin: add `shutdown()` method to `Plugin`

---

.github/workflows/bsd.yml
.github/workflows/ci.yaml
.github/workflows/ci_build.yml
.github/workflows/macos.yaml
.github/workflows/prototest.yaml
.github/workflows/pypi.yml

Fixes https://github.com/ElementsProject/lightning/issues/5976
I forgot to push this yesterday! This proposes to add a limit of 2 hours to the CI I do not know if 2h is a good time, but we can always increase it.
@instagibbs propose to limit only pytest, this will not catch dependencies resolution loop with python that time to time in the past happened
Changelog-None

ci: add timeout field to max 3h for each task

---

tests/test_db.py

Should resolve https://github.com/ElementsProject/lightning/issues/5909 , pretty sure the test harness just loses track of the other CLN node.
Also pushed a commit that adds a fixture that runs checks between every test looking for leaked processes and fds.

test_backfill_scriptpubkeys: stop first cln node before second sub-test

---

plugins/fetchinvoice.c
tests/test_pay.py

assign the quantity field to receive as RPC parameter inside the invrequest field.
Fixes https://github.com/ElementsProject/lightning/issues/6089

plugin: fetchinvoice: assign the quantity to the invrequest field

---

.msggen.json
cln-grpc/proto/node.proto
cln-grpc/src/convert.rs
cln-rpc/src/model.rs
contrib/pyln-testing/pyln/testing/grpc2py.py
doc/lightning-listfunds.7.md
doc/schemas/listfunds.schema.json
wallet/walletrpc.c

See #6020 for context. This is useful, makes more easy use of `dev-forget-channel` to remove channels with no transaction in a blockchain (`CHANNELD_AWAITING_LOCKIN` in my case), can give `channel_id` argument.
Changelog-None

Output `channel_id` in `listfunds`

---

connectd/tor_autoservice.c

This changes connectd to use `status_fail()` on TOR problems during statup instead of `err()`. Using `err()` did not write to the logfile.
To find out TOR problems during startup, the user needed to stop the system daemon and call `lightningd` manually in console to see the error.
`status_fail()` logs and exits, but also prints a whole stacktrace, which is a bit too much imho on config errors. But currently there is no `status_SOMETHING` method that logs, prints and exists on an error without stacktrace.
Changelog-None

connectd: log status_failed on TOR problems

---

channeld/channeld.c

We would sleep for 10msec (default) and try again, spamming the logs every second.  But we're waiting for revoke_and_ack, and that handler already sets off the timer, so there's no need to spin at all!
Fixes: #6077
Changelog-Fixed: `channeld`: no longer spin and spam logs when waiting for revoke_and_ack.

channeld: don't spin trying to send commitment while waiting.

---

tests/fuzz/fuzz-bech32.c

If the fuzzer passes an empty `data` buffer, the fuzz target currently attempts to read from it. We should short-circuit instead.
Changelog-None

fuzz: avoid buffer overflow in bech32 target

---

tests/fuzz/fuzz-channel_id.c

The issue is that `common_setup` wasn't called by the fuzz target, leaving `secp256k1_ctx` as NULL.
UBSan error:
```shell
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1" \
./fuzz-channel_id crash-1575b41ef09e62e4c09c165e6dc037a110b113f2
INFO: Running with entropic power schedule (0xFF, 100). INFO: Seed: 1153355603
INFO: Loaded 1 modules   (25915 inline 8-bit counters): 25915 [0x563bae7ac3a8, 0x563bae7b28e3),
INFO: Loaded 1 PC tables (25915 PCs): 25915 [0x563bae7b28e8,0x563bae817c98),
./fuzz-channel_id: Running 1 inputs 1 time(s) each.
Running: crash-1575b41ef09e62e4c09c165e6dc037a110b113f2
bitcoin/pubkey.c:19:33: runtime error: null pointer passed as argument 1, which is declared to never be null
external/libwally-core/src/secp256k1/include/secp256k1.h:373:3: note: nonnull attribute …
```

fuzz: fix UBSan nullability error

---

hsmd/libhsmd.c

Currently the failure prints a log and hangs forever; I suspect that isn't the intention.
N.B. `hsmd_status_broken` is only used here so it may be vestigial?

Report failure to sign psbt inputs by hsmd

---

plugins/autoclean.c

While we are cleaning up the list forwards with the autoclean plugin we are not taking into count the forward's payments with the status set to `local_failed`. In this case, the forwards have no resolved time because it was not resolved by us due to some local error.
So, this commit is fixing the auto clean plugin by allowing to delete of the forwards with status set to local_failed by taking into count the received_time, with the assumption that the received_time, in this case, is equal to the resolved time (?)
Reported-by: @denis2342
Link: https://github.com/ElementsProject/lightning/issues/6058
Changelog-Fixed: plugin: autoclean: considerer the forwards with status set to `local_failed`.
Fixes …

plugin: autoclean: cleanup the forwards with localfailed

---

cln-grpc/src/convert.rs
contrib/msggen/msggen/gen/grpc.py
plugins/grpc-plugin/src/tls.rs
tests/test_cln_rs.py

The mTLS private key files should be user-readable only, so set the mode accordingly. Also contains a bit of a drive-by fix for deprecated fields in our own code, causing warnings.
Fixes #6064

grpc: Adjust the file permissions on mTLS private keys

---

tests/fuzz/fuzz-close_tx.c

`pubkey_from_hexstr` was failing, which we didn't notice because we weren't checking the return value. The problem was that we were passing it a strlen that was half the actual length.
Relevant error:
```
[libsecp256k1] illegal argument: !secp256k1_fe_is_zero(&ge->x)
==417723== ERROR: libFuzzer: deadly signal
#7 0x7f5deaacc7fb in abort
#8 0x51b0b0 in secp256k1_default_illegal_callback_fn secp256k1.c
#9 0x51bd8e in secp256k1_ec_pubkey_serialize
#10 0x4e235b in pubkey_to_der bitcoin/pubkey.c:29:7
#11 0x4e2941 in pubkey_cmp bitcoin/pubkey.c:89:2
#12 0x4e333d in bitcoin_redeem_2of2 bitcoin/script.c:144:6
#13 0x4f1396 in run tests/fuzz/fuzz-close_tx.c:78:19
```

fuzz: fix invalid pubkey error

---

doc/lightning-delpay.7.md
lightningd/pay.c
tests/test_pay.py
wallet/wallet.c
wallet/wallet.h

There are cases (difficult to reproduce with a test) where
a payment will fail one time and succeed later.
As far I understand in this case the groupid field of the payment
is the same, and the only thing that change is the status, so
our logic inside the delpay is ambiguous where it is not
possible to delete a payment as described in https://github.com/ElementsProject/lightning/issues/6114
A sequence of commands that explain the problem is
```
$ lc -k listpays payment_hash=H
{
"pays": [
{
"bolt11": "I",
"destination": "redacted",
"payment_hash": "H",
"status": "complete",
"created_at": redacted,
"completed_at": redacted,
"preimage": "P",
"amount_msat": "redacted",
"amount_sent_msat": "redacted"
}
]
}
$ lc delpay H complete
{
"code": 211,
"message": "Payment with hash H has failed status …
```

delpay: delete the payment by status from the db 

---

contrib/pyln-client/README.md

Small fix to the [helloworld.py example](https://github.com/ElementsProject/lightning/tree/master/contrib/pyln-client#writing-a-plugin) in the README for pyln-client.
An alternate fix would be to simply link to [this file](https://github.com/ElementsProject/lightning/blob/master/contrib/plugins/helloworld.py), which has more examples and appears to be more up to date.
Let me know if you would like me to implement that instead :)
Changelog-None

fix helloworld.py example in README for pyln-client

---

db/exec.c
db/exec.h
db/utils.c
db/utils.h
gossipd/test/run-check_channel_announcement.c
gossipd/test/run-txout_failure.c
lightningd/test/run-find_my_abspath.c
lightningd/test/run-invoice-select-inchan.c
plugins/bkpr/recorder.c
wallet/test/run-db.c

No code changes, just some cleanups.

Db code cleanups

---

common/test/run-channel_type.c
lightningd/lightningd.c
lightningd/lightningd.h
tests/test_misc.py

In CI we see crashes when we call `stop` before connectd is setup.  This is not an elegant way to stop, and it's caused by an assertion that the io_loop will be exited by connectd's init reply (not the stop command!).
Simple fix.  Also fixes master which doesn't build RN :(
Fixes https://github.com/ElementsProject/lightning/issues/6130

Early shutdown fix

---

tests/test_pay.py

Inside our integration testing we get another timeout, so this commit 
adds a timeout to the waitpay command to avoid waiting forever.
Find inside the https://github.com/ElementsProject/lightning/pull/5997

test: add the timeout to the waitpay command

---

tests/test_pay.py

This is for VLS, which doesn't implement signing for the non-standard recurrence fields.
Only splits into two, no test change.
Changelog-None

tests: split fetchinvoice recurrence tests into separate test.

---

cln-rpc/src/primitives.rs
tests/test_cln_rs.py

We were using two incompatible custom types (dicts vs arrays), so we need a custom conversion.
Reported by @Evanfeenstra
Fixes #6143

clnrs: Add custom conversion for routehints

---

bitcoin/psbt.c

Intended to resolve https://github.com/ElementsProject/lightning/issues/6147
Whenever we send a PSBT over the wire, we set to legacy version, and whenever we read it off, we set to v2.
Changelog-None: fixes regression in this release cycle

have towire_wally_psbt and fromwire_wally_psbt set safe psbt version

---

doc/lightning-hsmtool.8.md
tests/test_wallet.py
tools/hsmtool.c

This allows creation of a master rune *before the node starts*.  You will still need to create a rune once the node starts, if you want commando to work (as it is only activated once it has generated one), but creating a default rune will give the identical results to the tool anyway.
Requested-by: @ShahanaFarooqui

hsmtool rune

---

.github/workflows/ci.yaml

There are several benefits of doing this:
- prevent fuzz target bit rot
- more test coverage in CI
- greater visibility of fuzz tests, encouraging contributions to the seed corpus and tests themselves
Resolves https://github.com/ElementsProject/lightning/issues/6083.
Changelog-None: no user-visible changes --RR

ci: run fuzz regression tests

---

connectd/gossip_store.c
connectd/gossip_store.h
connectd/multiplex.c
gossipd/gossip_store.c
gossipd/gossip_store.h
gossipd/gossipd.c
gossipd/routing.c
gossipd/test/run-check_channel_announcement.c
gossipd/test/run-txout_failure.c
tests/test_gossip.py

Despite improvements in peer handling and connection, there is still a bottleneck in connectd traversing the entire gossip_store on each new peer connection in order to send our own gossip (anything flagged with `push`.)  This moves the task of streaming our self-generated gossip from connectd to gossipd, gaining efficiency from gossipd's data structures.  As a side effect, the gossip_store push flag becomes superfluous. Additionally, the handling of gossip filtering is also now truly trinary (all/none/stream.)
Changelog-Changed: Self-generated gossip is more efficiently streamed on peer connect; gossip_store push bit removed.

gossip: improve handling of self-generated gossip when sending to peers

---

Makefile
cln-rpc/Makefile
contrib/pyln-testing/pyln/testing/utils.py
plugins/Makefile
plugins/examples/cln-plugin-reentrant.rs
plugins/src/codec.rs
plugins/src/lib.rs
plugins/src/messages.rs
plugins/src/options.rs
tests/test_cln_rs.py

This was reported as an issue with `htlc_accepted` and the `invoice_payment` hooks, not working properly, but the root cause seems to be that we were synchrously handling events, only reading the next once the previous one hast been fully dealt with. This of course doesn't allow for things like holding multiple `htlc_accepted` hook calls, waiting for an incoming notification while processing a hook or request, and prevent reentrant calls into the plugin through the RPC passthrough.
This PR just runs handlers in `async` tasks, freeing the event loop that reads from `lightningd` to read any concurrent events.

cln-plugin: Handle incoming events asynchronously

---

bitcoin/psbt.c

Trivial update, pulls in secp256k1-zkp security update: https://github.com/ElementsProject/libwally-core/releases/tag/release_0.8.9

Update libwally to 0.8.9

---

tests/test_reckless.py
tools/reckless

Removes an extraneous web request, and unnecessary config rewrites. Adds an installer class to support resolution/installation of dependencies and specification of necessary binaries for additional languages.
Based on #6110
Changelog-Changed: Added support for node.js plugin installation via reckless

Reckless update

---

tests/test_reckless.py
tools/reckless

Fixes a bug in installer registration where executable is evaluated before entrypoints and other details are added.
***RECKLESS STDERR***
File lightning/tools/reckless, line 382, in <module>
INSTALLERS['nodejs'].add_entrypoint('{name}')
KeyError: 'nodejs'
Reported by @ksedgwic
Changelog-None

reckless: simplify installer registration

---

connectd/websocketd.c

After the first iteration of the loop, we call `memmem` with a `buflen` that points past the end of `buf`.
In practice we probably never read the uninitialized memory since we guarantee the buffer ends with "\r\n", and since most libc implementations probably read the haystack sequentially. But maybe there's some libc with a crazy optimization out there. It's good to use an accurate `buflen` just in case.
Discovered this while running some unit tests with MSan.
Ref https://github.com/ElementsProject/lightning/issues/6119.

connectd: pass correct buflen to memmem

---

plugins/spender/multifundchannel.h

gcc 13 add an extra check for the enum in the definition of a method. In our case, the code was failing with the following error, and the compiler is right, our definition is different from the implementation.
```
$ make
CC: cc -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -Wshadow=local -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/x86_64-redhat-linux/libbacktrace-build -I external/libsodium/src/libsodium/include -I external/libsodium/src/libsodium/include/sodium -I …
```

fix: build with gcc 13 with enum and int mismatch

---

contrib/pyln-testing/pyln/testing/utils.py

Variable inroduced in 708fb17 is making CI fail.

pyln: remove unused variable

---

lightningd/peer_control.c

This is a regression that we introduced in this release
due to some dirty parts of our codebase.
For historical reasons (I think), we were using a `json_add_sat_only`
procedure defined in `peer_control.c`. So when @rustyrussell removed the _msat,
we thought that all the fields were reflecting the new behavior, but
we were wrong.
This PR fixes this bug and also removes the additional function
from `peer_control.c`. This way, we can be sure that there is no other part
of our codebase that uses this method (except for other `json_add` methods).
Fixes: https://github.com/ElementsProject/lightning/issues/6244
Reported-by: @hMsats

jsonrpc: Remove the old "_msat" prefix in the listpeerchannels command

---

.github/workflows/ci.yaml
tests/test_cln_rs.py

Test was hastily written, plugin crashed, command didn't return, pytest doesn't run with --timeout: CI just killed it after two hours.
Changelog-None

pytest: fix test_cln_plugin_reentrant which panics rust under CI.

---

cln-grpc/proto/primitives.proto
cln-rpc/src/primitives.rs

While updating my plugins to 23.05 non-deprecated methods i encountered this error 
```
Malformed response from lightningd: unknown variant `SENT_ADD_ACK_COMMIT`, expected one of `SENT_ADD_HTLC`, `SENT_ADD_COMMIT`, `RCVD_ADD_REVOCATION`, `RCVD_ADD_ACK_COMMIT`, `SENT_ADD_ACK_REVOCATION`, `RCVD_ADD_ACK_REVOCATION`, `RCVD_REMOVE_HTLC`, `RCVD_REMOVE_COMMIT`, `SENT_REMOVE_REVOCATION`, `SENT_REMOVE_ACK_COMMIT`, `RCVD_REMOVE_ACK_REVOCATION`"
```
this should fix it
Changelog-None

add missing htlc states from incoming htlcs

---

external/Makefile

This patches a sidechannel issue that was present in secp-zkp dependency, and also brings us a step closer to taproot deposit/withdrawal support: https://github.com/ElementsProject/libwally-core/releases/tag/release_0.9.0

Update libwally to 0.9.0

---

plugins/txprepare.c

kept it simple instead of trying to extract the transaction again, since it can be extracted using utilities

signpsbt_done: don't try to access global tx in exception

---

.github/scripts/build.sh
.github/scripts/setup.sh
.github/workflows/bsd.yml
.github/workflows/macos.yaml
Dockerfile
Makefile
configure
contrib/docker/Dockerfile.alpine
contrib/docker/Dockerfile.builder
contrib/docker/Dockerfile.builder.fedora
contrib/docker/Dockerfile.tester
contrib/docker/linuxarm32v7.Dockerfile
contrib/docker/linuxarm64v8.Dockerfile
contrib/docker/scripts/build.sh
contrib/docker/scripts/setup.sh
contrib/reprobuild/Dockerfile.focal
contrib/reprobuild/Dockerfile.jammy
doc/INSTALL.md
tools/headerversions.c
tools/repro-build.sh

Core and secp have not used gmp for a very long time now (core disabled it in 2015).

build: remove gmp

---

external/Makefile

`make clean && make` wasn't rebuilding lowdown.
Discovered this while building some external dependencies with MSan.

make: clean up lowdown install

---

db/bindings.c

I'm not sure this can be hit, but this seems like the smallest way to guard against it since we never create new PSBTs of version 0 anymore.

db_col_psbt: convert to PSBTv2 on load from db

---

contrib/pyln-testing/pyproject.toml
poetry.lock
pyproject.toml

Python package fails to build on latest ubuntu `Ubuntu 23.04`, so update the various things.  This was in https://github.com/ElementsProject/lightning/pull/6243 but I extracted it here because I need it to test...

Grpcio update

---

cln-grpc/Cargo.toml
cln-grpc/src/lib.rs
cln-grpc/src/pb.rs
plugins/grpc-plugin/Cargo.toml

Reported by @roeierez: the `cln-grpc` crate had a direct dependency on `cln-rpc` which can only run on Unix-like OSs due to its reliance on UDS to talk to CLN. Since we might want to use the `cln-grpc` crate on clients that may themselves not support UDS sockets, we better guard that behind a feature flag. Since the conversion is only required on the server, it's called the `server` feature, and `grpc-plugin` pulls it in via that flag.

rs: Split the `cln-grpc` into client-only and server features

---

gossipd/gossip_store.c

Aids in debugging #6270, where there was an attempt to delete gossip which had overrun the end of the gossip store. This logs the gossip type of the deletion attempt and avoids an immediate crash. We don't know what type gossip message failed the deletion attempt, but a tombstone would be fine to skip over at least.
Changelog-None

gossipd: don't fail on gossip deletion

---

.github/workflows/ci.yaml
doc/Makefile

CI currently does a merge with master, but that makes it nasty to do a straight diff (which is how we check schemas).
This changes it to do a rebase, which makes it trivial.

test: rebasing, and handing base ref to doc/Makefile

---

common/json_stream.c
common/json_stream.h
common/utils.h
db/bindings.c
devtools/decodemsg.c
devtools/route.c
lightningd/jsonrpc.c
lightningd/plugin.c
plugins/libplugin-pay.c

These were all uncovered from running the test suite with ASan and UBSan:
```shell
$ DEVELOPER=1 EXPERIMENTAL_FATURES=1 ASAN=1 UBSAN=1 VALGRIND=0 CC=clang ./configure
$ make check-units pytest
```
Motivation for https://github.com/ElementsProject/lightning/issues/6119.

Fix errors detected by ASan and UBSan

---

doc/lightning-commando-rune.7.md
plugins/commando.c
tests/test_plugin.py

(based on #6294 )
Closes: #6288 
I had forgotten that we already strip punctuation from parameter names, so we merely need to treat integer parameters correctly FTW.  And document that `_` stripping!

Runes: document parameter usage, and let them be ints.

---

.github/workflows/ci.yaml
tools/hsmtool.c

Running these sanitizers in CI will help to avoid introducing new memory safety errors.
Closes #6119.

ci: run tests with ASan and UBSan

---

lightningd/opening_control.c
openingd/openingd.c
openingd/openingd_wire.csv

option_scid_alias inside a channel_type allows for more private channels: in particular, it tells the peer that it MUST NOT allow routing via the real short channel id, and MUST use the alias.
It only makes sense (and is only permitted!) on unannounced channels.
Unfortunately, we didn't set this bit in the channel_type in v12.0 when it was introduced, instead relying on the presence of the feature bit with the peer.  This was fixed in 23.05, but:
1. Prior to 23.05 we didn't allow it to be set at all, and
2. LND has a limited set of features they allow, and this isn't allowed without option_anchors_zero_fee_htlc_tx.
We could simply drop this channel_type until we merge anchors, *but* that has nasty privacy implications (you can probe the real channel id).
So, if we don't negotiate anchors …

openingd: work harder to intuit OPT_SCID_ALIAS.

---

doc/PLUGINS.md
lightningd/bitcoind.c
lightningd/bitcoind.h
lightningd/chaintopology.c
plugins/bcli.c
tests/test_plugin.py

When core lightning is asking the information about
the blockchain with `getchaininfo` command lightningd
know already the information about the min and max block height.
the problem is when we have a smarter Bitcoin backend that is able
to switch between different clients in some cases is helpful
give the information about current known height by lightningd and
pass it down to the plugin.
In this way, the plugin knows what is the correct known height from lightnind, and can
try to fix some problems if any exist.
This is particularly useful when you are syncing a new backend from scratch
like https://github.com/cloudhead/nakamoto and we avoid returning the
lower height from the known, and avoid the crash of core lightning.
With this information, the plugin can start to sync the chain and …

[RFC] lightningd: pass the current known block height down to the getchaininfo call

---

.github/workflows/ci.yaml
.github/workflows/ci_build.yml
.github/workflows/pre_build.yml
.github/workflows/prototest.yaml

I have re-enabled the compilation build workflow to ensure that we maintain compatibility across different operating systems. Please refer to [this link](https://github.com/ElementsProject/lightning/pull/6335) for more details.
This PR addresses the issue of CI precedence by rearranging the workflow order, placing the pre-build checks before other workflows. Additionally, I have explored the usage of `workflow_run` to establish dependencies between workflows. 
By implementing this approach, we can now incorporate separate workflow files for different tasks, such as the `build check` or the `lnprototest check`. This allows us to maintain the precedence within the job graph and prevents the `ci.yml` file from becoming overly complex and unwieldy.

ci: re-enable the compilation workflow

---

common/configvar.c

This fixes the compile issue that we are having on Alpine.
```
cc wallet/wallet.c
cc wallet/walletrpc.c
cc wallet/reservation.c
cc wallet/db_sqlite3_sqlgen.c
cc wallet/db_postgres_sqlgen.c
cc common/addr.c
cc common/bolt11.c
cc common/bolt11_json.c
cc common/bolt12.c
cc common/configdir.c
cc common/configvar.c
cc common/scb_wiregen.c
common/configvar.c: In function 'configvar_remove':
common/configvar.c:118:9: error: unknown type name 'ssize_t'; did you mean 'size_t'?
118 |         ssize_t prev = -1;
|         ^~~~~~~
|         size_t
make: *** [Makefile:292: common/configvar.o] Error 1
make: *** Waiting for unfinished jobs....
```
Reported-by: @gruve-p
Fixes: https://github.com/ElementsProject/lightning/issues/6321

fix: build on alpine linux

---

lightningd/opening_control.c
lightningd/peer_control.c
lightningd/peer_control.h
tests/test_connection.py
wallet/db.c
wallet/test/run-wallet.c
wallet/wallet.c

On channel creation with a peer, we can persist feature bits of that peer and load them on restart.
This allows more sane behavior after a restart before we've reconnected with a peer, f.e. when deciding if a peer has opted in to `anysegwit` when creating taproot outputs. Needed for https://github.com/ElementsProject/lightning/pull/6035
This PR doesn't persist for each connection, only on new channel creation.

Persist feature bits across restarts

---

.github/workflows/ci.yaml
common/bolt11.c
lightningd/invoice.c
plugins/pay.c
tests/test_invoices.py
tests/test_pay.py

Fixes: #6085 
Notably, since our deschash comparison was broken, we cannot insist people provide a description, so back off on that deprecation.

Fix deschash escaped json

---

contrib/pyln-proto/pyln/proto/message/__init__.py

Exposing the tlv types to allow public access to it.
would be nice to have this merged before July to unlock me with lnprototest :)

pyln-proto: expose the tlv types

---

doc/INSTALL.md

GNU xgettext is required to compile. It is found in the gettext-tools package in OpenBSD. Tested on OpenBSD 7.3

Correct INSTALL.md requirements for OpenBSD

---

wallet/invoices.c

It'll wrap, probably be in the past, and infinite loop.  This was caused by an invoice with expiry set at 2076.  This wrap caused us to think the expiry has already passed, and keep looping!
Reported-by: @telelvis
Fixes: #6339
Changelog-Fixed: lightnind: don't infinite loop on 32 bit platforms if only invoices are expiring after 2038.

wallet: don't try to set a timer past 2038 on 32-bit platforms.

---

contrib/plugins/cowsay.sh

I was getting the following error when trying to call `cowsay` method:
$ lightning-cli cowsay
{
"code": -4,
"message": "Plugin terminated before replying to RPC call."
}

contrib: fix id parsing in IO loop of cowsay.sh plugin

---

contrib/init/lightningd.service

When the `--daemon` flag is used, `lightningd` requires that `--log-file` is used as well. By consequence, the `lightningd.service` didn't work out-of-the-box for me.
This changes also sends the logs to `journald`.
The new approach is consistent with the `bitcoind.service` file in the bitcoin-core repository.
I prefer this approach because it comes with automatic log-rotation.

Remove --daemon from lightningd.service

---

README.md
doc/INSTALL.md

This commit is adding the instructions for compiling cln on FreeBSD, because it looks like we not longer compile with the FreeBSD package manager, and I have no idea who the mantainer of this package is.
Fixes: https://github.com/ElementsProject/lightning/issues/6301 
Fixes https://github.com/ElementsProject/lightning/issues/6227

fix(docs): Fix instructions for installing cln on FreeBSD

---

contrib/plugins/helloworld.py
contrib/pylightning/README.md
contrib/pyln-client/README.md
doc/PLUGINS.md
doc/guides/Developer-s Guide/plugin-development/event-notifications.md
lightningd/notification.c
plugins/funder.c
tests/plugins/block_added.py
tests/plugins/test_libplugin.c

Notifications neaten format

---

lightningd/chaintopology.c
lightningd/channel_control.c

This commit fixes a bug introduced in 64b1ddd761de30152154714433974b72bfb7f278 that does not 
ignore the min fee as specified by the user setting.
We explicitly allow the user to ignore the fee limits, although this comes with inherent risks.
By enabling this option, users are explicitly
I was aware of the potential dangers.
There are situations, such as the one described in [1], where it 
becomes necessary to bypass the fee limits to resolve issues like a stuck channel.
BTW experimental-anchors should fix this.
[1] https://github.com/ElementsProject/lightning/issues/6362
Reported-by: @pabpas
Fixes:  https://github.com/ElementsProject/lightning/issues/6362

fix: do not ignore the ignore-fee-limit option
