- cln-grpc/src/convert.rs
- cln-rpc/src/model.rs
- contrib/msggen/msggen/gen/grpc.py
- contrib/msggen/msggen/gen/rust.py
- plugins/src/lib.rs
currently I'm doing something like this to compare two RPC enums:
```
format!("{:?}", sendpay_response.status) == format!("{:?}", SendpayStatus::COMPLETE)
```
(maybe there's a better hack I'm unaware of)
by adding PartialEq I can do `sendpay_response.status == SendpayStatus::COMPLETE`
I'm not super familiar with the whole logic of `rust.py` but I don't think this will land on any enums that can't derive PartialEq because `gen_enum` also derives TryFrom i32 for these same enums
Question: should this change include a bump to the cln-rpc version?
> rs: derive PartialEq for simple rust enums

- lightningd/chaintopology.c
- tests/test_closing.py
This is just housekeeping that allows up
to do not spam the logs of people with not
useful information.
Fixes https://github.com/ElementsProject/lightning/issues/6226
> lightnind: cleanup not necessary logs

- tools/hsmtool.c
This commit addresses a limitation in our CLI argument checking for the hsmtool. With this update, we introduce support for the Signet network.
In addition, it introduce a code semplification by directly passing the BIP32 version instead of using network testnet flag. This change improves code readability and minimaze code changes to support other networks.
Fixes https://github.com/ElementsProject/lightning/issues/6371
> hsmtool: Add support for Signet network

- .github/workflows/prototest.yaml
The lnprototest occasionally fails on our CI due to the
timeout duration we set while waiting for cln to start up.
This timeout is insufficient for machines like the ones
used in the GitHub CI environment.
To address this issue, this commit introduces the use of
environment variables to increase the lnprototest timeout,
ensuring sufficient time for cln to initialize.
Regarding the update of lnprototest version, there is nothing special. Just making some test 
code more general and lnprototest API more consistent
> lnprototest: update to the last version and fix flakiness of lnprototest on CI 

- Makefile
https://stackoverflow.com/a/14813278
Found-by: @ddustin
In theory you *shouldn't* need the '.bak' but it doesn't seem to work without it on mac?
> mac-fix: `sed` doesn't work the same on macos

- contrib/pyln-client/pyln/client/plugin.py
- doc/PLUGINS.md
- doc/guides/Developer-s Guide/plugin-development/event-notifications.md
- lightningd/notification.c
- lightningd/plugin.c
- plugins/libplugin.c
- plugins/libplugin.h
- tests/plugins/all_notifications.py
- tests/plugins/test_libplugin.c
- tests/test_plugin.py
Subscribing to "" will now give you every event: I've added support to pyln-client and libplugin for this.
Note: you can tell *which* notification it was in Python by having an argument called "request" and looking at "request.method"
Suggested-by: @ShahanaFarooqui
> Plugin event notification subscription wildcard support

- wallet/db.c
Currently our CI is not able to complete the compilation because
there is the following compilation error introduced in 0bcff1e76d
```
cc wallet/db.c
wallet/db.c: In function 'migrate_normalize_invstr':
wallet/db.c:1734:3: error: too many arguments to function 'db_bind_text'
1734 |   db_bind_text(update_stmt, 0, invstr);
|   ^~~~~~~~~~~~
In file included from wallet/db.c:10:
./db/bindings.h:25:6: note: declared here
25 | void db_bind_text(struct db_stmt *stmt, const char *val);
|      ^~~~~~~~~~~~
wallet/db.c:1735:3: error: too many arguments to function 'db_bind_u64'
1735 |   db_bind_u64(update_stmt, 1, id);
|   ^~~~~~~~~~~
In file included from wallet/db.c:10:
./db/bindings.h:23:6: note: declared here
23 | void db_bind_u64(struct db_stmt *stmt, u64 val);
|      ^~~~~~~~~~~ …
```
> wallet: Fixes the compilation error due the db_binindings change 

- gossipd/gossipd.c
- tests/test_gossip.py
@endothermicdev investigated this, and we diagnosed together.  It's a regression introduced in v23.05 when we moved "gossip blast" from gossip store into gossipd.
Through the glory of tests, we also fixed a similar issue where we didn't send incoming channel_updates: we never did, but it's a good thing to do!
Fixes: #6410
> Fix node announce self-advertize and advertize both sides of channels

- plugins/libplugin-pay.c
- plugins/pay.c
- tests/test_pay.py
- tests/test_plugin.py
The presplitter modifier would split a payment before trying the first
attempt based on some common sizes. Its goal was to have smaller parts
in flight over different paths, in order to make it more difficult for
a forwarding node to learn payment amount. However it was causing some
issues for direct payments, and estimates on spendable amounts which
considers only the first HTLC being added, but presplitter would
always cause multiple HTLCs to be kicked off, causing the estimate to
be off.
Removing the presplitter fixes this, making draining channels easier,
and worse success rates, due to more HTLCs in flight directly
impacting the changes of getting stuck.
> pay: Remove presplitter

- contrib/pyln-testing/README.md
- contrib/pyln-testing/pyln/testing/utils.py
- contrib/pyln-testing/pyproject.toml
We also document how the grpc test mode works, and why it currently lacks coverage.
This may help reduce the number of dependencies we pull in as well as sidestepping some esoteric platforms not having precompiled binaries for grpcio causing them to fail.
Changelog-Changed: pyln-testing: The grpc dependencies are now optional.
> pyln: Make the grpcio dependencies optional

- common/jsonrpc_errors.h
- doc/Makefile
- doc/index.rst
- doc/lightning-blacklistrune.7.md
- doc/lightning-checkrune.7.md
- doc/lightning-createrune.7.md
- doc/lightning-listrunes.7.md
- doc/schemas/blacklistrune.request.json
- doc/schemas/blacklistrune.schema.json
- doc/schemas/checkrune.request.json
- doc/schemas/checkrune.schema.json
- doc/schemas/createrune.request.json
- doc/schemas/createrune.schema.json
- doc/schemas/listrunes.request.json
- doc/schemas/listrunes.schema.json
- lightningd/Makefile
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/runes.c
- lightningd/runes.h
- lightningd/test/run-find_my_abspath.c
- tests/test_runes.py
- wallet/db.c
- wallet/wallet.c
- wallet/wallet.h
This moves the `runes` functionality of CLN from `commando` into the core (it does not yet redirect the commando plugin to use the core, but that's next!).  This allows runes to be use by far more infrastructure, such as the coming `clnrest` plugin!
Changelog-Added: JSON-RPC: `checkrune`: check rune validity for authorization; `createrune` to create/modify rune; `listrunes` to list existing runes; `blacklistrune` to revoke permission of rune
Changelog-Deprecated: JSON-RPC: `commando-rune`, `commando-listrunes` and `commando-blacklist`.
> Runes migration from commando to lightning

- README.md
Just a lil PR to update the docs links, for anyone, like me, who was confused about where the new docs live
> Swap out doc links with link to new doc website

- lightningd/pay.c
- plugins/libplugin-pay.c
Debugging a number of payments showed that we sometimes waste a number of attempts routing through a channel via its alias, rather than its scid. This is because while we annotate the scid when it has been set, we do not do so for the alias. The alias then is picked for routing despite not having enough capacity, failing the attempt locally.
It can also happen that we alternate between scid and alias, doubling the number of failed attempts before we can make progress.
This patch sets the hint for the alias to a capacity of 0 and disables it as if the peer were offline. This means when available we'll always use the scid, which is also far easier to read in the logs.
Changelog-Fixed: pay: We now track spendable amounts when routing on both the local alias as well as the short channel ID
> pay: Annotate both local alias and real scid with channel hints

- .github/workflows/ci.yaml
GH was complaining about Node v12 being used in v2.2.4. We used to hold back from this upgrade because v3 was breaking quotas, but we should try again.
Changelog-None
> ci: Update the upload-artifact step to v3

- channeld/channeld.c
```
channeld WARNING: Bad update_fail_malformed_htlc failure code 4103
```
Warren Togami reports this happening with Bitrefill on every reconnect, so it's clearly something LND does.
(4103 is TEMPORARY_CHANNEL_FAILURE, which does not belong in update_fail_malformed_htlc).
Changelog-Changed: Protocol: We allow update_fail_malformed_htlc with invalid error codes (LND?)
> channeld: don't close connection on invalid badonion code (LND bug?)

- devtools/print_wire.c
Clang on OpenBSD found this little guy. Build fails without the `%lld`.
```
devtools/print_wire.c:94:18: error: format specifies type 'long' but the argument has type 's64' (aka 'long long') [-Werror,-Wformat]
printf("%ld\n", v);
~~~     ^
%lld
1 error generated.
gmake: *** [Makefile:299: devtools/print_wire.o] Error 1
```
Changelog-None
> devtools/print_wire: long long instead of longing

- lightningd/subd.c
We get intermittant reports of subd->conn being leaked, but I could never find it. That's because it's actually subd which is not referenced any more: subd->conn gets reported because it's subd's tal_parent (and, except for the reference in subd, not referenced either).
The real issue is that the channel->owner is reassigned to the new subdaemon, and the old one is still exiting.  During that time, we can see a "leak".
```
- Node /tmp/ltests-hkr089bp/test_sql_1/lightning-3/ has memory leaks: [
{
"backtrace": [
"ccan/ccan/tal/tal.c:477 (tal_alloc_)",
"ccan/ccan/io/io.c:91 (io_new_conn_)",
"lightningd/subd.c:774 (new_subd)",
"lightningd/subd.c:828 (new_channel_subd_)",
"lightningd/dual_open_control.c:3662 (peer_restart_dualopend)",
"lightningd/peer_control.c:1161 (connect_activate_subd)", …
```
> lightningd: fix false memleak report (test flake)!

- gossipd/gossip_store.c
- gossipd/gossip_store.h
- gossipd/routing.c
- gossipd/test/run-check_channel_announcement.c
- gossipd/test/run-txout_failure.c
This looked like a test flake, but was real:
```
l1.daemon.wait_for_log("closing soon due to the funding outpoint being spent")
time.sleep(1)
>       assert len(get_gossip(l1)) == 2
E       assert 4 == 2
```
We can see that two channel_updates come in *after* we mark it dying:
```
gossipd: channel 103x1x0 closing soon due to the funding outpoint being spent
gossipd: REPLY WIRE_GOSSIPD_NEW_BLOCKHEIGHT_REPLY with 0 fds
022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-gossipd: Received channel_update for channel 103x1x0/0 now DISABLED
022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-gossipd: Received channel_update for channel 103x1x0/1 now DISABLED
```
We should keep marking channel_updates the same way.
> gossipd: don't "unmark" dying channels' updates if we receive them.

- Makefile
- lightningd/channel_control.c
At cold start, if your node is behind the blocktip and you've sent your peer a blockheight counter from the future, we shouldn't confuse ourselves with our rollback/replay.
Should fix flakes in CI that were spotting BROKEN blockheight updates.
Also includes small patch to use the same GRPC paths for the `rm` cleanup.
> blockheight bug

- doc/lightning-checkrune.7.md
- doc/schemas/checkrune.request.json
It accepts rune first and nodeid second but the documentation showed incorrect sequence.
> docs: Incorrect params sequence for checkrune command

- common/bolt11.c
For non-v0 witness programs we weren't stripping the data push byte before writing into the fallback address.
According to BIP14, all witness scripts will be data pushes (up to 40-bytes) so trimming the datapush byte should be kosher.
From BIP141:
A scriptPubKey (or redeemScript as defined in BIP16/P2SH) that
consists of a 1-byte push opcode (for 0 to 16) followed by a
data push between 2 and 40 bytes gets a new special meaning.
The value of the first push is called the "version byte". The
following byte vector pushed is called the "witness program".
Changelog-Fixed: Adding a >0 version witness program to a fallback address now is *just* the witness program, as per bolt11 spec
> bolt11: Don't push the size of the witness program for v1+ scripts

- channeld/channeld.c
- tests/test_misc.py
This commit addresses an issue to enhance the resilience of core lightning when receiving node announcements.
According to BOLT 7 (The announcement_signatures Message), if the node_signature OR the bitcoin_signature is NOT correct, it is recommended to either send a warning and close the connection or send an error and fail the channel.
In this commit, we take a strict approach. If any error is detected, we send an error and fail the open channel operation. This is because the announcement_signatures operation is optional, and we assume that it must be correct.
lnprototest at commit dea47c29b5541dbfe7fe53cc2598330e897fa4f4 report the following error now.
```
2023-07-06T21:03:20.930Z DEBUG   hsmd: Shutting down
ERROR    root:helpers.py:170 Traceback (most recent call last):
File …
```
> channeld: Verify the signature sent by the counterparty (aka do not trust verify)

- lightningd/peer_htlcs.c
- onchaind/onchaind.c
- plugins/bcli.c
- tests/test_closing.py
@t-bast described this issue in general, and here's the fix, with some cleanups on the way.
1. We forward an HTLC.
2. The outgoing channel goes onchain
3. We try to spend the outgoing HTLC (onchain) to time it out.
4. But we either don't pay enough because fees spiked, or with anchors, we decide it's not worthwhile to pay enough fees.
5. HTLC stays open and incoming side gets upset, closing channel.
Our solution is to monitor for this: 
1. If an htlc is incoming, and <= 3 blocks away from timing out
2. And there's a corresponding outgoing
3. And it's onchain (it will be by default, since cltv_delta is 6 (testnet) or 34 (mainnet).
4. Fail the incoming immediately.
This is a risk, of course: the outgoing HTLC could be claimed by the peer.  But that's no worse to us than it not getting mined …
> Avoid cascading failure: give up on incoming HTLCs in time if outgoing is stuck.

- gossipd/gossip_store.c
We also need a test that will break if you miss updating this test.  Will work on one.
> gossipd: handle upgrade from version 11 gossip_store

- tests/test_reckless.py
- tools/reckless
This adds abstractions to the search and directory traversal so that additional installation sources can be used.  It supports local git repositories, local directories, and web hosted git repos beyond github (does not require an api.)  Needs some squashing.
> Reckless: support additional installation sources

- plugins/libplugin-pay.c
The alias may not be set for non-alias channels after they
confirm. The other branch is safe because we only consider active
channels.
Changelog-None
Fixes #6450
> pay: Fix a null-dereference introduced in #6428

- lightningd/htlc_end.c
- lightningd/peer_htlcs.c
Since we now abandon HTLCs to avoid breaking a channel (in limited circumstances), the peer can take the funds if they beat us to spend the HTLC before we timeout.  This is extremely unusual, but finally happend in CI.
First it fails our internal sanity checks, but then it would fail when we tried to fulfill an already-failed HTLC:
```
**BROKEN** lightningd: fulfill_our_htlc_out:Output preimage, input failonion?
**BROKEN** lightningd: FATAL SIGNAL 6 (version f82fedb-modded)
**BROKEN** lightningd: backtrace: common/daemon.c:38 (send_backtrace) 0x55c09b04f0b5
**BROKEN** lightningd: backtrace: common/daemon.c:75 (crashdump) 0x55c09b04f247
**BROKEN** lightningd: backtrace: ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0 ((null)) 0x7f607463551f
**BROKEN** lightningd: backtrace: …
```
> lightningd: don't crash if peer manages to spend onchain HTLC after we've abandoned upstream

- gossipd/gossipd.c
- gossipd/gossipd_wire.csv
- lightningd/gossip_control.c
This will at least *help* the case where these were not populated, causing us to send errors without channel_updated appended.
It's not perfect: we can still send such errors if the gossip store is corrupted, and we still send them for private channels, but it should help.
(The much better fix is far more invasive, so slips to next release!)
See: #5822
> gossipd: tell lightningd about all our previous channel_updates at startup

- gossipd/gossip_generation.c
When an outdated own node announcement is present, it can fail the `nannounce_different` test and also fail to kick off the forced regen timer.
An alternative solution is to manually start the `setup_force_nannounce_regen_timer` from gossip_init, however as `maybe_send_own_node_announce` is already called at init, that seems like a more appropriate event to actually update and broadcast the refreshed node announcement.
Changelog-Fixed: Node announcements are refreshed more reliably.
> gossipd: actually update own node announcement if needed

- common/peer_failed.c
- common/peer_failed.h
- common/peer_status_wire.csv
- common/read_peer_msg.c
- common/wire_error.c
- lightningd/dual_open_control.c
- lightningd/dual_open_control.h
- lightningd/onchain_control.c
- lightningd/opening_common.c
- lightningd/opening_common.h
- lightningd/peer_control.c
- lightningd/peer_control.h
- lightningd/subd.c
- lightningd/subd.h
- lightningd/test/run-find_my_abspath.c
- lightningd/test/run-invoice-select-inchan.c
- lightningd/test/run-shuffle_fds.c
- openingd/dualopend.c
- openingd/dualopend_wire.csv
- plugins/funder.c
- tests/test_opening.py
- wallet/test/run-wallet.c
Reported by @t-bast from cross-compat with the Eclair dual-funding implementation.
Now we re-init the dualopend daemon when closed from an 'abort'. Seems to work very nicely? 
Also fixes a problem where the channel won't advance to "NORMAL" if aborted on a subsequent RBF attempt.
Also fix bug where the `funder` would increase the reservation on RBFs of already reserved utxos, which then led to us *not* unreserving them on open failure. It's a halfway move towards us not reserving utxos at all during the negotiation phase of a channel open.
> dual-fund: tx-abort fixups

- devtools/credit
Script was broken, at least here.
Changelog-None
> devtools/credit: ! not ^ to invert the match set in sh.

- lightningd/lightningd.c
- lightningd/test/run-find_my_abspath.c
- tests/test_invoices.py
- wallet/invoices.c
- wallet/invoices.h
- wallet/wallet.c
We need to set up indexes and ld->wallet before expiring invoices at startup, otherwise we can get a null dereference when invoice startup expires invoices immediately:
```
0x7f271a18d08f ??? /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x5581a27dc082 wait_index_increment lightningd/wait.c:112
0x5581a27e331a invoice_index_inc wallet/invoices.c:738
0x5581a27e3dfe invoice_index_update_status wallet/invoices.c:775
0x5581a27e3ea3 trigger_expiration wallet/invoices.c:185
0x5581a27e3f47 invoices_new wallet/invoices.c:134
0x5581a27e8a2c wallet_new wallet/wallet.c:121
0x5581a27b08b5 main lightningd/lightningd.c:1082
```
Fixes: #6457
Changelog-None: introduced in master
> wallet: fix crash on startup with expired invoices.

- channeld/channeld.c
STATUS_FAIL_MASTER_IO is correct here (and what we use elsewhere): STATUS_FAIL_INTERNAL_ERR prints a worrying backtrace:
```
0x5606a2992bdf send_backtrace
0x5606a299ccab status_failed
common/status.c:221
0x5606a297f4f1 master_wait_sync_reply
channeld/channeld.c:978
0x5606a29826ef send_commit
channeld/channeld.c:1379
0x5606a299d06a timer_expired
common/timeout.c:62
0x5606a2984fcd main
channeld/channeld.c:4046
0x7fd97dd9ed8f __libc_start_call_main
../sysdeps/nptl/libc_start_call_main.h:58
0x7fd97dd9ee3f __libc_start_main_impl
../csu/libc-start.c:392
0x5606a297e724 ???
???:0
0xffffffffffffffff ???
???:0
```
Fixes: #6221
Reported-by: https://github.com/joelklabo
> channeld: don't backtrace if master closes during sync read.

- ccan/README
- ccan/ccan/base64/base64.c
```
ccan/ccan/base64/base64.c:34:10: error: result of comparison of constant 255 with expression of type 'int8_t' (aka 'signed char') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
if (ret == (char)0xff) {
~~~ ^  ~~~~~~~~~~
ccan/ccan/base64/base64.c:44:57: error: result of comparison of constant 255 with expression of type 'const signed char' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
return (maps->decode_map[(const unsigned char)b64char] != (char)0xff);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
```
Reported-by: Christian Decker
> CCAN: update for base64 compile fix on ARM.

- channeld/channeld.c
- channeld/splice.c
- channeld/splice.h
Since it's only for transitory splicing info, the new name makes sense.
```
cc channeld/channeld.c
In file included from channeld/channeld.c:23:
./channeld/splice.h:37:8: error: redefinition of 'splice'
struct splice {
^
/usr/include/sys/socket.h:140:8: note: previous definition is here
struct  splice {
^
```
Reported-by: @grubles
Fixes: #6486
> channeld: replace `struct splice` with `struct splicing` for OpenBSD.

- plugins/renepay/pay.c
- plugins/renepay/pay_flow.h
Ran into this issue compiling master on Mac
Fixes #6491
> renepay: Use macros instead of manual format types

- Makefile
Steps to Reproduce: Run `sudo make install` then again `sudo make install` without uninstalling plugins in between. First command will install the plugin at `/usr/local/libexec/c-lightning/plugins/clnrest` as expected but the second command will install it inside the first folder like `/usr/local/libexec/c-lightning/plugins/clnrest/clnrest`.
Fix: Check and delete if the folder already exists.
> makefile: py plugins installed twice with `make install`

- .github/workflows/ci.yaml
- lightningd/options.c
- tests/utils.py
Splicing should work automatically on v1 or v2 channels so this requirement isn’t needed.
Changelog-None
> splicing: Remove dependency on experimental_dual_fund

- doc/index.rst
> docs: try to fix up readthedocs.io, so it has the latest man pages, but points to docs.corelighting.org for the rest

- plugins/clnrest/requirements.txt
Bug fix: pip install from plugins/clnrest/requirements.txt was unable to find "not yet released" pyln-proto version 23.08.
> plugin/clnrest: Downgrading pyln-proto version from 23.08 to 23.5.2

- .github/CODEOWNERS
The VLS team have asked to be pinged whenever there is a breaking change in the signer interface, and this is a good first approximation. I'll try to stay on top of other breaking changes and ping them accordingly.
Changelog-None
> meta: Adjust `CODEOWNERS` file

- contrib/docker/Dockerfile.tester
- contrib/docker/scripts/setup.sh
- plugins/bcli.c
Less than 22 is obsolete anyway, so we should increment this from 16.0 at least!
Closes: #6234
Changelog-None
> plugins/bcli: update minimum required bitcoind version.

- lightningd/peer_htlcs.c
- tests/test_closing.py
This can be cause by TCP/Tor silently disconnecting so we don't receive messages, so it's best to force a reconnect.
Fixes: #6506
> Disconnect on channeld death due to HTLC addition timeout

- lightningd/configs.c
Apparently MacOS doesn't always have fdatasync, so use fsync.  Even more importantly check whether it succeeds!
Fixes: #6516
> lightningd: use fsync not fdatasync.

- doc/lightning-listclosedchannels.7.md
- doc/lightning-listpeerchannels.7.md
- doc/lightning-listpeers.7.md
- doc/schemas/listclosedchannels.schema.json
- doc/schemas/listpeerchannels.schema.json
- doc/schemas/listpeers.schema.json
Change `False` to `True` in the description of the field `private` for the responses of the following calls:
- `listpeers`
- `listpeerchannels`
- `listclosedchannels`
New description is: "if True, we will not announce this channel"
> Fix a typo in the description of field `private`

- plugins/src/lib.rs
See: https://github.com/bitcoindevkit/bdk/issues/1047#issuecomment-1660645669
In general, futures produced by most libraries in the ecosystem of Rust, and bounds placed on users of famous runtimes like tokio and its spawn method all lack Sync requirements.
Because of this, anyone who creates a callback using any sort of library that returns a non-Sync future (which most libraries fit this description) inside of it will get some cryptic error messages (async error messages still leave a lot to be desired).
Removing these Sync requirements will make the library more useful.
> Fix: Remove Sync requirements on Futures returned in the Rust plugin library.

- plugins/bcli.c
We've stomped errno, so if exec fails we don't get a reliable result:
```
2023-08-07T17:58:45.713Z **BROKEN** plugin-bcli: bitcoin-cli exec failed: Bad file descriptor
```
See: #6529
> plugins: fix error report from bitcoin-cli exec failure.

- gossipd/gossip_store.c
Don't know how this is happening, but it is not harmful to ignore it for now.
Fixes: #6531
Changelog-None
> gossipd: ignore redundant node_announcement in gossip_store.

- gossipd/routing.c
- tests/test_gossip.py
When loading from the gossip store under a particular scenario:
channel announcement
node announcement
node announcement (spam)
channel update
There should be two node announcements pending the first channel update.  This case was not handled and the spam announcement was overwriting the broadcastable announcement causing gossipd to lose track of it.  The answer is to properly load the spam announcement alongside the broadcastable one once the channel is created.
Fixes: #6531
> Double nannounce patch

- plugins/renepay/pay.c
It's not there if it's a local error:
```
{
"code": 202,
"message": "Parsing '{message:%,data:{erring_index:%,failcode:%,raw_message:': object does not have member raw_message"
}
```
Reported-by: https://github.com/daywalker90
Fixes: #6553
Also fixes a double-free crash on return from adding gossip.
> renepay crash fixes: don't require raw_message in error reply, don't double-free

- plugins/renepay/test/run-mcf.c
We cannot carry pointers into the gossmap across localmod addition or removal.
We didn't notice because the map->chan_arr is not normally resized, but if we change gossmap.c line 689 to only allocate 1 to start, we see this:
```
VALGRIND=1 valgrind -q --error-exitcode=7 --track-origins=yes --leak-check=full --show-reachable=yes --errors-for-leak-kinds=all plugins/renepay/test/run-mcf > /dev/null
==2349744== Invalid read of size 4
==2349744==    at 0x1788C2: gossmap_chan_scid (gossmap.c:558)
==2349744==    by 0x1872A2: get_chan_extra_half_by_chan (flow.c:346)
==2349744==    by 0x187797: remove_completed_flow (flow.c:488)
==2349744==    by 0x187927: remove_completed_flow_set (flow.c:518)
==2349744==    by 0x18DF4D: main (run-mcf.c:393)
==2349744==  Address 0x4b80f38 is 88 bytes inside a …
```
> plugins/renepay/test: fix access-after-free.

- plugins/topology.c
We have a report that LND said our (unannounced) channel was disabled, so we didn't use it for routehints.  We're better off ignoring that in this case (if the peer is actually not connected, the routehint code will check that and ignore anyway).
Fixes: #6555
Changelog-Changed: pay: use channels in routehints even if peer says they're "disabled" (LND compat)
> pay: still use channels for routehints even if peer says it's disabled.

- channeld/channeld.c
We also shouldn’t be announcing channels or commitments when we have requested for `stfu` mode but are waiting for our apeer.
Changelog-None
> splice: quieter in more cases

- cli/lightning-cli.c
- common/configdir.c
- common/configdir.h
- devtools/checkchannels.c
- tests/test_misc.py
This should provide the default help message and exit, but freeing pointers passed to the default config setup lead to a segmentation fault when help tries to provide usage and triggers the callback.
```
Program received signal SIGSEGV, Segmentation fault.
__strlen_generic () at ../sysdeps/aarch64/multiarch/../strlen.S:98
98	../sysdeps/aarch64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_generic () at ../sysdeps/aarch64/multiarch/../strlen.S:98
#1  0x000000555555b9f0 in opt_show_charp (
buf=0x7ffffff0a0 "\"Usage: /usr/local/bin/lightning-cli <command> [<params>...]\n--conf=<file>     \"...", len=80, p=0x7ffffff150)
at ccan/ccan/opt/helpers.c:216
#2  0x000000555555d9b4 in add_desc (
base=0x555557dff8 "Usage: /usr/local/bin/lightning-cli <command> …
```
> cli: don't crash when there's no argument

- doc/developers-guide/plugin-development/hooks.md
Just some missing `,` and some whitespace changes.
Changelog-None
> doc: Drive-by fixes of JSON examples in hooks.md

- lightningd/channel.c
- lightningd/channel.h
- lightningd/channel_control.c
- lightningd/peer_control.c
- lightningd/peer_htlcs.c
- tests/test_splicing.py
- wallet/wallet.c
Don’t send the funding spend to onchaind if we detect it in inflights (aka. a splice). While we already prevented onchaind_funding_spent from being called directly, the call to wallet_channeltxs_add meant onchaind_funding_spent would be called *anyway* on restart. This is now fixed.
Additionally there was a potential for a race problem depending on the firing order of the channel depth and and funding spent events.
Instead of requiring these events fire in a specific order, we make a special “memory only” inflight object to prevent the race regardless of firing order.
Fixes #6533
> splice: prevent splice going to onchaind & race prevention

- lightningd/plugin.c
- lightningd/plugin_control.c
- tests/plugins/badinterp.py
- tests/test_plugin.py
It started with "plugin still in listplugins after it fails to exec" and escalated to "we can kill all our processes"!
> Plugin crash fixes!

- common/gossmap.c
Doesn't happen on x86, but struct gossmap_chan defines:
```
u32 private: 1;
u32 plus_scid_off: 31;
```
And complains when we initialize plus_scid_off and access it later:
```
VALGRIND=1 valgrind -q --error-exitcode=7 --track-origins=yes --leak-check=full --show-reachable=yes --errors-for-leak-kinds=all plugins/renepay/test/run-mcf > /dev/null
==186886== Conditional jump or move depends on uninitialised value(s)
==186886==    at 0x10076388: chan_iter (gossmap.c:1098)
==186886==    by 0x100797F3: gossmap_next_chan (gossmap.c:1112)
==186886==    by 0x1008C5AF: main (run-mcf.c:309)
==186886==  Uninitialised value was created by a heap allocation
==186886==    at 0x40F0A44: malloc (vg_replace_malloc.c:431)
==186886==    by 0x10072BAF: allocate (tal.c:256)
==186886==    by 0x100737A7: …
```
> gossmap: fix false valgrind uninitialized error on arm64, ppc.

- plugins/renepay/flow.c
There's a fascinating bug report which suggests this happens on local channels, implying spendable_msat is wrong?
See-also: #6567
Changelog-None: renepay new in this release.
> renepay: reduce minimum "known" if it proves incorrect.

- common/channel_type.c
- common/channel_type.h
- lightningd/opening_control.c
- openingd/dualopend.c
- openingd/openingd.c
- openingd/openingd_wire.csv
We were rejecting zeroconf channels outright, before checking the return value of the `openchannel` hook, as that was available only slightly later. Between CLN nodes that worked because we don't actually use featurebit 50 in the `channel_type`, making it optional, and we then just send `channel_ready` over when we're... well... ready.
`lnd` on the other hand is explicit in its expectations and actually uses the mandatory zeroconf bit, which we would reject because at the verification time the hooks hadn't been called yet, and therefore we could not possibly know if we'll accept it or not (the default `mindepth=1` meant we never accepted zeroconf right out of the gate).
> openingd: Defer zeroconf check until we called the `openchannel` hook

- plugins/renepay/payment.c
```
Aug 18 13:45:13  lightningd: 0x7fa921f8ffcf ???
Aug 18 13:45:13  lightningd:         ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
Aug 18 13:45:13  lightningd: 0x55b3bb54e6d3 pay_flow_finished_adding_gossip
Aug 18 13:45:13  lightningd:         plugins/renepay/pay_flow.c:675
Aug 18 13:45:13  lightningd: 0x55b3bb54af25 addgossip_done
Aug 18 13:45:13  lightningd:         plugins/renepay/pay.c:171
```
The assert we fail is almost certainly due to the flow being freed:
```
struct pf_result *pay_flow_finished_adding_gossip(struct pay_flow *pf)
{
assert(pf->state == PAY_FLOW_FAILED_GOSSIP_PENDING);
```
Reported-by: https://github.com/daywalker90
Fixes: #6567
> plugins/renepay: don't free waiting-for-addgossip flow!

- lightningd/peer_control.c
- tests/test_plugin.py
1. subd gratuitous restart during tests
2. timeout during autoclean
Sometimes valgrind on these lowend boxes makes things *really* slow cf. our pytest framework...
> More flake test fixes

- plugins/renepay/debug.h
- plugins/renepay/flow.c
- plugins/renepay/flow.h
- plugins/renepay/pay.c
- plugins/renepay/pay_flow.c
- plugins/renepay/pay_flow.h
- plugins/renepay/payment.c
- plugins/renepay/payment.h
- plugins/renepay/uncertainty_network.c
First commit is #6592 the rest is cleanups to try to get a more complete view of what's happening (and present it to the person running the command).
> Make renepay output cleaner so we can debug issues

- plugins/renepay/uncertainty_network.c
```
Flow 391: amount=23528000msat prob=0.000 fees=1023msat delay=140 path=-2471854x37x4/1(min=max=23528783msat)->-2414928x98x0/0->
Flow 391: Failure of 23529023msat for 2471854x37x4/1 capacity [23528783msat,23528783msat] -> [23528783msat,23528783msat]
```
We added fees and went over capacity!  This screams of a deeper logic bug, but renepay is experimental and it's release day so hack around it for now...
Reported-by: https://github.com/daywalker90
See: #6599
> renepay: hack in workaround spendable reduction for release.

- plugins/clnrest/clnrest.py
On mac the clnrest plugin hangs on log messages, causing it to never run.
This guide suggests switching to fork’ing instead of spwan’ing https://superfastpython.com/multiprocessing-common-errors/#Error_2_print_Does_Not_Work_In_Child_Processes
Switching to fork fixes the hang on Mac.
Changelog-None
> clnrest: Change process method to fork

- .github/workflows/ci.yaml
CI was always failing on `master` and I was wondering why :-)
Changelog-None
> gci: Do not try to rebase if we're on master already

- Makefile
> Use python3 instead of python in Makefile

- Makefile
- configure
- doc/Makefile
Riffs on #6618 which switched python->python3, this should do either.
> configure: don't assume python3, create $PYTHON var.

- plugins/renepay/pay.c
- plugins/renepay/pay_flow.c
- tests/test_renepay.py
- Fix cltv usage across the path.
- Make shadow code work.
> Renepay fixes

- plugins/clnrest/utilities/rpc_routes.py
- plugins/clnrest/utilities/shared.py
OpenAPI readme always includes `content-type: application/json` header, even when body parameters are empty. But the server expects data if the content-type has been sent. This results in a "Server Error" response for non-param requests from readme doc. This only affects readme requests as it is designed to send the header by default.
Changelog-None
> plugin/clnrest: do not read json payload if data length is zero

- cln-rpc/src/primitives.rs
I don't know if this can be problematic, but it would be nice to have so i can do things like comparison, `sort_by(|x| x.scid)` or scids as keys in `HashMap`/`BTreeMap` without converting them to `String` first.
> [cln-rpc]: add Eq, PartialOrd, Ord, Hash to ShortChannelId

- doc/lightning-checkrune.7.md
- doc/schemas/checkrune.request.json
- lightningd/runes.c
- lightningd/runes.h
- plugins/clnrest/README.md
- plugins/clnrest/clnrest.py
- plugins/clnrest/utilities/rpc_routes.py
- plugins/clnrest/utilities/shared.py
- tests/test_runes.py
- wallet/test/run-db.c
- wallet/test/run-wallet.c
~Builds on #6617~ (Rebased on master)
Also tighten our rune checking on our own runes which were generated from other code (a theoretical possibility), and make sure we only add valid restrictions...
> Tweak checkrune API (nodeid isn't required) and update docs.

- tools/build-release.sh
This PR aims to improve the verification procedure of the `build-release.sh` script when called with `--verify`. The following things are changed:
1. The script assumes that we have a file called `SHA256SUMS-<version>` in the root of the repository. 
We add a check if the file exists and that prints a hint where to get the checksum file if it does not.
2. The script copies the checksum for the Fedora build to the own checksum file but overrides an existing line.
We change the way we copy the sum to append it on top of the file.
3. The verification is done by comparing the release captains checksum file with the locally generated checksum file. This is fine, but if some sum is off we may want to have a hint which it is directly without having to compare the files ourselves.
We add a …
> Improve `build-release.sh` verification procedure

- tests/test_opening.py
- wallet/reservation.c
This is #6657 with a test added, Changelog line and git description, and a final neatening patch (I couldn't push to @TonyGiorgio 's branch!)
Closes: #6657 
Fixes: https://github.com/ElementsProject/lightning/issues/6183
> Update for PR 6657: fix fundchannel infinite loop with tiny UTXOs

- Makefile
We didn't want a rule to generate config.vars, since user should run configure manually with their desired options.  However, we do want to be able to *refresh* it, because otherwise, if we need a new configuration var for our Makefile, it won't get refreshed:
```
$ make
CC: cc -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wshadow=local -std=gnu11 -g -fstack-protector-strong  -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/build-x86_64-linux-gnu/libbacktrace-build -I external/libsodium/src/libsodium/include -I external/libsodium/src/libsodium/include/sodium -I …
```
> Makefile: regnerate config.vars if configure changes (recently PYTHON var)

- .github/workflows/ci.yaml
- conftest.py
This just adds a simple collection of test metadata (disabled by default, but enabled on CI since we don't want to snoop on devs). This is used to collect the stability or lack thereof (flaky tests) and be able to re-enable the `--force-flaky` flag on CI.
IMHO there is no added value in forcing devs to watch their CI and rerunning failed ones blindly because of flaky tests.
My goal is to track flakyness on `master` as groundtruth, and then open issues to address flaky tests based on that information. We still need to determine what percentage of flakyness is acceptable but we can do so better once we have some real data.
There is some concern that we end up papering over real issues, however I'd argue that training devs to just hit rerun without looking at the issue is worse.
> ci: Track flakyness of tests by collecting them on a server

- .github/workflows/ci.yaml
CI was broken due to an outdated repository cache, pointing to a yanked file.
Changelog-None
> gci: Update apt cache before installing

- Makefile
We do not, in fact, require Python to build, so we should still work after `make distclean`.
Fixes:  #6536
> Makefile: don't delete python-generated files in distclean.

- tests/test_renepay.py
Sometimes we don't shadow because it would break our budget:
```
def test_shadow(node_factory):
'''Make sure we shadow correctly.'''
l1, l2, l3 = node_factory.line_graph(3,
wait_for_announce=True,
opts=[{},
{'fee-base': 2000, 'fee-per-satoshi': 20, 'cltv-delta': 20},
{'fee-base': 3000, 'fee-per-satoshi': 30, 'cltv-delta': 30}])
for i in range(20):
inv = l2.rpc.invoice(123000, f'test_renepay{i}', 'description')['bolt11']
details = l1.rpc.call('renepay', {'invstring': inv})
assert details['status'] == 'complete'
assert details['amount_msat'] == Millisatoshi(123000)
assert details['destination'] == l2.info['id']
>           line = l1.daemon.wait_for_log("No MPP, so added .*msat shadow fee")
tests/test_renepay.py:51:
```
```
lightningd-1 2023-09-12T05:08:39.699Z UNUSUAL plugin-cln-renepay: No …
```
> pytest: fix renepay test_shadow flake.

- Dockerfile
- contrib/docker/Dockerfile.arm64v8
This PR removes deprecated GMP dependency since libsecp256k1 provides all the necessary functionality.
Enjoy faster build!
> Dockerfile: Remove deprecated GMP dependency

- Dockerfile
The cln-regtest-demo tries to run `bitcoind` but this docker image only contains `bitcoin-cli`, this change to include `bitcoind` seems innocent enough.
I pushed a "test" version here https://hub.docker.com/layers/blockstream/lightningd/ep-v23.08/images/sha256-d8d8093bea4a3c028eee2c16ac27ffb41981ae79d366fc355c7fe54321e66b27?context=explore which is currently powering cln-regtest-demo, the size difference between current `elementsproject/lightning` is roughly 30MB.
> docker: make available bitcoind binary

- configure
There was a typo in the `case` pattern.
> `configure`: recognize `--disable-ub-sanitizer` option

- wallet/wallet.c
I think this gave me a lot of problems while testing splicing. Don't ask me how I found it :-)
> Only 3 question marks for 4 variables

- .github/scripts/install-bitcoind.sh
- .github/workflows/ci.yaml
- tests/plugins/badestimate.py
Turns out we stopped using the `TEST_NETWORK` envvar and relied exclusively on `config.vars`. This broke the `liquid-regtest` tests on GCI...
> ci: Unbreak the liquid-regtest run on Github Actions

- Makefile
In its default mode, `xargs` interprets any whitespace as a delimiter, and it interprets single and double quotes and backslashes specially. This can play havoc when fed by tools that don't escape these special characters in their output.
Fortunately, `xargs` (at least the GNU and macOS versions of it) has a `-0` option that changes the behavior so that only NUL characters act as delimiters, and no other characters have any special meaning. Use this option consistently to avoid any nasty surprises.
Note that `git-ls-files` has a `-z` option that causes it to terminate filenames on output with a NUL character instead of a newline, and `grep` has a `-z` option that causes it to operate on NUL-terminated records rather than on lines. Use these options together with `xargs -0`.
Note: This …
> `Makefile`: use `xargs -0` consistently

- .github/workflows/crate-io.yml
- Cargo.lock
This includes the auto-publish the release on the crate-io
and also include a rust fix (see commit for details)
I do not know how @cdecker feals about dry-run when we merge a PR
this allow us to make sure that we do not fails on release
but it can be challenging during development.
Happy to drop it if we are not sure if this is really useful
> ci: autopublish rust crates on tag event

- tools/build-release.sh
Removed `bin-` while copying Fedora sums from release captain's file. Sums are saved as `clightning-$VERSION-Fedora-28-amd64.tar.gz` not as `clightning-$VERSION-bin-Fedora-28-amd64.tar.gz`
> tools: Fixed release verify typo

- doc/lightning-createrune.7.md
- lightningd/runes.c
- tests/test_plugin.py
- tests/test_runes.py
Changelog-Changed: JSON-RPC: `checkrune` `rate` restriction is slightly stricter (exact division of time like `per`)
> runes: Reimplement `rate` in terms of `per`

- lightningd/runes.c
- tests/test_runes.py
- wallet/db.c
- wallet/wallet.c
- wallet/wallet.h
Changelog-Fixed: runes: use runes table `id` instead `runes_uniqueid` from `vars` because it returns incorrect unique id if rune/s migrated from datastore.
Issue (#6696):
The issue occurs when user saves the rune (created by commando-rune) in the datastore with v23.02 and then upgrades the DB with v23.08. This upgrade calls migrate_datastore_commando_runes function to migrate runes from datastore to runes table. But it does not increment runes_uniqueid of vars table. So when user creates a new rune, CLN gets old next_unique_id and fails with UNIQUE_ID constraint error.
This issue effects Umbrel's users and users who saved their runes from older version in the datastore.
Solution 1:
- Add another migration function to recalculate `runes_uniqueid` and update vars table.
- Update …
> runes: Use next id from runes table not `runes_uniqueid` from `vars`

- lightningd/dual_open_control.c
We didn't apply the inflight to the channel struct before asserting, so we can break test_rbf_non_last_mined:
```
lightningd: lightningd/dual_open_control.c:981: dualopend_tell_depth: Assertion `bitcoin_txid_eq(&channel->funding.txid, txid)' failed.
```
> lightningd: fix assertion when funding depth changes fast.

- channeld/channeld.c
- closingd/closingd.c
- common/memleak.c
- common/memleak.h
- common/status.c
- common/status.h
- connectd/connectd.c
- gossipd/gossipd.c
- hsmd/hsmd.c
- lightningd/memdump.c
- onchaind/onchaind.c
- onchaind/test/run-grind_feerate-bug.c
- onchaind/test/run-grind_feerate.c
- openingd/dualopend.c
- openingd/openingd.c
- plugins/libplugin.c
There are two reasons a memleak can be hard to find even when we show where it's allocated:
1. That pointer is overridden somewhere without being freed.
2. The pointer is tal_steal() onto something else, which doesn't free it.
We can't do much about the former case, but we can definitely do the latter!
Changelog-None: developer infrastructure
> Print steal tracking when a memleak is detected

- contrib/pyln-client/pyln/client/lightning.py
- doc/Makefile
- doc/index.rst
- doc/lightning-addpsbtoutput.7.md
- doc/lightning-splice_init.7.md
- doc/schemas/addpsbtoutput.request.json
- doc/schemas/addpsbtoutput.schema.json
- tests/test_splicing.py
- tests/test_wallet.py
- wallet/reservation.c
Note: This now depends on PR #6677
New `addpsbtoutput` command for creating a PSBT that can receive funds to the on-chain wallet.
> addpsbtoutput: New onchain command for PSBT output and splice_out tests

- channeld/channeld.c
A few little stylistic things were bugging me when reading through the splice code so I cleaned them up.
ChangeLog-None
> splice: minor code cleanups

- contrib/startup_regtest.sh
Without `developer` option, after compiling CLN and sourcing `contrib/startup_regtest.sh`, if we try to start 2 nodes on regtest running the command `start_ln` we get the following error:
```
lightningd: Config file /tmp/l1-regtest/config line 6: dev-fast-gossip: requires --developer
...
lightningd: Config file /tmp/l2-regtest/config line 6: dev-fast-gossip: requires --developer
```
> contrib: add `developer` option to config file in startup_regtest.sh.

- lightningd/runes.c
- tests/test_runes.py
> runes: fix `checkrune` when `method` parameter is the empty string.

- plugins/grpc-plugin/src/main.rs
- tests/test_cln_rs.py
When we don't set `grpc-port` option, the `cln-grpc` plugin is not started.  So, we shouldn't generate certificates in that case.
> cln-grpc: do not generate cerficates when no autostart.

- lightningd/lightningd.c
- tests/test_misc.py
As a node matures and is no longer new, it can take some time 
to determine which version of `cln` it's running.
To address this, we now display the version earlier. This ensures 
that even in the event of a crash, we're aware of the running version.
```
(cln-meta-project-py3.11) ➜  lightning git:(macros/log-version) ✗ ./lightningd/lightningd
2023-10-12T19:21:00.899Z INFO    lightningd: lightningd v23.08.1-209-gae94be4-modded
2023-10-12T19:21:00.994Z INFO    lightningd: Creating configuration directory /home/vincent/.lightning/bitcoin
2023-10-12T19:21:01.235Z INFO    lightningd: Creating database
2023-10-12T19:21:01.279Z UNUSUAL hsmd: HSM: created new hsm_secret file
Could not connect to bitcoind using bitcoin-cli. Is bitcoind running?
Make sure you have bitcoind running and that …
```
> lightnind: print the version of cln early

- common/daemon.c
During our development, we modified the way
we report backtraces.
On a minimal configuration in OpenBSD, it seems that we no longer compile from commit a9f26b7d07 because
our conditional code is buggy.
With the following compiler
```
vultr# cc -v
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.3
Thread model: posix
InstalledDir: /usr/bin
```
We have the following error
```
cc common/channel_id.c
cc common/daemon.c
common/daemon.c:218:2: error: implicit declaration of function 'add_steal_notifiers' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
add_steal_notifiers(NULL);
^
1 error generated.
gmake: *** [Makefile:298: common/daemon.o] Error 1
```
Reported-by: @grubles
Fixes https://github.com/ElementsProject/lightning/issues/6701
> build: fix compilation issue on OpenBSD

- contrib/pyln-testing/pyln/testing/utils.py
This makes the pay helper function being able to route a payment using the optional `route` paramter that defaults to `False`.
I added this, as some plugins maintained their own version of `pay` that needed routed payment helper.
Changelog-None
> pytests: make pay helper able to route (optionally)

- lightningd/runes.c
- plugins/clnrest/utilities/shared.py
- tests/test_runes.py
This reverts and fixes #6759.  The root problem is that clnrest was specifying method as the empty string, instead of not specifying it at all.
With that changed, the previous behavior is correct.  @tonyaldon
> Real checkrune fix

- lightningd/channel_control.c
Changelog-None: introduced since release
> Closingd invalid fix

- common/hsm_version.h
- hsmd/hsmd.c
- hsmd/hsmd_wire.csv
- hsmd/libhsmd.c
- openingd/dualopend.c
- openingd/openingd.c
Originally VLS used hsmd_ready_channel as an early call during channel setup, but later the BOLT-2 spec changed the name of funding_locked to channel_ready.
This is very confusing because the hsmd_ready_channel is not directly related to the new channel_ready.
This commit is renaming the hsmd_ready_channel to hsmd_setup_channel.
Fixes: https://github.com/ElementsProject/lightning/issues/6717
Suggested-by: @ksedgwic
> hsmd: name the hsmd_ready_channel to hsmd_setup_channel

- channeld/channeld.c
- hsmd/libhsmd.c
The signer needs to know when the splice operation starts and the splice parameters for each splice transaction candidate.
The channel establishment v2 (dual funding) code path already notifies the signer via the hsmd API hsmd_ready_channel calls However, the splicing code path does not.
Fixes: https://github.com/ElementsProject/lightning/issues/6723
Suggested-by: @devrandom
Co-Developed-by: @devrandom
Co-Developed-by: Ken Sedgwick <ken@bonsai.com>
> splice: signer must be informed of splice params

- connectd/multiplex.c
- tests/test_pay.py
This time, a real bugfix involving tx_abort!
> CI: more flake fixes

- connectd/connectd.c
- connectd/connectd.h
- connectd/connectd_wire.csv
- connectd/multiplex.c
- connectd/multiplex.h
- contrib/pyln-client/pyln/client/plugin.py
- doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
- doc/lightning-sendcustommsg.7.md
- lightningd/connect_control.c
- lightningd/plugin.c
- lightningd/plugin.h
- tests/plugins/allow_even_msgs.py
- tests/test_misc.py
Closes:  #4963 (ancient)
Closes: #4960
> Allow even unknown messages, by registration, and allow sending them

- bitcoin/psbt.c
- bitcoin/psbt.h
- bitcoin/test/run-tx-bitcoin_tx_2of2_input_witness_weight.c
- common/psbt_open.c
- lightningd/dual_open_control.c
During the changeset calculation after the `openchannel2_sign` hook.
So this commit patches the problem with the following change:
- Addressed an issue where `psbt_get_changeset` was modifying the original PSBT unnecessarily.
- This modification led to problems with a different hsmd, as referenced in [Issue #6672](https://github.com/ElementsProject/lightning/issues/6672).
- Noted a potential optimization where only a subpart of the PSBT needs to be cloned, as the mutation is specific to inputs.
Fixes: https://github.com/ElementsProject/lightning/issues/6672
> psbt: fix PSBT mutation in the changeset

- lightningd/anchorspend.c
- lightningd/bitcoind.c
- lightningd/bitcoind.h
- lightningd/chaintopology.c
- lightningd/chaintopology.h
- lightningd/channel_control.c
- lightningd/dual_open_control.c
- lightningd/invoice.c
- lightningd/onchain_control.c
- lightningd/options.c
- lightningd/peer_control.c
- lightningd/plugin.c
- lightningd/plugin.h
- lightningd/plugin_hook.c
- lightningd/test/run-invoice-select-inchan.c
- tests/test_plugin.py
- wallet/test/run-wallet.c
- wallet/walletrpc.c
These were pre-work I had to do when cleaning anchors.  The plugin code was confusing, so I unified the "forwarding a JSON request" vs "our own JSON request", especially handling the plugin dying during these (we didn't handle the latter case at all, we would deref freed memory).
I then go on to refine our broadcast interfaces, since we're going to need a more powerful mechanism for using anchors on the peer's commitment txs.
> Plugin and broadcast cleanups

- connectd/multiplex.c
- tests/test_misc.py
Make sure plugin has got message to connectd before sending!
```
def test_even_sendcustommsg(node_factory):
l1, l2 = node_factory.get_nodes(2, opts={'log-level': 'io',
'allow_warning': True})
l1.connect(l2)
msg = hex(43690)[2:] + ('ff' * 30) + 'bb'
l1.rpc.sendcustommsg(l2.info['id'], msg)
l2.daemon.wait_for_log(r'\[IN\] {}'.format(msg))
l1.daemon.wait_for_log('Invalid unknown even msg')
wait_for(lambda: l1.rpc.listpeers(l2.info['id'])['peers'] == [])
l1.connect(l2)
l2.rpc.plugin_start(os.path.join(os.getcwd(), "tests/plugins/allow_even_msgs.py"))
l1.rpc.sendcustommsg(l2.info['id'], msg)
l2.daemon.wait_for_log(r'\[IN\] {}'.format(msg))
>       l2.daemon.wait_for_log(r'allow_even_msgs.*Got message 43690')
tests/test_misc.py:3623: 
...
>                   raise TimeoutError('Unable to find …
```
> pytest: fix flake in test_even_sendcustommsg

- cln-rpc/src/primitives.rs
It is recommend to implement `Display` instead of [ToString](https://doc.rust-lang.org/std/string/trait.ToString.html)
This also provides `.to_string()` but has the advantage that things like `info!("{}", scid)` just work without `.to_string()`
> [cln-rpc]: switch from ToString to Display for ShortChannelId

- channeld/channeld.c
- channeld/channeld_wire.csv
- contrib/pyln-testing/pyln/testing/utils.py
- gossipd/gossip_generation.c
- gossipd/gossipd_wire.csv
- gossipd/test/run-check_node_announcement.c
- gossipd/test/run-crc32_of_update.c
- lightningd/channel_control.c
- lightningd/gossip_control.c
- lightningd/gossip_control.h
- lightningd/peer_control.c
- lightningd/peer_htlcs.c
- lightningd/test/run-invoice-select-inchan.c
- wallet/test/run-wallet.c
This is only the beginning of the cleanup I wanted to perform, but the rest requires that gossipd no longer handle private gossip, which will not be in this release.
Nonetheless, this removes some fairly complex code, so nice to have: channeld used to make the updates, and tell lightningd to tell gossipd, and now lightningd does it itself.
> Simplify use of channel_update

- lightningd/plugin.c
- lightningd/plugin_hook.c
```
Already in transaction from lightningd/plugin.c:727
```
There are two callers, and one didn't disable transactions, so do it in plugin_exclusive_loop.
> lightningd: don't re-enter transaction if we have to call plugin_exclusive_loop

- bitcoin/psbt.c
- bitcoin/psbt.h
- wallet/walletrpc.c
Fixes https://github.com/ElementsProject/lightning/issues/6764
This is an alternate approach to #6766 .  By combining the signed psbt back into the
pre-signed psbt any metadata that a resource constrained signer (VLS) strips (`input.utxo`) will be restored.
> Restore any missing psbt metadata that resource constrained signers strip

- channeld/channeld.c
Under certain conditions, when splicing a new channel quickly enough, an old channel announcement would emit *after* `mutual_splice_lock` and *before* announcement signature exchange.
Since the original channeld wouldn’t start the announcement timer until signatures were exchagned, this wasn’t an issue before.
Now splicing enables us to go from having announcement sigs to losing them, so we have to be prepared for this case.
Fixes: https://github.com/ElementsProject/lightning/issues/6810
Changelog-None
> splice[FLAKE]: stale channel announcement fix

- channeld/channeld.c
- tests/test_splicing.py
* Regression test added for Issue #6572 (issuecomment-1730808863) w/stuck HTLC
* `check_balance` adjusted to calculate pending HTLCs explicitly
* Test confirmed to fail prior to PR #6713
ChangeLog-Fixed: Issue splicing with pending / stuck HTLCs fixed.
> Splice: Better balance checking

- plugins/src/lib.rs
Under some circumstances we may want to not log to `lightningd` directly, but rather configure the logging ourselves. This is useful for example if we want to use `tracing` and `tracing-subscriber` to add custom handling, or add opentelemetry span tracing.
Changelog-Changed: cln-plugin: Suppress internal logging handler via `with_logging(false)`
> cln-plugin: Make logging optional

- .github/workflows/crate-io.yml
- conftest.py
- contrib/pyln-grpc-proto/Makefile
- contrib/pyln-grpc-proto/pyln/grpc/__init__.py
- plugins/Cargo.toml
- plugins/grpc-plugin/Cargo.toml
- poetry.lock
- pyproject.toml
- tests/test_gossip.py
- tests/test_pay.py
- tests/test_plugin.py
- tests/test_splicing.py
The signal vs. noise ratio of the CI is currently abysmal, due to flaky tests that prevent runs from completing unless we trigger re-runs over and over again. The following tests have been marked as `@unittest.skip()` to regain some control.
If you were assigned to a task to fix the test that is because you were the main author according to `git blame`. If you have someone else that is better suited to fix the test and get the test coverage back please ping them in the appropriate issue, but don't just unassign yourself. Test coverage is important, and a flaky or skipped test could be hiding a real issue.
Disabled tests (flakyness in percentage over the last 30 days on `master` only to exclude real failures due to code changes):
- `test_commit_crash_splice` (28/174)
- …
> pytest: Mark flaky tests as skip and open issues for each of them

- channeld/channeld.c
- channeld/channeld_wire.csv
- channeld/commit_tx.c
- channeld/commit_tx.h
- channeld/full_channel.c
- channeld/full_channel.h
- channeld/test/run-commit_tx.c
- channeld/test/run-full_channel.c
- devtools/mkcommit.c
- lightningd/anchorspend.c
- lightningd/anchorspend.h
- lightningd/chaintopology.c
- lightningd/channel_control.c
- lightningd/peer_control.c
- lightningd/peer_htlcs.c
- lightningd/test/run-invoice-select-inchan.c
- tests/test_closing.py
- wallet/db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
- wallet/wallet.h
~Based on #6751~ (Merged!)
@t-bast pointed out that we should do this.  He's right, but I didn't want to try to reconstruct the peer's commitment transaction, so I save them at signing time: we only need to keep information about anchors on the last two commitment transactions, worst case (there may be more than two, due to splicing), as earlier ones are sure to be revoked.
> lightningd: use CPFP on peer's commitment tx if we can't broadcast our own

- tests/test_splicing.py
The log messages were changed but the test fields weren’t updated, resulting in some test flakiness. Being more explicit with the log message we’re looking for should help.
Fixes #6803
> splice: Update test for new logs

- channeld/channeld.c
While running the integration testing in VLS we noted that there is a problem with the old_secret during that revoke and ack.
The built-in signer of core lightning return always the secret, but with a signer with more strict policies this can not be true.
In fact, the VLS return the old_secret only if it is the last tx candidate. So we should keep track of the old_secret during the recursion.
The current core is unsage because we can only revoke transaction M-1 once we have transaction M signed by the counterparty. If there is a splice candidate that is unsigned yet, and we revoke commitment transaction M-1 for it, and it gets into the blockchain, and the peer goes away, we can't force close anymore.
```
lightningd-1 2023-10-25T15:24:25.151Z **BROKEN** …
```
> splice: unwrap the old_secret during tx candidates

- cln-rpc/Makefile
- plugins/examples/cln-plugin-startup.rs
- plugins/src/lib.rs
- plugins/src/messages.rs
- tests/test_cln_rs.py
The ability to send custom notifications from plugins is needed for a new rust plugin, [smaug](https://github.com/chrisguida/smaug), which, once finished, will watch a descriptor wallet for updates and sends on-chain movements to the `bookkeeper` plugin using custom notifications.
This PR updates the `cln-plugin` create with a new `send_custom_notification` method on the `Plugin` object, which allows plugins to send custom notifications during normal operation. It also expands the `getmanifest` rpc response with a `notifications` array, which is needed in order for the plugin to register which notifications it wants to send with `lightningd`.
Sorry for all the formatting changes, my editor does this automatically on save and I'm unsure how to easily revert these, but I will remove if …
> Implement registering and sending custom notifications to lightningd

- gossipd/gossipd.c
- gossipd/routing.c
This is not the complete gossipd rework I wanted, but this disables both "mark channels disabled at startup" and spam detection for our own channel_updates.
Fixes: https://github.com/ElementsProject/lightning/issues/5523 any more.
Next version, we will simplify gossipd by removing private information, allowing this code to be cleaned up greatly.
> Minimal update fix

- contrib/startup_regtest.sh
When trying to initialize `bitcoind` on regtest I was always getting an error related to the creation or loading of the default wallet.
For instance
```
$ start_ln 4
Bitcoin Core starting
awaiting bitcoind...
Making "default" bitcoind wallet.
error code: -35
error message:
Wallet "default" is already loaded.
```
This prevents the use of `startup_regtest.sh` logic inside bash scripts where `set -e` is stated.
I've added a logic that first checks if the default wallet exists before trying to create it,
and then another to check if the wallet is loaded before trying to load it.
> Remove error from startup_regtest when loading wallet

- doc/developers-guide/app-development/rest.md
- doc/getting-started/getting-started/installation.md
- plugins/clnrest/clnrest.py
- plugins/clnrest/utilities/generate_certs.py
- plugins/clnrest/utilities/rpc_plugin.py
- plugins/clnrest/utilities/rpc_routes.py
- plugins/clnrest/utilities/shared.py
While working on testcases, I found few bugs in `clnrest` that were fixed along the way:
- `clnrest` self-signed certificates adds `rest-host` IP in Subject Alternative Name
- Fixed: Only runes which authorise the `listclnrest-notifications` method are allowed to get notifications
Changelog-Fixed: websocket server notifications are available with `readonly` runes
Link to #6436.
> clnrest: refactoring

- cln-rpc/src/lib.rs
- cln-rpc/src/primitives.rs
Some methods like waitsendpay return important information inside an RpcError's `data` field when called via cli. cln-rpc did not have this field. I added it as a serde_json::Value. We can probably do better with specific Error responses but for now this is an easy fix so i dont have to do
```
Command::new(lightning_cli)
.arg("--lightning-dir=".to_string() + lightning_dir.to_str().unwrap())
.arg("--conf=".to_string() + lightning_conf)
.arg("waitsendpay")
.arg((payment_hash).to_string())
.arg(timeout.to_string())
.output()
.await;
```
to get the erroring node and reason from a sendpay.
> Add data field to RpcError

- doc/getting-started/getting-started/configuration.md
- doc/lightning-listconfigs.7.md
- doc/lightningd-config.5.md
- doc/schemas/listconfigs.schema.json
- lightningd/channel_control.c
- lightningd/lightningd.h
- lightningd/options.c
- tests/test_closing.py
- tests/test_connection.py
- tests/test_misc.py
This gets the channel opener to propose a higher feerate than what they would actually prefer to use (the minimum realistic fee.)  This may address some feerate disagreements which lead to disconnects with peers due to non-exactly matching feerates as described in #6756.  This may be due to differing mempool configuration, or fee estimation.  Either way, some additional tolerance set by opener by default should improve the situation.
I'm not sure if we want this option exposed, but it seemed appropriate.  The default is 5, which only covers rounding errors, but there are reports of CLN<->CLN fee disagreements by just 1sat per kw difference.  Additional data may be useful to adjust this default.
Changelog-Added: Added option --commit-fee-offset to potentially reduce feerate update …
> Update fee hysteresis

- .github/workflows/ci.yaml
- conftest.py
Code using `CI_SERVER` was added recently to track something.  It attempts to short-cut if `CI_SERVER` is not set, but on gitlab it is set to `yes`.  https://docs.gitlab.com/ee/ci/variables/
Instead use `CI_SERVER_URL`, maybe that is what is intended?
VLS CI was failing on all skipped tests with:
```
=================================== FAILURES ===================================
[31m[1m_____________________ test_bookkeeping_missed_chans_pushed _____________________[0m
[gw6] linux -- Python 3.10.12 /usr/bin/python3
pyfuncitem = <Function test_bookkeeping_missed_chans_pushed>
@pytest.hookimpl(hookwrapper=True)
def pytest_pyfunc_call(pyfuncitem):
global result
result = result.copy()
result["testname"] = pyfuncitem.name
result["start_time"] = int(time())
outcome = yield
result["end_time"] …
```
> ci: Possible fix for CI_SERVER issue in VLS CI

- contrib/docker/Dockerfile.builder.fedora
- contrib/reprobuild/Dockerfile.focal
- contrib/reprobuild/Dockerfile.jammy
Fedora needs a fix for a broken `setuptools` installation and the ubuntu images a rust version upgrade
> Fix broken docker images for release build

- doc/developers-guide/app-development/grpc.md
- Add instruction to generate `primitives_pb2.py` file,
- Import `grpc` in the Python script.
> doc: fix cln-grpc example.

- lightningd/hsm_control.c
Fixes #6866
Changelog-Fixed: The WIRE_HSMD_SIGN_SPLICE_TX HSM capability is now correctly checked.
> splice: fix WIRE_HSMD_SIGN_SPLICE_TX capability check

- doc/developers-guide/app-development/rest.md
- doc/lightningd-config.5.md
- plugins/clnrest/clnrest.py
- plugins/clnrest/utilities/rpc_plugin.py
- plugins/clnrest/utilities/shared.py
- tests/test_clnrest.py
This will allow users to use clnrest with c-lightning-REST without conflicts.
It was required for applications to have enough time for migrating from c-lightning-REST to clnrest.
Changelog-Changed:
config option `rest-certs` changed to `clnrest-certs`
config option `rest-protocol` changed to `clnrest-protocol`
config option `rest-host` changed to `clnrest-host`
config option `rest-port` changed to `clnrest-port`
config option `rest-cors-origins` changed to `clnrest-cors-origins`
config option `rest-csp` changed to `clnrest-csp`
> Clnrest: update config param with `cln` prefix

- Makefile
- doc/contribute-to-core-lightning/contributor-workflow.md
- plugins/clnrest/Makefile
Add a version bump for clnrest and the main poetry.lock to the makefile and update the release checklist to include the new target.
> Update release checklist

- lightningd/options.c
- tests/plugins/clnrest-use-options.py
- tests/test_clnrest.py
Since these worked in v23.08, we can't just rename them.  So if they are used and unclaimed, we should rename them internally (if they're claimed, it's probably clightning-rest, and we should *NOT* touch them!).
Changelog-Deprecated: Plugins: `clnrest` parameters `rest-port`, `rest-protocol`, `rest-host` and `rest-certs`: prefix `cln` to them
> lightningd: fix up deprecated `rest-port`, `rest-protocol`, `rest-host` and `rest-certs` option if we would otherwise fail.

- bitcoin/psbt.c
- bitcoin/psbt.h
- channeld/channeld.c
- channeld/channeld_wire.csv
- channeld/inflight.c
- channeld/inflight.h
- channeld/splice.c
- channeld/splice.h
- common/psbt_internal.c
- lightningd/channel.c
- lightningd/channel.h
- lightningd/channel_control.c
- lightningd/dual_open_control.c
- tests/test_splicing.py
- tests/test_splicing_disconnect.py
- wallet/db.c
- wallet/test/run-db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
Adds tests for when the connection fails during
1) splice tx_signature
2) splice commitment_signed
Fleshed out the reestablish flow for these two cases and implemented the fixes to make these reestablish flows work.
Fixes https://github.com/ElementsProject/lightning/issues/6703
Changelog-Fixed: Implemented splicing restart logic for tx_signature and commitment_signed.
> splice: Reestablish when commit or sig sends fail

- CHANGELOG.md
Update changelog and py versions for second release candidate that includes mainly some tests for cln-rest
> CHANGELOG.md: Update for 23.11rc2

- common/json_stream.c
- lightningd/invoice.c
- lightningd/notification.c
- tests/test_clnrest.py
- tests/test_plugin.py
Changelog-Fixed: JSON-RPC: Plugin notification `msat` fields in `invoice_payment` and `invoice_created` hooks now a number, not a string with "msat" suffix.
Changelog-Fixed: JSON-RPC: Plugin hook `payment` `msat` field is now a number, not a string with "msat" suffix.
> Clnrest notifications remove msat

- plugins/clnrest/clnrest.py
This fixes a crash on startup of core-lightning where gevent could not be imported. This happens before sys is imported and throws us into the except clause which calls sys.
By importing it explicitly in the except clause we are not dependend of the order of imports in the try bracket.
> clnrest: Import sys in except clause explicitly

- doc/lightning-hsmtool.8.md
- tools/hsmtool.c
+ A doc entry for `getemergencyrecover`
+ I changed the example of `getcodexsecret` as it contained a disallowed character `i`. I guess this was an honor to @adi2011 so sorry for the change (shall we keep it? ^^).
> Fix getemergency segfault

- contrib/startup_regtest.sh
Few updates to the startup_regtest.sh utility.
- Remove `PATH_TO_LIGHTNING` and `PATH_TO_BITCOIN`
- Introduce `LIGHTNING_BIN`, `LIGHTNING_DIR`, `BITCOIN_BIN`, `BITCOIN_DIR`. Now you can set where bitcoind/bitcoin datadir/lightningd/lightning-dir are!
- Update default setting for `funder` to always contribute funds
- Update `fund_nodes` to fund the 2nd node so it makes balanced channels by default
> startup_regtest.sh: updates + improvements

- contrib/startup_regtest.sh
This configures the startup_regtest.sh nodes to enable clnrest + websocket while also providing output on their connection info (an unrestricted rune is generated as well.) Also uses the snap installed bitcoind path if appropriate.
Format of the start_ln output is:
Commands:
l1-cli, l1-log,
l2-cli, l2-log,
bt-cli, stop_ln, fund_nodes
Node Info:
l1 rest: https://127.0.0.1:3110  rune: "lgkWSp0PQK-pkbElLpjcNVQnX7yfEjouJaJHjLuW8w89OA=="
l2 rest: https://127.0.0.1:3111  rune: "sUqGqkevGYG2r1e_JUiz8Me00GhtTv5-IuGk4o9Beyc9OQ=="
Changelog-None
> startup_regtest: configure clnrest and generate rune

- lightningd/channel_control.c
Turns out we were sending feerate updates to daemons that do not understand it. Don't do that!
Closes #6932
Changelog-Fixed: channeld: We could crash `closingd` by sending it a `channeld` message
> subd: Do not send feerate updates to non-channeld subds

- plugins/src/options.rs
Can be used to check if a `ConfigOption` is set
> Implement `is_some` for `cln_rpc::options::Value`

- .github/workflows/pypi.yml
We don't want to fail testing on `master` ever!
Changelog-None
> gha: Add `--skip-existing` option to publish to testpypi

- contrib/pyln-client/pyln/client/plugin.py
- tests/plugins/dynamic_option.py
- tests/test_plugin.py
The python plugin-library doesn't allow `options` to be `dynamic` yet.
The plugin-developer can mark a plugin as `dynamic` and users can change the value using `setconfig`
We don't notify the plugin-developer if `setconfig` is called.
> Allow dynamic option in python plugin

- doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
When the value of a `dynamic` option is updated core Lightning will make a JSON-RPC request to the plugin.
The documentation falsely mentioned the request has a method named `setvalue. It appears it is actually called `setconfig`.
> Doc fix: dynamic options

- tests/test_splicing_insane.py
Test node restarts in lots of phases of splice.
Changelog-None
> splice: Agressive restart testing during splices

- channeld/channeld.c
FIx build error on 32bit system:
```
cc channeld/channeld.c
In file included from channeld/channeld.c:41:
channeld/channeld.c: In function ‘peer_reconnect’:
channeld/channeld.c:5149:15: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
5149 |  status_debug("Got reestablish commit=%"PRIu64" revoke=%"PRIu64
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~
./common/status.h:41:28: note: in definition of macro ‘status_debug’
41 |  status_fmt(LOG_DBG, NULL, __VA_ARGS__)
|                            ^~~~~~~~~~~
channeld/channeld.c:5150:23: note: format string is defined here
5150 |        " inflights: %lu, active splices: %"PRIu32,
|                     ~~^
|                       |
|                       long …
```
> build: 32-bit status_debug fix

- doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
The example used a mix of whitespace and tabs to format the JSON which made it appear poorly on my device.
> Docs: Consistent whitespace in developers guide

- common/psbt_internal.c
On July 18th, @jgriffiths wrote:
> You need to set this to NULL after freeing it, otherwise if line 72 returns you have a dangling pointer and potential later use-after-free here. Alternately use wally_psbt_set_input_final_witness(NULL) which will free any existing witness and set the value to NULL.
Reported-By: @jgriffiths
See original report: https://github.com/ElementsProject/lightning/pull/6391#pullrequestreview-1535809620
> psbt-fix: set to NULL, which will cleanup dangling pointer

- common/test/Makefile
- common/test/run-trace.c
- common/trace.c
- common/trace.h
- contrib/cln-tracer/.gitignore
- contrib/cln-tracer/README.md
- contrib/cln-tracer/cln_tracer/trace.py
- contrib/cln-tracer/pyproject.toml
- doc/developers-guide/tracing-cln-performance.md
We changed a couple of things in the `common/trace.c` implementation,
and I was wondering what the overhead of the tracing might be. To
answer that I built a small test that creates and emits 1000000
spans. To test with and without an exporter attached I also added a
sample exporter that can be used to submit batches of spans to either
`otelcol` or `tempo`.
> Document tracing and add a sample exporter

- doc/developers-guide/plugin-development/event-notifications.md
- lightningd/connect_control.c
- lightningd/notification.c
- lightningd/notification.h
- tests/plugins/custommsg_notification.py
- tests/test_misc.py
Implements notifications for `custommsg`
> Custom msg as notification

- doc/beginners-guide/backup-and-recovery.md
- doc/beginners-guide/backup-and-recovery/recovery.md
- doc/beginners-guide/backup.md
- Adds instructions to recover the wallet with database
- Breaks the recovery subtitle into separate page
> docs: Recovery using database

- contrib/pyln-testing/pyproject.toml
pyln-testing depends on cheroot~=8 which depends on pkg_resources.
In python3.11 this has been deprecated which results in the following warning
```
.../venv/lib/python3.11/site-packages/cheroot/__init__.py:7: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
import pkg_resources
```
> Update pyln-testing cheroot dependency

- contrib/pyln-client/pyln/client/lightning.py
- contrib/pyln-client/pyln/client/plugin.py
- contrib/pyln-testing/pyln/testing/fixtures.py
- contrib/pyln-testing/pyln/testing/utils.py
- tests/test_closing.py
- tests/test_misc.py
- tests/test_pay.py
- tests/test_plugin.py
- tests/test_renepay.py
This was interfering with other JSON usages (confusingly!) such as clnrest.  We only did it because _msat fields used to be strings.
Leaves the generic fallback to ".to_json" to marshall *into* JSON though.
> Remove pyln-client json monkey patch for _msat fields to Millisatoshis

- cln-rpc/src/lib.rs
This should be the same, but without cloning.
> cln-rpc: rewrite is_none_or_empty to not use clone()

- common/bolt11.c
- common/test/run-bolt11.c
This will allow more time for the 18 block final cltv delta default to be adopted.
fixes #6956
> Force cltv field inclusion in BOLT 11 invoice

- doc/developers-guide/developers-guide.md
Currently, when inside the contrib folder, the script startup_regtest.sh is being sourced using the path contrib/startup_regtest.sh. However, for proper execution, we should use the relative path source startup_regtest.sh instead. This adjustment ensures that the script is loaded correctly when working within the contrib directory.
> fix: load script

- common/trace.c
- common/trace.h
The integration with opentelemetry was sub-optimal: it was generating jaeger-style traces, with short traceIds and we were considering the entire lifetime as a single trace. This PR changes that to a trace for startup and then a trace for any event that doesn't already have a parent.
We also allow using the `CLN_TRACEPARENT` envvar to attach the startup to a remote / external trace, potentially by whatever started the main process. This is useful to see the startup trace in the wider context of whatever tooling is built around it.
Changelog-Added: tracing: It is now possible to inject a parent for the startup trace by setting the `CLN_TRACEPARENT` envvar
> misc: Improve generated traces from common/trace.c

- .github/workflows/pypi.yml
- contrib/reprobuild/Dockerfile.focal
- contrib/reprobuild/Dockerfile.jammy
- tools/build-release.sh
Stepping through the docs I found a number of inconsistencies, specifically with the reproducible builds which seem to have bitrotted as multiple release captains added their own interpretation.
> docs: Minor changes in the release docs

- doc/developers-guide/app-development/rest.md
original listrunes's link is wrong, should use this:[iightning-commando-listrunes -- Command to list previously generated runes](https://docs.corelightning.org/reference/lightning-commando-listrunes)
**before**
**after**
> doc:correct listrunes's link

- configure
I noticed this while working on a nix devShell to work on CLN. We are
blanked overriding the `pkg-config` search path, which can cause some
trouble. Specifically `nix` uses content addressable locations, and
macOS arm64 and x84_64 use separate `pkg-config` search paths, and by
overwriting it we can cause a mix of different architectures failing
the compilation
Changelog-Fixed: configure: We now respect the `PKG_CONFIG_PATH` environment variable
> configure: Use the system `PKG_CONFIG_PATH`

- devtools/changelog.py
The `devtools/changelog.py` method `linkify` produces duplicate link entries if we have more than one changelog line in a PR. This change removes the duplicates so that we only have one link per PR.
> Deduplicate Changelog.md generated links

- Cargo.lock
- plugins/Cargo.toml
- plugins/src/logging.rs
This switches the logging implementation from using the `log`-facade to using the `tracing-subscriber` instead. This allows us to also tap into the tracing instrumentation if desired, which was not possible with `log`.
Changelog-Changed cln-plugin: The logging adapter now uses tracing-subscriber allowing the `tracing` ecosystem to be used. No format changes.
> cln-plugin: Switch from `env_logger` to `tracing-subscriber`

- plugins/renepay/pay.c
- plugins/renepay/payment.c
- plugins/renepay/payment.h
- tests/test_renepay.py
Self-pay feature for `renepay`, based on the implementation of self-pay for the default `pay` plugin.
Fixes #6606
> renepay: add self-pay feature

- plugins/renepay/flow.c
- plugins/renepay/flow.h
- plugins/renepay/mcf.c
- plugins/renepay/pay_flow.c
- plugins/renepay/payment.c
- plugins/renepay/payment.h
- plugins/renepay/test/run-testflow.c
- plugins/renepay/uncertainty_network.c
- tests/test_renepay.py
Min. Cost Flow (MCF) does not resolve the correct amount in channel forwarding
because the algorithm dismisses the amounts paid as fees to the routing
nodes. The root of this problem is that flow conservation is assumed for
simplicity such that the sender is the only *source* and the recepient is the
only *sink*. This in reality is not true, because also forwarding nodes are
sinks since they consume fees.
When real amounts including fees are then added to the payment routes by
the function `flow_complete`, some channels might be requested to forward an
amount which could be greater than `known_max - htlc_total`.
For remote channels this issue is likely inadverted because we are anyways
caping the probability of success down to 5% in our linearization scheme,
[see this …
> renepay: accomodate fees in the payment flow

- tests/test_closing.py
- tests/test_misc.py
If listpeers on l2 is called too fast, then it won't return any peers, and we will fail:
```
l1.connect(l2)
>       wait_for(lambda: l2.rpc.listpeers(l1.info['id'])['peers'][0]['connected'])
tests/test_misc.py:2690:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
contrib/pyln-testing/pyln/testing/utils.py:88: in wait_for
while not success():
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   wait_for(lambda: l2.rpc.listpeers(l1.info['id'])['peers'][0]['connected'])
E   IndexError: list index out of range
```
> pytest: fix flakes

- doc/lightning-fundchannel_start.7.md
- doc/schemas/fundchannel_cancel.request.json
- doc/schemas/fundchannel_complete.request.json
- doc/schemas/fundchannel_start.request.json
- Commit 1: Doc improvements for `fundchannel_start`
- Commit 2: Creates the corresponding json-schema''s for this method
I've refrained from including the bindings in `msggen`. 
The key problem is that `fundchannel_start` contains an underscore.
This results in `msggen` is generating broken code that cannot be fixed easily.
Replaces https://github.com/ElementsProject/lightning/pull/6946
> Document fundchannel_start, fundchannel_complete, fundchannel_cancel

- tests/test_closing.py
- tests/test_db.py
- tests/test_gossip.py
- tests/test_misc.py
- tests/test_opening.py
- tests/test_plugin.py
- tests/test_splicing.py
- tests/test_splicing_disconnect.py
If I understood correctly, the tests work pre- and post-private gossip change
so no need to be bundling them with that change at all. Cherry-picking the 
test changes so we don't have to carry them around as much, and they seem
to be useful independently of the gossip rework.
> gossip: Cherry pick test fixes out of 

- common/gossmap.c
- common/gossmap.h
- plugins/topology.c
- tests/test_connection.py
This happens in deprecated mode, and we get bogus results.  Valgrind caught it!  
Bonus: fix another flake.
Changelog-None: Introduced in recent gossip changes.
> topology: don't call gossmap for locally added channels.

- doc/lightning-hsmtool.8.md
- tools/hsmtool.c
I would like to have a feature in core-lightning to export the private keys used by the on-chain wallet.
This feature would allow to control the funds using a 3rd party software, personally I don't like to have funds that can only be recovered with a single wallet.
Currently core-lightning has a tool to generate the `hsm_secret` from a mnemonic sentence (+ passphrase), but this mechanics is not compliant with BIP39. The `hsm_secret` itself is not even the seed of the BIP32 wallet, and the HD wallet does not use BIP43 purpose derivation for the different types of addresses (wpkh, sh(wpkh), tr) instead a single extended key is used in all three wallets. That said one cannot just put the original mnemonic into another wallet and derive the public and private keys, and neither plug …
> hsmtool: add feature to dump private keys

- plugins/src/lib.rs
- plugins/src/messages.rs
Allow the plugin developper to specify the content of the `custommessages` field in getmanifest
> cln_plugin: custommessages in `get_manifest`

- tests/test_closing.py
Changelog-Added: added a withdraw all to the end of test_onchain_their_unilateral_out to ensure that the unilateral close info is correct with anchors.
Tests https://github.com/Blockstream/greenlight/issues/348
> tests: augment test to check to_remote witness generation

- Cargo.lock
- cln-grpc/Cargo.toml
- cln-grpc/build.rs
This PR adds serde annotations that help serializing / deserializing the cln-grpc protobuf types to and from json.
> cln-grpc: Derive serde Serialize/Deserialize for protobuf types

- configure
By default, UBSan reports runtime errors but does not stop execution. We already abort in debug builds, and this commit makes us also abort in regular builds when UBSan is enabled. Arguably, this is what users expect when they enable UBSan, so it is a good default.
I know I've missed some UBSan bugs in the past because of this issue, and @dergoegge mentioned that this also happened to him.
> configure: abort on UBSan failure

- .github/workflows/ci.yaml
- .github/workflows/fuzz.yaml
Fuzz testing as a side-quest while verifying the correctness of a PR is strange. Lets not do that.
> ci: Split fuzzing out of the PR testing

- plugins/renepay/flow.h
- plugins/renepay/mcf.c
- tests/test_renepay.py
Usually `minflow` would first compute a MCF solution and then construct routes based on that.
Neither of these steps would take into account the limits `htlc_min` and `htlc_max` on channels.
PR #6893 removes a portion of the amount committed to the routes if they exceed the `htlc_max`,
but that PR assumes that that excess is small and it is due to the MCF not taking into account the
addition of fees to the flow. If the amount committed to a route exceeds the `htlc_max` in a great
amount, we would be better off to allocate that difference in other routes by recomputing MCF.
But we don't have a check for the size of that number and we just assume that the excess is small.
I think a better way to constraint the flow with respect to the `htlc_max` (and `htlc_min`) bounds is
to do it at a …
> Renepay: htlc limits on mcf

- lightningd/opening_control.c
- tests/test_connection.py
- tests/test_gossip.py
Not sure how this got through CI...
> lightningd: fix reference to uninitialized channel_type during opening.

- contrib/startup_regtest.sh
If `$BITCOIN_BIN` is empty and `bitcoin-cli` or `bitcoind` are not found `startup_regtest` will shutdown and display a corresponding error message.
Similarly if `lightning-cli` and `lightningd` are not found.
Before this, the script would simply stop execution without any message whatsoever.
> regtest: error message if bitcoin-cli is not found

- plugins/bkpr/recorder.c
- tests/test_bookkeeper.py
[issue #6800](https://github.com/ElementsProject/lightning/issues/6800)
Grouping by `update_count` resulted in a crash due to a bad arithmetic assert in `recorder.c` line 365 calculating negative fees  caused by the returned rows not being consolidated.  This removes that update_count grouping and adds tests for single and dual funded channels.
---
**Update**
update_count is just the count of the records for a tx.  To calculate onchain fees
for an account we must sum all credits vs debits.  We don't need to GROUP BY update_count
nor ORDER BY update_count since it is just a running index of updates to this tx, so it can be removed.  
Previously...
Postgres was not happy with not having update_count in the GROUP BY if it was used in ORDER BY.  
The two pull requests below added update_count …
> Fix onchain fees lookup query

- contrib/startup_regtest.sh
Opsie: I pushed a bug in #6966, the `startup_regtest.sh` 
test that checks if `bitcoin-cli`, `bitcoind`, `lightning-cli` and `lightningd` are found as executables is broken.
This PR fixes that.
> regtest: fix check for bitcoin-cli

- plugins/grpc-plugin/src/main.rs
`cln-gprc` is assuming the `rpc-file` path is set as default, which may not always be the case. Set the path the what the plugin manager reports
Lately, Polar for macOS has been unable to deploy CLN nodes due to an issue with how the `rpc-file` is generated on the docker volume (see https://github.com/jamaljsr/polar/issues/779 for details). Recently, a workaround has been found, consisting of moving the `rpc-file` outside of its default location. However, doing so makes `cln-grpc` unable to connect to the backend.
This can be worked around by creating a simlink in the default location to point to where `lightning-rpc` is actually located. However, the underlying issue lies in `cln-grpc` not getting the info from `cln-plugin` but instead, assuming the location of the file.
> cln-grpc: Patches rpc-file path

- common/json_param.c
- common/test/run-param.c
- doc/developers-guide/deprecations.md
- doc/lightning-offer.7.md
- plugins/offers_offer.c
- tests/test_pay.py
@cdecker points out that it's ugly to have a string variant, and I agree.  Deprecate now (quickly, it's experimental) so GRPC/Rust bindings don't have to support it!
> Offers deprecate string recurrence

- contrib/pyln-client/pyln/client/lightning.py
This allows for people using the python SDK for CoreLN to send custom messages.
> Add a method to the pyln-client for using the sendcustommsg api

- contrib/pyln-testing/pyln/testing/utils.py
- doc/lightningd-config.5.md
- lightningd/hsm_control.c
- lightningd/lightningd.c
- lightningd/opening_control.c
- lightningd/options.c
- plugins/funder.c
- tests/test_bookkeeper.py
- tests/test_closing.py
- tests/test_connection.py
- tests/test_misc.py
- tests/test_opening.py
- tests/test_pay.py
- tests/test_plugin.py
- tests/utils.py
- wallet/reservation.c
- wallet/wallet.c
- wallet/wallet.h
~Based on #6780~  Rebased on master.
> Anchors not experimental

- wallet/db.c
Commit dac8964093feb1f4b1f996130fd208bad9900131 set aliases for channels at creation time, but neglected to convert channels in the database.  Do that now!
Fixes: #7039
Changelog-None: broken this release!
> wallet: ensure all established channels have aliases.

- Makefile
- contrib/docker/Dockerfile.alpine
Generating the msggen proto files doesn’t require rust (even though it generates rust files).
Keep getting in this loop where my docs don't match CI and it's because the doc scripts were never running on my machine and I didn't enable rust.
Other's will probably run into this problem and it's quite hard to figure out.
Spotted by @niftynei and @chrisguida
> make: always generate proto files sans rust

- plugins/examples/cln-plugin-startup.rs
- plugins/grpc-plugin/src/main.rs
- plugins/src/lib.rs
- plugins/src/messages.rs
- plugins/src/options.rs
- tests/test_cln_rs.py
This PR contains breaking changes.
I refactored `ConfigOption` in the `cln_plugin` crate and added some basic documentation.
It becomes easier to request the configured value of the `ConfigOption`.
I've marked this as draft because I still want to add some integration tests
> `cln_plugin` Refactor ConfigOption

- channeld/channeld.c
- channeld/channeld_wire.csv
- channeld/splice.c
- channeld/splice.h
- common/interactivetx.c
- common/interactivetx.h
- common/jsonrpc_errors.h
- common/wire_error.c
- lightningd/channel_control.c
- tests/test_connection.py
- tests/test_splicing.py
- tests/test_splicing_disconnect.py
- wallet/wallet.c
- wallet/wallet.h
Adds support for `tx_abort` including sending, receiving, and ACK'ing.
When `tx_abort` is confirmed in `channeld` we notify `lightningd` and shutdown. `lightningd` then restarts the channeld daemon.
This is all done without breaking the connection and special care is made to connect the daemon to the existing connection through a `connectd` fd.
> Splice: Complete tx_abort implementation

- lightningd/dual_open_control.c
- openingd/dualopend.c
- openingd/dualopend_wire.csv
- tests/fuzz/fuzz-wire-tx_ack_rbf.c
- tests/fuzz/fuzz-wire-tx_init_rbf.c
- wallet/wallet.c
- wire/extracted_peer_03_dual-funding.patch
- wire/peer_wire.csv
Be explicit about the `require-confirmed` requirements for RBFs as well as initial txs.
Updates CLN to conform to the latest spec draft, including https://github.com/lightning/bolts/pull/851/commits/27ffef47aee985d37dcef85d528719f9a4608400
Be explicit about the require-confirmed requirements for RBFs as well as initial txs.
Initially we were re-using the value at start for any subsequent renegotiations, but with this patch we
now use whatever the system-wide setting is at the time that we attempt an RBF. This makes it easier to test
and allows you to (with some effort) update what channels request at a system level.
Requested-By: @t-bast
> Dual-funding: permit re-negotiation of require-confirmed on RBFs

- common/gossip_store.h
- common/gossmap.c
- common/gossmap.h
- connectd/gossip_store.c
- contrib/pyln-testing/pyln/testing/fixtures.py
- devtools/dump-gossipstore.c
- gossipd/gossip_store.c
- gossipd/gossip_store.h
- gossipd/gossmap_manage.c
- tests/test_gossip.py
The "bad gossip" flakes were caused by the fact that:
1. When we see a channel close, we simply mark the channel_announce `dying` which means we don't propagate it.
2. We did not maintain this dying bit in various cases:
1. We did not set it on the node_announcement once all channels are dying.
2. Not *unset* it on the node_announcement if we see another channel confirmed.
3. Nor did we set it if a new channel_update came in on a dying channel (we still accept updates!)
4. Nor did we preserve it in node_announcements if we have to move it when all preceding channels are eliminated.
5. We did not set it on fresh node_announcements if all channels were dying.
6. We did not ignore dying channel_announcements when figuring out if we had to move the node_announcement.
I added a dev sanity …
> Fix gossip code when channels are marked dying

- gossipd/gossip_store.c
This happens to Vincenzo, and I think it's due to previous gossip_store issues.
Fixes: https://github.com/ElementsProject/lightning/issues/7051
Changelog-None: new bug for this release.
> gossipd: don't assert on redundant flag write, just log message.

- channeld/full_channel.c
- tests/test_connection.py
We would sometimes propose fees which we couldn't afford, and thus the peer would get upset: if we didn't recover it could cause force closes.
This was because we didn't take into account that pending htlcs will remove our total available funds.
Changelog-Fixes: Protocol: Don't upset peers by sending `update_fee` with fees we cannot afford in the case where HTLCs are large.
> channeld: fix update_fee cap.

- lightningd/connect_control.c
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/options.c
When a node has lot of private channels to nodes which are not always online, the is no reason to try to reconnect to them because they can be offline for long period of time.
> Add no-reconnect-private option to disable automatic reconnect-attempts to peers connected to our node with private channels only

- lightningd/channel_gossip.c
This was triggered by the recover plugin tests (not yet merged!) and causes a crash because we don't have signatures yet.  It can only happen if we lost our database, but at least don't crash!
Fixes the crash in https://github.com/ElementsProject/lightning/pull/6853
> lightningd: don't force state if gossipd gives us an unexpected channel_update.

- connectd/connectd.c
This code was trying to check that the address type is not one of the ADDR_TYPE_TOR* types, but the is_toraddr() function checks a domain name!  The cast should have been a clue that this was wrong!
Anyway, wireaddr_to_addrinfo() aborts on these cases already, so the asserts here are superfluous.
Found in unrelated CI run:
```
Valgrind error file: valgrind-errors.20610
==20610== Conditional jump or move depends on uninitialised value(s)
==20610==    at 0x484ED28: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==20610==    by 0x138FA3: is_toraddr (wireaddr.c:344)
==20610==    by 0x11499B: conn_init (connectd.c:729)
==20610==    by 0x28FD73: next_plan (io.c:59)
==20610==    by 0x28FF94: io_new_conn_ (io.c:116)
==20610==    by 0x11531B: try_connect_one_addr …
```
> connectd: fix bad assert.

- lightningd/channel_gossip.c
If we accept a channel_update in state "NEED_SIGS" we should not set refresh timer: we're simply holding it for the moment we get to that state (which will happen as we mine the block).
```
0x7fd1cce39205 __assert_fail
./assert/assert.c:101
0x55c103cc6ee9 check_channel_gossip
lightningd/channel_gossip.c:128
0x55c103cc8a13 channel_gossip_update_from_gossipd
lightningd/channel_gossip.c:821
0x55c103cd752d handle_init_cupdate
lightningd/gossip_control.c:138
0x55c103cd79a3 gossip_msg
lightningd/gossip_control.c:190
```
> lightnignd: Fix another assert crash.

- plugins/renepay/pay.c
- plugins/renepay/pay_flow.c
- tests/test_renepay.py
Whenever there is a payment failure that requires gossip update, for
example changing the fee rates of remote channels, we call addgossip.
For renepay to consider this changes in the coming payment attempts, it
must update gossmap.
Fixes issue #7081
> Renepay fix fees

- bitcoin/chainparams.h
- contrib/pyln-spec/bolt1/pyln/spec/bolt1/text.py
The comments in chainparams.h list Signet's port hex as 0xF87 which should be 0x9B77. This needs updating to match the actual port value
> Fix incorrect hex value for Signet port

- gossipd/gossmap_manage.c
As reported on Discord, we need to reload the gossip store after we move a node_announcement, lest we try to move it twice!
> Gossip store double delete fix

- channeld/channeld.c
You otherwise get thousands of these zero count Splice resume checks spamming your logs while most of the time it is only informing you of "nothing is happening".
Reduces log noise.
> channeld: Splice resume check should log to DEBUG

- bitcoin/script.c
- bitcoin/script.h
- bitcoin/tx.c
- bitcoin/tx.h
- lightningd/chaintopology.c
We were always allocating space and copying the scripts from the
outputs, and then immediately discarding them again if they weren't
P2WSH outputs. This patch adds an introspection method, and then uses
it to determine whether we're interested in the output before cloning
the script. This should save us almost 1 allocation and 1 deallocation
for each output in a block (thousands).
Builds on top of #6983
> core: Defer script extraction until we know it's needed

- bitcoin/tx_parts.c
Update to clone inputs as we do outputs already. Aside from requiring less code, this insulates us from any future wally changes to add new members inside the tx struct.
This is possible since the version bump to wally 1.2 now exposes the input clone function.
> tx_parts: use wally to clone tx inputs

- plugins/src/lib.rs
- plugins/src/options.rs
Static lifetimes are a bit "too long".
Since ConfigOption is `#[derive(Clone, Debug)]` it made sense to also make all the `config_type` like that.
> cln_plugin: switch lifetimes of ConfigOption from static to non-static

- plugins/libplugin-pay.c
- plugins/libplugin-pay.h
So far we would call `preapproveinvoice` once for each payment split,
i.e., at least once per HTLC, and potentially more often. There is no
point in doing so repeatedly, and especially in remote signer setup
this is actually counterproductive due to the additional roundtrips.
Changelog-Changed pay: Improved performance by removing repeated `preapproveinvoice` calls
> pay: Prevent duplicate preapproveinvoice calls

- plugins/recover.c
We also reduce the frequency of the
various checks from every 2 seconds
to every 30 seconds.
Changelog-Fixed plugin: The recovery plugin is less noisy
> plugin: Reduce the verbosity of the recover plugin

- plugins/renepay/pay.c
We have not yet worked on supporting BOLT12 invoices, we better refuse to pay them until we do.
> renepay: refuse to pay BOLT12 invoice

- plugins/renepay/mcf.c
In some weird situations it may happen that some channel along the route could have htlcmax=htlcmin, so that the supremum of htlcmin and the infimum of htlcmax are the same number. In that case there is only one allowed amount that can go through that route.
Without this patch renepay would not handle correctly this cornercase.
Solves issue #7115
> renepay: bugfix situation with htlcmax=htlcmin

- .github/workflows/pypi.yml
The pypi workflow had an error as it does not allow `"`. I also fixed the deprecation warnings by bumping the `setup-python` version.
> Minor pypi workflow fix

- .github/workflows/crate-io.yml
https://github.com/ElementsProject/lightning/actions/runs/8204293180/job/22438677830
errored because the workflow doesn't have protoc. This might fix it
> crates workflow: add protoc to workflow environment

- bitcoin/script.c
- bitcoin/script.h
- bitcoin/tx.c
- bitcoin/tx.h
- channeld/watchtower.c
- common/addr.c
- common/addr.h
- common/bolt11.c
- common/bolt11_json.c
- common/close_tx.c
- common/interactivetx.c
- common/psbt_open.c
- common/shutdown_scriptpubkey.c
- devtools/bolt11-cli.c
- hsmd/libhsmd.c
- lightningd/bitcoind.c
- lightningd/chaintopology.c
- lightningd/closing_control.c
- lightningd/dual_open_control.c
- lightningd/opening_control.c
- onchaind/onchaind.c
- openingd/dualopend.c
- wallet/txfilter.c
- wallet/wallet.c
- wallet/wallet.h
- wallet/walletrpc.c
Per discussion on https://github.com/ElementsProject/lightning/pull/6984, adding another introspection wrapper to avoid non-interesting matches is non-optimal. It's a duplicate of the is_xxx script call already exposed, and it doesn't fix the many other places where allocations are made unnecessarily.
It seems the original rationale for the copies is behaviour that was since fixed (see commit descriptions for details). But also, the script introspection functions are inconsistent w.r.t taking lengths. Removing this inconsistency by adding length args exposes a lot of places that were allocating redundantly which this PR addresses. In particular, we avoid allocations for interesting scripts which https://github.com/ElementsProject/lightning/pull/6984 does not. We are then able to remove …
> Faster block sync

- configure
See https://github.com/llvm/llvm-project/issues/81470 which started breaking CI because configurator doesn't expect test programs to crash!
> configure: disable ASAN for buggy clang.

- ccan/README
- ccan/ccan/rune/rune.c
- common/daemon.c
- common/daemon.h
- contrib/msggen/msggen/schema.json
- contrib/pyln-testing/pyln/testing/utils.py
- doc/contribute-to-core-lightning/testing.md
- doc/schemas/lightning-createrune.json
- lightningd/lightningd.c
- lightningd/options.c
- lightningd/plugin.c
- lightningd/runes.c
- lightningd/subd.c
- lightningd/test/run-find_my_abspath.c
- tests/test_plugin.py
- tests/test_runes.py
1. Add DEBUG_LIGHTNINGD to pytest infra so we can attach debuggers to lightningd itself conveniently.
2. We used to suppress `_` in rune names of parameters, but runes was changed two years ago to allow `_`, so we should stop doing that.  We allow both, for backwards compat.
3. Make error messages clearer, which lead me to clean up one unexpected case.
> Rune handling cleanups, new DEBUG_LIGHTNINGD option

- tools/hsmtool.c
This line is a cosmetic off-by-one error. There are 7 languages defined, but because counting starts at 0, the display shows "Select [0-7]" when in fact only 0-6 are valid choices.
> hsmtool.c - Fixes cosmetic off-by-one error 

- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-multifundchannel.json
- plugins/spender/multifundchannel.c
- tests/test_opening.py
related issue: https://github.com/ElementsProject/lightning/issues/6664
Using `"amount": "all"` is atleast in multifundchannel broken. I could not find a test for it so i wrote a simple test for it. Didn't know 100% where to put it or what to put for the `@`, but this test fails with:
```
pyln.client.lightning.RpcError: RPC call failed: method: multifundchannel, payload: {'destinations': [{'id': '022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59@localhost:35399', 'amount': 50000}, {'id': '035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d@localhost:42377', 'amount': 'all'}], 'minchannels': 2}, error: {'code': -1, 'message': 'Error broadcasting transaction: error code: -26\\nerror message:\\nbad-txns-in-belowout, value in (0.02) < value out (0.02045073). …
```
> repro: `multifundchannel` and `all` amount

- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/index.rst
- doc/schemas/lightning-dev-forget-channel.json
Hi, 
First attempt at the docs for the above command.  I did run `make doc-all` and the markdown was generated correctly, but not sure about the *.requests.json. 
@ShahanaFarooqui 
Issue reference: 
https://github.com/ElementsProject/lightning/issues/6923
> [docs] Add documentation for dev-forget-channel

- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-createrune.json
- lightningd/runes.c
- tests/test_runes.py
@ShahanaFarooqui co-wrote this with me: it adds the ability for runes to inspect inside bolt11 and bolt12 strings!
> Rune invoice inspect

- cln-grpc/src/pb.rs
The import is spurious and results in a warning when building the code.
I have removed the line to make the warning disappear
> Remove spurious import

- lightningd/dual_open_control.c
- lightningd/jsonrpc.c
- lightningd/opening_control.c
- lightningd/pay.c
- lightningd/peer_htlcs.c
- tests/test_invoices.py
- tests/test_misc.py
- tests/test_opening.py
- tests/test_pay.py
- wallet/test/run-wallet.c
Don't require us to be fully synced with bitcoind before we allow certain operations:
1. Allow outgoing HTLCs immediately.
2. Wait for openchannel_init/openchannel_bump/fundchannel_start instead of failing.
3. Use bitcoind's height, not ours, for CLTV values on payments.
This means Greenlight doesn't have to block operations while waiting for block sync.
> Faster startup

- lightningd/plugin_hook.c
Covered up by notleak() :(
Changelog-Fixed: lightingd: slow memory leak when using plugin hooks fixed (introduced in v23.11)
This may be why my machine was running out of memory after a while (clboss and lnmetrics use a lot of plugin hooks).
> lightningd: fix memleak where we didn't free plugin_hook_request when it was finished.

- plugins/libplugin-pay.c
- tests/test_pay.py
Fixes https://github.com/ElementsProject/lightning/issues/7177
Below lines of code failed to actually re-add the amount back to the channel hint's estimated capacity.
https://github.com/ElementsProject/lightning/blob/4b8d2617bbbc678a67376b32332804b66a691034/plugins/libplugin-pay.c#L586-L589
I'm not sure why tbh, it seems like a reasonable piece of code. However, it made the corresponding test (added in this PR) fail, because the channel hint's estimated capacity of the sender's own channel was below the amount he was trying to send. I tested this by logging the `channel_hints` before and after the operation in those lines. When _substracting_ the amount (`remove == false`) the estimated capacity of the sender's channel after the operation was smaller than before the operation. When …
> pay: fix re-adding payment amount back to estimated capacity

- .github/scripts/setup.sh
- .github/workflows/bsd.yml
- .github/workflows/ci.yaml
- .github/workflows/macos.yaml
> ci: use Bitcoin Core 26.1

- plugins/libplugin-pay.c
Builds on #7188 to make the code clearer.
> Pay: payment removal cleanup

- plugins/Makefile
- plugins/clnrest/clnrest
- tests/test_clnrest.py
Apparently NixOS didn't have Python (sometimes!) so let's not assume. By reusing the JSON "parsing" code from cowsay, we can self-disable to handle this case.
Reported-by: Shahana Farooqui <shahana.farooqui@gmail.com>
Changelog-Fixed: Plugins: `clnrest` now correctly self-disables if Python not present at all.
> plugins/clnrest: simple wrapper to handle missing python3.

- .msggen.json
- README.md
- cln-rpc/src/model.rs
- contrib/msggen/msggen/__main__.py
- contrib/msggen/msggen/gen/rust.py
- contrib/pyln-testing/pyln/testing/grpc.py
- doc/beginners-guide/opening-channels.md
- doc/lightningd.8.md
- tests/test_misc.py
There were various occurences of `p2sh-segwit` still left in msggen, tests and documentation. So i removed them. I also updated some documentation files to reflect the current state of `newaddr`.
Is it problematic that the values in `message NewaddrResponse` changed?
Fixes: #6996 
Replaces: #7146
> newaddr: various fixes for msggen and docs

- contrib/pyln-testing/pyln/testing/fixtures.py
- contrib/pyln-testing/pyln/testing/utils.py
- lightningd/channel.c
- lightningd/opening_control.c
- tests/test_closing.py
- tests/test_connection.py
- tests/test_db.py
- tests/test_gossip.py
- tests/test_misc.py
- tests/test_opening.py
- tests/test_pay.py
- tests/test_plugin.py
Several things which were gathering in unloved branches :)
> Tiny cleanups

- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-delinvoice.json
- doc/schemas/lightning-disableinvoicerequest.json
- doc/schemas/lightning-keysend.json
- doc/schemas/lightning-listsendpays.json
- doc/schemas/lightning-pay.json
- doc/schemas/lightning-sendpay.json
- doc/schemas/lightning-wait.json
- doc/schemas/lightning-waitanyinvoice.json
- doc/schemas/lightning-waitinvoice.json
- plugins/bkpr/bookkeeper.c
Not singular (though we used to have a listinvoice, removed in v0.6.1).
Reported-by: "Plant" via email
> spelling: its `listinvoices` and `listinvoicerequests`

- .github/workflows/ci.yaml
- plugins/bcli.c
- tests/test_misc.py
This PR adds a path in the `bcli` plugin that utilizes `getblockfrompeer` to try to fetch a block from a peer in case that we don't know about the block. This is something that happens when core lightning tries to fetch a block from bitcoind that has already been pruned by bitcoind.
`getblockfrompeer` has been introduced in `v23.0.0`. The call asks a given peer for a block that the local node does not know about. Even though `getblockfrompeer` does not make any guarantees about whether the block will be fetched (or pruned again right away), the success probabilities are really high if we just try long enough.
Here is a brief description about what happens now if core lightning asks for a block
a) get blockhash for height x
b) try to get block from bitcoind:
- found the block: perfect! …
> Fetch block from a peer if we don't have it

- doc/developers-guide/app-development/rest.md
- doc/lightningd-config.5.md
- plugins/clnrest/clnrest.py
- plugins/clnrest/utilities/rpc_plugin.py
- plugins/clnrest/utilities/shared.py
For BTCPay, the swaggerUI doesn't come up because it assume that it is running on the base of the domain. It will be easier to use, for BTCPay and others, if the SwaggerUI's root url can be configured.
- Updated config params and plugin
- Updated documentation
Changelog-Added: Added a new configuration for clnrest plugin to change the default Swagger UI path from `/` to custom url.
> plugin/clnrest: Adding new config param as `clnrest-swagger-root`

- plugins/libplugin.c
- tests/plugins/openchannel_hook_delay.py
- tests/test_pay.py
Uncommited channels are missing several fields which would normally bepopulated by an active channel.  This simply skips them for the purposes of finding a route.  The particular culprit was:
{
"peer_id": "038cd9f3679d5b39bb2105978467918d549572de472f07dd729e37c7a6377d41d5",
"peer_connected": true,
"state": "OPENINGD",
"owner": "lightning_openingd",
"opener": "local",
"to_us_msat": 8317559000,
"total_msat": 8317559000,
"features": [
"option_static_remotekey",
"option_anchors_zero_fee_htlc_tx"
]
}
Fixes #7197 - SEGV in direct_pay_listpeerchannels when field private missing
Changelog-Fixed: Fixed crash in pay plugin caused by parsing uncommitted dual open channels
> Pay listpeerchannels fix

- plugins/Makefile
- plugins/examples/cln-subscribe-wildcard.rs
- plugins/src/lib.rs
- tests/test_cln_rs.py
In Core Lightning plugins can subscribe to notifications using a wildcard `*`.
When the wildcard is used the plugin will receive all notifications.
This behavior was not supported by `cln_plugin`.
The first 2 commits create a plug-in that listens to the the wildcard `*`-subscription
and test the behavior. It appears that `cln_plugin` accepts the subscription but fails when the first plug-in message
is received.
The last commit adapts the `cln_plugin`-crate to support the wildcard.
> `cln_plugin` : Support wildcard subscriptions

- contrib/pyln-client/pyln/client/plugin.py
- tests/test_plugin.py
Without this, everything came out as level INFO.
Changelog-Fixed: pyln-client: Fix Plugin.notify_message() not to ignore `level` parameter.
> pyln-client: pass through level parameter on command notifications.

- contrib/reprobuild/Dockerfile.focal
`jq` is not available in the default repositories of the Ubuntu Focal image. To resolve this, adding the official jq package repository and then installing it.
> docker: Fix jq installation error for focal

- lightningd/anchorspend.c
- tests/test_closing.py
See https://github.com/ElementsProject/lightning/issues/6973
> Log and don't crash on broken anchorspend

- lightningd/plugin.c
This is fixing a bug that @chrisguida reported,
when we notify a plugin we also notify a plugin
that it is in the middle of initialization.
So imagine the following use case:
- 1. Plugin A sends get manifest
- 2. cln makes a check and generates a warning
- 3. Plugin A is subscribed to the warning or * notification
- 4. Core Lightning gets upset because it receives a warning message but it was waiting for a init.
I think it is still a bug in how Core Lightning handles the init, but also I think we should communicate with the plugin only if it is initialized.
```
lightningd-1 2024-04-23T23:20:34.154Z DEBUG   plugin-clnrest: Notification: {'warning': {'level': 'warn', 'time': '1713914433.818230531', 'timestamp': '2024-04-23T23:20:33.818Z', 'source': 'plugin-bookkeeper', 'log': \"topic …
```
> plugin: notify only the plugins with init state

- ccan/README
- ccan/ccan/crypto/siphash24/siphash24.h
- ccan/ccan/io/fdpass/fdpass.c
- ccan/ccan/io/fdpass/fdpass.h
- ccan/ccan/io/io.c
- ccan/ccan/io/io.h
- ccan/ccan/io/poll.c
- connectd/connectd.c
- connectd/connectd.h
- connectd/multiplex.c
- lightningd/channel_control.c
- lightningd/closing_control.c
- lightningd/dual_open_control.c
- lightningd/hsm_control.c
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/onchain_control.c
- lightningd/opening_control.c
- lightningd/options.c
- lightningd/peer_control.c
- lightningd/peer_control.h
- lightningd/test/run-find_my_abspath.c
- tests/test_misc.py
On many systems, the default fd limit is 1024, and we've got users with over 900 channels.  But that's a soft limit, and you can simply ask for an increase!
Also, we should log when we are running low, so people don't have to ask me what to do!
> Increase fd limits (and warn as we approach them)

- doc/lightningd-config.5.md
- plugins/bcli.c
This is a first pass at #2817.  It adds a `--bitcoin-rpcclienttimeout` parameter to `bcli`. It seems those parameters are automatically pulled in as `lightningd` parameters as well. Instead of setting the default value at `900` per the `bitcoind`, we set it to match the `retry_timeout` and then choose the maximum value from arguments gathered by the user.
Don't have much experience in C, but open to learn and contribute to this project where I can.
> Add --bitcoin-rpcclienttimeout CLI parameter

- channeld/channeld.c
- common/hsm_version.h
- hsmd/hsmd.c
- hsmd/hsmd_wire.csv
- hsmd/libhsmd.c
- hsmd/libhsmd.h
Removes returned old_secret from get_per_commitment_point making it safe to call on all commits
Motivation: When get_per_commitment_point returns the old secret it implies a revocation of index - 2. This causes a crash when VLS has validated a commitment but not seen the following revoke of the prior and the channel is asynchronously restarted. See https://gitlab.com/lightning-signer/validating-lightning-signer/-/issues/469
The last two commits in this PR are somewhat optional: by increasing the HSM_VERSION to 6 we can inform the signer that it should never return an old_secret (and therefore can't fail). The native hsmd implementation doesn't have the safety issue and it would be ok to leave it at HSM_VERSION 5. But it's cleaner to have consistent semantics.
All but the last two commits …
> hsmd: make get_per_commitment_point unconditionally safe by not returning secret

- doc/getting-started/getting-started/installation.md
Previously, we only had a single python plugin `clnrest` and the instructions were embedded under other heading.
Adding a new heading for python plugins and their installation instructions will make it easier for users to locate them.
> doc: Updating installation instructions for python plugins

- connectd/connectd.c
- connectd/connectd.h
- connectd/connectd_wire.csv
- connectd/peer_exchange_initmsg.c
- doc/lightningd-config.5.md
- lightningd/connect_control.c
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/options.c
- plugins/Makefile
- plugins/establish_onion_path.c
- plugins/establish_onion_path.h
- plugins/fetchinvoice.c
- plugins/offers.c
- plugins/offers.h
- plugins/offers_invreq_hook.c
- plugins/offers_invreq_hook.h
- tests/test_connection.py
- tests/test_pay.py
This is vital for LDK interop!  They give us a reply path which isn't an immediate peer.
So we do that.  Now we have to handle the case where an attacker makes us open many connections, so we demark these in connectd as "transient" so it knows to throw them away under stress.
Closes: https://github.com/ElementsProject/lightning/issues/7110
> Reply to invoice_request even if we need to make explicit connection to node

- plugins/examples/cln-plugin-startup.rs
- plugins/src/lib.rs
- plugins/src/options.rs
- tests/test_cln_rs.py
I want this in cln-plugin: #7289
So this is my take for cln-plugin on it. The formatting changes are because @cdecker is not using `rustfmt` like a good boy and i noticed it too late, sorry. Some things get a bit weird here and there but overall it works! 
I wanted existing projects to not have to do any changes if they were using static options (so all of them up to now), that's why i added the dynamic switch as a function, instead of an extra argument to the `new_*` functions.
Let me know what you think.
> cln-plugin: Add dynamic configs and a callback for changes

- lightningd/peer_htlcs.c
- plugins/libplugin-pay.c
- plugins/libplugin-pay.h
- plugins/offers.c
- plugins/offers_invreq_hook.c
- plugins/pay.c
- tests/test_pay.py
And fix pay to pay them properly too!
Thanks @carlaKC for the reports!
Closes: https://github.com/ElementsProject/lightning/issues/7161
Closes: https://github.com/ElementsProject/lightning/issues/7179
> offers: fix our blinded path setting in invoices

- contrib/pyln-testing/pyln/testing/db.py
- contrib/pyln-testing/pyln/testing/utils.py
- tests/test_cln_rs.py
- tests/test_clnrest.py
- tests/test_connection.py
- tests/test_gossip.py
- tests/test_misc.py
I could still spot the occasional 
```
Failed to bind socket for 127.0.0.1:44971: Address already in use
```
in some failed CI runs. After some stress testing different methods to get an unreserved port i found the `reserve_unused_port()` function to be the best in a parallel environment so let's use it everywhere! Also moved some calls to it closer to where they are used (i always imagine every line takes 1+ minute in CI :joy:)
> pytests: use reserve_unused_port() everywhere

- .github/workflows/readme-rpc-sync.yml
- tests/test_cln_rs.py
Now that our rpc documenation is generated from schema (since [#6995](https://github.com/ElementsProject/lightning/pull/6995)), we need to build the docs before trying to update the rdme contents.  The goal is to fix the following issue with the rdme-rpc-sync workflow:
Run python .github/scripts/sync-rpc-cmds.py
lightning-addgossip		lightning-addgossip.7.md
File .github/scripts/sync-rpc-cmds.py, line 92, in <module>
main()
File .github/scripts/sync-rpc-cmds.py, line 82, in main
with open(doc/ + file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'doc/lightning-addgossip.7.md'
> doc: update rpc docs before pushing to readme

- common/bech32_util.c
`bech32_charset_rev` is only 128 bytes in size but the `c < 0 || c > 128` check allows for `c` to be equal to 128 which would be out-of-bounds. Fix this off-by-one bug by changing the check to `c >= 128`.
Found by fuzzing the existing `fuzz-bolt12-bech32-decode` harness with UBSan (triggering input: `MUgwMEowMDBKMDMzMzMzgDMzSkswSzNLS0s=`).
```
common/bech32_util.c:88:7: runtime error: index 128 out of bounds for type 'const int8_t[128]' (aka 'const signed char[128]')
SUMMARY: UndefinedBehaviorSanitizer: out-of-bounds-index common/bech32_util.c:88:7 in 
```
> common: Fix off-by-one in `from_bech32_charset`

- lightningd/test/run-log-pruning.c
- plugins/bkpr/test/run-bkpr_db.c
- plugins/bkpr/test/run-recorder.c
- plugins/renepay/routetracker.c
- plugins/renepay/routetracker.h
- plugins/renepay/test/Makefile
- plugins/renepay/test/common.h
- plugins/renepay/test/run-bottleneck.c
- plugins/renepay/test/run-mcf-diamond.c
- plugins/renepay/test/run-mcf.c
- plugins/renepay/test/run-missingcapacity.c
- plugins/renepay/test/run-testflow.c
Add a test that checks `get_route` and `uncertainty_update` behavior's handling of missing channel capacities.
As pointed out in PR #7194: renepay couldn't handle a failed call to `gossmap_chan_get_capacity` leading to
```
2024-04-02T15:27:49.4484027Z lightningd-1 2024-04-02T15:21:59.115Z **BROKEN** plugin-cln-renepay: uncertainty_network_update (line 175) unable to fetch channel capacity
```
in rare cases.
After #7125 this issue was fixed, this PR adds a unit test to confirm that.
Therefore #7194 can be closed.
> renepay: test channel capacity unavailable

- .github/workflows/rdme-docs-sync.yml
- .github/workflows/readme-rpc-sync.yml
- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-listpeerchannels.json
Issue: rpc documentation on the readme server is not being updated.
Updating the path from `doc/**.md` to `doc/schemas/lightning-*.json` for triggering the action because all `doc/*.7.md` files are fully generated by the `tools/fromschema.py` now.
Added manual trigger event for readme's documentation update.
> doc: readme sync trigger fix

- lightningd/opening_control.c
- wallet/wallet.c
- wallet/wallet.h
Some nodes complained about `UNIQUE constraint failed` upon entering recovery mode. Which means they had closed channels inside the DB which were not loaded hence emergencyrecover tried to stub channels at the same ID. So we need to check for occupied channels inside the DB.
It solves: #7187 #7162 #7183
> Function to check if an ID is occupied by any channel inside the DB.

- .github/workflows/readme-rpc-sync.yml
Issue: rpc documentation on the readme server is not being updated.
It is an extension of PR #7326 to fix runtime error from github actions.
> doc: Updating python grpcio-tool dependency

- lightningd/closing_control.c
- tests/test_closing.py
- tests/test_connection.py
https://github.com/ElementsProject/lightning/issues/7242 describes the pain this causes :(
Fixes https://github.com/ElementsProject/lightning/issues/7242
> Ignore --ignore-fee-rates on mutual close, don't massively overpay with LDK nodes

- Dockerfile
- tools/build-release.sh
Supersede https://github.com/ElementsProject/lightning/pull/7208
This PR is cross compiling dockerfiles, except for the python dependencies required by cln-rest.
You will find here the difference build stages.
* The blue stages only run on amd64.
* The pink stages run on the target architecture
* The white stages are running on the architecture of the building machine
On my computer it takes around 30-40min to build. On github action, it takes 3 hours.
I also simplified `tools/build-release.sh` as to just use buildx the way it is intended to be used (no manual creation of manifest)
Note that it assumes that buildx has been configured before running the script (via `docker buildx create --use`)
> Use cross compile in dockerfile, fix arm32 support

- common/gossmap.c
- common/gossmap.h
- gossipd/gossip_store.c
- gossipd/gossip_store.h
- gossipd/gossmap_manage.c
https://github.com/ElementsProject/lightning/issues/7249
Can't see how this is happening on a fresh gossip store, but avoid crashing if it does, and put in more sanity checks in the only place I can see that we might do this.
> Gossmap crash fix

- plugins/renepay/Makefile
- plugins/renepay/mods.c
- plugins/renepay/payplugin.h
- plugins/renepay/renepayconfig.h
- plugins/renepay/uncertainty.c
- plugins/renepay/uncertainty.h
Add a payment modifier that relaxes the knowledge of the uncertainty network as a function of time.
We already had this functionality in version 24.02 but it was missing after the code refactor #7125.
> Renepay relax knowledge

- CHANGELOG.md
- contrib/pyln-client/pyln/client/__init__.py
- contrib/pyln-client/pyproject.toml
- contrib/pyln-proto/pyln/proto/__init__.py
- contrib/pyln-proto/pyproject.toml
- contrib/pyln-testing/pyln/testing/__init__.py
- contrib/pyln-testing/pyproject.toml
- plugins/clnrest/pyproject.toml
- plugins/wss-proxy/pyproject.toml
- poetry.lock
Thanks to everyone who included changelog entries in their commits.  If you did not, please note anything missing from the changelog or correct me where I did my best to describe your work.
> meta: update changelog for 24.05rc1

- plugins/chanbackup.c
This pull request addresses a minor typo fix in the chanbackup plugin.
Changes Made:
Corrected the typo "DUALOPENED_AWAITING_LOCKIN" to "DUALOPEND_AWAITING_LOCKIN".
> chanbackup: typo fix.

- lightningd/peer_control.c
- lightningd/test/run-invoice-select-inchan.c
- tests/test_closing.py
- wallet/test/run-wallet.c
We used to fire up channeld to send this, but:
1. That's silly, we have all the information to make it ourselves.
2. We didn't do it if there was an error on the channel, which as of 24.02
there always is!
3. When it did work, running channeld *stops* onchaind, indefinitely slowing recovery.
Fixes: https://github.com/Blockstream/greenlight/issues/433
> Properly send reestablish on close channels, do it simpler.

- common/sphinx.c
- common/sphinx.h
- common/test/run-sphinx-xor_cipher_stream.c
- lightningd/pay.c
- tests/test_pay.py
- wallet/test/run-wallet.c
Let's remove it again in... um...
Shit, it's going to be there forever, isn't it?
:sob: 
Fixes: #7347
> Restore legacy onion (damn you lnd!)

- .gitignore
- contrib/reprobuild/Dockerfile.focal
- contrib/reprobuild/Dockerfile.noble
- doc/getting-started/advanced-setup/repro.md
- tools/build-release.sh
- tools/repro-build.sh
This PR will help in publishing CLN reproducible binaries for Ubuntu v24.04 (noble).
Please note that I adjusted Dockerfiles for focal and jammy also to keep the base image creation script same for all 
three images. The step update was required because `noble` only runs with ubuntu:noble setup.
> script: Add reproducible build script for Ubuntu v24.04

- CHANGELOG.md
- Cargo.lock
- cln-grpc/Cargo.toml
- cln-rpc/Cargo.toml
- contrib/pyln-client/pyln/client/__init__.py
- contrib/pyln-client/pyproject.toml
- contrib/pyln-proto/pyln/proto/__init__.py
- contrib/pyln-proto/pyproject.toml
- contrib/pyln-testing/pyln/testing/__init__.py
- contrib/pyln-testing/pyproject.toml
- plugins/Cargo.toml
- plugins/grpc-plugin/Cargo.toml
Based on #7371 
1. Plugin things should all be prefixed by `Plugins:` then the name of the plugin altered.
2. New config options should always be named in CHANGELOG.md!
3. Unify groups of changes into a single line, in this case, GRPC.
4. Command, plugin and option names are in backticks.
5. Offers changes are still under EXPERIMENTAL.
> Changelog refresh

- Dockerfile
- tools/build-release.sh
Issue: Docker images for v24.05 were built on clean lightning directory and the published image should be running on v24.05 but it is running as v24.05-modded.
Root cause: Dockerfile builder was running different versions of grpcio-tools and protobuf. It resulted in auto generated update of contrib/pyln-grpc-proto/pyln/grpc/node_pb2.py and contrib/pyln-grpc-proto/pyln/grpc/primitive_pb2.py files.
Solution: Run `poetry install` before make in the dockerfile's builder stage to ensure that the grpcio-tools and protobuf versions are the same.
References:
https://github.com/ElementsProject/lightning/issues/7370#issuecomment-2152952820 
https://github.com/ElementsProject/lightning/pull/7376#issuecomment-2161102381
> docker: poetry install before make

- plugins/offers.c
Our CI do not catch this because we mine 100 blocks to make the funds usable.
However, it is possible to avoid this kind of crash, because
our assert is "wrong" because blockheight can be 0 and the
assert can fail.
In addition, the `rpc_scan` already checks for nullability, so the
assert is redundant
```
2024-06-07T14:14:29.278Z INFO    lightningd: v24.05-modded
2024-06-07T14:14:37.158Z INFO    lightningd: v24.05-modded
2024-06-07T14:14:29.329Z INFO    lightningd: Creating configuration directory /root/.lightning/signet
2024-06-07T14:14:37.589Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
2024-06-07T14:14:29.715Z INFO    lightningd: Creating database
2024-06-07T14:14:37.591Z UNUSUAL lightningd: Waiting for initial block download (this can take a while!) …
```
> offer: make the blockheight nullable

- configure
We do this with typesafe_cb and it's so useful I'm not going to remove it.  But clang 18 complains:
```
ccan/ccan/tal/tal.c:246:6: runtime error: call to function destroy_conn_close_fd through pointer to incorrect function type 'void (*)(void *)'
/home/rusty/devel/cvs/lightning/ccan/ccan/io/poll.c:251: note: destroy_conn_close_fd defined here
```
> configure: don't sanitize function call types.

- contrib/msggen/msggen/schema.json
- doc/developers-guide/deprecations.md
- doc/schemas/lightning-commando-blacklist.json
- doc/schemas/lightning-commando-listrunes.json
- doc/schemas/lightning-commando-rune.json
- doc/schemas/lightning-decode.json
- plugins/commando.c
- tests/test_misc.py
- tests/test_plugin.py
- tests/test_runes.py
- tests/test_wallet.py
We documented them as deprecated in v23.08 but unintentionally didn't deprecate them in the code. Thus we are starting their *actual* deprecation cycle from v24.08 release.
Updated removal version for commands `commando-rune`, `commando-listrunes`, and `commando-blacklist`.
> Commando updating removal version for rpcs

- doc/getting-started/getting-started/configuration.md
Going over the docs in setting/configuring a node, I've found some inconsistencies probably due to markdown autoformatting.
> doc: fix markdown in configuration node options

- contrib/cl-repro.sh
This script is useful for contributors to create reproducible binaries, signing and verifying releases.
> script: Adding cl-repro script for easier builder image building

- pyproject.toml
Since `poetry=1.8.0` there is a non-package mode. This can be used to
create `pyproject.toml` files that are only used to track dependencies.
Performing `poetry install` in the project-root with a recent version of `poetry`
is currently generating a warning which will become an error in the
future.
Setting `package-mode=false` makes this error go away.
A side-effect is that the `name`, `version` and `description` in the
`pyproject.toml`-file will be ignored. Keeping the parameters in the
`pyproject.toml` file ensures it will still work for developers who are
using `poetry<1.8.0`.
> poetry: Use non-package mode

- .github/workflows/docker-release.yml
This PR is adding github action for auto Docker releases. This will streamline Docker image builds & releases for enhanced efficiency, reliability, and consistency in managing Docker-based deployments.
The build & release event will be triggered:
- On any new tag creation without "rc" suffix.
- Manually for testing purposes.
Reference: PR #7331 was also merged to add the original .yml for testing. This is the final PR after it's successful testing.
> docker: Update github actions for Docker releases

- lightningd/peer_htlcs.c
Started seeing these in my test logs, and it's the wrong way around!
Also, fixes flake in test_penalty_htlc_tx_timeout[True]
> lightningd: log BROKEN if we lost funds, only unusual if we closed abandoned HTLC

- .github/workflows/bsd.yml
- .github/workflows/ci.yaml
- .github/workflows/macos.yaml
- .github/workflows/pypi.yml
- .github/workflows/rdme-docs-sync.yml
- .github/workflows/readme-rpc-sync.yml
Github actions was complaining about deprecated CI actions so i updated them all to the latest release version.
The recommended v1 FreeBSD action requries `runs-on: ubuntu-latest`.
> CI: upgrade CI actions to latest releases

- contrib/pyln-client/pyln/client/plugin.py
- tests/plugins/dynamic_option.py
- tests/plugins/zeroconf-selective.py
- tests/test_plugin.py
This is an alternative to #7288, that uses a callback per config
option rather than hooking the `setconfig` function entirely. This
allows us to react to individual config options changing, while still
maintaining the default `setconfig` behavior.
> pyln: Add a dynamic configs and a callback for changes

- lightningd/bitcoind.c
- lightningd/bitcoind.h
- lightningd/chaintopology.c
- lightningd/chaintopology.h
- lightningd/channel_control.c
- lightningd/dual_open_control.c
- lightningd/gossip_control.c
- lightningd/lightningd.c
- lightningd/peer_control.c
- lightningd/test/run-find_my_abspath.c
- lightningd/test/run-invoice-select-inchan.c
- wallet/test/run-wallet.c
- wallet/wallet.c
- wallet/wallet.h
- wallet/walletrpc.c
@ShahanaFarooqui and I spent about 2-3 hours trying to fix this, but the code was fragile and we kept breaking existing cases.
So instead, I started by reworking the code to make it simple, then I change it.  The result is much neater, and will serve us well for any future changes.
Fixes: https://github.com/ElementsProject/lightning/issues/6924
> Wait for bitcoind if it's gone backwards, don't abort.

- doc/getting-started/getting-started/installation.md
This PR adds two dependencies to fix fatal errors when building from source on a fresh install of Ubuntu 24.04 LTS.
This error occurs when installing the python dependencies `requirements.txt` file.
```text
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/user1/myenv/include -I/usr/include/python3.12 -c c/_cffi_backend.c -o build/temp.linux-x86_64-cpython-312/c/_cffi_backend.o
c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
15 | #include <ffi.h>
|          ^~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
[end of output]
note: This error originates from a subprocess, and is …
```
> doc(build): improve Ubuntu build dependencies in installation doc

- plugins/clnrest/clnrest.py
Reference Issue #6931: Fixes `Warning: option ssl_version is deprecated and it is ignored. Use ssl_context instead.`
Curl example with https: 
```
curl --cacert /path/to/certs/ca.pem --header 'Rune: ZrAK...E9MA==' --request POST --url https://127.0.0.1:3010/v1/getinfo
```
> clnrest: Fixes `ssl_version` deprecated warning

- doc/developers-guide/app-development/wss-proxy.md
Bug Fix: The wss-proxy plugin throws error `plugin-wss-proxy: Killing plugin: disabled itself at init: Error in parsing options: 'NoneType' object is not subscriptable` if CLN is not listening on websocket.
Reference: https://github.com/ElementsProject/lightning/issues/7386#issuecomment-2175766309
> doc: Updated warning box for wss-proxy

- cln-rpc/Makefile
The file `cln-rpc/src/notifications.rs` is generated by `msggen`.
The `Makefile` has tooling to update the file when needed
- `make check-gen-updated` should error if file isn't properly updated
- `make gen` updates the file
This comit fixes both behaviors mentioned above.
> Fix: Add `notifications.rs` to $(CHECK_GEN_ALL) target

- ccan/README
- ccan/ccan/bitmap/bitmap.c
- ccan/ccan/bitmap/bitmap.h
- ccan/ccan/io/benchmarks/Makefile
- ccan/ccan/io/benchmarks/run-stream-many.c
- ccan/ccan/io/io.c
- ccan/ccan/io/io.h
- ccan/ccan/io/test/run-43-io_plan_in_started.c
- wire/wire_io.c
A fairly simple change: ccan/io will now call the underlying I/O
routines repeatedly until they indicate they are unfinished, *or* fail
with EAGAIN.  This should make a significant difference to large
nodes, which currently spend far too much time calling poll() to
discover a single fd is still writable (mainly, for streaming gossip).
Changelog-Changed: connectd: now should use far less CPU on large nodes.
Fixes: https://github.com/ElementsProject/lightning/issues/7243
> Connectd speed up #1: spend less time polling.

- plugins/spender/openchannel.c
If the peer sends you their signatures before we return from the *first* openchannel_update then the state would still be in MULTIFUNDCHANNEL_STARTED (not UPDATED) and we'd incorrectly switch the state to MULTIFUNDCHANNEL_SIGNED, which would plunge us headfirst into `check_sigs_ready`.
However the `mfc->txid` hadn't been set yet, so we'd crash when trying to confirm that we've got sigs for the correct txid. Oops.
To fix this, we simply invert the check such that the *only* state that will move into SIGNED is SECURED
> fundchannel: remove crash on race condition

- contrib/msggen/msggen/__main__.py
- contrib/msggen/msggen/utils/utils.py
This PR adds a `missing-grpc` command to msggen which can be used to track down missing grpc methods: https://github.com/ElementsProject/lightning/issues/7167#issuecomment-2016969997
It currently outputs:
```
Missing RPC commands in grpc:
delforward
makesecret
reserveinputs
batching
upgradewallet
openchannel_signed
dev-forget-channel
renepaystatus
autoclean-status
delpay
fundchannel_complete
bkpr-listaccountevents
emergencyrecover
check
sql-template
splice_init
commando-blacklist
openchannel_abort
showrunes
getlog
listinvoicerequests
parsefeerate
multiwithdraw
openchannel_init
disableinvoicerequest
splice_signed
disableoffer
commando-listrunes
notifications
openchannel_bump
bkpr-dumpincomecsv
autoclean-once
checkrune
recoverchannel
fundchannel_start
deprecations
splice_update …
```
> msggen: add `missing-grpc` command

- cln-rpc/src/primitives.rs
In Fedimint we currently call `ShortChannelId::block`, `ShortChannelId::txindex`, and `ShortChannelId::outnum` and then convert these three fields to a `u64`:
https://github.com/fedimint/fedimint/blob/31bbcf6c8d4b2552112bfd525cfa7f0ce06ce0c6/gateway/ln-gateway/src/bin/cln_extension.rs#L1025-L1030
This struct is already represented internally as a `u64`, let's use it!
> chore: add ShortChannelId::to_u64

- .msggen.json
- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/schemas/notification/block_added.json
- doc/schemas/notification/channel_open_failed.json
- doc/schemas/notification/channel_opened.json
- doc/schemas/notification/channel_state_changed.json
- doc/schemas/notification/connect.json
- doc/schemas/notification/custommsg.json
@ShahanaFarooqui points out we that the "added" documentation on the notification schemas is wrong.  Fixing it required modifying files manually, however.
Includes a drive-by fix: we weren't jq-formatting the notification schemas, as noticed by the extra whitespace.
> Fix notification added versions

- .gitignore
With recent updates in PR #7444, the file is created but should not be uploaded to git.
> git: Ignore .doc_version

- .github/workflows/ci.yaml
- README.md
As suggested by @rustyrussell, Adding another step for testing minimum supported Bitcoin version with clang test suite.
> ci: Test minimum supported BTC version

- Makefile
- common/Makefile
- common/onion_message.c
- common/onion_message.h
- common/test/run-bolt12-offer-decode.c
- common/test/run-bolt12_decode.c
- common/test/run-bolt12_merkle-json.c
- common/test/run-bolt12_period.c
- common/test/run-onion-test-vector.c
- common/test/run-route_blinding_onion_test.c
- common/test/run-route_blinding_test.c
- plugins/Makefile
- plugins/establish_onion_path.c
- plugins/establish_onion_path.h
- plugins/fetchinvoice.c
- plugins/fetchinvoice.h
- plugins/offers.c
- plugins/offers.h
- plugins/offers_inv_hook.c
- plugins/offers_inv_hook.h
- plugins/offers_invreq_hook.c
- plugins/offers_invreq_hook.h
- plugins/offers_offer.c
- plugins/offers_offer.h
- tests/test_pay.py
~(Based on #7455)~ Merged!
We unify our onion_message construction routines and use them with the new "injectonionmessage" RPC.  This means we properly support routing where the start of the blinded path is not an immediate peer, which will happen more as the network of onion-message-enabled nodes expands.
We also, finally, add support for offers which use blinded paths, though we don't create them ourselves (except via a dev parameter for testing).
> Part 3: offers with paths

- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-sql-template.json
- plugins/sql.c
Hi. I'm using the SQL plugin to perform analytics on my node. It would be very useful to be able to use the date/time functions so that only the required data is returned.
I've written some queries to test this change and it works as expected.
> plugins/sql: allow datetime functions

- common/gossmap.c
If we need to iterate forward to find a timestamp (only happens if we have gossip older than 2 hours), we didn't exit the loop, as it didn't actually move the offset.
Fixes: https://github.com/ElementsProject/lightning/issues/7462
> common: fix endless loop in gossmap iteration.

- .github/scripts/setup.sh
It appears as if there is a type inference regression in `rustc` resulting in the following errors:
``` raw
cargo build --profile=release --quiet --bin cln-grpc
error[E0282]: type annotations needed for `Box<_>`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
make: *** [plugins/Makefile:264: …
```
> ci: Pin `rustc` to version 1.78 due to a type inference regression

- .github/scripts/setup.sh
- Cargo.lock
- plugins/grpc-plugin/Cargo.toml
- plugins/grpc-plugin/src/main.rs
- plugins/grpc-plugin/src/tls.rs
Related to https://github.com/ElementsProject/lightning/pull/7496
Imho updating the dependency is more elegant than pinning an older version of the Rust compiler. Especially in cases when people compile CLN themselves, they probably don't want to switch Rust versions if they even know that it would solve the compiler error.
> gRPC-plugin rcgen update

- contrib/pyln-proto/pyproject.toml
- poetry.lock
- pyproject.toml
fixes https://github.com/ElementsProject/lightning/issues/7472
please also create a new release of pyln-proto to PyPI once this is merged
> pyln-proto: update cryptography to v42

- lightningd/opening_control.c
This was confusing to debug, but if the peer already exists we must not create a second one.
> lightningd: don't create a second peer on stub recover if one already exists

- conftest.py
```
>           warnings.warn(f"Error reporting testrun: {e}: {e.read()}")
E           AttributeError: 'URLError' object has no attribute 'read'
```
> CI: don't fall over if cannot connect to upload server.

- gossipd/seeker.c
- tests/test_gossip.py
This is a hack, but we've had nodes missing gossip.  LDK does this, so until we get a better workaround, use this one.
Changelog-Changed: Protocol: we now always ask the first peer for all its gossip.
> gossipd: always ask first peer for all the gossip.

- contrib/pyln-client/pyln/client/plugin.py
- doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
- doc/developers-guide/plugin-development/json-rpc-passthrough.md
Category, description and long description from `json_command` and `plugin_command` have been removed in favour of reading them from json schema.  Reference PR: #7485 
Deprecating them in pyln-client as well. They will be removed completely in future releases.
Changelog-Deprecated: pyln-client: category, description and long descriptions for RPC commands are deprecated now.
> pyln-client: Deprecate category, desc and long description from method

- .github/workflows/macos.yaml
- plugins/autoclean.c
macos ci is disabled right now because noone is thinking of the frontend devs. This revives the macos CI which will build and run cln on macos. It discovered a build error in autoclean which i hopefully fixed correctly.
> macos: fix ci and autoclean

- Makefile
- configure
- devtools/Makefile
- devtools/gossmap-compress.c
- tests/test_gossip.py
- tests/utils.py
I've been meaning to do this for a while: create a format for representing the gossip map topology for testing routing.  My gossip store shrinks to about 500k in this format, which is something we could actually check into the repository for testing.
It also provides a nice way to create topologies for python tests.
> Gossmap topology compression and helper

- plugins/fetchinvoice.c
Now we actually check the other fields too, as per BOLT!
Reported-by: https://github.com/hMsats
Fixes: #7513
> offers: fix crash when receiving response to offer without `offer_issuser_id`

- Makefile
- lightningd/lightningd.c
- lightningd/lightningd.h
- tools/rel.sh
We had some weird code to try to do relative paths.  Instead, use absolute ones and keep life simple.  Also rename "daemon_dir" to the clearer "subdaemon_dir" as that's what it's used for.
This might help https://github.com/ElementsProject/lightning/pull/7511#issuecomment-2261549499
> Makefile: clean up install path handling.

- Makefile
- tests/test_reckless.py
- tools/reckless
This PR does several things:
1. Adds an installer for rust plugins.
2. Adds a --version flag.
3. Refactors logging and output.
4. Allows option flags in any order. (previously limited to before subcommands only)
5. Adds a --json output option.
In general, this prepares for a reckless-rpc plugin coming next.
> Reckless: add rust installer and json output

- common/coin_mvt.c
- common/coin_mvt.h
- lightningd/channel_control.c
- onchaind/onchaind.c
- onchaind/test/run-grind_feerate-bug.c
- onchaind/test/run-grind_feerate.c
- plugins/bkpr/bookkeeper.c
- plugins/bkpr/chain_event.h
- plugins/bkpr/db.c
- plugins/bkpr/recorder.c
- plugins/bkpr/test/run-recorder.c
- wallet/test/run-wallet.c
update the coin-movment notifications and the bookkeeper respectively so that splices are properly accounted for (quite literally).
Prior to this we haven't been logging the spend of the funding output for splices (they're simply not recorded). 
Will update with a PR built on #6980 which includes tests for these.
> bookkeeper, meet splicing

- wallet/wallet.c
one of the fields in the database isn't read/accessed during stub reinitialization, so my node crashes on restarts.
patched my node and it resolves the issue (node can now restart after emergency recover called on empty database)
error:
```
Never accessed column last_sig in query SELECT  id, peer_id, scid, full_channel_id, channel_config_local, channel_config_remote, state, funder, channel_flags, require_confirm_inputs_local, require_confirm_inputs_remote, minimum_depth, next_index_local, next_index_remote, next_htlc_id, funding_tx_id, funding_tx_outnum, funding_satoshi, our_funding_satoshi, funding_locked_remote, push_msatoshi, msatoshi_local, fundingkey_remote, revocation_basepoint_remote, payment_basepoint_remote, htlc_basepoint_remote, delayed_payment_basepoint_remote, …
```
> bugfix: node refuses to re-start after emergency recover

- plugins/bkpr/README.md
- plugins/bkpr/bookkeeper.c
- plugins/bkpr/recorder.c
- plugins/bkpr/recorder.h
- tests/plugins/bookkeeper_custom_coins.py
- tests/test_bookkeeper.py
This PR adds two new event types that `bookkeeper` listens for in order to track on-chain movements in external wallets.
This API is currently implemented by the plugin Smaug, which depends on this PR being merged before a release can be cut.
> bkpr: add two custom notifications that we listen for

- common/json_parse.c
- common/json_parse.h
- common/json_stream.c
- common/json_stream.h
- plugins/libplugin-pay.c
- plugins/libplugin-pay.h
- plugins/offers_offer.c
- plugins/pay.c
- plugins/test/run-route-calc.c
- plugins/test/run-route-overlong.c
While performing a payment we attempt to get several HTLCs through
from the sender to the destination. Some of these attempts may fail,
due to temporary unavailability, insufficient balance, or many other
reasons. We use `channel_hint`s to track these failures and compile
the observations into a more detailed view of the network.
So far we were just forgetting all of the inferred information once
the payment is done, however this information is useful for later
payments too, as it allows us to skip attempts that are unlikely to
succeed, and essentially continue the exploration where the previous
payments have left off.
The main issue we face is how do we relax the hints over time, such
that we maximize their usefulness by allowing us to skip channels that
are unlikely to succeed, while at …
> pay: Share channel_hints across payments and plugins

- plugins/renepay/mods.c
- plugins/renepay/payplugin.h
- plugins/renepay/routetracker.c
- plugins/renepay/routetracker.h
When renepay starts, one of the first operations it does is to check for pending sendpays for the same invoice. Those are added up to an internal database to keep track of. Also the amount they deliver to the destination is computed so that the current payment rpc call would try to complete the payment for whatever amount remains to pay. For an incomplete payment after calling the RPC renepay I found this in the logs:
2024-05-22T19:44:19.853Z DEBUG   plugin-cln-renepay: There are pending sendpays to this invoice. groupid = 6 delivering = 0msat, last_partid = 10
Where `delivering` should correspond to the sum of the amounts delivered by pending routes.
> renepay: bugfix reading pending sendpays

- plugins/bkpr/bookkeeper.c
Valgrind found this.  I think two PRs were added in parallel, which is why we only found it after merge:
```
2024-08-09T01:57:23.7375752Z ==34263== Uninitialised byte(s) found during client check request
2024-08-09T01:57:23.7376275Z ==34263==    at 0x172405: memcheck_ (mem.h:247)
2024-08-09T01:57:23.7376661Z ==34263==    by 0x172585: db_bind_int (bindings.c:49)
2024-08-09T01:57:23.7377086Z ==34263==    by 0x126233: log_chain_event (recorder.c:2057)
2024-08-09T01:57:23.7377544Z ==34263==    by 0x11BF8B: json_utxo_deposit (bookkeeper.c:1735)
2024-08-09T01:57:23.7378207Z ==34263==    by 0x12BED3: ld_command_handle (libplugin.c:1847)
2024-08-09T01:57:23.7378674Z ==34263==    by 0x12C649: ld_read_json_one (libplugin.c:1998)
2024-08-09T01:57:23.7379114Z ==34263==    by 0x12C780: ld_read_json …
```
> bookkeeper: fix uninitialized variable.

- common/configvar.c
- common/configvar.h
- doc/lightningd-config.5.md
- lightningd/log.c
- lightningd/options.c
- tests/test_misc.py
fixes #7132
I would really appreciate some friendly feedback on this, as it is my first PR to the project and I might have misunderstood or missed important details.
~~I did find a similar function `strip_trailing_whitespace` in `plugins/bcli.c`, but from what I understand, having `void trim_trailing_spaces(char *str);` in `ccan` would still be beneficial, right?~~
> Fix CLN service startup failure by trimming trailing spaces in config parameters

- common/jsonrpc_errors.h
- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-enableoffer.json
- lightningd/offer.c
- tests/test_pay.py
- wallet/wallet.c
- wallet/wallet.h
Sometimes, for various reasons, a user disables an offer and then wants to re-enable it. This should be allowed because, from the CLN point of view, it is just an internal state.
If a user has constraints on the description of the invoice because they are using services that link some sort of user ID to an offer, it is important for the user to be able to re-enable the offer, not create a new one. Creating a new offer would require a different description.
P.S: This is in an RFC, if it will be accepted I will finish the documentation but I still need to write the test 
Fixes: https://github.com/ElementsProject/lightning/issues/7360
> [RFC] offer: allow re-enabling a previously disabled offer

- lightningd/channel_gossip.c
- lightningd/connect_control.c
- lightningd/lightningd.c
- lightningd/lightningd.h
- tests/test_gossip.py
We didn't force-propagate new gossip to our peers as it happened, only on reconnect.
> Fix gossip update propagation

- plugins/libplugin-pay.c
Fixes: https://github.com/ElementsProject/lightning/issues/7200
> plugin/pay: fix crash if failcodename isn't set.

- plugins/askrene/askrene.c
Fixes bad guide for json_scan. Issue #7552
> askrene: reserve: fix assertion

- plugins/renepay/renepayconfig.h
The time of decay "TIMER_FORGET_SEC" was set to 1 hour, which is very low, it would make the plugin try depleted channels after just a couple of seconds for very small amounts.
I set it to 1 week ~ 6e5 seconds.
This improvement combined with #7540 is truly making Rene pay again!
Tested on mainnet with small amounts.
> renepay: small tweak to decay time

- plugins/renepay/json.c
- plugins/renepay/json.h
- plugins/renepay/main.c
- plugins/renepay/mcf.c
- plugins/renepay/mods.c
- plugins/renepay/payment.c
- plugins/renepay/payment.h
- plugins/renepay/payplugin.h
- plugins/renepay/routebuilder.c
- plugins/renepay/routefail.c
- plugins/renepay/routetracker.c
- plugins/renepay/routetracker.h
- plugins/renepay/test/run-route_map.c
While fixing the bug #7337 I have realized that the mechanism for tracking pending routes internally in renepay is way too complicated, prone to bugs. 
With this PR I wan to reduce that complexity by relying in the internal state as little as possible and using
lightningd as oracle. The tradeoff is that now there is an extra rpc call `listsendpays` for every route computation cycle;
this IO communication is way more expensive that checking the internal database. However the bottleneck of the payment
is the time spent waiting for onion messages from peers, not RPC communication with ligthningd and neither the computation
of the routes.
> Renepay simpler routetracking

- openingd/openingd.c
This is actually totally fair, and LND, which does not support it without an option, rejects.
Thanks to Vincenzo and roasbeef for debugging this for me!
Fixes: https://github.com/ElementsProject/lightning/issues/7221
Changelog-Fixed: Protocol: we can now open unannounced channels with LND nodes again.
> openingd: don't ask for scid_alias in channel type if remote doesn't tell us they support it.

- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/index.rst
- doc/schemas/lightning-reckless.json
- plugins/Makefile
- plugins/recklessrpc.c
~~Based on #7484~~ Merged
Adds a simple plugin to start a reckless process by rpc.  Reads relevant network, lightning directory and config file information to invoke reckless with matching parameters.
> Reckless RPC Plugin

- plugins/examples/cln-plugin-startup.rs
- plugins/src/lib.rs
- plugins/src/options.rs
- tests/test_cln_rs.py
cln-plugin was missing multi-style options. This PR adds them for `string` and `int`
> cln-plugin: add multi options for String and i64

- lightningd/chaintopology.c
- lightningd/watch.c
- lightningd/watch.h
Our hash tables allow duplicate keys, and we use that in a few places. However, the get() function only returns the first, so it's not a good idea with such hash tables.
Another patch fixes this at a deeper level (using different hash table types depending on whether this table can have duplicates), but this is the minimal fix for existing code.
This may be the cause behind us occasionally missing onchain events:
Fixes: https://github.com/ElementsProject/lightning/issues/7460
Fixes: https://github.com/ElementsProject/lightning/issues/7377
Fixes: https://github.com/ElementsProject/lightning/issues/7118
Fixes: https://github.com/ElementsProject/lightning/issues/6951
This fixes them in future: fixing them now will require something else.
Changelog-Fixed: lightningd: occasionally we could …
> lightningd: handle duplicate watches on the same thing correctly.

- lightningd/lightningd.c
Mainly, it just causes complaints if we're running a lightningd which is installed (in which case, my_path is not stolen, unlike running locally installed).
Reported-by: daywalker90
Fixes: https://github.com/ElementsProject/lightning/issues/7569
Changelog-None: regression this release
> lightningd: fix trivial memleak.

- contrib/pyln-testing/pyln/testing/fixtures.py
- tests/test_closing.py
- tests/test_gossip.py
- tests/test_misc.py
- tests/test_plugin.py
Commit 901342b50d0adb2d77418b1382cff4b289c7c9b3 ("pyln-testing: require explicit pattern for BROKEN messages.") changed to a manual scan of logs rather than using is_in_log, so it needs to manually refresh, otherwise we miss final log messages.
This causes us to often miss memleak messages, which are printed only in the exit path!
Reported-by: Lagrang3
Fixes: https://github.com/ElementsProject/lightning/issues/7565
> pyln-testing: fix catching of memleak/broken errors at exit.

- plugins/renepay/flow.c
- plugins/renepay/flow.h
- plugins/renepay/main.c
- plugins/renepay/mcf.c
- plugins/renepay/mcf.h
- plugins/renepay/payment.c
- plugins/renepay/payment.h
- plugins/renepay/payment_info.h
- plugins/renepay/routebuilder.c
- plugins/renepay/test/run-bottleneck.c
- plugins/renepay/test/run-mcf-diamond.c
- plugins/renepay/test/run-mcf.c
- plugins/renepay/test/run-missingcapacity.c
The probability for a success forward of `x` amount on a channel is now
computed as:
```
P_success(x) = b * P_rene(x)
```
where `P_rene(x)` is the probability distribution proposed by @renepickhardt 
with a uniform distribution on the known liquidity of the
channel and `b` is a new parameter we add in this PR, by the name of
"base probability". The "base probability" represents the probability
for a channel in the network chosen at random to be able to forward at
least 1msat, ie. of being alive, non-depleted and with at least one HTLC
slot. We don't know the value of 'b', but for the moment we assume that
it is 0.98 and use that as default.
As a consequence the probability cost becomes non-linear and non-convex
because of the additional constant term:
```
Cost(x) = - log P_success(x)
= - …
```
> Renepay const prob cost

- contrib/docker/Dockerfile.builder.fedora
- contrib/reprobuild/Dockerfile.focal
- contrib/reprobuild/Dockerfile.jammy
- contrib/reprobuild/Dockerfile.noble
- Added missing mako and grpcio-tools for ubuntu distro Docker files
- Fixed incorrect bitcoincore link
Changelog-Fixed: Fedora, focal, jammy & noble's failing reproducible builds are fixed now.
> docker: Docker file fixes for reproducible builds

- plugins/sql.c
- tests/test_plugin.py
Fixes a crash when there is a missing object which has subobjects (only happens in one place, listpeerchannels on unfinished channel which doesn't have an `updates` object yet).
Fixes: https://github.com/ElementsProject/lightning/issues/7505
> Sql plugin crash fix

- plugins/renepay/chan_extra.c
- plugins/renepay/chan_extra.h
- plugins/renepay/flow.c
- plugins/renepay/flow.h
- plugins/renepay/mcf.c
- plugins/renepay/mods.c
- plugins/renepay/routebuilder.c
- plugins/renepay/test/common.h
- plugins/renepay/test/run-bottleneck.c
- plugins/renepay/test/run-mcf-diamond.c
- plugins/renepay/test/run-mcf.c
- plugins/renepay/test/run-testflow.c
- plugins/renepay/uncertainty.c
- plugins/renepay/uncertainty.h
- tests/test_renepay.py
~~Make knowledge update and removal of pending HTLCs atomic to avoid race conditions.~~
A quick and dirty solution: comment the assertion making sure the rest of the code in `linearize_channel` can handle the
offending cases (for which `known_max<htlc_total`).
Fixes #7535.
> renepay: bugfix assertion htlc_total<=known_max

- lightningd/lightningd.c
```
**BROKEN** lightningd: MEMLEAK: 0x55ff8e8ec268
**BROKEN** lightningd:   label=char[]
**BROKEN** lightningd:   alloc:
**BROKEN** lightningd:     ccan/ccan/tal/tal.c:488 (tal_alloc_)
**BROKEN** lightningd:     ccan/ccan/tal/tal.c:517 (tal_alloc_arr_)
**BROKEN** lightningd:     ccan/ccan/tal/str/str.c:81 (tal_vfmt_)
**BROKEN** lightningd:     ccan/ccan/tal/str/str.c:37 (tal_fmt_)
**BROKEN** lightningd:     lightningd/lightningd.c:557 (find_subdaemons_and_plugins)
**BROKEN** lightningd:     lightningd/lightningd.c:1196 (main)
**BROKEN** lightningd:   parents:
**BROKEN** lightningd:     struct plugins
```
Changelog-None: Introduced this release.
Fixes: https://github.com/ElementsProject/lightning/issues/7590
> lightningd: fix another trivial memleak when running installed version.

- .github/workflows/docker-release.yml
- Dockerfile
- Temporarily adding `rc` tag trigger, some input variables & more logs for testing `Build and push multi-platform docker images` action flow before the final release.
- **Poetry on arm32:** The Docker build for `linux/arm/v7` failed in recent RC releases on the Poetry installation step in the `builder-python` stage. This issue occurred because the `builder-python` stage builds on target's arch but poetry was unable to install on arm/v7 without rust >= v1.56.1.
- **Solution:** Instead of installing poetry on the `builder-python` stage, we leveraged the existing multi-arch `builder` stage, which already had Poetry. Now, we export the dependencies from `pyproject.toml` to `requirements.txt` within the `builder` stage and then copy `requirements.txt` to the `builder-python` stage for pip …
> GitHub docker testing

- .github/workflows/bsd.yml
- .github/workflows/pypi.yml
>
>
- Passing bitcoind version from matrix
- cleanup: Removed extra tabs and `-` from pypi.yml
Changelog-Fixed: Github action for FreeBSD setup
> github: Update FreeBSD Test

- plugins/askrene/askrene.c
- plugins/askrene/mcf.c
- tests/test_askrene.py
- tests/test_renepay.py
This actually fixed the issue pointed out by @daywalker90 
It's a bit of a hack: I'm assuming that we have some cumulative overflow in our calculations somewhere, as we do use sats not millisats for efficiency.
> Real getroutes fixes

- tools/repro-build.sh
>
>
Since we added support for Ubuntu 24.04, it was installing `zlib1g-dev` version `1:1.3.dfsg-3.1ubuntu2`. However zlib released minor update version `1:1.3.dfsg-3.1ubuntu2.1` on Aug 9th.
```
zlib (1:1.3.dfsg-3.1ubuntu2.1) noble-proposed; urgency=medium
* SRU: LP: #2076340: No-change rebuild to pick up changed build flags
on ppc64 and s390x.
```
Which changed SHASUMS for our noble repro-build.sh and broke the build-release process. 
1: Either we can update the script with the latest zlib1g-dev SHASUMS Or
2: Lock the zlib1g-dev version to `1:1.3.dfsg-3.1ubuntu2`.
For now, I am updating the SHASUMS & version but we …
> script: Updating SHASUMS for updated zlib1g-dev in Ubuntu Noble

- Makefile
- lightningd/lightningd.c
Commit a1fdeee76b "Makefile: clean up install path handling." broke the ability to configure with one path and then run in a different path.  Turns out people actually do this!  So, we have to use relative paths, compared to our existing binary.
Fixes: https://github.com/ElementsProject/lightning/issues/7595
>
>
Please provide a brief summary of the changes made in this PR. What does it do, and why is it necessary?
List any related issues, bugs, or feature requests that are being addressed by this PR. Link them using GitHub's closing syntax (e.g., `Closes #123`).
- Closes #issue_number
Ensure the following tasks are …
> lightningd: fix up installs in subdirectories.

- Dockerfile
>
>
With PR [#7618](https://github.com/ElementsProject/lightning/issues/7618), Core Lightning installation with relative paths has been fixed and can be used again.
> Docker relative install cleanup

- .github/workflows/docker-release.yml
- .github/workflows/pypi.yml
- Dockerfile
- Makefile
- tools/repro-build.sh
>
>
Changelog-Fixed: Regex expression for github actions tags push trigger.
> github: Actions trigger of tag push

- contrib/cln-tracer/README.md
Some minor changes to the `cln-tracer` readme.
- There was a typo in the `libbpfcc` dependency
- add usage and prerequisites
> cln-tracer: readme usage clarifications

- doc/contribute-to-core-lightning/release-checklist.md
- doc/getting-started/advanced-setup/repro.md
- Updated `release-checklist` with new GitHub actions for Docker and PyPI publishing.
- Updated `repro` with information about the `cl-repro.sh` script.
> doc: After release instructions update

- doc/contribute-to-core-lightning/coding-style-guidelines/writing-json-schemas.md
- tests/autogenerate-rpc-examples.py
Spelling and clarity on how to update schemas when you have added an RPCs.  It wasn't super clear you have to run `make` again to get schema.json to update.  This will help newcomers in the process of adding new RPCs, and make it easier to ctrl-f to find things with the correct spelling.
- [na] Changelog has been added in relevant commit/s.
- [na] Tests have been added or updated to cover the changes.
- [na] Any relevant comments or `TODOs` have been addressed or removed.
Found these while helping to add the bkpr-editdescription RPCs.  Used the Grazie Clion plugin to find additional typos and grammar fixes.
> Docs: clarify writing-json-schemas.md and autogenerate-rpc-examples.py

- channeld/channeld.c
send_tlvs is NULL if no special features are supported, and peer sets `next_to_send` anyway:
```
0x5ed1c6719538 peer_reconnect
channeld/channeld.c:5205
0x5ed1c6719dab init_channel
channeld/channeld.c:5959
0x5ed1c6719f04 main
channeld/channeld.c:6005
```
Backport: v24.08
Fixes: https://github.com/ElementsProject/lightning/issues/7486
> channeld: fix crash with pre-TLV peers.

- lightningd/plugin.c
Lightningd should log if a builtin plugin fails to start instead of silently skip over it.
This would allow to debug situations like #7595.
> Log if builtin plugin fails to start

- lightningd/channel.c
- lightningd/opening_control.c
If we pull and old channel from the database, it might not.
Fixes: https://github.com/ElementsProject/lightning/issues/7645
Changelog-Fixes: lightningd: crash when starting channeld for older channel with no local alias.
> lightningd: make sure channels always have a local alias.

- wire/wire_io.c
Our low-level ccan/io IO routines return three values: -1: error.
0: call me again, I'm not finished.
1: I'm done, go onto the next thing.
In the last release, we tweaked the sematics of "-1": we now opportunistically call a routine which returns 0 once more, in case there's more data.  We use errno to distinguish between "EAGAIN" which means there wasn't any data, and real errors.
However, if the underlying read() returns 0 (which it does when the peer has closed the other end) the value of errno is UNDEFINED.  If it happens to be EAGAIN, we will call it again, rather than closing.  This causes us to spin: in particular people reported hsmd consuming 100% of CPU.
The ccan/io read code handled this by setting errno to 0 in this case, but our own wire low-level routines *did not*.
Fixes: …
> subds: fix case where we keep retrying on EOF.

- plugins/topology.c
- tests/test_plugin.py
Erroneous check made us complain every time we *output* a deprecated field in listchannels.
Fixes: https://github.com/ElementsProject/lightning/issues/7652
> Fix listchannels includeprivate broken

- plugins/src/logging.rs
In commit 60e1532dd89ec8a434ce4b31359c54558c41b4b1 (released in crate 0.1.8), which switched the logging framework to tracing-subscriber, the default log level filter was (accidentally) set to ERROR and above, instead of INFO and above.
Change this back to INFO as it was before. It can still be overridden with environment variable `CLN_PLUGIN_LOG`.
Follows the example in https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#method.from_env
- Closes #7658.
Changelog-Fixed: cln-plugin: Change default log level filter back to INFO
- N/A Tests have been added or updated to cover the changes.
- N/A Documentation has been updated as needed.
- N/A Any relevant comments or `TODOs` have been …
> cln-plugin: Change default log level filter back to INFO

- lightningd/plugin.c
- tests/plugins/broken.py
- tests/test_plugin.py
Thanks to @m-schmoock for the excellent bug report.
Fixes: https://github.com/ElementsProject/lightning/issues/7671
> Fix plugin startup crash

- tests/test_connection.py
I discovered that a node even and specifically when started `--offline` mode still tries to acquire a listening socket (and would fail to start if it is already bound!)
Also noteworthy, that an `--offline` node can make outbound connections when done via CLI (or by a plugin like clboss or similar).
Extend the testcase a bit and make it an `xfail` for the time being.
I think that an offline node needs to be really offline, because it may harm developers when trying to debug real world data 'in offline mode' and then a connection is made by mistake and a live network channel can end up in an invalid state.
This means that it should not try to bind a listening socket as well as forbid to make manual connections via cli, because a plugin that does not know the node is 'offline' can …
> pytests: extend the offline mode testcase

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- doc/contribute-to-core-lightning/release-checklist.md
- tests/test_clnrest.py
- tests/test_gossip.py
- tests/test_misc.py
- tests/test_plugin.py
> Makefile: Next version update to 24.11

- lightningd/channel.c
- lightningd/channel.h
- lightningd/channel_state.h
- lightningd/opening_control.c
- lightningd/peer_control.c
- lightningd/peer_htlcs.c
- lightningd/test/run-invoice-select-inchan.c
- wallet/test/run-db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
- wallet/wallet.h
This is an alternative to https://github.com/ElementsProject/lightning/pull/7611
> Remove db accesses in listpeerchannels

- Cargo.lock
- cln-grpc/Cargo.toml
- cln-rpc/Cargo.toml
- plugins/Cargo.toml
- plugins/grpc-plugin/Cargo.toml
Upgrade tonic to v0.12 for rust bins v0.1.9
Description
This PR upgrades the tonic dependency of the rust libraries to v0.12. Latest version used was v0.8. Tonic had some major bugfixes in between these versions. We need to upgrade tonic for downstream consumers of our libs to be able to upgrade tonic as well.
This PR also introduces a new versioning scheme where we bump the minor semver version on any breaking api change such as the removal of deprecated calls as well as changes to the requirements of fields.
The whole rust lib stack cln-grpc cln-rpc cln-plugin and cln-grpc-plugin is now on v0.2.x, on top of tag cln v24.02.2 for the underlying message scheme.
> Rust-bins: Upgrade tonic to v0.12 for v0.1.9

- wallet/wallet.c
When building a tx to spend *now* we shouldn't include CSV locked utxos as we want them to be immediately spendable.
(This is a subset of #7593)
> anchors: dont include utxos which are csv locked

- doc/lightning-hsmtool.8.md
- tests/test_wallet.py
- tools/hsmtool.c
This allows tools to validate that it is accessing the correct hsm_secret for this node!
This is extremely important for backups: if they are using VLS, they need to back *that* up instead, for example.
Changelog-Added: `hsmtool`: `getnodeid` command derives the node id from the hsm_secret, to verify it's the correct secret.
> hsmtool: provide nodeid from hsm secret.

- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/index.rst
- doc/schemas/lightning-getemergencyrecoverdata.json
- plugins/chanbackup.c
- tests/test_misc.py
This Pull Request introduces a new RPC command, `getemergencyrecoverdata`, designed to fetch and return data from the emergency.recover file.
Addresses #7283
> Add getemergencyrecoverdata RPC Command to Fetch Data from emergency.recover File

- contrib/pyln-testing/pyln/testing/fixtures.py
- contrib/pyln-testing/pyln/testing/utils.py
This PR adds a post-yield resolver sanity-check to the `bitcoind` test fixture to be sure file descriptors are not leaking.
- Closes #7130 (if it works)
- I made this PR with the faint hope that it might be related to the build failures in #7310 as well. Need to trigger CI to see...
Please let me know if there is a more elegant way to do this, or more appropriate place to put it.
> pyln-testing: Fix BitcoinD FD leak

- Makefile
- doc/contribute-to-core-lightning/testing.md
This is a small PR intended to slightly improve developer experience. When running the Pytest integration testing suite locally using the command `make pytest`, the build system takes care of altering the local context variable `PYTHONPATH` to make sure contributed modules are accessible to the process. While this works great for running the entire test suite, oftentimes developers are concerned with repeatedly running a subset of the tests, the particular test relevant to the functionality they are working on, or some problematic tests which the suite reports failing.
Currently, in order to target specific tests for a `pytest` run, a developer might:
1. Run `make pytest`
2. Observe the output to discern and capture the computed value for `PYTHONPATH`
3. Copy this value
4. Export the …
> pytest: DX - Support targeting specific tests using `make pytest` w/ `PYTEST_TESTS`

- lightningd/pay.c
- wallet/wallet.c
- wallet/wallet.h
This was incorrect once we stopped removing old payments on failure, which was the reason we had to remove the HTLCs.
It also removed by partid, which is wrong since it should have done old_payment->partid and old_payment->groupid!
(This is a subset of https://github.com/ElementsProject/lightning/pull/7640)
> lightningd: remove incorrect old-payment-htlc-delete logic.

- doc/contribute-to-core-lightning/release-checklist.md
> docs: Updating release checklist with Hotfix release instructions

- plugins/channel_hint.c
- plugins/channel_hint.h
- plugins/libplugin-pay.c
- plugins/test/run-route-calc.c
- plugins/test/run-route-overlong.c
For nodes with many channels this is a tremendous improvement in pay performance. PR #7611 improves payment performance from 15 seconds to 13.5 seconds on one of our nodes. This commit improves payment performance from 13.5 seconds to 5.7 seconds.
Changelog-Fixed: Improved pathfinding speed for large nodes.
Replaces #7648
> [!IMPORTANT]
> libplugin-pay: use map for channel hints

- common/gossmap.c
- common/gossmap.h
- gossipd/gossip_store.c
- gossipd/gossmap_manage.c
- plugins/topology.c
Since we don't compact the gossmap on the fly (FIXME!) we can easily surpass 4GB in the gossmap, and 32 bit offsets are not sufficient.
I'm a bit surprised we don't crash immediately, but we've definitely seen issues.
Changelog-Fixed: gossipd: crash errors with large gossip_store (>4MB) growth on longer-running nodes.
Fixes: #7689 (maybe!)
> 64 bit gs offsets to fix gossip_store crashes

- Cargo.lock
- cln-grpc/Cargo.toml
- cln-rpc/Cargo.toml
`cln-rpc` is the last upstream fedimint dependency that's blocking us from upgrading to `bitcoin` v0.32 😄
Can we prioritize new releases for `cln-grpc` and `cln-rpc` crates? Should release versions with `bitcoin` v0.31 and then bump to v0.32 and do another release to make the upgrade process easier.
> chore: bump rust bitcoin to 0.31

- plugins/libplugin-pay.c
The direct_pay payment modifier would query all peer channels, while
only the channels of the given peer suffices.
Multiple places in the pay lifecycle depend on mods to be set. By
setting the mods directly after the first listpeerchannels call,
subsequent calls to listpeerchannels are avoided.
> pay-plugin: less listpeerchannels load

- tools/Makefile
Whenever we build without `make clean` first, this file gets overwritten. It asks the user for input because it is not run with `-f`. This causes the build to hang until the user inputs `y`.
Here is an example build:
```
$ make -j7 && sudo make install
CC: cc -DCLN_NEXT_VERSION="v24.08" -DPKGLIBEXECDIR="/usr/local/libexec/c-lightning" -DBINDIR="/usr/local/bin" -DPLUGINDIR="/usr/local/libexec/c-lightning/plugins" -DCCAN_TAL_NEVER_RETURN_NULL=1 -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -Wshadow=local -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I …
```
> make: Change `mv` to `mv -f` when replacing tools/headerversions file

- connectd/peer_exchange_initmsg.c
tmpctx may not get cleaned immediately, so the timeout (a child of the struct early_peer at this point) can still outlast the conn!
Changelog-Fixed: connectd: crash on erroneous timeout.
Fixes: https://github.com/ElementsProject/lightning/issues/7728
> connectd: fix double-free crash on connection timeout.

- doc/contribute-to-core-lightning/code-generation.md
Commit 0251b45027827cc4d614705f6c6b5c884d12dd3f moved the location of the `rust.py` file. This PR adjusts sources to changes.
> doc: update reference to the generator code

- doc/developers-guide/app-development/grpc.md
Adds some additional documentation around generating custom gRPC SSL certificates.
1. Fixes anchor links to point to the `gprc` page instead of redirecting to `app-development`.
2. Adds a clarifying example depicting that "lightning" directory should actually be the network subdirectory, as certs are stored there.
3. Adds an additional section of documentation for generating SSL certificates using Subject Alternative Names.
After struggling with properly generating custom certificates for a long time while trying to run the API under both Tor and SSL, as well as allow another local service to communicate with the gRPC APIs, I'm submitting the process that …
> doc: gRPC SSL certificate documentation improvements

- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-listforwards.json
- lightningd/forwards.c
- tests/test_misc.py
This pull request fixes #7157 by altering the JsonRpc return value of `listforwards` to always return a value for the `received_time` field, initializing it to `0` if not found. These values could be missing as a result of forwarding attempts that were created prior the implementation of tracking this data, ostensibly in `v0.7.0` (?).
This also removes the `COMPAT_V070` compiler directive logic for `forwards.c`. Since `received_time` is `required` by the JSON schema, the old backward compatibility strategy is breaking and no longer viable.
I wasn't 100% sure which layer to address this issue in. Some alternative implementation ideas were:
1. Add a `default` key to the `received_time` field in the `listforwards` response definition in the JSON schema …
> lightningd: Default value for `received_time` in `listforwards` to 0

- common/jsonrpc_errors.h
- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/index.rst
- doc/schemas/lightning-injectpaymentonion.json
- lightningd/htlc_set.c
- lightningd/htlc_set.h
- lightningd/invoice.c
- lightningd/pay.c
- lightningd/pay.h
- lightningd/peer_htlcs.c
- lightningd/peer_htlcs.h
- lightningd/test/run-invoice-select-inchan.c
- tests/test_pay.py
- tests/utils.py
- wallet/test/run-wallet.c
This is a new RPC, improving on `sendonion`, which takes the same path as an onion coming in an HTLC from a peer.  This vastly simplifies handling cases like blinded paths which start at this peer, and self-pay: both are handled automatically.
In addition, the call simply blocks, rather than requiring another call to receive the results.
> Injectpaymentonion

- gossipd/gossmap_manage.c
According to the description, we should be checking the existence of a channel update on the other side here.
> [!IMPORTANT]
> gossipd: Correct evaluation of new channel announcement timestsamp

- .github/workflows/repro.yml
- Makefile
- contrib/reprobuild/Dockerfile.focal
This pull request attempts to address #7117 to implement Github Actions CI/CD to perform nightly reproducible builds. The goal is to catch local file changes that might emerge through the build process and result in a `-modded` release version. Currently supporting `focal`, `jammy` and `noble` Ubuntu releases.
Have been testing by adding the following to the `on` key of `.github/workflows/repro.yml`:
```
push:
branches:
- 7117-repro-nightly-builds
```
Add adding some temporary commit to dirty the tree in the `contrib/reprobuild/Dockerfile.[release]`
- Closes #7117 and hopes to score the bounty :)
- Added an entry to the CHANGELOG -- it was the first one observed since the last release, so also added the front matter.
- I …
> Repro nightly builds

- .github/workflows/ci.yaml
Skip CI failure if the PR description includes change log as None, even if the commits lack a change log entry.
Suggested-By: @rustyrussell 
> github: Check if Changelog-None is in PR description

- plugins/fetchinvoice.c
- tests/test_pay.py
Cherry-picking a small patch found in https://github.com/ElementsProject/lightning/pull/7786 and leaving the `git rebase` magic resolving commit history when merged
____
> bolt12: fix typo about parameters name in err str

- .github/workflows/ci.yaml
- contrib/giantnode.py
If the PR Description has special characters, the CI fails while trying to search for the `Changelog-None` entry.
Reference Issue: https://github.com/ElementsProject/lightning/pull/7750
> Fix: CI error from PR descriptions due to special characters

- plugins/renepay/json.c
- plugins/renepay/main.c
- tests/test_renepay.py
This remove an unnecessary check for existing description field if the description_hash is provided in the invoice. The bolt11_decode function already checks the description against the hash if both are provided.
Changelog-Fix: renepay: allow to pay BOLT11 invoices with description_hash, the description field is made optional
Fixes #7777
> renepay: pay BOLT11 invoices with description_hash

- Makefile
- channeld/channeld.c
- channeld/channeld_wire.csv
- devtools/gossmap-compress.c
- doc/Makefile
- lightningd/channel_control.c
- tests/plugins/Makefile
- tests/plugins/channeld_fakenet.c
- tests/test_askrene.py
- tests/test_xpay.py
- tools/hsmtool.c
A replacement subdaemon which does just enough to pretend it's talking to the peer, but it's actually simulating the network.  It can do this because it knows all the private keys (generated by gossmap-compress, or for l2, our test harness).
> Fakechanneld for testing against real topology.

- Makefile
Downstream, having a target for just building, but not running (i.e
`check-fuzz`) the fuzz targets, would be useful. Currently we just apply
this patch before building lightning in various workflows. However if
it's possible to have this upstreamed, as a convenience, that'd be
great.
Changelog-None
> build: add `all-fuzz-programs` target

- contrib/pyln-testing/pyln/testing/utils.py
- doc/lightningd-config.5.md
- plugins/grpc-plugin/src/main.rs
- tests/test_cln_rs.py
- tests/test_clnrest.py
- tests/test_plugin.py
The gRPC server will always start this way. Current port choice is arbitrary, open to suggestions.
closes: #7473
> plugins/grpc: default value for grpc port

- contrib/pyln-testing/pyln/testing/utils.py
No cln-grpc means no "grpc-port" option!  I often test this way, with RUST=0 for speed.
Changelog-None
> pyln-testing: don't fail to start node if we have no Rust.

- plugins/autoclean.c
> Autoclean gentler

- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/options.c
- lightningd/peer_htlcs.c
- tests/test_pay.py
When receiving a forward request lightningd selects the best channel with
the next peer based on its ability to add an HTLC and its spendable amount.
If two forwarding request arrive at the same time pointing to the same
peer we can have a race condition in which both HTLCs compete
concurrently for the same spendable amount.
There shouldn't be a race condition if both requests are supposed to be
allocated on different parallel channels. However, non-strict forwarding is allowed
in the protocol and it is reasonable that node operators can decide which channel
to use when forwarding to a peer.
Therefore we add configuration option `dev-strict-forwarding` default to false,
to enforce strict forwarding. With that flag we no longer need to skip  parallel channel
tests in renepay (9d88ce3).
- …
> Add strict-forwarding option

- ccan/README
- ccan/ccan/opt/opt.h
- ccan/ccan/tcon/tcon.h
- common/configvar.h
- common/hsm_encryption.c
- common/hsm_encryption.h
- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
- doc/index.rst
- doc/lightningd-config.5.md
- doc/schemas/lightning-exposesecret.json
- lightningd/configs.c
- lightningd/options.c
- lightningd/plugin.c
- plugins/.gitignore
- plugins/Makefile
- plugins/exposesecret.c
- tests/test_plugin.py
- tools/hsmtool.c
As co-programmed with @ShahanaFarooqui .
If you set `exposesecret-passphrase` you can use that to retrieve the hsm_secret using the `exposesecret` command.  It doesn't handle encrypted hsm secrets (if you're prepared type in the secret on every start, you don't want this).
> exposesecret: a way to back up the hsm_secret via rpc (if enabled!)

- gossipd/gossmap_manage.c
- lightningd/channel.c
- lightningd/channel.h
- lightningd/gossip_control.c
- lightningd/onchain_control.c
- lightningd/peer_control.c
- lightningd/subd.c
- lightningd/subd.h
- lightningd/test/run-invoice-select-inchan.c
- onchaind/onchaind.c
- onchaind/onchaind_wire.csv
- onchaind/test/run-grind_feerate.c
- tests/test_closing.py
- wallet/db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
- wallet/wallet.h
We have a report of onchaind not sweeping properly.  It seems to be missing an output during replay, which makes sense since Greenlight restarts nodes (a lot!).
See https://github.com/Blockstream/greenlight/issues/433
I've also got a similar issue on my node, but I assumed that was me corrupting the database by editing it long ago.  I will, however, test this fix on my node too...
> onchaind: replay using real block data, not db

- doc/lightning-hsmtool.8.md
- tests/test_wallet.py
- tools/hsmtool.c
Creating a hsm_file with `hsmtool` is currently an interactive process in terminal where user is expected to make choices for language, typing in seed phrase, etc. This works well, but is difficult to utilize for automated installs (ie. Docker, unattended-installs, etc). 
This adds a new method: `generatehsmbyargs` that allows the user to input all required args on command-line and generate the hsm_file without terminal interaction. 
Also the documentation was `lightning-hsmtool.8.md` updated to include new method. 
All existing functionality was preserved, this only added a new method.
> hsmtool.c - Added new method to enable creation of hsm_file from cmd-line args

- bitcoin/pubkey.c
Spotted a number being used instead of the macro constant.
Changelog-None
> secp256k1 pubkey constant fix

- doc/getting-started/getting-started/installation.md
Simple install doc update. Rust needs `protobuf` installed.
> Update Mac install instructions

- contrib/pyln-testing/pyln/testing/utils.py
- lightningd/onchain_control.c
- plugins/Makefile
- tests/plugins/Makefile
- tests/test_askrene.py
- tests/test_cln_rs.py
- tests/test_closing.py
- tests/test_connection.py
- tests/test_gossip.py
- tests/test_pay.py
- tests/test_plugin.py
- tests/test_reckless.py
- tests/test_wallet.py
- tools/hsmtool.c
> pytest: more flake fixes

- contrib/msggen/msggen/schema.json
- contrib/pyln-testing/pyln/testing/utils.py
- doc/developers-guide/deprecations.md
- doc/schemas/lightning-decodepay.json
- lightningd/invoice.c
- tests/autogenerate-rpc-examples.py
- tests/test_cln_rs.py
- tests/test_invoices.py
- tests/test_misc.py
- tests/test_opening.py
- tests/test_pay.py
- tests/test_plugin.py
It only works on BOLT11, and has long been replaced by the more generic "decode".
Removing it will stop the confusion!
(Note: documentation claims it was introduced in 23.08, but that was
wrong, as it's been in CLN since the beginning).
Fixes: https://github.com/ElementsProject/lightning/issues/6419
Changelog-Deprecated: JSON-RPC: `decodepay`: use `decode`.
> lightningd: deprecate decodepay.

- tests/test_splice.py
- tests/utils.py
Add tests for bookkeeping for splicing. Test that funds are allocated and accounted for appropriately, along with on-chain fees, for both splice-in and splice-out.
Note that fees for splices are attributed to the channels that the funds are spliced into/out of.
Built on #7533 and #6980. Start at commit 01da4834212629f6a6496e77831a1744f906d94d.
[Those are merged!  Rebased on master --RR]
Changelog-None: just tests...
> bookkeeper testing for splice-in + splice-out

- contrib/pyln-client/pyln/client/lightning.py
- tests/test_restart.py
Repeatedly STFU and then TX_ABORT a channel to trigger the socket/fd flake issue.
Changelog-None
> Agressive Channeld Restart Testing

- lightningd/subd.c
```
Ubuntu clang version 19.1.0 (++20240901083933+6d7e428df611-1~exp1~20240901084058.28)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-19/bin
./configure CC=clang-19
make -j17
<snip>
cc lightningd/offer.c
cc lightningd/signmessage.c
lightningd/subd.c:945:16: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
945 |         char permfail[strlen("PERMFAIL")];
|                       ^~~~~~~~~~~~~~~~~~
cc wallet/db.c
```
Changelog-Fixed: build: fix overzealous warning from clang 19.
> [!IMPORTANT]
Fixes: #7634
> lightningd: fix clang 19 compile error.

- tools/headerversions.c
Commit 531845971cf94d8e5c0de67c8531578bc2656353 broke the build without SQLite because this code:
new = tal_fmt(NULL, template,
IF_SQLITE3(sqlite3_libversion_number()));
preprocesses into:
new = tal_fmt(NULL, template,
);
which has a syntax error. Fix it by moving the comma into the macro argument.
Fixes: 531845971cf94d8e5c0de67c8531578bc2656353
Changelog-None
> [!IMPORTANT]
> tools/headerversions.c: fix build without SQLite

- contrib/pyln-client/pyln/client/plugin.py
- contrib/pyln-client/tests/test_plugin.py
- tests/test_plugin.py
The extended usage information (long_description) has been removed a while ago without proper replacement. ( commit 2ff3e55f0  Date:   Mon Jul 29 17:58:43 2024 -0700 )
- adds a optional `description` parameter to a plugin method via docstring that will (if set) be appended with a newline following the generated usage argument list.
- adds method usage to plugin.print_usage()
- adds a testcase that checks if extended usage information is passed to manifest json and `print_usage`
- Maybe we want to add an optional getmanifest json description field and use that instead of internally appending it with newline to the usage
> pyln_client: (re-)adds method description to usage via docstring

- db/utils.c
Accidentally copy-pasted the span name when instrumenting `db_exec_prepared`.
Changelog-None: Not published yet
> db: Correct the name of the `db_exec_prepared` span name

- tests/autogenerate-rpc-examples.py
- tests/test_pay.py
The test was merged after it was deprecated, and autogenerate-rpc-examples isn't run by CI.
Changelog-None
> pytest: fix test_pay tests now we've deprecated experimental-offers.

- common/onion_decode.c
- common/onion_decode.h
- common/test/run-blindedpath_onion.c
- common/test/run-onion-test-vector.c
- common/test/run-sphinx.c
- lightningd/pay.c
- lightningd/peer_htlcs.c
- plugins/offers.c
- tests/plugins/channeld_fakenet.c
- tests/test_pay.py
- tests/test_xpay.py
- wallet/test/run-wallet.c
Based on #7610 this fixes a great error which @vincenzopalazzo found (and makes it easier to find similar errors in future, with better logging).
Closes: #7610
> Fix offer payment failure

- gossipd/gossipd.c
- gossipd/gossipd.h
- gossipd/gossmap_manage.c
- gossipd/queries.c
- gossipd/seeker.c
- gossipd/test/run-extended-info.c
- plugins/test/run-route-calc.c
- plugins/test/run-route-overlong.c
- tests/test_gossip.py
> [!IMPORTANT]
The gossip seeker has been getting less reliable with nodes often failing to provide a full gossip sync when requested and/or miss gossip when streaming.  This PR does several thing to address this:
1. Increase the number of gossipers we stream from: 5 -> 10.
2. Ask a random peer for a full resync every hour.  Previously this was only once at startup.
3. Drop the worst performing gossip streamer, not a random one.
4. Rotate out the worst gossip streaming peer every ~30 minutes (was ~hourly.)
Considering a blackbox test for gossip rotation, but it's probabilistic, which makes it more difficult to test reliably.
> Aggressive Gossip Seeker

- lightningd/gossip_control.c
While we have (I hope!) fixed the underlying sync problem, this can still happen with older gossip.  So now we tell it the channel is dead, so it won't happen more than once.
Fixes: #7703
Changelog-None
> lightningd: tell gossipd channel is closed if it tells us about our channel and is wrong.

- tests/test_pay.py
This test fails with cln v24.08.2. Add this test, so it doesn't happen again.
> tests: add pay test over unannounced channels

- configure
- tests/test_closing.py
- tests/test_gossip.py
> More flake fixes

- contrib/pyln-client/pyln/client/plugin.py
24.05 and before requires a "description" field.  We should not have removed it here until that was EOL!
Changelog-Fixed: pyln-client: plugins now compatible with CLN <= 24.05 (broken in 24.08)
Reported-by: Christian Decker
> pyln-client: restore backwards compatibility with CLN prior to 24.08

- plugins/xpay/xpay.c
- tests/test_gossip.py
pay does this, xpay does not: it was found by a test flake, but the problem is real!
> Xpay: add one to CLTV blockheight

- Makefile
Due to Darwin-arm64 conditional setting of `CPPFLAGS`, the subsequent `CPPFLAGS +=` is resolved earlier on ARM macOS which results in empty paths being used.
Changelog-None
---
Snippets of running `make`:
* Before commit:
```
CC: cc -I/opt/homebrew/opt/sqlite/include -DCLN_NEXT_VERSION="v24.11" -DPKGLIBEXECDIR="" -DBINDIR="" -DPLUGINDIR="" -DCCAN_TAL_NEVER_RETURN_NULL=1 -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/build-arm64-apple-darwin24.1.0/libbacktrace-build -I . -I/opt/homebrew/include …
```
> Makefile: fix defines on ARM macOS

- contrib/startup_regtest.sh
The script doesn't work if this flag is present. Offers are now default on.
> startup_regtest: remove experimental-offers flag

- common/trace.c
- common/trace.h
- db/utils.c
- lightningd/lightningd.c
- lightningd/test/run-find_my_abspath.c
Replaces an earlier attempt in #7847 
Closes #7843
> common: Add a debug mode for tracing

- contrib/pyln-testing/pyln/testing/utils.py
- tests/test_gossip.py
This avoids potential test flakes, but the `autoconnect-seeker-peers` option can be explicitly set if needed for testing.
Changelog-None
> [!IMPORTANT]
> pyln-testing: disable seeker autoconnect by default

- lightningd/anchorspend.c
- lightningd/channel.c
- lightningd/channel.h
- lightningd/closing_control.c
- lightningd/closing_control.h
- lightningd/onchain_control.c
- lightningd/peer_control.c
- lightningd/peer_control.h
- lightningd/test/run-invoice-select-inchan.c
- tests/test_closing.py
- wallet/test/run-wallet.c
Ordering we were using for setting the channel state was causing us to send anchorspend transactions for onchain commitments.
This would occasionally show up in the CI as a flake, due to a race condition with onchaind adding commitment tx utxos that were then picked up in the anchorspend construction, which would fail due to bookkeeper assertions around spent/unspent utxos. (See #7526)
Also includes a fix to not include currently CSV locked outputs in the construction of anchorspends.
Fixes #7526
> Fix: don't send anchorspends for onchain commitment txs

- plugins/grpc-plugin/src/main.rs
We were logging notifications for which we do not have a handler registered.
That worked until we introduced the wildcard subscription, which the grpc plugin
uses. With this the guarantee that for each subscribed topic we had a corresponding
handler is no longer true, and the warning doesn't really add any information
to the logs, so we just stop logging.
Closes https://github.com/ElementsProject/lightning/issues/7836
> grpc: Silence the notification spam

- lightningd/anchorspend.c
- lightningd/channel.c
- lightningd/channel.h
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/opening_control.c
- lightningd/options.c
- lightningd/peer_control.c
- tests/test_closing.py
- wallet/db.c
- wallet/test/run-db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
If a commitment tx isnt' urgent (no HTLCs) we didn't create an anchor at all.  This is problematic as the user doesn't have a good way to do it themselves.
1. Always make an anchor if feeboost needed.
2. Always aim for 12 blocks away, at best (starts at 2 weeks).
3. Remember when we started closing, so this timing works across restarts.
4. Fix error where we would use the wrong values if we failed to create a PSBT in the loop (but we would update feerate etc).
> Anchor code cleanup: always use anchors, but only boost to estimateblockfee 12.

- plugins/askrene/askrene.c
- plugins/askrene/layer.c
- plugins/askrene/layer.h
- plugins/spender/multifundchannel.c
- plugins/spender/multifundchannel.h
Well, so far one xpay - askrene layer fix, and one "mfc thinks every multifundchannel has id 34" fix.
Changelog-None
> More flake fixes.

- connectd/multiplex.c
@vincenzopalazzo points out that large nodes are not always getting their own channel gossip out reliably.  The number of peers we spam our own channel gossip to is limited to save large nodes on startup, but this should be relaxed slightly to ensure propagation.
Changelog-Fixed: Own-channel gossip is broadcast to more peers on connect.
> [!IMPORTANT]
> connectd: force our own channel gossip to more peers

- gossipd/seeker.c
Reported-by: hMsats
Fixes: https://github.com/ElementsProject/lightning/issues/7875
Changelog-None: introduced in rc1
> gossipd: fix crash in seeker rotation code.

- plugins/Makefile
The nightly CI in the plugins repo is failing to build CLN right now:
```
make: cargo: No such file or directory
cargo build --quiet --bin cln-grpc
make: *** [plugins/Makefile:300: target/debug/cln-grpc] Error 127
```
I believe this is because `MSGGEN_GEN_ALL` ensures `contrib/msggen/msggen/schema.json` is available while for building `cln-grpc` we need the actual rust files which are ensured by `MSGGEN_GENALL`
With this change i got the CI building again.
> Makefile: ensure that cln-grpc depends on msggen generated rust files.

- connectd/connectd.c
```
Program received signal SIGSEGV, Segmentation fault.
0x000000001014e9d8 in io_set_finish_ (conn=0x0, finish=0x0, arg=0x0) at ccan/ccan/io/io.c:137
137             conn->finish = finish;
(gdb) bt
incoming=true) at connectd/connectd.c:394
```
Fixes: #7871
Reported-by: grubles
Changelog-None: broken in this release
> [!IMPORTANT]
> connectd: fix crash when we get an incoming conn while outgoing attempt is ratelimited

- gossipd/seeker.c
- lightningd/options.c
> [!IMPORTANT]
Testing the seeker autoconnect, I realized it should probably work even with no peers initially connected.  This PR allows the seeker to try autoconnecting in that case, and also entirely disables autoconnect when `--offline` is set.
> Enable seeker autoconnect when started with no peers, disable when --offline

- CHANGELOG.md
- plugins/Makefile
Somehow CHANGELOG was doubled up, so fixed.
Several crashes fixed.
Changelog-None
> CHANGELOG: update for rc2.

- common/bolt12.c
- common/bolt12.h
- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-xpay.json
- plugins/xpay/xpay.c
- tests/test_pay.py
In fact, there are several places where we try to decode old invoices, and they should all work.  The only place we should enforce expiration is when we're going to pay.
This also revealed that xpay wasn't checking bolt11 expiries!
Reported-by: hMsats
Fixes: https://github.com/ElementsProject/lightning/issues/7869
Changelog-Fixed: JSON-RPC: `decode` refused to decode expired bolt12 invoices.
> decode: don't fail to decode just because a bolt12 invoice has expired.

- channeld/full_channel.c
- lightningd/pay.c
- lightningd/subd.c
- tools/gen/impl_template
It's freaking people out when they see things like:
```
2024-11-11T05:26:41.281Z DEBUG ...53c-connectd: peer_out INVALID 22859
```
Fixes: https://github.com/ElementsProject/lightning/issues/7802
> wire: call unknown types "UNKNOWN X" not "INVALID X".

- .github/workflows/release.yml
- Removed branch testing as it is not required. Point releases will trigger the event due to `tag` push even when it is not from master branch.
- Added version in inputs for testing
- Added missing `inputs` tag
> ci: Release yml fixes for checkout error

- doc/getting-started/advanced-setup/repro.md
Clarifies that producing/verifying reproducible builds does not require someone to be a maintainer, and removing the use of `sudo` throughout, given it's not required.
> doc: minor changes to repro.md

- lightningd/watch.c
We are checking if `txw->depth` is `-1` and then print it, when we clearly want `depth` instead.
Changelog-Fixed logs: When printing depths some unsigned numbers could overflow
> logs: Correct a sign mismatch printing the depth change

- Cargo.lock
- cln-grpc/Cargo.toml
- cln-rpc/Cargo.toml
- plugins/Cargo.toml
- plugins/grpc-plugin/Cargo.toml
Need to bump these versions for release so the CI job publishes them to crates.io. I found some minor breaking changes so i bumped it to 0.3 (some removals and non-Option->Option changes)
> rust: bump versions for 24.11 release

- plugins/xpay/xpay.c
My lightningd logs are getting hammered by a particular log from v24.11's xpay plugin:
```
2024-12-11T16:29:03.439Z INFO    plugin-cln-xpay: Got command askrene-age
2024-12-11T16:29:03.440Z INFO    plugin-cln-xpay: Got command datastore
2024-12-11T16:30:02.530Z INFO    plugin-cln-xpay: Got command listpeerchannels
2024-12-11T16:30:03.440Z INFO    plugin-cln-xpay: Got command askrene-age
2024-12-11T16:30:03.441Z INFO    plugin-cln-xpay: Got command datastore
2024-12-11T16:31:03.493Z INFO    plugin-cln-xpay: Got command askrene-age
2024-12-11T16:31:03.493Z INFO    plugin-cln-xpay: Got command datastore
2024-12-11T16:32:03.495Z INFO    plugin-cln-xpay: Got command askrene-age
2024-12-11T16:32:03.496Z INFO    plugin-cln-xpay: Got command datastore
2024-12-11T16:33:03.555Z INFO …
```
> reduce xpay INFO verbosity

- common/splice_script.c
header sys/errno.h gets re-directed to errno.h leading to warning and then failure so instead directly referencing the header
fixes #7939, #7922
> [!IMPORTANT]
> splice: errno header redirection failure

- common/status.c
- common/status.h
- common/subdaemon.c
- connectd/test/run-netaddress.c
- lightningd/log.c
- lightningd/log.h
- lightningd/subd.c
- lightningd/test/run-find_my_abspath.c
- lightningd/test/run-shuffle_fds.c
We ratelimited DEBUG messages, but that can be annoying and cause us to miss things. We demoted the worst offenders in the last release, to TRACE level.
Now, only log trace if it's wanted, and never suppress DEBUG.
Changelog-Changed: Logging: we no longer suppress DEBUG messages from subdaemons.
Fixes: https://github.com/ElementsProject/lightning/issues/7917
> common: don't send trace messages by default, don't ratelimit at all.

- cli/lightning-cli.c
Changelog-Fixed: lightning-cli: fix "malformed response" bug
Fixes #7904 
There was a wrong assumption that the number of bytes read by `cli_read` would get us for each correctly
read token two extra CR characters. As a matter of fact one could read enough characters to parse the first
token, but the two extra CR characters are not guaranteed.
> lightning-cli: fix malformed response bug

- plugins/xpay/xpay.c
- tests/test_xpay.py
maxfeepercent is use by Zeus, so let's make that work.
maxfee is more precise, so it's the only xpay option (maxfee was added to pay later).
Fixes: https://github.com/ElementsProject/lightning/issues/7926
I prefer this to #7936
> xpay: emulate maxfeepercent and exemptfee when xpay-handle-pay used

- contrib/msggen/msggen/schema.json
- doc/lightningd-config.5.md
- doc/schemas/lightning-xpay.json
- plugins/xpay/xpay.c
- tests/test_xpay.py
Changelog-Changed: `xpay` now gives the same JSON success return as documented by `pay` when `xpay-handle-pay` is set.
Fixes: https://github.com/ElementsProject/lightning/issues/7923
Fixes: https://github.com/ElementsProject/lightning/issues/7934
> xpay: more accurately reflect pay when xpay-handle-pay is set.

- CHANGELOG.md
Changelog-None: changelog updated.
> Changelog: update to match 24.11.1 branch now that's released.

- .github/workflows/ci.yaml
- lightningd/datastore.c
- tests/plugins/channeld_fakenet.c
- tests/test_closing.py
- tests/test_gossip.py
- tests/test_misc.py
> Fix flakes #11

- .github/workflows/bsd.yml
- .github/workflows/ci.yaml
- .github/workflows/crate-io.yml
- .github/workflows/docker-release.yml
- .github/workflows/macos.yaml
- .github/workflows/rdme-docs-sync.yml
- .github/workflows/readme-rpc-sync.yml
- Dockerfile
- contrib/docker/Dockerfile.builder.fedora
- contrib/reprobuild/Dockerfile.focal
- contrib/reprobuild/Dockerfile.jammy
- contrib/reprobuild/Dockerfile.noble
- tests/data/recklessrepo/lightningd/testplugpyproj/pyproject.toml
These workflows are failing due to the update of `ubuntu-latest` from version `22.04` to `24.04`. For now, we can lock the Ubuntu version to `22.04` to resolve the issue and plan to update to `24.04` once it becomes more stable on GitHub Actions.
Reference: https://github.com/actions/runner-images/issues/10636
> ci: Fix broken CI after locking versions

- doc/getting-started/getting-started/installation.md
This doesn't do anything, because it's trying to create a symlink for a verison that doesn't exist. The version of `gettext` currently installed via brew is `0.22.5`.
In any case, on any recent macOS system, this should not be necessary.
> ci: remove macOS gettext symlinking

- configure
The current check fails when building with newer GCC, i.e:
```bash
error: ‘crypto_secretstream_xchacha20poly1305_init_push’ reading 32 bytes from a region of size 3 [-Werror=stringop-overread]
12 |         crypto_secretstream_xchacha20poly1305_init_push(&crypto_state, header,
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13 |                                                         data);
```
This inadvertently results in the release binaries for Ubuntu 22.04 & 24.04, not having a runtime libsodium dependency, but instead using the bundled lib.
It's not clear to me this is actually enough to fix (all) the release builds, as the build containers need to have `libsodium-dev`, not just `libsodium` in them, and it's not clear to me which packages are actually …
> build: fixup check for `HAVE_GOOD_LIBSODIUM`

- .github/workflows/repro.yml
> Send email if reproducible built fails in the CI

- .github/PULL_REQUEST_TEMPLATE.md
Feature freeze for v25.02 will be on January 31st.
Changelog-None
> [!IMPORTANT]
> github: update PR template with 25.02 freeze cutoff date.

- common/dev_disconnect.c
- common/dev_disconnect.h
- connectd/connectd.c
- connectd/multiplex.c
- connectd/peer_exchange_initmsg.c
- contrib/msggen/msggen/schema.json
- devtools/gossipwith.c
- doc/schemas/lightning-listconfigs.json
- gossipd/gossmap_manage.c
- lightningd/options.c
- tests/fixtures.py
- tests/test_closing.py
- tests/test_connection.py
- tests/test_gossip.py
- tests/test_opening.py
- tests/test_splicing_disconnect.py
- tests/test_xpay.py
Changelog-None: just tweaking tests...
> More flake fixes!

- common/daemon.c
- plugins/askrene/askrene.c
- plugins/askrene/flow.h
- plugins/askrene/refine.c
- plugins/xpay/xpay.c
- tests/test_askrene.py
> Fix askrene 0 amount crash (and hopefully stop xpay calling that!) and over capacity crash

- .github/scripts/sync-rpc-cmds.py
Remove the prefix for better aligned and cleaner RPC list on the documentation portal.
> docs: Remove `lightning-` prefix from all RPCs

- .github/workflows/release.yml
- doc/contribute-to-core-lightning/release-checklist.md
- doc/getting-started/advanced-setup/repro.md
- tools/build-release.sh
> ci: Version update for Fedora reproducible build

- doc/Makefile
- doc/index.rst
Adding the newly introduced RPCs, `editdescriptionbyoutpoint` and `editdescriptionbypaymentid`, to the `Makefile` for generating the corresponding `.md` files required for the documentation portal.
> doc: Add newly added bkpr RPCs in documentation

- plugins/libplugin-pay.c
We used to not print what happened with an HTLC in the `pay`
plugin. This meant that to follow the HTLCs we'd have to map the `pay`
HTLCs to the `lightningd` HTLCs, and then trace that. BY having `pay`
print the outcome as it sees it, we can make that tracking much
simpler, even allowing for tooling to do it for us.
Changelog-None This is a log-only change
> pay: Print the HTLC result as soon as it's known

- contrib/reprobuild/Dockerfile.focal
- contrib/reprobuild/Dockerfile.jammy
- contrib/reprobuild/Dockerfile.noble
After merging the Rust-based `clnrest` plugin into the master, all three reproducible build scripts failed with the following error:
```
error: package `socketioxide v0.15.1` cannot be built because it requires rustc 1.75.0 or newer, while the currently active rustc version is 1.73.0
Either upgrade to rustc 1.75.0 or newer, or use
cargo update -p socketioxide@0.15.1 --precise ver
where `ver` is the latest version of `socketioxide` supporting rustc 1.73.0
make: *** [plugins/Makefile:304: target/release/clnrest] Error 101
```
To resolve this, we can either downgrade `socketioxide` to `v0.11.1`, which is compatible with `Rust >=v1.67` OR Upgrade Rust to `v1.75`.
Since the latest Rust version is `1.84`, upgrading to `1.75` seems like a reasonable choice, as it is already 13 months old. …
> Update Rust version 1.73 to 1.75 for Ubuntu Dockerfiles

- contrib/msggen/msggen/schema.json
- doc/schemas/lightning-commando-listrunes.json
- doc/schemas/lightning-commando-rune.json
- doc/schemas/lightning-createrune.json
- doc/schemas/lightning-showrunes.json
- tests/autogenerate-rpc-examples.py
- tools/fromschema.py
- tools/md2man.sh
- Moved the `Usage` section further down in `createrune` and `commando-rune` for improved UX.
- Added a new example for creating a rune with `read-only` restrictions, extending it to allow only payments of `less than 100,000 sats per day` using the `pay` or `xpay` methods.
- Adjusted formatting by appending an extra space after the `dependentUpon` condition, fixing `[*start* [*end*]][*relist*]` to `[*start* [*end*]] [*relist*]`.
- Relocated `Examples` from the expandable section to a standard heading, as examples are now already placed at the end of the page.
> doc: Add new createrune example

- gossipd/gossipd.c
- gossipd/gossmap_manage.c
- tests/test_gossip.py
test_closing_different_fees fails:
```
2024-10-14T08:43:30.2733614Z
2024-10-14T08:43:30.2734133Z         # Now wait for them all to hit normal state, do payments
2024-10-14T08:43:30.2735205Z >       l1.daemon.wait_for_logs(['update for channel .* now ACTIVE'] * num_peers
2024-10-14T08:43:30.2736233Z                                 + ['to CHANNELD_NORMAL'] * num_peers)
2024-10-14T08:43:30.2736725Z
2024-10-14T08:43:30.2736903Z tests/test_closing.py:230:
...
2024-10-14T08:43:30.2761325Z E                   TimeoutError: Unable to find "[re.compile('update for channel .* now ACTIVE')]" in logs.
```
For some reason one of the channel_update injections does *not* evoke this message from gossipd...
> [!IMPORTANT]
Before …
> gossipd: extra debugging when inject fails.

- Makefile
When building from a release zipfile and there is no `git` present, the version number lacks a ‘v’.
This triggers db.c to fail its `is_released_version` check, which fails because the version does not start with a ‘v’ — thereby the database upgrade is rejected.
Issue reported by TonyV on Discord:
“Hey guys, I just upgraded to the latest release and am now getting
```
Refusing to irreversibly upgrade db from version 219 to 261 in non-final version 24.11.1 (use --database-upgrade=true to override)
```
I have the db backed up... but am I good to make those changes without breaking my channels?”
Changelog-Changed: Fix for people upgrading using source release zip packages.
> Add ‘v’ to the version from zipfile release

- common/interactivetx.c
Splice: Stricter interop errors
Error when our peer tries to use the shared output txid as well as the prevtx bytes.
> Splice: Stricter interop errors

- plugins/xpay/xpay.c
- tests/test_xpay.py
Changelog-Fixed: xpay-handle-pay: handle null parameters passed in the "param" list.
Solves issue #7953
> xpay-handle-pay: bugfix, handle null parameters

- channeld/channeld.c
- tests/test_splicing.py
- wallet/walletrpc.c
If a user tries to do a splice without signing their inputs we now provide them with a nice error message and cancel the RPC since that wouldn’t be productive for the user anyway.
We also add a helpful message if they do the opposite — try to sign a PSBT where they did not add any inputs.
Resolves #8011 and addresses `signpsbt` error confusion here: https://github.com/ElementsProject/lightning/issues/8030#issuecomment-2612550043
> splice: Don’t let users do unsigned splices

- tests/test_closing.py
- tests/utils.py
It's really hard to tell what on earth went wrong when a coin movement check fails, since we dont' return good error info.
Here we replace almost every `assert` with a proper check + error with message to help make debugging easier.
We also fixup a flake in one of the penalty HTLC anchor tests, which was causing errors here. https://github.com/ElementsProject/lightning/actions/runs/13090154480/job/36526299502?pr=8031#logs
Change Log: None
> bkpr tests: return actual error data, not just a blank assert failure

- contrib/pyln-testing/pyln/testing/fixtures.py
Currently, pyln tests fail if the `lightning-` prefix is removed from `schema/*.json` files. In this release, we will update pyln to remove its reliance on this prefix, and in the next release, we will remove the prefixes from the files as well.
> pyln-testing: Removing the `lightning-` prefix check for pyln-testing

- lightningd/plugin.c
Raspberry Pi, with bitcoind running and full gossip topology may actually hit this, and we have a report in practice.
Note that the comment is wrong, so fix that too.
Fixes: https://github.com/ElementsProject/lightning/issues/7724
Reported-by: m-schmoock
> [!IMPORTANT]
> lightningd: increase startup time for plugins to 120 seconds.

- lightningd/connect_control.c
We thought it was a good idea to terminate channel subds, but we included onchaind as well!
```
2025-01-29T21:31:46.053Z UNUSUAL 03…00-channeld-chan#255683: Adding HTLC 1737 too slow: killing connection
2025-01-29T21:31:46.053Z INFO    03…00-chan#255683: Peer transient failure in CHANNELD_NORMAL: Adding HTLC timed out: killed connection
2025-01-29T21:31:46.053Z DEBUG   03…00-channeld-chan#255683: Status closed, but not exited. Killing
2025-01-29T21:31:46.054Z DEBUG   03…00-chan#255683: Failing HTLC 1738 due to peer death
2025-01-29T21:31:46.058Z DEBUG   03…00-chan#255683: Failing HTLC 1737 due to peer death
2025-01-29T21:31:46.058Z DEBUG   03…00-chan#255673: Forcing disconnect due to One channel had an error
2025-01-29T21:31:46.059Z DEBUG   03…00-onchaind-chan#255673: Status closed, but …
```
> lightningd: don't kill onchaind if we are forcing a disconnect.

- contrib/startup_regtest.sh
Switching to /dev/null instead of typo’d /tmp/null
/tmp/null isn't correct -- it should be /dev/null
> dev: startup_regtest using wrong null dir

- Makefile
- contrib/msggen/msggen/schema.json
- contrib/plugins/fail/failtimeout.py
- contrib/startup_regtest.sh
- doc/schemas/lightning-listpeerchannels.json
- plugins/Makefile
- tests/test_plugin.py
> Fix flakes #13

- common/pseudorand.c
Reported by Grubles on ARM64:
```
VALGRIND=1 valgrind -q --error-exitcode=7 --track-origins=yes --leak-check=full --show-reachable=yes --errors-for-leak-kinds=all common/test/run-tal_arr_randomize > /dev/null
==151138== Source and destination overlap in memcpy(0x4d69f08, 0x4d69f08, 8)
==151138==    at 0x48CB68C: __GI_memcpy (vg_replace_strmem.c:1147)
==151138==    by 0x41B50B: tal_arr_randomize_ (pseudorand.c:84)
==151138==    by 0x41BB07: main (run-tal_arr_randomize.c:166)
==151138==
make: *** [Makefile:750: unittest/common/test/run-tal_arr_randomize] Error 7
```
It is correct: you can't overlap src and dst in memcpy.  It *probably* works in this case, but it's undefined!
Fixes: https://github.com/ElementsProject/lightning/issues/7030
Changelog-None: unit tests only (probably!)
> common: fix memcpy error in Fischer-Yates shuffle.

- doc/developers-guide/plugin-development/event-notifications.md
- lightningd/notification.c
- lightningd/notification.h
- lightningd/plugin.c
Send `plugin_started` when a plugin has completed startup and send `plugin_stopped` when a plugin is shutdown.
This PR follows the same motivations as #7507, and is the second piece of what will be required for other plugins such as clnrest to dynamically register and drop routes.
Added two new notifications: `plugin_started` and `plugin_stopped`
Updated the docs with the schemas for these notifications
> new notifications: `plugin_stopped` and `plugin_started`

- plugins/renepay/Makefile
- plugins/renepay/json.c
- plugins/renepay/json.h
- plugins/renepay/main.c
- plugins/renepay/mods.c
- plugins/renepay/payment.c
- plugins/renepay/payment.h
- plugins/renepay/payment_info.h
- plugins/renepay/route.c
- plugins/renepay/route.h
- plugins/renepay/routebuilder.c
- plugins/renepay/routebuilder.h
- plugins/renepay/routefail.c
- plugins/renepay/routetracker.c
- plugins/renepay/sendpay.c
- plugins/renepay/sendpay.h
- plugins/renepay/test/run-bottleneck.c
- plugins/renepay/test/run-testflow.c
- plugins/renepay/uncertainty.c
- plugins/renepay/uncertainty.h
- tests/test_renepay.py
Adding support for BOLT12 in renepay.
Closes #6609 
We compute routes to blinded paths by using a fake node as destination and then linking the entry point of every blinded path to the destination with a fake channel that represents the use of that blinded path. The same way that xpay does.
To send the payment we had to change from sendpay to sendonion. We could have used injectpaymentonion but since the injectpaymentonion does not yet support passing `shared_secrets` nor the `destination` id we preferred sendonion, also sendonion is more in tune with renepay design of sending the onions and wait for responses in a notification as opposed to xpay that reacts as soon as injectpaymentonion returns with success or failure.
> renepay: Support for BOLT12

- cli/lightning-cli.c
Changelog-Fixed: lightning-cli: access to man pages from the installed directory.
Fixes #8076
> lightning-cli: fix the access to man pages

- contrib/pyln-testing/pyln/testing/fixtures.py
In a previous [commit](https://github.com/ElementsProject/lightning/pull/8065/commits), I mistakenly removed the `lightning-` replacement logic from the base name also. This commit restores that functionality to re-enable schema checks.
> pyln-testing: Fix for disabled schema check

- tests/test_closing.py
- wallet/test/run-db.c
- wallet/test/run-wallet.c
- wallet/txfilter.c
- wallet/txfilter.h
- wallet/wallet.c
- wallet/wallet.h
- wallet/walletrpc.c
> Wallet can spend takes ages

- plugins/renepay/main.c
- plugins/renepay/mods.c
- plugins/renepay/route.c
- plugins/renepay/route.h
Allow renepay to read group ids from listsenpay with values that fit into u64 integer type.
Previously renepay was using a mixture of u32 and u64 types to handle group ids.
Changelog-Fixed: renepay: read groupids as u64 integers.
Fixes #7968
> renepay: bugfix: read groupids as u64

- contrib/pyln-testing/pyln/testing/utils.py
This happened in CI:
```
valgrind error file: valgrind-errors.16800
==16800== Thread 4 tokio-runtime-w:
==16800== Conditional jump or move depends on uninitialised value(s)
==16800==    at 0x2466BF: _ZN175_$LT$axum..middleware..from_fn..FromFn$LT$F$C$S$C$I$C$$LP$T1$C$T2$C$T3$RP$$GT$$u20$as$u20$tower_service..Service$LT$http..request..Request$LT$axum_core..body..Body$GT$$GT$$GT$4call28_$u7b$$u7b$closure$u7d$$u7d$17h4cc36de5dd56d9feE.llvm.119371497468325184 (in /home/runner/work/lightning/lightning/plugins/clnrest)
==16800==    by 0x57BFFA: <axum::middleware::from_fn::ResponseFuture as core::future::future::Future>::poll (in /home/runner/work/lightning/lightning/plugins/clnrest)
==16800==    by 0x37312B: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll …
```
> testing: don't try to valgrind clnrest, it's Rust.

- plugins/offers.c
- plugins/offers.h
- plugins/offers_invreq_hook.c
- plugins/offers_offer.c
- tests/test_pay.py
Suggested-by: Matt Corallo
Fixes: https://github.com/ElementsProject/lightning/issues/7806
Changelog-Changed: Offers: we will use a blinded path if we have no advertized address (so payers wouldn't be able to connect directly).
> offers: add a blinded path if we have no advertized address.

- plugins/askrene/explain_failure.c
- plugins/askrene/mcf.c
- tests/test_askrene.py
Excellent bug report, simple fix.
> xpay below minimum htlc amount should not give up

- common/deprecation.c
- common/features.c
- contrib/msggen/msggen/schema.json
- devtools/bolt11-cli.c
- doc/developers-guide/deprecations.md
- doc/schemas/lightning-getroutes.json
- plugins/askrene/askrene.c
- plugins/askrene/mcf.c
- plugins/askrene/mcf.h
- plugins/libplugin.c
- plugins/offers.c
- plugins/offers_invreq_hook.c
- plugins/xpay/xpay.c
- tests/test_askrene.py
- tests/test_xpay.py
Fixes: #8042 
Apparently Muun.
We can't (yet) honor this for bolt12, because *we* didn't set the MPP feature until this PR.
> xpay: don't MPP if we're told not to

- plugins/grpc-plugin/src/main.rs
- plugins/rest-plugin/src/main.rs
- tests/test_cln_rs.py
Changelog-Fixed: cln-grpc and clnrest errors that cause them to stop will now log
> [!IMPORTANT]
I consider this a bug fix pr for 25.02
> cln-grpc, clnrest: workaround for logging before shutdown

- doc/developers-guide/plugin-development/event-notifications.md
> [!IMPORTANT]
Adjusted the indentation in the JSON example for the 'connect' command to improve readability and maintain consistency with other examples in the Core Lightning documentation.
> docs: fix JSON indentation in 'connect' example

- tests/test_xpay.py
When we merged blinded paths for nodes with no address (6e4ff6a7d283ef199f93625c3b1ecb73e56b8c10), this test broke.  We need to prevent that, otherwise:
```
>       assert ret['successful_parts'] == 2
E       assert 1 == 2
tests/test_xpay.py:677: AssertionError
```
Changelog-None
> pytest: fix test_xpay_bolt12_no_mpp

- plugins/xpay/xpay.c
Don't print unnecessary log entries every time we receive an `rpc_command` hook event. Only log when `pay` is called.
Fixes issue #8025
> xpay: reduce log entries on rpc_command hook

- cli/lightning-cli.c
- contrib/pyln-client/pyln/client/plugin.py
- lightningd/jsonrpc.c
- tests/plugins/multiline-help.py
- tests/test_misc.py
Fixes: #8020 
- **Improved formatting of plugin descriptions displayed in the `lightning-cli help` output**: Previously, the descriptions contained unnecessary `\n` characters when shown as a single line, which affected readability.  
**Proposed Solution**: Replace `\n` with `|` as the line separator when output is displayed in a single line, for better clarity and consistency.
- **Removed unused variables and related code from `pyln-client`**: For example, the `doc` variable in `pyln/client/plugin.py` was declared but never utilized, and related code was cleaned up to improve maintainability.
> [!IMPORTANT]
Before submitting the PR, ensure the following tasks are completed. If an item is not …
> pyln-client+cli: Fix formatting issues for plugin description in lightning-cli help

- lightningd/peer_control.c
- tests/test_connection.py
Thanks to @cdecker for the report.  This should be a simply cherry-pick for v24.11 as well.
> Fix --dev-dev-no-reconnect-private on restart

- doc/getting-started/getting-started/installation.md
Bitcoin Core has switched to using CMake as its build system. Update the docs here so that they will work.
`berkeley-db4` is removed, because it should not be used for new installs of Core (it's deprecated, and slated for removal).
`miniupnpc` is removed, because Core no-longer uses that dependency (the functionality has been implemented internally).
macOS ships with a version of sqlite that will be picked up and used for wallets.
> docs: update Bitcoin Core install docs

- contrib/pyln-client/pyln/client/__init__.py
- contrib/pyln-client/pyln/client/version.py
- contrib/pyln-client/tests/test_version.py
- contrib/pyln-testing/pyln/testing/utils.py
- tests/fixtures.py
It is sometimes useful to use `pyln-testing` also on older versions of Core Lightning. In greenlight we use `pyln-testing` to test our scheduler which has to support multiple versions of Core Lightning at the same time.
A similar issue exists for plug-in developers that want to support a range of cln-versions.
This PR introduces `NodeVersion` in `pyln-client` which can be used to compare the versions `lightningd` and test if the version is greater or not.
It also modifes `pyln-testing` so it will only use the `--developer` flag if it is available.
> Support multiple cln-version in pyln-testing

- contrib/pyln-testing/pyln/testing/utils.py
Changelog-None
> [!IMPORTANT]
Following https://github.com/ElementsProject/lightning/pull/7173 i tested one of my plugins with cln 24.05 and noticed that tests are failing because of `lightningd: --autoconnect-seeker-peers=0: unknown option` so let's use the new version comparison to only set it in cln versions after the option was introduced (24.11)
> pyln-testing: fix unknown option compatibility with older cln versions

- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/index.rst
- doc/schemas/lightning-enableoffer.json
The `enableoffer` JSON schema is present, but it is not included in the `GENERATE_MARKDOWN` list within the Makefile. This resulted into missing `.7` and `.7.md` files, leading to missing manpage and the documentation portal page.
Fixes #8079.
> doc: Add enableoffer in makefile

- common/scb_wire.csv
- lightningd/channel.c
- lightningd/channel.h
- lightningd/dual_open_control.c
- lightningd/opening_control.c
- lightningd/peer_control.c
- lightningd/test/run-invoice-select-inchan.c
- plugins/Makefile
- plugins/chanbackup.c
- tests/test_misc.py
- tools/gen/header_template
- tools/gen/impl_template
- tools/generate-wire.py
- wallet/test/run-db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
This PR would enable nodes to create penalty transaction when the peer publishes an old revoked state using the emergency.recover.
Addresses: #7696
> Update emergency.recover after every 'commitment_revocation' so that user can sweep funds by penalty transaction.

- lightningd/onchain_control.c
- onchaind/onchaind.c
- onchaind/onchaind_wire.csv
- onchaind/test/run-grind_feerate.c
- tests/test_closing.py
We got the nSequence wrong if there's a lease in progress.  Increase test coverage, and then make the two fixes where we used the "to-self-delay" (which is correct for the non-lease case).
Fixes: #7460
> Unilateral lease close fixes

- gossipd/gossmap_manage.c
- plugins/chanbackup.c
The vast majority of incoming channel updates seem to be cut due to age, which results in noisy logs.  Similarly, the chanbackup logging verbosity might better match the equivalent actions in channeld, which are at the debug level.
Fixes: #8058
Changelog-None: introduced in 25.02
> [!IMPORTANT]
> gossipd, chanbackup: reduce logging levels

- devtools/bolt12-cli.c
- plugins/xpay/xpay.c
- tests/test_misc.py
- tests/test_xpay.py
Fixes: https://github.com/ElementsProject/lightning/issues/8119
> xpay blinded path fix

- lightningd/onchain_control.c
If a tx has already spent one tx we're watching, and it spends another, we try to add it to the hash table twice, which isn't allowed:
```
2025-02-28T23:00:32.155Z **BROKEN** lightningd: backtrace: ../sysdeps/unix/sysv/linux/raise.c:51 (__GI_raise) 0x7fab2e363d51
2025-02-28T23:00:32.155Z **BROKEN** lightningd: backtrace: ./stdlib/abort.c:79 (__GI_abort) 0x7fab2e34d536
2025-02-28T23:00:32.155Z **BROKEN** lightningd: backtrace: ./assert/assert.c:92 (__assert_fail_base) 0x7fab2e34d40e
2025-02-28T23:00:32.155Z **BROKEN** lightningd: backtrace: ./assert/assert.c:101 (__GI___assert_fail) 0x7fab2e35c6d1
2025-02-28T23:00:32.155Z **BROKEN** lightningd: backtrace: lightningd/onchain_control.c:48 (replay_tx_hash_add) 0x556928d4e114
2025-02-28T23:00:32.155Z **BROKEN** lightningd: backtrace: …
```
> lightningd: fix crash in onchaind replay.

- onchaind/onchaind.c
This can happen if a descendent tx has no witness and we don't tell the main daemon in time that we're not iterested.
Fixes: https://github.com/ElementsProject/lightning/issues/8133
Changelog-Fixed: lightningd: onchaind crash when seeing unrelated txs (usually when catching up with old closes)
> onchaind: fix crash if we enounter a tx with no witness.

- Cargo.lock
- cln-grpc/Cargo.toml
- cln-rpc/Cargo.toml
- plugins/Cargo.toml
- plugins/grpc-plugin/Cargo.toml
- plugins/rest-plugin/Cargo.toml
Changelog-None
These need to be bumped for publishing by the CI job. We had breaking changes so we need a 0.x.0 bump.
> crates: bump versions to 0.4.0 for CLN 25.02 release

- lightningd/channel_control.c
- tests/test_opening.py
This addresses #8147.
We used to forget channels if a) we were the fundee, i.e., had no
stake in the channel, and b) the channel did not confirm in 2016
blocks / 2 weeks.
The first implication is no longer true: with `zeroconf` support we
can have a stake in a channel, despite not being confirmed yet. With
this assumption no longer true we now need to explicitly check that we
own no funds in the channel on top of checking if we had contributed
to the funding.
> opening: Do not forget `zeroconf` channels due to funding timeout

- bitcoin/psbt.c
- hsmd/libhsmd.c
Not an important update, but is required for Elements p2tr support whenever that is due.
Supersedes https://github.com/ElementsProject/lightning/pull/8098 using the just minted wally release. Removes now-redundant serialized psbt copies, and enables signature hash caching for faster PSBT signing.
The code that creates signature hashes with transactions should be migrated to PSBT, it's kind of a mix currently and the APIs exposed/wally APIs used don't lend themselves to caching or taproot signing. Thats out of scope for this PR though.
> [!IMPORTANT]
> Wally 1.4.0 update

- wallet/walletrpc.c
Adopting the same `list` standard as other RPCs, where the start index begins at 1.
> dev: Start `dev-listaddrs` index from 1 not 0

- doc/contribute-to-core-lightning/release-checklist.md
> docs: Update instructions to append `rcN` to release candidates

- common/gossmap.c
- tests/test_gossip.py
We handed NULL as the logcb, resulting in a very uninformative crash:
```
2025-03-14T03:46:36.447Z INFO    lightningd: Server started with public key 03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5, alias Jubilee (color #dc42f4) and lightningd v25.02
topology: FATAL SIGNAL 11 (version v25.02)
0x560037f64aad send_backtrace
0x560037f64b49 crashdump
common/daemon.c:78
0x7f6c41ff351f ???
./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x0 ???
???:0
```
Changelog-Fixed: `topology` crash on invoice creation if a peer had a really high feerate.
Fixes: https://github.com/ElementsProject/lightning/issues/8156
> [!IMPORTANT]
Before submitting the PR, ensure the …
> common: fix crash when we have a localmod with unrepresentable fee values

- lightningd/bitcoind.c
Fixes: https://github.com/ElementsProject/lightning/issues/8182
Use the indirect-free trick, otherwise this can happen:
```
2025-03-28T10:46:16.437Z BROKEN lightningd: FATAL SIGNAL 6 (version v25.02)
2025-03-28T10:46:16.437Z BROKEN lightningd: backtrace: common/daemon.c:41 (send_backtrace) 0x6447525af68c
2025-03-28T10:46:16.437Z BROKEN lightningd: backtrace: common/daemon.c:78 (crashdump) 0x6447525af6db
2025-03-28T10:46:16.437Z BROKEN lightningd: backtrace: ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0 ((null)) 0x7783e2c4532f
2025-03-28T10:46:16.437Z BROKEN lightningd: backtrace: ./nptl/pthread_kill.c:44 (__pthread_kill_implementation) 0x7783e2c9eb2c
2025-03-28T10:46:16.437Z BROKEN lightningd: backtrace: ./nptl/pthread_kill.c:78 (__pthread_kill_internal) 0x7783e2c9eb2c …
```
> lightningd: allow bitcoind_getrawblockbyheight callback to free call struct

- lightningd/anchorspend.c
It's not the *outgoing* HTLC which sets the deadline, it's the incoming.
Changelog-Fixed: Protocol: Egregious anchor fee paid for unilateral close txs due to HTLC timeouts; it's not as urgent as our code made out!
Fixes: https://github.com/ElementsProject/lightning/issues/8174
(There are other issues with our exact feerate calculation, but those will come in a separate PR for the next release)
> lightningd: fix anchorspend HTLC deadline logic.

- lightningd/peer_htlcs.c
We pre-close incoming under some circumstances, so this does happen (it didn't when this code was written).  Don't walk all the HTLCs complaining about them in this case, and don't freak out.
Changelog-Fixed: lightningd: incorrect spamming of log and potential crash on testnet case of duplicate HTLCs and slow closing.
Fixes: https://github.com/ElementsProject/lightning/issues/8176
> lightningd: don't spam logs on dangling outgoing HTLCs.

- common/trace.c
- common/trace.h
- plugins/libplugin.c
This happens with autoclean, which does a datastore request then frees the parent command without waiting for a response (see clean_finished).
This leaks a trace, and causes a crash if the pointer is later reused.
My solution is to create a trace variant which declares the trace key to be a tal ptr and then we can clean up in the destructor if this happens. This fixes the issue for me.
> trace: handle key being freed while suspended.

- Makefile
Since clnrest is no longer a python plugin it's old directory was not removed by the existing code and leads to an error when running `make install` when upgrading to cln 25.02 from an older version that was previously installed.
Users had to see the error during `make install` and remove the directory themselves and run `make install` again to fix this. The PR hopefully takes care of that automatically.
Fixes https://github.com/ElementsProject/lightning/issues/8141
Don't know if it fixes the nix issue mentioned
> make: remove old clnrest directory

- .github/workflows/release.yml
The workflow fails to trigger manually after recreating the release tag. It should support re-running even if the tag was previously deleted and recreated.
> ci: Checkout with fresh tags in case the old tag reference is corrupted

- doc/getting-started/getting-started/installation.md
Debian packages rust 1.63 and new lightning users will run into issues following the installation docs if they do not have a newer version
Changelog-None
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 12TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 23rd_, RC2 on _May 26th_, ...
>
> The final release is on MAY 29TH.
> doc: recommend rustup for Debian systems

- doc/getting-started/getting-started/installation.md
Also removes usage of pip due to this error that crops up on newer versions of Ubuntu:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
note: If you believe …
```
> docs: Update install docs for v25.02

- common/bolt11.c
This PR fixes an issue with BOLT11 fallback address validation discovered through differential fuzzing between Lightning implementations. Core Lightning was accepting invoices with non-standard witness address fallbacks that other implementations correctly reject.
While comparing parse results from LND, LDK, and Core Lightning using the [bitcoinfuzz PR #132](https://github.com/brunoerg/bitcoinfuzz/pull/132), I found that Core Lightning enforces the 40-byte upper limit for witness programs as per BIP-141, but doesn't check the 2-byte minimum length requirement.
The fix is minimal: adding a lower bound check to ensure witness programs are at least 2 bytes long, bringing Core Lightning in line with both the BIP-141 specification and other Lightning implementations.
Before submitting the PR, …
> Enforce minimum witness program length for fallback addresses in BOLT11 parsing

- tests/test_misc.py
- tests/test_renepay.py
1. Flake where we manually reconnected while autoreconnect is happening.
2. get_channel_scid() returns the *first* channel, and we want all the channels. So they may not actually be all visible in gossip.
```
@unittest.skipIf(TEST_NETWORK == 'liquid-regtest', "broken for some reason")
def test_hardmpp2(node_factory, bitcoind):
"""Credits to @daywalker90 for this test case."""
opts = {"disable-mpp": None, "fee-base": 0, "fee-per-satoshi": 10}
l1, l2, l3 = node_factory.get_nodes(3, opts=opts)
start_channels(
[
(l1, l2, 100_000),
(l1, l2, 200_000),
(l1, l2, 300_000),
(l1, l2, 400_000),
(l2, l3, 100_000),
(l2, l3, 200_000),
(l2, l3, 300_000),
(l2, l3, 600_000),
]
)
inv = l3.rpc.invoice("800000sat", "inv", "description")
>       l1.rpc.call("renepay", {"invstring": inv["bolt11"]}) …
```
> pytest: fix more flakes

- contrib/pyln-client/pyln/client/lightning.py
symlink the socket to a tempfile which has a shorter path
> [!IMPORTANT]
> fix: workaround for macOS AF_UNIX path error

- Cargo.lock
- cln-grpc/Cargo.toml
- cln-grpc/src/lib.rs
This PR exposes the `NotificationStream` of the grpc server implementation. This is required for wrapping services to be able to pass down any notification stream.
> `cln-grpc` Expose `NotificationStream`

- .github/workflows/bsd.yml
```
12 MiB to be downloaded.
[1/1] Fetching pkg-2.1.0.pkg: .......... done
Checking integrity... done (0 conflicting)
[1/1] Upgrading pkg from 1.21.3 to 2.1.0...
[1/1] Extracting pkg-2.1.0: .......... done
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'python38' have been found in the repositories
Error: The process '/usr/bin/bash' failed with exit code 1
```
Changelog-None: CI only
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 12TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 23rd_, RC2 on _May 26th_, ...
>
> The final release is on MAY 29TH.
Before submitting the PR, ensure the following tasks are completed. If an item is not applicable to your …
> CI: update freebsd test to python 3.10.

- wallet/db.c
Introduced the use of UPDATE FROM syntax in SQLite queries, which is not supported in versions prior to 3.33.0.
This causes issues on systems with older SQLite versions,
as reported in issue #8231. Rewrite the query in
migrate_convert_old_channel_keyidx() to use a subquery
with IN clause instead of UPDATE FROM, ensuring compatibility with
older SQLite versions.
Fixes [68f3649d6b9fc65ece3f1dc3e2f7e6a053170ea5](https://github.com/ElementsProject/lightning/issues/8231)
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 12TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 23rd_, RC2 on _May 26th_, ...
>
> The final release is on MAY 29TH.
Before submitting the PR, ensure the following tasks are completed. …
> db: replace UPDATE FROM syntax for SQLite compat

- common/test/Makefile
- common/test/run-trace.c
- common/trace.c
- common/trace.h
- lightningd/lightningd.c
- lightningd/test/run-find_my_abspath.c
- lightningd/test/run-jsonrpc.c
- plugins/bkpr/test/run-bkpr_db.c
- plugins/bkpr/test/run-recorder.c
- plugins/test/run-route-calc.c
- plugins/test/run-route-overlong.c
- tests/test_misc.py
Recommended by @cdecker , tests were a great idea!
> Tracing tests, fixes, and optimizations

- .github/scripts/setup.sh
- common/trace.c
- lightningd/test/run-find_my_abspath.c
- plugins/bkpr/test/Makefile
- plugins/bkpr/test/run-bkpr_db.c
- plugins/bkpr/test/run-recorder.c
We have a crash right now, which passed CI.  This turns it on in our main CI build, and fixes the bug.
Changelog-None
> Tracing: fix recent bug, and ensure CI actually tests it

- channeld/channeld.c
- channeld/channeld_wire.csv
- lightningd/channel.c
- lightningd/channel.h
- lightningd/channel_control.c
- lightningd/channel_control.h
- lightningd/closed_channel.c
- lightningd/closed_channel.h
- lightningd/dual_open_control.c
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/memdump.c
- lightningd/onchain_control.c
- lightningd/opening_control.c
- lightningd/peer_control.c
- lightningd/test/run-find_my_abspath.c
- lightningd/test/run-invoice-select-inchan.c
- tests/plugins/channeld_fakenet.c
- tests/test_closing.py
- tests/test_connection.py
- tests/test_opening.py
- wallet/test/run-db.c
- wallet/test/run-wallet.c
- wallet/wallet.c
- wallet/wallet.h
This does several nice things:
1. Cleans up our closed channel handling.
2. Loosens the timeout of 2016 blocks on unopened channels: we allow 100 channels to go over that before we start timing them out (requested by @michael1011 )
> Handle closed channels better.

- common/dijkstra.c
Fixed typos and standardized English spelling of "neighbor" to match the variable names in the Dijkstra algorithm explanation.
Changelog-None
> doc: Minor typo fixes in Dijkstra description

- doc/getting-started/getting-started/installation.md
We should definitely add the tip that people shouold set RUST_PROFILE=release for production builds somewhere, since the default is debug!
> docs: add RUST_PROFILE to installation steps

- plugins/chanbackup.c
plugin_log inside after_send_scb_single was logging after sending peer storage to each peer which could lead to spam in logs for big nodes, hence we should reduce the log level to log_trace for it.
Closes: #8251
> Change LOG_INFORM to LOG_TRACE in chanbackup

- tests/test_connection.py
This finally happened on my local build machine, so I tracked it down using py-spy, `apt-get install python3-dbg` and `py-local`.
Turns out the dev-memleak command was hanging, and the processes were stuck in SIGSTOP.  There are only two places we send that, and sure enough, this was the test which was running at the time.
Changelog-None
> pytest: fix CI hang.

- plugins/wss-proxy/wss-proxy
We try to do a JSON response if Python is not present, but it assumes sed.  We should cleanly exit on errors.
Before:
```
$ PATH=/tmp ./plugins/wss-proxy/wss-proxy
Something
./plugins/wss-proxy/wss-proxy: 12: sed: not found
{"jsonrpc":"2.0","id":,"result":{"disable":"No python3 binary found"}}
```
After:
```
$ PATH=/tmp ./plugins/wss-proxy/wss-proxy
something
./plugins/wss-proxy/wss-proxy: 12: sed: not found
```
Changelog-None
Reported-by: @cdecker
> plugins: wss-proxy should not return invalid JSON if sed does not exist.

- .github/workflows/ci.yaml
- plugins/libplugin.c
- tests/test_closing.py
- tests/test_misc.py
- tests/test_opening.py
- tests/test_xpay.py
> Fix flakes #17

- Cargo.lock
- Cargo.toml
- plugins/.gitignore
- plugins/Makefile
- plugins/lsps-plugin/Cargo.toml
- plugins/lsps-plugin/src/client.rs
- plugins/lsps-plugin/src/jsonrpc/client.rs
- plugins/lsps-plugin/src/jsonrpc/mod.rs
- plugins/lsps-plugin/src/jsonrpc/server.rs
- plugins/lsps-plugin/src/lib.rs
- plugins/lsps-plugin/src/lsps0/mod.rs
- plugins/lsps-plugin/src/lsps0/model.rs
- plugins/lsps-plugin/src/lsps0/transport.rs
- plugins/lsps-plugin/src/main.rs
- plugins/lsps-plugin/src/service.rs
- tests/test_cln_lsps.py
This PR implments the basic transport mechanism (`lsps0`) for LSP clients and services as described in https://github.com/lightning/blips/blob/master/blip-0050.md
`lsps0` describes how LSPs communicate with their clients, wich basically is JSON-RPC v2.0 via custom lightning messages.
> Add LSPS0 Client and Service Plugin

- contrib/pyln-client/pyln/client/__init__.py
- contrib/pyln-client/pyln/client/version.py
- contrib/pyln-client/tests/test_version.py
- contrib/pyln-testing/pyln/testing/utils.py
This broke my build machine, because lightningd --version was malformed (I had no tags somehow in that branch).
I dived into the code to figure out what was wrong, and I was horrified.
1. STOP.  Never write this much code.
2. You just need a NodeVersion class.  That's it.  No others.
3. Don't throw away the entire first part if it starts with 'v'.  Just remove the v.
4. Always fail on invalid strings in the constructor, NOT on the first time you use it.
I have rewritten it.
Changelog-None
> pyln-client: reimplement NodeVersion, simply.

- contrib/pyln-client/pyln/client/lightning.py
> pyln-client: Adding disableoffer, enableoffer, fetchinvoice, listoffers and offer commands

- contrib/startup_regtest.sh
- lightningd/plugin.c
- plugins/askrene/askrene.c
- plugins/libplugin.c
- plugins/renepay/mods.c
Add the ability to log "trace" events with plugins.
Before this PR a `LOG_TRACE` from a plugin was being logged as `**BROKEN**` because "trace" was missing from
libplugin.
I've also added trace logs to every json rpc call on askrene and to the payment modifiers steps in renepay.
> Libplugin: add log trace

- README.md
- doc/beginners-guide/beginners-guide.md
- doc/node-operators-guide/faq.md
Links to 'helpme' plugin on the website are dead. It turned out that plugin has been archived but website has not been updated.
This PR removes mentions of the plugin form README and doc. It removes FAQ's section _**I don't know where to start, help me !**_ without substitution.
> doc: Remove mentions of 'helpme' plugin

- plugins/examples/cln-plugin-startup.rs
- plugins/src/logging.rs
- tests/test_cln_rs.py
Now that libplugin can log to trace (https://github.com/ElementsProject/lightning/pull/8258/commits/6381fd2aa2b1c2b7e7e04dd8a9f5e6a16e7f7df0) we can enable it in cln-plugin! I don't know if it's possible to check for the actual log level in the test? Does this require a changelog entry?
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 05TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 12th_, RC2 on _May 16th_, ...
>
> The final release is on MAY 20TH.
> cln-plugin: trace level logging support

- contrib/msggen/msggen/schema.json
- doc/schemas/askrene-bias-channel.json
- doc/schemas/plugin.json
- plugins/askrene/askrene.c
- plugins/askrene/layer.c
- plugins/askrene/layer.h
The channel bias feature is not being used yet by any plugin, so this hopefully doesn't break any working code.
When askrene-bias-channel is called the bias quantity is added on top of any previous biased already present on that channel instead of overwriting it.
Changelog-Changed: askrene-bias-channel: bias call add up.
The use case I envision is the following in the context of a payment plugin:
Stack biases on channels that fail often with weird errors and avoid DoS:
- plugin sends payment for computed route
- route fails with weird error such as `WIRE_AMOUNT_BELOW_MINIMUM` indicating that we need to update the gossmap
- we don't have to trust this channel is behaving correctly, so we update the gossmap and we add some negative bias to it.
- next time we fail the payment again with the …
> askrene-bias-channel: bias call add up.

- connectd/connectd.c
- connectd/connectd.h
- connectd/connectd_wire.csv
- lightningd/connect_control.c
- lightningd/gossip_control.c
Remove DNS lookups altogether which are fairly useless and cause problems (being sync!).  And remove an ugliness where we could have multiple reconnect timers running at once.
Fixes: https://github.com/ElementsProject/lightning/issues/7913
Fixes: #8157
> Fix connect address failures

- .github/workflows/ci.yaml
- common/daemon.c
- connectd/multiplex.c
- gossipd/gossipd.c
- gossipd/gossmap_manage.c
- gossipd/gossmap_manage.h
- lightningd/log.c
- lightningd/notification.c
- lightningd/plugin.c
- lightningd/plugin.h
- tests/test_closing.py
- tests/test_connection.py
- tests/test_opening.py
- tests/test_pay.py
- tests/test_wallet.py
- tests/utils.py
I noticed we were not going as fast as we should, in a 100-payments test.  Turns out our Nagle-suppressing code was wrong!  
Then I continued with minor optimization until our profiling basically only contained sqlite operations, resulting in an 8% speedup in bouncing payments. (when eatmydata was used).
(Dropped patch which speeds CI using eatmydata, as it broke too much!)
> Fix nagle, other minor optimizations

- .github/workflows/ci.yaml
- contrib/msggen/msggen/schema.json
- doc/schemas/askrene-bias-channel.json
- lightningd/connect_control.c
- lightningd/peer_control.c
- lightningd/peer_control.h
- plugins/askrene/askrene.c
- tests/test_askrene.py
- tests/test_closing.py
- tests/test_misc.py
> Fix CI Automerge button, and another flake

- plugins/bcli.c
- tests/test_misc.py
Suggested-by: @NicolasDorier
Closes: https://github.com/ElementsProject/lightning/issues/8078
Changelog-Changed: Protocol: we no longer try asking for blocks from bitcoind's peers if they don't store blocks.
\
> bcli: don't try asking non-full nodes for blocks.

- contrib/msggen/msggen/schema.json
- doc/schemas/fundchannel.json
- doc/schemas/withdraw.json
Reported-by: https://github.com/michaelWuensch
Changelog-None: trivial
Fixes: #8099
> doc: clarify that `all` with `utxos` spends all those utxos only.

- lightningd/peer_control.c
- tests/test_misc.py
LND does not force close on us when we recover our node using emergency.recover or peer storage backups (https://github.com/lightningnetwork/lnd/blob/abb1e3463f3a83bbb843d5c399869dbe930ad94f/htlcswitch/link.go#L2119).
We will send a channel reestablish with bogus data to make them force close on us.
> Workaround for LND to cause a force-close on our channel

- .github/scripts/sync-rpc-cmds.py
- contrib/msggen/msggen/schema.json
- doc/Makefile
- doc/index.rst
- doc/lightning-reckless.1.md
- doc/reckless.7.md
- doc/schemas/reckless.json
> Separate reckless utility (1) and reckless rpc (7) documentation

- plugins/askrene/askrene.c
There are two ways a plugin can use the `askrene-inform-channel` API on a payment failure: before or after calling
`askrene-unreserve`.
A plugin's logic could be the following:
- compute routes
- send routes
- call `askrene-reserve` 
Then on failure
- call `askrene-unreserve`
- call `askrene-inform-channel amount=x inform=constrained`
It is important to ensure that `askrene-inform-channel` is called once `askrene-unreserve` has completed,
because the upper bound on the liquidity is computed as
```
upperBound = reserves + amount - 1
```
Therefore a race condition here would alter the results by double counting the value of `amount`.
Alternatively the plugin's logic could inverse the order of operations in the case of failure:
- call `askrene-inform-channel amount=0 inform=constrained`
- …
> askrene-inform-channel: change order of operations

- common/amount.c
- common/test/run-amount.c
- tests/test_askrene.py
We may introduce high capacity channels in askrene to represent problems
with multiple destinations (eg. multiple blinded paths) or to solve
self-payments. The integer computation of the deliverable amount through
these channels (I tested this with a channel with 21M bitcoin) would
fail due to an integer overflow in the function `amount_msat_sub_fee`,
21M BTC = 21 x 10^17 msat, which overflows u64 integers when multiplied
by 10^6. We have fixed `amount_msat_sub_fee` operations, so that it
doesn't overflow.
Basically we had the following integer operation:
```
floor(x * a/b)
```
where `a<b` and `a=10^6`, so the result fits in u64. The problem is that we first compute `a*x` and then divide by `b`.
`a*x` can overflow.
We fixed the operation by splitting `x = q_x * b + r_x` where `q_x = …
> askrene: fix integer overflow for dummy channels

- doc/lightning-reckless.1.md
- tests/test_reckless.py
- tools/reckless
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 05TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 12th_, RC2 on _May 16th_, ...
>
> The final release is on MAY 20TH.
Adds the ability to update all reckless-installed plugins, or a single one at a time.  For repository sources, reckless avoids unnecessarily updating if the latest commit has not advanced from the installed version.  The installed version and source are obtained from the .metadata file of the installed plugin.
> Reckless: Add an `update` command

- lightningd/plugin.c
- tests/test_cln_rs.py
- tests/test_misc.py
- tests/test_pay.py
- tests/test_plugin.py
- tests/test_xpay.py
Previously, the code utilized JSON-encoded text to pass log messages to the log_() function, resulting in new lines being printed to the log as '\n'. This commit addresses this issue by unescaping and splitting the log message into lines, with each non-empty line being logged separately.
It is deemed acceptable to pass non-printable characters to log_() since they are replaced with "?" in the logv() function, invoked by log_(). Therefore, leaving lines JSON unescaped is permissible.
It's important to note that only the last log_() call may have call_notifier set to true. This adjustment is crucial to prevent Python tracebacks complaining about a broken pipe after lightningd exits.
Fixes: https://github.com/ElementsProject/lightning/issues/4912
Tested:
```
./lightningd/lightningd …
```
> Enhance plugin_log_handle to accommodate multi-line messages

- channeld/channeld.c
Fix a typo where the commit sig message ordering was not handled correctly for the first element.
We need to use msg_batch[0] to get the first post-sorted result instead of the original msg.
Changelog-None
> splice: Test fix for test crash splice

- Makefile
- contrib/msggen/msggen/schema.json
- doc/schemas/plugin.json
- doc/schemas/splice_init.json
- tools/fromschema.py
- tools/md2man.sh
Lowdown requires a blank line before all preformatted blocks, or it doesn't recognize them. `tools/md2man.sh` contained some ad-hoc efforts at fixing up some locations where these required blank lines are absent from the output of `tools/fromschema.py`, but it missed some. Instead of playing Whack-a-Mole, use a blanket sed expression to ensure that a blank line precedes _every_ opening \`\`\`.
`esc_underscores(…)` in `tools/fromschema.py` did not work correctly on strings containing an odd number of backticks, notably the \`\`\` delimiters surrounding preformatted text blocks. Specifically, it was dropping the last backtick since none of the alternatives in the regex matched it. Add a new alternative that matches a whole preformatted block as a single unit.
`output_member(…)` in …
> doc: properly handle preformatted blocks

- channeld/channeld.c
- closingd/closingd.c
- gossipd/gossmap_manage.c
- lightningd/chaintopology.c
- lightningd/channel.c
- lightningd/channel.h
- lightningd/channel_control.c
- lightningd/channel_control.h
- lightningd/channel_gossip.c
- lightningd/channel_gossip.h
- lightningd/coin_mvts.c
- lightningd/coin_mvts.h
- lightningd/dual_open_control.c
- lightningd/gossip_control.c
- lightningd/gossip_control.h
- lightningd/lightningd.c
- lightningd/lightningd.h
- lightningd/opening_common.c
- lightningd/opening_control.c
- lightningd/options.c
- lightningd/peer_control.c
- lightningd/peer_control.h
- lightningd/peer_htlcs.c
- lightningd/peer_htlcs.h
- lightningd/test/run-find_my_abspath.c
- tests/test_gossip.py
- wallet/test/run-wallet.c
~(Based on #8135)~ Merged into master
I tried modifying our state machine to allow us to send (as allowed in the latest spec revisions) announcement_signatures before 6 blocks have passed.  However, our state machine did not capture the entire state, so it proved fragile.  The result is a rework on the state machine to be more robust.
> Channel gossip rework

- channeld/channeld.c
Eclair only sets `batch_size` and `funding_txid` when its a batch larger than 1.
Adjust how we send and what we expect to receive to match this.
Changelog-None
> splice: Adjust `batch_size` TLV to match Eclair’s

- common/bolt11.c
- common/test/run-bolt11.c
This PR adds validation of public keys in BOLT11 routing hints to prevent processing of malformed public keys. Without this validation, invalid public keys could be accepted.
> common/bolt11: validate public keys in routing hints

- tools/repro-build.sh
The reproducible build is currently failing on Ubuntu Noble, causing the daily `Repro Build Nightly` GitHub action to fail and triggering email notifications.
This update resolves the issue by adjusting the default sqlite3 version and checksums to match the packages now available in Noble, allowing the image to build successfully.
> ci: Fix noble repro build by updating sqlite3 version and shasums

- CHANGELOG.md
The TLV numbers for splicing were used by the upgrade protocol, and we always demarshal TLVs:
```
rusty@rusty-Framework:~/devel/cvs/lightning ((v25.02.1))$ ./devtools/decodemsg 00883d448f5a4d2d82c861a1e60ba317f5c848989d8c92f65833ff85cc82cb96adf500000000000000c600000000000000c559ebae46ed6f64c3e7c0005494bc684a630223d4b942a7e09b76742727b863cc02aac24eb41bbcfd77cb2e75f51bc5d298a6862cd7c2478268aa67572d8a08311801203d448f5a4d2d82c861a1e60ba317f5c848989d8c92f65833ff85cc82cb96adf503203d448f5a4d2d82c861a1e60ba317f5c848989d8c92f65833ff85cc82cb96adf5
WIRE_CHANNEL_REESTABLISH:
channel_id=3d448f5a4d2d82c861a1e60ba317f5c848989d8c92f65833ff85cc82cb96adf5
next_commitment_number=198
next_revocation_number=197
your_last_per_commitment_secret=59ebae46ed6f64c3e7c0005494bc684a630223d4b942a7e09b76742727b863cc …
```
> CHANGELOG.md: warn that spec compliance mean we broke splicing.

- lightningd/plugin.c
Apparently clboss gives us \u UTF codes.  We don't support that (use UTF-8 directly)
```
126	../sysdeps/x86_64/multiarch/strlen-vec.S: No such file or directory.
(gdb) bt
label=label@entry=0x63e2f9604db9 "char *[]") at ccan/ccan/tal/str/str.c:137
complete=complete@entry=0x7ffe9090b0f6, destroyed=destroyed@entry=0x7ffe9090b0f7) at lightningd/plugin.c:773
```
Reported-by: Ken Sedgwick
Fixes: #8338
Changelog-None: broken in this release
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 05TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 12th_, RC2 on _May 16th_, ...
>
> The final release is on MAY 20TH.
> lightningd: fix log crash on weird escape lines from plugin.

- tests/test_closing.py
- wallet/wallet.c
This seems to have been inadvertently omitted in the recent closed channel refactor.
Fixes: #8346
Changelog-None: Changed this release.
> [!IMPORTANT]
>
> 25.05 FREEZE MAY 05TH: Non-bugfix PRs not ready by this date will wait for 25.08.
>
> RC1 is scheduled on _May 12th_, RC2 on _May 16th_, ...
>
> The final release is on MAY 20TH.
> wallet: initialize previously closed channels

- ccan/README
- ccan/ccan/fdpass/fdpass.c
- ccan/ccan/time/test/run-monotonic.c
- ccan/ccan/time/time.h
Also gets some new timemono helpers, but we don't use them (yet).
Changelog-Fixed: Compilation on FreeBSD.
Closes: https://github.com/ElementsProject/lightning/issues/7758
> ccan: update for FreeBSD compile fixes.

- tests/test_closing.py
With recent changes, particularly using postgres, we can finish the HTLC before we force close, so the test fails.  Insert an explicit hangup here so we reliably get the result we expect:
```
@pytest.mark.parametrize("anchors", [False, True])
@unittest.skipIf(TEST_NETWORK != 'regtest', 'elementsd anchors not supportd')
def test_anchorspend_using_to_remote(node_factory, bitcoind, anchors):
"""Make sure we can use `to_remote` output of previous close to spend anchor"""
l4_opts = {}
if anchors is False:
l4_opts['dev-force-features'] = "-23"
l1, l2, l3, l4 = node_factory.get_nodes(4, opts=[{},
{},
{'disconnect': ['-WIRE_UPDATE_FULFILL_HTLC']},
l4_opts])
node_factory.join_nodes([l4, l2])
l4.rpc.pay(l2.rpc.invoice(100000000, 'test', 'test')['bolt11'])
>       wait_for(lambda: …
```
> pytest: fix flake in test_anchorspend_using_to_remote

- doc/contribute-to-core-lightning/release-checklist.md
> docs: Fix script used to update versions in point release instructions

- doc/beginners-guide/beginners-guide.md
- doc/developers-guide/app-development.md
- doc/developers-guide/app-development/commando-plugin.md
- doc/developers-guide/app-development/json-rpc.md
- doc/developers-guide/deprecated-features.md
- doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
- doc/developers-guide/plugin-development/hooks.md
- doc/getting-started/advanced-setup/bitcoin-core.md
- doc/getting-started/getting-started/configuration.md
- doc/node-operators-guide/analytics.md
- doc/node-operators-guide/faq.md
- Fixed RPC links after removing `lightning-` prefix from commands list
- Updated Commando plugin doc after `commando-rune`, `commando-blacklist` and `commando-listrunes` removal
- Fixed `commando` and `deprecations` pages.
> Documentation fixes

- contrib/msggen/msggen/schema.json
- doc/schemas/listpays.json
- doc/schemas/listsendpays.json
- doc/schemas/sendonion.json
- tests/test_pay.py
Need to specify exactly when this field is missing: turns out is "never" is.
Also, we noticed that sendonion does not refer to the modern coolness of injectpaymentonion!
Fixes: https://github.com/ElementsProject/lightning/issues/6909
Closes: https://github.com/ElementsProject/lightning/pull/8144
Changelog-None: doc only
> Document listsendpays amount msat better

- plugins/sql.c
Before vs after:
- `forwards` indexed by `in_channel and in_htlc_id` (see lightning-listforwards(7))
- `forwards` indexed by `in_channel` and `in_htlc_id` (see lightning-listforwards(7))
And:
- `htlcs` indexed by `short_channel_id and id` (see lightning-listhtlcs(7))
- `htlcs` indexed by `short_channel_id` and `id` (see lightning-listhtlcs(7))
Changelog-None
> plugins/sql: fix doc formatting for tables with multiple indices.

- plugins/src/lib.rs
> cln-plugin: don't panic if notification handler returns error

- plugins/askrene/askrene.c
Add log information about the runtime of getroutes in the form
```
get_routes completed in X ms
```
Is this proper naming?
The string should have a unique signature to be able to extract it with regex patterns.
> askrene: add runtime of getroutes to the logs

- plugins/askrene/askrene.c
- plugins/askrene/mcf.c
- plugins/askrene/mcf.h
This PR only does a bit of refactoring to askrene.
I would like to add the possibility to switch algorithms in askrene.
This would not be available from the user interface, it is just for developers.
It would allow us to test different algorithms for experimenting performance and reliability
without risking breaking the existing code.
This PR sets the stage for switching between multiple MCF algorithms.
This PR is built on top of #7932.
> Askrene algorithm switcher

- tests/test_closing.py
- tests/test_connection.py
- tests/test_splicing.py
We get a unilateral close if the blocks come too fast:
```
>       l2.daemon.wait_for_log(r'CHANNELD_AWAITING_SPLICE to CHANNELD_NORMAL')
tests/test_splicing.py:96:
...
>                   raise TimeoutError('Unable to find "{}" in logs.'.format(exs))
E                   TimeoutError: Unable to find "[re.compile('CHANNELD_AWAITING_SPLICE to CHANNELD_NORMAL')]" in logs.
```
Here:
```
lightningd-2 2025-07-08T12:08:30.430Z DEBUG   lightningd: Adding block 114: 542499dfc63bc94c0ba0a3d81bdaff07ab73ba9aebddd4c2ae4b2e0c1e8bd15f
...
lightningd-2 2025-07-08T12:08:30.459Z UNUSUAL 0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-chan#1: Peer permanent failure in CHANNELD_AWAITING_SPLICE: Fulfilled HTLC 1 RCVD_REMOVE_REVOCATION cltv11 4 hit deadline (reason=protocol)
lightningd-2 …
```
> pytest: fix flakes in test_splicing_rbf, test_reconnect_signed, test_htlc_no_force_close

- common/amount.c
- common/amount.h
- common/test/run-amount.c
- plugins/askrene/mcf.c
- tests/test_askrene.py
- tests/test_xpay.py
This PR depends on #8299 and supersedes #8314.
With this PR I want to make a small improvement to the MCF solver in askrene.
First: I would like to constrain the number of flow units to 1000 by setting the accuracy of the solver
to the total payment amount divided by 1000. Some MCF algorithms like "successive shortest path" (SSP)
have theoretical complexity bounds that depend on that number.
Note: the 1000 number is arbitrary, the smaller it is we may reduce the solver's runtime but we lose
a accuracy.
Second: I would like to prune the set of arcs in the network. I can achieve this by setting a limit to the sum
of the arc capacities that correspond to the same channel to U, the maximum number of flow units
in the payment. Notice that due to the piece-wise linearization of the channel
cost …
> Askrene: prune and cap

- doc/lightningd-config.5.md
- doc/lightningd-rpc.7.md
> doc: fix typo and missing `ws:` prefix documentation.

- Makefile
- configure
On macOS, libbacktrace was failing to find debug information due to:
1. Debug symbols not being properly linked with dsymutil
2. Apple Clang 17.0.0 generating DWARF 5 which libbacktrace couldn't parse
In this commit we address both issues:
Debug symbol accessibility:
- Add dsymutil integration in Makefile to properly link debug symbols
DWARF format compatibility:
- Force -gdwarf-4 instead of default DWARF 5 to avoid "DW_FORM_addrx value out of range" errors
- Update the version of libbacktrace being used in core-lightning (see [commit](https://github.com/ianlancetaylor/libbacktrace/commit/d48f84034ce3e53e501d10593710d025cb1121db))
Changelog-added: libbacktrace works with macOS
Example stacktrace:
```
sangbida@Sangbidas-MacBook-Pro lightning % ./lightningd/lightningd
lightningd: FATAL …
```
> configure: Add macOS-specific debug flags for libbacktrace compatibility

- configure
- db/db_sqlite3.c
- plugins/sql.c
- tools/headerversions.c
- wallet/db.c
Oldest supported distro is RHEL8, so make it >= 3.26.  Document that and enforce it.
> Sqlite updates

- contrib/msggen/msggen/schema.json
- doc/schemas/sql-template.json
- plugins/sql.c
- tests/test_plugin.py
Changelog-Added: Plugins: `sql` also supports functions `json_object(key1, value1, ...)` to construct JSON objects and `json_group_array(value)` to aggregate rows into JSON array.
Security Considerations
- No new SQL injection risks: Functions only process explicitly provided column values (no arbitrary string parsing).
- Explicit column requirements: Wildcards (*) are not supported, all fields must be named (e.g., json_object('peer_id', id)).
- Permission-bound data access: Functions adhere to the same table/row permissions as the underlying query.
Performance Impact
- Optimized native execution: Leverages SQLite’s built-in JSON1 extension (when available) for efficiency.
- Moderate CPU overhead: Complex nesting may impact performance on large datasets but still faster than …
> Add `json_object` and `json_group_array` support in sql plugin

- common/bolt11.c
- common/json_parse.c
- common/json_parse_simple.c
The `strto{l,ul,ull}` functions do not set `errno` upon a successful return, so a successful return from a maximally valued input could be misinterpreted as an overflow error if `errno` happened already to be set to `ERANGE` before the call. To guard against this edge case, always set `errno` to zero before calling these functions if checking `errno` afterward.
> common: set `errno=0` before calling `strto{l,ul,ull}`

- doc/developers-guide/plugin-development/hooks.md
- lightningd/dual_open_control.c
- lightningd/opening_control.c
- openingd/dualopend.c
- openingd/dualopend_wire.csv
- openingd/openingd.c
- openingd/openingd_wire.csv
- tests/plugins/openchannel_hook_accepter.py
- tests/test_plugin.py
An obvious omission!
Changelog-Added: Plugins: `openchannel` and `openchannel2` hooks now expose the `channel_type` field for the offered channel.
Closes: #8379
> lightningd: add channel_type to openchannel & openchannel2 hooks.

- plugins/offers_invreq_hook.c
In practice, we were too strict.  Here's Phoenix paying my node via another node:
```
2025-08-25T13:57:53.311Z DEBUG   02...-chan#216: Failing HTLC because of an invalid payload (TLV 10 pos 103): cltv_expiry 911816 > payment_constraint 911721
```
We add 6 blocks, but this is supposed to be the *max* allowed.  Increase it to 1008, to allow shadow padding.  Here are the CLTV delays across advertized channels in the network: most are far less than this:
Count   Delay
...
899 18
602 20
...
4352 34
...
15256 40
...
26793 80
...
9527 100
...
14303 144
...
105 288
...
12 500
...
1 1900
1 2016
Fixes: https://github.com/ElementsProject/lightning/issues/7718
> offers: loosen payment_constraints on invoices' blinded paths.

- uv.lock
This wasn't committed, so CI is failing.
Changelog-None
> uv.lock: update for rc3.

- CHANGELOG.md
Sorry :(
We chose to update our own few custom plugin notifications by manually creating the deprecated fields and adding the new ones, rather than having lightningd fix them up.  But this didn't apply to other plugins which might issue their own notifications: in particular, this hit @daywalker90.
Simply documenting this is lazy, but we're close to release and I don't expect anyone else to be affected.
Reported-by: @daywalker90
Changelog-None
Fixes: #8478
> CHANGELOG.md: note that we broke custom rust notifications.

- common/coin_mvt.c
- common/coin_mvt.h
- common/test/run-coin_mvt.c
- contrib/msggen/msggen/schema.json
- doc/schemas/listchainmoves.json
- plugins/bkpr/account.c
- wallet/account_migration.c
Fixes: #8485 
Changelog-None: broken in this release
> Fix accounting migration2

- tools/build-release.sh
1. Run uv venv.
2. Do make under `uv run`
Changelog-None
> Release: fix build inside Fedora

- common/daemon_conn.c
Changelog-Fixed: Use the correct context in `daemon_conn_new_()` by allocating `struct daemon_conn` with `ctx` instead of `NULL`.
This ensures proper ownership and cleanup of `daemon_conn` objects, avoiding memory leaks.
CC: @morehouse
> common: fix dangling memory allocation in `daemon_conn_new_()`

- plugins/bcli.c
Replaced custom wait logic with the `-rpcwait` flag in bitcoin-cli to handle waiting for bitcoind to warm up. Added a timer to print the warm-up message only if bitcoind doesn't start serving RPC calls within `30 seconds`. 
This simplifies the code and ensures that errors unrelated to warmup are passed up directly without additional checks.
Fixes: #3505
> plugins/bcli: use -rpcwait to simplify waiting for bitcoind to warm up

- Cargo.lock
- Dockerfile
- plugins/bip353-plugin/Cargo.toml
Cargo utilizes `git ls-remote` to resolve git dependencies specified by commit hashes. GitHub only advertises commits that are reachable from branches, tags, or PR references. The `bip353-plugin` was referencing an orphaned commit in the `bitcoin-payment-instructions` dependency that was unreachable through any advertised reference. This is resolved by installing the tarball release `v0.5.0`.
> docker: Dockerfile fixes after poetry to uv migration

- contrib/pyln-testing/pyln/testing/utils.py
Can we please get a pyln-testing v25.9.1 release with this change? That way it stays compatible with older CLN versions without having to rewrite every test and disable it manually.
> pyln-testing: set 'dev-save-plugin-io' only on CLN v25.09 and later

- lightningd/datastore.c
I'm noticing a lot of entries in the `debug` log as such:
`439Z DEBUG   lightningd: Printing`
There doesn't seem to be any other helpful information. Assumption is that this was a debugging exercise that wasn't fully removed, but I could be wrong. This PR removes that line in the `listdatastore` RPC.
Changelog-None
> [!IMPORTANT]
>
> 25.12 FREEZE October 27th: Non-bugfix PRs not ready by this date will wait for 26.03.
>
> RC1 is scheduled on _November 10th_
>
> The final release is scheduled for December 1st.
> fix: Remove "Printing" (and related) from listdatastore debug log.

- tools/repro-build.sh
Changelog-Fixed: Reproducible build for Ubuntu noble by updating sqlite3 version and shasums.
> ci: Update sqlite3 version and shasums for noble repro build

- common/json_param.c
- common/json_parse_simple.c
- common/json_parse_simple.h
The `json_str_to_u64()` function contains incorrect logic. It chops one character off of the beginning and end of the JSMN token and then parses the remainder as a `u64`, but `JSMN_STRING` tokens already do not include the enclosing quotation marks, so `json_str_to_u64()` would actually parse the JSON string `"1234"` into the integer 23. Oops! Also note that it would simply fail on all input strings shorter than two characters since `tok->end` would wind up *before* `tok->start`.
Just drop the function entirely. It was only used in one place, and that place explicitly doesn't care whether its input is a JSON number or a numeric string, and it was already calling `json_to_u64()` as an alternative, and that function already accepts both JSON strings and JSON numbers as input, so the call to …
> common/json_parse_simple: drop redundant and wrong `json_str_to_u64()`

- tests/fuzz/fuzz-funder-policy.c
```
tests/fuzz/fuzz-funder-policy.c:32:	amt.satoshis %= (MAX_SATS + 1);
tests/fuzz/fuzz-funder-policy.c:132:				total.satoshis, tcase->max_channel_size.satoshis);
tests/fuzz/fuzz-funder-policy.c:140:				our_funds.satoshis, tcase->policy.per_channel_min.satoshis);
tests/fuzz/fuzz-funder-policy.c:145:				our_funds.satoshis, tcase->policy.per_channel_max.satoshis);
tests/fuzz/fuzz-funder-policy.c:155:				our_funds.satoshis, tcase->available_funds.satoshis,
tests/fuzz/fuzz-funder-policy.c:156:				tcase->policy.reserve_tank.satoshis);
tests/fuzz/fuzz-funder-policy.c:161:			tcase->policy.reserve_tank.satoshis, tcase->available_funds.satoshis,
tests/fuzz/fuzz-funder-policy.c:162:			our_funds.satoshis);
make: *** [Makefile:577: check-amount-access] Error 1
```
Changelog-None
> build: suppress amount checking in fuzzing tests.

- ccan/README
- ccan/ccan/io/io.c
- connectd/connectd.c
- connectd/connectd.h
- connectd/connectd_wire.csv
- connectd/multiplex.c
- connectd/multiplex.h
- lightningd/connect_control.c
- lightningd/dual_open_control.c
- lightningd/notification.c
- lightningd/notification.h
- lightningd/peer_control.c
- lightningd/peer_control.h
- lightningd/test/run-invoice-select-inchan.c
- openingd/dualopend.c
- openingd/dualopend_wire.csv
- tests/test_connection.py
- tests/test_opening.py
- wallet/test/run-wallet.c
One issue we have in CI is reconnection races: if an incoming connection arrives while an outgoing one is negotiated, we close the outgoing one and issue a disconnect, which fails any connect attempts.
By sending a "reconnected" message instead of disconnect/connect we can avoid disturbing in-progress connection attempts which happens in CI quite a bit.
Changelog-None
> connectd: simplify logic, and add a "reconnected" message.

- .github/workflows/readme-rpc-sync.yml
RPC documentation is not syncing on readme server with error `uv: command not found`.
> workflow: Add uv installation step

- contrib/pyln-testing/pyln/testing/utils.py
- tests/test_cln_lsps.py
- tests/test_cln_rs.py
- tests/test_clnrest.py
- tests/test_connection.py
* `tests/test_cln_lsps.py::test_lsps0_listprotocols`
* `tests/test_clnrest.py`
* `tests/test_connection.py::test_wss_proxy`
> tests: skip certain tests if `RUST` is not enabled

- lightningd/lightningd.c
- lightningd/test/run-find_my_abspath.c
- tests/test_misc.py
- tests/test_wallet.py
- wallet/wallet.c
- wallet/wallet.h
> Fix latency spike when old high-traffic channels close.

- contrib/pyln-testing/pyln/testing/utils.py
The `bitcoin.rpc.DEFAULT_HTTP_TIMEOUT` of 30 seconds may not be enough time to generate a block when the test machine is under load. Pass `pyln.testing.utils.TIMEOUT` to `bitcoin.rpc.RawProxy` to allow extra time: currently 60 seconds by default or 180 seconds if `SLOW_MACHINE` is set.
Changelog-None
> pyln-testing: pass timeout to `BitcoinProxy`

- lightningd/plugin.c
- lightningd/plugin.h
We need to remove the feature-bits set after a plugins `getmanifest` response when the `init` response disables the plugin.
Fixes tests on #8227 that fail due to feature-bit assumptions.
> Don't set feature-bits when plugin is disabled
